CREATE SEQUENCE  "BMTB_NOTE_FLOW_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER NOCYCLE ;
CREATE TABLE BMTB_NOTE_FLOW (
  NOTE_FLOW_NO NUMBER(18) NOT NULL,
  NOTE_NO NUMBER(18) NOT NULL,
  FROM_STATUS VARCHAR2(1) NOT NULL, -- N = NEW, P = PENDING, A = APPROVED, R = REJECTED
  TO_STATUS VARCHAR2(1) NOT NULL, -- N = NEW, P = PENDING, A = APPROVED, R = REJECTED
  USER_ID NUMBER(10) NOT NULL,
  REMARKS VARCHAR2(500),
  FLOW_DT TIMESTAMP NOT NULL,
  VERSION NUMBER(9,0) DEFAULT 0,
  CONSTRAINT BMTB_NOTE_FLOW_PK PRIMARY KEY(NOTE_FLOW_NO),
  CONSTRAINT BMTB_NOTE_FLOW_FK1 FOREIGN KEY(NOTE_NO) REFERENCES BMTB_NOTE(NOTE_NO),
  CONSTRAINT BMTB_NOTE_FLOW_FK2 FOREIGN KEY(USER_ID) REFERENCES SATB_USER(USER_ID)
);
CREATE INDEX BMTB_NOTE_FLOW_N1 ON BMTB_NOTE_FLOW (NOTE_NO);

--SATB Resource
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION)
VALUES (702,110,'Approve Credit/Debit Note','U','/billing/note/search_note_req.zul',3,'Approve Credit/Debit Note','Y',0);