SET PAGES 5000
SET LINE  10000
SET TRIMSPOOL ON
set echo on

column dt new_value new_dt
column ext new_value new_ext
select  sys_context('userenv','instance_name') || '_aprP30IssueLogs_ddl_01_' || to_char(sysdate,'YYYYMMDDHH24MISS') dt,'.txt' ext from dual;
SPOOL  &new_dt&new_ext
set define off
alter session set current_schema=ibssys;



/*
 * This is for account management
 */

ALTER TABLE AMTB_ACCOUNT ADD (E_INVOICE_EMAIL_FLAG varchar2(1 char) DEFAULT 'N');
COMMENT ON COLUMN AMTB_ACCOUNT.E_INVOICE_EMAIL_FLAG IS 'E Invoice Email Flag';

ALTER TABLE AMTB_ACCOUNT ADD (E_INVOICE_EMAIL varchar2(500 char));
COMMENT ON COLUMN AMTB_ACCOUNT.E_INVOICE_EMAIL IS 'E Invoice Email';

ALTER TABLE AMTB_ACCOUNT ADD (E_INVOICE_EMAIL_SUBJECT varchar2(500 char));
COMMENT ON COLUMN AMTB_ACCOUNT.E_INVOICE_EMAIL_SUBJECT IS 'E Invoice Email Subject';
          
ALTER TABLE AMTB_ACCOUNT ADD (E_INVOICE_EMAIL_ZIP_FLAG varchar2(1 char) DEFAULT 'N');
COMMENT ON COLUMN AMTB_ACCOUNT.E_INVOICE_EMAIL_ZIP_FLAG IS 'E Invoice Email Zip Flag';

ALTER TABLE AMTB_ACCOUNT ADD (E_INVOICE_EMAIL_ATTACHMENT varchar2(1 char) DEFAULT 'O');
COMMENT ON COLUMN AMTB_ACCOUNT.E_INVOICE_EMAIL_ATTACHMENT IS 'E Invoice Email Attachment';

ALTER TABLE AMTB_ACCOUNT ADD (E_INVOICE_EMAIL_PAGE varchar2(1 char) DEFAULT 'A');
COMMENT ON COLUMN AMTB_ACCOUNT.E_INVOICE_EMAIL_PAGE IS 'E Invoice Email Page';

/*
 * This is cleanup UAT server
 */

UPDATE AMTB_ACCOUNT SET E_INVOICE_EMAIL_FLAG = 'N' WHERE (E_INVOICE_EMAIL = '' OR E_INVOICE_EMAIL IS NULL);

/*
 * This is for role management
 */

INSERT INTO SATB_RESOURCE (RSRC_ID, PAR_RSRC_ID, RSRC_NAME, RSRC_TYPE, URI, SEQUENCE, DISPLAY_NAME, DISPLAY, VERSION)
VALUES((SELECT MAX(RSRC_ID)+1 FROM SATB_RESOURCE), (SELECT RSRC_ID FROM SATB_RESOURCE WHERE RSRC_NAME = 'Manage Accounts'), 
'Edit eInvoice Email', 'U', '/acct/acct/eInvoiceEmail.zul', (SELECT MAX(SEQUENCE)+1 FROM SATB_RESOURCE WHERE RSRC_NAME = 'Manage Accounts'), 
'Edit eInvoice Email', 'N', 0);

/*
 * This is for master list management
 */

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION,MASTER_GROUPING)
VALUES ((SELECT MAX(MASTER_NO)+1 FROM MSTB_MASTER_TABLE), 'EERL', 'CONT', NULL, 'Please refer attachment in this email.', 'A', 0, 'Email');

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION,MASTER_GROUPING)
VALUES ((SELECT MAX(MASTER_NO)+1 FROM MSTB_MASTER_TABLE), 'EERL', 'EMAIL', NULL, 'reny.ho@wizvision.com;reny.ho@vision.com', 'A', 0, 'Email');

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION,MASTER_GROUPING)
VALUES ((SELECT MAX(MASTER_NO)+1 FROM MSTB_MASTER_TABLE), 'EERL', 'SUBJ', NULL, 'E Invoice Email PDF Generation', 'A', 0, 'Email');

commit;