-- Add Karhoo Payment Type & Acquirer

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,MASTER_VALUE,MASTER_STATUS,VERSION,INTERFACE_MAPPING_VALUE,MASTER_GROUPING) 
values (MSTB_MASTER_TABLE_SQ1.nextVal,'APT','K','KARHOO','A',0,'KARHOO','Others');

insert into mstb_acquirer (acquirer_no, name, created_dt, created_by) values (mstb_acquirer_sq1.nextval, 'KARHOO', sysdate, 'TestDomain\system');

insert into mstb_acquirer_mdr 
(
mdr_no,
acquirer_no,
effective_date,
rate,
created_dt,
created_by
) 
values 
(
MSTB_ACQUIRER_MDR_SQ1.nextval,
(select acquirer_no from mstb_acquirer where name='KARHOO'),
sysdate,
0,
sysdate,
'TestDomain\system'
);


-- Add to masterlist
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,MASTER_VALUE,MASTER_STATUS,VERSION,INTERFACE_MAPPING_VALUE,MASTER_GROUPING) 
values (MSTB_MASTER_TABLE_SQ1.nextVal,'COMM','PCT','PERCENTAGE COMMISSION (%)','A',0,null,'Others');

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,MASTER_VALUE,MASTER_STATUS,VERSION,INTERFACE_MAPPING_VALUE,MASTER_GROUPING) 
values (MSTB_MASTER_TABLE_SQ1.nextVal,'COMM','FIX','FIXED VALUE BUSINESS PARTNER COMMISSION ($)','A',0,null,'Others');


-- Add commission amt, type & value to tmtb Non billable
ALTER TABLE TMTB_NON_BILLABLE_TXN ADD (COMMISSION_AMT decimal(12,2) NULL);
ALTER TABLE TMTB_NON_BILLABLE_TXN ADD (COMMISSION_TYPE varchar2(5) NULL);
ALTER TABLE TMTB_NON_BILLABLE_TXN ADD (COMMISSION_VALUE decimal(12,2) NULL);

COMMENT ON COLUMN TMTB_NON_BILLABLE_TXN.COMMISSION_AMT IS 'Commission Amount ($)';
COMMENT ON COLUMN TMTB_NON_BILLABLE_TXN.COMMISSION_TYPE IS 'Commission Type (Pct or Fix) value was used';
COMMENT ON COLUMN TMTB_NON_BILLABLE_TXN.COMMISSION_VALUE IS 'Commission Value (the % Commission or fix value that was used for calculation for this txn)';


-- Create Commission SEQUENCE
CREATE SEQUENCE  "MSSQ_COMMISSION_NO"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 2 CACHE 10 NOORDER  NOCYCLE;

-- Create Mstb Acquirer Payment Commission Table
CREATE TABLE MSTB_ACQUIRER_PYMT_COMM (
	COMMISSION_NO NUMBER(8) NOT NULL,
	COMMISSION_VALUE NUMBER(12,2) NOT NULL,
	COMMISSION_TYPE VARCHAR2(5),
	EFFECTIVE_DT_FROM TIMESTAMP NOT NULL,
	EFFECTIVE_DT_TO TIMESTAMP,
	PYMT_TYPE_NO NUMBER(8) NOT NULL,
	CREATED_DT timestamp, 
    CREATED_BY varchar2(80), 
    UPDATED_DT timestamp, 
    UPDATED_BY varchar2(80)
);

COMMENT ON COLUMN MSTB_ACQUIRER_PYMT_COMM.COMMISSION_VALUE IS 'Commission Value';
COMMENT ON COLUMN MSTB_ACQUIRER_PYMT_COMM.COMMISSION_TYPE IS 'Commission Type (Pct or Fix) value was used';
COMMENT ON COLUMN MSTB_ACQUIRER_PYMT_COMM.EFFECTIVE_DT_FROM IS 'Effective Date From';
COMMENT ON COLUMN MSTB_ACQUIRER_PYMT_COMM.EFFECTIVE_DT_TO IS 'Effective Date To';

