ALTER TABLE AMTB_APPLICATION add INVOICE_FORMAT varchar2(1 char);

ALTER TABLE AMTB_APPLICATION add INVOICE_SORTING varchar2(1 char);

ALTER TABLE AMTB_APPLICATION add GOVT_E_INVOICE_FLAG varchar2(1 char) DEFAULT 'N';

ALTER TABLE AMTB_APPLICATION add BUSINESS_UNIT_MASTER_NO NUMBER(8,0);