SET PAGES 5000
SET LINE  10000
SET TRIMSPOOL ON
set echo on

column dt new_value new_dt
column ext new_value new_ext
select  sys_context('userenv','instance_name') || '_janIssueLogs_ddl_' || to_char(sysdate,'YYYYMMDDHH24MISS') dt,'.txt' ext from dual;
SPOOL  &new_dt&new_ext
set define off
alter session set current_schema=ibssys;




/*-- 13/12/2016  CR/0216/038 #85 VITAL MASTER ACCESS START */

CREATE TABLE ITTB_CP_MASTER_LOGIN (
	MASTER_LOGIN_NO NUMBER(8) NOT NULL,
	NAME VARCHAR2(80),
	EMAIL VARCHAR2(80) ,
	TELEPHONE VARCHAR2(80) ,
	COMPANY_NAME VARCHAR2(80) ,
	LOGIN_ID VARCHAR2(80),
	CREATED_BY VARCHAR2(40),
	CREATED_DT TIMESTAMP NOT NULL,
	UPDATED_BY VARCHAR2(40),
	UPDATED_DT TIMESTAMP
);

-- Create SEQUENCE
CREATE SEQUENCE  "ITSQ_MASTER_LOGIN_NO"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 2 CACHE 10 NOORDER  NOCYCLE ;

COMMENT ON COLUMN ITTB_CP_MASTER_LOGIN.MASTER_LOGIN_NO IS 'SeqNo';
COMMENT ON COLUMN ITTB_CP_MASTER_LOGIN.NAME IS 'Name';
COMMENT ON COLUMN ITTB_CP_MASTER_LOGIN.EMAIL IS 'Email Address';
COMMENT ON COLUMN ITTB_CP_MASTER_LOGIN.TELEPHONE IS 'Telephone';
COMMENT ON COLUMN ITTB_CP_MASTER_LOGIN.COMPANY_NAME IS 'Company Name';
COMMENT ON COLUMN ITTB_CP_MASTER_LOGIN.LOGIN_ID IS 'Login Id';

CREATE TABLE ITTB_CP_MASTER_TAG_ACCT (
	TAG_ACCOUNT_NO NUMBER(8) NOT NULL,
	MASTER_LOGIN_NO NUMBER(8) NOT NULL,
	CUST_NO VARCHAR2(6) ,
	ACCOUNT_NO NUMBER(8) ,
	ACCOUNT_NAME VARCHAR2(80),
	ACCOUNT_CATEGORY VARCHAR2(4),
	CREATED_BY VARCHAR2(40),
	CREATED_DT TIMESTAMP NOT NULL,
	UPDATED_BY VARCHAR2(40),
	UPDATED_DT TIMESTAMP
);

-- Create SEQUENCE
CREATE SEQUENCE  "ITSQ_TAG_ACCOUNT_NO"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 2 CACHE 10 NOORDER  NOCYCLE ;

COMMENT ON COLUMN ITTB_CP_MASTER_TAG_ACCT.TAG_ACCOUNT_NO IS 'Seq No';
COMMENT ON COLUMN ITTB_CP_MASTER_TAG_ACCT.MASTER_LOGIN_NO IS 'SeqNo of Ittb_Cp_Master_Login';
COMMENT ON COLUMN ITTB_CP_MASTER_TAG_ACCT.ACCOUNT_NAME IS 'Account Name';
COMMENT ON COLUMN ITTB_CP_MASTER_TAG_ACCT.CUST_NO IS 'Cust No';
COMMENT ON COLUMN ITTB_CP_MASTER_TAG_ACCT.ACCOUNT_NO IS 'Account No';
COMMENT ON COLUMN ITTB_CP_MASTER_TAG_ACCT.ACCOUNT_CATEGORY IS 'Account Category';

-- creating seq for Vital Master Login Registration INTERFACE --
CREATE SEQUENCE  "ITSQ_CP_MSTR_REG_REQ_SQ1"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  CYCLE;

/*-- 13/12/2016  CR/0216/038 #85 VITAL MASTER ACCESS END */





/*-- 01/02/2017 CR/0117/047 #131 Add Race to Personal Application START */

--Add to Application
ALTER TABLE AMTB_APPLICATION ADD (MAIN_CONTACT_RACE varchar2(20 char));
COMMENT ON COLUMN AMTB_APPLICATION.MAIN_CONTACT_RACE IS 'Main Contact Race';

-- Add to Amtb Personal Detail
ALTER TABLE AMTB_PERSONAL_DETAIL ADD (MAIN_CONTACT_RACE varchar2(20 char));
COMMENT ON COLUMN AMTB_PERSONAL_DETAIL.MAIN_CONTACT_RACE IS 'Main Contact Race';

/*-- 01/02/2017 CR/0117/047 #131 Add Race to Personal Application END */

spool off
