ALTER TABLE AMTB_ACCOUNT ADD "GOVT_E_INVOICE_FLAG" VARCHAR(1) DEFAULT 'N' NOT NULL;

ALTER TABLE AMTB_ACCOUNT ADD "BUSINESS_UNIT_MASTER_NO" NUMBER(8);
ALTER TABLE AMTB_ACCOUNT ADD CONSTRAINT AMTB_ACCOUNT_FK8 FOREIGN KEY(BUSINESS_UNIT_MASTER_NO) REFERENCES MSTB_MASTER_TABLE(MASTER_NO);
CREATE INDEX AMTB_ACCOUNT_N15 ON AMTB_ACCOUNT (BUSINESS_UNIT_MASTER_NO);

ALTER TABLE BMTB_BILL_GEN_SETUP ADD "GOVT_E_INVOICE_FLAG" VARCHAR(3) DEFAULT 'OFF' NOT NULL;

-- GOVT EINVOICE BILL GEN SETUP, FILE SIZE IN BYTES
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'GEBGS','GEFZ',null,'5000','A',0);
-- GOVT EINVOICE BILL GEN SETUP, MAX NUMBER OF LINES
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'GEBGS','GEML',null,'20000','A',0);

/*
@Geok Hua: Please amend accordingly to add in the BU
*/
-- GOVT EINVOICE Business Unit
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'GEBU','BUA',null,'BU Alpha','A',0);
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'GEBU','BUB',null,'BU Bravo','A',0);
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'GEBU','BUC',null,'BU Charlie','A',0);


create TABLE ITTB_GOVT_EINVOICE_REQ
(
   REQ_NO NUMBER(8) PRIMARY KEY NOT NULL,
   STATUS varchar2(1) NOT NULL,
   FILE_NAME VARCHAR2(80) NOT NULL,
   RETURN_FILE_NAME VARCHAR2(80),
   RETURN_FILE_UPLOAD_DT TIMESTAMP,
   BILL_GEN_REQ_NO NUMBER(8),
   INVOICE_NO_FROM NUMBER(18),
   INVOICE_NO_TO NUMBER(18),
   INVOICE_DATE DATE,
   ACCOUNT_NO NUMBER(8),
   VERSION number(9) DEFAULT 0,
   CREATED_BY varchar2(80),
   CREATED_DT timestamp,
   UPDATED_BY varchar2(80),
   UPDATED_DT timestamp
);
create SEQUENCE ITTB_GOVT_EINVOICE_REQ_SQ1 MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
ALTER TABLE ITTB_GOVT_EINVOICE_REQ ADD CONSTRAINT ITTB_GOVT_EINVOICE_REQ_FK1 FOREIGN KEY (BILL_GEN_REQ_NO) REFERENCES BMTB_BILL_GEN_REQ (REQ_NO) ENABLE;
ALTER TABLE ITTB_GOVT_EINVOICE_REQ ADD CONSTRAINT ITTB_GOVT_EINVOICE_REQ_FK2 FOREIGN KEY (ACCOUNT_NO) REFERENCES AMTB_ACCOUNT (ACCOUNT_NO) ENABLE;
CREATE INDEX ITTB_GOVT_EINVOICE_REQ_N1 ON ITTB_GOVT_EINVOICE_REQ(BILL_GEN_REQ_NO);
CREATE INDEX ITTB_GOVT_EINVOICE_REQ_N2 ON ITTB_GOVT_EINVOICE_REQ(ACCOUNT_NO);

create TABLE ITTB_GOVT_EINVOICE_HDR_DTL
(
   HEADER_NO NUMBER(18) PRIMARY KEY NOT NULL,
   REQ_NO NUMBER(8) NOT NULL,
   BUSINESS_UNIT VARCHAR2(5) NOT NULL,
   INVOICE_NO VARCHAR2(30) NOT NULL,
   INVOICE_DATE DATE NOT NULL,
   PO_NO VARCHAR2(17),
   DELIVERY_ORDER_NO VARCHAR2(30),
   VENDOR_ID VARCHAR2(10) NOT NULL,
   CURRENCY_CODE VARCHAR2(3) NOT NULL,
   FREIGHT_AMT NUMBER(25,2) NOT NULL,
   GST_AMT NUMBER(25,2) NOT NULL,
   GROSS_AMT NUMBER(25,2) NOT NULL,
   ATTENTION_TO VARCHAR2(20) NOT NULL,
   DESCRIPTION VARCHAR2(254) NOT NULL,
   CREDIT_TERM VARCHAR2(5) NOT NULL,
   GST_PERCENTAGE NUMBER(4,2) NOT NULL,
   RETURN_STATUS VARCHAR2(1)
);
create SEQUENCE ITTB_GOVT_EINVOICE_HDR_DTL_SQ1 MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
ALTER TABLE ITTB_GOVT_EINVOICE_HDR_DTL ADD CONSTRAINT ITTB_GOVT_EINVOICE_HDR_DTL_FK1 FOREIGN KEY (REQ_NO) REFERENCES ITTB_GOVT_EINVOICE_REQ (REQ_NO) ENABLE;
CREATE INDEX ITTB_GOVT_EINVOICE_HDR_DTL_N1 ON ITTB_GOVT_EINVOICE_HDR_DTL(REQ_NO);

create TABLE ITTB_GOVT_EINVOICE_LINE_DTL
(
   ID NUMBER(18) PRIMARY KEY NOT NULL,
   HEADER_NO NUMBER(18) NOT NULL,
   LINE_NO NUMBER(5) NOT NULL,
   UNIT_PRICE NUMBER(15,5) NOT NULL,
   QUANTITY NUMBER(15,4) NOT NULL,
   GST_AMT NUMBER(25,2) NOT NULL,
   MERCHANDISE_AMT NUMBER(25,2) NOT NULL,
   DESCRIPTION VARCHAR2(254) NOT NULL
);
create SEQUENCE ITTB_GOVT_EINV_LINE_DTL_SQ1 MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
ALTER TABLE ITTB_GOVT_EINVOICE_LINE_DTL ADD CONSTRAINT ITTB_GOVT_EINV_LINE_DTL_FK1 FOREIGN KEY (HEADER_NO) REFERENCES ITTB_GOVT_EINVOICE_HDR_DTL (HEADER_NO) ENABLE;
CREATE INDEX ITTB_GOVT_EINV_LINE_DTL_N1 ON ITTB_GOVT_EINVOICE_LINE_DTL(HEADER_NO, LINE_NO);