ALTER TABLE ITTB_GOVT_EINVOICE_HDR_DTL ADD (
  RETURN_REMARKS varchar2(254)
);

INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (705,401,'Govt eInvoice','U','Govt eInvoice',13,'Govt eInvoice','Y',0);
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (706,705,'Govt eInvoice Report','U','/report/govt_einv.zul?rsrcId=706',1,'Govt eInvoice Report','Y',0);
INSERT INTO MSTB_REPORT_FORMAT_MAP values (106,706,'CSV');

CREATE INDEX ITTB_GOVT_EINVOICE_HDR_DTL_N2 ON ITTB_GOVT_EINVOICE_HDR_DTL(INVOICE_NO);