INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (703,98,'Create Govt eInv Request','U','/govt_einv/create_request.zul',5,'Create Govt eInv Request','Y',0);

ALTER TABLE ITTB_GOVT_EINVOICE_REQ MODIFY (FILE_NAME null);