SET PAGES 5000
SET LINE  10000
SET TRIMSPOOL ON
set echo on

column dt new_value new_dt
column ext new_value new_ext
select  sys_context('userenv','instance_name') || '_septIssueLogs_ddl_04_' || to_char(sysdate,'YYYYMMDDHH24MISS') dt,'.txt' ext from dual;
SPOOL  &new_dt&new_ext
set define off
alter session set current_schema=ibssys;


/*-- 27/09/2017 CR #171 Virtual CabCharge START */

--Drop previous table. will recreate later.
DROP TABLE PMTB_VIRTUAL_EMAIL;

--drop sequence if have. will recreate later
DROP SEQUENCE "PMSQ_VIRTUAL_CARD_ID";


--Add new Virtual Product Column to PMTB_PRODUCT_TYPE
ALTER TABLE PMTB_PRODUCT_TYPE ADD VIRTUAL_PRODUCT VARCHAR(1) DEFAULT 'N' NOT NULL;
COMMENT ON COLUMN PMTB_PRODUCT_TYPE.VIRTUAL_PRODUCT IS 'Virtual Product Yes No';




-- Pmtb Virtual Email
CREATE TABLE PMTB_VIRTUAL_EMAIL (
	VIRTUAL_EMAIL_NO NUMBER(8) NOT NULL,
	PRODUCT_NO NUMBER(19) NOT NULL,
	REMARKS VARCHAR2(80),
	REQUEST_DATE TIMESTAMP NOT NULL,
	REQUEST_BY VARCHAR2(40),
	UPDATED_DATE TIMESTAMP,
	UPDATED_BY VARCHAR2(40),
	EMAIL_STATUS VARCHAR2(2) DEFAULT 'N' NOT NULL,
	FAIL_REASON VARCHAR2(500)
);

-- Create SEQUENCE
CREATE SEQUENCE  "PMSQ_VIRTUAL_CARD_ID"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 2 CACHE 10 NOORDER  NOCYCLE ;

--Create primary key
ALTER TABLE PMTB_VIRTUAL_EMAIL ADD CONSTRAINT PMPC_VIRT_EMAIL__VIR_CARD_ID PRIMARY KEY(VIRTUAL_EMAIL_NO);

--create index
CREATE INDEX PMIX_VIRT_EMAIL__E_STATUS ON PMTB_VIRTUAL_EMAIL (EMAIL_STATUS);
CREATE INDEX PMIX_VIRT_EMAIL__REQ_DATE ON PMTB_VIRTUAL_EMAIL (REQUEST_DATE);
CREATE INDEX PMIX_VIRT_EMAIL__PROD_NO ON PMTB_VIRTUAL_EMAIL (PRODUCT_NO);
CREATE INDEX PMIX_VIRT_EMAIL__REMARKS ON PMTB_VIRTUAL_EMAIL (REMARKS);

--comments
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.PRODUCT_NO IS 'Product No the email is tag to';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.REMARKS IS 'New Issuance or Renewal or Replacement';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.REQUEST_DATE IS 'Date the virtual product is issued/renew/replace';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.REQUEST_BY IS 'Requested by which person.';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.UPDATED_DATE IS 'Last updated date.';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.UPDATED_BY IS 'last updated by';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.EMAIL_STATUS IS 'S=Success F=Fail N=NotSendYet D=DontSend,Coz Terminated';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.FAIL_REASON IS 'Error/Reason for Fail.';

/*-- 27/09/2017 CR #171 Virtual Cabcharge END */

spool off
