SET PAGES 5000
SET LINE  10000
SET TRIMSPOOL ON
set echo on

column dt new_value new_dt
column ext new_value new_ext
select  sys_context('userenv','instance_name') || '_septIssueLogs_ddl_05_' || to_char(sysdate,'YYYYMMDDHH24MISS') dt,'.txt' ext from dual;
SPOOL  &new_dt&new_ext
set define off
alter session set current_schema=ibssys;


/*-- 03/10/2017 CR #171 Virtual CabCharge START */

--Drop previous table. will recreate later.
DROP TABLE PMTB_VIRTUAL_EMAIL;

--drop sequence if have. will recreate later
DROP SEQUENCE "PMSQ_VIRTUAL_CARD_ID";

-- drop column if have. will recreate later
ALTER TABLE PMTB_PRODUCT_TYPE DROP COLUMN  VIRTUAL_PRODUCT;


--Add new Virtual Product Column to PMTB_PRODUCT_TYPE
ALTER TABLE PMTB_PRODUCT_TYPE ADD VIRTUAL_PRODUCT VARCHAR2(1) DEFAULT 'N' NOT NULL;
COMMENT ON COLUMN PMTB_PRODUCT_TYPE.VIRTUAL_PRODUCT IS 'Virtual Product Yes No';




-- Pmtb Virtual Email
CREATE TABLE PMTB_VIRTUAL_EMAIL (
	VIRTUAL_EMAIL_NO NUMBER(8) NOT NULL,
	PRODUCT_NO NUMBER(19) NOT NULL,
	ACTIONS VARCHAR2(25) NOT NULL,
	REQUEST_DATE TIMESTAMP NOT NULL,
	REQUEST_BY NUMBER(10) NOT NULL,
	UPDATED_DATE TIMESTAMP,
	UPDATED_BY VARCHAR2(40),
	EMAIL_STATUS VARCHAR2(1) DEFAULT 'N' NOT NULL,
	FAIL_REASON VARCHAR2(500)
);

-- Create SEQUENCE
CREATE SEQUENCE  "PMSQ_VIRTUAL_CARD_ID"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 2 CACHE 10 NOORDER  NOCYCLE ;

--Create primary key
ALTER TABLE PMTB_VIRTUAL_EMAIL ADD CONSTRAINT PMPC_VIRT_EMAIL__VIR_CARD_ID PRIMARY KEY(VIRTUAL_EMAIL_NO);

--Create foreign key
ALTER TABLE PMTB_VIRTUAL_EMAIL ADD CONSTRAINT PMFC_VIRT_EMAIL__PROD_NO FOREIGN KEY ("PRODUCT_NO") REFERENCES PMTB_PRODUCT ("PRODUCT_NO") ENABLE;

ALTER TABLE PMTB_VIRTUAL_EMAIL ADD CONSTRAINT PMFC_VIRT_EMAIL__REQ_BY FOREIGN KEY ("REQUEST_BY") REFERENCES SATB_USER ("USER_ID") ENABLE;


-- Create Check Constraints
ALTER TABLE PMTB_VIRTUAL_EMAIL ADD CONSTRAINT PMCC_VIRT_EMAIL__ACTIONS CHECK (ACTIONS IN ('CARD RENEWAL', 'NEW CARD', 'REPLACEMENT', 'CARD LOST REPLACEMENT', 'FAULTY/DAMAGED', 'NEW PREPAID CARD'));

ALTER TABLE PMTB_VIRTUAL_EMAIL ADD CONSTRAINT PMCC_VIRT_EMAIL__E_STATUS CHECK (EMAIL_STATUS IN ('S', 'F', 'N', 'D'));


--create index
CREATE INDEX PMIX_VIRT_EMAIL__E_STATUS ON PMTB_VIRTUAL_EMAIL (EMAIL_STATUS);
CREATE INDEX PMIX_VIRT_EMAIL__REQ_DATE ON PMTB_VIRTUAL_EMAIL (REQUEST_DATE);
CREATE INDEX PMIX_VIRT_EMAIL__PROD_NO ON PMTB_VIRTUAL_EMAIL (PRODUCT_NO);
CREATE INDEX PMIX_VIRT_EMAIL__ACTIONS ON PMTB_VIRTUAL_EMAIL (ACTIONS);
CREATE INDEX PMIX_VIRT_EMAIL__REQ_BY ON PMTB_VIRTUAL_EMAIL (REQUEST_BY);

--comments
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.PRODUCT_NO IS 'Foreign Key of PmtbProduct.Product_No. Product No the email is tag to';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.ACTIONS IS 'NEW CARD, CARD RENEWAL, REPLACEMENT, CARD LOST REPLACEMENT, FAULTY/DAMAGED, NEW PREPAID CARD';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.REQUEST_DATE IS 'Date the virtual product is issued/renew/replace';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.REQUEST_BY IS 'Foreign Key of SATB_USER.USER_ID. Requested by which person.';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.UPDATED_DATE IS 'Last updated date.';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.UPDATED_BY IS 'last updated by';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.EMAIL_STATUS IS 'S=Success F=Fail N=NotSendYet D=DontSend,Coz Terminated';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.FAIL_REASON IS 'Error/Reason for Fail. Error Log Messages';

/*-- 03/10/2017 CR #171 Virtual Cabcharge END */

spool off
