package com.cdgtaxi.ibs.acl.model;
// Generated Mar 18, 2009 1:50:21 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import org.springframework.security.GrantedAuthority;
import org.springframework.security.userdetails.UserDetails;

import com.cdgtaxi.ibs.acl.Constants;
import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.common.model.Creatable;
import com.cdgtaxi.ibs.common.model.Updatable;


/**
 * SatbUser generated by hbm2java
 */

public class SatbUser  implements java.io.Serializable, UserDetails, Auditable, Updatable, Creatable {


    // Fields    

    private Long userId;
    private String loginId;
    private String domain;
    private String password;
    private String name;
    private String email;
    private String status;
    private String locked;
    private String createdBy;
    private Timestamp createdDt;
    private String updatedBy;
    private Timestamp updatedDt;
    private int version;
    private Set<SatbPassword> satbPasswords = new HashSet<SatbPassword>(0);
    private Set<SatbRole> satbRoles = new HashSet<SatbRole>(0);


    // Constructors

    /** default constructor */
    public SatbUser() {
    }

	/** minimal constructor */
    public SatbUser(String loginId, String domain, String name, String status, String locked, int version) {
        this.loginId = loginId;
        this.domain = domain;
        this.name = name;
        this.status = status;
        this.locked = locked;
        this.version = version;
    }
    
    /** full constructor */
    public SatbUser(String loginId, String domain, String password, String name, String email, String status, String locked, String createdBy, Timestamp createdDt, String updatedBy, Timestamp updatedDt, int version, Set<SatbPassword> satbPasswords, Set<SatbRole> satbRoles) {
        this.loginId = loginId;
        this.domain = domain;
        this.password = password;
        this.name = name;
        this.email = email;
        this.status = status;
        this.locked = locked;
        this.createdBy = createdBy;
        this.createdDt = createdDt;
        this.updatedBy = updatedBy;
        this.updatedDt = updatedDt;
        this.version = version;
        this.satbPasswords = satbPasswords;
        this.satbRoles = satbRoles;
    }
    

   
    // Property accessors

    public Long getUserId() {
        return this.userId;
    }
    
    public String getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public String getLocked() {
        return this.locked;
    }
    
    public void setLocked(String locked) {
        this.locked = locked;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }

    public Set<SatbPassword> getSatbPasswords() {
        return this.satbPasswords;
    }
    
    public void setSatbPasswords(Set<SatbPassword> satbPasswords) {
        this.satbPasswords = satbPasswords;
    }

    public Set<SatbRole> getSatbRoles() {
        return this.satbRoles;
    }
    
    public void setSatbRoles(Set<SatbRole> satbRoles) {
        this.satbRoles = satbRoles;
    }
   
    public String getDomain() {
		return domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("loginId").append("='").append(getLoginId()).append("' ");
      buffer.append("domain").append("='").append(getDomain()).append("' ");		
      buffer.append("password").append("='").append(getPassword()).append("' ");			
      buffer.append("name").append("='").append(getName()).append("' ");			
      buffer.append("email").append("='").append(getEmail()).append("' ");			
      buffer.append("status").append("='").append(getStatus()).append("' ");			
      buffer.append("locked").append("='").append(getLocked()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SatbUser) ) return false;
		 SatbUser castOther = ( SatbUser ) other; 
         
		 return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getLoginId()==castOther.getLoginId()) || ( this.getLoginId()!=null && castOther.getLoginId()!=null && this.getLoginId().equals(castOther.getLoginId()) ) )
 && ( (this.getDomain()==castOther.getDomain()) || ( this.getDomain()!=null && castOther.getDomain()!=null && this.getDomain().equals(castOther.getDomain()) ) )
 && ( (this.getPassword()==castOther.getPassword()) || ( this.getPassword()!=null && castOther.getPassword()!=null && this.getPassword().equals(castOther.getPassword()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getLocked()==castOther.getLocked()) || ( this.getLocked()!=null && castOther.getLocked()!=null && this.getLocked().equals(castOther.getLocked()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && (this.getVersion()==castOther.getVersion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getLoginId() == null ? 0 : this.getLoginId().hashCode() );
         result = 37 * result + ( getDomain() == null ? 0 : this.getDomain().hashCode() );
         result = 37 * result + ( getPassword() == null ? 0 : this.getPassword().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getLocked() == null ? 0 : this.getLocked().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + this.getVersion();
         
         
         return result;
   }   

   /* Spring Security - Required methods from implementation of UserDetails */
   public String getUsername() {
       return getLoginId();
   }

   public GrantedAuthority[] getAuthorities() {
	   Set<SatbRole> roles = new HashSet<SatbRole>();
	   
	   for(SatbRole role : this.satbRoles){
		   if(role.getStatus().equals(Constants.STATUS_ACTIVE))
			   roles.add(role);
	   }
	   
	   GrantedAuthority[] authorities = new GrantedAuthority[roles.size()];
	   
	   int index = 0;
	   for(SatbRole role : roles){
		   authorities[index] = role;
		   index++;
	   }
	   
	   return authorities;
   }

   public boolean isAccountNonExpired() {
       return !getStatus().equals(Constants.STATUS_INACTIVE);
   }

   public boolean isAccountNonLocked() {
       return !getLocked().equals(Constants.BOOLEAN_YES);
   }

   public boolean isCredentialsNonExpired() {
       return !getStatus().equals(Constants.STATUS_INACTIVE);
   }

   public boolean isEnabled() {
       return getStatus().equals(Constants.STATUS_ACTIVE);
   }
}
