package com.cdgtaxi.ibs.acl.model;
// Generated Mar 18, 2009 1:50:22 PM by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;


/**
 * SatbResource generated by hbm2java
 */

public class SatbResource  implements java.io.Serializable {


    // Fields    

    private Long rsrcId;
    private String rsrcName;
    private String rsrcType;
    private String uri;
    private Integer sequence;
    private String displayName;
    private String display;
    private Integer version;
    private Set<SatbResource> satbResources = new HashSet<SatbResource>(0);
    private SatbResource satbResource;
    private Set<SatbRole> satbRoles = new HashSet<SatbRole>(0);


    // Constructors

    /** default constructor */
    public SatbResource() {
    }

	/** minimal constructor */
    public SatbResource(String rsrcName, String displayName, String display) {
        this.rsrcName = rsrcName;
        this.displayName = displayName;
        this.display = display;
    }
    
    /** full constructor */
    public SatbResource(String rsrcName, String rsrcType, String uri, Integer sequence, String displayName, String display, Integer version, Set<SatbResource> satbResources, SatbResource satbResource, Set<SatbRole> satbRoles) {
        this.rsrcName = rsrcName;
        this.rsrcType = rsrcType;
        this.uri = uri;
        this.sequence = sequence;
        this.displayName = displayName;
        this.display = display;
        this.version = version;
        this.satbResources = satbResources;
        this.satbResource = satbResource;
        this.satbRoles = satbRoles;
    }
    

   
    // Property accessors

    public Long getRsrcId() {
        return this.rsrcId;
    }
    
    public void setRsrcId(Long rsrcId) {
        this.rsrcId = rsrcId;
    }

    public String getRsrcName() {
        return this.rsrcName;
    }
    
    public void setRsrcName(String rsrcName) {
        this.rsrcName = rsrcName;
    }

    public String getRsrcType() {
        return this.rsrcType;
    }
    
    public void setRsrcType(String rsrcType) {
        this.rsrcType = rsrcType;
    }

    public String getUri() {
        return this.uri;
    }
    
    public void setUri(String uri) {
        this.uri = uri;
    }

    public Integer getSequence() {
        return this.sequence;
    }
    
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplay() {
        return this.display;
    }
    
    public void setDisplay(String display) {
        this.display = display;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public Set<SatbResource> getSatbResources() {
        return this.satbResources;
    }
    
    public void setSatbResources(Set<SatbResource> satbResources) {
        this.satbResources = satbResources;
    }

    public SatbResource getSatbResource() {
        return this.satbResource;
    }
    
    public void setSatbResource(SatbResource satbResource) {
        this.satbResource = satbResource;
    }

    public Set<SatbRole> getSatbRoles() {
        return this.satbRoles;
    }
    
    public void setSatbRoles(Set<SatbRole> satbRoles) {
        this.satbRoles = satbRoles;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("rsrcName").append("='").append(getRsrcName()).append("' ");			
      buffer.append("rsrcType").append("='").append(getRsrcType()).append("' ");			
      buffer.append("uri").append("='").append(getUri()).append("' ");			
      buffer.append("sequence").append("='").append(getSequence()).append("' ");			
      buffer.append("displayName").append("='").append(getDisplayName()).append("' ");			
      buffer.append("display").append("='").append(getDisplay()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SatbResource) ) return false;
		 SatbResource castOther = ( SatbResource ) other; 
         
		 return ( (this.getRsrcId()==castOther.getRsrcId()) || ( this.getRsrcId()!=null && castOther.getRsrcId()!=null && this.getRsrcId().equals(castOther.getRsrcId()) ) )
 && ( (this.getRsrcName()==castOther.getRsrcName()) || ( this.getRsrcName()!=null && castOther.getRsrcName()!=null && this.getRsrcName().equals(castOther.getRsrcName()) ) )
 && ( (this.getRsrcType()==castOther.getRsrcType()) || ( this.getRsrcType()!=null && castOther.getRsrcType()!=null && this.getRsrcType().equals(castOther.getRsrcType()) ) )
 && ( (this.getUri()==castOther.getUri()) || ( this.getUri()!=null && castOther.getUri()!=null && this.getUri().equals(castOther.getUri()) ) )
 && ( (this.getSequence()==castOther.getSequence()) || ( this.getSequence()!=null && castOther.getSequence()!=null && this.getSequence().equals(castOther.getSequence()) ) )
 && ( (this.getDisplayName()==castOther.getDisplayName()) || ( this.getDisplayName()!=null && castOther.getDisplayName()!=null && this.getDisplayName().equals(castOther.getDisplayName()) ) )
 && ( (this.getDisplay()==castOther.getDisplay()) || ( this.getDisplay()!=null && castOther.getDisplay()!=null && this.getDisplay().equals(castOther.getDisplay()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getSatbResource()==castOther.getSatbResource()) || ( this.getSatbResource()!=null && castOther.getSatbResource()!=null && this.getSatbResource().equals(castOther.getSatbResource()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRsrcId() == null ? 0 : this.getRsrcId().hashCode() );
         result = 37 * result + ( getRsrcName() == null ? 0 : this.getRsrcName().hashCode() );
         result = 37 * result + ( getRsrcType() == null ? 0 : this.getRsrcType().hashCode() );
         result = 37 * result + ( getUri() == null ? 0 : this.getUri().hashCode() );
         result = 37 * result + ( getSequence() == null ? 0 : this.getSequence().hashCode() );
         result = 37 * result + ( getDisplayName() == null ? 0 : this.getDisplayName().hashCode() );
         result = 37 * result + ( getDisplay() == null ? 0 : this.getDisplay().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         
         result = 37 * result + ( getSatbResource() == null ? 0 : this.getSatbResource().hashCode() );
         
         return result;
   }   





}
