/* *******************
 * Inventory
 * *******************/
UPDATE MSTB_MASTER_TABLE SET MASTER_VALUE='<style>*{font-family:Calibri;font-size:16px;white-space:pre;}dir{margin-top:0}</style>Dear #userName#,<br><br>The Inventory Issuance Request you submitted has been approved.<br>The details are as follows:<dir>Submitter: #submitter#<br>Account No: #custNo#<br>Account Name: #acctName#<br>Item Type: #itemType#<br>Quantity: #quantity#</dir>To check your Inventory Issuance Request, please <a href="http://localhost:8080/ibs">click this link</a> to login to the System<br><br>Thanks and Best Regards.'
WHERE MASTER_TYPE = 'EMIRA' AND MASTER_CODE = 'CONT';
UPDATE MSTB_MASTER_TABLE SET MASTER_VALUE='<style>*{font-family:Calibri;font-size:16px;white-space:pre;}dir{margin-top:0}</style>Dear #userName#,<br><br>The Inventory Issuance Request you submitted has been <font face="Calibri Bold" color="red">rejected</font>.<br>The details are as follows:<dir>Submitter: #submitter#<br>Account No: #custNo#<br>Account Name: #acctName#<br>Item Type: #itemType#<br>Quantity: #quantity#</dir>To check your Inventory Issuance Request, please <a href="http://localhost:8080/ibs">click this link</a> to login to the System<br><br>Thanks and Best Regards.'
WHERE MASTER_TYPE = 'EMIRR' AND MASTER_CODE = 'CONT';
UPDATE MSTB_MASTER_TABLE SET MASTER_VALUE='<style>*{font-family:Calibri;font-size:16px;white-space:pre;}dir{margin-top:0}</style>Dear #userName#,<br><br>An Inventory Issuance Request has been submitted for your approval.<br>The details are as follows:<dir>Submitter: #submitter#<br>Account No: #custNo#<br>Account Name: #acctName#<br>Item Type: #itemType#<br>Quantity: #quantity#</dir>Please <a href="http://localhost:8080/ibs">click this link</a> to login to the System<br><br>Thanks and Best Regards.'
WHERE MASTER_TYPE = 'EMIRS' AND MASTER_CODE = 'CONT';
