SET PAGES 5000
SET LINE  10000
SET TRIMSPOOL ON
set echo on

column dt new_value new_dt
column ext new_value new_ext
select  sys_context('userenv','instance_name') || '_novIssueLogs_ddl_01_' || to_char(sysdate,'YYYYMMDDHH24MISS') dt,'.txt' ext from dual;
SPOOL  &new_dt&new_ext
set define off
alter session set current_schema=ibssys;


/*-- 20/11/2017 CR #177 Trip Code Reason START */

--Add new Trip Code Reason Column to TMTB_ACQUIRE_TXN
ALTER TABLE TMTB_ACQUIRE_TXN ADD TRIP_CODE_REASON VARCHAR(80);
COMMENT ON COLUMN TMTB_ACQUIRE_TXN.TRIP_CODE_REASON IS 'Trip Code Reason Description';

--Add new Trip Code Reason Column to TMTB_TXN_REVIEW_REQ
ALTER TABLE TMTB_TXN_REVIEW_REQ ADD TRIP_CODE_REASON VARCHAR(80);
COMMENT ON COLUMN TMTB_TXN_REVIEW_REQ.TRIP_CODE_REASON IS 'Trip Code Reason Description';

--Add new Trip Code Reason Column to BMTB_INVOICE_TXN
ALTER TABLE BMTB_INVOICE_TXN ADD TRIP_CODE_REASON VARCHAR(80);
COMMENT ON COLUMN BMTB_INVOICE_TXN.TRIP_CODE_REASON IS 'Trip Code Reason Description';

--Add new Trip Code Reason Column to BMTB_DRAFT_INV_TXN
ALTER TABLE BMTB_DRAFT_INV_TXN ADD TRIP_CODE_REASON VARCHAR(80);
COMMENT ON COLUMN BMTB_DRAFT_INV_TXN.TRIP_CODE_REASON IS 'Trip Code Reason Description';


--Add new Trip Code Column to ITTB_TRIPS_TXN
ALTER TABLE ITTB_TRIPS_TXN ADD TRIP_CODE VARCHAR(80);
COMMENT ON COLUMN ITTB_TRIPS_TXN.TRIP_CODE IS 'Trip Code Column';

--Add new Trip Code Description Column to ITTB_TRIPS_TXN
ALTER TABLE ITTB_TRIPS_TXN ADD TRIP_DESC VARCHAR(80);
COMMENT ON COLUMN ITTB_TRIPS_TXN.TRIP_DESC IS 'Trip Description';

--Add new Trip Code Column to ITTB_TRIPS_TXN_ERROR
ALTER TABLE ITTB_TRIPS_TXN_ERROR ADD TRIP_CODE VARCHAR(80);
COMMENT ON COLUMN ITTB_TRIPS_TXN_ERROR.TRIP_CODE IS 'Trip Code Column';

--Add new Trip Code Description Column to ITTB_TRIPS_TXN_ERROR
ALTER TABLE ITTB_TRIPS_TXN_ERROR ADD TRIP_DESC VARCHAR(80);
COMMENT ON COLUMN ITTB_TRIPS_TXN_ERROR.TRIP_DESC IS 'Trip Description';


--Add new Trip Code Column to RCVW_INTF_TRIPS_FOR_IBS
ALTER TABLE RCVW_INTF_TRIPS_FOR_IBS ADD TRIP_CODE VARCHAR(80);
COMMENT ON COLUMN RCVW_INTF_TRIPS_FOR_IBS.TRIP_CODE IS 'Trip Code Column';

--Add new Trip Code Description Column to RCVW_INTF_TRIPS_FOR_IBS
ALTER TABLE RCVW_INTF_TRIPS_FOR_IBS ADD TRIP_DESC VARCHAR(80);
COMMENT ON COLUMN RCVW_INTF_TRIPS_FOR_IBS.TRIP_DESC IS 'Trip Description';


/*-- 20/11/2017 CR #177 Trip Code Reason END */

spool off
