SET PAGES 5000
SET LINE  10000
SET TRIMSPOOL ON
set echo on

column dt new_value new_dt
column ext new_value new_ext
select  sys_context('userenv','instance_name') || '_mayp32IssueLogs_ddl_02_' || to_char(sysdate,'YYYYMMDDHH24MISS') dt,'.txt' ext from dual;
SPOOL  &new_dt&new_ext
set define off
alter session set current_schema=ibssys;


/*--  CR RECURRING START */

-- new Table for Recurring Requests
-- 1 Foreign Key only BillGenReqNo
create TABLE ITTB_RECURRING_REQ
(
   REQ_NO NUMBER(9) PRIMARY KEY NOT NULL,
   STATUS varchar2(1) NOT NULL,
   FILE_NAME VARCHAR2(80),
   RETURN_FILE_NAME VARCHAR2(80),
   RETURN_FILE_UPLOAD_DT DATE,
   RECURRING_AUTO_MANUAL varchar2(1),
   BILL_GEN_REQ_NO NUMBER(9),
   INVOICE_NO_FROM NUMBER(18),
   INVOICE_NO_TO NUMBER(18),
   INVOICE_DATE DATE,
   CHARGING_DATE DATE,
   ACCOUNT_NOS varchar2(200),
   VERSION number(9) DEFAULT 0 not null,
   CREATED_BY varchar2(80) not null,
   CREATED_DT TIMESTAMP not null,
   UPDATED_BY varchar2(80),
   UPDATED_DT TIMESTAMP
);
-- CreatedDT UpdatedDT have to use timestamp.
create SEQUENCE ITSQ_RECURRING_REQ MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;

ALTER TABLE ITTB_RECURRING_REQ ADD CONSTRAINT ITCC_REC_REQ__BILLGENREQNO FOREIGN KEY (BILL_GEN_REQ_NO) REFERENCES BMTB_BILL_GEN_REQ (REQ_NO) ENABLE;
CREATE INDEX ITIX_REC_REQ__BILLGENREQNO ON ITTB_RECURRING_REQ(BILL_GEN_REQ_NO);
CREATE INDEX ITIX_REC_REQ__ACCOUNTNOS ON ITTB_RECURRING_REQ(ACCOUNT_NOS);
CREATE INDEX ITIX_REC_REQ__STATUS ON ITTB_RECURRING_REQ(STATUS);
CREATE INDEX ITIX_REC_REQ__INVOICENOFROM ON ITTB_RECURRING_REQ(INVOICE_NO_FROM);
CREATE INDEX ITIX_REC_REQ__INVOICENOTO ON ITTB_RECURRING_REQ(INVOICE_NO_TO);
CREATE INDEX ITIX_REC_REQ__INVOICEDT ON ITTB_RECURRING_REQ(INVOICE_DATE);
CREATE INDEX ITIX_REC_REQ__CHARGINGDATE ON ITTB_RECURRING_REQ(CHARGING_DATE);
CREATE INDEX ITIX_REC_REQ__RECAUTOMAN ON ITTB_RECURRING_REQ(RECURRING_AUTO_MANUAL);

COMMENT ON TABLE ITTB_RECURRING_REQ IS 'Table for Recurring Requests';
COMMENT ON COLUMN ITTB_RECURRING_REQ.REQ_NO IS 'Sequence Id for IttbRecurringReq';
COMMENT ON COLUMN ITTB_RECURRING_REQ.STATUS IS 'Request Status; P=Pending, N=PendingProgress, G=InProgress, C=Completed, E=Error, F=Completed No Record, U=Uploaded, D=Deleted';
COMMENT ON COLUMN ITTB_RECURRING_REQ.FILE_NAME IS 'File Name generated to send to reddot';
COMMENT ON COLUMN ITTB_RECURRING_REQ.RETURN_FILE_NAME IS 'Reddot Return File Name';
COMMENT ON COLUMN ITTB_RECURRING_REQ.RETURN_FILE_UPLOAD_DT IS 'Reddot Return File Upload Date';
COMMENT ON COLUMN ITTB_RECURRING_REQ.RECURRING_AUTO_MANUAL IS 'Request Type: Recurring Auto or Manual Flag; A=Auto, M=Manual';
COMMENT ON COLUMN ITTB_RECURRING_REQ.BILL_GEN_REQ_NO IS 'Parameters: Bill Gen Request No; from bmtbBillGenReq';
COMMENT ON COLUMN ITTB_RECURRING_REQ.INVOICE_NO_FROM IS 'Parameters: Invoice No From; from bmtbInvoiceHeader';
COMMENT ON COLUMN ITTB_RECURRING_REQ.INVOICE_NO_TO IS 'Parameters: Invoice No To; from bmtbInvoiceHeader';
COMMENT ON COLUMN ITTB_RECURRING_REQ.INVOICE_DATE IS 'Parameters: Invoice Date; from bmtbInvoiceHeader';
COMMENT ON COLUMN ITTB_RECURRING_REQ.CHARGING_DATE IS 'Parameters: Charging Date; from amtbAccount';
COMMENT ON COLUMN ITTB_RECURRING_REQ.ACCOUNT_NOS IS 'Parameters: Customers Nos (delimiter by semicolon)';
COMMENT ON COLUMN ITTB_RECURRING_REQ.VERSION IS 'Version';
COMMENT ON COLUMN ITTB_RECURRING_REQ.CREATED_BY IS 'Created By';
COMMENT ON COLUMN ITTB_RECURRING_REQ.CREATED_DT IS 'Created Date';
COMMENT ON COLUMN ITTB_RECURRING_REQ.UPDATED_BY IS 'Updated By';
COMMENT ON COLUMN ITTB_RECURRING_REQ.UPDATED_DT IS 'Updated Date';



-- new Table for Recurring Requests Details
-- 1 Foreign Key base on ReqNo
create TABLE ITTB_RECURRING_DTL
(
   RECURRING_DTL_REQ_NO NUMBER(18) PRIMARY KEY NOT NULL,
   REQ_NO NUMBER(9) NOT NULL,
   REFERENCE_ID VARCHAR(50),
   TOKEN_ID VARCHAR2(150),
   AMOUNT NUMBER(18,2) not null,
   CURRENCY VARCHAR2(20),
   INVOICE_DATE DATE,
   INVOICE_NO  VARCHAR2(50),
   CABCHARGE_CUST_NO  VARCHAR2(50),
   CABCHARGE_CARD_NO  VARCHAR2(50),
   STATUS      VARCHAR2(10),
   ERROR       VARCHAR2(200)
);

create SEQUENCE ITSQ_RECURRING_DTL MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
ALTER TABLE ITTB_RECURRING_DTL ADD CONSTRAINT ITCC_REC_DTL__REQNO FOREIGN KEY (REQ_NO) REFERENCES ITTB_RECURRING_REQ (REQ_NO) ENABLE;
CREATE INDEX ITIX_REC_DTL__REQNO ON ITTB_RECURRING_DTL(REQ_NO);
CREATE INDEX ITIX_REC_DTL__INVOICENO ON ITTB_RECURRING_DTL(INVOICE_NO);
CREATE INDEX ITIX_REC_DTL__REFNO ON ITTB_RECURRING_DTL(REFERENCE_ID);
CREATE INDEX ITIX_REC_DTL__ACCOUNTNO ON ITTB_RECURRING_DTL(CABCHARGE_CUST_NO);
CREATE INDEX ITIX_REC_DTL__PRODUCTNO ON ITTB_RECURRING_DTL(CABCHARGE_CARD_NO);
CREATE INDEX ITIX_REC_DTL__INVOICEDT ON ITTB_RECURRING_DTL(INVOICE_DATE);
CREATE INDEX ITIX_REC_DTL__TOKENID ON ITTB_RECURRING_DTL(TOKEN_ID);

COMMENT ON TABLE ITTB_RECURRING_DTL IS 'Table for Recurring Requests Details';
COMMENT ON COLUMN ITTB_RECURRING_DTL.RECURRING_DTL_REQ_NO IS 'Recurring Detail Sequence Id';
COMMENT ON COLUMN ITTB_RECURRING_DTL.REQ_NO IS 'Request No of ittbRecurringReq';
COMMENT ON COLUMN ITTB_RECURRING_DTL.REFERENCE_ID IS 'Written on CSV: Reference No';
COMMENT ON COLUMN ITTB_RECURRING_DTL.TOKEN_ID IS 'Written on CSV: Token ID ';
COMMENT ON COLUMN ITTB_RECURRING_DTL.AMOUNT IS 'Written on CSV: Invoice Detail Outstanding Transaction Amount $ Value';
COMMENT ON COLUMN ITTB_RECURRING_DTL.CURRENCY IS 'Written on CSV: Currency Value';
COMMENT ON COLUMN ITTB_RECURRING_DTL.INVOICE_DATE IS 'Written on CSV: Invoice Date Value';
COMMENT ON COLUMN ITTB_RECURRING_DTL.INVOICE_NO IS 'Written on CSV: Invoice No Value';
COMMENT ON COLUMN ITTB_RECURRING_DTL.CABCHARGE_CUST_NO IS 'Written on CSV: Cabcharge Customer Account No';
COMMENT ON COLUMN ITTB_RECURRING_DTL.CABCHARGE_CARD_NO IS 'Written on CSV: Cabcharge Card No';
COMMENT ON COLUMN ITTB_RECURRING_DTL.STATUS IS 'Reddot Return Status Y or Yes = Error , N or No = No Error';
COMMENT ON COLUMN ITTB_RECURRING_DTL.ERROR IS 'Reddot Error Message';



--Failure URL for AutoTopup
alter table PMTB_PREPAID_REQ add failureUri varchar2(100 char);
COMMENT ON COLUMN PMTB_PREPAID_REQ.URI IS 'Failure URL for reddot';

/*-- CR  RECURRING END */

spool off
