/*
 * 2015/11/06 SQL
 */
alter table AMTB_APPLICATION add OUTSOURCE_PRINTING_FLAG varchar2(1) NULL;
alter table AMTB_ACCOUNT add OUTSOURCE_PRINTING_FLAG varchar2(1) NULL;

/*
 * 2015/11/09 New SQL 
 */
update AMTB_ACCOUNT set OUTSOURCE_PRINTING_FLAG = 'Y';
update AMTB_APPLICATION set OUTSOURCE_PRINTING_FLAG = 'Y';
alter table AMTB_APPLICATION add constraint CHECK_APP_OS_PRINT_FLAG CHECK (OUTSOURCE_PRINTING_FLAG IN ('Y','N')) ENABLE;
alter table AMTB_ACCOUNT add constraint CHECK_ACCT_OS_PRINT_FLAG CHECK (OUTSOURCE_PRINTING_FLAG IN ('Y','N')) ENABLE;  

/*
 *  2015/11/06 SQL
 */
INSERT INTO SATB_RESOURCE
(RSRC_ID, PAR_RSRC_ID, RSRC_NAME, RSRC_TYPE, URI, SEQUENCE, DISPLAY_NAME, DISPLAY, VERSION)
VALUES(800, 98, 'Transfer Outsource Printing', 'U', '/billgen/transfer_outsource_printing.zul', 1, 'Transfer Outsource Printing', 'Y', 0);