alter table BMTB_INVOICE_HEADER add ( INVOICE_TYPE varchar2(2) );
alter table BMTB_INVOICE_HEADER add ( IMTB_ISSUE_NO number(8) );
COMMENT ON COLUMN BMTB_INVOICE_HEADER.INVOICE_TYPE IS 'To determine the invoice type with the use of a code e.g. misc invoice for taxi voucher issuance'; 
COMMENT ON COLUMN BMTB_INVOICE_HEADER.IMTB_ISSUE_NO IS 'Denotes the invoice is raised for which taxi voucher issuance';

ALTER TABLE BMTB_INVOICE_HEADER ADD CONSTRAINT BMFC_INV_HEAD__I_NO$IMTB_I_NO FOREIGN KEY ("IMTB_ISSUE_NO") REFERENCES IMTB_ISSUE ("ISSUE_NO") ENABLE;

CREATE INDEX BMIX_INV_HEAD__IMTB_ISSUE_NO ON BMTB_INVOICE_HEADER(IMTB_ISSUE_NO);