
ALTER TABLE PMTB_PRODUCT_TYPE ADD CONTACTLESS VARCHAR(1) DEFAULT 'N' NOT NULL;

ALTER TABLE PMTB_PRODUCT ADD OFFLINE_COUNT NUMBER(6,0);

ALTER TABLE PMTB_PRODUCT ADD OFFLINE_AMOUNT NUMBER(6,2);

ALTER TABLE PMTB_PRODUCT ADD OFFLINE_TXN_AMOUNT NUMBER(6,2);

ALTER TABLE PMTB_PRODUCT ADD EMBOSS_NAME_ON_CARD VARCHAR(1) DEFAULT 'Y' NOT NULL;

ALTER TABLE PMTB_PRODUCT ADD WAIVE_ISSUANCE_FEE_FLAG VARCHAR(1) DEFAULT 'Y' NOT NULL;


ALTER TABLE ITTB_AS_ADD_PROD_REQ ADD OFFLINE_COUNT VARCHAR(8);

ALTER TABLE ITTB_AS_ADD_PROD_REQ ADD OFFLINE_AMOUNT VARCHAR(20);

ALTER TABLE ITTB_AS_ADD_PROD_REQ ADD OFFLINE_TXN_AMOUNT VARCHAR(20);

ALTER TABLE ITTB_AS_ADD_PROD_REQ ADD FORCE_ONLINE VARCHAR(1);


ALTER TABLE ITTB_AS_UPD_PROD_REQ ADD OFFLINE_COUNT VARCHAR(8);

ALTER TABLE ITTB_AS_UPD_PROD_REQ ADD OFFLINE_AMOUNT VARCHAR(20);

ALTER TABLE ITTB_AS_UPD_PROD_REQ ADD OFFLINE_TXN_AMOUNT VARCHAR(20);

ALTER TABLE ITTB_AS_UPD_PROD_REQ ADD FORCE_ONLINE VARCHAR(1);
