alter table MSTB_MASTER_TABLE modify MASTER_VALUE varchar2(1000);

--BN: Begin Notification | CN:Complete Notification | NCN: Not Complete Notification | CWE: Complete With Errors (That means file completely written yet encountered errors e.g. re-scheduling
--SJ:Subject, CT:Content
--GUO: GIRO UOB GOING
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'EMGUO','BNCT',null,'<p style="font-family: Calibri; font-size: 16px; white-space: pre;">GIRO UOB File Generation Request #reqNo# begin processing<br /><br />Entity = #entityCode#<br />Value Date = #valueDate#<br />Cutoff Date = #cutoffDate#<br />&nbsp;</p>','A',9);
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'EMGUO','BNSJ',null,'GIRO UOB File Generation Request #reqNo# begin processing','A',0);
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'EMGUO','CNCT',null,'<p style="font-family: Calibri; font-size: 16px; white-space: pre;">GIRO UOB File Generation Request #reqNo#<br /><br />Process Start = #processStartTime#<br />Process End = #processEndTime#<br /><br />Giro File Generation Status = Completed<br /><br />Entity = #entityCode#<br />File Name = #fileName#<br />Number of records = #totalRecordCount#<br />Amount = #totalGiroAmount#</p>','A',4);
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'EMGUO','CNSJ',null,'GIRO UOB File Generation Request #reqNo# Completed','A',1);
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'EMGUO','CWECT',null,'<p style="font-family: Calibri; font-size: 16px; white-space: pre;">GIRO UOB File Generation Request #reqNo#<br /><br />Process Start = #processStartTime#<br />Process End = #processEndTime#<br /><br />Giro File Generation Status = Not Completed<br />Reason = #reason#<br /><br />Entity = #entityCode#<br />File Name = #fileName#<br />Number of records = #totalRecordCount#<br />Amount = #totalGiroAmount#</p>','A',2);
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'EMGUO','CWESJ',null,'GIRO UOB File Generation Request #reqNo# Not Completed','A',1);
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'EMGUO','NCNCT',null,'<p style="font-family: Calibri; font-size: 16px; white-space: pre;">GIRO UOB File Generation Request #reqNo#<br /><br />Process Start = #processStartTime#<br />Process End = #processEndTime#<br /><br />Giro File Generation Status = Not Completed<br />Reason = #reason#<br /><br />Entity = #entityCode#</p>','A',2);
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'EMGUO','NCNSJ',null,'GIRO UOB File Generation Request #reqNo# Not Completed','A',1);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'EMGUI','BNCT',null,'<p style="font-family: Calibri; font-size: 16px; white-space: pre;">GIRO UOB File Upload Request #reqNo# begin processing<br /><br />Entity = #entityCode#<br />File Name = #fileName#<br />&nbsp;</p>','A',11);
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'EMGUI','BNSJ',null,'GIRO UOB File Upload Request #reqNo# begin processing','A',1);
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'EMGUI','CNCT',null,'<p style="font-family: Calibri; font-size: 16px; white-space: pre;">GIRO UOB File Upload Request #reqNo#<br /><br />Process Start = #processStartTime#<br />Process End = #processEndTime#<br /><br />Giro UOB File Return Status = Completed<br /><br />Entity = #entityCode#<br />File Name = #fileName#<br />Number of records accepted by IBS = #acceptedCount#<br />Number of receipts created by IBS = #receiptCreatedCount#<br />Total Amount Applied = #totalAmountApplied#<br /><br />Number of records rejected by IBS = #rejectedCount#<br />Total amount not applied = #totalAmountNotApplied#<br /><br />To view receipt details, click &lt;a href=&quot;http&quot;&gt;here&lt;/a&gt;.</p>','A',5);
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'EMGUI','CNSJ',null,'GIRO UOB File Upload Request #reqNo# Completed','A',2);
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'EMGUI','NCNCT',null,'<p style="font-family: Calibri; font-size: 16px; white-space: pre;">GIRO UOB File Upload Request #reqNo#<br /><br />Process Start = #processStartTime#<br />Process End = #processEndTime#<br /><br />Giro UOB File Return Status = Not Completed<br />Reason = #reason#<br /><br />Entity = #entityCode#<br />File Name = #fileName#</p>','A',3);
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'EMGUI','NCNSJ',null,'GIRO UOB File Upload Request #reqNo# Not Completed','A',2);

