--SMS Notification for Prepaid Cards

--Change master type of SMS to TXSMS
update MSTB_MASTER_TABLE set master_type='TXSMS' where master_type='SMS';

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EXSMS','DEF', NULL, 'Expiry SMS Template', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'TUSMS','DEF',NULL, 'Top Up SMS Template', 'A',0);


--EXPBJ
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EXPBJ','SUBJ',NULL, 'Subject', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EXPBJ','CONT',NULL, 'Content', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EXPBJ','SEND',NULL, 'Send', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EXPBJ','REC',NULL, 'Rec', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EXPBJ','GRACE',NULL, 'Grace', 'A',0);


--TUBJ
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'TUBJ','SUBJ',NULL, 'Subject', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'TUBJ','CONT',NULL, 'Content', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'TUBJ','SEND',NULL, 'Send', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'TUBJ','REC',NULL, 'Rec', 'A',0);


--Script to add Fields

--Add Expiry SMS Format, Top Up SMS Format fields into PRODUCT TYPE
alter table pmtb_product_type add SMS_EXPIRY_FORMAT_MASTER_NO NUMBER(8);

alter table pmtb_product_type add SMS_TOPUP_FORMAT_MASTER_NO NUMBER(8);

--Add SMS Expiry Flag, SMS Top Up Flag fields into APPLICATION
alter table amtb_application add SMS_EXPIRY_FLAG VARCHAR2(1);

alter table amtb_application add SMS_TOPUP_FLAG VARCHAR2(1);

--Add SMS Expiry Flag, SMS Top Up Flag fields into ACCOUNT
alter table amtb_account add SMS_EXPIRY_FLAG VARCHAR2(1);

alter table amtb_account add SMS_TOPUP_FLAG VARCHAR2(1);

--Add SMS Expiry Flag, SMS Top Up Flag fields into PRODUCT
alter table pmtb_product add SMS_EXPIRY_FLAG VARCHAR2(1);

alter table pmtb_product add SMS_TOPUP_FLAG VARCHAR2(1);

--Add SMS Expiry Sent (indicator to prevent sms sent multiple time) field into PRODUCT
alter table pmtb_product add (SMS_EXPIRY_SENT VARCHAR2(1) default 'N');

--Add SMS Top Up Sent (indicator to prevent sms sent multiple time) field into PRODUCT_REPLACEMENT
alter table pmtb_product_replacement add (SMS_TOPUP_SENT VARCHAR2(1) default 'N');

--patch script for sms notification
update amtb_application set SMS_EXPIRY_FLAG='N', SMS_TOPUP_FLAG='N';

update amtb_account set SMS_EXPIRY_FLAG='N', SMS_TOPUP_FLAG='N' where cust_no is not null;

update pmtb_product set SMS_EXPIRY_FLAG='S', SMS_TOPUP_FLAG='S';

--new at 26-02-2013
update amtb_account set SMS_FLAG='N' where cust_no is not null and SMS_FLAG is null;



