
UPDATE SATB_RESOURCE SET URI='Promotion Plan', RSRC_NAME='Promotion Plan', DISPLAY_NAME='Promotion Plan' WHERE RSRC_NAME='Manage Promotion Plan';

INSERT
INTO SATB_RESOURCE
  (
    RSRC_ID,
    PAR_RSRC_ID,
    RSRC_NAME,
    RSRC_TYPE,
    URI,
    SEQUENCE,
    DISPLAY_NAME,
    DISPLAY,
    VERSION
  )
  VALUES
  (
    909,
    603,
    'Manage Promotion Plan',
    'U',
    '/admin/promotion/manage_promotion_plan.zul',
    1,
    'Manage Promotion Plan',
    'Y',
    0
  );

INSERT
INTO SATB_RESOURCE
  (
    RSRC_ID,
    PAR_RSRC_ID,
    RSRC_NAME,
    RSRC_TYPE,
    URI,
    SEQUENCE,
    DISPLAY_NAME,
    DISPLAY,
    VERSION
  )
  VALUES
  (
    910,
    603,
    'Promotion Plan Approval',
    'U',
    '/admin/promotion/approve_promotion_plan.zul',
    2,
    'Promotion Plan Approval',
    'Y',
    0
  );

INSERT INTO SATB_ROLE_RESOURCE SELECT ROLE_ID, 909 FROM SATB_ROLE_RESOURCE WHERE RSRC_ID IN (SELECT RSRC_ID FROM SATB_RESOURCE WHERE RSRC_NAME= 'Promotion Plan');
INSERT INTO SATB_ROLE_RESOURCE SELECT ROLE_ID, 910 FROM SATB_ROLE_RESOURCE WHERE RSRC_ID IN (SELECT RSRC_ID FROM SATB_RESOURCE WHERE RSRC_NAME= 'Promotion Plan');


--Enhancement on Bill Gen Notification

alter table bmtb_bill_gen_req add ACCOUNT_NO NUMBER(8);


INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EMBSP','SUBJ',NULL, 'Bill Gen Request #billGenReq# (#billGenSetup# - #entityName#) begin processing', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EMBSP','CONT',NULL, 'Bill Gen Request #billGenReq# (#billGenSetup# - #entityName#) begin processing', 'A',0);


INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EMBEP','SUBJ',NULL, 'Bill Gen Request #billGenReq# (#billGenSetup# - #entityName#) completed', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EMBEP','CONT',NULL, 'Bill Gen Request #billGenReq# (#billGenSetup# - #entityName#) completed<br><br>No of success invoice: #successCount#<br>No of fail invoice: #failCount#', 'A',0);


INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EMPSP','SUBJ',NULL, 'Bill Gen Request #billGenReq# (#billGenSetup# - #entityName#) - Pdf Gen begin processing', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EMPSP','CONT',NULL, 'Bill Gen Request #billGenReq# (#billGenSetup# - #entityName#) - Pdf Gen begin processing', 'A',0);


INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EMPEP','SUBJ',NULL, 'Bill Gen Request #billGenReq# (#billGenSetup# - #entityName#) - Pdf Gen completed', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EMPEP','CONT',NULL, 'Bill Gen Request #billGenReq# (#billGenSetup# - #entityName#) - Pdf Gen completed', 'A',0);


INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EMAG','SUBJ',NULL, '(#entityName#)- Customer Aging Detail Report Generation', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EMAG','CONT',NULL, 'Customer Aging Detail Report generation completed<br><br>#entityName#<br>#billGenList#<br><br>#hyperlinkList#', 'A',0);


INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EMSAD','SUBJ',NULL, 'Bill Gen Request #billGenReq# (#billGenSetup# - #accountNo#) begin processing', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EMSAD','CONT',NULL, 'Bill Gen Request #billGenReq# (#billGenSetup# - #accountName# (#accountNo#)) begin processing', 'A',0);


INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EMEAD','SUBJ',NULL, 'Bill Gen Request #billGenReq# (#billGenSetup# - #accountNo#) completed', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EMEAD','CONT',NULL, 'Bill Gen Request #billGenReq# (#billGenSetup# - #accountName# (#accountNo#)) completed', 'A',0);


INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EPSAD','SUBJ',NULL, 'Bill Gen Request #billGenReq# (#billGenSetup# - #accountNo#) - Pdf Gen begin processing', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EPSAD','CONT',NULL, 'Bill Gen Request #billGenReq# (#billGenSetup# - #accountName# (#accountNo#)) - Pdf Gen begin processing', 'A',0);


INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EPEAD','SUBJ',NULL, 'Bill Gen Request #billGenReq# (#billGenSetup# - #accountNo#) - Pdf Gen completed', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EPEAD','CONT',NULL, 'Bill Gen Request #billGenReq# (#billGenSetup# - #accountName# (#accountNo#)) - Pdf Gen completed', 'A',0);

