--Email Notification for REGEN Request

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EMSRG','SUBJ',NULL, 'Bill Gen Request #billGenReq# REGEN (#originalBillGenReq# - #acctNoOrEntityName#) begin processing', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EMSRG','CONT',NULL, 'Bill Gen Request #billGenReq# REGEN list of accounts: <br><br> #accountList#', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EPSRG','SUBJ',NULL, 'Bill Gen Request #billGenReq# REGEN (#originalBillGenReq# - #acctNoOrEntityName#) - Pdf Gen begin processing', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EPSRG','CONT',NULL, 'Bill Gen Request #billGenReq# REGEN (#originalBillGenReq# - #acctNoOrEntityName#) - Pdf Gen begin processing', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EPERG','SUBJ',NULL, 'Bill Gen Request #billGenReq# REGEN (#originalBillGenReq# - #acctNoOrEntityName#) - Pdf Gen completed', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EPERG','CONT',NULL, 'Bill Gen Request #billGenReq# REGEN (#originalBillGenReq# - #acctNoOrEntityName#) - Pdf Gen completed', 'A',0);

--20130502
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EMERG','SUBJ',NULL, 'Bill Gen Request #billGenReq# REGEN (#originalBillGenReq# - #acctNoOrEntityName#) completed', 'A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'EMERG','CONT',NULL, 'Bill Gen Request #billGenReq# REGEN completed<br><br>No of success invoice: #successCount#<br>No of fail invoice: #failCount#', 'A',0);

update MSTB_MASTER_TABLE set master_value='Bill Gen Request #billGenReq# (#billGenSetup# - #accountName# (#accountNo#)) completed<br><br>No of success invoice: #successCount#<br>No of fail invoice: #failCount#' where MASTER_TYPE='EMEAD' and master_code='CONT';








--
