-- Add new column Print Tax Invoice in AmtbAccount

ALTER TABLE AMTB_ACCOUNT ADD (PRINT_TAX_INV_ONLY varchar2(1 char) DEFAULT 'N');

COMMENT ON COLUMN AMTB_ACCOUNT.PRINT_TAX_INV_ONLY IS 'Print Tax Invoice Flag';

ALTER TABLE AMTB_APPLICATION ADD (PRINT_TAX_INV_ONLY varchar2(1 char) DEFAULT 'N');

COMMENT ON COLUMN AMTB_ACCOUNT.PRINT_TAX_INV_ONLY IS 'Print Tax Invoice Flag';