ALTER TABLE BMTB_INVOICE_TXN add ASSIGN_TO varchar2(80 char);


ALTER TABLE BMTB_DRAFT_INV_TXN add ASSIGN_TO varchar2(80 char);

ALTER TABLE ITTB_CP_CUST_CARD_ISSUANCE add BATCH_FLAG varchar2(1 char) DEFAULT 'N';

ALTER TABLE ITTB_CP_CUST_CARD_ISSUANCE add REMARKS varchar2(500 char);
