SET PAGES 5000
SET LINE  10000
SET TRIMSPOOL ON
set echo on

column dt new_value new_dt
column ext new_value new_ext
select  sys_context('userenv','instance_name') || '_septIssueLogs_ddl_01_' || to_char(sysdate,'YYYYMMDDHH24MISS') dt,'.txt' ext from dual;
SPOOL  &new_dt&new_ext
set define off
alter session set current_schema=ibssys;


/*-- 16/09/2017 CR #171 Virtual CabCharge START */

--Add new Virtual Product Column to PMTB_PRODUCT_TYPE
ALTER TABLE PMTB_PRODUCT_TYPE ADD VIRTUAL_PRODUCT VARCHAR(1) DEFAULT 'N' NOT NULL;
COMMENT ON COLUMN PMTB_PRODUCT_TYPE.VIRTUAL_PRODUCT IS 'Virtual Product Yes No';




-- Pmtb Virtual Email
CREATE TABLE PMTB_VIRTUAL_EMAIL (
	VIRTUAL_CARD_ID NUMBER(8) NOT NULL,
	PRODUCT_ID NUMBER(19) NOT NULL,
	ACCOUNT_NAME VARCHAR2(80) NOT NULL,
	CUSTOMER_ID VARCHAR2(6) NOT NULL,
	SHIPPING_CONTACT_NAME VARCHAR2(80) NOT NULL,
	EMAIL_ADDRESS_TO VARCHAR2(255) NOT NULL,
	ASSIGNED_TO VARCHAR2(80) NOT NULL,
	MOBILE_NO VARCHAR2(20) NOT NULL,
	VIRTUAL_CARD_NO VARCHAR2(19) NOT NULL,
	EXPIRY_DATE VARCHAR2(7) NOT NULL,
	DIVISION_DEPARTMENT VARCHAR2(80),
	REMARKS VARCHAR2(80),
	DATE_SUBMITTED TIMESTAMP NOT NULL,
	SUBMITTED_BY VARCHAR2(40),
	SUBMITTED_BY_EMAIL VARCHAR2(80),
	FAIL_REASON VARCHAR2(80)
);

-- Create SEQUENCE
CREATE SEQUENCE  "PMSQ_VIRTUAL_CARD_ID"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 2 CACHE 10 NOORDER  NOCYCLE ;

--comments
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.PRODUCT_ID IS 'Product ID ';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.ACCOUNT_NAME IS 'Account Name';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.CUSTOMER_ID IS 'Customer ID';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.SHIPPING_CONTACT_NAME IS 'Shipping Contact Name';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.EMAIL_ADDRESS_TO IS 'Email Address';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.ASSIGNED_TO IS 'Assigned To';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.MOBILE_NO IS 'Mobile No';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.EXPIRY_DATE IS 'Expiry Date';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.DIVISION_DEPARTMENT IS 'Division Deparment';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.REMARKS IS 'Remarks';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.DATE_SUBMITTED IS 'Date Submitted';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.SUBMITTED_BY IS 'Submitted by';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.SUBMITTED_BY_EMAIL IS 'Submitted by Email Address';
COMMENT ON COLUMN PMTB_VIRTUAL_EMAIL.FAIL_REASON IS 'Failed Reason';

/*-- 16/09/2017 CR #171 Virtual Cabcharge END */

spool off
