SET PAGES 5000
SET LINE  10000
SET TRIMSPOOL ON
set echo on

column dt new_value new_dt
column ext new_value new_ext
select  sys_context('userenv','instance_name') || '_octIssueLogs_ddl_01_' || to_char(sysdate,'YYYYMMDDHH24MISS') dt,'.txt' ext from dual;
SPOOL  &new_dt&new_ext
set define off
alter session set current_schema=ibssys;


/*-- 30/8/2018 CR #192 PUBBS START */


--Add new PUBBS FLAG to AMTB_APPLICATION
ALTER TABLE AMTB_ACCOUNT ADD (PUBBS_FLAG varchar2(1 char) DEFAULT 'N');
COMMENT ON COLUMN AMTB_ACCOUNT.PUBBS_FLAG IS 'PUBBS Flag';

ALTER TABLE AMTB_APPLICATION ADD (PUBBS_FLAG varchar2(1 char) DEFAULT 'N');
COMMENT ON COLUMN AMTB_APPLICATION.PUBBS_FLAG IS 'PUBBS Flag';

ALTER TABLE BMTB_BILL_GEN_SETUP ADD "PUBBS_FLAG" VARCHAR(3) DEFAULT 'OFF' NOT NULL;
COMMENT ON COLUMN BMTB_BILL_GEN_SETUP.PUBBS_FLAG IS 'PUBBS FLAG';

create TABLE ITTB_PUBBS_REQ
(
   REQ_NO NUMBER(8) PRIMARY KEY NOT NULL,
   STATUS varchar2(1) NOT NULL,
   FILE_NAME VARCHAR2(80),
   RETURN_FILE_NAME VARCHAR2(80),
   RETURN_FILE_UPLOAD_DT TIMESTAMP,
   BILL_GEN_REQ_NO NUMBER(8),
   INVOICE_NO_FROM NUMBER(18),
   INVOICE_NO_TO NUMBER(18),
   INVOICE_DATE DATE,
   ACCOUNT_NO NUMBER(8),
   VERSION number(9) DEFAULT 0,
   CREATED_BY varchar2(80),
   CREATED_DT timestamp,
   UPDATED_BY varchar2(80),
   UPDATED_DT timestamp
);
create SEQUENCE ITTB_PUBBS_REQ_SQ1 MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
ALTER TABLE ITTB_PUBBS_REQ ADD CONSTRAINT ITTB_PUBBS_REQ_FK1 FOREIGN KEY (BILL_GEN_REQ_NO) REFERENCES BMTB_BILL_GEN_REQ (REQ_NO) ENABLE;
ALTER TABLE ITTB_PUBBS_REQ ADD CONSTRAINT ITTB_PUBBS_REQ_FK2 FOREIGN KEY (ACCOUNT_NO) REFERENCES AMTB_ACCOUNT (ACCOUNT_NO) ENABLE;
CREATE INDEX ITTB_PUBBS_REQ_N1 ON ITTB_PUBBS_REQ(BILL_GEN_REQ_NO);
CREATE INDEX ITTB_PUBBS_REQ_N2 ON ITTB_PUBBS_REQ(ACCOUNT_NO);


COMMENT ON COLUMN ITTB_PUBBS_REQ.REQ_NO IS 'Request No';
COMMENT ON COLUMN ITTB_PUBBS_REQ.STATUS IS 'Status';
COMMENT ON COLUMN ITTB_PUBBS_REQ.FILE_NAME IS 'File Name';
COMMENT ON COLUMN ITTB_PUBBS_REQ.RETURN_FILE_NAME IS 'Return File Name';
COMMENT ON COLUMN ITTB_PUBBS_REQ.RETURN_FILE_UPLOAD_DT IS 'Return File Upload Date';
COMMENT ON COLUMN ITTB_PUBBS_REQ.BILL_GEN_REQ_NO IS 'Bill Gen Request No';
COMMENT ON COLUMN ITTB_PUBBS_REQ.INVOICE_NO_FROM IS 'Invoice No From';
COMMENT ON COLUMN ITTB_PUBBS_REQ.INVOICE_NO_TO IS 'Invoice No To';
COMMENT ON COLUMN ITTB_PUBBS_REQ.INVOICE_DATE IS 'Invoice Date';
COMMENT ON COLUMN ITTB_PUBBS_REQ.ACCOUNT_NO IS 'Account No';
COMMENT ON COLUMN ITTB_PUBBS_REQ.VERSION IS 'Request No';
COMMENT ON COLUMN ITTB_PUBBS_REQ.CREATED_BY IS 'Created By';
COMMENT ON COLUMN ITTB_PUBBS_REQ.CREATED_DT IS 'Created Date';
COMMENT ON COLUMN ITTB_PUBBS_REQ.UPDATED_BY IS 'Updated By';
COMMENT ON COLUMN ITTB_PUBBS_REQ.UPDATED_DT IS 'Updated Date';


create TABLE ITTB_PUBBS_DTL
(
   HEADER_NO NUMBER(18) PRIMARY KEY NOT NULL,
   REQ_NO NUMBER(8) NOT NULL,
   CUSTOMER_ACCOUNT_NO VARCHAR2(30) NOT NULL,
   TRANSACTION_TYPE VARCHAR2(20) NOT NULL,
   BILL_TYPE VARCHAR2(20) NOT NULL,
   INVOICE_NO VARCHAR2(30) NOT NULL,
   INVOICE_DATE DATE NOT NULL,
   INVOICE_CURRENCY_CODE VARCHAR2(15) NOT NULL,
   INVOICE_QTY NUMBER(16,2) NOT NULL,
   INVOICE_GROSS_AMOUNT NUMBER(16,2) NOT NULL,
   INVOICE_TAX_AMOUNT NUMBER(16,2) NOT NULL,
   INVOICE_TOTAL_AMOUNT NUMBER(16,2) NOT NULL,
   REFERENCE VARCHAR2(20) NOT NULL,
   RETURN_STATUS VARCHAR2(1),
   RETURN_REMARKS varchar2(254)
);
create SEQUENCE ITTB_PUBBS_DTL_SQ1 MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
ALTER TABLE ITTB_PUBBS_DTL ADD CONSTRAINT ITTB_PUBBS_DTL_FK1 FOREIGN KEY (REQ_NO) REFERENCES ITTB_PUBBS_REQ (REQ_NO) ENABLE;
CREATE INDEX ITTB_PUBBS_DTL_N1 ON ITTB_PUBBS_DTL(REQ_NO);


COMMENT ON COLUMN ITTB_PUBBS_DTL.HEADER_NO IS 'Header No';
COMMENT ON COLUMN ITTB_PUBBS_DTL.REQ_NO IS 'Request No';
COMMENT ON COLUMN ITTB_PUBBS_DTL.CUSTOMER_ACCOUNT_NO IS 'Customer Acct No';
COMMENT ON COLUMN ITTB_PUBBS_DTL.TRANSACTION_TYPE IS 'Transaction Type';
COMMENT ON COLUMN ITTB_PUBBS_DTL.BILL_TYPE IS 'Bill Type';
COMMENT ON COLUMN ITTB_PUBBS_DTL.INVOICE_NO IS 'Invoice No';
COMMENT ON COLUMN ITTB_PUBBS_DTL.INVOICE_DATE IS 'Invoice Date';
COMMENT ON COLUMN ITTB_PUBBS_DTL.INVOICE_QTY IS 'Invoice Quantity';
COMMENT ON COLUMN ITTB_PUBBS_DTL.INVOICE_GROSS_AMOUNT IS 'Invoice Gross Amount';
COMMENT ON COLUMN ITTB_PUBBS_DTL.INVOICE_TAX_AMOUNT IS 'Invoice Tax Amount';
COMMENT ON COLUMN ITTB_PUBBS_DTL.INVOICE_TOTAL_AMOUNT IS 'Invoice Total Amount';
COMMENT ON COLUMN ITTB_PUBBS_DTL.REFERENCE IS 'Reference';
COMMENT ON COLUMN ITTB_PUBBS_DTL.RETURN_STATUS IS 'Return Status';
COMMENT ON COLUMN ITTB_PUBBS_DTL.RETURN_REMARKS IS 'Return remarks';


--links
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES ((SELECT MAX(rsrc_id)+1 FROM SATB_RESOURCE),(select rsrc_id from SATB_RESOURCE where RSRC_NAME = 'Bill Gen'),'Create PUBBS Request','U','/pubbs/create_pubbs_request.zul',(SELECT MAX(SEQUENCE)+1 FROM SATB_RESOURCE where rsrc_name='Bill Gen'),'Create PUBBS Request','Y',0);
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES ((SELECT MAX(rsrc_id)+1 FROM SATB_RESOURCE),(select rsrc_id from SATB_RESOURCE where RSRC_NAME = 'Bill Gen'),'Manage PUBBS Request','U','/pubbs/manage_pubbs_request.zul',(SELECT MAX(SEQUENCE)+1 FROM SATB_RESOURCE where rsrc_name='Bill Gen'),'Manage PUBBS Request','Y',0);

INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES ((SELECT MAX(rsrc_id)+1 FROM SATB_RESOURCE),(select rsrc_id from SATB_RESOURCE where RSRC_NAME = 'Report'),'PUBBS Billing','U','PUBBS Billing',(SELECT MAX(SEQUENCE)+1 FROM SATB_RESOURCE where rsrc_name='Report'),'PUBBS Billing','Y',0);
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES ((SELECT MAX(rsrc_id)+1 FROM SATB_RESOURCE),(select rsrc_id from SATB_RESOURCE where RSRC_NAME = 'PUBBS Billing'),'PUBBS Billing Report','U','/report/pubbs.zul',(SELECT MAX(SEQUENCE)+1 FROM SATB_RESOURCE where rsrc_name='PUBBS Billing Report'),'PUBBS Billing Report','Y',0);

--updated 20/02/2019 with  ?rscId=    fix
update satb_resource set uri = '/report/pubbs.zul?rsrcId='||(SELECT rsrc_id from satb_resource where uri = '/report/pubbs.zul' ) where uri = '/report/pubbs.zul';
INSERT INTO MSTB_REPORT_FORMAT_MAP values (MSTB_REPORT_FORMAT_MAP_SQ1.nextVal,(select rsrc_id from SATB_RESOURCE where RSRC_NAME = 'PUBBS Billing Report'),'CSV');

CREATE INDEX ITTB_PUBBS_DTL_N2 ON ITTB_PUBBS_DTL(INVOICE_NO);


/*-- 30/8/2018 CR #192 PUBBS END */

spool off
