-- creating seq for CNII INTERFACE --
CREATE SEQUENCE  "ITTB_CNII_ACCT_REQ_SQ1"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  CYCLE ;
-- CNII INTERFACE --
CREATE TABLE ITTB_CNII_ACCT_REQ (
	REQ_ID VARCHAR2(14) NOT NULL, -- YYYYMMDD + SQ1
	REQ_DATE TIMESTAMP NOT NULL,
	REQ_STATUS VARCHAR2(1) DEFAULT 'P' NOT NULL, -- P = PENDING
	REQ_ERROR_REMARK VARCHAR2(255),
	EVENT_TYPE VARCHAR2(1) NOT NULL, -- N = NEW, U = UPDATE, D = DEACTIVATE
	ACCOUNT_ID VARCHAR2(20) NOT NULL, -- CUST_NO + DIVISION CODE + DEPARTMENT CODE
	ACCOUNT_CD VARCHAR2(10) NOT NULL, -- CUST_NO OR DIVISION CODE OR DEPARTMENT CODE
	ACCOUNT_NM VARCHAR2(80) NOT NULL, -- ACCOUNT NAME OR DIVISION NAME OR DEPT NAME
	PARENT_ID VARCHAR2(20), -- NULL FOR CORP, CUST_NO FOR DIV, CUST_NO + DIV_CODE FOR DEPT
	TERMINATE_DT DATE, -- TERMINATION DATE
	SUSPENSION_START_DT DATE, -- SUSPENSION START DATE
	SUSPENSION_END_DT DATE, -- SUSPENSION END DATE
	VALID_FLG VARCHAR2(1) DEFAULT 'Y' NOT NULL, -- ALWAYS Y
	UPDATED_BY VARCHAR2(10) DEFAULT 'IBS' NOT NULL, -- ALWAYS IBS
	UPDATED_DT TIMESTAMP NOT NULL, -- CURRENT DATE
	VERSION NUMBER(9,0) DEFAULT 0,
	CONSTRAINT ITTB_CNII_ACCT_REQ_PK PRIMARY KEY(REQ_ID)
);
-- creating indexes --
-- dumping some data into it
-- creating seq for FMS INTERFACE --
CREATE SEQUENCE  "ITTB_FMS_DRVR_RFND_COL_REQ_SQ1"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  CYCLE ;
-- FMS INTERFACE --
CREATE TABLE ITTB_FMS_DRVR_RFND_COL_REQ (
	REQ_ID VARCHAR2(14) NOT NULL, -- YYYYMMDD + SQ1
	REQ_DATE TIMESTAMP NOT NULL,
	REQ_STATUS VARCHAR2(1) DEFAULT 'P' NOT NULL, -- P = PENDING
	REQ_ERROR_REMARK VARCHAR2(255),
	EVENT_TYPE VARCHAR2(1) NOT NULL, -- N = NEW, U = UPDATE, D = DEACTIVATE
	ENTITY_CODE VARCHAR2(5) NOT NULL, -- ENTITY CODE
	NRIC VARCHAR2(15) NOT NULL,
	JOB_NO VARCHAR2(10) NOT NULL, -- job no
	TAXI_NO VARCHAR2(10) NOT NULL, -- taxi no
	JOB_TYPE VARCHAR2(10) NOT NULL, -- job type
	SERVICE_PROVIDER VARCHAR2(10) NOT NULL, -- NORM - normal, PMSV - premier
	PAYMENT_MODE VARCHAR2(10) NOT NULL	, -- Product type in our screen, 
	PAYMENT_AMT NUMBER(12,2) NOT NULL, -- refund amount/collect amount to FMS
	LEVY NUMBER(6,2), -- levy amount, calculated by create/update/edit transaciton screen in IBS
	TRIP_START_DT TIMESTAMP NOT NULL,
	TRIP_END_DT TIMESTAMP NOT NULL,
	ACCOUNT_NAME VARCHAR2(80), -- premier trips account name
	PICKUP_ADDRESS VARCHAR2(255) NOT NULL,
	DESTINATION VARCHAR2(255) NOT NULL,
	UPDATED_BY VARCHAR2(10) NOT NULL, -- "IBS"
	UPDATED_DT TIMESTAMP NOT NULL,-- current date
	VERSION NUMBER(9,0) DEFAULT 0,
	CONSTRAINT ITTB_FMS_DRVR_RFND_COL_REQ_PK PRIMARY KEY(REQ_ID)
);
-- for view --
CREATE TABLE RCVW_INTF_TRIPS_FOR_IBS(
	TRIP_INTF_PK decimal(22) NOT NULL,
	JOB_NO varchar2(10) NOT NULL,
	VEHICLE_NO varchar2(10) NOT NULL,
	DRIVER_IC varchar2(10),
	ENTITY varchar2(10),
	BOOKED_CHANNEL varchar2(10),
	BOOKED_DATE_TIME timestamp,
	BOOKED_VEHICLE_GROUP varchar2(40),
	PAX_NAME varchar2(40),
	BOOKING_REFERENCE varchar2(40),
	TRIP_START timestamp,
	TRIP_END timestamp,
	PICKUP varchar2(80),
	DESTINATION varchar2(80),
	JOB_TYPE varchar2(10),
	JOB_STATUS varchar2(10) NOT NULL,
	PAX_PRIVILEGE varchar2(20),
	PRODUCT_ID varchar2(10),
	PRODUCT varchar2(40),
	PAYMENT_MODE varchar2(10),
	ACCOUNT_LV1 varchar2(10),
	ACCOUNT_LV2 varchar2(10),
	CARD_NO varchar2(20),
	APPROVAL_CODE varchar2(20),
	GST_INCLUSIVE varchar2(1),
	TXN_AMOUNT NUMBER(6,2),
	BOOKING_FEE NUMBER(6,2),
	ADMIN_AMOUNT NUMBER(6,2),
	GST_AMOUNT NUMBER(6,2),
	TOTAL_AMOUNT NUMBER(6,2),
	DRIVER_LEVY NUMBER(6,2),
	MERIT_POINT_FEE NUMBER(6,2),
	SURCHARGE_DESCRIPTION varchar2(80),
	CHARGED_TO varchar2(40),
	COMPLIMENTARY varchar2(1),
	STATUS varchar2(1),
	FMS_STATUS varchar2(1),
	FMS_DATE timestamp,
	CREATE_BY varchar2(10),
	CREATE_DATE timestamp,
	LAST_UPDATE_BY varchar2(10),
	LAST_UPDATE_DATE timestamp,
	SERVICE_TYPE varchar2(10),
	ACCOUNT_LV3 varchar2(10),
	ACCOUNT_LV1_NAME varchar2(80),
	ACCOUNT_LV2_NAME varchar2(80),
	ACCOUNT_LV3_NAME varchar2(80),
	BOOKED_BY varchar2(15),
	ERROR_CODE varchar2(10),
	FLOWTHRU_ACTION varchar2(10),
	FLOWTHRU_BY varchar2(10),
	FLOWTHRU_DT timestamp,
	FLOWTHRU_COMMENTS varchar2(80),
	TID varchar2(8),
	CANCEL_REASON_CODE decimal(22),
	CANCEL_REASON_DESC varchar2(60),
	SURCHARGE_BREAKDOWN varchar2(80),
	TRIP_INTF_REF varchar2(20),
	REFUND NUMBER(6,2),
	CARD_TYPE varchar2(1),
	SETL_DATE timestamp,
	BANK_TID varchar2(8),
	BANK_BATCH_CLOSE_NO varchar2(6),
	COMPLETED_DT timestamp,
	SALES_DRAFT_NO varchar2(15),
	RECON_DATE timestamp,
	SCENARIO varchar2(20),
	IBS_STATUS varchar2(1),
	IBS_ERROR_CODE varchar2(10),
	IBS_DATE timestamp,
	FLIGHT_DETAILS varchar2(20),
	AGENT_NAME varchar2(80)
);
CREATE OR REPLACE VIEW VW_INTF_TRIPS_FOR_IBS AS
	SELECT "TRIP_INTF_PK","JOB_NO","VEHICLE_NO","DRIVER_IC","ENTITY","BOOKED_CHANNEL","BOOKED_DATE_TIME",
		"BOOKED_VEHICLE_GROUP","PAX_NAME","BOOKING_REFERENCE","TRIP_START","TRIP_END","PICKUP","DESTINATION",
		"JOB_TYPE","JOB_STATUS","PAX_PRIVILEGE","PRODUCT_ID","PRODUCT","PAYMENT_MODE","ACCOUNT_LV1",
		"ACCOUNT_LV2","CARD_NO","APPROVAL_CODE","GST_INCLUSIVE","TXN_AMOUNT","BOOKING_FEE","ADMIN_AMOUNT",
		"GST_AMOUNT","TOTAL_AMOUNT","DRIVER_LEVY","MERIT_POINT_FEE","SURCHARGE_DESCRIPTION","CHARGED_TO",
		"COMPLIMENTARY","STATUS","FMS_STATUS","FMS_DATE","CREATE_BY","CREATE_DATE","LAST_UPDATE_BY",
		"LAST_UPDATE_DATE","SERVICE_TYPE","ACCOUNT_LV3","ACCOUNT_LV1_NAME","ACCOUNT_LV2_NAME","ACCOUNT_LV3_NAME",
		"BOOKED_BY","ERROR_CODE","FLOWTHRU_ACTION","FLOWTHRU_BY","FLOWTHRU_DT","FLOWTHRU_COMMENTS","TID",
		"CANCEL_REASON_CODE","CANCEL_REASON_DESC","SURCHARGE_BREAKDOWN","TRIP_INTF_REF","REFUND","CARD_TYPE",
		"SETL_DATE","BANK_TID","BANK_BATCH_CLOSE_NO","COMPLETED_DT","SALES_DRAFT_NO","RECON_DATE","SCENARIO",
		"IBS_STATUS","IBS_ERROR_CODE","IBS_DATE","FLIGHT_DETAILS","AGENT_NAME"
	FROM RCVW_INTF_TRIPS_FOR_IBS;

CREATE TABLE ITTB_TRIPS_TXN(
	TRIP_INTF_PK decimal(22) NOT NULL,
	JOB_NO varchar2(10),
	VEHICLE_NO varchar2(10),
	DRIVER_IC varchar2(10),
	ENTITY varchar2(10),
	BOOKED_CHANNEL varchar2(10),
	BOOKED_DATE_TIME timestamp,
	BOOKED_VEHICLE_GROUP varchar2(40),
	PAX_NAME varchar2(40),
	BOOKING_REFERENCE varchar2(40),
	TRIP_START timestamp,
	TRIP_END timestamp,
	PICKUP varchar2(80),
	DESTINATION varchar2(80),
	JOB_TYPE varchar2(10),
	JOB_STATUS varchar2(10),
	PAX_PRIVILEGE varchar2(20),
	PRODUCT_ID varchar2(10),
	PRODUCT varchar2(40),
	PAYMENT_MODE varchar2(10),
	ACCOUNT_LV1 varchar2(10),
	ACCOUNT_LV2 varchar2(10),
	CARD_NO varchar2(20),
	APPROVAL_CODE varchar2(20),
	GST_INCLUSIVE varchar2(1),
	TXN_AMOUNT NUMBER(6,2),
	BOOKING_FEE NUMBER(6,2),
	ADMIN_AMOUNT NUMBER(6,2),
	GST_AMOUNT NUMBER(6,2),
	TOTAL_AMOUNT NUMBER(6,2),
	DRIVER_LEVY NUMBER(6,2),
	MERIT_POINT_FEE NUMBER(6,2),
	SURCHARGE_DESCRIPTION varchar2(80),
	CHARGED_TO varchar2(40),
	COMPLIMENTARY varchar2(1),
	STATUS varchar2(1),
	FMS_STATUS varchar2(1),
	FMS_DATE timestamp,
	CREATE_BY varchar2(10),
	CREATE_DATE timestamp,
	LAST_UPDATE_BY varchar2(10),
	LAST_UPDATE_DATE timestamp,
	SERVICE_TYPE varchar2(10),
	ACCOUNT_LV3 varchar2(10),
	ACCOUNT_LV1_NAME varchar2(80),
	ACCOUNT_LV2_NAME varchar2(80),
	ACCOUNT_LV3_NAME varchar2(80),
	BOOKED_BY varchar2(15),
	ERROR_CODE varchar2(10),
	FLOWTHRU_ACTION varchar2(10),
	FLOWTHRU_BY varchar2(10),
	FLOWTHRU_DT timestamp,
	FLOWTHRU_COMMENTS varchar2(80),
	TID varchar2(8),
	CANCEL_REASON_CODE decimal(22),
	CANCEL_REASON_DESC varchar2(60),
	SURCHARGE_BREAKDOWN varchar2(80),
	TRIP_INTF_REF varchar2(20),
	REFUND NUMBER(6,2),
	CARD_TYPE varchar2(1),
	SETL_DATE timestamp,
	BANK_TID varchar2(8),
	BANK_BATCH_CLOSE_NO varchar2(6),
	COMPLETED_DT timestamp,
	SALES_DRAFT_NO varchar2(15),
	RECON_DATE timestamp,
	SCENARIO varchar2(20),
	IBS_STATUS varchar2(1),
	IBS_ERROR_CODE varchar2(10),
	IBS_DATE timestamp,
	ERROR_MSG VARCHAR2(255),
	FLIGHT_DETAILS varchar2(20),
	AGENT_NAME varchar2(80),
	CONSTRAINT ITTB_TRIPS_TXN_PK PRIMARY KEY(TRIP_INTF_PK)
);
	
CREATE TABLE ITTB_TRIPS_TXN_ERROR(
	TRIP_INTF_PK decimal(22) NOT NULL,
	JOB_NO varchar2(10),
	VEHICLE_NO varchar2(10),
	DRIVER_IC varchar2(10),
	ENTITY varchar2(10),
	BOOKED_CHANNEL varchar2(10),
	BOOKED_DATE_TIME timestamp,
	BOOKED_VEHICLE_GROUP varchar2(40),
	PAX_NAME varchar2(40),
	BOOKING_REFERENCE varchar2(40),
	TRIP_START timestamp,
	TRIP_END timestamp,
	PICKUP varchar2(80),
	DESTINATION varchar2(80),
	JOB_TYPE varchar2(10),
	JOB_STATUS varchar2(10),
	PAX_PRIVILEGE varchar2(20),
	PRODUCT_ID varchar2(10),
	PRODUCT varchar2(40),
	PAYMENT_MODE varchar2(10),
	ACCOUNT_LV1 varchar2(10),
	ACCOUNT_LV2 varchar2(10),
	CARD_NO varchar2(20),
	APPROVAL_CODE varchar2(20),
	GST_INCLUSIVE varchar2(1),
	TXN_AMOUNT NUMBER(6,2),
	BOOKING_FEE NUMBER(6,2),
	ADMIN_AMOUNT NUMBER(6,2),
	GST_AMOUNT NUMBER(6,2),
	TOTAL_AMOUNT NUMBER(6,2),
	DRIVER_LEVY NUMBER(6,2),
	MERIT_POINT_FEE NUMBER(6,2),
	SURCHARGE_DESCRIPTION varchar2(80),
	CHARGED_TO varchar2(40),
	COMPLIMENTARY varchar2(1),
	STATUS varchar2(1),
	FMS_STATUS varchar2(1),
	FMS_DATE timestamp,
	CREATE_BY varchar2(10),
	CREATE_DATE timestamp,
	LAST_UPDATE_BY varchar2(10),
	LAST_UPDATE_DATE timestamp,
	SERVICE_TYPE varchar2(10),
	ACCOUNT_LV3 varchar2(10),
	ACCOUNT_LV1_NAME varchar2(80),
	ACCOUNT_LV2_NAME varchar2(80),
	ACCOUNT_LV3_NAME varchar2(80),
	BOOKED_BY varchar2(15),
	ERROR_CODE varchar2(10),
	FLOWTHRU_ACTION varchar2(10),
	FLOWTHRU_BY varchar2(10),
	FLOWTHRU_DT timestamp,
	FLOWTHRU_COMMENTS varchar2(80),
	TID varchar2(8),
	CANCEL_REASON_CODE decimal(22),
	CANCEL_REASON_DESC varchar2(60),
	SURCHARGE_BREAKDOWN varchar2(80),
	TRIP_INTF_REF varchar2(20),
	REFUND NUMBER(6,2),
	CARD_TYPE varchar2(1),
	SETL_DATE timestamp,
	BANK_TID varchar2(8),
	BANK_BATCH_CLOSE_NO varchar2(6),
	COMPLETED_DT timestamp,
	SALES_DRAFT_NO varchar2(15),
	RECON_DATE timestamp,
	SCENARIO varchar2(20),
	IBS_STATUS varchar2(1),
	IBS_ERROR_CODE varchar2(10),
	IBS_DATE timestamp,
	ERROR_MSG VARCHAR2(255),
	FLIGHT_DETAILS varchar2(20),
	AGENT_NAME varchar2(80)
);
-- creating indexes --

CREATE INDEX ITTB_FMS_DRVR_RFND_COL_REQ_N1 ON ITTB_FMS_DRVR_RFND_COL_REQ (JOB_NO);



--  CREATE TABLE ITTB_TRIPS_TXN
--   (	"TRIP_INTF_PK" NUMBER(22,0) NOT NULL ENABLE, 
--	"JOB_NO" VARCHAR2(10 BYTE), 
--	"VEHICLE_NO" VARCHAR2(10 BYTE), 
--	"DRIVER_IC" VARCHAR2(10 BYTE), 
--	"ENTITY" VARCHAR2(10 BYTE), 
--	"BOOKED_CHANNEL" VARCHAR2(10 BYTE), 
--	"BOOKED_DATE_TIME" TIMESTAMP (6), 
--	"BOOKED_VEHICLE_GROUP" VARCHAR2(40 BYTE), 
--	"PAX_NAME" VARCHAR2(40 BYTE), 
--	"BOOKING_REFERENCE" VARCHAR2(40 BYTE), 
--	"TRIP_START" TIMESTAMP (6), 
--	"TRIP_END" TIMESTAMP (6), 
--	"PICKUP" VARCHAR2(80 BYTE), 
--	"DESTINATION" VARCHAR2(80 BYTE), 
--	"JOB_TYPE" VARCHAR2(10 BYTE), 
--	"JOB_STATUS" VARCHAR2(10 BYTE), 
--	"PAX_PRIVILEGE" VARCHAR2(20 BYTE), 
--	"PRODUCT_ID" VARCHAR2(10 BYTE), 
--	"PRODUCT" VARCHAR2(40 BYTE), 
--	"PAYMENT_MODE" VARCHAR2(10 BYTE), 
--	"ACCOUNT_LV1" VARCHAR2(10 BYTE), 
--	"ACCOUNT_LV2" VARCHAR2(10 BYTE), 
--	"CARD_NO" VARCHAR2(20 BYTE), 
--	"APPROVAL_CODE" VARCHAR2(20 BYTE), 
--	"GST_INCLUSIVE" VARCHAR2(1 BYTE), 
--	"TXN_AMOUNT" NUMBER(6,2), 
--	"BOOKING_FEE" NUMBER(6,2), 
--	"ADMIN_AMOUNT" NUMBER(6,2), 
--	"GST_AMOUNT" NUMBER(6,2), 
--	"TOTAL_AMOUNT" NUMBER(6,2), 
--	"DRIVER_LEVY" NUMBER(6,2), 
--	"MERIT_POINT_FEE" NUMBER(6,2), 
--	"SURCHARGE_DESCRIPTION" VARCHAR2(80 BYTE), 
--	"CHARGED_TO" VARCHAR2(40 BYTE), 
--	"COMPLIMENTARY" VARCHAR2(1 BYTE), 
--	"STATUS" VARCHAR2(1 BYTE), 
--	"FMS_STATUS" VARCHAR2(1 BYTE), 
--	"FMS_DATE" TIMESTAMP (6), 
--	"CREATE_BY" VARCHAR2(10 BYTE), 
--	"CREATE_DATE" TIMESTAMP (6), 
--	"LAST_UPDATE_BY" VARCHAR2(10 BYTE), 
--	"LAST_UPDATE_DATE" TIMESTAMP (6), 
--	"SERVICE_TYPE" VARCHAR2(10 BYTE), 
--	"ACCOUNT_LV3" VARCHAR2(10 BYTE), 
--	"ACCOUNT_LV1_NAME" VARCHAR2(80 BYTE), 
--	"ACCOUNT_LV2_NAME" VARCHAR2(80 BYTE), 
--	"ACCOUNT_LV3_NAME" VARCHAR2(80 BYTE), 
--	"BOOKED_BY" VARCHAR2(15 BYTE), 
--	"ERROR_CODE" VARCHAR2(10 BYTE), 
--	"FLOWTHRU_ACTION" VARCHAR2(10 BYTE), 
--	"FLOWTHRU_BY" VARCHAR2(10 BYTE), 
--	"FLOWTHRU_DT" TIMESTAMP (6), 
--	"FLOWTHRU_COMMENTS" VARCHAR2(80 BYTE), 
--	"TID" VARCHAR2(8 BYTE), 
--	"CANCEL_REASON_CODE" NUMBER(22,0), 
--	"CANCEL_REASON_DESC" VARCHAR2(60 BYTE), 
--	"SURCHARGE_BREAKDOWN" VARCHAR2(80 BYTE), 
--	"TRIP_INTF_REF" VARCHAR2(20 BYTE), 
--	"REFUND" NUMBER(6,2), 
--	"CARD_TYPE" VARCHAR2(1 BYTE), 
--	"SETL_DATE" TIMESTAMP (6), 
--	"BANK_TID" VARCHAR2(8 BYTE), 
--	"BANK_BATCH_CLOSE_NO" VARCHAR2(6 BYTE), 
--	"COMPLETED_DT" TIMESTAMP (6), 
--	"SALES_DRAFT_NO" VARCHAR2(15 BYTE), 
--	"RECON_DATE" TIMESTAMP (6), 
--	"SCENARIO" VARCHAR2(20 BYTE), 
--	"IBS_STATUS" VARCHAR2(1 BYTE), 
--	"IBS_ERROR_CODE" VARCHAR2(10 BYTE), 
--	"IBS_DATE" TIMESTAMP (6), 
--	"ERROR_MSG" VARCHAR2(255 BYTE)
--   );
-- dumping some data into it

CREATE SEQUENCE  "ITTB_TRIPS_TXN_REQ_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE TABLE ITTB_TRIPS_TXN_REQ
(
  REQ_NO NUMBER(18) NOT NULL,
  STATUS VARCHAR2(1) NOT NULL,
  REQUEST_DATE DATE NOT NULL,
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP,
  VERSION NUMBER(9) DEFAULT 0
);
ALTER TABLE "ITTB_TRIPS_TXN_REQ" ADD CONSTRAINT "ITTB_TRIPS_TXN_REQ_PK" PRIMARY KEY ("REQ_NO") ENABLE;


DROP TABLE ITTB_TRIPS_TXN_REQ;
DROP TABLE ITTB_CNII_ACCT_REQ;
DROP TABLE ITTB_FMS_DRVR_RFND_COL_REQ;
DROP TABLE RCVW_INTF_TRIPS_FOR_IBS;
DROP TABLE ITTB_TRIPS_TXN_ERROR;
DROP TABLE ITTB_TRIPS_TXN;

DROP SEQUENCE ITTB_TRIPS_TXN_REQ_SQ1;
DROP SEQUENCE ITTB_CNII_ACCT_REQ_SQ1;
DROP SEQUENCE ITTB_FMS_DRVR_RFND_COL_REQ_SQ1;