/**********************************************/
/**************** DROP STATMENTS **************/
/**********************************************/

DROP TABLE FMTB_GL_LOG_DETAIL;
DROP TABLE FMTB_GL_LOG_HEADER;
DROP TABLE BMTB_BILL_GEN_REQ_DETAIL 		cascade constraints;
DROP TABLE BMTB_BILL_GEN_REQ 				cascade constraints;
DROP TABLE BMTB_BILL_GEN_SETUP 				cascade constraints;
DROP TABLE BMTB_BILL_GEN_ERROR 				cascade constraints;
DROP TABLE BMTB_INVOICE_FILE 				cascade constraints;
DROP TABLE BMTB_INVOICE_HEADER 				cascade constraints;
DROP TABLE BMTB_INVOICE_SUMMARY 			cascade constraints;
DROP TABLE BMTB_INVOICE_DETAIL 				cascade constraints;
DROP TABLE BMTB_INVOICE_TXN 				cascade constraints;
DROP TABLE BMTB_INVOICE_PAYMENT_HEADER 		cascade constraints;
DROP TABLE BMTB_INVOICE_PAYMENT_DETAIL 		cascade constraints;
DROP TABLE BMTB_PAYMENT_RECEIPT 			cascade constraints;
DROP TABLE BMTB_PAYMENT_RECEIPT_DETAIL 		cascade constraints;
DROP TABLE BMTB_NOTE 						cascade constraints;
DROP TABLE BMTB_LAST_INVOICE_LOG			cascade constraints;
DROP TABLE BMTB_INVOICE_DEPOSIT_TXN			cascade constraints;
DROP TABLE BMTB_DRAFT_INV_FILE 				cascade constraints;
DROP TABLE BMTB_DRAFT_INV_HEADER 			cascade constraints;
DROP TABLE BMTB_DRAFT_INV_SUMMARY 			cascade constraints;
DROP TABLE BMTB_DRAFT_INV_DETAIL 			cascade constraints;
DROP TABLE BMTB_DRAFT_INV_TXN 				cascade constraints;
DROP TABLE BMTB_DRAFT_INV_PAYMENT_HEADER 	cascade constraints;
DROP TABLE BMTB_DRAFT_INV_PAYMENT_DETAIL 	cascade constraints;
DROP TABLE BMTB_INVOICE_PRINT_REQ 			cascade constraints;
DROP TABLE ITTB_CP_LOGIN					cascade constraints;

DROP SEQUENCE FMTB_GL_LOG_DETAIL_SQ1;
DROP SEQUENCE FMTB_GL_LOG_HEADER_SQ1;
DROP SEQUENCE BMTB_BILL_GEN_REQ_SQ1;
DROP SEQUENCE BMTB_BILL_GEN_ERROR_SQ1;
DROP SEQUENCE BMTB_INVOICE_FILE_SQ1;
DROP SEQUENCE BMTB_INVOICE_HEADER_SQ1;
DROP SEQUENCE BMTB_INVOICE_HEADER_SQ2;
DROP SEQUENCE BMTB_INVOICE_SUMMARY_SQ1;
DROP SEQUENCE BMTB_INVOICE_DETAIL_SQ1;
DROP SEQUENCE BMTB_INVOICE_TXN_SQ1;
DROP SEQUENCE BMTB_INVOICE_PAYMENT_HEA_SQ1;
DROP SEQUENCE BMTB_INVOICE_PAYMENT_DET_SQ1;
DROP SEQUENCE BMTB_PAYMENT_RECEIPT_SQ1;
DROP SEQUENCE BMTB_PAYMENT_RECEIPT_DET_SQ1;
DROP SEQUENCE BMTB_NOTE_SQ1;
DROP SEQUENCE BMTB_INVOICE_DEPOSIT_TXN_SQ1;
DROP SEQUENCE BMTB_DRAFT_INV_FILE_SQ1;
DROP SEQUENCE BMTB_DRAFT_INV_HEADER_SQ1;
DROP SEQUENCE BMTB_DRAFT_INV_HEADER_SQ2;
DROP SEQUENCE BMTB_DRAFT_INV_SUMMARY_SQ1;
DROP SEQUENCE BMTB_DRAFT_INV_DETAIL_SQ1;
DROP SEQUENCE BMTB_DRAFT_INV_TXN_SQ1;
DROP SEQUENCE BMTB_DRAFT_INV_PYMT_HEADER_SQ1;
DROP SEQUENCE BMTB_DRAFT_INV_PYMT_DETAIL_SQ1;
DROP SEQUENCE BMTB_INVOICE_PRINT_REQ_SQ1;

/**********************************************/
/**************** SEQUENCE ********************/
/**********************************************/

CREATE SEQUENCE  "BMTB_BILL_GEN_REQ_SQ1"  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_BILL_GEN_ERROR_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_INVOICE_FILE_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_INVOICE_HEADER_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_INVOICE_HEADER_SQ2"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_INVOICE_SUMMARY_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_INVOICE_DETAIL_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_INVOICE_TXN_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_INVOICE_PAYMENT_HEA_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_INVOICE_PAYMENT_DET_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_PAYMENT_RECEIPT_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_PAYMENT_RECEIPT_DET_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_NOTE_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_INVOICE_DEPOSIT_TXN_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_DRAFT_INV_FILE_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_DRAFT_INV_HEADER_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_DRAFT_INV_HEADER_SQ2"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_DRAFT_INV_SUMMARY_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_DRAFT_INV_DETAIL_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_DRAFT_INV_TXN_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_DRAFT_INV_PYMT_HEADER_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_DRAFT_INV_PYMT_DETAIL_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_INVOICE_PRINT_REQ_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;

/**********************************************/
/**************** TABLES **********************/
/**********************************************/

CREATE TABLE BMTB_BILL_GEN_SETUP
(
  SETUP_NO NUMBER(9) NOT NULL,
  NAME VARCHAR2(80) NOT NULL,
  CUT_OFF_DAY NUMBER(2),
  BILL_GEN_DAY NUMBER(2),
  BILL_GEN_TIME VARCHAR2(5),
  INVOICE_DAY NUMBER(2),
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP,
  VERSION NUMBER(9) DEFAULT 0
)
;

ALTER TABLE "BMTB_BILL_GEN_SETUP" ADD CONSTRAINT "BMTB_BILL_GEN_SETUP_PK" PRIMARY KEY ("SETUP_NO") ENABLE;
ALTER TABLE BMTB_BILL_GEN_SETUP ADD CONSTRAINT BMCT_BILL_GEN_SETUP_U1 UNIQUE(NAME) ENABLE;
COMMENT ON COLUMN BMTB_BILL_GEN_SETUP.BILL_GEN_TIME IS 'format is 24HH:00';

/***************************************************************/

CREATE TABLE BMTB_BILL_GEN_REQ
(
  REQ_NO NUMBER(9) NOT NULL,
  STATUS VARCHAR2(1) NOT NULL,
  SETUP_NO NUMBER(9) NOT NULL,
  REGEN_REQ_NO NUMBER(9),
  REGEN_SETUP_NO NUMBER(9),
  BILL_GEN_MONTH NUMBER(2) NOT NULL,
  REQUEST_DATE DATE NOT NULL,
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP,
  VERSION NUMBER(9) DEFAULT 0
)
;

COMMENT ON COLUMN BMTB_BILL_GEN_REQ.REQUEST_DATE IS 'The date which the batch job will pickup the request';
COMMENT ON COLUMN BMTB_BILL_GEN_REQ.STATUS IS 'Status of the Bill Gen P - Pending R - Rescheduled C - Completed';
COMMENT ON COLUMN BMTB_BILL_GEN_REQ.REGEN_REQ_NO IS 'Ad hoc bill gen based on previous error bill gen request. It is like a regen of the previous bill gen request for selected accounts';
ALTER TABLE "BMTB_BILL_GEN_REQ" ADD CONSTRAINT "BMTB_BILL_GEN_REQ_PK" PRIMARY KEY ("REQ_NO") ENABLE;
ALTER TABLE BMTB_BILL_GEN_REQ ADD CONSTRAINT BMTB_BILL_GEN_REQ_FK1 FOREIGN KEY ("SETUP_NO") REFERENCES BMTB_BILL_GEN_SETUP ("SETUP_NO") ENABLE;
ALTER TABLE BMTB_BILL_GEN_REQ ADD CONSTRAINT BMTB_BILL_GEN_REQ_FK2 FOREIGN KEY ("REGEN_REQ_NO") REFERENCES BMTB_BILL_GEN_REQ ("REQ_NO") ENABLE;
ALTER TABLE BMTB_BILL_GEN_REQ ADD CONSTRAINT BMTB_BILL_GEN_REQ_FK3 FOREIGN KEY ("REGEN_SETUP_NO") REFERENCES BMTB_BILL_GEN_SETUP ("SETUP_NO") ENABLE;

/***************************************************************/

CREATE TABLE BMTB_BILL_GEN_ERROR
(
  ERROR_NO NUMBER(18) NOT NULL,
  REQ_NO NUMBER(9) NOT NULL,
  TOP_LEVEL_ACCOUNT_NO NUMBER(8) NOT NULL,
  BILLABLE_ACCOUNT_NO NUMBER(8) NOT NULL,
  ERROR_MSG VARCHAR2(255),
  ERROR_DT TIMESTAMP NOT NULL
)
;

ALTER TABLE BMTB_BILL_GEN_ERROR ADD CONSTRAINT BMTB_BILL_GEN_ERROR_PK PRIMARY KEY ("ERROR_NO") ENABLE;
ALTER TABLE BMTB_BILL_GEN_ERROR ADD CONSTRAINT BMTB_BILL_GEN_ERROR_FK1 FOREIGN KEY ("REQ_NO") REFERENCES BMTB_BILL_GEN_REQ ("REQ_NO") ENABLE;
ALTER TABLE BMTB_BILL_GEN_ERROR ADD CONSTRAINT BMTB_BILL_GEN_ERROR_FK2 FOREIGN KEY ("TOP_LEVEL_ACCOUNT_NO") REFERENCES AMTB_ACCOUNT ("ACCOUNT_NO") ENABLE;
ALTER TABLE BMTB_BILL_GEN_ERROR ADD CONSTRAINT BMTB_BILL_GEN_ERROR_FK3 FOREIGN KEY ("BILLABLE_ACCOUNT_NO") REFERENCES AMTB_ACCOUNT ("ACCOUNT_NO") ENABLE;

/***************************************************************/

CREATE TABLE BMTB_BILL_GEN_REQ_DETAIL
(
  REQ_NO NUMBER(9) NOT NULL,
  ACCOUNT_NO NUMBER(8) NOT NULL
)
;

ALTER TABLE "BMTB_BILL_GEN_REQ_DETAIL" ADD CONSTRAINT "BMTB_BILL_GEN_REQ_DET_PK" PRIMARY KEY ("REQ_NO", "ACCOUNT_NO") ENABLE;
ALTER TABLE BMTB_BILL_GEN_REQ_DETAIL ADD CONSTRAINT BMTB_BILL_GEN_REQ_DET_FK1 FOREIGN KEY(ACCOUNT_NO) REFERENCES AMTB_ACCOUNT(ACCOUNT_NO) ENABLE;
ALTER TABLE BMTB_BILL_GEN_REQ_DETAIL ADD CONSTRAINT BMTB_BILL_GEN_REQ_DET_FK2 FOREIGN KEY(REQ_NO) REFERENCES BMTB_BILL_GEN_REQ(REQ_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_INVOICE_FILE
(
  FILE_NO NUMBER(18) NOT NULL,
  INVOICE_FILE BLOB,
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP,
  VERSION NUMBER(9) DEFAULT 0
)
;

ALTER TABLE BMTB_INVOICE_FILE ADD CONSTRAINT BMTB_INVOICE_FILE_PK PRIMARY KEY (FILE_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_INVOICE_HEADER
(
  INVOICE_HEADER_NO NUMBER(18) NOT NULL,
  REQ_NO NUMBER(18),
  ACCOUNT_NO NUMBER(8) NOT NULL,
  DEBT_TO NUMBER(8) NOT NULL,
  INVOICE_NO NUMBER(18),
  INVOICE_DATE DATE NOT NULL,
  INVOICE_STATUS VARCHAR2(1) NOT NULL,
  INVOICE_FORMAT VARCHAR2(1) NOT NULL,
  DUE_DATE DATE,
  STATEMENT_PERIOD_FROM_DATE DATE,
  STATEMENT_PERIOD_TO_DATE DATE,
  PREV_BALANCE NUMBER(12,2) DEFAULT 0 NOT NULL,
  PREV_PAYMENT NUMBER(12,2) DEFAULT 0 NOT NULL,
  NEW_TXN NUMBER(12,2) DEFAULT 0 NOT NULL,
  NEW_BALANCE NUMBER(12,2) DEFAULT 0 NOT NULL,
  LESS_30_DAYS NUMBER(12,2) DEFAULT 0 NOT NULL,
  LESS_60_DAYS NUMBER(12,2) DEFAULT 0 NOT NULL,
  LESS_90_DAYS NUMBER(12,2) DEFAULT 0 NOT NULL,
  MORE_90_DAYS NUMBER(12,2) DEFAULT 0 NOT NULL,
  PREV_REWARDS_PTS NUMBER(8) DEFAULT 0,
  REDEEMED_REWARDS_PTS NUMBER(8) DEFAULT 0,
  NEW_REWARDS_PTS NUMBER(8) DEFAULT 0,
  TOTAL_REWARDS_PTS NUMBER(8) DEFAULT 0,
  ACCOUNT_DEPOSIT NUMBER(12,2) DEFAULT 0,
  ACCOUNT_EXCESS NUMBER(12,2) DEFAULT 0,
  OVERDUE_INVOICE VARCHAR2(255),
  TXN_CUTOFF_DATE DATE,
  LATE_PAYMENT_INTEREST NUMBER(5,2) DEFAULT 0 NOT NULL,
  LATE_PAYMENT_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  LAST_LATE_PAYMENT_CHARGED_DATE DATE,
  LATE_PAYMENT_FLAG VARCHAR2(1) DEFAULT 'N' NOT NULL,
  EARLY_PAYMENT_FLAG VARCHAR2(1) DEFAULT 'N' NOT NULL,
  OUTSTANDING_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  TOTAL_FARE_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  TOTAL_NO_OF_TRIP NUMBER(8,0) DEFAULT 0 NOT NULL,
  REMARKS VARCHAR2(500),
  BILLED_FLAG VARCHAR2(1),
  FILE_NO NUMBER(18),
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP,
  VERSION NUMBER(9) DEFAULT 0
)
;

COMMENT ON COLUMN BMTB_INVOICE_HEADER.TOTAL_FARE_AMOUNT IS 'FOR CALCULATION OF VOLUME DISCOUNT';
COMMENT ON COLUMN BMTB_INVOICE_HEADER.TOTAL_NO_OF_TRIP IS 'FOR CALCULATION OF VOLUME DISCOUNT';
COMMENT ON COLUMN BMTB_INVOICE_HEADER.LATE_PAYMENT_FLAG IS 'N = NO, Y = YES';
COMMENT ON COLUMN BMTB_INVOICE_HEADER.INVOICE_STATUS IS 'O = OUSTANDING, C = CLOSED';
COMMENT ON COLUMN BMTB_INVOICE_HEADER.INVOICE_FORMAT IS 'A = ACCOUNT FORMAT, S = SUBACCOUNT, P = PERSONAL, M = MISC, D = DEPOSIT';
ALTER TABLE "BMTB_INVOICE_HEADER" ADD CONSTRAINT "BMTB_INVOICE_HEADER_PK" PRIMARY KEY ("INVOICE_HEADER_NO") ENABLE;
ALTER TABLE BMTB_INVOICE_HEADER ADD CONSTRAINT BMTB_INVOICE_HEADER_FK1 FOREIGN KEY(ACCOUNT_NO) REFERENCES AMTB_ACCOUNT(ACCOUNT_NO) ENABLE;
ALTER TABLE BMTB_INVOICE_HEADER ADD CONSTRAINT BMTB_INVOICE_HEADER_FK2 FOREIGN KEY(DEBT_TO) REFERENCES AMTB_ACCOUNT(ACCOUNT_NO) ENABLE;
ALTER TABLE BMTB_INVOICE_HEADER ADD CONSTRAINT BMTB_INVOICE_HEADER_FK3 FOREIGN KEY(REQ_NO) REFERENCES BMTB_BILL_GEN_REQ(REQ_NO) ENABLE;
ALTER TABLE BMTB_INVOICE_HEADER ADD CONSTRAINT BMTB_INVOICE_HEADER_FK4 FOREIGN KEY(FILE_NO) REFERENCES BMTB_INVOICE_FILE(FILE_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_INVOICE_SUMMARY
(
  INVOICE_SUMMARY_NO NUMBER(18) NOT NULL,
  INVOICE_HEADER_NO NUMBER(18) NOT NULL,
  ACCOUNT_NO NUMBER(8) ,
  PRODUCT_TYPE_ID VARCHAR2(2) ,
  SUMMARY_TYPE VARCHAR2(2) ,
  SUMMARY_NAME VARCHAR2(80) NOT NULL,
  DISPLAY_PRIORITY_1 NUMBER(1) NOT NULL,
  DISPLAY_PRIORITY_2 NUMBER(1) NOT NULL,
  PREV_BALANCE NUMBER(12,2) DEFAULT 0 NOT NULL,
  PREV_PAYMENT NUMBER(12,2) DEFAULT 0 NOT NULL,
  NEW_TXN NUMBER(12,2) DEFAULT 0 NOT NULL,
  ADMIN_FEE NUMBER(12,2) DEFAULT 0 NOT NULL,
  GST NUMBER(12,2) DEFAULT 0 NOT NULL,
  TOTAL_NEW NUMBER(12,2) DEFAULT 0 NOT NULL,
  BALANCE NUMBER(12,2) DEFAULT 0 NOT NULL,
  UNIT_PRICE NUMBER(12,2) DEFAULT 0,
  QUANTITY NUMBER(18) DEFAULT 0,
  DISCOUNT NUMBER(12,2) DEFAULT 0,
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP
)
;

COMMENT ON COLUMN BMTB_INVOICE_SUMMARY.UNIT_PRICE IS 'APPLICABLE FOR MISC INVOICE ONLY';
COMMENT ON COLUMN BMTB_INVOICE_SUMMARY.QUANTITY IS 'APPLICABLE FOR MISC INVOICE ONLY';
COMMENT ON COLUMN BMTB_INVOICE_SUMMARY.DISCOUNT IS 'APPLICABLE FOR MISC INVOICE ONLY';
COMMENT ON COLUMN BMTB_INVOICE_SUMMARY.SUMMARY_TYPE IS 'TRANSACTION SUMMARY SECTION GROUPING NAME (ACCOUNT NAME + ACCOUNT CODE)';
COMMENT ON COLUMN BMTB_INVOICE_SUMMARY.SUMMARY_NAME IS 'INDIVIDUAL PRODUCT TYPE NAME IN THE TRANSACTION SUMMARY SECTION';
ALTER TABLE "BMTB_INVOICE_SUMMARY" ADD CONSTRAINT "BMTB_INVOICE_SUMMARY_PK" PRIMARY KEY ("INVOICE_SUMMARY_NO") ENABLE;
ALTER TABLE BMTB_INVOICE_SUMMARY ADD CONSTRAINT BMTB_INVOICE_SUMMARY_FK1 FOREIGN KEY(INVOICE_HEADER_NO) REFERENCES BMTB_INVOICE_HEADER(INVOICE_HEADER_NO) ENABLE;
ALTER TABLE BMTB_INVOICE_SUMMARY ADD CONSTRAINT BMTB_INVOICE_SUMMARY_FK2 FOREIGN KEY(PRODUCT_TYPE_ID) REFERENCES PMTB_PRODUCT_TYPE(PRODUCT_TYPE_ID) ENABLE;
ALTER TABLE BMTB_INVOICE_SUMMARY ADD CONSTRAINT BMTB_INVOICE_SUMMARY_FK3 FOREIGN KEY(ACCOUNT_NO) REFERENCES AMTB_ACCOUNT(ACCOUNT_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_INVOICE_DETAIL
(
  INVOICE_DETAIL_NO NUMBER(18) NOT NULL,
  INVOICE_SUMMARY_NO NUMBER(18) NOT NULL,
  PRODUCT_NO NUMBER(19) ,
  PRODUCT_TYPE_ID VARCHAR2(2),
  ACCOUNT_NO NUMBER(8) NOT NULL,
  INVOICE_DETAIL_NAME VARCHAR2(80),
  INVOICE_DETAIL_TYPE VARCHAR2(2) NOT NULL,
  NEW_TXN NUMBER(12,2) DEFAULT 0 NOT NULL,
  ADMIN_FEE NUMBER(12,2) DEFAULT 0 NOT NULL,
  GST NUMBER(12,2) DEFAULT 0 NOT NULL,
  TOTAL_NEW NUMBER(12,2) DEFAULT 0 NOT NULL,
  CARD_NAME VARCHAR2(80),
  CARD_NO VARCHAR2(19),
  CARD_CREDIT_LIMIT NUMBER(12,2),
  CARD_REPLACEMENT NUMBER(12,2),
  CARD_REPLACEMENT_GST NUMBER(12,2),
  CARD_REPLACEMENT_GST_PERCENT NUMBER(5,2),
  SUBSCRIPTION_FEE NUMBER(12,2),
  SUBSCRIPTION_FEE_GST NUMBER(12,2),
  SUBSCRIPTION_FEE_GST_PERCENT NUMBER(5,2),
  ORI_ADMIN_FEE NUMBER(12,2) DEFAULT 0 NOT NULL,
  PROD_DIS NUMBER(12,2) DEFAULT 0 NOT NULL,
  PROMO_DIS NUMBER(12,2) DEFAULT 0 NOT NULL,
  TXN_CODE NUMBER(8),
  OUTSTANDING_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP,
  VERSION NUMBER(9) DEFAULT 0
)
;

COMMENT ON COLUMN BMTB_INVOICE_DETAIL.CARD_REPLACEMENT IS 'A SNAPSHOT OF THE REPLACEMENT FEE AMOUNT BUT NOT ACCUMULATED INTO DETAIL OUTSTANDING AMOUNT';
COMMENT ON COLUMN BMTB_INVOICE_DETAIL.INVOICE_DETAIL_NAME IS 'NAME TO BE DISPLAYED AS THE DETAIL HEADER, NOT APPLICABLE TO PERSONAL FORMAT';
COMMENT ON COLUMN BMTB_INVOICE_DETAIL.INVOICE_DETAIL_TYPE IS 'TO INDICATE WHETHER IT IS A NORMAL OR CREDIT/DEBIT DETAIL: N = NORMAL, C = CREDIT/DEBIT';
ALTER TABLE "BMTB_INVOICE_DETAIL" ADD CONSTRAINT "BMTB_INVOICE_DETAIL_PK" PRIMARY KEY ("INVOICE_DETAIL_NO") ENABLE;
ALTER TABLE BMTB_INVOICE_DETAIL ADD CONSTRAINT BMTB_INVOICE_DETAIL_FK1 FOREIGN KEY(INVOICE_SUMMARY_NO) REFERENCES BMTB_INVOICE_SUMMARY(INVOICE_SUMMARY_NO) ENABLE;
ALTER TABLE BMTB_INVOICE_DETAIL ADD CONSTRAINT BMTB_INVOICE_DETAIL_FK2 FOREIGN KEY(PRODUCT_NO) REFERENCES PMTB_PRODUCT(PRODUCT_NO) ENABLE;
ALTER TABLE BMTB_INVOICE_DETAIL ADD CONSTRAINT BMTB_INVOICE_DETAIL_FK3 FOREIGN KEY(ACCOUNT_NO) REFERENCES AMTB_ACCOUNT(ACCOUNT_NO) ENABLE;
ALTER TABLE BMTB_INVOICE_DETAIL ADD CONSTRAINT BMTB_INVOICE_DETAIL_FK4 FOREIGN KEY(PRODUCT_TYPE_ID) REFERENCES PMTB_PRODUCT_TYPE(PRODUCT_TYPE_ID) ENABLE;
ALTER TABLE BMTB_INVOICE_DETAIL ADD CONSTRAINT BMTB_INVOICE_DETAIL_FK5 FOREIGN KEY(TXN_CODE) REFERENCES FMTB_TRANSACTION_CODE(TRANSACTION_CODE_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_INVOICE_TXN
(
  INVOICE_TXN_NO NUMBER(18) NOT NULL,
  INVOICE_DETAIL_NO NUMBER(18) NOT NULL,
  ACQUIRE_TXN_NO NUMBER(8) ,
  CARD_NO VARCHAR2(19),
  JOB_TYPE VARCHAR2(80),
  JOB_REF_NO VARCHAR2(10),
  FLIGHT_INFO VARCHAR2(40),
  BOOKING_REF VARCHAR2(40),
  BOOKED_BY VARCHAR2(80),
  TAXI_NO VARCHAR2(10),
  VEHICLE_TYPE VARCHAR2(500),
  PICKUP VARCHAR2(255),
  DESTINATION VARCHAR2(255),
  TXN_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  ADMIN_FEE NUMBER(12,2) DEFAULT 0 NOT NULL,
  ADMIN_FEE_PERCENT NUMBER(5,2) DEFAULT 0 NOT NULL,
  GST NUMBER(12,2) DEFAULT 0 NOT NULL,
  GST_PERCENT NUMBER(5,2) DEFAULT 0 NOT NULL,
  "ORI_ADMIN_FEE" NUMBER(12,2) DEFAULT 0 NOT NULL,
  "PROD_DIS_PERCENT" NUMBER(5,2) DEFAULT 0 NOT NULL, 
  "PROD_DIS_VALUE" NUMBER(12,2) DEFAULT 0 NOT NULL, 
  "PROMO_DIS_PERCENT" NUMBER(5,2) DEFAULT 0 NOT NULL, 
  "PROMO_DIS_VALUE" NUMBER(12,2) DEFAULT 0 NOT NULL,
  TOTAL NUMBER(12,2) DEFAULT 0,
  PASSENGER_NAME VARCHAR2(80),
  SURCHARGE VARCHAR2(255),
  TRIP_START_DT TIMESTAMP,
  TRIP_END_DT TIMESTAMP,
  PROJECT_CODE VARCHAR2(80),
  ISSUED_INVOICE_HEADER_NO NUMBER(18),
  ISSUED_INVOICE_NO NUMBER(18),
  ISSUED_INVOICE_DATE DATE, 
  NOTE VARCHAR2(20),
  DESCRIPTION VARCHAR2(255),
  HOTEL_INFO VARCHAR2(255),
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP
)
;

COMMENT ON COLUMN BMTB_INVOICE_TXN.DESCRIPTION IS 'USED FOR TRANSACTION DETAILS LIKE CREDIT/DEBIT NOTE DESCRIPTION: WAIVE LATE PAYMENT';
ALTER TABLE "BMTB_INVOICE_TXN" ADD CONSTRAINT "BMTB_INVOICE_TXN_PK" PRIMARY KEY ("INVOICE_TXN_NO") ENABLE;
ALTER TABLE BMTB_INVOICE_TXN ADD CONSTRAINT BMTB_INVOICE_TXN_FK1 FOREIGN KEY(INVOICE_DETAIL_NO) REFERENCES BMTB_INVOICE_DETAIL(INVOICE_DETAIL_NO) ENABLE;
ALTER TABLE BMTB_INVOICE_TXN ADD CONSTRAINT BMTB_INVOICE_TXN_FK2 FOREIGN KEY(ISSUED_INVOICE_HEADER_NO) REFERENCES BMTB_INVOICE_HEADER(INVOICE_HEADER_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_INVOICE_PAYMENT_HEADER
(
  INVOICE_PAYMENT_NO NUMBER(18) NOT NULL,
  INVOICE_HEADER_NO NUMBER(18) NOT NULL,
  HEADER_TYPE VARCHAR2(1) NOT NULL,
  PAYMENT_TYPE VARCHAR2(50) NOT NULL,
  PAYMENT_REF_NO VARCHAR2(30) NULL,
  PAYMENT_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP
)
;

COMMENT ON COLUMN BMTB_INVOICE_PAYMENT_HEADER.HEADER_TYPE IS 'R = PAYMENT RECEIVED, C = PAYMENT CANCELED, A = PAYMENT APPLIED';
COMMENT ON COLUMN BMTB_INVOICE_PAYMENT_HEADER.PAYMENT_TYPE IS 'EXAMPLE CONTRA OR CREDIT CARD';
ALTER TABLE "BMTB_INVOICE_PAYMENT_HEADER" ADD CONSTRAINT "BMTB_INVOICE_PAYMENT_HEADER_PK" PRIMARY KEY ("INVOICE_PAYMENT_NO") ENABLE;
ALTER TABLE BMTB_INVOICE_PAYMENT_HEADER ADD CONSTRAINT BMTB_INVOICE_PAYMENT_HEA_FK1 FOREIGN KEY(INVOICE_HEADER_NO) REFERENCES BMTB_INVOICE_HEADER(INVOICE_HEADER_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_INVOICE_PAYMENT_DETAIL
(
  INVOICE_PAYMENT_DETAIL_NO NUMBER(18) NOT NULL,
  INVOICE_PAYMENT_NO NUMBER(18) NOT NULL,
  INVOICE_NO NUMBER(18) NOT NULL,
  ACCOUNT_NAME VARCHAR2(80) NOT NULL,
  PAYMENT_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP
)
;

ALTER TABLE "BMTB_INVOICE_PAYMENT_DETAIL" ADD CONSTRAINT "BMTB_INVOICE_PAYMENT_DETAIL_PK" PRIMARY KEY ("INVOICE_PAYMENT_DETAIL_NO") ENABLE;
ALTER TABLE BMTB_INVOICE_PAYMENT_DETAIL ADD CONSTRAINT BMTB_INVOICE_PAYMENT_DET_FK1 FOREIGN KEY(INVOICE_PAYMENT_NO) REFERENCES BMTB_INVOICE_PAYMENT_HEADER(INVOICE_PAYMENT_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_PAYMENT_RECEIPT
(
  PAYMENT_RECEIPT_NO NUMBER(18) NOT NULL,
  ACCOUNT_NO NUMBER(8) NOT NULL,
  PAYMENT_NO VARCHAR2(30),
  PAYMENT_MODE NUMBER(8) NOT NULL,
  PAYMENT_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  EXCESS_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  PAYMENT_DATE DATE NOT NULL,
  RECEIPT_DT TIMESTAMP NOT NULL,
  CANCEL_DT TIMESTAMP,
  CANCELLATION_REASON NUMBER(8),
  CANCEL_REMARKS VARCHAR2(500),
  BANK NUMBER(8),
  BRANCH NUMBER(8),
  BANK_IN NUMBER(8),
  QUICK_CHEQUE_DEPOSIT VARCHAR2(1),
  CHEQUE_NO VARCHAR2(20),
  CHEQUE_DATE DATE,
  REMARKS VARCHAR2(500),
  BILLED_FLAG VARCHAR2(1) NOT NULL,
  CANCEL_BILLED_FLAG VARCHAR2(1) NOT NULL DEFAULT 'N',
  MEMO_RECEIPT_NO NUMBER(18),
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP,
  VERSION NUMBER(9) DEFAULT 0
)
;

COMMENT ON COLUMN BMTB_PAYMENT_RECEIPT.PAYMENT_MODE IS 'MODE OF PAYMENT E.G. CHEQUE/CREDIT CARD/CONTRA. PAYMENT MODE IS PICKED FROM MASTER TABLE.';
COMMENT ON COLUMN BMTB_PAYMENT_RECEIPT.QUICK_CHEQUE_DEPOSIT IS 'Y/N TO INDICATE WHETHER THE CHEQUE IS A QUICK DEPOSIT';
COMMENT ON COLUMN BMTB_PAYMENT_RECEIPT.PAYMENT_NO IS 'PAYMENT REFERENCE NO';
COMMENT ON COLUMN BMTB_PAYMENT_RECEIPT.BILLED_FLAG IS 'TO INDICATE WHETHER PAYMENT RECEIPT IS BILLED SO THAT NEXT APPLIED AMOUNT IS SHOWN DIFFERENTLY ON THE NEXT INVOICE';
ALTER TABLE "BMTB_PAYMENT_RECEIPT" ADD CONSTRAINT "BMTB_PAYMENT_RECEIPT_PK" PRIMARY KEY ("PAYMENT_RECEIPT_NO") ENABLE;
ALTER TABLE BMTB_PAYMENT_RECEIPT ADD CONSTRAINT BMTB_PAYMENT_RECEIPT_FK1 FOREIGN KEY(ACCOUNT_NO) REFERENCES AMTB_ACCOUNT(ACCOUNT_NO) ENABLE;
ALTER TABLE BMTB_PAYMENT_RECEIPT ADD CONSTRAINT BMTB_PAYMENT_RECEIPT_FK2 FOREIGN KEY(PAYMENT_MODE) REFERENCES MSTB_MASTER_TABLE(MASTER_NO) ENABLE;
ALTER TABLE BMTB_PAYMENT_RECEIPT ADD CONSTRAINT BMTB_PAYMENT_RECEIPT_FK3 FOREIGN KEY(BANK) REFERENCES MSTB_BANK_MASTER(BANK_MASTER_NO) ENABLE;
ALTER TABLE BMTB_PAYMENT_RECEIPT ADD CONSTRAINT BMTB_PAYMENT_RECEIPT_FK4 FOREIGN KEY(BRANCH) REFERENCES MSTB_BRANCH_MASTER(BRANCH_MASTER_NO) ENABLE;
ALTER TABLE BMTB_PAYMENT_RECEIPT ADD CONSTRAINT BMTB_PAYMENT_RECEIPT_FK5 FOREIGN KEY(BANK_IN) REFERENCES FMTB_BANK_CODE(BANK_CODE_NO) ENABLE;
ALTER TABLE BMTB_PAYMENT_RECEIPT ADD CONSTRAINT BMTB_PAYMENT_RECEIPT_FK7 FOREIGN KEY(CANCELLATION_REASON) REFERENCES MSTB_MASTER_TABLE(MASTER_NO) ENABLE;
ALTER TABLE BMTB_PAYMENT_RECEIPT ADD CONSTRAINT BMTB_PAYMENT_RECEIPT_FK8 FOREIGN KEY(MEMO_RECEIPT_NO) REFERENCES BMTB_PAYMENT_RECEIPT(PAYMENT_RECEIPT_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_PAYMENT_RECEIPT_DETAIL
(
  PAYMENT_RECEIPT_DETAIL_NO NUMBER(18) NOT NULL,
  PAYMENT_RECEIPT_NO NUMBER(18) NOT NULL,
  INVOICE_HEADER_NO NUMBER(18) NOT NULL,
  INVOICE_DETAIL_NO NUMBER(18) NOT NULL,
  APPLIED_AMOUNT NUMBER(12,2),
  DEDUCTED_CREDIT_BALANCE NUMBER(12,2) NOT NULL,
  BILLED_FLAG VARCHAR2(1) NOT NULL,
  CANCEL_BILLED_FLAG VARCHAR2(1) NOT NULL DEFAULT 'N',
  INVOICE_PAYMENT_NO NUMBER(18),
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP,
  VERSION NUMBER(9) DEFAULT 0
)
;

ALTER TABLE "BMTB_PAYMENT_RECEIPT_DETAIL" ADD CONSTRAINT "BMTB_PAYMENT_RECEIPT_DETAIL_PK" PRIMARY KEY ("PAYMENT_RECEIPT_DETAIL_NO") ENABLE;
ALTER TABLE BMTB_PAYMENT_RECEIPT_DETAIL ADD CONSTRAINT BMTB_PAYMENT_RECEIPT_DET_FK1 FOREIGN KEY(PAYMENT_RECEIPT_NO) REFERENCES BMTB_PAYMENT_RECEIPT(PAYMENT_RECEIPT_NO) ENABLE;
ALTER TABLE BMTB_PAYMENT_RECEIPT_DETAIL ADD CONSTRAINT BMTB_PAYMENT_RECEIPT_DET_FK2 FOREIGN KEY(INVOICE_HEADER_NO) REFERENCES BMTB_INVOICE_HEADER(INVOICE_HEADER_NO) ENABLE;
ALTER TABLE BMTB_PAYMENT_RECEIPT_DETAIL ADD CONSTRAINT BMTB_PAYMENT_RECEIPT_DET_FK3 FOREIGN KEY(INVOICE_DETAIL_NO) REFERENCES BMTB_INVOICE_DETAIL(INVOICE_DETAIL_NO) ENABLE;
ALTER TABLE BMTB_PAYMENT_RECEIPT_DETAIL ADD CONSTRAINT BMTB_PAYMENT_RECEIPT_DET_FK4 FOREIGN KEY(INVOICE_PAYMENT_NO) REFERENCES BMTB_INVOICE_PAYMENT_HEADER(INVOICE_PAYMENT_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_NOTE
(
  NOTE_NO NUMBER(18) NOT NULL,
  ACCOUNT_NO NUMBER(8) NOT NULL,
  ISSUED_INVOICE_HEADER_NO NUMBER(18),
  ISSUED_INVOICE_TXN_NO NUMBER(18),
  BILLED_INVOICE_TXN_NO NUMBER(18),
  NOTE_TYPE VARCHAR2(1) NOT NULL,
  NOTE_TXN_TYPE VARCHAR2(1) NOT NULL,
  NOTE_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL, --note/refund txn amount
  DISCOUNT NUMBER(12,2) DEFAULT 0 NOT NULL, --note discount amount
  ADMIN_FEE NUMBER(12,2) DEFAULT 0 NOT NULL, --original admin fee
  PROD_DIS NUMBER(12,2) DEFAULT 0 NOT NULL, --product discount
  GST NUMBER(12,2) DEFAULT 0 NOT NULL, --note gst/refund txn gst after discounted admin
  TXN_CODE NUMBER(8),
  REASON NUMBER(8,0),
  CANCELLATION_REASON NUMBER(8,0),
  REMARKS VARCHAR2(500),
  STATUS VARCHAR2(1),
  CANCEL_DT TIMESTAMP,
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP,
  VERSION NUMBER(9) DEFAULT 0
)
;

COMMENT ON COLUMN BMTB_NOTE.NOTE_TYPE IS 'C = CREDIT NOTE, D = DEBIT NOTE';
COMMENT ON COLUMN BMTB_NOTE.NOTE_TXN_TYPE IS 'T = TRIP BASED, M = MISC CREDIT/DEBIT NOTE';
COMMENT ON COLUMN BMTB_NOTE.STATUS IS 'P = PENDING, B = BILLED, C = CANCELLED';
ALTER TABLE "BMTB_NOTE" ADD CONSTRAINT "BMTB_NOTE_PK" PRIMARY KEY ("NOTE_NO") ENABLE;
ALTER TABLE BMTB_NOTE ADD CONSTRAINT BMTB_NOTE_FK1 FOREIGN KEY(ACCOUNT_NO) REFERENCES AMTB_ACCOUNT(ACCOUNT_NO) ENABLE;
ALTER TABLE BMTB_NOTE ADD CONSTRAINT BMTB_NOTE_FK2 FOREIGN KEY(ISSUED_INVOICE_HEADER_NO) REFERENCES BMTB_INVOICE_HEADER(INVOICE_HEADER_NO) ENABLE;
ALTER TABLE BMTB_NOTE ADD CONSTRAINT BMTB_NOTE_FK3 FOREIGN KEY(ISSUED_INVOICE_TXN_NO) REFERENCES BMTB_INVOICE_TXN(INVOICE_TXN_NO) ENABLE;
ALTER TABLE BMTB_NOTE ADD CONSTRAINT BMTB_NOTE_FK4 FOREIGN KEY(BILLED_INVOICE_TXN_NO) REFERENCES BMTB_INVOICE_TXN(INVOICE_TXN_NO) ENABLE;
ALTER TABLE BMTB_NOTE ADD CONSTRAINT BMTB_NOTE_FK5 FOREIGN KEY(TXN_CODE) REFERENCES FMTB_TRANSACTION_CODE(TRANSACTION_CODE_NO) ENABLE;
ALTER TABLE BMTB_NOTE ADD CONSTRAINT BMTB_NOTE_FK6 FOREIGN KEY ("REASON") REFERENCES "MSTB_MASTER_TABLE" ("MASTER_NO") ENABLE;
ALTER TABLE BMTB_NOTE ADD CONSTRAINT BMTB_NOTE_FK7 FOREIGN KEY ("CANCELLATION_REASON") REFERENCES "MSTB_MASTER_TABLE" ("MASTER_NO") ENABLE;
ALTER TABLE TMTB_ACQUIRE_TXN ADD CONSTRAINT TMTB_ACQUIRE_TXN_FK7 FOREIGN KEY(NOTE_NO) REFERENCES BMTB_NOTE(NOTE_NO) ENABLE;
/***************************************************************/

CREATE TABLE BMTB_LAST_INVOICE_LOG
(
  ACCOUNT_NO NUMBER(8) NOT NULL,
  INVOICE_HEADER_NO NUMBER(18) NOT NULL,
  BILL_GEN_DATE DATE NOT NULL
)
;

ALTER TABLE "BMTB_LAST_INVOICE_LOG" ADD CONSTRAINT "BMTB_LAST_INVOICE_LOG_PK" PRIMARY KEY ("ACCOUNT_NO") ENABLE;
ALTER TABLE BMTB_LAST_INVOICE_LOG ADD CONSTRAINT BMTB_LAST_INVOICE_LOG_FK1 FOREIGN KEY(ACCOUNT_NO) REFERENCES AMTB_ACCOUNT(ACCOUNT_NO) ENABLE;
ALTER TABLE BMTB_LAST_INVOICE_LOG ADD CONSTRAINT BMTB_LAST_INVOICE_LOG_FK2 FOREIGN KEY(INVOICE_HEADER_NO) REFERENCES BMTB_INVOICE_HEADER(INVOICE_HEADER_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_INVOICE_DEPOSIT_TXN
(
  INVOICE_DEPOSIT_TXN_NO NUMBER(18) NOT NULL,
  ACCOUNT_NO NUMBER(8) NOT NULL,
  INVOICE_HEADER_NO NUMBER(18),
  NOTE_NO NUMBER(18),
  PAYMENT_RECEIPT_NO NUMBER(18), 
  TXN_TYPE VARCHAR2(1) NOT NULL,
  AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  TXN_DATE DATE NOT NULL,
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP
)
;

ALTER TABLE "BMTB_INVOICE_DEPOSIT_TXN" ADD CONSTRAINT "BMTB_INVOICE_DEPOSIT_TXN_PK" PRIMARY KEY ("INVOICE_DEPOSIT_TXN_NO") ENABLE;
ALTER TABLE BMTB_INVOICE_DEPOSIT_TXN ADD CONSTRAINT BMTB_INVOICE_DEPOSIT_TXN_FK1 FOREIGN KEY(ACCOUNT_NO) REFERENCES AMTB_ACCOUNT(ACCOUNT_NO) ENABLE;
ALTER TABLE BMTB_INVOICE_DEPOSIT_TXN ADD CONSTRAINT BMTB_INVOICE_DEPOSIT_TXN_FK2 FOREIGN KEY(INVOICE_HEADER_NO) REFERENCES BMTB_INVOICE_HEADER(INVOICE_HEADER_NO) ENABLE;
ALTER TABLE BMTB_INVOICE_DEPOSIT_TXN ADD CONSTRAINT BMTB_INVOICE_DEPOSIT_TXN_FK3 FOREIGN KEY(NOTE_NO) REFERENCES BMTB_NOTE(NOTE_NO) ENABLE;
ALTER TABLE BMTB_INVOICE_DEPOSIT_TXN ADD CONSTRAINT BMTB_INVOICE_DEPOSIT_TXN_FK4 FOREIGN KEY(PAYMENT_RECEIPT_NO) REFERENCES BMTB_PAYMENT_RECEIPT(PAYMENT_RECEIPT_NO) ENABLE;
COMMENT ON COLUMN BMTB_INVOICE_DEPOSIT_TXN.TXN_TYPE IS 'R - REQUEST, F = REFUND';

/***************************************************************/

CREATE TABLE BMTB_DRAFT_INV_FILE
(
  FILE_NO NUMBER(18) NOT NULL,
  INVOICE_FILE BLOB,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP,
  VERSION NUMBER(9) DEFAULT 0
)
;

ALTER TABLE BMTB_DRAFT_INV_FILE ADD CONSTRAINT BMTB_DRAFT_INV_FILE_PK PRIMARY KEY (FILE_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_DRAFT_INV_HEADER
(
  INVOICE_HEADER_NO NUMBER(18) NOT NULL,
  REQ_NO NUMBER(18),
  ACCOUNT_NO NUMBER(8) NOT NULL,
  DEBT_TO NUMBER(8) NOT NULL,
  INVOICE_NO NUMBER(18),
  INVOICE_DATE DATE NOT NULL,
  INVOICE_STATUS VARCHAR2(1) NOT NULL,
  INVOICE_FORMAT VARCHAR2(1) NOT NULL,
  DUE_DATE DATE,
  STATEMENT_PERIOD_FROM_DATE DATE,
  STATEMENT_PERIOD_TO_DATE DATE,
  PREV_BALANCE NUMBER(12,2) DEFAULT 0 NOT NULL,
  PREV_PAYMENT NUMBER(12,2) DEFAULT 0 NOT NULL,
  NEW_TXN NUMBER(12,2) DEFAULT 0 NOT NULL,
  NEW_BALANCE NUMBER(12,2) DEFAULT 0 NOT NULL,
  LESS_30_DAYS NUMBER(12,2) DEFAULT 0 NOT NULL,
  LESS_60_DAYS NUMBER(12,2) DEFAULT 0 NOT NULL,
  LESS_90_DAYS NUMBER(12,2) DEFAULT 0 NOT NULL,
  MORE_90_DAYS NUMBER(12,2) DEFAULT 0 NOT NULL,
  PREV_REWARDS_PTS NUMBER(8) DEFAULT 0,
  REDEEMED_REWARDS_PTS NUMBER(8) DEFAULT 0,
  NEW_REWARDS_PTS NUMBER(8) DEFAULT 0,
  TOTAL_REWARDS_PTS NUMBER(8) DEFAULT 0,
  ACCOUNT_DEPOSIT NUMBER(12,2) DEFAULT 0,
  ACCOUNT_EXCESS NUMBER(12,2) DEFAULT 0,
  OVERDUE_INVOICE VARCHAR2(255),
  TXN_CUTOFF_DATE DATE,
  LATE_PAYMENT_INTEREST NUMBER(5,2) DEFAULT 0 NOT NULL,
  LATE_PAYMENT_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  LAST_LATE_PAYMENT_CHARGED_DATE DATE,
  LATE_PAYMENT_FLAG VARCHAR2(1) DEFAULT 'N' NOT NULL,
  EARLY_PAYMENT_FLAG VARCHAR2(1) DEFAULT 'N' NOT NULL,
  OUTSTANDING_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  TOTAL_FARE_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  TOTAL_NO_OF_TRIP NUMBER(8,0) DEFAULT 0 NOT NULL,
  REMARKS VARCHAR2(500),
  BILLED_FLAG VARCHAR2(1),
  FILE_NO NUMBER(18),
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP,
  VERSION NUMBER(9) DEFAULT 0
)
;

COMMENT ON COLUMN BMTB_DRAFT_INV_HEADER.TOTAL_FARE_AMOUNT IS 'FOR CALCULATION OF VOLUME DISCOUNT';
COMMENT ON COLUMN BMTB_DRAFT_INV_HEADER.TOTAL_NO_OF_TRIP IS 'FOR CALCULATION OF VOLUME DISCOUNT';
COMMENT ON COLUMN BMTB_DRAFT_INV_HEADER.LATE_PAYMENT_FLAG IS 'N = NO, Y = YES';
COMMENT ON COLUMN BMTB_DRAFT_INV_HEADER.INVOICE_STATUS IS 'O = OUTSTANDING, C = CLOSED';
COMMENT ON COLUMN BMTB_DRAFT_INV_HEADER.INVOICE_FORMAT IS 'A = ACCOUNT FORMAT, S = SUBACCOUNT, P = PERSONAL, M = MISC, D = DEPOSIT';
ALTER TABLE BMTB_DRAFT_INV_HEADER ADD CONSTRAINT BMTB_DRAFT_INV_HEADER_PK PRIMARY KEY ("INVOICE_HEADER_NO") ENABLE;
ALTER TABLE BMTB_DRAFT_INV_HEADER ADD CONSTRAINT BMTB_DRAFT_INV_HEADER_FK1 FOREIGN KEY(ACCOUNT_NO) REFERENCES AMTB_ACCOUNT(ACCOUNT_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_HEADER ADD CONSTRAINT BMTB_DRAFT_INV_HEADER_FK2 FOREIGN KEY(DEBT_TO) REFERENCES AMTB_ACCOUNT(ACCOUNT_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_HEADER ADD CONSTRAINT BMTB_DRAFT_INV_HEADER_FK3 FOREIGN KEY(REQ_NO) REFERENCES BMTB_BILL_GEN_REQ(REQ_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_HEADER ADD CONSTRAINT BMTB_DRAFT_INV_HEADER_FK4 FOREIGN KEY(FILE_NO) REFERENCES BMTB_DRAFT_INV_FILE(FILE_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_DRAFT_INV_SUMMARY
(
  INVOICE_SUMMARY_NO NUMBER(18) NOT NULL,
  INVOICE_HEADER_NO NUMBER(18) NOT NULL,
  ACCOUNT_NO NUMBER(8) ,
  PRODUCT_TYPE_ID VARCHAR2(2) ,
  SUMMARY_TYPE VARCHAR2(2) ,
  SUMMARY_NAME VARCHAR2(80) NOT NULL,
  DISPLAY_PRIORITY_1 NUMBER(1) NOT NULL,
  DISPLAY_PRIORITY_2 NUMBER(1) NOT NULL,
  PREV_BALANCE NUMBER(12,2) DEFAULT 0 NOT NULL,
  PREV_PAYMENT NUMBER(12,2) DEFAULT 0 NOT NULL,
  NEW_TXN NUMBER(12,2) DEFAULT 0 NOT NULL,
  ADMIN_FEE NUMBER(12,2) DEFAULT 0 NOT NULL,
  GST NUMBER(12,2) DEFAULT 0 NOT NULL,
  TOTAL_NEW NUMBER(12,2) DEFAULT 0 NOT NULL,
  BALANCE NUMBER(12,2) DEFAULT 0 NOT NULL,
  UNIT_PRICE NUMBER(12,2) DEFAULT 0,
  QUANTITY NUMBER(18) DEFAULT 0,
  DISCOUNT NUMBER(12,2) DEFAULT 0
)
;

COMMENT ON COLUMN BMTB_DRAFT_INV_SUMMARY.UNIT_PRICE IS 'APPLICABLE FOR MISC INVOICE ONLY';
COMMENT ON COLUMN BMTB_DRAFT_INV_SUMMARY.QUANTITY IS 'APPLICABLE FOR MISC INVOICE ONLY';
COMMENT ON COLUMN BMTB_DRAFT_INV_SUMMARY.DISCOUNT IS 'APPLICABLE FOR MISC INVOICE ONLY';
COMMENT ON COLUMN BMTB_DRAFT_INV_SUMMARY.SUMMARY_TYPE IS 'TRANSACTION SUMMARY SECTION GROUPING NAME (ACCOUNT NAME + ACCOUNT CODE)';
COMMENT ON COLUMN BMTB_DRAFT_INV_SUMMARY.SUMMARY_NAME IS 'INDIVIDUAL PRODUCT TYPE NAME IN THE TRANSACTION SUMMARY SECTION';
ALTER TABLE BMTB_DRAFT_INV_SUMMARY ADD CONSTRAINT BMTB_DRAFT_INV_SUMMARY_PK PRIMARY KEY (INVOICE_SUMMARY_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_SUMMARY ADD CONSTRAINT BMTB_DRAFT_INV_SUMMARY_FK1 FOREIGN KEY(INVOICE_HEADER_NO) REFERENCES BMTB_DRAFT_INV_HEADER(INVOICE_HEADER_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_SUMMARY ADD CONSTRAINT BMTB_DRAFT_INV_SUMMARY_FK2 FOREIGN KEY(PRODUCT_TYPE_ID) REFERENCES PMTB_PRODUCT_TYPE(PRODUCT_TYPE_ID) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_SUMMARY ADD CONSTRAINT BMTB_DRAFT_INV_SUMMARY_FK3 FOREIGN KEY(ACCOUNT_NO) REFERENCES AMTB_ACCOUNT(ACCOUNT_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_DRAFT_INV_DETAIL
(
  INVOICE_DETAIL_NO NUMBER(18) NOT NULL,
  INVOICE_SUMMARY_NO NUMBER(18) NOT NULL,
  PRODUCT_NO NUMBER(19) ,
  PRODUCT_TYPE_ID VARCHAR2(2),
  ACCOUNT_NO NUMBER(8) NOT NULL,
  INVOICE_DETAIL_NAME VARCHAR2(80),
  INVOICE_DETAIL_TYPE VARCHAR2(2) NOT NULL,
  NEW_TXN NUMBER(12,2) DEFAULT 0 NOT NULL,
  ADMIN_FEE NUMBER(12,2) DEFAULT 0 NOT NULL,
  GST NUMBER(12,2) DEFAULT 0 NOT NULL,
  TOTAL_NEW NUMBER(12,2) DEFAULT 0 NOT NULL,
  CARD_NAME VARCHAR2(80),
  CARD_NO VARCHAR2(19),
  CARD_CREDIT_LIMIT NUMBER(12,2),
  CARD_REPLACEMENT NUMBER(12,2),
  CARD_REPLACEMENT_GST NUMBER(12,2),
  CARD_REPLACEMENT_GST_PERCENT NUMBER(5,2),
  SUBSCRIPTION_FEE NUMBER(12,2),
  SUBSCRIPTION_FEE_GST NUMBER(12,2),
  SUBSCRIPTION_FEE_GST_PERCENT NUMBER(5,2),
  ORI_ADMIN_FEE NUMBER(12,2) DEFAULT 0 NOT NULL,
  PROD_DIS NUMBER(12,2) DEFAULT 0 NOT NULL,
  PROMO_DIS NUMBER(12,2) DEFAULT 0 NOT NULL,
  TXN_CODE NUMBER(8),
  OUTSTANDING_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP,
  VERSION NUMBER(9) DEFAULT 0
)
;

COMMENT ON COLUMN BMTB_DRAFT_INV_DETAIL.CARD_REPLACEMENT IS 'A SNAPSHOT OF THE REPLACEMENT FEE AMOUNT BUT NOT ACCUMULATED INTO DETAIL OUTSTANDING AMOUNT';
COMMENT ON COLUMN BMTB_DRAFT_INV_DETAIL.INVOICE_DETAIL_NAME IS 'NAME TO BE DISPLAYED AS THE DETAIL HEADER, NOT APPLICABLE TO PERSONAL FORMAT';
COMMENT ON COLUMN BMTB_DRAFT_INV_DETAIL.INVOICE_DETAIL_TYPE IS 'TO INDICATE WHETHER IT IS A NORMAL OR CREDIT/DEBIT DETAIL: N = NORMAL, C = CREDIT/DEBIT';
ALTER TABLE BMTB_DRAFT_INV_DETAIL ADD CONSTRAINT BMTB_DRAFT_INV_DETAIL_PK PRIMARY KEY (INVOICE_DETAIL_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_DETAIL ADD CONSTRAINT BMTB_DRAFT_INV_DETAIL_FK1 FOREIGN KEY(INVOICE_SUMMARY_NO) REFERENCES BMTB_DRAFT_INV_SUMMARY(INVOICE_SUMMARY_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_DETAIL ADD CONSTRAINT BMTB_DRAFT_INV_DETAIL_FK2 FOREIGN KEY(PRODUCT_NO) REFERENCES PMTB_PRODUCT(PRODUCT_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_DETAIL ADD CONSTRAINT BMTB_DRAFT_INV_DETAIL_FK3 FOREIGN KEY(ACCOUNT_NO) REFERENCES AMTB_ACCOUNT(ACCOUNT_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_DETAIL ADD CONSTRAINT BMTB_DRAFT_INV_DETAIL_FK4 FOREIGN KEY(PRODUCT_TYPE_ID) REFERENCES PMTB_PRODUCT_TYPE(PRODUCT_TYPE_ID) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_DETAIL ADD CONSTRAINT BMTB_DRAFT_INV_DETAIL_FK5 FOREIGN KEY(TXN_CODE) REFERENCES FMTB_TRANSACTION_CODE(TRANSACTION_CODE_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_DRAFT_INV_TXN
(
  INVOICE_TXN_NO NUMBER(18) NOT NULL,
  INVOICE_DETAIL_NO NUMBER(18) NOT NULL,
  CARD_NO VARCHAR2(19),
  JOB_TYPE VARCHAR2(80),
  JOB_REF_NO VARCHAR2(10),
  FLIGHT_INFO VARCHAR2(40),
  BOOKING_REF VARCHAR2(40),
  BOOKED_BY VARCHAR2(80),
  TAXI_NO VARCHAR2(10),
  VEHICLE_TYPE VARCHAR2(500),
  PICKUP VARCHAR2(255),
  DESTINATION VARCHAR2(255),
  TXN_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  ADMIN_FEE NUMBER(12,2) DEFAULT 0 NOT NULL,
  ADMIN_FEE_PERCENT NUMBER(5,2) DEFAULT 0 NOT NULL,
  GST NUMBER(12,2) DEFAULT 0 NOT NULL,
  GST_PERCENT NUMBER(5,2) DEFAULT 0 NOT NULL,
  "ORI_ADMIN_FEE" NUMBER(12,2) DEFAULT 0 NOT NULL,
  "PROD_DIS_PERCENT" NUMBER(5,2) DEFAULT 0 NOT NULL, 
  "PROD_DIS_VALUE" NUMBER(12,2) DEFAULT 0 NOT NULL, 
  "PROMO_DIS_PERCENT" NUMBER(5,2) DEFAULT 0 NOT NULL, 
  "PROMO_DIS_VALUE" NUMBER(12,2) DEFAULT 0 NOT NULL,
  TOTAL NUMBER(12,2) DEFAULT 0,
  PASSENGER_NAME VARCHAR2(80),
  SURCHARGE VARCHAR2(255),
  TRIP_START_DT TIMESTAMP,
  TRIP_END_DT TIMESTAMP,
  PROJECT_CODE VARCHAR2(80),
  ISSUED_INVOICE_NO NUMBER(18),
  ISSUED_INVOICE_DATE DATE, 
  NOTE VARCHAR2(20),
  DESCRIPTION VARCHAR2(255),
  HOTEL_INFO VARCHAR2(255)
)
;

COMMENT ON COLUMN BMTB_DRAFT_INV_TXN.DESCRIPTION IS 'USED FOR TRANSACTION DETAILS LIKE CREDIT/DEBIT NOTE DESCRIPTION: WAIVE LATE PAYMENT';
ALTER TABLE BMTB_DRAFT_INV_TXN ADD CONSTRAINT BMTB_DRAFT_INV_TXN_PK PRIMARY KEY (INVOICE_TXN_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_TXN ADD CONSTRAINT BMTB_DRAFT_INV_TXN_FK1 FOREIGN KEY(INVOICE_DETAIL_NO) REFERENCES BMTB_DRAFT_INV_DETAIL(INVOICE_DETAIL_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_DRAFT_INV_PAYMENT_HEADER
(
  INVOICE_PAYMENT_NO NUMBER(18) NOT NULL,
  INVOICE_HEADER_NO NUMBER(18) NOT NULL,
  HEADER_TYPE VARCHAR2(1) NOT NULL,
  PAYMENT_TYPE VARCHAR2(50) NOT NULL,
  PAYMENT_REF_NO VARCHAR2(30),
  PAYMENT_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL
)
;

COMMENT ON COLUMN BMTB_DRAFT_INV_PAYMENT_HEADER.HEADER_TYPE IS 'R = PAYMENT RECEIVED, C = PAYMENT CANCELED, A = PAYMENT APPLIED';
COMMENT ON COLUMN BMTB_DRAFT_INV_PAYMENT_HEADER.PAYMENT_TYPE IS 'EXAMPLE CONTRA OR CREDIT CARD';
ALTER TABLE BMTB_DRAFT_INV_PAYMENT_HEADER ADD CONSTRAINT BMTB_DRAFT_INV_PYMT_HEADER_PK PRIMARY KEY (INVOICE_PAYMENT_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_PAYMENT_HEADER ADD CONSTRAINT BMTB_DRAFT_INV_PYMT_HEADER_FK1 FOREIGN KEY(INVOICE_HEADER_NO) REFERENCES BMTB_DRAFT_INV_HEADER(INVOICE_HEADER_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_DRAFT_INV_PAYMENT_DETAIL
(
  INVOICE_PAYMENT_DETAIL_NO NUMBER(18) NOT NULL,
  INVOICE_PAYMENT_NO NUMBER(18) NOT NULL,
  INVOICE_NO NUMBER(18) NOT NULL,
  ACCOUNT_NAME VARCHAR2(80) NOT NULL,
  PAYMENT_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL
)
;

ALTER TABLE BMTB_DRAFT_INV_PAYMENT_DETAIL ADD CONSTRAINT BMTB_DRAFT_INV_PYMT_DETAIL_PK PRIMARY KEY (INVOICE_PAYMENT_DETAIL_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_PAYMENT_DETAIL ADD CONSTRAINT BMTB_DRAFT_INV_PYMT_DETAIL_FK1 FOREIGN KEY(INVOICE_PAYMENT_NO) REFERENCES BMTB_DRAFT_INV_PAYMENT_HEADER(INVOICE_PAYMENT_NO) ENABLE;

/***************************************************************/

create table BMTB_INVOICE_PRINT_REQ
(
	REQ_ID NUMBER(18) primary key not null,
	BILL_GEN_REQ_NO NUMBER(9),
	CUST_NO_FROM NUMBER(6),
	CUST_NO_TO NUMBER(6),
	INVOICE_NO_FROM NUMBER(18),
	INVOICE_NO_TO NUMBER(18),
	CREATED_BY varchar2(80),
	CREATED_DT timestamp
)
;

/***************************************************************/

create table ITTB_CP_LOGIN
(
	login_id varchar2(80) not null,
	login_type varchar2(3) not null,
	login_method varchar2(1) not null,
	product_no decimal(19),
	contact_person_no decimal(8),
	status varchar2(1) not null,
	CREATED_DT timestamp,
    UPDATED_DT timestamp,
    UPDATED_BY varchar2(80),
    CREATED_BY varchar2(80),
    VERSION decimal(9) DEFAULT 0,
    primary key(login_id, login_type)
);

CREATE INDEX ITTB_CP_LOGIN_N1 ON ITTB_CP_LOGIN(product_no);
CREATE INDEX ITTB_CP_LOGIN_N2 ON ITTB_CP_LOGIN(contact_person_no);
COMMENT ON COLUMN ITTB_CP_LOGIN.login_type IS 'HS - Hotel System CP – Customer Portal HCP – Hotel Customer Portal';
COMMENT ON COLUMN ITTB_CP_LOGIN.login_method IS 'P – Product No Login C – Contact Person Login ';
COMMENT ON COLUMN ITTB_CP_LOGIN.product_no IS 'In the event of card replacement or recycle, this will be updated.';
COMMENT ON COLUMN ITTB_CP_LOGIN.contact_person_no IS 'New main contact for an account, this will be updated.';
COMMENT ON COLUMN ITTB_CP_LOGIN.status IS 'A = Active D = Deleted';
ALTER TABLE ITTB_CP_LOGIN ADD CONSTRAINT ITTB_CP_LOGIN_FK1 FOREIGN KEY (product_no) REFERENCES PMTB_PRODUCT (product_no) ENABLE;
ALTER TABLE ITTB_CP_LOGIN ADD CONSTRAINT ITTB_CP_LOGIN_FK2 FOREIGN KEY (contact_person_no) REFERENCES AMTB_CONTACT_PERSON (contact_person_no) ENABLE;

/**********************************************/
/**************** INDEXES **********************/
/**********************************************/

CREATE INDEX BMTB_BILL_GEN_SETUP_N1 ON BMTB_BILL_GEN_SETUP(BILL_GEN_TIME);
CREATE INDEX "BMTB_BILL_GEN_REQ_N1" ON BMTB_BILL_GEN_REQ("SETUP_NO");
CREATE INDEX "BMTB_BILL_GEN_REQ_N2" ON BMTB_BILL_GEN_REQ("REGEN_SETUP_NO");
CREATE INDEX BMTB_BILL_GEN_REQ_N3 ON BMTB_BILL_GEN_REQ(SETUP_NO, REQUEST_DATE, STATUS);
CREATE INDEX "BMTB_BILL_GEN_ERROR_N1" ON BMTB_BILL_GEN_ERROR("REQ_NO");
CREATE INDEX "BMTB_BILL_GEN_ERROR_N2" ON BMTB_BILL_GEN_ERROR("TOP_LEVEL_ACCOUNT_NO");
CREATE INDEX "BMTB_BILL_GEN_ERROR_N3" ON BMTB_BILL_GEN_ERROR("BILLABLE_ACCOUNT_NO");
CREATE INDEX BMTB_BILL_GEN_ERROR_N4 ON BMTB_BILL_GEN_ERROR(TOP_LEVEL_ACCOUNT_NO, ERROR_DT);
CREATE INDEX "BMTB_BILL_GEN_REQ_DET_N1" ON BMTB_BILL_GEN_REQ_DETAIL(ACCOUNT_NO);
CREATE INDEX "BMTB_BILL_GEN_REQ_DET_N2" ON BMTB_BILL_GEN_REQ_DETAIL(REQ_NO);
CREATE INDEX "BMTB_INVOICE_HEADER_N1" ON BMTB_INVOICE_HEADER(ACCOUNT_NO);
CREATE INDEX "BMTB_INVOICE_HEADER_N2" ON BMTB_INVOICE_HEADER(DEBT_TO);
CREATE INDEX "BMTB_INVOICE_HEADER_N3" ON BMTB_INVOICE_HEADER(REQ_NO);
CREATE INDEX "BMTB_INVOICE_HEADER_N4" ON BMTB_INVOICE_HEADER(FILE_NO);
CREATE INDEX BMTB_INVOICE_HEADER_N5 ON BMTB_INVOICE_HEADER(DEBT_TO, DUE_DATE);
CREATE INDEX BMTB_INVOICE_HEADER_N6 ON BMTB_INVOICE_HEADER(DEBT_TO, INVOICE_FORMAT, BILLED_FLAG, INVOICE_DATE);
CREATE INDEX BMTB_INVOICE_HEADER_N7 ON BMTB_INVOICE_HEADER(DEBT_TO, INVOICE_STATUS, DUE_DATE, INVOICE_NO, OUTSTANDING_AMOUNT);
CREATE INDEX BMTB_INVOICE_HEADER_N8 ON BMTB_INVOICE_HEADER(INVOICE_NO, REQ_NO);
CREATE INDEX "BMTB_INVOICE_SUMMARY_N1" ON BMTB_INVOICE_SUMMARY(INVOICE_HEADER_NO);
CREATE INDEX "BMTB_INVOICE_SUMMARY_N2" ON BMTB_INVOICE_SUMMARY(PRODUCT_TYPE_ID);
CREATE INDEX "BMTB_INVOICE_SUMMARY_N3" ON BMTB_INVOICE_SUMMARY(ACCOUNT_NO);
CREATE INDEX BMTB_INVOICE_SUMMARY_N4 ON BMTB_INVOICE_SUMMARY(INVOICE_HEADER_NO, SUMMARY_TYPE);
CREATE INDEX BMTB_INVOICE_SUMMARY_N5 ON BMTB_INVOICE_SUMMARY(SUMMARY_TYPE);
CREATE INDEX BMTB_INVOICE_SUMMARY_N6 ON BMTB_INVOICE_SUMMARY(NEW_TXN, ADMIN_FEE, GST, TOTAL_NEW);
CREATE INDEX BMTB_INVOICE_SUMMARY_N7 ON BMTB_INVOICE_SUMMARY(PREV_BALANCE, PREV_PAYMENT, NEW_TXN, ADMIN_FEE, GST, TOTAL_NEW, BALANCE);
CREATE INDEX "BMTB_INVOICE_DETAIL_N1" ON BMTB_INVOICE_DETAIL(INVOICE_SUMMARY_NO);
CREATE INDEX "BMTB_INVOICE_DETAIL_N2" ON BMTB_INVOICE_DETAIL(PRODUCT_NO);
CREATE INDEX "BMTB_INVOICE_DETAIL_N3" ON BMTB_INVOICE_DETAIL(ACCOUNT_NO);
CREATE INDEX "BMTB_INVOICE_DETAIL_N4" ON BMTB_INVOICE_DETAIL(PRODUCT_TYPE_ID);
CREATE INDEX "BMTB_INVOICE_DETAIL_N5" ON BMTB_INVOICE_DETAIL(TXN_CODE);
CREATE INDEX BMTB_INVOICE_DETAIL_N6 ON BMTB_INVOICE_DETAIL(subscription_fee, card_replacement);
CREATE INDEX BMTB_INVOICE_DETAIL_N7 ON BMTB_INVOICE_DETAIL(invoice_detail_type);
CREATE INDEX "BMTB_INVOICE_TXN_N1" ON BMTB_INVOICE_TXN(INVOICE_DETAIL_NO);
CREATE INDEX "BMTB_INVOICE_TXN_N2" ON BMTB_INVOICE_TXN(ISSUED_INVOICE_HEADER_NO);
CREATE INDEX "BMTB_INVOICE_TXN_N3" ON BMTB_INVOICE_TXN (ACQUIRE_TXN_NO);
CREATE INDEX "BMTB_INVOICE_PAYMENT_HEADER_N1" ON BMTB_INVOICE_PAYMENT_HEADER(INVOICE_HEADER_NO);
CREATE INDEX "BMTB_INVOICE_PAYMENT_DETAIL_N1" ON BMTB_INVOICE_PAYMENT_DETAIL(INVOICE_PAYMENT_NO);
CREATE INDEX "BMTB_PAYMENT_RECEIPT_N1" ON BMTB_PAYMENT_RECEIPT(ACCOUNT_NO);
CREATE INDEX "BMTB_PAYMENT_RECEIPT_N2" ON BMTB_PAYMENT_RECEIPT(PAYMENT_MODE);
CREATE INDEX "BMTB_PAYMENT_RECEIPT_N3" ON BMTB_PAYMENT_RECEIPT(BANK);
CREATE INDEX "BMTB_PAYMENT_RECEIPT_N4" ON BMTB_PAYMENT_RECEIPT(BRANCH);
CREATE INDEX "BMTB_PAYMENT_RECEIPT_N5" ON BMTB_PAYMENT_RECEIPT(BANK_IN);
CREATE INDEX BMTB_PAYMENT_RECEIPT_N6 ON BMTB_PAYMENT_RECEIPT(ACCOUNT_NO, BILLED_FLAG, CANCEL_DT);
CREATE INDEX BMTB_PAYMENT_RECEIPT_N7 ON BMTB_PAYMENT_RECEIPT(ACCOUNT_NO, CANCEL_DT, EXCESS_AMOUNT);
CREATE INDEX "BMTB_PAYMENT_RECEIPT_DETAIL_N1" ON BMTB_PAYMENT_RECEIPT_DETAIL(PAYMENT_RECEIPT_NO);
CREATE INDEX "BMTB_PAYMENT_RECEIPT_DETAIL_N2" ON BMTB_PAYMENT_RECEIPT_DETAIL(INVOICE_HEADER_NO);
CREATE INDEX "BMTB_PAYMENT_RECEIPT_DETAIL_N3" ON BMTB_PAYMENT_RECEIPT_DETAIL(INVOICE_DETAIL_NO);
CREATE INDEX BMTB_PAYMENT_RECEIPT_DETAIL_N4 ON BMTB_PAYMENT_RECEIPT_DETAIL(CREATED_DT);
CREATE INDEX "BMTB_NOTE_N1" ON BMTB_NOTE(ACCOUNT_NO);
CREATE INDEX "BMTB_NOTE_N2" ON BMTB_NOTE(ISSUED_INVOICE_HEADER_NO);
CREATE INDEX "BMTB_NOTE_N3" ON BMTB_NOTE(ISSUED_INVOICE_TXN_NO);
CREATE INDEX "BMTB_NOTE_N4" ON BMTB_NOTE(BILLED_INVOICE_TXN_NO);
CREATE INDEX "BMTB_NOTE_N5" ON BMTB_NOTE(TXN_CODE);
CREATE INDEX BMTB_NOTE_N6 ON BMTB_NOTE(ACCOUNT_NO, CREATED_DT, STATUS);
CREATE INDEX "BMTB_LAST_INVOICE_LOG_N1" ON BMTB_LAST_INVOICE_LOG(INVOICE_HEADER_NO);
CREATE INDEX "BMTB_INVOICE_DEPOSIT_TXN_N1" ON BMTB_INVOICE_DEPOSIT_TXN(ACCOUNT_NO);
CREATE INDEX "BMTB_INVOICE_DEPOSIT_TXN_N2" ON BMTB_INVOICE_DEPOSIT_TXN(INVOICE_HEADER_NO);
CREATE INDEX "BMTB_INVOICE_DEPOSIT_TXN_N3" ON BMTB_INVOICE_DEPOSIT_TXN(NOTE_NO);
CREATE INDEX "BMTB_INVOICE_DEPOSIT_TXN_N4" ON BMTB_INVOICE_DEPOSIT_TXN(PAYMENT_RECEIPT_NO);
CREATE INDEX BMTB_INVOICE_DEPOSIT_TXN_N5 ON BMTB_INVOICE_DEPOSIT_TXN(ACCOUNT_NO, TXN_TYPE);
CREATE INDEX "BMTB_DRAFT_INV_HEADER_N1" ON BMTB_DRAFT_INV_HEADER(ACCOUNT_NO);
CREATE INDEX "BMTB_DRAFT_INV_HEADER_N2" ON BMTB_DRAFT_INV_HEADER(DEBT_TO);
CREATE INDEX "BMTB_DRAFT_INV_HEADER_N3" ON BMTB_DRAFT_INV_HEADER(REQ_NO);
CREATE INDEX "BMTB_DRAFT_INV_HEADER_N4" ON BMTB_DRAFT_INV_HEADER(FILE_NO);
CREATE INDEX BMTB_DRAFT_INV_HEADER_N5 ON BMTB_DRAFT_INV_HEADER(DEBT_TO, DUE_DATE);
CREATE INDEX BMTB_DRAFT_INV_HEADER_N6 ON BMTB_DRAFT_INV_HEADER(DEBT_TO, INVOICE_FORMAT, BILLED_FLAG, INVOICE_DATE);
CREATE INDEX BMTB_DRAFT_INV_HEADER_N7 ON BMTB_DRAFT_INV_HEADER(DEBT_TO, INVOICE_STATUS, DUE_DATE, INVOICE_NO, OUTSTANDING_AMOUNT);
CREATE INDEX BMTB_DRAFT_INV_HEADER_N8 ON BMTB_DRAFT_INV_HEADER(INVOICE_NO, REQ_NO);
CREATE INDEX "BMTB_DRAFT_INV_SUMMARY_N1" ON BMTB_DRAFT_INV_SUMMARY(INVOICE_HEADER_NO);
CREATE INDEX "BMTB_DRAFT_INV_SUMMARY_N2" ON BMTB_DRAFT_INV_SUMMARY(PRODUCT_TYPE_ID);
CREATE INDEX "BMTB_DRAFT_INV_SUMMARY_N3" ON BMTB_DRAFT_INV_SUMMARY(ACCOUNT_NO);
CREATE INDEX BMTB_DRAFT_INV_SUMMARY_N4 ON BMTB_DRAFT_INV_SUMMARY(INVOICE_HEADER_NO, SUMMARY_TYPE);
CREATE INDEX BMTB_DRAFT_INV_SUMMARY_N5 ON BMTB_DRAFT_INV_SUMMARY(SUMMARY_TYPE);
CREATE INDEX BMTB_DRAFT_INV_SUMMARY_N6 ON BMTB_DRAFT_INV_SUMMARY(NEW_TXN, ADMIN_FEE, GST, TOTAL_NEW);
CREATE INDEX BMTB_DRAFT_INV_SUMMARY_N7 ON BMTB_DRAFT_INV_SUMMARY(PREV_BALANCE, PREV_PAYMENT, NEW_TXN, ADMIN_FEE, GST, TOTAL_NEW, BALANCE);
CREATE INDEX "BMTB_DRAFT_INV_DETAIL_N1" ON BMTB_DRAFT_INV_DETAIL(INVOICE_SUMMARY_NO);
CREATE INDEX "BMTB_DRAFT_INV_DETAIL_N2" ON BMTB_DRAFT_INV_DETAIL(PRODUCT_NO);
CREATE INDEX "BMTB_DRAFT_INV_DETAIL_N3" ON BMTB_DRAFT_INV_DETAIL(ACCOUNT_NO);
CREATE INDEX "BMTB_DRAFT_INV_DETAIL_N4" ON BMTB_DRAFT_INV_DETAIL(PRODUCT_TYPE_ID);
CREATE INDEX "BMTB_DRAFT_INV_DETAIL_N5" ON BMTB_DRAFT_INV_DETAIL(TXN_CODE);
CREATE INDEX BMTB_DRAFT_INV_DETAIL_N6 ON BMTB_DRAFT_INV_DETAIL(subscription_fee, card_replacement);
CREATE INDEX "BMTB_DRAFT_INV_TXN_N1" ON BMTB_DRAFT_INV_TXN(INVOICE_DETAIL_NO);
CREATE INDEX "BMTB_DRAFT_INV_PYMT_HEADER_N1" ON BMTB_DRAFT_INV_PAYMENT_HEADER(INVOICE_HEADER_NO);
CREATE INDEX "BMTB_DRAFT_INV_PYMT_DETAIL_N1" ON BMTB_DRAFT_INV_PAYMENT_DETAIL(INVOICE_PAYMENT_NO);
/**********************************************/
/**************** SAMPLE DATA *****************/
/**********************************************/

--REM INSERTING into BILL_GEN_SETUP
Insert into BMTB_BILL_GEN_SETUP (SETUP_NO,NAME,CUT_OFF_DAY,BILL_GEN_DAY,BILL_GEN_TIME,INVOICE_DAY,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (1,'BI-WEEKLY 1',15,19,'00:00',15,'SYSTEM',to_timestamp('11-MAR-09 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,null,0);
Insert into BMTB_BILL_GEN_SETUP (SETUP_NO,NAME,CUT_OFF_DAY,BILL_GEN_DAY,BILL_GEN_TIME,INVOICE_DAY,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (2,'BI-WEEKLY 2',26,30,'00:00',30,'SYSTEM',to_timestamp('11-MAR-09 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,null,0);
Insert into BMTB_BILL_GEN_SETUP (SETUP_NO,NAME,CUT_OFF_DAY,BILL_GEN_DAY,BILL_GEN_TIME,INVOICE_DAY,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (3,'MONTHLY',26,30,'00:00',30,'SYSTEM',to_timestamp('11-MAR-09 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,null,0);
Insert into BMTB_BILL_GEN_SETUP (SETUP_NO,NAME,CUT_OFF_DAY,BILL_GEN_DAY,BILL_GEN_TIME,INVOICE_DAY,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (4,'AD HOC',null,null,null,null,'SYSTEM',to_timestamp('11-MAR-09 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,null,0);
Insert into BMTB_BILL_GEN_SETUP (SETUP_NO,NAME,CUT_OFF_DAY,BILL_GEN_DAY,BILL_GEN_TIME,INVOICE_DAY,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (5,'DRAFT',null,null,null,null,'SYSTEM',to_timestamp('11-MAR-09 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,null,0);

--REM INSERTING into BMTB_BILL_GEN_REQ
--Insert into BMTB_BILL_GEN_REQ (REQ_NO,STATUS,SETUP_NO,FOR_ACCOUNT,BILL_GEN_MONTH,REQUEST_DATE,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (6,'P',1,null,2,to_timestamp('19-FEB-09','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,null,11);
--Insert into BMTB_BILL_GEN_REQ (REQ_NO,STATUS,SETUP_NO,FOR_ACCOUNT,BILL_GEN_MONTH,REQUEST_DATE,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (7,'P',1,null,3,to_timestamp('19-MAR-09','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,null,8);
--Insert into BMTB_BILL_GEN_REQ (REQ_NO,STATUS,SETUP_NO,FOR_ACCOUNT,BILL_GEN_MONTH,REQUEST_DATE,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (8,'P',1,null,4,to_timestamp('19-APR-09','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,null,1);
--Insert into BMTB_BILL_GEN_REQ (REQ_NO,STATUS,SETUP_NO,FOR_ACCOUNT,BILL_GEN_MONTH,REQUEST_DATE,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (9,'P',1,null,5,to_timestamp('19-MAY-09','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,null,0);
--Insert into BMTB_BILL_GEN_REQ (REQ_NO,STATUS,SETUP_NO,FOR_ACCOUNT,BILL_GEN_MONTH,REQUEST_DATE,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (10,'P',1,null,6,to_timestamp('19-JUN-09','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,null,0);
--Insert into BMTB_BILL_GEN_REQ (REQ_NO,STATUS,SETUP_NO,FOR_ACCOUNT,BILL_GEN_MONTH,REQUEST_DATE,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (11,'P',2,null,2,to_timestamp('27-FEB-09','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,null,11);
--Insert into BMTB_BILL_GEN_REQ (REQ_NO,STATUS,SETUP_NO,FOR_ACCOUNT,BILL_GEN_MONTH,REQUEST_DATE,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (12,'P',2,null,3,to_timestamp('27-MAR-09','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,null,8);
--Insert into BMTB_BILL_GEN_REQ (REQ_NO,STATUS,SETUP_NO,FOR_ACCOUNT,BILL_GEN_MONTH,REQUEST_DATE,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (13,'P',2,null,4,to_timestamp('27-APR-09','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,null,1);
--Insert into BMTB_BILL_GEN_REQ (REQ_NO,STATUS,SETUP_NO,FOR_ACCOUNT,BILL_GEN_MONTH,REQUEST_DATE,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (14,'P',2,null,5,to_timestamp('27-MAY-09','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,null,0);
--Insert into BMTB_BILL_GEN_REQ (REQ_NO,STATUS,SETUP_NO,FOR_ACCOUNT,BILL_GEN_MONTH,REQUEST_DATE,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (15,'P',2,null,6,to_timestamp('27-JUN-09','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,null,0);
--Insert into BMTB_BILL_GEN_REQ (REQ_NO,STATUS,SETUP_NO,FOR_ACCOUNT,BILL_GEN_MONTH,REQUEST_DATE,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (1,'P',3,null,2,to_timestamp('27-FEB-09','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,null,11);
--Insert into BMTB_BILL_GEN_REQ (REQ_NO,STATUS,SETUP_NO,FOR_ACCOUNT,BILL_GEN_MONTH,REQUEST_DATE,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (2,'P',3,null,3,to_timestamp('27-MAR-09','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,null,8);
--Insert into BMTB_BILL_GEN_REQ (REQ_NO,STATUS,SETUP_NO,FOR_ACCOUNT,BILL_GEN_MONTH,REQUEST_DATE,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (3,'P',3,null,4,to_timestamp('27-APR-09','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,null,1);
--Insert into BMTB_BILL_GEN_REQ (REQ_NO,STATUS,SETUP_NO,FOR_ACCOUNT,BILL_GEN_MONTH,REQUEST_DATE,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (4,'P',3,null,5,to_timestamp('27-MAY-09','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,null,0);
--Insert into BMTB_BILL_GEN_REQ (REQ_NO,STATUS,SETUP_NO,FOR_ACCOUNT,BILL_GEN_MONTH,REQUEST_DATE,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (5,'P',3,null,6,to_timestamp('27-JUN-09','DD-MON-RR HH.MI.SS.FF AM'),null,null,null,null,0);
-- creating seq for LOG HEADER --
CREATE SEQUENCE  "FMTB_GL_LOG_HEADER_SQ1"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 3 CACHE 10 NOORDER  NOCYCLE ;
-- LOG HEADER --
CREATE TABLE FMTB_GL_LOG_HEADER (
	GL_LOG_NO NUMBER(8) NOT NULL,
	ENTITY_NO NUMBER(8) NOT NULL,
	GL_DATE DATE,
	CREATED_DATE DATE,
	VERSION NUMBER(9,0) DEFAULT 0,
	CONSTRAINT FMTB_GL_LOG_HEADER_FK1 FOREIGN KEY(ENTITY_NO) REFERENCES FMTB_ENTITY_MASTER(ENTITY_NO),
	CONSTRAINT FMTB_GL_LOG_HEADER_PK PRIMARY KEY(GL_LOG_NO)
);
-- creating indexes --
CREATE INDEX FMTB_GL_LOG_HEADER_N1 ON FMTB_GL_LOG_HEADER (ENTITY_NO);
-- dumping some data into it
-- creating seq for LOG DETAIL --
CREATE SEQUENCE  "FMTB_GL_LOG_DETAIL_SQ1"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 3 CACHE 10 NOORDER  NOCYCLE ;
-- LOG DETAIL --
CREATE TABLE FMTB_GL_LOG_DETAIL (
	GL_LOG_DETAIL_NO NUMBER(8) NOT NULL,
	GL_LOG_NO NUMBER(8) NOT NULL,
	INVOICE_HEADER_NO NUMBER(18),
	PAYMENT_RECEIPT_NO NUMBER(18),
	NOTE_NO NUMBER(18),
	GL_EVENT_TYPE VARCHAR(6) NOT NULL,
	POSTING_DATE DATE NOT NULL,
	DOC_DATE DATE NOT NULL,
	CREATED_DATE TIMESTAMP,
	VERSION NUMBER(9,0) DEFAULT 0,
	CONSTRAINT FMTB_GL_LOG_DETAIL_FK1 FOREIGN KEY(GL_LOG_NO) REFERENCES FMTB_GL_LOG_HEADER(GL_LOG_NO),
	CONSTRAINT FMTB_GL_LOG_DETAIL_FK2 FOREIGN KEY(INVOICE_HEADER_NO) REFERENCES BMTB_INVOICE_HEADER(INVOICE_HEADER_NO),
	CONSTRAINT FMTB_GL_LOG_DETAIL_FK3 FOREIGN KEY(PAYMENT_RECEIPT_NO) REFERENCES BMTB_PAYMENT_RECEIPT(PAYMENT_RECEIPT_NO),
	CONSTRAINT FMTB_GL_LOG_DETAIL_FK4 FOREIGN KEY(NOTE_NO) REFERENCES BMTB_NOTE(NOTE_NO),
	CONSTRAINT FMTB_GL_LOG_DETAIL_PK PRIMARY KEY(GL_LOG_DETAIL_NO)
);
-- creating indexes --
CREATE INDEX FMTB_GL_LOG_DETAIL_N1 ON FMTB_GL_LOG_DETAIL (GL_LOG_NO);
CREATE INDEX FMTB_GL_LOG_DETAIL_N2 ON FMTB_GL_LOG_DETAIL (INVOICE_HEADER_NO);
CREATE INDEX FMTB_GL_LOG_DETAIL_N3 ON FMTB_GL_LOG_DETAIL (PAYMENT_RECEIPT_NO);
CREATE INDEX FMTB_GL_LOG_DETAIL_N4 ON FMTB_GL_LOG_DETAIL (NOTE_NO);
-- dumping some data into it