drop table ITTB_AS_UPD_PROD_REQ;
drop table ITTB_AS_UPD_USAGE_REQ;
drop table ITTB_AS_UPD_PAY_ACCT_REQ;
drop table ITTB_AS_UPD_PAY_PROD_REQ;
drop table ITTB_AS_UPD_BILL_ACCT_REQ;
drop table ITTB_AS_UPD_BILL_PROD_REQ;
drop table ITTB_AS_REV_ACCT_TXN_REQ;
drop table ITTB_AS_REV_PROD_TXN_REQ;
drop table ITTB_AS_ADD_NEG_PROD_REQ;
drop table ITTB_AS_ADD_ACCT_REQ;
drop table ITTB_AS_ADD_PROD_REQ;
drop table ITTB_AS_UPD_ACCT_REQ;
drop table ITTB_AS_MASTER_REQ;
drop sequence ITTB_AS_MASTER_REQ_SQ1;


------------------------------------------ TABLE CREATION

CREATE TABLE ITTB_AS_MASTER_REQ
(
  REQ_ID VARCHAR2(14) NOT NULL,
  REQ_TABLE VARCHAR2(30) NOT NULL,
  REQ_STATUS CHAR(1) NOT NULL,
  REQ_DATE TIMESTAMP(6)
, CONSTRAINT ITTB_AS_MASTER_REQ PRIMARY KEY
  (
    REQ_ID
  )
  ENABLE
)
;

---------------------------------------------------------

CREATE TABLE ITTB_AS_UPD_PROD_REQ
(
  REQ_ID VARCHAR2(14) NOT NULL,
  CARD_NO VARCHAR2(19),
  STATUS CHAR(1),
  NEW_CREDIT_LIMIT VARCHAR2(20),
  EXPIRY_DATE VARCHAR2(4),
  ACCT_ID VARCHAR2(18),
  REASON_CODE CHAR(1),
  UPDATE_BY VARCHAR2(50)
, CONSTRAINT ITTB_AS_UPD_PROD_REQ_PK PRIMARY KEY
  (
    REQ_ID
  )
  ENABLE
)
;

ALTER TABLE ITTB_AS_UPD_PROD_REQ
ADD CONSTRAINT UPDATE_PRODUCT_MASTER_FK1 FOREIGN KEY
(
  REQ_ID
)
REFERENCES ITTB_AS_MASTER_REQ
(
REQ_ID
) ENABLE
;

---------------------------------------------------------

CREATE TABLE ITTB_AS_UPD_ACCT_REQ
(
  REQ_ID VARCHAR2(14) NOT NULL,
  ACCT_ID VARCHAR2(18),
  NEW_CREDIT_LIMIT VARCHAR2(20),
  PARENT_ID VARCHAR2(18),
  UPDATE_BY VARCHAR2(50)
, CONSTRAINT ITTB_AS_UPD_ACCT_REQ_PK PRIMARY KEY
  (
    REQ_ID
  )
  ENABLE
)
;

ALTER TABLE ITTB_AS_UPD_ACCT_REQ
ADD CONSTRAINT UPDATE_ACCOUNT_MASTER_FK1 FOREIGN KEY
(
  REQ_ID
)
REFERENCES ITTB_AS_MASTER_REQ
(
REQ_ID
) ENABLE
;

---------------------------------------------------------

CREATE TABLE ITTB_AS_ADD_PROD_REQ
(
  REQ_ID VARCHAR2(14) NOT NULL,
  CARD_NO VARCHAR2(19),
  ACCT_ID VARCHAR2(18),
  PROD_TYPE_ID VARCHAR2(18),
  FIXED_VALUE VARCHAR2(20),
  CREDIT_LIMIT VARCHAR2(20),
  EXPIRY_DATE VARCHAR2(4),
  STATUS CHAR(1),
  REASON_CODE CHAR(1),
  CREATE_BY VARCHAR2(50)
, CONSTRAINT ITTB_AS_ADD_PROD_REQ_PK PRIMARY KEY
  (
    REQ_ID
  )
  ENABLE
)
;

ALTER TABLE ITTB_AS_ADD_PROD_REQ
ADD CONSTRAINT CREATE_PRODUCT_MASTER_FK1 FOREIGN KEY
(
  REQ_ID
)
REFERENCES ITTB_AS_MASTER_REQ
(
REQ_ID
) ENABLE
;

---------------------------------------------------------

CREATE TABLE ITTB_AS_ADD_ACCT_REQ
(
  REQ_ID VARCHAR2(14) NOT NULL,
  ACCT_ID VARCHAR2(18),
  ACCT_TYPE VARCHAR2(4),
  CREDIT_LIMIT VARCHAR2(20),
  PARENT_ID VARCHAR2(18),
  CREATE_BY VARCHAR2(50)
, CONSTRAINT ITTB_AS_ADD_ACCT_REQ_PK PRIMARY KEY
  (
    REQ_ID
  )
  ENABLE
)
;

ALTER TABLE ITTB_AS_ADD_ACCT_REQ
ADD CONSTRAINT CREATE_ACCOUNT_MASTER_FK1 FOREIGN KEY
(
  REQ_ID
)
REFERENCES ITTB_AS_MASTER_REQ
(
REQ_ID
) ENABLE
;

---------------------------------------------------------

CREATE TABLE ITTB_AS_ADD_NEG_PROD_REQ
(
  REQ_ID VARCHAR2(14) NOT NULL,
  CARD_NO VARCHAR2(19),
  STATUS CHAR(1),
  CREATE_BY VARCHAR2(50)
, CONSTRAINT ITTB_AS_ADD_NEG_PROD_REQ_PK PRIMARY KEY
  (
    REQ_ID
  )
  ENABLE
)
;

ALTER TABLE ITTB_AS_ADD_NEG_PROD_REQ
ADD CONSTRAINT CREATE_NEG_PROD_MASTER_FK1 FOREIGN KEY
(
  REQ_ID
)
REFERENCES ITTB_AS_MASTER_REQ
(
REQ_ID
) ENABLE
;

---------------------------------------------------------

CREATE TABLE ITTB_AS_REV_PROD_TXN_REQ
(
  REQ_ID VARCHAR2(14) NOT NULL,
  CARD_NO VARCHAR2(19),
  TXN_AMT VARCHAR2(20),
  ACCT_ID VARCHAR2(18),
  UPDATE_BY VARCHAR2(50)
, CONSTRAINT ITTB_AS_REV_PROD_TXN_REQ_PK PRIMARY KEY
  (
    REQ_ID
  )
  ENABLE
)
;

ALTER TABLE ITTB_AS_REV_PROD_TXN_REQ
ADD CONSTRAINT REVERSAL_TXN_MASTER_FK1 FOREIGN KEY
(
  REQ_ID
)
REFERENCES ITTB_AS_MASTER_REQ
(
REQ_ID
) ENABLE
;

---------------------------------------------------------

CREATE TABLE ITTB_AS_REV_ACCT_TXN_REQ
(
  REQ_ID VARCHAR2(14) NOT NULL,
  ACCT_ID VARCHAR2(18),
  TXN_AMT VARCHAR2(20),
  PARENT_ID VARCHAR2(18),
  UPDATE_BY VARCHAR2(50)
, CONSTRAINT REVERSAL_TXN_ACCT_REQUEST_PK PRIMARY KEY
  (
    REQ_ID
  )
  ENABLE
)
;

ALTER TABLE ITTB_AS_REV_ACCT_TXN_REQ
ADD CONSTRAINT REVERSAL_TXN_ACCT_MASTER_FK1 FOREIGN KEY
(
  REQ_ID
)
REFERENCES ITTB_AS_MASTER_REQ
(
REQ_ID
) ENABLE
;

---------------------------------------------------------

CREATE TABLE ITTB_AS_UPD_BILL_PROD_REQ
(
  REQ_ID VARCHAR2(14) NOT NULL,
  CARD_NO VARCHAR2(19),
  NEW_CREDIT_LIMIT VARCHAR2(20),
  TOTAL_TXN_AMT_BILLED VARCHAR2(20),
  ACCT_ID VARCHAR2(18),
  UPDATE_BY VARCHAR2(50)
, CONSTRAINT ITTB_AS_UPD_BILL_PROD_REQ_PK PRIMARY KEY
  (
    REQ_ID
  )
  ENABLE
)
;

ALTER TABLE ITTB_AS_UPD_BILL_PROD_REQ
ADD CONSTRAINT UPDATE_PROD_BILLING_MASTER_FK1 FOREIGN KEY
(
  REQ_ID
)
REFERENCES ITTB_AS_MASTER_REQ
(
REQ_ID
) ENABLE
;

---------------------------------------------------------

CREATE TABLE ITTB_AS_UPD_BILL_ACCT_REQ
(
  REQ_ID VARCHAR2(14) NOT NULL,
  ACCT_ID VARCHAR2(18),
  NEW_CREDIT_LIMIT VARCHAR2(20),
  TOTAL_TXN_AMT_BILLED VARCHAR2(20),
  PARENT_ID VARCHAR2(18),
  UPDATE_BY VARCHAR2(50)
, CONSTRAINT ITTB_AS_UPD_BILL_ACCT_REQ_PK PRIMARY KEY
  (
    REQ_ID
  )
  ENABLE
)
;

ALTER TABLE ITTB_AS_UPD_BILL_ACCT_REQ
ADD CONSTRAINT UPDATE_ACCT_BILLING_MASTER_FK1 FOREIGN KEY
(
  REQ_ID
)
REFERENCES ITTB_AS_MASTER_REQ
(
REQ_ID
) ENABLE
;

---------------------------------------------------------

CREATE TABLE ITTB_AS_UPD_PAY_PROD_REQ
(
  REQ_ID VARCHAR2(14) NOT NULL,
  CARD_NO VARCHAR2(19),
  NEW_CREDIT_LIMIT VARCHAR2(20),
  ACCT_ID VARCHAR2(18),
  UPDATE_BY VARCHAR2(50)
, CONSTRAINT UPDATE_PROD_PYMT_REQUEST_PK PRIMARY KEY
  (
    REQ_ID
  )
  ENABLE
)
;

ALTER TABLE ITTB_AS_UPD_PAY_PROD_REQ
ADD CONSTRAINT UPDATE_PROD_PAYMENT_MASTER_FK1 FOREIGN KEY
(
  REQ_ID
)
REFERENCES ITTB_AS_MASTER_REQ
(
REQ_ID
) ENABLE
;

---------------------------------------------------------

CREATE TABLE ITTB_AS_UPD_PAY_ACCT_REQ
(
  REQ_ID VARCHAR2(14) NOT NULL,
  ACCT_ID VARCHAR2(18),
  NEW_CREDIT_LIMIT VARCHAR2(20),
  PARENT_ID VARCHAR2(18),
  UPDATE_BY VARCHAR2(50)
, CONSTRAINT UPDATE_ACCT_PYMT_REQUEST_PK PRIMARY KEY
  (
    REQ_ID
  )
  ENABLE
)
;

ALTER TABLE ITTB_AS_UPD_PAY_ACCT_REQ
ADD CONSTRAINT UPDATE_ACCT_PAYMENT_MASTER_FK1 FOREIGN KEY
(
  REQ_ID
)
REFERENCES ITTB_AS_MASTER_REQ
(
REQ_ID
) ENABLE
;

---------------------------------------------------------

CREATE TABLE ITTB_AS_UPD_USAGE_REQ
(
  REQ_ID VARCHAR2(14) NOT NULL,
  CARD_NO VARCHAR2(19),
  USAGE VARCHAR2(1),
  UPDATE_BY VARCHAR2(50)
, CONSTRAINT UPDATE_PRODUCT_USAGE_REQU_PK PRIMARY KEY
  (
    REQ_ID
  )
  ENABLE
)
;

ALTER TABLE ITTB_AS_UPD_USAGE_REQ
ADD CONSTRAINT UPDATE_PRODUCT_USAGE_REQU_FK1 FOREIGN KEY
(
  REQ_ID
)
REFERENCES ITTB_AS_MASTER_REQ
(
REQ_ID
) ENABLE
;

--------------------------------------- SEQUENCE CREATION

CREATE SEQUENCE  "ITTB_AS_MASTER_REQ_SQ1"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  CYCLE ;

CREATE OR REPLACE FUNCTION GET_NEXT_REQUEST_ID
RETURN VARCHAR2
AS
REQ_ID VARCHAR2(6);
BEGIN
select ITTB_AS_MASTER_REQ.nextval into REQ_ID from dual;
return req_id;
END GET_NEXT_REQUEST_ID;