-- sequence for REWARDS ACCOUNT --
CREATE SEQUENCE  "LRTB_REWARD_ACCOUNT_SQ1"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 2 CACHE 10 NOORDER  NOCYCLE ;
-- REWARDS ACCOUNT TABLE --
CREATE TABLE LRTB_REWARD_ACCOUNT (
	REWARD_ACCOUNT_NO NUMBER(8) NOT NULL,
	ACCOUNT_NO NUMBER(8) NOT NULL,
	CUT_OFF_DT TIMESTAMP NOT NULL,
	EXPIRE_DT TIMESTAMP,
	EXT_MTH_TO_EXPIRY NUMBER(2),
	VERSION NUMBER(9,0) DEFAULT 0,
	CONSTRAINT LRTB_REWARD_ACCOUNT_PK PRIMARY KEY(REWARD_ACCOUNT_NO),
	CONSTRAINT LRTB_REWARD_ACCOUNT_FK1 FOREIGN KEY(ACCOUNT_NO) REFERENCES AMTB_ACCOUNT(ACCOUNT_NO)
);
-- creating indexes --
CREATE INDEX LRTB_REWARD_ACCOUNT_N1 ON LRTB_REWARD_ACCOUNT (ACCOUNT_NO);

CREATE SEQUENCE  "LRTB_GIFT_CATEGORY_SQ1"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 2 CACHE 10 NOORDER  NOCYCLE ;
CREATE TABLE "LRTB_GIFT_CATEGORY" (
	"GIFT_CATEGORY_NO" NUMBER(8,0) NOT NULL ENABLE, 
	"CATEGORY_NAME" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
	"VERSION" NUMBER(9,0) DEFAULT 0, 
	CONSTRAINT "LRTB_GIFT_CATEGORY_PK" PRIMARY KEY ("GIFT_CATEGORY_NO") ENABLE
);

CREATE SEQUENCE  "LRTB_GIFT_ITEM_SQ1"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 2 CACHE 10 NOORDER  NOCYCLE ;
CREATE TABLE "LRTB_GIFT_ITEM" (
	"GIFT_ITEM_NO" NUMBER(8,0) NOT NULL ENABLE, 
	"ITEM_CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ITEM_NAME" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
	"PRICE" NUMBER(12,2) NOT NULL ENABLE, 
	"IMAGE" BLOB, 
	"VERSION" NUMBER(9,0) DEFAULT 0, 
	"GIFT_CATEGORY_NO" NUMBER(8,0) NOT NULL ENABLE, 
	"POINTS" NUMBER(8,0) NOT NULL ENABLE, 
	"STOCK" NUMBER(9,0), 
	CONSTRAINT "LRTB_GIFT_ITEM_PK" PRIMARY KEY ("GIFT_ITEM_NO") ENABLE, 
	CONSTRAINT "LRTB_GIFT_ITEM_UK1" UNIQUE ("ITEM_CODE") ENABLE
);

CREATE SEQUENCE  "LRTB_GIFT_STOCK_SQ1"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 2 CACHE 10 NOORDER  NOCYCLE ;
CREATE TABLE "LRTB_GIFT_STOCK" (
	"GIFT_STOCK_NO" NUMBER(8,0) NOT NULL ENABLE, 
	"TXN_TYPE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"TXN_DT" TIMESTAMP (6) NOT NULL ENABLE, 
	"VERSION" NUMBER(9,0) DEFAULT 0, 
	"ACCOUNT_NO" NUMBER(8,0), 
	"GIFT_ITEM_NO" NUMBER(8,0) NOT NULL ENABLE, 
	"TXN_QTY" NUMBER(9,0), 
	CONSTRAINT "LRTB_GIFT_STOCK_PK" PRIMARY KEY ("GIFT_STOCK_NO") ENABLE, 
	CONSTRAINT "LRTB_GIFT_STOCK_FK2" FOREIGN KEY ("GIFT_ITEM_NO") REFERENCES "LRTB_GIFT_ITEM" ("GIFT_ITEM_NO") ENABLE, 
	CONSTRAINT "LRTB_GIFT_STOCK_FK1" FOREIGN KEY ("ACCOUNT_NO") REFERENCES "AMTB_ACCOUNT" ("ACCOUNT_NO") ENABLE
);

COMMENT ON COLUMN "LRTB_GIFT_STOCK"."TXN_TYPE" IS 'I - STOCK IN, O - STOCK OUT, R - REDEEM';

-- sequence for REWARDS TXN --
CREATE SEQUENCE  "LRTB_REWARD_TXN_SQ1"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 2 CACHE 10 NOORDER  NOCYCLE ;
-- REWARDS TXN TABLE --
CREATE TABLE LRTB_REWARD_TXN (
	REWARD_TXN_NO NUMBER(8) NOT NULL,
	REWARD_ACCOUNT_NO NUMBER(8) NOT NULL,
	REWARD_PLAN_NO NUMBER(8),
	GIFT_STOCK_NO NUMBER(8,0), 
	INVOICE_HEADER_NO NUMBER(18),
	REWARDS_PTS NUMBER(8,0) NOT NULL,
	VERSION NUMBER(9,0) DEFAULT 0,
	CONSTRAINT LRTB_REWARD_TXN_PK PRIMARY KEY(REWARD_TXN_NO),
	CONSTRAINT LRTB_REWARD_TXN_FK1 FOREIGN KEY(REWARD_ACCOUNT_NO) REFERENCES LRTB_REWARD_ACCOUNT(REWARD_ACCOUNT_NO),
	CONSTRAINT LRTB_REWARD_TXN_FK2 FOREIGN KEY(REWARD_PLAN_NO) REFERENCES LRTB_REWARD_MASTER(REWARD_PLAN_NO),
	CONSTRAINT LRTB_REWARD_TXN_FK3 FOREIGN KEY(INVOICE_HEADER_NO) REFERENCES BMTB_INVOICE_HEADER(INVOICE_HEADER_NO),
	CONSTRAINT LRTB_REWARD_TXN_FK4 FOREIGN KEY (GIFT_STOCK_NO) REFERENCES LRTB_GIFT_STOCK (GIFT_STOCK_NO) ENABLE
);

COMMENT ON COLUMN "LRTB_REWARD_TXN"."GIFT_STOCK_NO" IS 'Redemption';

-- creating indexes --
CREATE INDEX LRTB_REWARD_TXN_N1 ON LRTB_REWARD_TXN (REWARD_ACCOUNT_NO);
CREATE INDEX LRTB_REWARD_TXN_N2 ON LRTB_REWARD_TXN (REWARD_PLAN_NO);
CREATE INDEX LRTB_REWARD_TXN_N3 ON LRTB_REWARD_TXN (INVOICE_HEADER_NO);
-- dumping default data --

--INVENTORY
CREATE TABLE "IMTB_ITEM_TYPE" (
"ITEM_TYPE_NO" NUMBER(8,0) NOT NULL ENABLE, 
"TYPE_NAME" VARCHAR2(80 BYTE) NOT NULL ENABLE, 
"PRICE" NUMBER(12,2) NOT NULL ENABLE, 
"VERSION" NUMBER(9,0) DEFAULT 0
);

CREATE TABLE "IMTB_ISSUE_REQ_FLOW" (
"ISSUE_REQ_FLOW_NO" NUMBER(8,0) NOT NULL ENABLE, 
"PARENT_REQ_FLOW_NO" NUMBER(8,0), 
"ISSUE_REQ_NO" NUMBER(8,0) NOT NULL ENABLE, 
"FROM_STATUS" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
"TO_STATUS" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
"REMARKS" VARCHAR2(500 BYTE), 
"FLOW_DT" TIMESTAMP (6) NOT NULL ENABLE, 
"USER_ID" NUMBER(10,0) NOT NULL ENABLE, 
"VERSION" NUMBER(9,0) DEFAULT 0
);

CREATE TABLE "IMTB_ISSUE_REQ" (
"ISSUE_REQ_NO" NUMBER(8,0) NOT NULL ENABLE, 
"ACCOUNT_NO" NUMBER(8,0) NOT NULL ENABLE, 
"ITEM_TYPE_NO" NUMBER(8,0) NOT NULL ENABLE, 
"ISSUE_REQ_FLOW_NO" NUMBER(8,0),
"QUANTITY" NUMBER(8,0) NOT NULL ENABLE, 
"REQUEST_DT" TIMESTAMP (6) NOT NULL ENABLE, 
"CREATE_BY" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"VERSION" NUMBER(9,0) DEFAULT 0
);

CREATE TABLE "IMTB_STOCK" (
"STOCK_NO" NUMBER(8,0) NOT NULL ENABLE, 
"ITEM_TYPE_NO" NUMBER(8,0) NOT NULL ENABLE, 
"TXN_TYPE" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
"TXN_DT" TIMESTAMP (6) NOT NULL ENABLE, 
"SERIAL_NO_START" NUMBER(25,0) NOT NULL ENABLE, 
"SERIAL_NO_END" NUMBER(25,0) NOT NULL ENABLE, 
"VERSION" NUMBER(9,0) DEFAULT 0
);

CREATE TABLE "IMTB_ISSUE" (
"ISSUE_NO" NUMBER(8,0) NOT NULL ENABLE, 
"STOCK_NO" NUMBER(8,0) NOT NULL ENABLE,
"EXPIRY_DATE" DATE, 
"HANDLING_FEE" NUMBER(12,2) NOT NULL ENABLE, 
"DISCOUNT" NUMBER(12,2) NOT NULL ENABLE, 
"USER_ID" NUMBER(8,0) NOT NULL ENABLE, 
"VERSION" NUMBER(9,0) DEFAULT 0
);

CREATE TABLE "IMTB_ITEM" (
"ITEM_TYPE_NO" NUMBER(8,0) NOT NULL ENABLE, 
"SERIAL_NO" NUMBER(25,0) NOT NULL ENABLE, 
"ISSUE_NO" NUMBER(8,0) NOT NULL ENABLE, 
"ITEM_NO" NUMBER(18,0) NOT NULL ENABLE,
"STATUS" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
"UPDATE_DT" TIMESTAMP (6) NOT NULL ENABLE, 
"VERSION" NUMBER(9,0) DEFAULT 0
);


ALTER TABLE "IMTB_ITEM_TYPE" ADD CONSTRAINT "IMTB_ITEM_TYPE_PK" PRIMARY KEY ("ITEM_TYPE_NO") ENABLE;
ALTER TABLE "IMTB_ISSUE_REQ_FLOW" ADD CONSTRAINT "IMTB_ISSUE_REQ_FLOW_PK" PRIMARY KEY ("ISSUE_REQ_FLOW_NO") ENABLE;
ALTER TABLE "IMTB_ISSUE_REQ" ADD CONSTRAINT "IMTB_REQUEST_PK" PRIMARY KEY ("ISSUE_REQ_NO") ENABLE;
ALTER TABLE "IMTB_STOCK" ADD CONSTRAINT "IMTB_STOCK_PK" PRIMARY KEY ("STOCK_NO") ENABLE;
ALTER TABLE "IMTB_ISSUE" ADD CONSTRAINT "IMTB_ISSUE_PK" PRIMARY KEY ("ISSUE_NO") ENABLE;
ALTER TABLE "IMTB_ITEM" ADD CONSTRAINT "IMTB_ITEM_PK" PRIMARY KEY ("ITEM_NO") ENABLE;

ALTER TABLE "IMTB_ISSUE_REQ_FLOW" ADD CONSTRAINT "IMTB_ISSUE_REQ_FLOW_FK2" FOREIGN KEY ("USER_ID") REFERENCES "SATB_USER" ("USER_ID") ENABLE;
ALTER TABLE "IMTB_ISSUE_REQ_FLOW" ADD CONSTRAINT "IMTB_ISSUE_REQ_FLOW_FK1" FOREIGN KEY ("ISSUE_REQ_NO") REFERENCES "IMTB_ISSUE_REQ" ("ISSUE_REQ_NO") ENABLE;
ALTER TABLE "IMTB_ISSUE_REQ_FLOW" ADD CONSTRAINT "IMTB_ISSUE_REQ_FLOW_FK3" FOREIGN KEY ("PARENT_REQ_FLOW_NO") REFERENCES "IMTB_ISSUE_REQ_FLOW" ("ISSUE_REQ_FLOW_NO") ENABLE;

ALTER TABLE "IMTB_ISSUE_REQ" ADD CONSTRAINT "IMTB_ISSUE_REQ_FK1" FOREIGN KEY ("ACCOUNT_NO") REFERENCES "AMTB_ACCOUNT" ("ACCOUNT_NO") ENABLE;
ALTER TABLE "IMTB_ISSUE_REQ" ADD CONSTRAINT "IMTB_ISSUE_REQ_FK2" FOREIGN KEY ("ITEM_TYPE_NO") REFERENCES "IMTB_ITEM_TYPE" ("ITEM_TYPE_NO") ENABLE;
ALTER TABLE "IMTB_ISSUE_REQ" ADD CONSTRAINT "IMTB_ISSUE_REQ_FK3" FOREIGN KEY ("ISSUE_REQ_FLOW_NO") REFERENCES "IMTB_ISSUE_REQ_FLOW" ("ISSUE_REQ_FLOW_NO") ENABLE;

ALTER TABLE "IMTB_STOCK" ADD CONSTRAINT "IMTB_STOCK_FK1" FOREIGN KEY ("ITEM_TYPE_NO") REFERENCES "IMTB_ITEM_TYPE" ("ITEM_TYPE_NO") ENABLE;
COMMENT ON COLUMN "IMTB_STOCK"."TXN_TYPE" IS 'I - Stock In, O - Stock Out';

ALTER TABLE "IMTB_ISSUE" ADD CONSTRAINT "IMTB_ISSUE_UK1" UNIQUE ("STOCK_NO") ENABLE;
ALTER TABLE "IMTB_ISSUE" ADD CONSTRAINT "IMTB_ISSUE_FK1" FOREIGN KEY ("ISSUE_NO") REFERENCES "IMTB_ISSUE_REQ" ("ISSUE_REQ_NO") ENABLE;
ALTER TABLE "IMTB_ISSUE" ADD CONSTRAINT "IMTB_ISSUE_FK2" FOREIGN KEY ("USER_ID") REFERENCES "SATB_USER" ("USER_ID") ENABLE;
ALTER TABLE "IMTB_ISSUE" ADD CONSTRAINT "IMTB_ISSUE_FK3" FOREIGN KEY ("STOCK_NO") REFERENCES "IMTB_STOCK" ("STOCK_NO") ENABLE;
--CREATE UNIQUE INDEX "IMTB_ISSUE_UN1" ON "IMTB_ISSUE" ("ISSUE_NO");
--CREATE UNIQUE INDEX "IMTB_ISSUE_UN2" ON "IMTB_ISSUE" ("STOCK_NO");

ALTER TABLE "IMTB_ITEM" ADD CONSTRAINT "IMTB_ITEM_UK1" UNIQUE ("ITEM_TYPE_NO", "SERIAL_NO") ENABLE;
ALTER TABLE "IMTB_ITEM" ADD CONSTRAINT "IMTB_ITEM_FK1" FOREIGN KEY ("ITEM_TYPE_NO") REFERENCES "IMTB_ITEM_TYPE" ("ITEM_TYPE_NO") ENABLE;
ALTER TABLE "IMTB_ITEM" ADD CONSTRAINT "IMTB_ITEM_FK2" FOREIGN KEY ("ISSUE_NO") REFERENCES "IMTB_ISSUE" ("ISSUE_NO") ENABLE;
COMMENT ON COLUMN "IMTB_ITEM"."STATUS" IS 'I - Issued, R - Redeemed';
--CREATE UNIQUE INDEX "IMTB_ITEM_PK" ON "IMTB_ITEM" ("ITEM_NO");
--CREATE UNIQUE INDEX "IMTB_ITEM_UN1" ON "IMTB_ITEM" ("ITEM_TYPE_NO", "SERIAL_NO");

DROP TABLE IMTB_ITEM;
DROP TABLE IMTB_ISSUE;
DROP TABLE IMTB_STOCK;
ALTER TABLE IMTB_ISSUE_REQ DROP CONSTRAINT IMTB_ISSUE_REQ_FK3;
DROP TABLE IMTB_ISSUE_REQ_FLOW;
DROP TABLE IMTB_ISSUE_REQ;
DROP TABLE IMTB_ITEM_TYPE;
DROP TABLE LRTB_GIFT_CATEGORY;
DROP TABLE LRTB_REWARD_TXN;
DROP TABLE LRTB_REWARD_ACCOUNT;
DROP TABLE LRTB_GIFT_STOCK;
DROP TABLE LRTB_GIFT_ITEM;
DROP SEQUENCE LRTB_REWARD_TXN_SQ1;
DROP SEQUENCE LRTB_REWARD_ACCOUNT_SQ1;