CREATE TABLE ASVW_ACCOUNT
(
  ACCT_ID VARCHAR2(25) NOT NULL,
  ACCT_TYPE VARCHAR2(2) NOT NULL,
  CREDIT_LIMIT NUMBER(*, 2) ,
  TOTAL_TXN_AMT NUMBER(*, 2) DEFAULT 0,
  PARENT_ID VARCHAR2(25),
  CREATE_DATE TIMESTAMP(6), 
  CREATE_BY VARCHAR2(50), 
  UPDATE_DATE TIMESTAMP(6), 
  UPDATE_BY VARCHAR2(50)
, CONSTRAINT ACCOUNT_PK PRIMARY KEY
  (
    ACCT_ID
  )
  ENABLE
)
;

ALTER TABLE ASVW_ACCOUNT
ADD CONSTRAINT ACCOUNT_ACCOUNT_FK1 FOREIGN KEY
(
  PARENT_ID
)
REFERENCES ASVW_ACCOUNT
(
ACCT_ID
) ENABLE
;

CREATE TABLE ASVW_PRODUCT_TYPE
(
  PROD_TYPE_ID VARCHAR2(2) NOT NULL,
  PROD_NAME VARCHAR2(50) NOT NULL,
  BIN_RANGE VARCHAR2(6),
  SUB_BIN_RANGE VARCHAR2(4),
  ONE_TIME_USAGE_FLG CHAR(1) DEFAULT 'N' NOT NULL,
  FIXED_VALUE_FLG CHAR(1) DEFAULT 'N' NOT NULL,
  CREDIT_LIMIT_FLG CHAR(1) DEFAULT 'N' NOT NULL,
  NEGATIVE_FILE_CHECK_FLG CHAR(1) DEFAULT 'N' NOT NULL,
  EXPIRY_DATE_FLG CHAR(1) DEFAULT 'N' NOT NULL,
  STATUS CHAR(1) NOT NULL,
  CREATE_DATE TIMESTAMP(6),
  CREATE_BY VARCHAR2(50)
, CONSTRAINT PRODUCT_TYPE_PK PRIMARY KEY
  (
    PROD_TYPE_ID
  )
  ENABLE
)
;

ALTER TABLE ASVW_PRODUCT_TYPE
ADD CONSTRAINT PRODUCT_TYPE_UK1 UNIQUE
(
  PROD_NAME
)
 ENABLE
;

CREATE TABLE ASVW_PRODUCT
(
  CARD_NO VARCHAR2(19) NOT NULL,
  ACCT_ID VARCHAR2(25) NOT NULL,
  PROD_TYPE_ID VARCHAR2(2) NOT NULL,
  FIXED_VALUE NUMBER(*, 2),
  CREDIT_LIMIT NUMBER(*, 2),
  TOTAL_TXN_AMT NUMBER(*, 2) DEFAULT 0,
  STATUS CHAR(1) NOT NULL,
  REASON_CODE CHAR(1),
  USED CHAR(1),
  CREATE_DATE TIMESTAMP(6), 
  CREATE_BY VARCHAR2(50), 
  UPDATE_DATE TIMESTAMP(6), 
  UPDATE_BY VARCHAR2(50)
, CONSTRAINT PRODUCT_PK PRIMARY KEY
  (
    CARD_NO
  )
  ENABLE
)
;

ALTER TABLE ASVW_PRODUCT
ADD CONSTRAINT PRODUCT_ACCOUNT_FK1 FOREIGN KEY
(
  ACCT_ID
)
REFERENCES ASVW_ACCOUNT
(
ACCT_ID
) ENABLE
;

ALTER TABLE ASVW_PRODUCT
ADD CONSTRAINT PRODUCT_PRODUCT_TYPE_FK1 FOREIGN KEY
(
  PROD_TYPE_ID
)
REFERENCES ASVW_PRODUCT_TYPE
(
PROD_TYPE_ID
) ENABLE
;

CREATE TABLE ASVW_PRODUCT_EXPIRY_DATE
(
  ID NUMBER(18) NOT NULL,
  CARD_NO VARCHAR2(19) NOT NULL,
  EXPIRY_DATE VARCHAR2(4) NOT NULL
, CONSTRAINT PRODUCT_EXPIRY_DATE_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
)
;

ALTER TABLE ASVW_PRODUCT_EXPIRY_DATE
ADD CONSTRAINT PRODUCT_EXPIRY_DATE_UK1 UNIQUE
(
  CARD_NO,
  EXPIRY_DATE
)
 ENABLE
;

ALTER TABLE ASVW_PRODUCT_EXPIRY_DATE
ADD CONSTRAINT PRODUCT_EXPIRY_DATE_PRODU_FK1 FOREIGN KEY
(
  CARD_NO
)
REFERENCES ASVW_PRODUCT
(
CARD_NO
) ENABLE
;