CREATE INDEX TMTB_ACQUIRE_TXN_N12 ON TMTB_ACQUIRE_TXN (PRODUCT_TYPE_ID,TRIP_START_DT,TRIP_END_DT);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO, MASTER_TYPE, MASTER_CODE, INTERFACE_MAPPING_VALUE, MASTER_VALUE, MASTER_STATUS) VALUES ('117', 'TR', 'TC', 'C', 'TERMINATED (E-VOUCHER)', 'I');

CREATE INDEX AMTB_ACCOUNT_N9 ON AMTB_ACCOUNT (CODE);