alter table TMTB_TXN_REVIEW_REQ add PROJECT_DESC VARCHAR2(80);

--SENGTAT: CARD REPLACEMENT TO HAVE BILL_FLAG
ALTER TABLE "PMTB_PRODUCT_REPLACEMENT"
ADD (
    BILLED_FLAG VARCHAR2(1) DEFAULT 'N' NOT NULL
);
