--SENGTAT: INVOICE HEADER DUE DATE CAN BE NULL
--THIS MEANS THAT THE INVOICE WILL NEVER BE DUE
ALTER TABLE BMTB_INVOICE_HEADER 
MODIFY ("DUE_DATE" NULL)
;
--END


--WILSON: VIEW INVOICE
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (506, '29', 'Search Invoice', 'U', '/billing/invoice/search_invoice.zul', '4', 'View Invoice', 'Y', '0');
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (507, '29', 'View Invoice', 'U', '/billing/invoice/view_invoice.zul', '5', 'View Invoice', 'N', '0');

INSERT INTO SATB_ROLE_RESOURCE (ROLE_ID, RSRC_ID) VALUES(2, 506);
INSERT INTO SATB_ROLE_RESOURCE (ROLE_ID, RSRC_ID) VALUES(2, 507);
--END
-- adding interface value to product type table
alter table PMTB_PRODUCT_TYPE add INTERFACE_MAPPING_VALUE VARCHAR2(80);