--SENGTAT: NO LONGER NEED FOR ACCOUNT
ALTER TABLE "BMTB_BILL_GEN_REQ" DROP COLUMN FOR_ACCOUNT;
--END

--SENGTAT: REGEN SETUP NO
ALTER TABLE "BMTB_BILL_GEN_REQ"
ADD (
    REGEN_SETUP_NO NUMBER(9) ,
	CONSTRAINT "BMTB_BILL_GEN_REQ_FK3" FOREIGN KEY ("REGEN_SETUP_NO")
	  REFERENCES "BMTB_BILL_GEN_SETUP" ("SETUP_NO") ENABLE
);
CREATE INDEX "BMTB_BILL_GEN_REQ_N2" ON BMTB_BILL_GEN_REQ(REGEN_SETUP_NO);
--END