CREATE SEQUENCE  "BMTB_DRAFT_INV_FILE_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_DRAFT_INV_HEADER_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_DRAFT_INV_HEADER_SQ2"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_DRAFT_INV_SUMMARY_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_DRAFT_INV_DETAIL_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_DRAFT_INV_TXN_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_DRAFT_INV_PYMT_HEADER_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "BMTB_DRAFT_INV_PYMT_DETAIL_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;

/***************************************************************/

CREATE TABLE BMTB_DRAFT_INV_FILE
(
  FILE_NO NUMBER(18) NOT NULL,
  INVOICE_FILE BLOB,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP,
  VERSION NUMBER(9) DEFAULT 0
)
;

ALTER TABLE BMTB_DRAFT_INV_FILE ADD CONSTRAINT BMTB_DRAFT_INV_FILE_PK PRIMARY KEY (FILE_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_DRAFT_INV_HEADER
(
  INVOICE_HEADER_NO NUMBER(18) NOT NULL,
  REQ_NO NUMBER(18),
  ACCOUNT_NO NUMBER(8) NOT NULL,
  DEBT_TO NUMBER(8) NOT NULL,
  INVOICE_NO NUMBER(18),
  INVOICE_DATE DATE NOT NULL,
  INVOICE_STATUS VARCHAR2(1) NOT NULL,
  INVOICE_FORMAT VARCHAR2(1) NOT NULL,
  DUE_DATE DATE,
  STATEMENT_PERIOD_FROM_DATE DATE,
  STATEMENT_PERIOD_TO_DATE DATE,
  PREV_BALANCE NUMBER(12,2) DEFAULT 0 NOT NULL,
  PREV_PAYMENT NUMBER(12,2) DEFAULT 0 NOT NULL,
  NEW_TXN NUMBER(12,2) DEFAULT 0 NOT NULL,
  NEW_BALANCE NUMBER(12,2) DEFAULT 0 NOT NULL,
  LESS_30_DAYS NUMBER(12,2) DEFAULT 0 NOT NULL,
  LESS_60_DAYS NUMBER(12,2) DEFAULT 0 NOT NULL,
  LESS_90_DAYS NUMBER(12,2) DEFAULT 0 NOT NULL,
  MORE_90_DAYS NUMBER(12,2) DEFAULT 0 NOT NULL,
  PREV_REWARDS_PTS NUMBER(8) DEFAULT 0,
  REDEEMED_REWARDS_PTS NUMBER(8) DEFAULT 0,
  NEW_REWARDS_PTS NUMBER(8) DEFAULT 0,
  TOTAL_REWARDS_PTS NUMBER(8) DEFAULT 0,
  ACCOUNT_DEPOSIT NUMBER(12,2) DEFAULT 0,
  ACCOUNT_EXCESS NUMBER(12,2) DEFAULT 0,
  OVERDUE_INVOICE VARCHAR2(255),
  TXN_CUTOFF_DATE DATE,
  LATE_PAYMENT_INTEREST NUMBER(5,2) DEFAULT 0 NOT NULL,
  LATE_PAYMENT_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  LAST_LATE_PAYMENT_CHARGED_DATE DATE,
  LATE_PAYMENT_FLAG VARCHAR2(1) DEFAULT 'N' NOT NULL,
  EARLY_PAYMENT_FLAG VARCHAR2(1) DEFAULT 'N' NOT NULL,
  OUTSTANDING_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  TOTAL_FARE_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  TOTAL_NO_OF_TRIP NUMBER(8,0) DEFAULT 0 NOT NULL,
  REMARKS VARCHAR2(500),
  BILLED_FLAG VARCHAR2(1),
  FILE_NO NUMBER(18),
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP,
  VERSION NUMBER(9) DEFAULT 0
)
;

COMMENT ON COLUMN BMTB_DRAFT_INV_HEADER.TOTAL_FARE_AMOUNT IS 'FOR CALCULATION OF VOLUME DISCOUNT';
COMMENT ON COLUMN BMTB_DRAFT_INV_HEADER.TOTAL_NO_OF_TRIP IS 'FOR CALCULATION OF VOLUME DISCOUNT';
COMMENT ON COLUMN BMTB_DRAFT_INV_HEADER.LATE_PAYMENT_FLAG IS 'N = NO, Y = YES';
COMMENT ON COLUMN BMTB_DRAFT_INV_HEADER.INVOICE_STATUS IS 'O = OUTSTANDING, C = CLOSED';
COMMENT ON COLUMN BMTB_DRAFT_INV_HEADER.INVOICE_FORMAT IS 'A = ACCOUNT FORMAT, S = SUBACCOUNT, P = PERSONAL, M = MISC, D = DEPOSIT';
ALTER TABLE BMTB_DRAFT_INV_HEADER ADD CONSTRAINT BMTB_DRAFT_INV_HEADER_PK PRIMARY KEY ("INVOICE_HEADER_NO") ENABLE;
ALTER TABLE BMTB_DRAFT_INV_HEADER ADD CONSTRAINT BMTB_DRAFT_INV_HEADER_FK1 FOREIGN KEY(ACCOUNT_NO) REFERENCES AMTB_ACCOUNT(ACCOUNT_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_HEADER ADD CONSTRAINT BMTB_DRAFT_INV_HEADER_FK2 FOREIGN KEY(DEBT_TO) REFERENCES AMTB_ACCOUNT(ACCOUNT_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_HEADER ADD CONSTRAINT BMTB_DRAFT_INV_HEADER_FK3 FOREIGN KEY(REQ_NO) REFERENCES BMTB_BILL_GEN_REQ(REQ_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_HEADER ADD CONSTRAINT BMTB_DRAFT_INV_HEADER_FK4 FOREIGN KEY(FILE_NO) REFERENCES BMTB_DRAFT_INV_FILE(FILE_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_DRAFT_INV_SUMMARY
(
  INVOICE_SUMMARY_NO NUMBER(18) NOT NULL,
  INVOICE_HEADER_NO NUMBER(18) NOT NULL,
  ACCOUNT_NO NUMBER(8) ,
  PRODUCT_TYPE_ID VARCHAR2(2) ,
  SUMMARY_TYPE VARCHAR2(2) ,
  SUMMARY_NAME VARCHAR2(80) NOT NULL,
  DISPLAY_PRIORITY_1 NUMBER(1) NOT NULL,
  DISPLAY_PRIORITY_2 NUMBER(1) NOT NULL,
  PREV_BALANCE NUMBER(12,2) DEFAULT 0 NOT NULL,
  PREV_PAYMENT NUMBER(12,2) DEFAULT 0 NOT NULL,
  NEW_TXN NUMBER(12,2) DEFAULT 0 NOT NULL,
  ADMIN_FEE NUMBER(12,2) DEFAULT 0 NOT NULL,
  GST NUMBER(12,2) DEFAULT 0 NOT NULL,
  TOTAL_NEW NUMBER(12,2) DEFAULT 0 NOT NULL,
  BALANCE NUMBER(12,2) DEFAULT 0 NOT NULL,
  UNIT_PRICE NUMBER(12,2) DEFAULT 0,
  QUANTITY NUMBER(18) DEFAULT 0,
  DISCOUNT NUMBER(12,2) DEFAULT 0
)
;

COMMENT ON COLUMN BMTB_DRAFT_INV_SUMMARY.UNIT_PRICE IS 'APPLICABLE FOR MISC INVOICE ONLY';
COMMENT ON COLUMN BMTB_DRAFT_INV_SUMMARY.QUANTITY IS 'APPLICABLE FOR MISC INVOICE ONLY';
COMMENT ON COLUMN BMTB_DRAFT_INV_SUMMARY.DISCOUNT IS 'APPLICABLE FOR MISC INVOICE ONLY';
COMMENT ON COLUMN BMTB_DRAFT_INV_SUMMARY.SUMMARY_TYPE IS 'TRANSACTION SUMMARY SECTION GROUPING NAME (ACCOUNT NAME + ACCOUNT CODE)';
COMMENT ON COLUMN BMTB_DRAFT_INV_SUMMARY.SUMMARY_NAME IS 'INDIVIDUAL PRODUCT TYPE NAME IN THE TRANSACTION SUMMARY SECTION';
ALTER TABLE BMTB_DRAFT_INV_SUMMARY ADD CONSTRAINT BMTB_DRAFT_INV_SUMMARY_PK PRIMARY KEY (INVOICE_SUMMARY_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_SUMMARY ADD CONSTRAINT BMTB_DRAFT_INV_SUMMARY_FK1 FOREIGN KEY(INVOICE_HEADER_NO) REFERENCES BMTB_DRAFT_INV_HEADER(INVOICE_HEADER_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_SUMMARY ADD CONSTRAINT BMTB_DRAFT_INV_SUMMARY_FK2 FOREIGN KEY(PRODUCT_TYPE_ID) REFERENCES PMTB_PRODUCT_TYPE(PRODUCT_TYPE_ID) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_SUMMARY ADD CONSTRAINT BMTB_DRAFT_INV_SUMMARY_FK3 FOREIGN KEY(ACCOUNT_NO) REFERENCES AMTB_ACCOUNT(ACCOUNT_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_DRAFT_INV_DETAIL
(
  INVOICE_DETAIL_NO NUMBER(18) NOT NULL,
  INVOICE_SUMMARY_NO NUMBER(18) NOT NULL,
  PRODUCT_NO NUMBER(19) ,
  PRODUCT_TYPE_ID VARCHAR2(2),
  ACCOUNT_NO NUMBER(8) NOT NULL,
  INVOICE_DETAIL_NAME VARCHAR2(80),
  INVOICE_DETAIL_TYPE VARCHAR2(2) NOT NULL,
  NEW_TXN NUMBER(12,2) DEFAULT 0 NOT NULL,
  ADMIN_FEE NUMBER(12,2) DEFAULT 0 NOT NULL,
  GST NUMBER(12,2) DEFAULT 0 NOT NULL,
  TOTAL_NEW NUMBER(12,2) DEFAULT 0 NOT NULL,
  CARD_NAME VARCHAR2(80),
  CARD_NO VARCHAR2(19),
  CARD_CREDIT_LIMIT NUMBER(12,2),
  CARD_REPLACEMENT NUMBER(12,2),
  CARD_REPLACEMENT_GST NUMBER(12,2),
  CARD_REPLACEMENT_GST_PERCENT NUMBER(5,2),
  SUBSCRIPTION_FEE NUMBER(12,2),
  SUBSCRIPTION_FEE_GST NUMBER(12,2),
  SUBSCRIPTION_FEE_GST_PERCENT NUMBER(5,2),
  ORI_ADMIN_FEE NUMBER(12,2) DEFAULT 0 NOT NULL,
  PROD_DIS NUMBER(12,2) DEFAULT 0 NOT NULL,
  PROMO_DIS NUMBER(12,2) DEFAULT 0 NOT NULL,
  TXN_CODE NUMBER(8),
  OUTSTANDING_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP,
  VERSION NUMBER(9) DEFAULT 0
)
;

COMMENT ON COLUMN BMTB_DRAFT_INV_DETAIL.CARD_REPLACEMENT IS 'A SNAPSHOT OF THE REPLACEMENT FEE AMOUNT BUT NOT ACCUMULATED INTO DETAIL OUTSTANDING AMOUNT';
COMMENT ON COLUMN BMTB_DRAFT_INV_DETAIL.INVOICE_DETAIL_NAME IS 'NAME TO BE DISPLAYED AS THE DETAIL HEADER, NOT APPLICABLE TO PERSONAL FORMAT';
COMMENT ON COLUMN BMTB_DRAFT_INV_DETAIL.INVOICE_DETAIL_TYPE IS 'TO INDICATE WHETHER IT IS A NORMAL OR CREDIT/DEBIT DETAIL: N = NORMAL, C = CREDIT/DEBIT';
ALTER TABLE BMTB_DRAFT_INV_DETAIL ADD CONSTRAINT BMTB_DRAFT_INV_DETAIL_PK PRIMARY KEY (INVOICE_DETAIL_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_DETAIL ADD CONSTRAINT BMTB_DRAFT_INV_DETAIL_FK1 FOREIGN KEY(INVOICE_SUMMARY_NO) REFERENCES BMTB_DRAFT_INV_SUMMARY(INVOICE_SUMMARY_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_DETAIL ADD CONSTRAINT BMTB_DRAFT_INV_DETAIL_FK2 FOREIGN KEY(PRODUCT_NO) REFERENCES PMTB_PRODUCT(PRODUCT_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_DETAIL ADD CONSTRAINT BMTB_DRAFT_INV_DETAIL_FK3 FOREIGN KEY(ACCOUNT_NO) REFERENCES AMTB_ACCOUNT(ACCOUNT_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_DETAIL ADD CONSTRAINT BMTB_DRAFT_INV_DETAIL_FK4 FOREIGN KEY(PRODUCT_TYPE_ID) REFERENCES PMTB_PRODUCT_TYPE(PRODUCT_TYPE_ID) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_DETAIL ADD CONSTRAINT BMTB_DRAFT_INV_DETAIL_FK5 FOREIGN KEY(TXN_CODE) REFERENCES FMTB_TRANSACTION_CODE(TRANSACTION_CODE_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_DRAFT_INV_TXN
(
  INVOICE_TXN_NO NUMBER(18) NOT NULL,
  INVOICE_DETAIL_NO NUMBER(18) NOT NULL,
  CARD_NO VARCHAR2(19),
  JOB_TYPE VARCHAR2(80),
  JOB_REF_NO VARCHAR2(10),
  FLIGHT_INFO VARCHAR2(40),
  BOOKING_REF VARCHAR2(40),
  BOOKED_BY VARCHAR2(80),
  TAXI_NO VARCHAR2(10),
  VEHICLE_TYPE VARCHAR2(500),
  PICKUP VARCHAR2(255),
  DESTINATION VARCHAR2(255),
  TXN_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  ADMIN_FEE NUMBER(12,2) DEFAULT 0 NOT NULL,
  ADMIN_FEE_PERCENT NUMBER(5,2) DEFAULT 0 NOT NULL,
  GST NUMBER(12,2) DEFAULT 0 NOT NULL,
  GST_PERCENT NUMBER(5,2) DEFAULT 0 NOT NULL,
  "ORI_ADMIN_FEE" NUMBER(12,2) DEFAULT 0 NOT NULL,
  "PROD_DIS_PERCENT" NUMBER(5,2) DEFAULT 0 NOT NULL, 
  "PROD_DIS_VALUE" NUMBER(12,2) DEFAULT 0 NOT NULL, 
  "PROMO_DIS_PERCENT" NUMBER(5,2) DEFAULT 0 NOT NULL, 
  "PROMO_DIS_VALUE" NUMBER(12,2) DEFAULT 0 NOT NULL,
  TOTAL NUMBER(12,2) DEFAULT 0,
  PASSENGER_NAME VARCHAR2(80),
  SURCHARGE VARCHAR2(255),
  TRIP_START_DT TIMESTAMP,
  TRIP_END_DT TIMESTAMP,
  PROJECT_CODE VARCHAR2(80),
  ISSUED_INVOICE_NO NUMBER(18),
  ISSUED_INVOICE_DATE DATE, 
  NOTE VARCHAR2(20),
  DESCRIPTION VARCHAR2(255)
)
;

COMMENT ON COLUMN BMTB_DRAFT_INV_TXN.DESCRIPTION IS 'USED FOR TRANSACTION DETAILS LIKE CREDIT/DEBIT NOTE DESCRIPTION: WAIVE LATE PAYMENT';
ALTER TABLE BMTB_DRAFT_INV_TXN ADD CONSTRAINT BMTB_DRAFT_INV_TXN_PK PRIMARY KEY (INVOICE_TXN_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_TXN ADD CONSTRAINT BMTB_DRAFT_INV_TXN_FK1 FOREIGN KEY(INVOICE_DETAIL_NO) REFERENCES BMTB_DRAFT_INV_DETAIL(INVOICE_DETAIL_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_DRAFT_INV_PAYMENT_HEADER
(
  INVOICE_PAYMENT_NO NUMBER(18) NOT NULL,
  INVOICE_HEADER_NO NUMBER(18) NOT NULL,
  HEADER_TYPE VARCHAR2(1) NOT NULL,
  PAYMENT_TYPE VARCHAR2(50) NOT NULL,
  PAYMENT_REF_NO VARCHAR2(30) NOT NULL,
  PAYMENT_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL
)
;

COMMENT ON COLUMN BMTB_DRAFT_INV_PAYMENT_HEADER.HEADER_TYPE IS 'R = PAYMENT RECEIVED, C = PAYMENT CANCELED, A = PAYMENT APPLIED';
COMMENT ON COLUMN BMTB_DRAFT_INV_PAYMENT_HEADER.PAYMENT_TYPE IS 'EXAMPLE CONTRA OR CREDIT CARD';
ALTER TABLE BMTB_DRAFT_INV_PAYMENT_HEADER ADD CONSTRAINT BMTB_DRAFT_INV_PYMT_HEADER_PK PRIMARY KEY (INVOICE_PAYMENT_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_PAYMENT_HEADER ADD CONSTRAINT BMTB_DRAFT_INV_PYMT_HEADER_FK1 FOREIGN KEY(INVOICE_HEADER_NO) REFERENCES BMTB_DRAFT_INV_HEADER(INVOICE_HEADER_NO) ENABLE;

/***************************************************************/

CREATE TABLE BMTB_DRAFT_INV_PAYMENT_DETAIL
(
  INVOICE_PAYMENT_DETAIL_NO NUMBER(18) NOT NULL,
  INVOICE_PAYMENT_NO NUMBER(18) NOT NULL,
  INVOICE_NO NUMBER(18) NOT NULL,
  ACCOUNT_NAME VARCHAR2(80) NOT NULL,
  PAYMENT_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL
)
;

ALTER TABLE BMTB_DRAFT_INV_PAYMENT_DETAIL ADD CONSTRAINT BMTB_DRAFT_INV_PYMT_DETAIL_PK PRIMARY KEY (INVOICE_PAYMENT_DETAIL_NO) ENABLE;
ALTER TABLE BMTB_DRAFT_INV_PAYMENT_DETAIL ADD CONSTRAINT BMTB_DRAFT_INV_PYMT_DETAIL_FK1 FOREIGN KEY(INVOICE_PAYMENT_NO) REFERENCES BMTB_DRAFT_INV_PAYMENT_HEADER(INVOICE_PAYMENT_NO) ENABLE;


CREATE INDEX "BMTB_DRAFT_INV_HEADER_N1" ON BMTB_DRAFT_INV_HEADER(ACCOUNT_NO);
CREATE INDEX "BMTB_DRAFT_INV_HEADER_N2" ON BMTB_DRAFT_INV_HEADER(DEBT_TO);
CREATE INDEX "BMTB_DRAFT_INV_HEADER_N3" ON BMTB_DRAFT_INV_HEADER(REQ_NO);
CREATE INDEX "BMTB_DRAFT_INV_HEADER_N4" ON BMTB_DRAFT_INV_HEADER(FILE_NO);
CREATE INDEX "BMTB_DRAFT_INV_SUMMARY_N1" ON BMTB_DRAFT_INV_SUMMARY(INVOICE_HEADER_NO);
CREATE INDEX "BMTB_DRAFT_INV_SUMMARY_N2" ON BMTB_DRAFT_INV_SUMMARY(PRODUCT_TYPE_ID);
CREATE INDEX "BMTB_DRAFT_INV_SUMMARY_N3" ON BMTB_DRAFT_INV_SUMMARY(ACCOUNT_NO);
CREATE INDEX "BMTB_DRAFT_INV_DETAIL_N1" ON BMTB_DRAFT_INV_DETAIL(INVOICE_SUMMARY_NO);
CREATE INDEX "BMTB_DRAFT_INV_DETAIL_N2" ON BMTB_DRAFT_INV_DETAIL(PRODUCT_NO);
CREATE INDEX "BMTB_DRAFT_INV_DETAIL_N3" ON BMTB_DRAFT_INV_DETAIL(ACCOUNT_NO);
CREATE INDEX "BMTB_DRAFT_INV_DETAIL_N4" ON BMTB_DRAFT_INV_DETAIL(PRODUCT_TYPE_ID);
CREATE INDEX "BMTB_DRAFT_INV_DETAIL_N5" ON BMTB_DRAFT_INV_DETAIL(TXN_CODE);
CREATE INDEX "BMTB_DRAFT_INV_TXN_N1" ON BMTB_DRAFT_INV_TXN(INVOICE_DETAIL_NO);
CREATE INDEX "BMTB_DRAFT_INV_PYMT_HEADER_N1" ON BMTB_DRAFT_INV_PAYMENT_HEADER(INVOICE_HEADER_NO);
CREATE INDEX "BMTB_DRAFT_INV_PYMT_DETAIL_N1" ON BMTB_DRAFT_INV_PAYMENT_DETAIL(INVOICE_PAYMENT_NO);

CREATE INDEX BMTB_DRAFT_INV_HEADER_N5 ON BMTB_DRAFT_INV_HEADER(DEBT_TO, DUE_DATE);
CREATE INDEX BMTB_DRAFT_INV_HEADER_N6 ON BMTB_DRAFT_INV_HEADER(DEBT_TO, INVOICE_FORMAT, BILLED_FLAG, INVOICE_DATE);
CREATE INDEX BMTB_DRAFT_INV_HEADER_N7 ON BMTB_DRAFT_INV_HEADER(DEBT_TO, INVOICE_STATUS, DUE_DATE, INVOICE_NO, OUTSTANDING_AMOUNT);
CREATE INDEX BMTB_DRAFT_INV_HEADER_N8 ON BMTB_DRAFT_INV_HEADER(INVOICE_NO, REQ_NO);
CREATE INDEX BMTB_DRAFT_INV_SUMMARY_N4 ON BMTB_DRAFT_INV_SUMMARY(INVOICE_HEADER_NO, SUMMARY_TYPE);
CREATE INDEX BMTB_DRAFT_INV_DETAIL_N6 ON BMTB_DRAFT_INV_DETAIL(subscription_fee, card_replacement);
CREATE INDEX BMTB_DRAFT_INV_SUMMARY_N5 ON BMTB_DRAFT_INV_SUMMARY(SUMMARY_TYPE);
CREATE INDEX BMTB_DRAFT_INV_SUMMARY_N6 ON BMTB_DRAFT_INV_SUMMARY(NEW_TXN, ADMIN_FEE, GST, TOTAL_NEW);
CREATE INDEX BMTB_DRAFT_INV_SUMMARY_N7 ON BMTB_DRAFT_INV_SUMMARY(PREV_BALANCE, PREV_PAYMENT, NEW_TXN, ADMIN_FEE, GST, TOTAL_NEW, BALANCE);

Insert into BMTB_BILL_GEN_SETUP (SETUP_NO,NAME,CUT_OFF_DAY,BILL_GEN_DAY,BILL_GEN_TIME,INVOICE_DAY,CREATED_BY,CREATED_DT,UPDATED_BY,UPDATED_DT,VERSION) values (5,'DRAFT',null,null,null,null,'SYSTEM',to_timestamp('11-MAR-09 12.00.00.000000000 AM','DD-MON-RR HH.MI.SS.FF AM'),null,null,0);

INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (536, '29', 'Search Draft Invoice', 'U', '/billing/invoice/search_draft_invoice.zul', '12', 'View Draft Invoice', 'Y', '0');

ALTER TABLE "BMTB_PAYMENT_RECEIPT"
ADD (
    CANCEL_BILLED_FLAG VARCHAR2(1) DEFAULT 'N' NOT NULL
);
Insert into SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) values (423,412,'Cashless Transaction Trip Analysis','U','/report/report_input.zul?report=Cashless Transaction Trip Analysis',1,'Cashless Transaction Trip Analysis','N',0);
