--Seng Tat
ALTER TABLE BMTB_INVOICE_HEADER
ADD (
  BILLED_FLAG VARCHAR2(1)
);

ALTER TABLE BMTB_PAYMENT_RECEIPT_DETAIL
ADD (
  BILLED_FLAG VARCHAR2(1) NOT NULL;
);
--END

--Rodney
ALTER TABLE TMTB_ACQUIRE_TXN
ADD (
  NOTE_NO NUMBER(18)
);

ALTER TABLE TMTB_ACQUIRE_TXN ADD CONSTRAINT TMTB_ACQUIRE_TXN_FK7 FOREIGN KEY ("NOTE_NO") REFERENCES BMTB_NOTE ("NOTE_NO") ENABLE;
CREATE INDEX TMTB_ACQUIRE_TXN_N7 ON TMTB_ACQUIRE_TXN (NOTE_NO);

alter table TMTB_ACQUIRE_TXN rename column PYMT_AMT to BILLABLE_AMT

ALTER TABLE TMTB_ACQUIRE_TXN 
MODIFY ("TXN_STATUS" VARCHAR2(2 BYTE))
;
--END