CREATE INDEX TMTB_ACQUIRE_TXN_N11 ON TMTB_ACQUIRE_TXN (JOB_NO);
CREATE INDEX TMTB_TXN_REVIEW_REQ_FLOW_N4 ON TMTB_TXN_REVIEW_REQ_FLOW (TO_STATUS);
CREATE INDEX ITTB_FMS_DRVR_RFND_COL_REQ_N1 ON ITTB_FMS_DRVR_RFND_COL_REQ (JOB_NO);
CREATE INDEX BMTB_INVOICE_TXN_N3 ON BMTB_INVOICE_TXN (ACQUIRE_TXN_NO);