--SEPARATING THE INVOICE FILE BLOB FROM THE INVOICE HEADER INTO A INDIVIDUAL TABLE ITSELF FOR PERFORMANCE
alter table bmtb_invoice_header drop column invoice_file;
alter table bmtb_invoice_header add (
  file_no number(18)
);

CREATE TABLE BMTB_INVOICE_FILE
(
  FILE_NO NUMBER(18) NOT NULL,
  INVOICE_FILE BLOB,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP,
  VERSION NUMBER(9) DEFAULT 0
)
;

ALTER TABLE BMTB_INVOICE_FILE ADD CONSTRAINT BMTB_INVOICE_FILE_PK PRIMARY KEY (FILE_NO) ENABLE;
ALTER TABLE BMTB_INVOICE_HEADER ADD CONSTRAINT BMTB_INVOICE_HEADER_FK4 FOREIGN KEY(FILE_NO) REFERENCES BMTB_INVOICE_FILE(FILE_NO) ENABLE;
ALTER TABLE BMTB_INVOICE_HEADER ADD CONSTRAINT BMTB_INVOICE_HEADER_U1 UNIQUE(FILE_NO) ENABLE;

CREATE INDEX "BMTB_INVOICE_HEADER_N4" ON BMTB_INVOICE_HEADER(FILE_NO);

CREATE SEQUENCE  "BMTB_INVOICE_FILE_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
--END