ALTER TABLE TMTB_TXN_REVIEW_REQ ADD BOOK_DATE_TIME TIMESTAMP;
ALTER TABLE TMTB_ACQUIRE_TXN ADD FLIGHT_INFO VARCHAR2(20);
ALTER TABLE TMTB_TXN_REVIEW_REQ ADD FLIGHT_INFO VARCHAR2(20);
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,MASTER_VALUE,MASTER_STATUS,VERSION,INTERFACE_MAPPING_VALUE) values (80,'MQR','200','200','A',0,null);
ALTER TABLE PMTB_PRODUCT ADD "IS_INDIVIDUAL_CARD" VARCHAR2(1);

--MODIFYING THE PAYMENT RECEIPT BANK IN TO BE LINKED WITH FMTB_BANK_CODE AND NOT MSTB_BANK_MASTER
alter table bmtb_payment_receipt drop column BRANCH_IN;
alter table bmtb_payment_receipt drop CONSTRAINT BMTB_PAYMENT_RECEIPT_FK5;
ALTER TABLE BMTB_PAYMENT_RECEIPT ADD CONSTRAINT BMTB_PAYMENT_RECEIPT_FK5 FOREIGN KEY(BANK_IN) REFERENCES FMTB_BANK_CODE(BANK_CODE_NO) ENABLE;