--SENGTAT: DEPOSIT REFUND
ALTER TABLE "BMTB_INVOICE_DEPOSIT_TXN"
ADD (
    PAYMENT_RECEIPT_NO NUMBER(18,0),
	CONSTRAINT "BMTB_INVOICE_DEPOSIT_TXN_FK4" FOREIGN KEY ("PAYMENT_RECEIPT_NO")
	  REFERENCES "BMTB_PAYMENT_RECEIPT" ("PAYMENT_RECEIPT_NO") ENABLE
);
CREATE INDEX "BMTB_INVOICE_DEPOSIT_TXN_N4" ON BMTB_DEPOSIT_TXN(PAYMENT_RECEIPT_NO);
--END

--REPORT RESOURCES
Insert into SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) values (406,401,'Receipt','U','Receipt',4,'Receipt','N',0);
Insert into SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) values (407,406,'Receipt By Period Detailed','U','/report/report_input.zul?report=Receipt By Period Detailed',1,'Receipt By Period Detailed','N',0);

--SENGTAT: Refund Excess Amount
Insert into SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) values (109,38,'Refund Excess Amount Payment Receipt','U','/billing/payment/refund_excess_amount_payment_receipt.zul',7,'Refund Excess Amount Payment Receipt','N',0);

--SENGTAT: REFUND OVERPAYMENT
ALTER TABLE BMTB_PAYMENT_RECEIPT
ADD (
    MEMO_RECEIPT_NO NUMBER(18,0),
	CONSTRAINT "BMTB_PAYMENT_RECEIPT_FK8" FOREIGN KEY ("MEMO_RECEIPT_NO")
	  REFERENCES "BMTB_PAYMENT_RECEIPT" ("PAYMENT_RECEIPT_NO") ENABLE
);
--END

--SENGTAT: PROJECT CODE
ALTER TABLE BMTB_INVOICE_TXN
ADD (
    PROJECT_CODE VARCHAR2(80)
);
--END