--SENGTAT: NO LONGER NEEDED TO KEEP NAME AND ADDRESS IN TABLES
ALTER TABLE BMTB_INVOICE_DETAIL DROP COLUMN ACCOUNT_NAME;
ALTER TABLE BMTB_INVOICE_DETAIL DROP COLUMN ACCOUNT_CODE;
ALTER TABLE BMTB_INVOICE_SUMMARY DROP COLUMN SUMMARY_GROUP;
ALTER TABLE BMTB_INVOICE_SUMMARY DROP COLUMN SUMMARY_GROUP_NAME;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN CUSTOMER_NAME;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ADDRESS_BLOCK;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ADDRESS_STREET;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ADDRESS_UNIT;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ADDRESS_BUILDING;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ADDRESS_AREA;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ADDRESS_COUNTRY;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ADDRESS_POSTAL;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ADDRESS_CITY;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ADDRESS_STATE;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN BILLING_CONTACT_PERSON_NAME;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN CUSTOMER_ID;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ENTITY_NAME;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ENTITY_BLOCK;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ENTITY_UNIT;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ENTITY_STREET;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ENTITY_BUILDING;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ENTITY_AREA;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ENTITY_COUNTRY;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ENTITY_POSTAL;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ENTITY_CITY;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ENTITY_STATE;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ENTITY_GST_NO;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ENTITY_RCB_NO;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ENTITY_TEL;
ALTER TABLE BMTB_INVOICE_HEADER DROP COLUMN ENTITY_EMAIL;
--END
-- for embossing of renewed cards
alter table PMTB_PRODUCT_RENEW add EMBOSS_FLAG VARCHAR2(1);
-- for subscription history
CREATE SEQUENCE  "AMTB_SUBSC_TO_HIST_SQ1"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 2 CACHE 10 NOORDER  NOCYCLE ;
-- ACCOUNT SUBSCRIBED TO HISTORY TABLE --
CREATE TABLE AMTB_SUBSC_TO_HIST (
	SUBSC_TO_HIST_NO NUMBER(8) NOT NULL,
	ACCOUNT_NO NUMBER(8) NOT NULL,
	PRODUCT_TYPE_ID VARCHAR2(2) NOT NULL,
	PRODUCT_DISCOUNT_PLAN_NO NUMBER(8),
	REWARD_PLAN_NO NUMBER(8),
	SUBSCRIPTION_FEE_NO NUMBER(8),
	EFF_DT_FROM TIMESTAMP NOT NULL,
	EFF_DT_TO TIMESTAMP,
	VERSION NUMBER(9,0) DEFAULT 0,
	CONSTRAINT AMTB_SUBSC_TO_HIST_PK PRIMARY KEY(SUBSC_TO_HIST_NO),
	CONSTRAINT AMTB_SUBSC_TO_HIST_FK1 FOREIGN KEY(ACCOUNT_NO) REFERENCES AMTB_ACCOUNT(ACCOUNT_NO),
	CONSTRAINT AMTB_SUBSC_TO_HIST_FK2 FOREIGN KEY(PRODUCT_TYPE_ID) REFERENCES PMTB_PRODUCT_TYPE(PRODUCT_TYPE_ID),
	CONSTRAINT AMTB_SUBSC_TO_HIST_FK3 FOREIGN KEY(REWARD_PLAN_NO) REFERENCES LRTB_REWARD_MASTER(REWARD_PLAN_NO),
	CONSTRAINT AMTB_SUBSC_TO_HIST_FK4 FOREIGN KEY(SUBSCRIPTION_FEE_NO) REFERENCES MSTB_SUBSC_FEE_MASTER(SUBSCRIPTION_FEE_NO),
	CONSTRAINT AMTB_SUBSC_TO_HIST_FK5 FOREIGN KEY(PRODUCT_DISCOUNT_PLAN_NO) REFERENCES MSTB_PROD_DISC_MASTER(PRODUCT_DISCOUNT_PLAN_NO)
);
-- CREATING COMMENTS
-- creating indexes --
CREATE INDEX AMTB_SUBSC_HIST_TO_N1 ON AMTB_SUBSC_TO_HIST (ACCOUNT_NO);
CREATE INDEX AMTB_SUBSC_HIST_TO_N2 ON AMTB_SUBSC_TO_HIST (PRODUCT_TYPE_ID);
CREATE INDEX AMTB_SUBSC_HIST_TO_N3 ON AMTB_SUBSC_TO_HIST (REWARD_PLAN_NO);
CREATE INDEX AMTB_SUBSC_HIST_TO_N4 ON AMTB_SUBSC_TO_HIST (SUBSCRIPTION_FEE_NO);
CREATE INDEX AMTB_SUBSC_HIST_TO_N5 ON AMTB_SUBSC_TO_HIST (PRODUCT_DISCOUNT_PLAN_NO);