--SENGTAT: Misc Invoice does not need to populate the following, so they can be null
ALTER TABLE BMTB_INVOICE_HEADER 
MODIFY ("STATEMENT_PERIOD_FROM_DATE" NULL)
;

ALTER TABLE BMTB_INVOICE_HEADER 
MODIFY ("STATEMENT_PERIOD_TO_DATE" NULL)
;

ALTER TABLE BMTB_INVOICE_HEADER 
MODIFY ("TXN_CUTOFF_DATE" NULL)
;
--END