ALTER TABLE ITTB_TRIPS_TXN
ADD (
  FLIGHT_DETAILS varchar2(20),
  AGENT_NAME varchar2(80)
);
ALTER TABLE ITTB_TRIPS_TXN_ERROR
ADD (
  FLIGHT_DETAILS varchar2(20),
  AGENT_NAME varchar2(80)
);