Insert into SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) values (108,401,'Product Embossing','U','/report/product_embossing.zul',2,'Generate Embossing','Y',0);
Insert into SATB_ROLE_RESOURCE (ROLE_ID,RSRC_ID) values (2,108);
ALTER TABLE PMTB_PRODUCT ADD "EMBOSS_FLAG" VARCHAR2(1);
ALTER TABLE PMTB_PRODUCT_REPLACEMENT ADD "EMBOSS_FLAG" VARCHAR2(1);