CREATE SEQUENCE  "ITTB_TRIPS_TXN_REQ_SQ1"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
CREATE TABLE ITTB_TRIPS_TXN_REQ
(
  REQ_NO NUMBER(18) NOT NULL,
  STATUS VARCHAR2(1) NOT NULL,
  REQUEST_DATE DATE NOT NULL,
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP,
  VERSION NUMBER(9) DEFAULT 0
);
ALTER TABLE "ITTB_TRIPS_TXN_REQ" ADD CONSTRAINT "ITTB_TRIPS_TXN_REQ_PK" PRIMARY KEY ("REQ_NO") ENABLE;

INSERT INTO SATB_RESOURCE (RSRC_ID, PAR_RSRC_ID, RSRC_NAME, RSRC_TYPE, URI, SEQUENCE, DISPLAY_NAME, DISPLAY) VALUES ('902', '502', 'Process Trips', 'U', '/txn/process_txn.zul', '2', 'Process Trips', 'N');

CREATE INDEX PMTB_PRODUCT_N5 ON PMTB_PRODUCT (NAME_ON_PRODUCT);

