package com.cdgtaxi.ibs.interfaces.as.model;
// Generated Sep 17, 2009 6:06:33 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;


/**
 * AsvwProductType generated by hbm2java
 */

public class AsvwProductType  implements java.io.Serializable {


    // Fields    

    private String prodTypeId;
    private String prodName;
    private String binRange;
    private String subBinRange;
    private String oneTimeUsageFlg;
    private String fixedValueFlg;
    private String creditLimitFlg;
    private String negativeFileCheckFlg;
    private String expiryDateFlg;
    private String status;
    private Timestamp createDate;
    private String createBy;
    private Set<AsvwProduct> asvwProducts = new HashSet<AsvwProduct>(0);


    // Constructors

    /** default constructor */
    public AsvwProductType() {
    }

	/** minimal constructor */
    public AsvwProductType(String prodName, String oneTimeUsageFlg, String fixedValueFlg, String creditLimitFlg, String negativeFileCheckFlg, String expiryDateFlg, String status) {
        this.prodName = prodName;
        this.oneTimeUsageFlg = oneTimeUsageFlg;
        this.fixedValueFlg = fixedValueFlg;
        this.creditLimitFlg = creditLimitFlg;
        this.negativeFileCheckFlg = negativeFileCheckFlg;
        this.expiryDateFlg = expiryDateFlg;
        this.status = status;
    }
    
    /** full constructor */
    public AsvwProductType(String prodName, String binRange, String subBinRange, String oneTimeUsageFlg, String fixedValueFlg, String creditLimitFlg, String negativeFileCheckFlg, String expiryDateFlg, String status, Timestamp createDate, String createBy, Set<AsvwProduct> asvwProducts) {
        this.prodName = prodName;
        this.binRange = binRange;
        this.subBinRange = subBinRange;
        this.oneTimeUsageFlg = oneTimeUsageFlg;
        this.fixedValueFlg = fixedValueFlg;
        this.creditLimitFlg = creditLimitFlg;
        this.negativeFileCheckFlg = negativeFileCheckFlg;
        this.expiryDateFlg = expiryDateFlg;
        this.status = status;
        this.createDate = createDate;
        this.createBy = createBy;
        this.asvwProducts = asvwProducts;
    }
    

   
    // Property accessors

    public String getProdTypeId() {
        return this.prodTypeId;
    }
    
    public void setProdTypeId(String prodTypeId) {
        this.prodTypeId = prodTypeId;
    }

    public String getProdName() {
        return this.prodName;
    }
    
    public void setProdName(String prodName) {
        this.prodName = prodName;
    }

    public String getBinRange() {
        return this.binRange;
    }
    
    public void setBinRange(String binRange) {
        this.binRange = binRange;
    }

    public String getSubBinRange() {
        return this.subBinRange;
    }
    
    public void setSubBinRange(String subBinRange) {
        this.subBinRange = subBinRange;
    }

    public String getOneTimeUsageFlg() {
        return this.oneTimeUsageFlg;
    }
    
    public void setOneTimeUsageFlg(String oneTimeUsageFlg) {
        this.oneTimeUsageFlg = oneTimeUsageFlg;
    }

    public String getFixedValueFlg() {
        return this.fixedValueFlg;
    }
    
    public void setFixedValueFlg(String fixedValueFlg) {
        this.fixedValueFlg = fixedValueFlg;
    }

    public String getCreditLimitFlg() {
        return this.creditLimitFlg;
    }
    
    public void setCreditLimitFlg(String creditLimitFlg) {
        this.creditLimitFlg = creditLimitFlg;
    }

    public String getNegativeFileCheckFlg() {
        return this.negativeFileCheckFlg;
    }
    
    public void setNegativeFileCheckFlg(String negativeFileCheckFlg) {
        this.negativeFileCheckFlg = negativeFileCheckFlg;
    }

    public String getExpiryDateFlg() {
        return this.expiryDateFlg;
    }
    
    public void setExpiryDateFlg(String expiryDateFlg) {
        this.expiryDateFlg = expiryDateFlg;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public Timestamp getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public Set<AsvwProduct> getAsvwProducts() {
        return this.asvwProducts;
    }
    
    public void setAsvwProducts(Set<AsvwProduct> asvwProducts) {
        this.asvwProducts = asvwProducts;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("prodName").append("='").append(getProdName()).append("' ");			
      buffer.append("binRange").append("='").append(getBinRange()).append("' ");			
      buffer.append("subBinRange").append("='").append(getSubBinRange()).append("' ");			
      buffer.append("oneTimeUsageFlg").append("='").append(getOneTimeUsageFlg()).append("' ");			
      buffer.append("fixedValueFlg").append("='").append(getFixedValueFlg()).append("' ");			
      buffer.append("creditLimitFlg").append("='").append(getCreditLimitFlg()).append("' ");			
      buffer.append("negativeFileCheckFlg").append("='").append(getNegativeFileCheckFlg()).append("' ");			
      buffer.append("expiryDateFlg").append("='").append(getExpiryDateFlg()).append("' ");			
      buffer.append("status").append("='").append(getStatus()).append("' ");			
      buffer.append("createDate").append("='").append(getCreateDate()).append("' ");			
      buffer.append("createBy").append("='").append(getCreateBy()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AsvwProductType) ) return false;
		 AsvwProductType castOther = ( AsvwProductType ) other; 
         
		 return ( (this.getProdTypeId()==castOther.getProdTypeId()) || ( this.getProdTypeId()!=null && castOther.getProdTypeId()!=null && this.getProdTypeId().equals(castOther.getProdTypeId()) ) )
 && ( (this.getProdName()==castOther.getProdName()) || ( this.getProdName()!=null && castOther.getProdName()!=null && this.getProdName().equals(castOther.getProdName()) ) )
 && ( (this.getBinRange()==castOther.getBinRange()) || ( this.getBinRange()!=null && castOther.getBinRange()!=null && this.getBinRange().equals(castOther.getBinRange()) ) )
 && ( (this.getSubBinRange()==castOther.getSubBinRange()) || ( this.getSubBinRange()!=null && castOther.getSubBinRange()!=null && this.getSubBinRange().equals(castOther.getSubBinRange()) ) )
 && ( (this.getOneTimeUsageFlg()==castOther.getOneTimeUsageFlg()) || ( this.getOneTimeUsageFlg()!=null && castOther.getOneTimeUsageFlg()!=null && this.getOneTimeUsageFlg().equals(castOther.getOneTimeUsageFlg()) ) )
 && ( (this.getFixedValueFlg()==castOther.getFixedValueFlg()) || ( this.getFixedValueFlg()!=null && castOther.getFixedValueFlg()!=null && this.getFixedValueFlg().equals(castOther.getFixedValueFlg()) ) )
 && ( (this.getCreditLimitFlg()==castOther.getCreditLimitFlg()) || ( this.getCreditLimitFlg()!=null && castOther.getCreditLimitFlg()!=null && this.getCreditLimitFlg().equals(castOther.getCreditLimitFlg()) ) )
 && ( (this.getNegativeFileCheckFlg()==castOther.getNegativeFileCheckFlg()) || ( this.getNegativeFileCheckFlg()!=null && castOther.getNegativeFileCheckFlg()!=null && this.getNegativeFileCheckFlg().equals(castOther.getNegativeFileCheckFlg()) ) )
 && ( (this.getExpiryDateFlg()==castOther.getExpiryDateFlg()) || ( this.getExpiryDateFlg()!=null && castOther.getExpiryDateFlg()!=null && this.getExpiryDateFlg().equals(castOther.getExpiryDateFlg()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getCreateDate()==castOther.getCreateDate()) || ( this.getCreateDate()!=null && castOther.getCreateDate()!=null && this.getCreateDate().equals(castOther.getCreateDate()) ) )
 && ( (this.getCreateBy()==castOther.getCreateBy()) || ( this.getCreateBy()!=null && castOther.getCreateBy()!=null && this.getCreateBy().equals(castOther.getCreateBy()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProdTypeId() == null ? 0 : this.getProdTypeId().hashCode() );
         result = 37 * result + ( getProdName() == null ? 0 : this.getProdName().hashCode() );
         result = 37 * result + ( getBinRange() == null ? 0 : this.getBinRange().hashCode() );
         result = 37 * result + ( getSubBinRange() == null ? 0 : this.getSubBinRange().hashCode() );
         result = 37 * result + ( getOneTimeUsageFlg() == null ? 0 : this.getOneTimeUsageFlg().hashCode() );
         result = 37 * result + ( getFixedValueFlg() == null ? 0 : this.getFixedValueFlg().hashCode() );
         result = 37 * result + ( getCreditLimitFlg() == null ? 0 : this.getCreditLimitFlg().hashCode() );
         result = 37 * result + ( getNegativeFileCheckFlg() == null ? 0 : this.getNegativeFileCheckFlg().hashCode() );
         result = 37 * result + ( getExpiryDateFlg() == null ? 0 : this.getExpiryDateFlg().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getCreateDate() == null ? 0 : this.getCreateDate().hashCode() );
         result = 37 * result + ( getCreateBy() == null ? 0 : this.getCreateBy().hashCode() );
         
         return result;
   }   





}
