--FMS Column Update
alter table ITTB_FMS_DRVR_RFND_COL_REQ drop column EVENT_TYPE;
alter table ITTB_FMS_DRVR_RFND_COL_REQ rename column SERVICE_PROVIDER to SERVICE_TYPE;
alter table ITTB_FMS_DRVR_RFND_COL_REQ rename column PAYMENT_AMT to REFUND_AMT;

--REPORT RESOURCE
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (446,440,'Inventory Movement Report Summary','U','/report/inventory_movement_report_summary.zul?rsrcId=446',15,'Inventory Movement Report Summary','Y',0);
insert into MSTB_REPORT_FORMAT_MAP (map_no, rsrc_id, report_format) values ((select max(map_no)+1 from MSTB_REPORT_FORMAT_MAP), 446, 'PDF');

CREATE SEQUENCE LRTB_GIFT_CATEGORY_SQ1 MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER NOCYCLE ; 
CREATE SEQUENCE LRTB_GIFT_STOCK_SQ1 MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER NOCYCLE; 
CREATE SEQUENCE LRTB_GIFT_ITEM_SQ1 MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER NOCYCLE; 
