ALTER TABLE ITTB_FMS_DRVR_RFND_COL_REQ ADD "FARE_AMT" NUMBER(12,2);
ALTER TABLE AMTB_ACCOUNT ADD "E_INVOICE_FLAG" VARCHAR(1);

--Resources for Rewards, Loyalty Plan and Inventory
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (514,0,'Loyalty & Rewards','U','Rewards',11,'Loyalty & Rewards','Y',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (515,514,'List Loyalty Plans','U','/rewards/list_plan.zul',1,'Manage Loyalty Plans','Y',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (516,514,'List Gifts','U','/rewards/list_category.zul',2,'Manage Gifts','Y',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (517,514,'Search Item','U','/rewards/search_item.zul',3,'Redeem Gift','Y',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (518,514,'Search History','U','/rewards/view_redemption_history.zul',4,'Rewards History','Y',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (519,514,'Add Gift Item','U','/rewards/add_item.zul',5,'Add Gift Item','N',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (520,514,'Add Loyalty Plan Detail','U','/rewards/add_plan_detail.zul',6,'Add Loyalty Plan Detail','N',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (521,514,'Create Gift Category','U','/rewards/create_category.zul',7,'Create Gift Category','N',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (522,514,'Create Loyalty Plan','U','/rewards/create_plan.zul',8,'Create Loyalty Plan','N',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (523,514,'Edit Gift Item','U','/rewards/edit_item.zul',9,'Edit Gift Item','N',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (524,514,'Edit Loyalty Plan Detail','U','/rewards/edit_plan_detail.zul',10,'Edit Loyalty Plan Detail','N',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (525,514,'Move Gift Item','U','/rewards/move_item.zul',11,'Move Gift Item','N',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (526,514,'Stockup Gift Item','U','/rewards/stockup_item.zul',12,'Stockup Gift Item','N',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (527,514,'View Gift Category','U','/rewards/view_category.zul',13,'View Gift Category','N',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (528,514,'View Loyalty Plan','U','/rewards/view_plan.zul',14,'View Loyalty Plan','N',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (529,514,'Manage Inventory','U','/inventory/list_item_type.zul',6,'Manage Inventory','Y',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (530,529,'Create Inventory Type','U','/inventory/create_item_type.zul',2,'Create Inventory Type','N',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (531,529,'Add Stock','U','/inventory/add_stock.zul',3,'Add Stock','N',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (532,529,'View Item Type','U','/inventory/view_item_type.zul',4,'View Item Type','N',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (533,529,'Request Issuance','U','/inventory/request_issuance.zul',5,'Request Issuance','N',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (534,529,'View Request','U','/inventory/view_request.zul',5,'View Request','N',0);
INSERT INTO "IBS_USR_P2"."SATB_RESOURCE" (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (535,529,'View Issuance','U','/inventory/view_issuance.zul',5,'View Issuance','N',0);

--missing sequence
create SEQUENCE IMTB_ITEM_TYPE_SQ1 MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
create SEQUENCE IMTB_STOCK_SQ1 MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
create SEQUENCE IMTB_ISSUE_SQ1 MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
create SEQUENCE IMTB_ISSUE_REQ_SQ1 MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
create SEQUENCE IMTB_ISSUE_REQ_FLOW_SQ1 MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ; 
create SEQUENCE IMTB_ITEM_SQ1 MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;