/* **********************
 * PROMOTION FOR BILL GEN
 * **********************/
alter table bmtb_draft_inv_txn add(
	DEDUCTED_PROMO_DIS_VALUE number(10,2) DEFAULT 0 NOT NULL
);

alter table bmtb_invoice_txn add(
	DEDUCTED_PROMO_DIS_VALUE number(10,2) DEFAULT 0 NOT NULL
);

alter table bmtb_invoice_detail add(
	DEDUCTED_PROMO_DIS number(10,2) DEFAULT 0 NOT NULL
);

alter table bmtb_draft_inv_detail add(
	DEDUCTED_PROMO_DIS number(10,2) DEFAULT 0 NOT NULL
);
ALTER TABLE AMTB_ACCT_PROMOTION_REQ ADD REQ_ACCT_PROMOTION_NO NUMBER(8);
ALTER TABLE AMTB_ACCT_PROMOTION_REQ ADD CONSTRAINT AMTB_ACCT_PROMOTION_REQ_FK3 FOREIGN KEY (REQ_ACCT_PROMOTION_NO) REFERENCES AMTB_ACCT_PROMOTION(ACCT_PROMOTION_NO);

-- sequence for ACCOUNT PROMOTION --
CREATE SEQUENCE "AMTB_ACCT_PROMOTION_SQ1" MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER NOCYCLE ;
-- ACCOUNT PROMOTION TABLE --
CREATE TABLE AMTB_ACCT_PROMOTION(
	ACCT_PROMOTION_NO NUMBER(8) NOT NULL,
	ACCOUNT_NO NUMBER(8) NOT NULL,
	PROMO_NO NUMBER(8),
	EFFECTIVE_DATE_FROM DATE NOT NULL,
    EFFECTIVE_DATE_TO DATE,
	VERSION NUMBER(9,0) DEFAULT 0,
	CONSTRAINT AMTB_ACCT_PROMOTION_PK PRIMARY KEY(ACCT_PROMOTION_NO),
	CONSTRAINT AMTB_ACCT_PROMOTION_FK1 FOREIGN KEY(ACCOUNT_NO) REFERENCES AMTB_ACCOUNT(ACCOUNT_NO),
	CONSTRAINT AMTB_ACCT_PROMOTION_FK2 FOREIGN KEY(PROMO_NO) REFERENCES MSTB_PROMOTION(PROMO_NO)
);
-- creating indexes --
CREATE INDEX AMTB_ACCT_PROMOTION_N1 ON AMTB_ACCT_PROMOTION(ACCOUNT_NO);
CREATE INDEX AMTB_ACCT_PROMOTION_N2 ON AMTB_ACCT_PROMOTION(PROMO_NO);
CREATE INDEX AMTB_ACCT_PROMOTION_N3 ON AMTB_ACCT_PROMOTION(EFFECTIVE_DATE_FROM);
CREATE INDEX AMTB_ACCT_PROMOTION_N4 ON AMTB_ACCT_PROMOTION(EFFECTIVE_DATE_TO);
-- sequence for ACCOUNT CREDIT TERM REQUEST --
CREATE SEQUENCE "AMTB_ACCT_PROMOTION_REQ_SQ1" MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER NOCYCLE ;
-- ACCOUNT CREDIT TERM REQUEST TABLE --
CREATE TABLE AMTB_ACCT_PROMOTION_REQ (
	ACCT_PROMOTION_REQ_NO NUMBER(8) NOT NULL,
	REQ_ACCT_PROMOTION_NO NUMBER(8),
	BILL_REQ_NO NUMBER(8) NOT NULL,
	PROMO_NO NUMBER(8) NOT NULL,
	EVENT VARCHAR2(1), -- C = CREATE, U = UPDATE, D = DELETE
	EFFECTIVE_DT_FROM TIMESTAMP NOT NULL,
	EFFECTIVE_DT_TO TIMESTAMP,
    VERSION NUMBER(9,0) DEFAULT 0,
	CONSTRAINT AMTB_ACCT_PROMOTION_REQ_PK PRIMARY KEY(ACCT_PROMOTION_REQ_NO),
	CONSTRAINT AMTB_ACCT_PROMOTION_REQ_FK1 FOREIGN KEY(BILL_REQ_NO) REFERENCES AMTB_BILL_REQ(BILL_REQ_NO),
	CONSTRAINT AMTB_ACCT_PROMOTION_REQ_FK2 FOREIGN KEY(PROMO_NO) REFERENCES MSTB_PROMOTION(PROMO_NO),
	CONSTRAINT AMTB_ACCT_PROMOTION_REQ_FK3 FOREIGN KEY(REQ_ACCT_PROMOTION_NO) REFERENCES AMTB_ACCT_PROMOTION(ACCT_PROMOTION_NO)
);
-- creating indexes --
CREATE INDEX AMTB_ACCT_PROMOTION_REQ_N1 ON AMTB_ACCT_PROMOTION_REQ (BILL_REQ_NO);
CREATE INDEX AMTB_ACCT_PROMOTION_REQ_N2 ON AMTB_ACCT_PROMOTION_REQ (PROMO_NO);
	