package com.cdgtaxi.ibs.master.model;
// Generated Jul 21, 2009 1:20:20 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.common.model.Creatable;
import com.cdgtaxi.ibs.common.model.Updatable;


/**
 * LrtbRewardDetail generated by hbm2java
 */

public class LrtbRewardDetail  implements java.io.Serializable, Auditable, Creatable, Updatable{


    // Fields    

    private Integer rewardPlanDetailNo;
    private String rewardType;
    private Timestamp effectiveDtFrom;
    private Timestamp effectiveDtTo;
    private Integer version;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private LrtbRewardMaster lrtbRewardMaster;
    private Set<LrtbRewardTier> lrtbRewardTiers = new HashSet<LrtbRewardTier>(0);


    // Constructors

    /** default constructor */
    public LrtbRewardDetail() {
    }

	/** minimal constructor */
    public LrtbRewardDetail(String rewardType, Timestamp effectiveDtFrom, Timestamp effectiveDtTo) {
        this.rewardType = rewardType;
        this.effectiveDtFrom = effectiveDtFrom;
        this.effectiveDtTo = effectiveDtTo;
    }
    
    /** full constructor */
    public LrtbRewardDetail(String rewardType, Timestamp effectiveDtFrom, Timestamp effectiveDtTo, Integer version, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, LrtbRewardMaster lrtbRewardMaster, Set<LrtbRewardTier> lrtbRewardTiers) {
        this.rewardType = rewardType;
        this.effectiveDtFrom = effectiveDtFrom;
        this.effectiveDtTo = effectiveDtTo;
        this.version = version;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.lrtbRewardMaster = lrtbRewardMaster;
        this.lrtbRewardTiers = lrtbRewardTiers;
    }
    

   
    // Property accessors

    public Integer getRewardPlanDetailNo() {
        return this.rewardPlanDetailNo;
    }
    
    public void setRewardPlanDetailNo(Integer rewardPlanDetailNo) {
        this.rewardPlanDetailNo = rewardPlanDetailNo;
    }

    public String getRewardType() {
        return this.rewardType;
    }
    
    public void setRewardType(String rewardType) {
        this.rewardType = rewardType;
    }

    public Timestamp getEffectiveDtFrom() {
        return this.effectiveDtFrom;
    }
    
    public void setEffectiveDtFrom(Timestamp effectiveDtFrom) {
        this.effectiveDtFrom = effectiveDtFrom;
    }

    public Timestamp getEffectiveDtTo() {
        return this.effectiveDtTo;
    }
    
    public void setEffectiveDtTo(Timestamp effectiveDtTo) {
        this.effectiveDtTo = effectiveDtTo;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public LrtbRewardMaster getLrtbRewardMaster() {
        return this.lrtbRewardMaster;
    }
    
    public void setLrtbRewardMaster(LrtbRewardMaster lrtbRewardMaster) {
        this.lrtbRewardMaster = lrtbRewardMaster;
    }

    public Set<LrtbRewardTier> getLrtbRewardTiers() {
        return this.lrtbRewardTiers;
    }
    
    public void setLrtbRewardTiers(Set<LrtbRewardTier> lrtbRewardTiers) {
        this.lrtbRewardTiers = lrtbRewardTiers;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("rewardType").append("='").append(getRewardType()).append("' ");			
      buffer.append("effectiveDtFrom").append("='").append(getEffectiveDtFrom()).append("' ");			
      buffer.append("effectiveDtTo").append("='").append(getEffectiveDtTo()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");		
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");	
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LrtbRewardDetail) ) return false;
		 LrtbRewardDetail castOther = ( LrtbRewardDetail ) other; 
         
		 return ( (this.getRewardPlanDetailNo()==castOther.getRewardPlanDetailNo()) || ( this.getRewardPlanDetailNo()!=null && castOther.getRewardPlanDetailNo()!=null && this.getRewardPlanDetailNo().equals(castOther.getRewardPlanDetailNo()) ) )
 && ( (this.getRewardType()==castOther.getRewardType()) || ( this.getRewardType()!=null && castOther.getRewardType()!=null && this.getRewardType().equals(castOther.getRewardType()) ) )
 && ( (this.getEffectiveDtFrom()==castOther.getEffectiveDtFrom()) || ( this.getEffectiveDtFrom()!=null && castOther.getEffectiveDtFrom()!=null && this.getEffectiveDtFrom().equals(castOther.getEffectiveDtFrom()) ) )
 && ( (this.getEffectiveDtTo()==castOther.getEffectiveDtTo()) || ( this.getEffectiveDtTo()!=null && castOther.getEffectiveDtTo()!=null && this.getEffectiveDtTo().equals(castOther.getEffectiveDtTo()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getLrtbRewardMaster()==castOther.getLrtbRewardMaster()) || ( this.getLrtbRewardMaster()!=null && castOther.getLrtbRewardMaster()!=null && this.getLrtbRewardMaster().equals(castOther.getLrtbRewardMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRewardPlanDetailNo() == null ? 0 : this.getRewardPlanDetailNo().hashCode() );
         result = 37 * result + ( getRewardType() == null ? 0 : this.getRewardType().hashCode() );
         result = 37 * result + ( getEffectiveDtFrom() == null ? 0 : this.getEffectiveDtFrom().hashCode() );
         result = 37 * result + ( getEffectiveDtTo() == null ? 0 : this.getEffectiveDtTo().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getLrtbRewardMaster() == null ? 0 : this.getLrtbRewardMaster().hashCode() );
         
         return result;
   }   

}
