package com.cdgtaxi.ibs.master.model;
// Generated Mar 27, 2009 6:34:10 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;


/**
 * LrtbRewardTier generated by hbm2java
 */

public class LrtbRewardTier  implements java.io.Serializable {


    // Fields    

    private Integer rewardPlanTierNo;
    private BigDecimal startRange;
    private BigDecimal endRange;
    private int ptsPerValue;
    private Integer version;
    private LrtbRewardDetail lrtbRewardDetail;


    // Constructors

    /** default constructor */
    public LrtbRewardTier() {
    }

	/** minimal constructor */
    public LrtbRewardTier(BigDecimal startRange, BigDecimal endRange, int ptsPerValue) {
        this.startRange = startRange;
        this.endRange = endRange;
        this.ptsPerValue = ptsPerValue;
    }
    
    /** full constructor */
    public LrtbRewardTier(BigDecimal startRange, BigDecimal endRange, int ptsPerValue, Integer version, LrtbRewardDetail lrtbRewardDetail) {
        this.startRange = startRange;
        this.endRange = endRange;
        this.ptsPerValue = ptsPerValue;
        this.version = version;
        this.lrtbRewardDetail = lrtbRewardDetail;
    }
    

   
    // Property accessors

    public Integer getRewardPlanTierNo() {
        return this.rewardPlanTierNo;
    }
    
    public void setRewardPlanTierNo(Integer rewardPlanTierNo) {
        this.rewardPlanTierNo = rewardPlanTierNo;
    }

    public BigDecimal getStartRange() {
        return this.startRange;
    }
    
    public void setStartRange(BigDecimal startRange) {
        this.startRange = startRange;
    }

    public BigDecimal getEndRange() {
        return this.endRange;
    }
    
    public void setEndRange(BigDecimal endRange) {
        this.endRange = endRange;
    }

    public int getPtsPerValue() {
        return this.ptsPerValue;
    }
    
    public void setPtsPerValue(int ptsPerValue) {
        this.ptsPerValue = ptsPerValue;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public LrtbRewardDetail getLrtbRewardDetail() {
        return this.lrtbRewardDetail;
    }
    
    public void setLrtbRewardDetail(LrtbRewardDetail lrtbRewardDetail) {
        this.lrtbRewardDetail = lrtbRewardDetail;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("startRange").append("='").append(getStartRange()).append("' ");			
      buffer.append("endRange").append("='").append(getEndRange()).append("' ");			
      buffer.append("ptsPerValue").append("='").append(getPtsPerValue()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LrtbRewardTier) ) return false;
		 LrtbRewardTier castOther = ( LrtbRewardTier ) other; 
         
		 return ( (this.getRewardPlanTierNo()==castOther.getRewardPlanTierNo()) || ( this.getRewardPlanTierNo()!=null && castOther.getRewardPlanTierNo()!=null && this.getRewardPlanTierNo().equals(castOther.getRewardPlanTierNo()) ) )
 && ( (this.getStartRange()==castOther.getStartRange()) || ( this.getStartRange()!=null && castOther.getStartRange()!=null && this.getStartRange().equals(castOther.getStartRange()) ) )
 && ( (this.getEndRange()==castOther.getEndRange()) || ( this.getEndRange()!=null && castOther.getEndRange()!=null && this.getEndRange().equals(castOther.getEndRange()) ) )
 && (this.getPtsPerValue()==castOther.getPtsPerValue())
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getLrtbRewardDetail()==castOther.getLrtbRewardDetail()) || ( this.getLrtbRewardDetail()!=null && castOther.getLrtbRewardDetail()!=null && this.getLrtbRewardDetail().equals(castOther.getLrtbRewardDetail()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRewardPlanTierNo() == null ? 0 : this.getRewardPlanTierNo().hashCode() );
         result = 37 * result + ( getStartRange() == null ? 0 : this.getStartRange().hashCode() );
         result = 37 * result + ( getEndRange() == null ? 0 : this.getEndRange().hashCode() );
         result = 37 * result + this.getPtsPerValue();
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getLrtbRewardDetail() == null ? 0 : this.getLrtbRewardDetail().hashCode() );
         return result;
   }   





}
