package com.cdgtaxi.ibs.master.model;
// Generated Mar 27, 2009 6:21:35 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Timestamp;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.common.model.Creatable;
import com.cdgtaxi.ibs.common.model.Updatable;


/**
 * MstbLatePaymentDetail generated by hbm2java
 */

public class MstbLatePaymentDetail  implements java.io.Serializable, Creatable, Updatable, Auditable {


    // Fields    

    private Integer latePaymentPlanDetailNo;
    private Timestamp effectiveDt;
    private BigDecimal latePayment;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private Integer version;
    private MstbLatePaymentMaster mstbLatePaymentMaster;


    // Constructors

    /** default constructor */
    public MstbLatePaymentDetail() {
    }

	/** minimal constructor */
    public MstbLatePaymentDetail(Timestamp effectiveDt, BigDecimal latePayment) {
        this.effectiveDt = effectiveDt;
        this.latePayment = latePayment;
    }
    
    /** full constructor */
    public MstbLatePaymentDetail(Timestamp effectiveDt, BigDecimal latePayment, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, Integer version, MstbLatePaymentMaster mstbLatePaymentMaster) {
        this.effectiveDt = effectiveDt;
        this.latePayment = latePayment;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.version = version;
        this.mstbLatePaymentMaster = mstbLatePaymentMaster;
    }
    

   
    // Property accessors

    public Integer getLatePaymentPlanDetailNo() {
        return this.latePaymentPlanDetailNo;
    }
    
    public void setLatePaymentPlanDetailNo(Integer latePaymentPlanDetailNo) {
        this.latePaymentPlanDetailNo = latePaymentPlanDetailNo;
    }

    public Timestamp getEffectiveDt() {
        return this.effectiveDt;
    }
    
    public void setEffectiveDt(Timestamp effectiveDt) {
        this.effectiveDt = effectiveDt;
    }

    public BigDecimal getLatePayment() {
        return this.latePayment;
    }
    
    public void setLatePayment(BigDecimal latePayment) {
        this.latePayment = latePayment;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public MstbLatePaymentMaster getMstbLatePaymentMaster() {
        return this.mstbLatePaymentMaster;
    }
    
    public void setMstbLatePaymentMaster(MstbLatePaymentMaster mstbLatePaymentMaster) {
        this.mstbLatePaymentMaster = mstbLatePaymentMaster;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("effectiveDt").append("='").append(getEffectiveDt()).append("' ");			
      buffer.append("latePayment").append("='").append(getLatePayment()).append("' ");		
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstbLatePaymentDetail) ) return false;
		 MstbLatePaymentDetail castOther = ( MstbLatePaymentDetail ) other; 
         
		 return ( (this.getLatePaymentPlanDetailNo()==castOther.getLatePaymentPlanDetailNo()) || ( this.getLatePaymentPlanDetailNo()!=null && castOther.getLatePaymentPlanDetailNo()!=null && this.getLatePaymentPlanDetailNo().equals(castOther.getLatePaymentPlanDetailNo()) ) )
 && ( (this.getEffectiveDt()==castOther.getEffectiveDt()) || ( this.getEffectiveDt()!=null && castOther.getEffectiveDt()!=null && this.getEffectiveDt().equals(castOther.getEffectiveDt()) ) )
 && ( (this.getLatePayment()==castOther.getLatePayment()) || ( this.getLatePayment()!=null && castOther.getLatePayment()!=null && this.getLatePayment().equals(castOther.getLatePayment()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getMstbLatePaymentMaster()==castOther.getMstbLatePaymentMaster()) || ( this.getMstbLatePaymentMaster()!=null && castOther.getMstbLatePaymentMaster()!=null && this.getMstbLatePaymentMaster().equals(castOther.getMstbLatePaymentMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getLatePaymentPlanDetailNo() == null ? 0 : this.getLatePaymentPlanDetailNo().hashCode() );
         result = 37 * result + ( getEffectiveDt() == null ? 0 : this.getEffectiveDt().hashCode() );
         result = 37 * result + ( getLatePayment() == null ? 0 : this.getLatePayment().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getMstbLatePaymentMaster() == null ? 0 : this.getMstbLatePaymentMaster().hashCode() );
         return result;
   }   

}
