package com.cdgtaxi.ibs.master.model;
// Generated Apr 8, 2009 2:34:00 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.common.model.AmtbAcctVolDisc;
import com.cdgtaxi.ibs.common.model.AmtbAcctVolDiscReq;
import com.cdgtaxi.ibs.common.model.AmtbApplication;
import com.cdgtaxi.ibs.common.model.Creatable;
import com.cdgtaxi.ibs.common.model.Updatable;


/**
 * MstbVolDiscMaster generated by hbm2java
 */

public class MstbVolDiscMaster  implements java.io.Serializable, Creatable, Updatable {


    // Fields    

    private Integer volumeDiscountPlanNo;
    private String volumeDiscountPlanName;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private Integer version;
    private Set<AmtbAcctVolDiscReq> amtbAcctVolDiscReqs = new HashSet<AmtbAcctVolDiscReq>(0);
    private Set<AmtbApplication> amtbApplications = new HashSet<AmtbApplication>(0);
    private Set<AmtbAcctVolDisc> amtbAcctVolDiscs = new HashSet<AmtbAcctVolDisc>(0);
    private Set<MstbVolDiscDetail> mstbVolDiscDetails = new HashSet<MstbVolDiscDetail>(0);


    // Constructors

    /** default constructor */
    public MstbVolDiscMaster() {
    }

	/** minimal constructor */
    public MstbVolDiscMaster(String volumeDiscountPlanName) {
        this.volumeDiscountPlanName = volumeDiscountPlanName;
    }
    
    /** full constructor */
    public MstbVolDiscMaster(String volumeDiscountPlanName, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, Integer version, Set<AmtbAcctVolDiscReq> amtbAcctVolDiscReqs, Set<AmtbApplication> amtbApplications, Set<AmtbAcctVolDisc> amtbAcctVolDiscs, Set<MstbVolDiscDetail> mstbVolDiscDetails) {
        this.volumeDiscountPlanName = volumeDiscountPlanName;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.version = version;
        this.amtbAcctVolDiscReqs = amtbAcctVolDiscReqs;
        this.amtbApplications = amtbApplications;
        this.amtbAcctVolDiscs = amtbAcctVolDiscs;
        this.mstbVolDiscDetails = mstbVolDiscDetails;
    }
    

   
    // Property accessors

    public Integer getVolumeDiscountPlanNo() {
        return this.volumeDiscountPlanNo;
    }
    
    public void setVolumeDiscountPlanNo(Integer volumeDiscountPlanNo) {
        this.volumeDiscountPlanNo = volumeDiscountPlanNo;
    }

    public String getVolumeDiscountPlanName() {
        return this.volumeDiscountPlanName;
    }
    
    public void setVolumeDiscountPlanName(String volumeDiscountPlanName) {
        this.volumeDiscountPlanName = volumeDiscountPlanName;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public Set<AmtbAcctVolDiscReq> getAmtbAcctVolDiscReqs() {
        return this.amtbAcctVolDiscReqs;
    }
    
    public void setAmtbAcctVolDiscReqs(Set<AmtbAcctVolDiscReq> amtbAcctVolDiscReqs) {
        this.amtbAcctVolDiscReqs = amtbAcctVolDiscReqs;
    }

    public Set<AmtbApplication> getAmtbApplications() {
        return this.amtbApplications;
    }
    
    public void setAmtbApplications(Set<AmtbApplication> amtbApplications) {
        this.amtbApplications = amtbApplications;
    }

    public Set<AmtbAcctVolDisc> getAmtbAcctVolDiscs() {
        return this.amtbAcctVolDiscs;
    }
    
    public void setAmtbAcctVolDiscs(Set<AmtbAcctVolDisc> amtbAcctVolDiscs) {
        this.amtbAcctVolDiscs = amtbAcctVolDiscs;
    }

    public Set<MstbVolDiscDetail> getMstbVolDiscDetails() {
        return this.mstbVolDiscDetails;
    }
    
    public void setMstbVolDiscDetails(Set<MstbVolDiscDetail> mstbVolDiscDetails) {
        this.mstbVolDiscDetails = mstbVolDiscDetails;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("volumeDiscountPlanName").append("='").append(getVolumeDiscountPlanName()).append("' ");
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstbVolDiscMaster) ) return false;
		 MstbVolDiscMaster castOther = ( MstbVolDiscMaster ) other; 
         
		 return ( (this.getVolumeDiscountPlanNo()==castOther.getVolumeDiscountPlanNo()) || ( this.getVolumeDiscountPlanNo()!=null && castOther.getVolumeDiscountPlanNo()!=null && this.getVolumeDiscountPlanNo().equals(castOther.getVolumeDiscountPlanNo()) ) )
 && ( (this.getVolumeDiscountPlanName()==castOther.getVolumeDiscountPlanName()) || ( this.getVolumeDiscountPlanName()!=null && castOther.getVolumeDiscountPlanName()!=null && this.getVolumeDiscountPlanName().equals(castOther.getVolumeDiscountPlanName()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getVolumeDiscountPlanNo() == null ? 0 : this.getVolumeDiscountPlanNo().hashCode() );
         result = 37 * result + ( getVolumeDiscountPlanName() == null ? 0 : this.getVolumeDiscountPlanName().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         return result;
   }   





}
