package com.cdgtaxi.ibs.master.model;
// Generated Mar 31, 2010 6:19:35 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.common.model.Creatable;
import com.cdgtaxi.ibs.common.model.TmtbNonBillableTxn;
import com.cdgtaxi.ibs.common.model.Updatable;


/**
 * MstbAcquirerPymtType generated by hbm2java
 */

public class MstbAcquirerPymtType  implements java.io.Serializable, Creatable, Updatable, Auditable{


    // Fields    

    private Integer pymtTypeNo;
    private Timestamp effectiveDtFrom;
    private Timestamp effectiveDtTo;
    private String remarks;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private Integer version;
    private MstbAcquirer mstbAcquirer;
    private Set<TmtbNonBillableTxn> tmtbNonBillableTxns = new HashSet<TmtbNonBillableTxn>(0);
    private Set<MstbAcquirerPymtComm> mstbAcquirerPymtComm = new HashSet<MstbAcquirerPymtComm>(0);
    private MstbMasterTable mstbMasterTable;


    // Constructors

    /** default constructor */
    public MstbAcquirerPymtType() {
    }

	/** minimal constructor */
    public MstbAcquirerPymtType(Timestamp effectiveDtFrom) {
        this.effectiveDtFrom = effectiveDtFrom;
    }
    
    /** full constructor */
    public MstbAcquirerPymtType(Timestamp effectiveDtFrom, Timestamp effectiveDtTo, String remarks, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, Integer version, MstbAcquirer mstbAcquirer, Set<TmtbNonBillableTxn> tmtbNonBillableTxns, MstbMasterTable mstbMasterTable, Set<MstbAcquirerPymtComm> mstbAcquirerPymtComm) {
        this.effectiveDtFrom = effectiveDtFrom;
        this.effectiveDtTo = effectiveDtTo;
        this.remarks = remarks;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.version = version;
        this.mstbAcquirer = mstbAcquirer;
        this.tmtbNonBillableTxns = tmtbNonBillableTxns;
        this.mstbAcquirerPymtComm = mstbAcquirerPymtComm;
        this.mstbMasterTable = mstbMasterTable;
    }
    

   
    // Property accessors

    public Integer getPymtTypeNo() {
        return this.pymtTypeNo;
    }
    
    public void setPymtTypeNo(Integer pymtTypeNo) {
        this.pymtTypeNo = pymtTypeNo;
    }

    public Timestamp getEffectiveDtFrom() {
        return this.effectiveDtFrom;
    }
    
    public void setEffectiveDtFrom(Timestamp effectiveDtFrom) {
        this.effectiveDtFrom = effectiveDtFrom;
    }

    public Timestamp getEffectiveDtTo() {
        return this.effectiveDtTo;
    }
    
    public void setEffectiveDtTo(Timestamp effectiveDtTo) {
        this.effectiveDtTo = effectiveDtTo;
    }

    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public MstbAcquirer getMstbAcquirer() {
        return this.mstbAcquirer;
    }
    
    public void setMstbAcquirer(MstbAcquirer mstbAcquirer) {
        this.mstbAcquirer = mstbAcquirer;
    }

    public Set<TmtbNonBillableTxn> getTmtbNonBillableTxns() {
        return this.tmtbNonBillableTxns;
    }
    
    public void setTmtbNonBillableTxns(Set<TmtbNonBillableTxn> tmtbNonBillableTxns) {
        this.tmtbNonBillableTxns = tmtbNonBillableTxns;
    }

    public Set<MstbAcquirerPymtComm> getMstbAcquirerPymtComm() {
		return mstbAcquirerPymtComm;
	}

	public void setMstbAcquirerPymtComm(Set<MstbAcquirerPymtComm> mstbAcquirerPymtComm) {
		this.mstbAcquirerPymtComm = mstbAcquirerPymtComm;
	}

	public MstbMasterTable getMstbMasterTable() {
        return this.mstbMasterTable;
    }
    
    public void setMstbMasterTable(MstbMasterTable mstbMasterTable) {
        this.mstbMasterTable = mstbMasterTable;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("effectiveDtFrom").append("='").append(getEffectiveDtFrom()).append("' ");			
      buffer.append("effectiveDtTo").append("='").append(getEffectiveDtTo()).append("' ");			
      buffer.append("remarks").append("='").append(getRemarks()).append("' ");			
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstbAcquirerPymtType) ) return false;
		 MstbAcquirerPymtType castOther = ( MstbAcquirerPymtType ) other; 
         
		 return ( (this.getPymtTypeNo()==castOther.getPymtTypeNo()) || ( this.getPymtTypeNo()!=null && castOther.getPymtTypeNo()!=null && this.getPymtTypeNo().equals(castOther.getPymtTypeNo()) ) )
 && ( (this.getEffectiveDtFrom()==castOther.getEffectiveDtFrom()) || ( this.getEffectiveDtFrom()!=null && castOther.getEffectiveDtFrom()!=null && this.getEffectiveDtFrom().equals(castOther.getEffectiveDtFrom()) ) )
 && ( (this.getEffectiveDtTo()==castOther.getEffectiveDtTo()) || ( this.getEffectiveDtTo()!=null && castOther.getEffectiveDtTo()!=null && this.getEffectiveDtTo().equals(castOther.getEffectiveDtTo()) ) )
 && ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getMstbAcquirer()==castOther.getMstbAcquirer()) || ( this.getMstbAcquirer()!=null && castOther.getMstbAcquirer()!=null && this.getMstbAcquirer().equals(castOther.getMstbAcquirer()) ) )
 && ( (this.getMstbMasterTable()==castOther.getMstbMasterTable()) || ( this.getMstbMasterTable()!=null && castOther.getMstbMasterTable()!=null && this.getMstbMasterTable().equals(castOther.getMstbMasterTable()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPymtTypeNo() == null ? 0 : this.getPymtTypeNo().hashCode() );
         result = 37 * result + ( getEffectiveDtFrom() == null ? 0 : this.getEffectiveDtFrom().hashCode() );
         result = 37 * result + ( getEffectiveDtTo() == null ? 0 : this.getEffectiveDtTo().hashCode() );
         result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         
         return result;
   }   

}
