package com.cdgtaxi.ibs.master.model;
// Generated Mar 27, 2009 6:21:33 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Timestamp;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.common.model.Creatable;
import com.cdgtaxi.ibs.common.model.Updatable;


/**
 * MstbVolDiscTier generated by hbm2java
 */

public class MstbVolDiscTier  implements java.io.Serializable, Creatable, Auditable, Updatable {


    // Fields    

    private Integer volumeDiscountPlanTierNo;
    private BigDecimal volumeDiscount;
    private BigDecimal startRange;
    private BigDecimal endRange;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private Integer version;
    private MstbVolDiscDetail mstbVolDiscDetail;


    // Constructors

    /** default constructor */
    public MstbVolDiscTier() {
    }

	/** minimal constructor */
    public MstbVolDiscTier(BigDecimal volumeDiscount, BigDecimal startRange, BigDecimal endRange) {
        this.volumeDiscount = volumeDiscount;
        this.startRange = startRange;
        this.endRange = endRange;
    }
    
    /** full constructor */
    public MstbVolDiscTier(BigDecimal volumeDiscount, BigDecimal startRange, BigDecimal endRange, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, Integer version, MstbVolDiscDetail mstbVolDiscDetail) {
        this.volumeDiscount = volumeDiscount;
        this.startRange = startRange;
        this.endRange = endRange;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.version = version;
        this.mstbVolDiscDetail = mstbVolDiscDetail;
    }
    

   
    // Property accessors

    public Integer getVolumeDiscountPlanTierNo() {
        return this.volumeDiscountPlanTierNo;
    }
    
    public void setVolumeDiscountPlanTierNo(Integer volumeDiscountPlanTierNo) {
        this.volumeDiscountPlanTierNo = volumeDiscountPlanTierNo;
    }

    public BigDecimal getVolumeDiscount() {
        return this.volumeDiscount;
    }
    
    public void setVolumeDiscount(BigDecimal volumeDiscount) {
        this.volumeDiscount = volumeDiscount;
    }

    public BigDecimal getStartRange() {
        return this.startRange;
    }
    
    public void setStartRange(BigDecimal startRange) {
        this.startRange = startRange;
    }

    public BigDecimal getEndRange() {
        return this.endRange;
    }
    
    public void setEndRange(BigDecimal endRange) {
        this.endRange = endRange;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public MstbVolDiscDetail getMstbVolDiscDetail() {
        return this.mstbVolDiscDetail;
    }
    
    public void setMstbVolDiscDetail(MstbVolDiscDetail mstbVolDiscDetail) {
        this.mstbVolDiscDetail = mstbVolDiscDetail;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("volumeDiscount").append("='").append(getVolumeDiscount()).append("' ");			
      buffer.append("startRange").append("='").append(getStartRange()).append("' ");			
      buffer.append("endRange").append("='").append(getEndRange()).append("' ");		
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");		
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstbVolDiscTier) ) return false;
		 MstbVolDiscTier castOther = ( MstbVolDiscTier ) other; 
         
		 return ( (this.getVolumeDiscountPlanTierNo()==castOther.getVolumeDiscountPlanTierNo()) || ( this.getVolumeDiscountPlanTierNo()!=null && castOther.getVolumeDiscountPlanTierNo()!=null && this.getVolumeDiscountPlanTierNo().equals(castOther.getVolumeDiscountPlanTierNo()) ) )
 && ( (this.getVolumeDiscount()==castOther.getVolumeDiscount()) || ( this.getVolumeDiscount()!=null && castOther.getVolumeDiscount()!=null && this.getVolumeDiscount().equals(castOther.getVolumeDiscount()) ) )
 && ( (this.getStartRange()==castOther.getStartRange()) || ( this.getStartRange()!=null && castOther.getStartRange()!=null && this.getStartRange().equals(castOther.getStartRange()) ) )
 && ( (this.getEndRange()==castOther.getEndRange()) || ( this.getEndRange()!=null && castOther.getEndRange()!=null && this.getEndRange().equals(castOther.getEndRange()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getMstbVolDiscDetail()==castOther.getMstbVolDiscDetail()) || ( this.getMstbVolDiscDetail()!=null && castOther.getMstbVolDiscDetail()!=null && this.getMstbVolDiscDetail().equals(castOther.getMstbVolDiscDetail()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getVolumeDiscountPlanTierNo() == null ? 0 : this.getVolumeDiscountPlanTierNo().hashCode() );
         result = 37 * result + ( getVolumeDiscount() == null ? 0 : this.getVolumeDiscount().hashCode() );
         result = 37 * result + ( getStartRange() == null ? 0 : this.getStartRange().hashCode() );
         result = 37 * result + ( getEndRange() == null ? 0 : this.getEndRange().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getMstbVolDiscDetail() == null ? 0 : this.getMstbVolDiscDetail().hashCode() );
         return result;
   }   


}
