package com.cdgtaxi.ibs.master.model;
// Generated Jun 15, 2010 3:44:38 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;
import java.util.Set;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.common.model.Creatable;
import com.cdgtaxi.ibs.common.model.PmtbIssuanceReqCard;
import com.cdgtaxi.ibs.common.model.PmtbTopUpReqCard;
import com.cdgtaxi.ibs.common.model.Updatable;


/**
 * MstbPromotion generated by hbm2java
 */

@SuppressWarnings("serial")
public class MstbPromotionCashPlus  implements java.io.Serializable, Creatable, Updatable, Auditable {

    private String promoCode;
    private String createdBy;
    private Timestamp createdDt;
    private String updatedBy;
    private Timestamp updatedDt;
    private Integer version;
    private String remarks;
    
    private Date effectiveDtFrom;
    private Date effectiveDtTo;
    private BigDecimal cashplus;
    private Set<PmtbIssuanceReqCard> pmtbIssuanceReqCards;
    private Set<PmtbTopUpReqCard> pmtbTopUpReqCards;
	public String getPromoCode() {
		return promoCode;
	}
	public String getCreatedBy() {
		return createdBy;
	}
	public Timestamp getCreatedDt() {
		return createdDt;
	}
	public String getUpdatedBy() {
		return updatedBy;
	}
	public Timestamp getUpdatedDt() {
		return updatedDt;
	}
	public Integer getVersion() {
		return version;
	}
	public Date getEffectiveDtFrom() {
		return effectiveDtFrom;
	}
	public Date getEffectiveDtTo() {
		return effectiveDtTo;
	}
	public BigDecimal getCashplus() {
		return cashplus;
	}
	public void setPromoCode(String promoCode) {
		this.promoCode = promoCode;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	public void setCreatedDt(Timestamp createdDt) {
		this.createdDt = createdDt;
	}
	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}
	public void setUpdatedDt(Timestamp updatedDt) {
		this.updatedDt = updatedDt;
	}
	public void setVersion(Integer version) {
		this.version = version;
	}
	public void setEffectiveDtFrom(Date effectiveDtFrom) {
		this.effectiveDtFrom = effectiveDtFrom;
	}
	public void setEffectiveDtTo(Date effectiveDtTo) {
		this.effectiveDtTo = effectiveDtTo;
	}
	public void setCashplus(BigDecimal cashplus) {
		this.cashplus = cashplus;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((promoCode == null) ? 0 : promoCode.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		MstbPromotionCashPlus other = (MstbPromotionCashPlus) obj;
		if (promoCode == null) {
			if (other.promoCode != null)
				return false;
		} else if (!promoCode.equals(other.promoCode))
			return false;
		return true;
	}
	
	public String getRemarks() {
		return remarks;
	}
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
	public Set<PmtbIssuanceReqCard> getPmtbIssuanceReqCards() {
		return pmtbIssuanceReqCards;
	}
	public Set<PmtbTopUpReqCard> getPmtbTopUpReqCards() {
		return pmtbTopUpReqCards;
	}
	public void setPmtbIssuanceReqCards(Set<PmtbIssuanceReqCard> pmtbIssuanceReqCards) {
		this.pmtbIssuanceReqCards = pmtbIssuanceReqCards;
	}
	public void setPmtbTopUpReqCards(Set<PmtbTopUpReqCard> pmtbTopUpReqCards) {
		this.pmtbTopUpReqCards = pmtbTopUpReqCards;
	}
	
	
	
	

	
	
    
    
    
}
