package com.cdgtaxi.ibs.master.model;
// Generated Apr 8, 2009 2:33:57 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.common.model.AmtbAcctAdminFee;
import com.cdgtaxi.ibs.common.model.AmtbAcctAdminFeeReq;
import com.cdgtaxi.ibs.common.model.AmtbApplication;
import com.cdgtaxi.ibs.common.model.Creatable;
import com.cdgtaxi.ibs.common.model.Updatable;


/**
 * MstbAdminFeeMaster generated by hbm2java
 */

public class MstbAdminFeeMaster  implements java.io.Serializable, Creatable, Updatable {


    // Fields    

    private Integer adminFeePlanNo;
    private String adminFeePlanName;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private Integer version;
    private Set<AmtbAcctAdminFeeReq> amtbAcctAdminFeeReqs = new HashSet<AmtbAcctAdminFeeReq>(0);
    private Set<AmtbApplication> amtbApplications = new HashSet<AmtbApplication>(0);
    private Set<AmtbAcctAdminFee> amtbAcctAdminFees = new HashSet<AmtbAcctAdminFee>(0);
    private Set<MstbAdminFeeDetail> mstbAdminFeeDetails = new HashSet<MstbAdminFeeDetail>(0);


    // Constructors

    /** default constructor */
    public MstbAdminFeeMaster() {
    }

	/** minimal constructor */
    public MstbAdminFeeMaster(String adminFeePlanName) {
        this.adminFeePlanName = adminFeePlanName;
    }
    
    /** full constructor */
    public MstbAdminFeeMaster(String adminFeePlanName, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, Integer version, Set<AmtbAcctAdminFeeReq> amtbAcctAdminFeeReqs, Set<AmtbApplication> amtbApplications, Set<AmtbAcctAdminFee> amtbAcctAdminFees, Set<MstbAdminFeeDetail> mstbAdminFeeDetails) {
        this.adminFeePlanName = adminFeePlanName;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.version = version;
        this.amtbAcctAdminFeeReqs = amtbAcctAdminFeeReqs;
        this.amtbApplications = amtbApplications;
        this.amtbAcctAdminFees = amtbAcctAdminFees;
        this.mstbAdminFeeDetails = mstbAdminFeeDetails;
    }
    

   
    // Property accessors

    public Integer getAdminFeePlanNo() {
        return this.adminFeePlanNo;
    }
    
    public void setAdminFeePlanNo(Integer adminFeePlanNo) {
        this.adminFeePlanNo = adminFeePlanNo;
    }

    public String getAdminFeePlanName() {
        return this.adminFeePlanName;
    }
    
    public void setAdminFeePlanName(String adminFeePlanName) {
        this.adminFeePlanName = adminFeePlanName;
    }
    
    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public Set<AmtbAcctAdminFeeReq> getAmtbAcctAdminFeeReqs() {
        return this.amtbAcctAdminFeeReqs;
    }
    
    public void setAmtbAcctAdminFeeReqs(Set<AmtbAcctAdminFeeReq> amtbAcctAdminFeeReqs) {
        this.amtbAcctAdminFeeReqs = amtbAcctAdminFeeReqs;
    }

    public Set<AmtbApplication> getAmtbApplications() {
        return this.amtbApplications;
    }
    
    public void setAmtbApplications(Set<AmtbApplication> amtbApplications) {
        this.amtbApplications = amtbApplications;
    }

    public Set<AmtbAcctAdminFee> getAmtbAcctAdminFees() {
        return this.amtbAcctAdminFees;
    }
    
    public void setAmtbAcctAdminFees(Set<AmtbAcctAdminFee> amtbAcctAdminFees) {
        this.amtbAcctAdminFees = amtbAcctAdminFees;
    }

    public Set<MstbAdminFeeDetail> getMstbAdminFeeDetails() {
        return this.mstbAdminFeeDetails;
    }
    
    public void setMstbAdminFeeDetails(Set<MstbAdminFeeDetail> mstbAdminFeeDetails) {
        this.mstbAdminFeeDetails = mstbAdminFeeDetails;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("adminFeePlanName").append("='").append(getAdminFeePlanName()).append("' ");
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstbAdminFeeMaster) ) return false;
		 MstbAdminFeeMaster castOther = ( MstbAdminFeeMaster ) other; 
         
		 return ( (this.getAdminFeePlanNo()==castOther.getAdminFeePlanNo()) || ( this.getAdminFeePlanNo()!=null && castOther.getAdminFeePlanNo()!=null && this.getAdminFeePlanNo().equals(castOther.getAdminFeePlanNo()) ) )
 && ( (this.getAdminFeePlanName()==castOther.getAdminFeePlanName()) || ( this.getAdminFeePlanName()!=null && castOther.getAdminFeePlanName()!=null && this.getAdminFeePlanName().equals(castOther.getAdminFeePlanName()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAdminFeePlanNo() == null ? 0 : this.getAdminFeePlanNo().hashCode() );
         result = 37 * result + ( getAdminFeePlanName() == null ? 0 : this.getAdminFeePlanName().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         return result;
   }   

}
