package com.cdgtaxi.ibs.master.model;
// Generated Mar 27, 2009 6:21:33 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Timestamp;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.common.model.Creatable;
import com.cdgtaxi.ibs.common.model.Updatable;


/**
 * MstbProdDiscDetail generated by hbm2java
 */

public class MstbProdDiscDetail  implements java.io.Serializable, Creatable, Updatable, Auditable{


    // Fields    

    private Integer prodDiscountPlanDetailNo;
    private Timestamp effectiveDt;
    private BigDecimal productDiscount;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private Integer version;
    private MstbProdDiscMaster mstbProdDiscMaster;


    // Constructors

    /** default constructor */
    public MstbProdDiscDetail() {
    }

	/** minimal constructor */
    public MstbProdDiscDetail(Timestamp effectiveDt, BigDecimal productDiscount) {
        this.effectiveDt = effectiveDt;
        this.productDiscount = productDiscount;
    }
    
    /** full constructor */
    public MstbProdDiscDetail(Timestamp effectiveDt, BigDecimal productDiscount, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, Integer version, MstbProdDiscMaster mstbProdDiscMaster) {
        this.effectiveDt = effectiveDt;
        this.productDiscount = productDiscount;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.version = version;
        this.mstbProdDiscMaster = mstbProdDiscMaster;
    }
    

   
    // Property accessors

    public Integer getProdDiscountPlanDetailNo() {
        return this.prodDiscountPlanDetailNo;
    }
    
    public void setProdDiscountPlanDetailNo(Integer prodDiscountPlanDetailNo) {
        this.prodDiscountPlanDetailNo = prodDiscountPlanDetailNo;
    }

    public Timestamp getEffectiveDt() {
        return this.effectiveDt;
    }
    
    public void setEffectiveDt(Timestamp effectiveDt) {
        this.effectiveDt = effectiveDt;
    }

    public BigDecimal getProductDiscount() {
        return this.productDiscount;
    }
    
    public void setProductDiscount(BigDecimal productDiscount) {
        this.productDiscount = productDiscount;
    }
    
    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public MstbProdDiscMaster getMstbProdDiscMaster() {
        return this.mstbProdDiscMaster;
    }
    
    public void setMstbProdDiscMaster(MstbProdDiscMaster mstbProdDiscMaster) {
        this.mstbProdDiscMaster = mstbProdDiscMaster;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("effectiveDt").append("='").append(getEffectiveDt()).append("' ");			
      buffer.append("productDiscount").append("='").append(getProductDiscount()).append("' ");
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");	
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstbProdDiscDetail) ) return false;
		 MstbProdDiscDetail castOther = ( MstbProdDiscDetail ) other; 
         
		 return ( (this.getProdDiscountPlanDetailNo()==castOther.getProdDiscountPlanDetailNo()) || ( this.getProdDiscountPlanDetailNo()!=null && castOther.getProdDiscountPlanDetailNo()!=null && this.getProdDiscountPlanDetailNo().equals(castOther.getProdDiscountPlanDetailNo()) ) )
 && ( (this.getEffectiveDt()==castOther.getEffectiveDt()) || ( this.getEffectiveDt()!=null && castOther.getEffectiveDt()!=null && this.getEffectiveDt().equals(castOther.getEffectiveDt()) ) )
 && ( (this.getProductDiscount()==castOther.getProductDiscount()) || ( this.getProductDiscount()!=null && castOther.getProductDiscount()!=null && this.getProductDiscount().equals(castOther.getProductDiscount()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getMstbProdDiscMaster()==castOther.getMstbProdDiscMaster()) || ( this.getMstbProdDiscMaster()!=null && castOther.getMstbProdDiscMaster()!=null && this.getMstbProdDiscMaster().equals(castOther.getMstbProdDiscMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProdDiscountPlanDetailNo() == null ? 0 : this.getProdDiscountPlanDetailNo().hashCode() );
         result = 37 * result + ( getEffectiveDt() == null ? 0 : this.getEffectiveDt().hashCode() );
         result = 37 * result + ( getProductDiscount() == null ? 0 : this.getProductDiscount().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getMstbProdDiscMaster() == null ? 0 : this.getMstbProdDiscMaster().hashCode() );
         return result;
   }   





}
