package com.cdgtaxi.ibs.master.model;
// Generated Jun 15, 2010 3:44:38 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.common.model.AmtbAcctPromotion;
import com.cdgtaxi.ibs.common.model.AmtbAcctPromotionReq;
import com.cdgtaxi.ibs.common.model.Creatable;


/**
 * MstbPromotion generated by hbm2java
 */

@SuppressWarnings("serial")
public class MstbPromotion  implements java.io.Serializable, Creatable, Auditable {

    // Fields    
	
    private Integer promoNo;
    private String createdBy;
    private Timestamp createdDt;
    private String lastUpdatedBy;
    private Timestamp lastUpdatedDt;
    private Integer version;
    private MstbPromoReq lastPromoReq;
    private MstbPromoDetail currentPromoDetail;
    private String currentStatus;
    private Set<AmtbAcctPromotion> amtbAcctPromotions = new HashSet<AmtbAcctPromotion>(0);
    private Set<AmtbAcctPromotionReq> amtbAcctPromotionReqs = new HashSet<AmtbAcctPromotionReq>(0);
    private Set<MstbPromoReq> mstbPromoReqs = new HashSet<MstbPromoReq>(0);
    // Constructors

    /** default constructor */
    public MstbPromotion() {
    }

	/** minimal constructor */
    public MstbPromotion(Integer promoNo) {
        this.promoNo = promoNo;
    }
    
    /** full constructor */
    public MstbPromotion(Integer promoNo, String createdBy, Timestamp createdDt, String lastUpdatedBy, Timestamp lastUpdatedDt, Integer version, MstbPromoReq lastPromoReq, MstbPromoDetail currentPromoDetail, String currentStatus, Set<AmtbAcctPromotion> amtbAcctPromotions, Set<AmtbAcctPromotionReq> amtbAcctPromotionReqs,Set<MstbPromoReq> mstbPromoReqs) {
        this.promoNo = promoNo;
        this.createdBy = createdBy;
		this.createdDt = createdDt;
		this.lastUpdatedBy = lastUpdatedBy;
		this.lastUpdatedDt = lastUpdatedDt;
        this.version = version;
        this.lastPromoReq = lastPromoReq;
        this.currentPromoDetail = currentPromoDetail;
        this.currentStatus = currentStatus;
        this.amtbAcctPromotions = amtbAcctPromotions;
        this.amtbAcctPromotionReqs = amtbAcctPromotionReqs;
        this.mstbPromoReqs = mstbPromoReqs;
    }
    // Property accessors

    public Integer getPromoNo() {
        return this.promoNo;
    }
    
    public void setPromoNo(Integer promoNo) {
        this.promoNo = promoNo;
    }
    
    public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Timestamp getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Timestamp createdDt) {
		this.createdDt = createdDt;
	}
	
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}
	
	public Timestamp getLastUpdatedDt() {
		return this.lastUpdatedDt;
	}

	public void setLastUpdatedDt(Timestamp lastUpdatedDt) {
		this.lastUpdatedDt = lastUpdatedDt;
	}

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    public MstbPromoReq getLastPromoReq() {
        return this.lastPromoReq;
    }
    
    public void setLastPromoReq(MstbPromoReq lastPromoReq) {
        this.lastPromoReq = lastPromoReq;
    }
    
    public MstbPromoDetail getCurrentPromoDetail() {
        return this.currentPromoDetail;
    }
    
    public void setCurrentPromoDetail(MstbPromoDetail currentPromoDetail) {
        this.currentPromoDetail = currentPromoDetail;
    }
    
    public String getCurrentStatus() {
        return this.currentStatus;
    }
    
    public void setCurrentStatus(String currentStatus) {
        this.currentStatus = currentStatus;
    }

    public Set<AmtbAcctPromotion> getAmtbAcctPromotions() {
        return this.amtbAcctPromotions;
    }
    
    public void setAmtbAcctPromotions(Set<AmtbAcctPromotion> amtbAcctPromotions) {
        this.amtbAcctPromotions = amtbAcctPromotions;
    }

    public Set<AmtbAcctPromotionReq> getAmtbAcctPromotionReqs() {
        return this.amtbAcctPromotionReqs;
    }
    
    public void setAmtbAcctPromotionReqs(Set<AmtbAcctPromotionReq> amtbAcctPromotionReqs) {
        this.amtbAcctPromotionReqs = amtbAcctPromotionReqs;
    }
    
    public Set<MstbPromoReq> getMstbPromoReqs() {
        return this.mstbPromoReqs;
    }
    
    public void setMstbPromoReqs(Set<MstbPromoReq> mstbPromoReqs) {
        this.mstbPromoReqs = mstbPromoReqs;
    }

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
	  buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");
	  buffer.append("lastUpdatedBy").append("='").append(getLastUpdatedBy()).append("' ");
	  buffer.append("lastUpdatedDt").append("='").append(getLastUpdatedDt()).append("' ");
	  //buffer.append("lastPromoReq").append("='").append(getLastPromoReq()).append("' ");
	  buffer.append("currentPromoDetail").append("='").append(getCurrentPromoDetail()).append("' ");
	  buffer.append("currentStatus").append("='").append(getCurrentStatus()).append("' ");
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstbPromotion) ) return false;
		 MstbPromotion castOther = ( MstbPromotion ) other; 
         
		 return ( (this.getPromoNo()==castOther.getPromoNo()) || ( this.getPromoNo()!=null && castOther.getPromoNo()!=null && this.getPromoNo().equals(castOther.getPromoNo()) ) )
	 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
	 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) ) 
	 && ( (this.getLastUpdatedBy()==castOther.getLastUpdatedBy()) || ( this.getLastUpdatedBy()!=null && castOther.getLastUpdatedBy()!=null && this.getLastUpdatedBy().equals(castOther.getLastUpdatedBy()) ) )
	 && ( (this.getLastUpdatedDt()==castOther.getLastUpdatedDt()) || ( this.getLastUpdatedDt()!=null && castOther.getLastUpdatedDt()!=null && this.getLastUpdatedDt().equals(castOther.getLastUpdatedDt()) ) ) 
	 //&& ( (this.getLastPromoReq()==castOther.getLastPromoReq()) || ( this.getLastPromoReq()!=null && castOther.getLastPromoReq()!=null && this.getLastPromoReq().equals(castOther.getLastPromoReq()) ) )
	 && ( (this.getCurrentPromoDetail()==castOther.getCurrentPromoDetail()) || ( this.getCurrentPromoDetail()!=null && castOther.getCurrentPromoDetail()!=null && this.getCurrentPromoDetail().equals(castOther.getCurrentPromoDetail()) ) )
	 && ( (this.getCurrentStatus()==castOther.getCurrentStatus()) || ( this.getCurrentStatus()!=null && castOther.getCurrentStatus()!=null && this.getCurrentStatus().equals(castOther.getCurrentStatus()) ) )
	 
	 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) );
}
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPromoNo() == null ? 0 : this.getPromoNo().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
		 result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
		 result = 37 * result + ( getLastUpdatedBy() == null ? 0 : this.getLastUpdatedBy().hashCode() );
		 result = 37 * result + ( getLastUpdatedDt() == null ? 0 : this.getLastUpdatedDt().hashCode() );
		 //result = 37 * result + ( getLastPromoReq() == null ? 0 : this.getLastPromoReq().hashCode() );
		 result = 37 * result + ( getCurrentPromoDetail() == null ? 0 : this.getCurrentPromoDetail().hashCode() );
		 result = 37 * result + ( getCurrentStatus() == null ? 0 : this.getCurrentStatus().hashCode() );
		 result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         
         return result;
   }   





}
