package com.cdgtaxi.ibs.master.model;
// Generated Jul 20, 2009 6:36:40 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.common.model.AmtbAccount;
import com.cdgtaxi.ibs.common.model.AmtbBillReq;
import com.cdgtaxi.ibs.common.model.BmtbPaymentReceipt;
import com.cdgtaxi.ibs.common.model.Creatable;
import com.cdgtaxi.ibs.common.model.Updatable;


/**
 * MstbBranchMaster generated by hbm2java
 */

public class MstbBranchMaster  implements java.io.Serializable, Creatable, Updatable, Auditable {


    // Fields    

    private Integer branchMasterNo;
    private String branchName;
    private String branchCode;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private Integer version;
    private MstbBankMaster mstbBankMaster;
    private Set<BmtbPaymentReceipt> bmtbPaymentReceipts = new HashSet<BmtbPaymentReceipt>(0);
    private Set<AmtbBillReq> amtbBillReqs = new HashSet<AmtbBillReq>(0);
    private Set<AmtbAccount> amtbAccounts = new HashSet<AmtbAccount>(0);


    // Constructors

    /** default constructor */
    public MstbBranchMaster() {
    }

	/** minimal constructor */
    public MstbBranchMaster(String branchName, String branchCode) {
        this.branchName = branchName;
        this.branchCode = branchCode;
    }
    
    /** full constructor */
    public MstbBranchMaster(String branchName, String branchCode, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, Integer version, MstbBankMaster mstbBankMaster, Set<BmtbPaymentReceipt> bmtbPaymentReceipts, Set<AmtbBillReq> amtbBillReqs, Set<AmtbAccount> amtbAccounts) {
        this.branchName = branchName;
        this.branchCode = branchCode;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.version = version;
        this.mstbBankMaster = mstbBankMaster;
        this.bmtbPaymentReceipts = bmtbPaymentReceipts;
        this.amtbBillReqs = amtbBillReqs;
        this.amtbAccounts = amtbAccounts;
    }
    

   
    // Property accessors

    public Integer getBranchMasterNo() {
        return this.branchMasterNo;
    }
    
    public void setBranchMasterNo(Integer branchMasterNo) {
        this.branchMasterNo = branchMasterNo;
    }

    public String getBranchName() {
        return this.branchName;
    }
    
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    public String getBranchCode() {
        return this.branchCode;
    }
    
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }
    
    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public MstbBankMaster getMstbBankMaster() {
        return this.mstbBankMaster;
    }
    
    public void setMstbBankMaster(MstbBankMaster mstbBankMaster) {
        this.mstbBankMaster = mstbBankMaster;
    }

    public Set<BmtbPaymentReceipt> getBmtbPaymentReceipts() {
        return this.bmtbPaymentReceipts;
    }
    
    public void setBmtbPaymentReceipts(Set<BmtbPaymentReceipt> bmtbPaymentReceipts) {
        this.bmtbPaymentReceipts = bmtbPaymentReceipts;
    }

    public Set<AmtbBillReq> getAmtbBillReqs() {
        return this.amtbBillReqs;
    }
    
    public void setAmtbBillReqs(Set<AmtbBillReq> amtbBillReqs) {
        this.amtbBillReqs = amtbBillReqs;
    }

    public Set<AmtbAccount> getAmtbAccounts() {
        return this.amtbAccounts;
    }
    
    public void setAmtbAccounts(Set<AmtbAccount> amtbAccounts) {
        this.amtbAccounts = amtbAccounts;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("branchName").append("='").append(getBranchName()).append("' ");			
      buffer.append("branchCode").append("='").append(getBranchCode()).append("' ");
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstbBranchMaster) ) return false;
		 MstbBranchMaster castOther = ( MstbBranchMaster ) other; 
         
		 return ( (this.getBranchMasterNo()==castOther.getBranchMasterNo()) || ( this.getBranchMasterNo()!=null && castOther.getBranchMasterNo()!=null && this.getBranchMasterNo().equals(castOther.getBranchMasterNo()) ) )
 && ( (this.getBranchName()==castOther.getBranchName()) || ( this.getBranchName()!=null && castOther.getBranchName()!=null && this.getBranchName().equals(castOther.getBranchName()) ) )
 && ( (this.getBranchCode()==castOther.getBranchCode()) || ( this.getBranchCode()!=null && castOther.getBranchCode()!=null && this.getBranchCode().equals(castOther.getBranchCode()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getMstbBankMaster()==castOther.getMstbBankMaster()) || ( this.getMstbBankMaster()!=null && castOther.getMstbBankMaster()!=null && this.getMstbBankMaster().equals(castOther.getMstbBankMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBranchMasterNo() == null ? 0 : this.getBranchMasterNo().hashCode() );
         result = 37 * result + ( getBranchName() == null ? 0 : this.getBranchName().hashCode() );
         result = 37 * result + ( getBranchCode() == null ? 0 : this.getBranchCode().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getMstbBankMaster() == null ? 0 : this.getMstbBankMaster().hashCode() );
         return result;
   }   

}
