package com.cdgtaxi.ibs.master.model;
// Generated Jul 20, 2009 6:37:01 PM by Hibernate Tools 3.1.0.beta4

import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.common.model.AmtbAccount;
import com.cdgtaxi.ibs.common.model.AmtbAcctStatus;
import com.cdgtaxi.ibs.common.model.AmtbApplication;
import com.cdgtaxi.ibs.common.model.AmtbContactPerson;
import com.cdgtaxi.ibs.common.model.AmtbCorporateDetail;
import com.cdgtaxi.ibs.common.model.AmtbPersonalDetail;
import com.cdgtaxi.ibs.common.model.BmtbNote;
import com.cdgtaxi.ibs.common.model.BmtbPaymentReceipt;
import com.cdgtaxi.ibs.common.model.FmtbEntityMaster;
import com.cdgtaxi.ibs.common.model.FmtbTaxCode;
import com.cdgtaxi.ibs.common.model.FmtbTransactionCode;
import com.cdgtaxi.ibs.common.model.PmtbProductReplacement;
import com.cdgtaxi.ibs.common.model.PmtbProductStatus;
import com.cdgtaxi.ibs.common.model.TmtbAcquireTxn;
import com.cdgtaxi.ibs.common.model.TmtbNonBillableTxn;
import com.cdgtaxi.ibs.common.model.TmtbTxnReviewReq;


/**
 * MstbMasterTable generated by hbm2java
 */

public class MstbMasterTable  implements java.io.Serializable {


    // Fields    

    private Integer masterNo;
    private String masterType;
    private String masterCode;
    private String interfaceMappingValue;
    private String masterValue;
    private String masterStatus;
    private Integer version;
    private String masterGrouping;
    //private String masterGroupingDesc;
    private Set<AmtbCorporateDetail> amtbCorporateDetailsByIndustry = new HashSet<AmtbCorporateDetail>(0);
    private Set<AmtbCorporateDetail> amtbCorporateDetailsByAuthPersonSal = new HashSet<AmtbCorporateDetail>(0);
    private Set<AmtbCorporateDetail> amtbCorporateDetailsByAddressCountry = new HashSet<AmtbCorporateDetail>(0);
    private Set<AmtbPersonalDetail> amtbPersonalDetailsByIndustry = new HashSet<AmtbPersonalDetail>(0);
    private Set<AmtbPersonalDetail> amtbPersonalDetailsByAddressCountry = new HashSet<AmtbPersonalDetail>(0);
    private Set<AmtbPersonalDetail> amtbPersonalDetailsByEmployerCountry = new HashSet<AmtbPersonalDetail>(0);
    private Set<AmtbPersonalDetail> amtbPersonalDetailsByJobStatus = new HashSet<AmtbPersonalDetail>(0);
    private Set<AmtbPersonalDetail> amtbPersonalDetailsByRelationToParent = new HashSet<AmtbPersonalDetail>(0);
    private Set<AmtbAcctStatus> amtbAcctStatuses = new HashSet<AmtbAcctStatus>(0);
    private Set<TmtbTxnReviewReq> tmtbTxnReviewReqsByServiceProvider = new HashSet<TmtbTxnReviewReq>(0);
    private Set<TmtbTxnReviewReq> tmtbTxnReviewReqsByTripType = new HashSet<TmtbTxnReviewReq>(0);
    private Set<TmtbTxnReviewReq> tmtbTxnReviewReqsByVehicleType = new HashSet<TmtbTxnReviewReq>(0);
    private Set<PmtbProductReplacement> pmtbProductReplacements = new HashSet<PmtbProductReplacement>(0);
    private Set<AmtbContactPerson> amtbContactPersonsByAddressCountry = new HashSet<AmtbContactPerson>(0);
    private Set<AmtbContactPerson> amtbContactPersonsByMainContactSal = new HashSet<AmtbContactPerson>(0);
    private Set<AmtbContactPerson> amtbContactPersonsBySubContactSal = new HashSet<AmtbContactPerson>(0);
    private Set<FmtbTransactionCode> fmtbTransactionCodes = new HashSet<FmtbTransactionCode>(0);
    private Set<BmtbNote> bmtbNotesByCancellationReason = new HashSet<BmtbNote>(0);
    private Set<BmtbNote> bmtbNotesByReason = new HashSet<BmtbNote>(0);
    private Set<BmtbPaymentReceipt> bmtbPaymentReceiptsByCancellationReason = new HashSet<BmtbPaymentReceipt>(0);
    private Set<BmtbPaymentReceipt> bmtbPaymentReceiptsByPaymentMode = new HashSet<BmtbPaymentReceipt>(0);
    private Set<AmtbApplication> amtbApplicationsByEmployerCountry = new HashSet<AmtbApplication>(0);
    private Set<AmtbApplication> amtbApplicationsByBillingCountry = new HashSet<AmtbApplication>(0);
    private Set<AmtbApplication> amtbApplicationsByJobStatus = new HashSet<AmtbApplication>(0);
    private Set<AmtbApplication> amtbApplicationsByShippingCountry = new HashSet<AmtbApplication>(0);
    private Set<AmtbApplication> amtbApplicationsByAuthSal = new HashSet<AmtbApplication>(0);
    private Set<AmtbApplication> amtbApplicationsByIndustryNo = new HashSet<AmtbApplication>(0);
    private Set<AmtbApplication> amtbApplicationsByInformationSource = new HashSet<AmtbApplication>(0);
    private Set<AmtbApplication> amtbApplicationsByAddressCountry = new HashSet<AmtbApplication>(0);
    private Set<TmtbAcquireTxn> tmtbAcquireTxnsByTripType = new HashSet<TmtbAcquireTxn>(0);
    private Set<TmtbAcquireTxn> tmtbAcquireTxnsByServiceProvider = new HashSet<TmtbAcquireTxn>(0);
    private Set<TmtbAcquireTxn> tmtbAcquireTxnsByVehicleType = new HashSet<TmtbAcquireTxn>(0);
    private Set<FmtbEntityMaster> fmtbEntityMasters = new HashSet<FmtbEntityMaster>(0);
    private Set<FmtbTaxCode> fmtbTaxCodes = new HashSet<FmtbTaxCode>(0);
    private Set<AmtbAccount> amtbAccountsByDefaultPaymentMode = new HashSet<AmtbAccount>(0);
    private Set<AmtbAccount> amtbAccountsByInformationSource = new HashSet<AmtbAccount>(0);
    private Set<PmtbProductStatus> pmtbProductStatuses = new HashSet<PmtbProductStatus>(0);
    private Set<TmtbNonBillableTxn> tmtbNonBillableTxns = new HashSet<TmtbNonBillableTxn>(0);
    private Set<MstbAcquirerPymtType> mstbAcquirerPymtTypes = new HashSet<MstbAcquirerPymtType>(0);


    // Constructors

    /** default constructor */
    public MstbMasterTable() {
    }

	/** minimal constructor */
    public MstbMasterTable(String masterType, String masterCode, String masterValue, String masterStatus, String masterGrouping) {
        this.masterType = masterType;
        this.masterCode = masterCode;
        this.masterValue = masterValue;
        this.masterStatus = masterStatus;
        this.masterGrouping = masterGrouping;
    }
    
    /** full constructor */
    public MstbMasterTable(String masterType, String masterCode, String interfaceMappingValue, String masterValue, String masterStatus, Integer version, Set<AmtbCorporateDetail> amtbCorporateDetailsByIndustry, Set<AmtbCorporateDetail> amtbCorporateDetailsByAuthPersonSal, Set<AmtbCorporateDetail> amtbCorporateDetailsByAddressCountry, Set<AmtbPersonalDetail> amtbPersonalDetailsByIndustry, Set<AmtbPersonalDetail> amtbPersonalDetailsByAddressCountry, Set<AmtbPersonalDetail> amtbPersonalDetailsByEmployerCountry, Set<AmtbPersonalDetail> amtbPersonalDetailsByJobStatus, Set<AmtbPersonalDetail> amtbPersonalDetailsByRelationToParent, Set<AmtbAcctStatus> amtbAcctStatuses, Set<TmtbTxnReviewReq> tmtbTxnReviewReqsByServiceProvider, Set<TmtbTxnReviewReq> tmtbTxnReviewReqsByTripType, Set<TmtbTxnReviewReq> tmtbTxnReviewReqsByVehicleType, Set<PmtbProductReplacement> pmtbProductReplacements, Set<AmtbContactPerson> amtbContactPersonsByAddressCountry, Set<AmtbContactPerson> amtbContactPersonsByMainContactSal, Set<AmtbContactPerson> amtbContactPersonsBySubContactSal, Set<FmtbTransactionCode> fmtbTransactionCodes, Set<BmtbNote> bmtbNotesByCancellationReason, Set<BmtbNote> bmtbNotesByReason, Set<BmtbPaymentReceipt> bmtbPaymentReceiptsByCancellationReason, Set<BmtbPaymentReceipt> bmtbPaymentReceiptsByPaymentMode, Set<AmtbApplication> amtbApplicationsByEmployerCountry, Set<AmtbApplication> amtbApplicationsByBillingCountry, Set<AmtbApplication> amtbApplicationsByJobStatus, Set<AmtbApplication> amtbApplicationsByShippingCountry, Set<AmtbApplication> amtbApplicationsByAuthSal, Set<AmtbApplication> amtbApplicationsByIndustryNo, Set<AmtbApplication> amtbApplicationsByInformationSource, Set<AmtbApplication> amtbApplicationsByAddressCountry, Set<TmtbAcquireTxn> tmtbAcquireTxnsByTripType, Set<TmtbAcquireTxn> tmtbAcquireTxnsByServiceProvider, Set<TmtbAcquireTxn> tmtbAcquireTxnsByVehicleType, Set<FmtbEntityMaster> fmtbEntityMasters, Set<FmtbTaxCode> fmtbTaxCodes, Set<AmtbAccount> amtbAccountsByDefaultPaymentMode, Set<AmtbAccount> amtbAccountsByInformationSource, Set<PmtbProductStatus> pmtbProductStatuses, Set<TmtbNonBillableTxn> tmtbNonBillableTxns, Set<MstbAcquirerPymtType> mstbAcquirerPymtTypes, String masterGrouping) {
        this.masterType = masterType;
        this.masterCode = masterCode;
        this.interfaceMappingValue = interfaceMappingValue;
        this.masterValue = masterValue;
        this.masterStatus = masterStatus;
        this.version = version;
        this.amtbCorporateDetailsByIndustry = amtbCorporateDetailsByIndustry;
        this.amtbCorporateDetailsByAuthPersonSal = amtbCorporateDetailsByAuthPersonSal;
        this.amtbCorporateDetailsByAddressCountry = amtbCorporateDetailsByAddressCountry;
        this.amtbPersonalDetailsByIndustry = amtbPersonalDetailsByIndustry;
        this.amtbPersonalDetailsByAddressCountry = amtbPersonalDetailsByAddressCountry;
        this.amtbPersonalDetailsByEmployerCountry = amtbPersonalDetailsByEmployerCountry;
        this.amtbPersonalDetailsByJobStatus = amtbPersonalDetailsByJobStatus;
        this.amtbPersonalDetailsByRelationToParent = amtbPersonalDetailsByRelationToParent;
        this.amtbAcctStatuses = amtbAcctStatuses;
        this.tmtbTxnReviewReqsByServiceProvider = tmtbTxnReviewReqsByServiceProvider;
        this.tmtbTxnReviewReqsByTripType = tmtbTxnReviewReqsByTripType;
        this.tmtbTxnReviewReqsByVehicleType = tmtbTxnReviewReqsByVehicleType;
        this.pmtbProductReplacements = pmtbProductReplacements;
        this.amtbContactPersonsByAddressCountry = amtbContactPersonsByAddressCountry;
        this.amtbContactPersonsByMainContactSal = amtbContactPersonsByMainContactSal;
        this.amtbContactPersonsBySubContactSal = amtbContactPersonsBySubContactSal;
        this.fmtbTransactionCodes = fmtbTransactionCodes;
        this.bmtbNotesByCancellationReason = bmtbNotesByCancellationReason;
        this.bmtbNotesByReason = bmtbNotesByReason;
        this.bmtbPaymentReceiptsByCancellationReason = bmtbPaymentReceiptsByCancellationReason;
        this.bmtbPaymentReceiptsByPaymentMode = bmtbPaymentReceiptsByPaymentMode;
        this.amtbApplicationsByEmployerCountry = amtbApplicationsByEmployerCountry;
        this.amtbApplicationsByBillingCountry = amtbApplicationsByBillingCountry;
        this.amtbApplicationsByJobStatus = amtbApplicationsByJobStatus;
        this.amtbApplicationsByShippingCountry = amtbApplicationsByShippingCountry;
        this.amtbApplicationsByAuthSal = amtbApplicationsByAuthSal;
        this.amtbApplicationsByIndustryNo = amtbApplicationsByIndustryNo;
        this.amtbApplicationsByInformationSource = amtbApplicationsByInformationSource;
        this.amtbApplicationsByAddressCountry = amtbApplicationsByAddressCountry;
        this.tmtbAcquireTxnsByTripType = tmtbAcquireTxnsByTripType;
        this.tmtbAcquireTxnsByServiceProvider = tmtbAcquireTxnsByServiceProvider;
        this.tmtbAcquireTxnsByVehicleType = tmtbAcquireTxnsByVehicleType;
        this.fmtbEntityMasters = fmtbEntityMasters;
        this.fmtbTaxCodes = fmtbTaxCodes;
        this.amtbAccountsByDefaultPaymentMode = amtbAccountsByDefaultPaymentMode;
        this.amtbAccountsByInformationSource = amtbAccountsByInformationSource;
        this.pmtbProductStatuses = pmtbProductStatuses;
        this.tmtbNonBillableTxns = tmtbNonBillableTxns;
        this.mstbAcquirerPymtTypes = mstbAcquirerPymtTypes;
        this.masterGrouping = masterGrouping;
    }
    

   
    // Property accessors

    public Integer getMasterNo() {
        return this.masterNo;
    }
    
    public void setMasterNo(Integer masterNo) {
        this.masterNo = masterNo;
    }

    public String getMasterType() {
        return this.masterType;
    }
    
    public void setMasterType(String masterType) {
        this.masterType = masterType;
    }

    public String getMasterCode() {
        return this.masterCode;
    }
    
    public void setMasterCode(String masterCode) {
        this.masterCode = masterCode;
    }

    public String getInterfaceMappingValue() {
        return this.interfaceMappingValue;
    }
    
    public void setInterfaceMappingValue(String interfaceMappingValue) {
        this.interfaceMappingValue = interfaceMappingValue;
    }

    public String getMasterValue() {
        return this.masterValue;
    }
    
    public void setMasterValue(String masterValue) {
        this.masterValue = masterValue;
    }

    public String getMasterStatus() {
        return this.masterStatus;
    }
    
    public void setMasterStatus(String masterStatus) {
        this.masterStatus = masterStatus;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public Set<AmtbCorporateDetail> getAmtbCorporateDetailsByIndustry() {
        return this.amtbCorporateDetailsByIndustry;
    }
    
    public void setAmtbCorporateDetailsByIndustry(Set<AmtbCorporateDetail> amtbCorporateDetailsByIndustry) {
        this.amtbCorporateDetailsByIndustry = amtbCorporateDetailsByIndustry;
    }

    public Set<AmtbCorporateDetail> getAmtbCorporateDetailsByAuthPersonSal() {
        return this.amtbCorporateDetailsByAuthPersonSal;
    }
    
    public void setAmtbCorporateDetailsByAuthPersonSal(Set<AmtbCorporateDetail> amtbCorporateDetailsByAuthPersonSal) {
        this.amtbCorporateDetailsByAuthPersonSal = amtbCorporateDetailsByAuthPersonSal;
    }

    public Set<AmtbCorporateDetail> getAmtbCorporateDetailsByAddressCountry() {
        return this.amtbCorporateDetailsByAddressCountry;
    }
    
    public void setAmtbCorporateDetailsByAddressCountry(Set<AmtbCorporateDetail> amtbCorporateDetailsByAddressCountry) {
        this.amtbCorporateDetailsByAddressCountry = amtbCorporateDetailsByAddressCountry;
    }

    public Set<AmtbPersonalDetail> getAmtbPersonalDetailsByIndustry() {
        return this.amtbPersonalDetailsByIndustry;
    }
    
    public void setAmtbPersonalDetailsByIndustry(Set<AmtbPersonalDetail> amtbPersonalDetailsByIndustry) {
        this.amtbPersonalDetailsByIndustry = amtbPersonalDetailsByIndustry;
    }

    public Set<AmtbPersonalDetail> getAmtbPersonalDetailsByAddressCountry() {
        return this.amtbPersonalDetailsByAddressCountry;
    }
    
    public void setAmtbPersonalDetailsByAddressCountry(Set<AmtbPersonalDetail> amtbPersonalDetailsByAddressCountry) {
        this.amtbPersonalDetailsByAddressCountry = amtbPersonalDetailsByAddressCountry;
    }

    public Set<AmtbPersonalDetail> getAmtbPersonalDetailsByEmployerCountry() {
        return this.amtbPersonalDetailsByEmployerCountry;
    }
    
    public void setAmtbPersonalDetailsByEmployerCountry(Set<AmtbPersonalDetail> amtbPersonalDetailsByEmployerCountry) {
        this.amtbPersonalDetailsByEmployerCountry = amtbPersonalDetailsByEmployerCountry;
    }

    public Set<AmtbPersonalDetail> getAmtbPersonalDetailsByJobStatus() {
        return this.amtbPersonalDetailsByJobStatus;
    }
    
    public void setAmtbPersonalDetailsByJobStatus(Set<AmtbPersonalDetail> amtbPersonalDetailsByJobStatus) {
        this.amtbPersonalDetailsByJobStatus = amtbPersonalDetailsByJobStatus;
    }

    public Set<AmtbPersonalDetail> getAmtbPersonalDetailsByRelationToParent() {
        return this.amtbPersonalDetailsByRelationToParent;
    }
    
    public void setAmtbPersonalDetailsByRelationToParent(Set<AmtbPersonalDetail> amtbPersonalDetailsByRelationToParent) {
        this.amtbPersonalDetailsByRelationToParent = amtbPersonalDetailsByRelationToParent;
    }

    public Set<AmtbAcctStatus> getAmtbAcctStatuses() {
        return this.amtbAcctStatuses;
    }
    
    public void setAmtbAcctStatuses(Set<AmtbAcctStatus> amtbAcctStatuses) {
        this.amtbAcctStatuses = amtbAcctStatuses;
    }

    public Set<TmtbTxnReviewReq> getTmtbTxnReviewReqsByServiceProvider() {
        return this.tmtbTxnReviewReqsByServiceProvider;
    }
    
    public void setTmtbTxnReviewReqsByServiceProvider(Set<TmtbTxnReviewReq> tmtbTxnReviewReqsByServiceProvider) {
        this.tmtbTxnReviewReqsByServiceProvider = tmtbTxnReviewReqsByServiceProvider;
    }

    public Set<TmtbTxnReviewReq> getTmtbTxnReviewReqsByTripType() {
        return this.tmtbTxnReviewReqsByTripType;
    }
    
    public void setTmtbTxnReviewReqsByTripType(Set<TmtbTxnReviewReq> tmtbTxnReviewReqsByTripType) {
        this.tmtbTxnReviewReqsByTripType = tmtbTxnReviewReqsByTripType;
    }

    public Set<TmtbTxnReviewReq> getTmtbTxnReviewReqsByVehicleType() {
        return this.tmtbTxnReviewReqsByVehicleType;
    }
    
    public void setTmtbTxnReviewReqsByVehicleType(Set<TmtbTxnReviewReq> tmtbTxnReviewReqsByVehicleType) {
        this.tmtbTxnReviewReqsByVehicleType = tmtbTxnReviewReqsByVehicleType;
    }

    public Set<PmtbProductReplacement> getPmtbProductReplacements() {
        return this.pmtbProductReplacements;
    }
    
    public void setPmtbProductReplacements(Set<PmtbProductReplacement> pmtbProductReplacements) {
        this.pmtbProductReplacements = pmtbProductReplacements;
    }

    public Set<AmtbContactPerson> getAmtbContactPersonsByAddressCountry() {
        return this.amtbContactPersonsByAddressCountry;
    }
    
    public void setAmtbContactPersonsByAddressCountry(Set<AmtbContactPerson> amtbContactPersonsByAddressCountry) {
        this.amtbContactPersonsByAddressCountry = amtbContactPersonsByAddressCountry;
    }

    public Set<AmtbContactPerson> getAmtbContactPersonsByMainContactSal() {
        return this.amtbContactPersonsByMainContactSal;
    }
    
    public void setAmtbContactPersonsByMainContactSal(Set<AmtbContactPerson> amtbContactPersonsByMainContactSal) {
        this.amtbContactPersonsByMainContactSal = amtbContactPersonsByMainContactSal;
    }

    public Set<AmtbContactPerson> getAmtbContactPersonsBySubContactSal() {
        return this.amtbContactPersonsBySubContactSal;
    }
    
    public void setAmtbContactPersonsBySubContactSal(Set<AmtbContactPerson> amtbContactPersonsBySubContactSal) {
        this.amtbContactPersonsBySubContactSal = amtbContactPersonsBySubContactSal;
    }

    public Set<FmtbTransactionCode> getFmtbTransactionCodes() {
        return this.fmtbTransactionCodes;
    }
    
    public void setFmtbTransactionCodes(Set<FmtbTransactionCode> fmtbTransactionCodes) {
        this.fmtbTransactionCodes = fmtbTransactionCodes;
    }

    public Set<BmtbNote> getBmtbNotesByCancellationReason() {
        return this.bmtbNotesByCancellationReason;
    }
    
    public void setBmtbNotesByCancellationReason(Set<BmtbNote> bmtbNotesByCancellationReason) {
        this.bmtbNotesByCancellationReason = bmtbNotesByCancellationReason;
    }

    public Set<BmtbNote> getBmtbNotesByReason() {
        return this.bmtbNotesByReason;
    }
    
    public void setBmtbNotesByReason(Set<BmtbNote> bmtbNotesByReason) {
        this.bmtbNotesByReason = bmtbNotesByReason;
    }

    public Set<BmtbPaymentReceipt> getBmtbPaymentReceiptsByCancellationReason() {
        return this.bmtbPaymentReceiptsByCancellationReason;
    }
    
    public void setBmtbPaymentReceiptsByCancellationReason(Set<BmtbPaymentReceipt> bmtbPaymentReceiptsByCancellationReason) {
        this.bmtbPaymentReceiptsByCancellationReason = bmtbPaymentReceiptsByCancellationReason;
    }

    public Set<BmtbPaymentReceipt> getBmtbPaymentReceiptsByPaymentMode() {
        return this.bmtbPaymentReceiptsByPaymentMode;
    }
    
    public void setBmtbPaymentReceiptsByPaymentMode(Set<BmtbPaymentReceipt> bmtbPaymentReceiptsByPaymentMode) {
        this.bmtbPaymentReceiptsByPaymentMode = bmtbPaymentReceiptsByPaymentMode;
    }

    public Set<AmtbApplication> getAmtbApplicationsByEmployerCountry() {
        return this.amtbApplicationsByEmployerCountry;
    }
    
    public void setAmtbApplicationsByEmployerCountry(Set<AmtbApplication> amtbApplicationsByEmployerCountry) {
        this.amtbApplicationsByEmployerCountry = amtbApplicationsByEmployerCountry;
    }

    public Set<AmtbApplication> getAmtbApplicationsByBillingCountry() {
        return this.amtbApplicationsByBillingCountry;
    }
    
    public void setAmtbApplicationsByBillingCountry(Set<AmtbApplication> amtbApplicationsByBillingCountry) {
        this.amtbApplicationsByBillingCountry = amtbApplicationsByBillingCountry;
    }

    public Set<AmtbApplication> getAmtbApplicationsByJobStatus() {
        return this.amtbApplicationsByJobStatus;
    }
    
    public void setAmtbApplicationsByJobStatus(Set<AmtbApplication> amtbApplicationsByJobStatus) {
        this.amtbApplicationsByJobStatus = amtbApplicationsByJobStatus;
    }

    public Set<AmtbApplication> getAmtbApplicationsByShippingCountry() {
        return this.amtbApplicationsByShippingCountry;
    }
    
    public void setAmtbApplicationsByShippingCountry(Set<AmtbApplication> amtbApplicationsByShippingCountry) {
        this.amtbApplicationsByShippingCountry = amtbApplicationsByShippingCountry;
    }

    public Set<AmtbApplication> getAmtbApplicationsByAuthSal() {
        return this.amtbApplicationsByAuthSal;
    }
    
    public void setAmtbApplicationsByAuthSal(Set<AmtbApplication> amtbApplicationsByAuthSal) {
        this.amtbApplicationsByAuthSal = amtbApplicationsByAuthSal;
    }

    public Set<AmtbApplication> getAmtbApplicationsByIndustryNo() {
        return this.amtbApplicationsByIndustryNo;
    }
    
    public void setAmtbApplicationsByIndustryNo(Set<AmtbApplication> amtbApplicationsByIndustryNo) {
        this.amtbApplicationsByIndustryNo = amtbApplicationsByIndustryNo;
    }

    public Set<AmtbApplication> getAmtbApplicationsByInformationSource() {
        return this.amtbApplicationsByInformationSource;
    }
    
    public void setAmtbApplicationsByInformationSource(Set<AmtbApplication> amtbApplicationsByInformationSource) {
        this.amtbApplicationsByInformationSource = amtbApplicationsByInformationSource;
    }

    public Set<AmtbApplication> getAmtbApplicationsByAddressCountry() {
        return this.amtbApplicationsByAddressCountry;
    }
    
    public void setAmtbApplicationsByAddressCountry(Set<AmtbApplication> amtbApplicationsByAddressCountry) {
        this.amtbApplicationsByAddressCountry = amtbApplicationsByAddressCountry;
    }

    public Set<TmtbAcquireTxn> getTmtbAcquireTxnsByTripType() {
        return this.tmtbAcquireTxnsByTripType;
    }
    
    public void setTmtbAcquireTxnsByTripType(Set<TmtbAcquireTxn> tmtbAcquireTxnsByTripType) {
        this.tmtbAcquireTxnsByTripType = tmtbAcquireTxnsByTripType;
    }

    public Set<TmtbAcquireTxn> getTmtbAcquireTxnsByServiceProvider() {
        return this.tmtbAcquireTxnsByServiceProvider;
    }
    
    public void setTmtbAcquireTxnsByServiceProvider(Set<TmtbAcquireTxn> tmtbAcquireTxnsByServiceProvider) {
        this.tmtbAcquireTxnsByServiceProvider = tmtbAcquireTxnsByServiceProvider;
    }

    public Set<TmtbAcquireTxn> getTmtbAcquireTxnsByVehicleType() {
        return this.tmtbAcquireTxnsByVehicleType;
    }
    
    public void setTmtbAcquireTxnsByVehicleType(Set<TmtbAcquireTxn> tmtbAcquireTxnsByVehicleType) {
        this.tmtbAcquireTxnsByVehicleType = tmtbAcquireTxnsByVehicleType;
    }

    public Set<FmtbEntityMaster> getFmtbEntityMasters() {
        return this.fmtbEntityMasters;
    }
    
    public void setFmtbEntityMasters(Set<FmtbEntityMaster> fmtbEntityMasters) {
        this.fmtbEntityMasters = fmtbEntityMasters;
    }

    public Set<FmtbTaxCode> getFmtbTaxCodes() {
        return this.fmtbTaxCodes;
    }
    
    public void setFmtbTaxCodes(Set<FmtbTaxCode> fmtbTaxCodes) {
        this.fmtbTaxCodes = fmtbTaxCodes;
    }

    public Set<AmtbAccount> getAmtbAccountsByDefaultPaymentMode() {
        return this.amtbAccountsByDefaultPaymentMode;
    }
    
    public void setAmtbAccountsByDefaultPaymentMode(Set<AmtbAccount> amtbAccountsByDefaultPaymentMode) {
        this.amtbAccountsByDefaultPaymentMode = amtbAccountsByDefaultPaymentMode;
    }

    public Set<AmtbAccount> getAmtbAccountsByInformationSource() {
        return this.amtbAccountsByInformationSource;
    }
    
    public void setAmtbAccountsByInformationSource(Set<AmtbAccount> amtbAccountsByInformationSource) {
        this.amtbAccountsByInformationSource = amtbAccountsByInformationSource;
    }

    public Set<PmtbProductStatus> getPmtbProductStatuses() {
        return this.pmtbProductStatuses;
    }
    
    public void setPmtbProductStatuses(Set<PmtbProductStatus> pmtbProductStatuses) {
        this.pmtbProductStatuses = pmtbProductStatuses;
    }
   
    public Set<TmtbNonBillableTxn> getTmtbNonBillableTxns() {
    	return tmtbNonBillableTxns;
    }

    public void setTmtbNonBillableTxns(Set<TmtbNonBillableTxn> tmtbNonBillableTxns) {
    	this.tmtbNonBillableTxns = tmtbNonBillableTxns;
    }   
    
    public Set<MstbAcquirerPymtType> getMstbAcquirerPymtTypes() {
    	return mstbAcquirerPymtTypes;
    }

    public void setMstbAcquirerPymtTypes(
    		Set<MstbAcquirerPymtType> mstbAcquirerPymtTypes) {
    	this.mstbAcquirerPymtTypes = mstbAcquirerPymtTypes;
    }
    
    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("masterType").append("='").append(getMasterType()).append("' ");			
      buffer.append("masterCode").append("='").append(getMasterCode()).append("' ");			
      buffer.append("interfaceMappingValue").append("='").append(getInterfaceMappingValue()).append("' ");			
      buffer.append("masterValue").append("='").append(getMasterValue()).append("' ");			
      buffer.append("masterStatus").append("='").append(getMasterStatus()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");					
      buffer.append("masterGrouping").append("='").append(getMasterGrouping()).append("' ");
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstbMasterTable) ) return false;
		 MstbMasterTable castOther = ( MstbMasterTable ) other; 
         
		 return ( (this.getMasterNo()==castOther.getMasterNo()) || ( this.getMasterNo()!=null && castOther.getMasterNo()!=null && this.getMasterNo().equals(castOther.getMasterNo()) ) )
 && ( (this.getMasterType()==castOther.getMasterType()) || ( this.getMasterType()!=null && castOther.getMasterType()!=null && this.getMasterType().equals(castOther.getMasterType()) ) )
 && ( (this.getMasterCode()==castOther.getMasterCode()) || ( this.getMasterCode()!=null && castOther.getMasterCode()!=null && this.getMasterCode().equals(castOther.getMasterCode()) ) )
 && ( (this.getInterfaceMappingValue()==castOther.getInterfaceMappingValue()) || ( this.getInterfaceMappingValue()!=null && castOther.getInterfaceMappingValue()!=null && this.getInterfaceMappingValue().equals(castOther.getInterfaceMappingValue()) ) )
 && ( (this.getMasterValue()==castOther.getMasterValue()) || ( this.getMasterValue()!=null && castOther.getMasterValue()!=null && this.getMasterValue().equals(castOther.getMasterValue()) ) )
 && ( (this.getMasterStatus()==castOther.getMasterStatus()) || ( this.getMasterStatus()!=null && castOther.getMasterStatus()!=null && this.getMasterStatus().equals(castOther.getMasterStatus()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getMasterGrouping()==castOther.getMasterGrouping()) || ( this.getMasterGrouping()!=null && castOther.getMasterGrouping()!=null && this.getMasterGrouping().equals(castOther.getMasterGrouping()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMasterNo() == null ? 0 : this.getMasterNo().hashCode() );
         result = 37 * result + ( getMasterType() == null ? 0 : this.getMasterType().hashCode() );
         result = 37 * result + ( getMasterCode() == null ? 0 : this.getMasterCode().hashCode() );
         result = 37 * result + ( getInterfaceMappingValue() == null ? 0 : this.getInterfaceMappingValue().hashCode() );
         result = 37 * result + ( getMasterValue() == null ? 0 : this.getMasterValue().hashCode() );
         result = 37 * result + ( getMasterStatus() == null ? 0 : this.getMasterStatus().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getMasterGrouping() == null ? 0 : this.getMasterGrouping().hashCode() );
         
         return result;
   }

public String getMasterGrouping() {
	return masterGrouping;
}

public void setMasterGrouping(String masterGrouping) {
	this.masterGrouping = masterGrouping;
}


}
