package com.cdgtaxi.ibs.master.model;
// Generated Mar 31, 2010 6:19:35 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Timestamp;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.common.model.Creatable;
import com.cdgtaxi.ibs.common.model.Updatable;


/**
 * MstbAcquirerPymtComm generated by hbm2java
 */

public class MstbAcquirerPymtComm implements java.io.Serializable, Creatable, Updatable, Auditable{


    // Fields    

	private Integer commissionNo;
    private Timestamp effectiveDtFrom;
    private MstbAcquirerPymtType mstbAcquirerPymtType;
    private Timestamp effectiveDtTo;
    private String commissionType;
    private BigDecimal commissionValue;
    
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;

    // Constructors

    /** default constructor */
    public MstbAcquirerPymtComm() {
    }
    
    /** full constructor */
    public MstbAcquirerPymtComm(MstbAcquirerPymtType mstbAcquirerPymtType, Timestamp effectiveDtFrom, Timestamp effectiveDtTo, String commissionType, BigDecimal commissionValue, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy) {
        this.effectiveDtFrom = effectiveDtFrom;
        this.effectiveDtTo = effectiveDtTo;
        this.mstbAcquirerPymtType = mstbAcquirerPymtType;
        this.commissionType = commissionType;
        this.commissionValue = commissionValue;
        
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
    }
    

   
    // Property accessors


    public Integer getCommissionNo() {
 		return commissionNo;
 	}

 	public void setCommissionNo(Integer commissionNo) {
 		this.commissionNo = commissionNo;
 	}

 	public MstbAcquirerPymtType getMstbAcquirerPymtType() {
 		return mstbAcquirerPymtType;
 	}

 	public void setMstbAcquirerPymtType(MstbAcquirerPymtType mstbAcquirerPymtType) {
 		this.mstbAcquirerPymtType = mstbAcquirerPymtType;
 	}

 	public Timestamp getEffectiveDtFrom() {
 		return effectiveDtFrom;
 	}

 	public void setEffectiveDtFrom(Timestamp effectiveDtFrom) {
 		this.effectiveDtFrom = effectiveDtFrom;
 	}

 	public Timestamp getEffectiveDtTo() {
 		return effectiveDtTo;
 	}

 	public void setEffectiveDtTo(Timestamp effectiveDtTo) {
 		this.effectiveDtTo = effectiveDtTo;
 	}

 	public String getCommissionType() {
 		return commissionType;
 	}

 	public void setCommissionType(String commissionType) {
 		this.commissionType = commissionType;
 	}

 	public BigDecimal getCommissionValue() {
 		return commissionValue;
 	}

 	public void setCommissionValue(BigDecimal commissionValue) {
 		this.commissionValue = commissionValue;
 	}

    public Timestamp getCreatedDt() {
		return createdDt;
	}

	public void setCreatedDt(Timestamp createdDt) {
		this.createdDt = createdDt;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Timestamp getUpdatedDt() {
		return updatedDt;
	}

	public void setUpdatedDt(Timestamp updatedDt) {
		this.updatedDt = updatedDt;
	}

	public String getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	/**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("effectiveDtFrom").append("='").append(getEffectiveDtFrom()).append("' ");			
      buffer.append("effectiveDtTo").append("='").append(getEffectiveDtTo()).append("' ");			
      buffer.append("commissionValue").append("='").append(getCommissionValue()).append("' ");			
      buffer.append("commissionType").append("='").append(getCommissionType()).append("' ");
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");		
      buffer.append("]");
      
      return buffer.toString();
     }


public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstbAcquirerPymtComm) ) return false;
		 MstbAcquirerPymtComm castOther = ( MstbAcquirerPymtComm ) other; 
         
		 return ( (this.getCommissionNo()==castOther.getCommissionNo()) || ( this.getCommissionNo()!=null && castOther.getCommissionNo()!=null && this.getCommissionNo().equals(castOther.getCommissionNo()) ) )
 && ( (this.getEffectiveDtFrom()==castOther.getEffectiveDtFrom()) || ( this.getEffectiveDtFrom()!=null && castOther.getEffectiveDtFrom()!=null && this.getEffectiveDtFrom().equals(castOther.getEffectiveDtFrom()) ) )
 && ( (this.getEffectiveDtTo()==castOther.getEffectiveDtTo()) || ( this.getEffectiveDtTo()!=null && castOther.getEffectiveDtTo()!=null && this.getEffectiveDtTo().equals(castOther.getEffectiveDtTo()) ) )
 && ( (this.getCommissionType()==castOther.getCommissionType()) || ( this.getCommissionType()!=null && castOther.getCommissionType()!=null && this.getCommissionType().equals(castOther.getCommissionType()) ) )
 && ( (this.getCommissionValue()==castOther.getCommissionValue()) || ( this.getCommissionValue()!=null && castOther.getCommissionValue()!=null && this.getCommissionValue().equals(castOther.getCommissionValue()) ) )
 && ( (this.getMstbAcquirerPymtType()==castOther.getMstbAcquirerPymtType()) || ( this.getMstbAcquirerPymtType()!=null && castOther.getMstbAcquirerPymtType()!=null && this.getMstbAcquirerPymtType().equals(castOther.getMstbAcquirerPymtType()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) ); 
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCommissionNo() == null ? 0 : this.getCommissionNo().hashCode() );
         result = 37 * result + ( getEffectiveDtFrom() == null ? 0 : this.getEffectiveDtFrom().hashCode() );
         result = 37 * result + ( getEffectiveDtTo() == null ? 0 : this.getEffectiveDtTo().hashCode() );
         result = 37 * result + ( getCommissionType() == null ? 0 : this.getCommissionType().hashCode() );
         result = 37 * result + ( getCommissionValue() == null ? 0 : this.getCommissionValue().hashCode() );
         result = 37 * result + ( getMstbAcquirerPymtType() == null ? 0 : this.getMstbAcquirerPymtType().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         return result;
   }


}
