package com.cdgtaxi.ibs.master.model;
// Generated Apr 13, 2009 6:45:39 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Timestamp;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.common.model.Creatable;
import com.cdgtaxi.ibs.common.model.Updatable;


/**
 * MstbIssuanceFeeDetail generated by hbm2java
 */

public class MstbIssuanceFeeDetail  implements java.io.Serializable, Creatable, Updatable, Auditable {


	// Fields    

    private Integer issuanceFeeDetailNo;
    private Timestamp effectiveDt;
    private BigDecimal issuanceFee;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private Integer version;
    private MstbIssuanceFeeMaster mstbIssuanceFeeMaster;


    // Constructors

    /** default constructor */
    public MstbIssuanceFeeDetail() {
    }

	/** minimal constructor */
    public MstbIssuanceFeeDetail(Timestamp effectiveDt, BigDecimal issuanceFee) {
        this.effectiveDt = effectiveDt;
        this.issuanceFee = issuanceFee;
       
    }
    
    /** full constructor */
    public MstbIssuanceFeeDetail(Timestamp effectiveDt, BigDecimal issuanceFee, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, Integer version, MstbIssuanceFeeMaster mstbIssuanceFeeMaster) {
        this.effectiveDt = effectiveDt;
        this.issuanceFee = issuanceFee;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.version = version;
        this.mstbIssuanceFeeMaster = mstbIssuanceFeeMaster;
    }
    

   
    // Property accessors

    public Integer getIssuanceFeeDetailNo() {
        return this.issuanceFeeDetailNo;
    }
    
    public void setIssuanceFeeDetailNo(Integer issuanceFeeDetailNo) {
        this.issuanceFeeDetailNo = issuanceFeeDetailNo;
    }

    public Timestamp getEffectiveDt() {
        return this.effectiveDt;
    }
    
    public void setEffectiveDt(Timestamp effectiveDt) {
        this.effectiveDt = effectiveDt;
    }

    public BigDecimal getIssuanceFee() {
        return this.issuanceFee;
    }
    
    public void setIssuanceFee(BigDecimal issuanceFee) {
        this.issuanceFee = issuanceFee;
    }
    
    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public MstbIssuanceFeeMaster getMstbIssuanceFeeMaster() {
        return this.mstbIssuanceFeeMaster;
    }
    
    public void setMstbIssuanceFeeMaster(MstbIssuanceFeeMaster mstbIssuanceFeeMaster) {
        this.mstbIssuanceFeeMaster = mstbIssuanceFeeMaster;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("effectiveDt").append("='").append(getEffectiveDt()).append("' ");			
      buffer.append("issuanceFee").append("='").append(getIssuanceFee()).append("' ");					
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstbIssuanceFeeDetail) ) return false;
		 MstbIssuanceFeeDetail castOther = ( MstbIssuanceFeeDetail ) other; 
         
		 return ( (this.getIssuanceFeeDetailNo()==castOther.getIssuanceFeeDetailNo()) || ( this.getIssuanceFeeDetailNo()!=null && castOther.getIssuanceFeeDetailNo()!=null && this.getIssuanceFeeDetailNo().equals(castOther.getIssuanceFeeDetailNo()) ) )
 && ( (this.getEffectiveDt()==castOther.getEffectiveDt()) || ( this.getEffectiveDt()!=null && castOther.getEffectiveDt()!=null && this.getEffectiveDt().equals(castOther.getEffectiveDt()) ) )
 && ( (this.getIssuanceFee()==castOther.getIssuanceFee()) || ( this.getIssuanceFee()!=null && castOther.getIssuanceFee()!=null && this.getIssuanceFee().equals(castOther.getIssuanceFee()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getMstbIssuanceFeeMaster()==castOther.getMstbIssuanceFeeMaster()) || ( this.getMstbIssuanceFeeMaster()!=null && castOther.getMstbIssuanceFeeMaster()!=null && this.getMstbIssuanceFeeMaster().equals(castOther.getMstbIssuanceFeeMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIssuanceFeeDetailNo() == null ? 0 : this.getIssuanceFeeDetailNo().hashCode() );
         result = 37 * result + ( getEffectiveDt() == null ? 0 : this.getEffectiveDt().hashCode() );
         result = 37 * result + ( getIssuanceFee() == null ? 0 : this.getIssuanceFee().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getMstbIssuanceFeeMaster() == null ? 0 : this.getMstbIssuanceFeeMaster().hashCode() );
         return result;
   }   

}
