package com.cdgtaxi.ibs.master.model;
// Generated Mar 27, 2009 6:21:31 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Timestamp;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.common.model.Creatable;
import com.cdgtaxi.ibs.common.model.Updatable;


/**
 * MstbAdminFeeDetail generated by hbm2java
 */

public class MstbAdminFeeDetail  implements java.io.Serializable, Creatable, Updatable, Auditable {


    // Fields    

    private Integer adminFeePlanDetailNo;
    private Timestamp effectiveDt;
    private BigDecimal adminFee;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private Integer version;
    private MstbAdminFeeMaster mstbAdminFeeMaster;


    // Constructors

    /** default constructor */
    public MstbAdminFeeDetail() {
    }

	/** minimal constructor */
    public MstbAdminFeeDetail(Timestamp effectiveDt, BigDecimal adminFee) {
        this.effectiveDt = effectiveDt;
        this.adminFee = adminFee;
    }
    
    /** full constructor */
    public MstbAdminFeeDetail(Timestamp effectiveDt, BigDecimal adminFee, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, Integer version, MstbAdminFeeMaster mstbAdminFeeMaster) {
        this.effectiveDt = effectiveDt;
        this.adminFee = adminFee;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.version = version;
        this.mstbAdminFeeMaster = mstbAdminFeeMaster;
    }
    

   
    // Property accessors

    public Integer getAdminFeePlanDetailNo() {
        return this.adminFeePlanDetailNo;
    }
    
    public void setAdminFeePlanDetailNo(Integer adminFeePlanDetailNo) {
        this.adminFeePlanDetailNo = adminFeePlanDetailNo;
    }

    public Timestamp getEffectiveDt() {
        return this.effectiveDt;
    }
    
    public void setEffectiveDt(Timestamp effectiveDt) {
        this.effectiveDt = effectiveDt;
    }

    public BigDecimal getAdminFee() {
        return this.adminFee;
    }
    
    public void setAdminFee(BigDecimal adminFee) {
        this.adminFee = adminFee;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public MstbAdminFeeMaster getMstbAdminFeeMaster() {
        return this.mstbAdminFeeMaster;
    }
    
    public void setMstbAdminFeeMaster(MstbAdminFeeMaster mstbAdminFeeMaster) {
        this.mstbAdminFeeMaster = mstbAdminFeeMaster;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("effectiveDt").append("='").append(getEffectiveDt()).append("' ");			
      buffer.append("adminFee").append("='").append(getAdminFee()).append("' ");
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstbAdminFeeDetail) ) return false;
		 MstbAdminFeeDetail castOther = ( MstbAdminFeeDetail ) other; 
         
		 return ( (this.getAdminFeePlanDetailNo()==castOther.getAdminFeePlanDetailNo()) || ( this.getAdminFeePlanDetailNo()!=null && castOther.getAdminFeePlanDetailNo()!=null && this.getAdminFeePlanDetailNo().equals(castOther.getAdminFeePlanDetailNo()) ) )
 && ( (this.getEffectiveDt()==castOther.getEffectiveDt()) || ( this.getEffectiveDt()!=null && castOther.getEffectiveDt()!=null && this.getEffectiveDt().equals(castOther.getEffectiveDt()) ) )
 && ( (this.getAdminFee()==castOther.getAdminFee()) || ( this.getAdminFee()!=null && castOther.getAdminFee()!=null && this.getAdminFee().equals(castOther.getAdminFee()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getMstbAdminFeeMaster()==castOther.getMstbAdminFeeMaster()) || ( this.getMstbAdminFeeMaster()!=null && castOther.getMstbAdminFeeMaster()!=null && this.getMstbAdminFeeMaster().equals(castOther.getMstbAdminFeeMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAdminFeePlanDetailNo() == null ? 0 : this.getAdminFeePlanDetailNo().hashCode() );
         result = 37 * result + ( getEffectiveDt() == null ? 0 : this.getEffectiveDt().hashCode() );
         result = 37 * result + ( getAdminFee() == null ? 0 : this.getAdminFee().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getMstbAdminFeeMaster() == null ? 0 : this.getMstbAdminFeeMaster().hashCode() );
         return result;
   }   





}
