package com.cdgtaxi.ibs.master.model;
// Generated Mar 27, 2009 6:21:30 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Timestamp;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.common.model.Creatable;
import com.cdgtaxi.ibs.common.model.Updatable;


/**
 * MstbEarlyPaymentDetail generated by hbm2java
 */

public class MstbEarlyPaymentDetail  implements java.io.Serializable, Creatable, Updatable, Auditable {


    // Fields    

    private Integer earlyPaymentPlanDetailNo;
    private Timestamp effectiveDt;
    private BigDecimal earlyPayment;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private Integer version;
    private MstbEarlyPaymentMaster mstbEarlyPaymentMaster;


    // Constructors

    /** default constructor */
    public MstbEarlyPaymentDetail() {
    }

	/** minimal constructor */
    public MstbEarlyPaymentDetail(Timestamp effectiveDt, BigDecimal earlyPayment) {
        this.effectiveDt = effectiveDt;
        this.earlyPayment = earlyPayment;
    }
    
    /** full constructor */
    public MstbEarlyPaymentDetail(Timestamp effectiveDt, BigDecimal earlyPayment, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, Integer version, MstbEarlyPaymentMaster mstbEarlyPaymentMaster) {
        this.effectiveDt = effectiveDt;
        this.earlyPayment = earlyPayment;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.version = version;
        this.mstbEarlyPaymentMaster = mstbEarlyPaymentMaster;
    }
    

   
    // Property accessors

    public Integer getEarlyPaymentPlanDetailNo() {
        return this.earlyPaymentPlanDetailNo;
    }
    
    public void setEarlyPaymentPlanDetailNo(Integer earlyPaymentPlanDetailNo) {
        this.earlyPaymentPlanDetailNo = earlyPaymentPlanDetailNo;
    }

    public Timestamp getEffectiveDt() {
        return this.effectiveDt;
    }
    
    public void setEffectiveDt(Timestamp effectiveDt) {
        this.effectiveDt = effectiveDt;
    }

    public BigDecimal getEarlyPayment() {
        return this.earlyPayment;
    }
    
    public void setEarlyPayment(BigDecimal earlyPayment) {
        this.earlyPayment = earlyPayment;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public MstbEarlyPaymentMaster getMstbEarlyPaymentMaster() {
        return this.mstbEarlyPaymentMaster;
    }
    
    public void setMstbEarlyPaymentMaster(MstbEarlyPaymentMaster mstbEarlyPaymentMaster) {
        this.mstbEarlyPaymentMaster = mstbEarlyPaymentMaster;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("effectiveDt").append("='").append(getEffectiveDt()).append("' ");			
      buffer.append("earlyPayment").append("='").append(getEarlyPayment()).append("' ");
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstbEarlyPaymentDetail) ) return false;
		 MstbEarlyPaymentDetail castOther = ( MstbEarlyPaymentDetail ) other; 
         
		 return ( (this.getEarlyPaymentPlanDetailNo()==castOther.getEarlyPaymentPlanDetailNo()) || ( this.getEarlyPaymentPlanDetailNo()!=null && castOther.getEarlyPaymentPlanDetailNo()!=null && this.getEarlyPaymentPlanDetailNo().equals(castOther.getEarlyPaymentPlanDetailNo()) ) )
 && ( (this.getEffectiveDt()==castOther.getEffectiveDt()) || ( this.getEffectiveDt()!=null && castOther.getEffectiveDt()!=null && this.getEffectiveDt().equals(castOther.getEffectiveDt()) ) )
 && ( (this.getEarlyPayment()==castOther.getEarlyPayment()) || ( this.getEarlyPayment()!=null && castOther.getEarlyPayment()!=null && this.getEarlyPayment().equals(castOther.getEarlyPayment()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getMstbEarlyPaymentMaster()==castOther.getMstbEarlyPaymentMaster()) || ( this.getMstbEarlyPaymentMaster()!=null && castOther.getMstbEarlyPaymentMaster()!=null && this.getMstbEarlyPaymentMaster().equals(castOther.getMstbEarlyPaymentMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getEarlyPaymentPlanDetailNo() == null ? 0 : this.getEarlyPaymentPlanDetailNo().hashCode() );
         result = 37 * result + ( getEffectiveDt() == null ? 0 : this.getEffectiveDt().hashCode() );
         result = 37 * result + ( getEarlyPayment() == null ? 0 : this.getEarlyPayment().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getMstbEarlyPaymentMaster() == null ? 0 : this.getMstbEarlyPaymentMaster().hashCode() );
         return result;
   }   

}
