package com.cdgtaxi.ibs.master.model;
// Generated Jul 20, 2009 6:36:49 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.common.model.AmtbAccount;
import com.cdgtaxi.ibs.common.model.AmtbBillReq;
import com.cdgtaxi.ibs.common.model.BmtbPaymentReceipt;
import com.cdgtaxi.ibs.common.model.Creatable;
import com.cdgtaxi.ibs.common.model.Updatable;


/**
 * MstbBankMaster generated by hbm2java
 */

public class MstbBankMaster  implements java.io.Serializable, Creatable, Updatable, Auditable {


    // Fields    

    private Integer bankMasterNo;
    private String bankName;
    private String bankCode;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private Integer version;
    private Set<BmtbPaymentReceipt> bmtbPaymentReceipts = new HashSet<BmtbPaymentReceipt>(0);
    private Set<MstbBranchMaster> mstbBranchMasters = new HashSet<MstbBranchMaster>(0);
    private Set<AmtbBillReq> amtbBillReqs = new HashSet<AmtbBillReq>(0);
    private Set<AmtbAccount> amtbAccounts = new HashSet<AmtbAccount>(0);


    // Constructors

    /** default constructor */
    public MstbBankMaster() {
    }

	/** minimal constructor */
    public MstbBankMaster(String bankName, String bankCode) {
        this.bankName = bankName;
        this.bankCode = bankCode;
    }
    
    /** full constructor */
    public MstbBankMaster(String bankName, String bankCode, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, Integer version, Set<BmtbPaymentReceipt> bmtbPaymentReceipts, Set<MstbBranchMaster> mstbBranchMasters, Set<AmtbBillReq> amtbBillReqs, Set<AmtbAccount> amtbAccounts) {
        this.bankName = bankName;
        this.bankCode = bankCode;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.version = version;
        this.bmtbPaymentReceipts = bmtbPaymentReceipts;
        this.mstbBranchMasters = mstbBranchMasters;
        this.amtbBillReqs = amtbBillReqs;
        this.amtbAccounts = amtbAccounts;
    }
    

   
    // Property accessors

    public Integer getBankMasterNo() {
        return this.bankMasterNo;
    }
    
    public void setBankMasterNo(Integer bankMasterNo) {
        this.bankMasterNo = bankMasterNo;
    }

    public String getBankName() {
        return this.bankName;
    }
    
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    public String getBankCode() {
        return this.bankCode;
    }
    
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public Set<BmtbPaymentReceipt> getBmtbPaymentReceipts() {
        return this.bmtbPaymentReceipts;
    }
    
    public void setBmtbPaymentReceipts(Set<BmtbPaymentReceipt> bmtbPaymentReceipts) {
        this.bmtbPaymentReceipts = bmtbPaymentReceipts;
    }

    public Set<MstbBranchMaster> getMstbBranchMasters() {
        return this.mstbBranchMasters;
    }
    
    public void setMstbBranchMasters(Set<MstbBranchMaster> mstbBranchMasters) {
        this.mstbBranchMasters = mstbBranchMasters;
    }

    public Set<AmtbBillReq> getAmtbBillReqs() {
        return this.amtbBillReqs;
    }
    
    public void setAmtbBillReqs(Set<AmtbBillReq> amtbBillReqs) {
        this.amtbBillReqs = amtbBillReqs;
    }

    public Set<AmtbAccount> getAmtbAccounts() {
        return this.amtbAccounts;
    }
    
    public void setAmtbAccounts(Set<AmtbAccount> amtbAccounts) {
        this.amtbAccounts = amtbAccounts;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("bankName").append("='").append(getBankName()).append("' ");			
      buffer.append("bankCode").append("='").append(getBankCode()).append("' ");		
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstbBankMaster) ) return false;
		 MstbBankMaster castOther = ( MstbBankMaster ) other; 
         
		 return ( (this.getBankMasterNo()==castOther.getBankMasterNo()) || ( this.getBankMasterNo()!=null && castOther.getBankMasterNo()!=null && this.getBankMasterNo().equals(castOther.getBankMasterNo()) ) )
 && ( (this.getBankName()==castOther.getBankName()) || ( this.getBankName()!=null && castOther.getBankName()!=null && this.getBankName().equals(castOther.getBankName()) ) )
 && ( (this.getBankCode()==castOther.getBankCode()) || ( this.getBankCode()!=null && castOther.getBankCode()!=null && this.getBankCode().equals(castOther.getBankCode()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBankMasterNo() == null ? 0 : this.getBankMasterNo().hashCode() );
         result = 37 * result + ( getBankName() == null ? 0 : this.getBankName().hashCode() );
         result = 37 * result + ( getBankCode() == null ? 0 : this.getBankCode().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         return result;
   }   

}
