package com.cdgtaxi.ibs.master.model;
// Generated Apr 30, 2010 3:43:15 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.common.model.Creatable;
import com.cdgtaxi.ibs.common.model.Updatable;


/**
 * MstbAcquirerMdr generated by hbm2java
 */

public class MstbAcquirerMdr  implements java.io.Serializable, Auditable, Creatable, Updatable {


    // Fields    

    private Integer mdrNo;
    private Date effectiveDate;
    private BigDecimal rate;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private Integer version;
    private MstbAcquirer mstbAcquirer;


    // Constructors

    /** default constructor */
    public MstbAcquirerMdr() {
    }

	/** minimal constructor */
    public MstbAcquirerMdr(Date effectiveDate, BigDecimal rate) {
        this.effectiveDate = effectiveDate;
        this.rate = rate;
    }
    
    /** full constructor */
    public MstbAcquirerMdr(Date effectiveDate, BigDecimal rate, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, Integer version, MstbAcquirer mstbAcquirer) {
        this.effectiveDate = effectiveDate;
        this.rate = rate;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.version = version;
        this.mstbAcquirer = mstbAcquirer;
    }
    

   
    // Property accessors

    public Integer getMdrNo() {
        return this.mdrNo;
    }
    
    public void setMdrNo(Integer mdrNo) {
        this.mdrNo = mdrNo;
    }

    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    public BigDecimal getRate() {
        return this.rate;
    }
    
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public MstbAcquirer getMstbAcquirer() {
        return this.mstbAcquirer;
    }
    
    public void setMstbAcquirer(MstbAcquirer mstbAcquirer) {
        this.mstbAcquirer = mstbAcquirer;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("effectiveDate").append("='").append(getEffectiveDate()).append("' ");			
      buffer.append("rate").append("='").append(getRate()).append("' ");			
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstbAcquirerMdr) ) return false;
		 MstbAcquirerMdr castOther = ( MstbAcquirerMdr ) other; 
         
		 return ( (this.getMdrNo()==castOther.getMdrNo()) || ( this.getMdrNo()!=null && castOther.getMdrNo()!=null && this.getMdrNo().equals(castOther.getMdrNo()) ) )
 && ( (this.getEffectiveDate()==castOther.getEffectiveDate()) || ( this.getEffectiveDate()!=null && castOther.getEffectiveDate()!=null && this.getEffectiveDate().equals(castOther.getEffectiveDate()) ) )
 && ( (this.getRate()==castOther.getRate()) || ( this.getRate()!=null && castOther.getRate()!=null && this.getRate().equals(castOther.getRate()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getMstbAcquirer()==castOther.getMstbAcquirer()) || ( this.getMstbAcquirer()!=null && castOther.getMstbAcquirer()!=null && this.getMstbAcquirer().equals(castOther.getMstbAcquirer()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMdrNo() == null ? 0 : this.getMdrNo().hashCode() );
         result = 37 * result + ( getEffectiveDate() == null ? 0 : this.getEffectiveDate().hashCode() );
         result = 37 * result + ( getRate() == null ? 0 : this.getRate().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getMstbAcquirer() == null ? 0 : this.getMstbAcquirer().hashCode() );
         return result;
   }   





}
