package com.cdgtaxi.ibs.interfaces.as.model;
// Generated Oct 13, 2008 9:51:24 AM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;


/**
 * NegativeList generated by hbm2java
 */

public class AsvwNegativeList implements java.io.Serializable {


	// Fields    

    private String cardNo;
    private Timestamp createDate;
    private String createBy;


    // Constructors

    /** default constructor */
    public AsvwNegativeList() {
    }

    
    /** full constructor */
    public AsvwNegativeList(Timestamp createDate, String createBy) {
        this.createDate = createDate;
        this.createBy = createBy;
    }
    

   
    // Property accessors

    public String getCardNo() {
        return this.cardNo;
    }
    
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    public Timestamp getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Timestamp createDate) {
        this.createDate = createDate;
    }

    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("createDate").append("='").append(getCreateDate()).append("' ");			
      buffer.append("createBy").append("='").append(getCreateBy()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AsvwNegativeList) ) return false;
		 AsvwNegativeList castOther = ( AsvwNegativeList ) other; 
         
		 return ( (this.getCardNo()==castOther.getCardNo()) || ( this.getCardNo()!=null && castOther.getCardNo()!=null && this.getCardNo().equals(castOther.getCardNo()) ) )
 && ( (this.getCreateDate()==castOther.getCreateDate()) || ( this.getCreateDate()!=null && castOther.getCreateDate()!=null && this.getCreateDate().equals(castOther.getCreateDate()) ) )
 && ( (this.getCreateBy()==castOther.getCreateBy()) || ( this.getCreateBy()!=null && castOther.getCreateBy()!=null && this.getCreateBy().equals(castOther.getCreateBy()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCardNo() == null ? 0 : this.getCardNo().hashCode() );
         result = 37 * result + ( getCreateDate() == null ? 0 : this.getCreateDate().hashCode() );
         result = 37 * result + ( getCreateBy() == null ? 0 : this.getCreateBy().hashCode() );
         return result;
   }   
}
