package com.cdgtaxi.ibs.interfaces.as.model;
// Generated Jul 23, 2009 3:32:46 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;


/**
 * IttbAsMasterReq generated by hbm2java
 */

public class IttbAsMasterReq  implements java.io.Serializable {


    // Fields    

    private String reqId;
    private String reqTable;
    private String reqStatus;
    private Timestamp reqDate;
    private IttbAsUpdBillAcctReq ittbAsUpdBillAcctReq;
    private IttbAsAddAcctReq ittbAsAddAcctReq;
    private IttbAsRevAcctTxnReq ittbAsRevAcctTxnReq;
    private IttbAsUpdUsageReq ittbAsUpdUsageReq;
    private IttbAsUpdAcctReq ittbAsUpdAcctReq;
    private IttbAsRevProdTxnReq ittbAsRevProdTxnReq;
    private IttbAsUpdPayAcctReq ittbAsUpdPayAcctReq;
    private IttbAsAddNegProdReq ittbAsAddNegProdReq;
    private IttbAsUpdProdReq ittbAsUpdProdReq;
    private IttbAsUpdPayProdReq ittbAsUpdPayProdReq;
    private IttbAsUpdBillProdReq ittbAsUpdBillProdReq;
    private IttbAsAddProdReq ittbAsAddProdReq;


    /** Constant Field **/
    //reqStatus
    public static final String COMPLETED 	= "C";
	public static final String PENDING 		= "P";
	public static final String ERROR 		= "E";
	
	//reqTable
	public static final String CREATE_PRODUCT_REQUEST 			= "ITTB_AS_ADD_PROD_REQ";
	public static final String UPDATE_PRODUCT_REQUEST 			= "ITTB_AS_UPD_PROD_REQ";
	public static final String UPDATE_PROD_BILLING_REQUEST 		= "ITTB_AS_UPD_BILL_PROD_REQ";
	public static final String UPDATE_PROD_PAYMENT_REQUEST 		= "ITTB_AS_UPD_PAY_PROD_REQ";
	public static final String CREATE_ACCOUNT_REQUEST 			= "ITTB_AS_ADD_ACCT_REQ";
	public static final String UPDATE_ACCT_BILLING_REQUEST 		= "ITTB_AS_UPD_BILL_ACCT_REQ";
	public static final String UPDATE_ACCT_PAYMENT_REQUEST 		= "ITTB_AS_UPD_PAY_ACCT_REQ";
	public static final String CREATE_NEG_PROD_REQUEST 			= "ITTB_AS_ADD_NEG_PROD_REQ";
	public static final String REVERSAL_TXN_REQUEST 			= "ITTB_AS_REV_PROD_TXN_REQ";
	public static final String REVERSAL_TXN_FOR_ACCT_REQUEST 	= "ITTB_AS_REV_ACCT_TXN_REQ";
	public static final String UPDATE_ACCOUNT_REQUEST 			= "ITTB_AS_UPD_ACCT_REQ";
	public static final String UPDATE_PRODUCT_USAGE_REQUEST 	= "ITTB_AS_UPD_USAGE_REQ";
	
    // Constructors

    /** default constructor */
    public IttbAsMasterReq() {
    }

	/** minimal constructor */
    public IttbAsMasterReq(String reqTable, String reqStatus) {
        this.reqTable = reqTable;
        this.reqStatus = reqStatus;
    }
    
    /** full constructor */
    public IttbAsMasterReq(String reqTable, String reqStatus, Timestamp reqDate, IttbAsUpdBillAcctReq ittbAsUpdBillAcctReq, IttbAsAddAcctReq ittbAsAddAcctReq, IttbAsRevAcctTxnReq ittbAsRevAcctTxnReq, IttbAsUpdUsageReq ittbAsUpdUsageReq, IttbAsUpdAcctReq ittbAsUpdAcctReq, IttbAsRevProdTxnReq ittbAsRevProdTxnReq, IttbAsUpdPayAcctReq ittbAsUpdPayAcctReq, IttbAsAddNegProdReq ittbAsAddNegProdReq, IttbAsUpdProdReq ittbAsUpdProdReq, IttbAsUpdPayProdReq ittbAsUpdPayProdReq, IttbAsUpdBillProdReq ittbAsUpdBillProdReq, IttbAsAddProdReq ittbAsAddProdReq) {
        this.reqTable = reqTable;
        this.reqStatus = reqStatus;
        this.reqDate = reqDate;
        this.ittbAsUpdBillAcctReq = ittbAsUpdBillAcctReq;
        this.ittbAsAddAcctReq = ittbAsAddAcctReq;
        this.ittbAsRevAcctTxnReq = ittbAsRevAcctTxnReq;
        this.ittbAsUpdUsageReq = ittbAsUpdUsageReq;
        this.ittbAsUpdAcctReq = ittbAsUpdAcctReq;
        this.ittbAsRevProdTxnReq = ittbAsRevProdTxnReq;
        this.ittbAsUpdPayAcctReq = ittbAsUpdPayAcctReq;
        this.ittbAsAddNegProdReq = ittbAsAddNegProdReq;
        this.ittbAsUpdProdReq = ittbAsUpdProdReq;
        this.ittbAsUpdPayProdReq = ittbAsUpdPayProdReq;
        this.ittbAsUpdBillProdReq = ittbAsUpdBillProdReq;
        this.ittbAsAddProdReq = ittbAsAddProdReq;
    }
    

   
    // Property accessors

    public String getReqId() {
        return this.reqId;
    }
    
    public void setReqId(String reqId) {
        this.reqId = reqId;
    }

    public String getReqTable() {
        return this.reqTable;
    }
    
    public void setReqTable(String reqTable) {
        this.reqTable = reqTable;
    }

    public String getReqStatus() {
        return this.reqStatus;
    }
    
    public void setReqStatus(String reqStatus) {
        this.reqStatus = reqStatus;
    }

    public Timestamp getReqDate() {
        return this.reqDate;
    }
    
    public void setReqDate(Timestamp reqDate) {
        this.reqDate = reqDate;
    }

    public IttbAsUpdBillAcctReq getIttbAsUpdBillAcctReq() {
        return this.ittbAsUpdBillAcctReq;
    }
    
    public void setIttbAsUpdBillAcctReq(IttbAsUpdBillAcctReq ittbAsUpdBillAcctReq) {
        this.ittbAsUpdBillAcctReq = ittbAsUpdBillAcctReq;
    }

    public IttbAsAddAcctReq getIttbAsAddAcctReq() {
        return this.ittbAsAddAcctReq;
    }
    
    public void setIttbAsAddAcctReq(IttbAsAddAcctReq ittbAsAddAcctReq) {
        this.ittbAsAddAcctReq = ittbAsAddAcctReq;
    }

    public IttbAsRevAcctTxnReq getIttbAsRevAcctTxnReq() {
        return this.ittbAsRevAcctTxnReq;
    }
    
    public void setIttbAsRevAcctTxnReq(IttbAsRevAcctTxnReq ittbAsRevAcctTxnReq) {
        this.ittbAsRevAcctTxnReq = ittbAsRevAcctTxnReq;
    }

    public IttbAsUpdUsageReq getIttbAsUpdUsageReq() {
        return this.ittbAsUpdUsageReq;
    }
    
    public void setIttbAsUpdUsageReq(IttbAsUpdUsageReq ittbAsUpdUsageReq) {
        this.ittbAsUpdUsageReq = ittbAsUpdUsageReq;
    }

    public IttbAsUpdAcctReq getIttbAsUpdAcctReq() {
        return this.ittbAsUpdAcctReq;
    }
    
    public void setIttbAsUpdAcctReq(IttbAsUpdAcctReq ittbAsUpdAcctReq) {
        this.ittbAsUpdAcctReq = ittbAsUpdAcctReq;
    }

    public IttbAsRevProdTxnReq getIttbAsRevProdTxnReq() {
        return this.ittbAsRevProdTxnReq;
    }
    
    public void setIttbAsRevProdTxnReq(IttbAsRevProdTxnReq ittbAsRevProdTxnReq) {
        this.ittbAsRevProdTxnReq = ittbAsRevProdTxnReq;
    }

    public IttbAsUpdPayAcctReq getIttbAsUpdPayAcctReq() {
        return this.ittbAsUpdPayAcctReq;
    }
    
    public void setIttbAsUpdPayAcctReq(IttbAsUpdPayAcctReq ittbAsUpdPayAcctReq) {
        this.ittbAsUpdPayAcctReq = ittbAsUpdPayAcctReq;
    }

    public IttbAsAddNegProdReq getIttbAsAddNegProdReq() {
        return this.ittbAsAddNegProdReq;
    }
    
    public void setIttbAsAddNegProdReq(IttbAsAddNegProdReq ittbAsAddNegProdReq) {
        this.ittbAsAddNegProdReq = ittbAsAddNegProdReq;
    }

    public IttbAsUpdProdReq getIttbAsUpdProdReq() {
        return this.ittbAsUpdProdReq;
    }
    
    public void setIttbAsUpdProdReq(IttbAsUpdProdReq ittbAsUpdProdReq) {
        this.ittbAsUpdProdReq = ittbAsUpdProdReq;
    }

    public IttbAsUpdPayProdReq getIttbAsUpdPayProdReq() {
        return this.ittbAsUpdPayProdReq;
    }
    
    public void setIttbAsUpdPayProdReq(IttbAsUpdPayProdReq ittbAsUpdPayProdReq) {
        this.ittbAsUpdPayProdReq = ittbAsUpdPayProdReq;
    }

    public IttbAsUpdBillProdReq getIttbAsUpdBillProdReq() {
        return this.ittbAsUpdBillProdReq;
    }
    
    public void setIttbAsUpdBillProdReq(IttbAsUpdBillProdReq ittbAsUpdBillProdReq) {
        this.ittbAsUpdBillProdReq = ittbAsUpdBillProdReq;
    }

    public IttbAsAddProdReq getIttbAsAddProdReq() {
        return this.ittbAsAddProdReq;
    }
    
    public void setIttbAsAddProdReq(IttbAsAddProdReq ittbAsAddProdReq) {
        this.ittbAsAddProdReq = ittbAsAddProdReq;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("reqTable").append("='").append(getReqTable()).append("' ");			
      buffer.append("reqStatus").append("='").append(getReqStatus()).append("' ");			
      buffer.append("reqDate").append("='").append(getReqDate()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IttbAsMasterReq) ) return false;
		 IttbAsMasterReq castOther = ( IttbAsMasterReq ) other; 
         
		 return ( (this.getReqId()==castOther.getReqId()) || ( this.getReqId()!=null && castOther.getReqId()!=null && this.getReqId().equals(castOther.getReqId()) ) )
 && ( (this.getReqTable()==castOther.getReqTable()) || ( this.getReqTable()!=null && castOther.getReqTable()!=null && this.getReqTable().equals(castOther.getReqTable()) ) )
 && ( (this.getReqStatus()==castOther.getReqStatus()) || ( this.getReqStatus()!=null && castOther.getReqStatus()!=null && this.getReqStatus().equals(castOther.getReqStatus()) ) )
 && ( (this.getReqDate()==castOther.getReqDate()) || ( this.getReqDate()!=null && castOther.getReqDate()!=null && this.getReqDate().equals(castOther.getReqDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getReqId() == null ? 0 : this.getReqId().hashCode() );
         result = 37 * result + ( getReqTable() == null ? 0 : this.getReqTable().hashCode() );
         result = 37 * result + ( getReqStatus() == null ? 0 : this.getReqStatus().hashCode() );
         result = 37 * result + ( getReqDate() == null ? 0 : this.getReqDate().hashCode() );
         
         
         
         
         
         
         
         
         
         
         
         
         return result;
   }   





}
