--GIRO RETURN REQUEST
create TABLE ITTB_GIRO_RETURN_REQ
(
   REQ_NO number(18) PRIMARY KEY NOT NULL,
   UOB_HEADER_NO number(18),
   PROCESSING_DATE date NOT NULL,
   PROCESSING_TIME number(2) NOT NULL,
   STATUS varchar2(1) NOT NULL,
   VERSION number(8) DEFAULT 0,
   CREATED_BY varchar2(80),
   CREATED_DT timestamp,
   UPDATED_BY varchar2(80),
   UPDATED_DT timestamp
);
CREATE INDEX ITTB_GIRO_RETURN_REQ_N1 ON ITTB_GIRO_RETURN_REQ(PROCESSING_DATE, PROCESSING_TIME, STATUS);
ALTER TABLE ITTB_GIRO_RETURN_REQ ADD CONSTRAINT ITTB_GIRO_RETURN_REQ_FK1 FOREIGN KEY (UOB_HEADER_NO) REFERENCES ITTB_GIRO_UOB_HEADER (UOB_HEADER_NO) ENABLE;
create SEQUENCE ITTB_GIRO_RETURN_REQ_SQ1 MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;

--GIRO Rejection Codes
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '00' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'ACCEPTED' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '10' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'INVALID RECEIVING A/C NO.' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '20' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'ERROR IN RECEIVING BANK CODE' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '21' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'ERROR IN RECEIVING BRANCH CODE' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '30' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'AMOUNT EXCEEDED' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '31' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'ERROR IN AMOUNT' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '40' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'NO DDA (Direct Debit Authorisation)' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '41' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'DDA TERMINATED' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '42' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'INVALID ORIGINATING A/C NO.' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '43' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'ERROR IN ORIGINATING BANK CODE' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '44' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'NON-ORIGINATING BANK CODE' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '45' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'ERROR IN ORIGINATING BRANCH CODE' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '46' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'UNMATCHED REFERENCE NO.' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '47' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'REFERENCE NO. MISSING' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '50' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'REFER PAYING PARTY' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '51' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'EFFECTS NOT CLEARED' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '60' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'ACCOUNT CLOSED' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '61' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'ACCOUNT DOES NOT EXIST' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '70' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'ERROR IN TRANS CODE' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '71' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'ERROR IN RECORD LENGTH' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '72' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'INVALID RECORD TYPE' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '73' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'INVALID SACH CODE' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '74' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'DUPLICATE SACH CODE' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '75' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'INVALID RETURN CODE' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '76' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'RETURN REASON MISSING' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GURC' as MASTER_TYPE, '90' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'ANY OTHER REASONS' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GIRC' as MASTER_TYPE, '100' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'GIRO AMOUNT SENT FOR DEDUCTION IS DIFFERENT FROM GIRO AMOUNT DEDUCTED FROM RETURN FILE' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;
insert into MSTB_MASTER_TABLE select MSTB_MASTER_TABLE_SQ1.nextVal as MASTER_NO, 'GIRC' as MASTER_TYPE, '101' as MASTER_CODE, null as INTERFACE_MAPPING_VALUE, 'INVOICE DETAIL''S OUTSTANDING AMOUNT HAS CHANGED' as MASTER_VALUE, 'A' as MASTER_STATUS, 0 as VERSION from dual;

--giro return request screens
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (479,476,'Upload Giro Return File','U','/admin/giro_interface/upload_giro_return_file.zul',7,'Upload Giro Return File','Y',0);
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (480,476,'Manager Giro Return Request','U','/admin/giro_interface/manage_giro_return_request.zul',8,'Manager Giro Return Request','Y',0);
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (481,476,'View Giro Return Request','U','/admin/giro_interface/view_giro_return_request.zul',9,'View Giro Return Request','N',0);
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (482,476,'Delete Giro Return Request','U','Delete Giro Return Request',10,'Delete Giro Return Request','N',0);
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (483,476,'Edit Giro Return Request','U','/admin/giro_interface/edit_giro_return_request.zul',11,'Edit Giro Return Request','N',0);

--To be executed once
/*
ALTER tabLE ITTB_GIRO_UOB_DETAIL ADD(
	PARTICULARS varchar2(12) NOT NULL,
	REFERENCE varchar2(12) NOT NULL
);
CREATE INDEX ITTB_GIRO_UOB_DETAIL_N1 ON ITTB_GIRO_UOB_DETAIL(PARTICULARS, REFERENCE);

Alter TABLE ITTB_GIRO_UOB_HEADER add(
	bank_code_no number(8) not null
);
ALTER TABLE ITTB_GIRO_UOB_HEADER ADD CONSTRAINT ITTB_GIRO_UOB_HEADER_FK2 FOREIGN KEY (BANK_CODE_NO) REFERENCES FMTB_BANK_CODE (BANK_CODE_NO) ENABLE;
*/