/* ********************
 * UOB Giro Interface
 * ********************/
alter table Fmtb_Bank_Code add(
	IS_DEFAULT_GIRO_BANK char(1) default 'N' not null,
	BANK_ACCT_NAME VARCHAR2(80) default ' ' not null
);
 
create TABLE ITTB_GIRO_SETUP
(
   SETUP_NO number(8) PRIMARY KEY NOT NULL,
   ENTITY_NO number(8) NOT NULL,
   CUT_OFF_DAY number(2) NOT NULL,
   REQUEST_DAY number(2) NOT NULL,
   REQUEST_TIME number(2) NOT NULL,
   VALUE_DAY number(2) NOT NULL,
   INVOICE_GIRO_DAY number(2) NOT NULL,
   VERSION number(9) DEFAULT 0,
   CREATED_BY varchar2(80),
   CREATED_DT timestamp,
   UPDATED_BY varchar2(80),
   UPDATED_DT timestamp
);
CREATE INDEX ITTB_GIRO_SETUP_N1 ON ITTB_GIRO_SETUP(ENTITY_NO);
ALTER TABLE ITTB_GIRO_SETUP ADD CONSTRAINT ITTB_GIRO_SETUP_FK1 FOREIGN KEY (ENTITY_NO) REFERENCES FMTB_ENTITY_MASTER (ENTITY_NO) ENABLE;
create SEQUENCE ITTB_GIRO_SETUP_SQ1 MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;

create TABLE ITTB_GIRO_REQ
(
   REQ_NO number(18) PRIMARY KEY NOT NULL,
   SETUP_NO number(8) NOT NULL,
   REQUEST_DATE date NOT NULL,
   REQUEST_TIME number(2) NOT NULL,
   VALUE_DATE date NOT NULL,
   CUTOFF_DATE date NOT NULL,
   STATUS varchar2(1) NOT NULL,
   VERSION number(8) DEFAULT 0,
   CREATED_BY varchar2(80),
   CREATED_DT timestamp,
   UPDATED_BY varchar2(80),
   UPDATED_DT timestamp
);
CREATE INDEX ITTB_GIRO_REQ_N1 ON ITTB_GIRO_REQ(REQUEST_DATE, REQUEST_TIME, STATUS);
ALTER TABLE ITTB_GIRO_REQ ADD CONSTRAINT ITTB_GIRO_REQ_FK1 FOREIGN KEY (SETUP_NO) REFERENCES ITTB_GIRO_SETUP (SETUP_NO) ENABLE;
create SEQUENCE ITTB_GIRO_REQ_SQ1 MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;

CREATE TABLE ITTB_GIRO_UOB_HEADER(
	UOB_HEADER_NO number(18) PRIMARY KEY NOT NULL,
	REQ_NO number(18) NOT NULL,
	BANK_CODE_NO number(8) not null,
	VALUE_DATE date not null,
	GENERATION_DATE date not null,
	UPLOAD_DATE date,
	GIRO_FILE_NAME varchar2(10) not null,
	RETURN_FILE_NAME varchar2(11),
	OUTGOING_COUNT number(18) not null,
	OUTGOING_AMOUNT number(12,2) not null,
	INCOMING_SUCCESS_COUNT number(18),
	INCOMING_SUCCESS_AMOUNT number(12,2),
	INCOMING_REJECTED_COUNT number(18),
	INCOMING_REJECTED_AMOUNT number(12,2),
	VERSION number(9) DEFAULT 0,
	CREATED_BY varchar2(80),
    CREATED_DT timestamp,
    UPDATED_BY varchar2(80),
    UPDATED_DT timestamp
);
ALTER TABLE ITTB_GIRO_UOB_HEADER ADD CONSTRAINT ITTB_GIRO_UOB_HEADER_FK1 FOREIGN KEY (REQ_NO) REFERENCES ITTB_GIRO_REQ (REQ_NO) ENABLE;
ALTER TABLE ITTB_GIRO_UOB_HEADER ADD CONSTRAINT ITTB_GIRO_UOB_HEADER_FK2 FOREIGN KEY (BANK_CODE_NO) REFERENCES FMTB_BANK_CODE (BANK_CODE_NO) ENABLE;
create SEQUENCE ITTB_GIRO_UOB_HEADER_SQ1 MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;

CREATE TABLE ITTB_GIRO_UOB_REJECTED(
	UOB_REJECTED_NO number(18) PRIMARY KEY NOT NULL,
	ACCOUNT_NO NUMBER(8) NOT NULL,
	BANK_CODE VARCHAR2(10) NOT NULL,
	BRANCH_CODE VARCHAR2(10) NOT NULL,
	BANK_ACCT_NO VARCHAR2(25) NOT NULL,
	TRANSACTION_CODE NUMBER(2) NOT NULL,
	GIRO_AMOUNT NUMBER(12,2) NOT NULL,
	PARTICULARS VARCHAR2(12) NOT NULL,
	REFERENCE VARCHAR2(12) NOT NULL,
	CLEAR_FATE NUMBER(1) NOT NULL,
	REJECTION_CODE NUMBER(3) NOT NULL,
	REJECTION_REASON VARCHAR2(255),
	REJECTED_BY VARCHAR2(20) NOT NULL,
	VERSION number(9) DEFAULT 0,
	CREATED_BY varchar2(80),
    CREATED_DT timestamp,
    UPDATED_BY varchar2(80),
    UPDATED_DT timestamp
);
ALTER TABLE ITTB_GIRO_UOB_REJECTED ADD CONSTRAINT ITTB_GIRO_UOB_REJECTED_FK1 FOREIGN KEY (ACCOUNT_NO) REFERENCES AMTB_ACCOUNT (ACCOUNT_NO) ENABLE;
create SEQUENCE ITTB_GIRO_UOB_REJECTED_SQ1 MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;

CREATE TABLE ITTB_GIRO_UOB_DETAIL(
	UOB_DETAIL_NO number(18) PRIMARY KEY NOT NULL,
	UOB_HEADER_NO number(18) NOT NULL,
	PARTICULARS varchar2(12) NOT NULL,
	REFERENCE varchar2(12) NOT NULL,
	INVOICE_HEADER_NO number(18) NOT NULL,
	INVOICE_DETAIL_NO number(18) NOT NULL,
	GIRO_AMOUNT number(12,2) not null,
	PAYMENT_RECEIPT_DETAIL_NO NUMBER(18),
	UOB_REJECTED_NO number(18),
	VERSION number(9) DEFAULT 0,
	CREATED_BY varchar2(80),
    CREATED_DT timestamp,
    UPDATED_BY varchar2(80),
    UPDATED_DT timestamp
);
CREATE INDEX ITTB_GIRO_UOB_DETAIL_N1 ON ITTB_GIRO_UOB_DETAIL(PARTICULARS, REFERENCE);
ALTER TABLE ITTB_GIRO_UOB_DETAIL ADD CONSTRAINT ITTB_GIRO_UOB_DETAIL_FK1 FOREIGN KEY (UOB_HEADER_NO) REFERENCES ITTB_GIRO_UOB_HEADER (UOB_HEADER_NO) ENABLE;
ALTER TABLE ITTB_GIRO_UOB_DETAIL ADD CONSTRAINT ITTB_GIRO_UOB_DETAIL_FK2 FOREIGN KEY (INVOICE_HEADER_NO) REFERENCES BMTB_INVOICE_HEADER (INVOICE_HEADER_NO) ENABLE;
ALTER TABLE ITTB_GIRO_UOB_DETAIL ADD CONSTRAINT ITTB_GIRO_UOB_DETAIL_FK3 FOREIGN KEY (INVOICE_DETAIL_NO) REFERENCES BMTB_INVOICE_DETAIL (INVOICE_DETAIL_NO) ENABLE;
ALTER TABLE ITTB_GIRO_UOB_DETAIL ADD CONSTRAINT ITTB_GIRO_UOB_DETAIL_FK4 FOREIGN KEY (PAYMENT_RECEIPT_DETAIL_NO) REFERENCES BMTB_PAYMENT_RECEIPT_DETAIL (PAYMENT_RECEIPT_DETAIL_NO) ENABLE;
ALTER TABLE ITTB_GIRO_UOB_DETAIL ADD CONSTRAINT ITTB_GIRO_UOB_DETAIL_FK5 FOREIGN KEY (UOB_REJECTED_NO) REFERENCES ITTB_GIRO_UOB_REJECTED (UOB_REJECTED_NO) ENABLE;
create SEQUENCE ITTB_GIRO_UOB_DETAIL_SQ1 MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;

--INTRODUCING NEW PAYMENT MODE
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION)
SELECT 
	MSTB_MASTER_TABLE_SQ1.nextVal,
	'PM','IG',null,'INTERBANK GIRO','A',0
FROM DUAL;

--GIRO Interface resources
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (476,25,'GIRO Interface','U','GIRO Interface',201,'GIRO Interface','Y',0);
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (477,476,'Configure Giro Setup','U','/admin/giro_interface/configure_giro_setup.zul',1,'Configure Giro Setup','Y',0);
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (478,476,'Create Giro Request','U','/admin/giro_interface/create_giro_request.zul',2,'Create Giro Request','Y',0);
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (472,476,'Manage Giro Request','U','/admin/giro_interface/manage_giro_request.zul',3,'Manage Giro Request','Y',0);
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (473,476,'View Giro Request','U','/admin/giro_interface/view_giro_request.zul',4,'View Giro Request','N',0);
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (474,476,'Edit Giro Request','U','/admin/giro_interface/edit_giro_request.zul',5,'Edit Giro Request','N',0);
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) VALUES (475,476,'Delete Giro Request','U','/admin/giro_interface/delete_giro_request.zul',6,'Delete Giro Request','N',0);

--INVOICE
alter table BMTB_INVOICE_HEADER add (
	GIRO_BANK_ACCT_NO varchar2(30),
	--e.g. 21st, 22nd, 23rd, 24th...
	GIRO_DAY varchar2(4)
);

alter table BMTB_DRAFT_INV_HEADER add (
	GIRO_BANK_ACCT_NO varchar2(30),
	--e.g. 21st, 22nd, 23rd, 24th...
	GIRO_DAY varchar2(4)
);