SET PAGES 5000
SET LINE  10000
SET TRIMSPOOL ON
set echo on

column dt new_value new_dt
column ext new_value new_ext
select  sys_context('userenv','instance_name') || '_septIssueLogs_ddl_' || to_char(sysdate,'YYYYMMDDHH24MISS') dt,'.txt' ext from dual;
SPOOL  &new_dt&new_ext
set define off
alter session set current_schema=ibssys;





/*-- 19/08/2016  #122 - add on outsource  START */

-- Invoice Promo
CREATE TABLE MSTB_INVOICE_PROMO (
	INVOICE_PROMO_ID NUMBER(8) NOT NULL,
	NAME VARCHAR2(80) NOT NULL,
	INSERT_DT TIMESTAMP NOT NULL,
	CHECK_OVERDUE VARCHAR2(1 CHAR) DEFAULT 'N',
	CHECK_INVOICE_CORP VARCHAR2(1 CHAR) DEFAULT 'N',
	CHECK_INVOICE_CORP_VALUE NUMBER(12,2),
	CHECK_INVOICE_PERS VARCHAR2(1 CHAR) DEFAULT 'N',
	CHECK_INVOICE_PERS_VALUE NUMBER(12,2),
	CHECK_PT VARCHAR2(1 CHAR) DEFAULT 'N',
	CHECK_PT_VALUE NUMBER(12,2),
	CHECK_MAIN_BILL_CONTACT VARCHAR2(1 CHAR) DEFAULT 'N',
	CHECK_RACE VARCHAR2(1 CHAR) DEFAULT 'N',
	CHECK_RACE_VALUE VARCHAR2(200);
	CHECK_ALT_CONTACT VARCHAR2(1 CHAR) DEFAULT 'N',
	CHECK_QUANTITY_VALUE NUMBER(12,2),
	PROMO1 VARCHAR2(1 CHAR),
	PROMO2 VARCHAR2(1 CHAR),
	PROMO3 VARCHAR2(1 CHAR),
	CREATED_BY VARCHAR2(40),
	CREATED_DT TIMESTAMP NOT NULL,
	UPDATED_BY VARCHAR2(40),
	UPDATED_DT TIMESTAMP
);

-- Create SEQUENCE
CREATE SEQUENCE  "MSSQ_INVOICE_PROMO"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 2 CACHE 10 NOORDER  NOCYCLE ;

-- Create Index
CREATE INDEX MSIX_INVOICE_PROMO__INVPROMOID ON MSTB_INVOICE_PROMO(INVOICE_PROMO_ID);
CREATE INDEX MSIX_INVOICE_PROMO__INSERT_DT ON MSTB_INVOICE_PROMO(INSERT_DT);

COMMENT ON COLUMN MSTB_INVOICE_PROMO.NAME IS 'Promo Name';
COMMENT ON COLUMN MSTB_INVOICE_PROMO.INSERT_DT IS 'Date to Insert';
COMMENT ON COLUMN MSTB_INVOICE_PROMO.CHECK_OVERDUE IS 'Check Overdue';
COMMENT ON COLUMN MSTB_INVOICE_PROMO.CHECK_INVOICE_CORP IS 'Check sum of all invoices if more than this value for Corporate';
COMMENT ON COLUMN MSTB_INVOICE_PROMO.CHECK_INVOICE_CORP_VALUE IS 'Check if more than this point';
COMMENT ON COLUMN MSTB_INVOICE_PROMO.CHECK_INVOICE_PERS IS 'Check sum of all invoices if more than this value for personal';
COMMENT ON COLUMN MSTB_INVOICE_PROMO.CHECK_INVOICE_PERS_VALUE IS 'Check if more than this point';
COMMENT ON COLUMN MSTB_INVOICE_PROMO.CHECK_PT IS 'Check if more than this value point';
COMMENT ON COLUMN MSTB_INVOICE_PROMO.CHECK_PT_VALUE IS 'Check if more than this point';
COMMENT ON COLUMN MSTB_INVOICE_PROMO.CHECK_MAIN_BILL_CONTACT IS 'Check Main Billing Contact';
COMMENT ON COLUMN MSTB_INVOICE_PROMO.CHECK_RACE IS 'Check Race';
COMMENT ON COLUMN MSTB_INVOICE_PROMO.CHECK_RACE_VALUE IS 'Check Races Value';
COMMENT ON COLUMN MSTB_INVOICE_PROMO.CHECK_ALT_CONTACT IS 'Check Alt Contact';
COMMENT ON COLUMN MSTB_INVOICE_PROMO.CHECK_QUANTITY_VALUE IS 'Custom Quantity';
COMMENT ON COLUMN MSTB_INVOICE_PROMO.PROMO1 IS 'Check is it PROMO1';
COMMENT ON COLUMN MSTB_INVOICE_PROMO.PROMO2 IS 'Check is it PROMO2';
COMMENT ON COLUMN MSTB_INVOICE_PROMO.PROMO3 IS 'Check is it PROMO3';


--RACE
ALTER TABLE AMTB_CONTACT_PERSON ADD (MAIN_CONTACT_RACE varchar2(20 char));
COMMENT ON COLUMN AMTB_CONTACT_PERSON.MAIN_CONTACT_RACE IS 'Main Contact Race';
ALTER TABLE AMTB_CONTACT_PERSON ADD (SUB_CONTACT_RACE varchar2(20 char));
COMMENT ON COLUMN AMTB_CONTACT_PERSON.SUB_CONTACT_RACE IS 'Sub Contact Race';


--BMTB INVOICE FILE
ALTER TABLE BMTB_INVOICE_FILE ADD (FILE_NAME varchar2(100 char));
COMMENT ON COLUMN BMTB_INVOICE_FILE.FILE_NAME IS 'File Name';
ALTER TABLE BMTB_INVOICE_FILE ADD (PAGE_COUNT varchar2(10 char));
COMMENT ON COLUMN BMTB_INVOICE_FILE.PAGE_COUNT IS 'Page Count';


/*-- 19/08/2016  #122 - add on outsource END */



/*-- 23/09/2016  CR/0215/042 - cabreward amount START */

alter table TMTB_ACQUIRE_TXN add ( CABREWARDS_AMT decimal(12,2) );

alter table tmtb_txn_review_req add ( CABREWARDS_AMT decimal(12,2) );

alter table TMTB_NON_BILLABLE_TXN add ( CABREWARDS_AMT decimal(12,2) );

alter table ittb_trips_txn add ( CABREWARDS_AMT decimal(12,2) );

alter table ittb_trips_txn_error add ( CABREWARDS_AMT decimal(12,2) );

alter table ITTB_FMS_DRVR_RFND_COL_REQ add ( CABREWARDS_AMT decimal(12,2) DEFAULT 0);

alter table rcvw_intf_trips_for_IBS add ( CABREWARDS_AMT decimal(12,2) );


COMMENT ON COLUMN TMTB_ACQUIRE_TXN.CABREWARDS_AMT IS 'CabRewardsAmount Field';
COMMENT ON COLUMN tmtb_txn_review_req.CABREWARDS_AMT IS 'CabRewardsAmount Field';
COMMENT ON COLUMN TMTB_NON_BILLABLE_TXN.CABREWARDS_AMT IS 'CabRewardsAmount Field';
COMMENT ON COLUMN ittb_trips_txn.CABREWARDS_AMT IS 'CabRewardsAmount Field';
COMMENT ON COLUMN ittb_trips_txn_error.CABREWARDS_AMT IS 'CabRewardsAmount Field';
COMMENT ON COLUMN ITTB_FMS_DRVR_RFND_COL_REQ.CABREWARDS_AMT IS 'CabRewardsAmount Field';
COMMENT ON COLUMN rcvw_intf_trips_for_IBS.CABREWARDS_AMT IS 'CabRewardsAmount Field';

/*-- 23/09/2016  CR/0215/042 - cabreward amount END */



/* -- 15/11/2016 outsource printing invoice promo upload START */

alter table MSTB_INVOICE_PROMO ADD (FILE_DATA BLOB);
alter table MSTB_INVOICE_PROMO ADD (FILE_NAME varchar2(100 char));

COMMENT ON COLUMN MSTB_INVOICE_PROMO.FILE IS 'Upload File Blob';
COMMENT ON COLUMN MSTB_INVOICE_PROMO.FILE_NAME IS 'Upload file name';

/* -- 15/11/2016 outsource printing invoice promo upload END */

spool off
