INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'EMIRDS','SUBJ',null,'Invoice Reminder Due Soon','A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'EMIRDS','CONT',null,'<P style="font-family:Calibri; font-size:16px;white-space: pre">Customer ID: #customerId# <br>Customer Name: #customerName# <br><br> #table# <br><br>Please reply to billing@cdgtaxi.com.sg</P>','A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'EMIROD','SUBJ',null,'Invoice Reminder Overdue','A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'EMIROD','CONT',null,'<P style="font-family:Calibri; font-size:16px;white-space: pre">Customer ID: #customerId# <br>Customer Name: #customerName# <br><br> #table# <br><br>Please reply to billing@cdgtaxi.com.sg</P>','A',0);


INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'CLC','CLC',null,'2000','A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'CBC','CBC',null,'1000','A',0);


INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'IDS','IDS',null,'5','A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'IORY','IORY',null,'7','A',0);

INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.nextVal,'IORZ','IORZ',null,'90','A',0);




-- For Overdue Reminder
ALTER TABLE AMTB_ACCOUNT add OVERDUE_REMINDER varchar2(1 char) DEFAULT 'N';

ALTER TABLE AMTB_ACCOUNT add REMINDER_EMAIL varchar2(500 char);