SET PAGES 5000
SET LINE  10000
SET TRIMSPOOL ON
set echo on

column dt new_value new_dt
column ext new_value new_ext
select  sys_context('userenv','instance_name') || '_mayP32IssueLogs_dml_01_' || to_char(sysdate,'YYYYMMDDHH24MISS') dt,'.txt' ext from dual;
SPOOL  &new_dt&new_ext
set define off
alter session set current_schema=ibssys;



--Create Table to track recurring token
CREATE TABLE ITTB_RECURRING_CHARGE (
ID NUMBER(19) primary key not null,
TOKEN_ID VARCHAR2(150) not null unique,
TOKEN_EXPIRY DATE not null,
CREDIT_CARD_NO VARCHAR2(50) not null,
CREDIT_CARD_NO_EXPIRY DATE not null
);

CREATE SEQUENCE "ITSQ_RECURRING_CHARGE"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 152 CACHE 10 NOORDER  NOCYCLE ;

COMMENT ON TABLE ITTB_RECURRING_CHARGE IS 'Table to track recurring token';
COMMENT ON COLUMN ITTB_RECURRING_CHARGE.ID IS 'Sequence Id for IttbRecurringCharge';
COMMENT ON COLUMN ITTB_RECURRING_CHARGE.TOKEN_ID IS 'The CreditCard Token ID from reddot';
COMMENT ON COLUMN ITTB_RECURRING_CHARGE.TOKEN_EXPIRY IS 'The expiry date of the token';
COMMENT ON COLUMN ITTB_RECURRING_CHARGE.CREDIT_CARD_NO IS 'The CreditCard Number';
COMMENT ON COLUMN ITTB_RECURRING_CHARGE.CREDIT_CARD_NO_EXPIRY IS 'CreditCards Expiry Date';


--Create Table to track recurring token that are tag to which accounts
CREATE TABLE ITTB_RECURRING_CHARGE_TAG_ACCT (
ID NUMBER(19) not null,
ACCOUNT_NO NUMBER(8) NOT NULL,
RECURRING_CHARGE_ID NUMBER(19) not null,
constraint ITPC_RECTAGACCT__ACCTNO$RECID primary key (ACCOUNT_NO, RECURRING_CHARGE_ID)
);

ALTER TABLE ITTB_RECURRING_CHARGE_TAG_ACCT ADD CONSTRAINT ITFC_REC_TAG_ACCT__ACCTNO FOREIGN KEY (ACCOUNT_NO) REFERENCES AMTB_ACCOUNT (ACCOUNT_NO) ENABLE;
ALTER TABLE ITTB_RECURRING_CHARGE_TAG_ACCT ADD CONSTRAINT ITFC_REC_TAG_ACCT__RECCHGID FOREIGN KEY (RECURRING_CHARGE_ID) REFERENCES ITTB_RECURRING_CHARGE (ID) ENABLE;

CREATE SEQUENCE "ITSQ_RECURRING_CHARGE_TG_ACCT"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 152 CACHE 10 NOORDER  NOCYCLE ;
CREATE INDEX ITIX_REC_TAG_ACCT__RECID ON ITTB_RECURRING_CHARGE_TAG_ACCT(RECURRING_CHARGE_ID);

COMMENT ON TABLE ITTB_RECURRING_CHARGE_TAG_ACCT IS 'Table to track recurring token that are tag to which accounts';
COMMENT ON COLUMN ITTB_RECURRING_CHARGE_TAG_ACCT.ID IS 'Sequence Id for IttbRecurringChargeTagAcct';
COMMENT ON COLUMN ITTB_RECURRING_CHARGE_TAG_ACCT.ACCOUNT_NO IS 'The Account Number that is tag to this token';
COMMENT ON COLUMN ITTB_RECURRING_CHARGE_TAG_ACCT.RECURRING_CHARGE_ID IS 'The recurring charge id to map to ittbRecurringCharge Id';


--Create Table to track recurring token that are tag to which cards
CREATE TABLE ITTB_RECURRING_CHARGE_TAG_CARD (
ID NUMBER(19) not null,
PRODUCT_NO NUMBER(19) NOT NULL,
RECURRING_CHARGE_ID NUMBER(19) not null,
constraint ITPC_RECTAGPROD__PRODNO$RECID primary key (PRODUCT_NO,RECURRING_CHARGE_ID)
);

ALTER TABLE ITTB_RECURRING_CHARGE_TAG_CARD ADD CONSTRAINT ITFC_REC_TAG_CARD__PRODUCTNO FOREIGN KEY (PRODUCT_NO) REFERENCES PMTB_PRODUCT (PRODUCT_NO) ENABLE;
ALTER TABLE ITTB_RECURRING_CHARGE_TAG_CARD ADD CONSTRAINT ITFC_REC_TAG_CARD__RECCHGID FOREIGN KEY (RECURRING_CHARGE_ID) REFERENCES ITTB_RECURRING_CHARGE (ID) ENABLE;

CREATE SEQUENCE "ITSQ_RECURRING_CHARGE_TG_CARD"  MINVALUE 1 MAXVALUE 999999999999999999 INCREMENT BY 1 START WITH 152 CACHE 10 NOORDER  NOCYCLE ;
CREATE INDEX ITIX_REC_TAG_CARD__RECID ON ITTB_RECURRING_CHARGE_TAG_CARD(RECURRING_CHARGE_ID);

COMMENT ON TABLE ITTB_RECURRING_CHARGE_TAG_CARD IS 'Table to track recurring token that are tag to which cards';
COMMENT ON COLUMN ITTB_RECURRING_CHARGE_TAG_CARD.ID IS 'Sequence Id for IttbRecurringChargeTagProd';
COMMENT ON COLUMN ITTB_RECURRING_CHARGE_TAG_CARD.PRODUCT_NO IS 'The Product ID that is tag to this token';
COMMENT ON COLUMN ITTB_RECURRING_CHARGE_TAG_CARD.RECURRING_CHARGE_ID IS 'The recurring charge id to map to ittbRecurringCharge id';




--To set Recurring flag for Account, Y=Yes, N=No
alter table AMTB_ACCOUNT add RECURRING_FLAG varchar(1) default 'N';
COMMENT ON COLUMN AMTB_ACCOUNT.RECURRING_FLAG IS 'Recurring Flag; Y=Yes, N=No';

-- To set the recurring flag for Application,  Y=Yes, N=No;
alter table AMTB_APPLICATION add RECURRING_FLAG varchar(1) default 'N';
COMMENT ON COLUMN AMTB_APPLICATION.RECURRING_FLAG IS 'Recurring Flag; Y=Yes, N=No';

-- To set the charge day for accounts recurring so that every month this day, it will get auto recurred.
alter table AMTB_ACCOUNT add RECURRING_CHARGE_DAY NUMBER(2);
COMMENT ON COLUMN AMTB_ACCOUNT.RECURRING_CHARGE_DAY IS 'Recurring Charge Day; 1 to 31 ';


-- To keep track if invoice has been done by auto recurring job. Y=Yes, N=No
alter table BMTB_INVOICE_HEADER ADD (RECURRING_DONE_FLAG varchar2(1 char) DEFAULT 'N');
COMMENT ON COLUMN BMTB_INVOICE_HEADER.RECURRING_DONE_FLAG IS 'Recurring Done Flag; Y=Yes, N=No';


commit;