package com.cdgtaxi.ibs.common.model;
// Generated Jul 20, 2009 5:50:40 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.master.model.MstbBankMaster;
import com.cdgtaxi.ibs.master.model.MstbBranchMaster;


/**
 * AmtbBillReq generated by hbm2java
 */

public class AmtbBillReq  implements java.io.Serializable {


    // Fields    

    private Integer billReqNo;
    private Timestamp requestDt;
    private String bankAccountNo;
    private Integer version;
    private MstbBankMaster mstbBankMaster;
    private AmtbAccount amtbAccount;
    private Set<AmtbAcctLatePymtReq> amtbAcctLatePymtReqs = new HashSet<AmtbAcctLatePymtReq>(0);
    private Set<AmtbAcctAdminFeeReq> amtbAcctAdminFeeReqs = new HashSet<AmtbAcctAdminFeeReq>(0);
    private Set<AmtbAcctVolDiscReq> amtbAcctVolDiscReqs = new HashSet<AmtbAcctVolDiscReq>(0);
    private Set<AmtbBillReqFlow> amtbBillReqFlows = new HashSet<AmtbBillReqFlow>(0);
    private Set<AmtbAcctBillCycleReq> amtbAcctBillCycleReqs = new HashSet<AmtbAcctBillCycleReq>(0);
    private Set<AmtbAcctCredTermReq> amtbAcctCredTermReqs = new HashSet<AmtbAcctCredTermReq>(0);
    private Set<AmtbAcctPromotionReq> amtbAcctPromotionReqs = new HashSet<AmtbAcctPromotionReq>(0);
    private Set<AmtbAcctEarlyPymtReq> amtbAcctEarlyPymtReqs = new HashSet<AmtbAcctEarlyPymtReq>(0);
    private MstbBranchMaster mstbBranchMaster;


    // Constructors

    /** default constructor */
    public AmtbBillReq() {
    }

	/** minimal constructor */
    public AmtbBillReq(Timestamp requestDt) {
        this.requestDt = requestDt;
    }
    
    /** full constructor */
    public AmtbBillReq(Timestamp requestDt, String bankAccountNo, Integer version, MstbBankMaster mstbBankMaster, MstbBranchMaster mstbBranchMaster, AmtbAccount amtbAccount, Set<AmtbAcctLatePymtReq> amtbAcctLatePymtReqs, Set<AmtbAcctAdminFeeReq> amtbAcctAdminFeeReqs, Set<AmtbAcctVolDiscReq> amtbAcctVolDiscReqs, Set<AmtbBillReqFlow> amtbBillReqFlows, Set<AmtbAcctBillCycleReq> amtbAcctBillCycleReqs, Set<AmtbAcctCredTermReq> amtbAcctCredTermReqs, Set<AmtbAcctPromotionReq> amtbAcctPromotionReqs, Set<AmtbAcctEarlyPymtReq> amtbAcctEarlyPymtReqs) {
        this.requestDt = requestDt;
        this.bankAccountNo = bankAccountNo;
        this.version = version;
        this.mstbBankMaster = mstbBankMaster;
        this.amtbAccount = amtbAccount;
        this.amtbAcctLatePymtReqs = amtbAcctLatePymtReqs;
        this.amtbAcctAdminFeeReqs = amtbAcctAdminFeeReqs;
        this.amtbAcctVolDiscReqs = amtbAcctVolDiscReqs;
        this.amtbBillReqFlows = amtbBillReqFlows;
        this.amtbAcctBillCycleReqs = amtbAcctBillCycleReqs;
        this.amtbAcctCredTermReqs = amtbAcctCredTermReqs;
        this.amtbAcctEarlyPymtReqs = amtbAcctEarlyPymtReqs;
        this.amtbAcctPromotionReqs = amtbAcctPromotionReqs;
        this.mstbBranchMaster = mstbBranchMaster;
    }
    

   
    // Property accessors

    public Integer getBillReqNo() {
        return this.billReqNo;
    }
    
    public void setBillReqNo(Integer billReqNo) {
        this.billReqNo = billReqNo;
    }

    public Timestamp getRequestDt() {
        return this.requestDt;
    }
    
    public void setRequestDt(Timestamp requestDt) {
        this.requestDt = requestDt;
    }

    public String getBankAccountNo() {
        return this.bankAccountNo;
    }
    
    public void setBankAccountNo(String bankAccountNo) {
        this.bankAccountNo = bankAccountNo;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public MstbBankMaster getMstbBankMaster() {
        return this.mstbBankMaster;
    }
    
    public void setMstbBankMaster(MstbBankMaster mstbBankMaster) {
        this.mstbBankMaster = mstbBankMaster;
    }

    public AmtbAccount getAmtbAccount() {
        return this.amtbAccount;
    }
    
    public void setAmtbAccount(AmtbAccount amtbAccount) {
        this.amtbAccount = amtbAccount;
    }

    public Set<AmtbAcctLatePymtReq> getAmtbAcctLatePymtReqs() {
        return this.amtbAcctLatePymtReqs;
    }
    
    public void setAmtbAcctLatePymtReqs(Set<AmtbAcctLatePymtReq> amtbAcctLatePymtReqs) {
        this.amtbAcctLatePymtReqs = amtbAcctLatePymtReqs;
    }

    public Set<AmtbAcctAdminFeeReq> getAmtbAcctAdminFeeReqs() {
        return this.amtbAcctAdminFeeReqs;
    }
    
    public void setAmtbAcctAdminFeeReqs(Set<AmtbAcctAdminFeeReq> amtbAcctAdminFeeReqs) {
        this.amtbAcctAdminFeeReqs = amtbAcctAdminFeeReqs;
    }

    public Set<AmtbAcctVolDiscReq> getAmtbAcctVolDiscReqs() {
        return this.amtbAcctVolDiscReqs;
    }
    
    public Set<AmtbAcctPromotionReq> getAmtbAcctPromotionReqs() {
        return this.amtbAcctPromotionReqs;
    }
    
    public void setAmtbAcctPromotionReqs(Set<AmtbAcctPromotionReq> amtbAcctPromotionReqs) {
        this.amtbAcctPromotionReqs = amtbAcctPromotionReqs;
    }
    
    public void setAmtbAcctVolDiscReqs(Set<AmtbAcctVolDiscReq> amtbAcctVolDiscReqs) {
        this.amtbAcctVolDiscReqs = amtbAcctVolDiscReqs;
    }

    public Set<AmtbBillReqFlow> getAmtbBillReqFlows() {
        return this.amtbBillReqFlows;
    }
    
    public void setAmtbBillReqFlows(Set<AmtbBillReqFlow> amtbBillReqFlows) {
        this.amtbBillReqFlows = amtbBillReqFlows;
    }

    public Set<AmtbAcctBillCycleReq> getAmtbAcctBillCycleReqs() {
        return this.amtbAcctBillCycleReqs;
    }
    
    public void setAmtbAcctBillCycleReqs(Set<AmtbAcctBillCycleReq> amtbAcctBillCycleReqs) {
        this.amtbAcctBillCycleReqs = amtbAcctBillCycleReqs;
    }

    public Set<AmtbAcctCredTermReq> getAmtbAcctCredTermReqs() {
        return this.amtbAcctCredTermReqs;
    }
    
    public void setAmtbAcctCredTermReqs(Set<AmtbAcctCredTermReq> amtbAcctCredTermReqs) {
        this.amtbAcctCredTermReqs = amtbAcctCredTermReqs;
    }

    public Set<AmtbAcctEarlyPymtReq> getAmtbAcctEarlyPymtReqs() {
        return this.amtbAcctEarlyPymtReqs;
    }
    
    public void setAmtbAcctEarlyPymtReqs(Set<AmtbAcctEarlyPymtReq> amtbAcctEarlyPymtReqs) {
        this.amtbAcctEarlyPymtReqs = amtbAcctEarlyPymtReqs;
    }

    public MstbBranchMaster getMstbBranchMaster() {
        return this.mstbBranchMaster;
    }
    
    public void setMstbBranchMaster(MstbBranchMaster mstbBranchMaster) {
        this.mstbBranchMaster = mstbBranchMaster;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("requestDt").append("='").append(getRequestDt()).append("' ");			
      buffer.append("bankAccountNo").append("='").append(getBankAccountNo()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmtbBillReq) ) return false;
		 AmtbBillReq castOther = ( AmtbBillReq ) other; 
         
		 return ( (this.getBillReqNo()==castOther.getBillReqNo()) || ( this.getBillReqNo()!=null && castOther.getBillReqNo()!=null && this.getBillReqNo().equals(castOther.getBillReqNo()) ) )
 && ( (this.getRequestDt()==castOther.getRequestDt()) || ( this.getRequestDt()!=null && castOther.getRequestDt()!=null && this.getRequestDt().equals(castOther.getRequestDt()) ) )
 && ( (this.getBankAccountNo()==castOther.getBankAccountNo()) || ( this.getBankAccountNo()!=null && castOther.getBankAccountNo()!=null && this.getBankAccountNo().equals(castOther.getBankAccountNo()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getMstbBankMaster()==castOther.getMstbBankMaster()) || ( this.getMstbBankMaster()!=null && castOther.getMstbBankMaster()!=null && this.getMstbBankMaster().equals(castOther.getMstbBankMaster()) ) )
 && ( (this.getAmtbAccount()==castOther.getAmtbAccount()) || ( this.getAmtbAccount()!=null && castOther.getAmtbAccount()!=null && this.getAmtbAccount().equals(castOther.getAmtbAccount()) ) )
 && ( (this.getMstbBranchMaster()==castOther.getMstbBranchMaster()) || ( this.getMstbBranchMaster()!=null && castOther.getMstbBranchMaster()!=null && this.getMstbBranchMaster().equals(castOther.getMstbBranchMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBillReqNo() == null ? 0 : this.getBillReqNo().hashCode() );
         result = 37 * result + ( getRequestDt() == null ? 0 : this.getRequestDt().hashCode() );
         result = 37 * result + ( getBankAccountNo() == null ? 0 : this.getBankAccountNo().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getMstbBankMaster() == null ? 0 : this.getMstbBankMaster().hashCode() );
         result = 37 * result + ( getAmtbAccount() == null ? 0 : this.getAmtbAccount().hashCode() );
         
         
         
         
         
         
         
         result = 37 * result + ( getMstbBranchMaster() == null ? 0 : this.getMstbBranchMaster().hashCode() );
         return result;
   }   





}
