package com.cdgtaxi.ibs.common.model;
// Generated Jul 20, 2009 4:09:43 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;

import com.cdgtaxi.ibs.master.model.MstbVolDiscMaster;


/**
 * AmtbAcctVolDiscReq generated by hbm2java
 */

public class AmtbAcctVolDiscReq  implements java.io.Serializable {


    // Fields    

    private Integer acctVolDiscReqNo;
    private String event;
    private Timestamp effectiveDt;
    private Integer version;
    private MstbVolDiscMaster mstbVolDiscMaster;
    private AmtbBillReq amtbBillReq;


    // Constructors

    /** default constructor */
    public AmtbAcctVolDiscReq() {
    }

	/** minimal constructor */
    public AmtbAcctVolDiscReq(Timestamp effectiveDt) {
        this.effectiveDt = effectiveDt;
    }
    
    /** full constructor */
    public AmtbAcctVolDiscReq(String event, Timestamp effectiveDt, Integer version, MstbVolDiscMaster mstbVolDiscMaster, AmtbBillReq amtbBillReq) {
        this.event = event;
        this.effectiveDt = effectiveDt;
        this.version = version;
        this.mstbVolDiscMaster = mstbVolDiscMaster;
        this.amtbBillReq = amtbBillReq;
    }
    

   
    // Property accessors

    public Integer getAcctVolDiscReqNo() {
        return this.acctVolDiscReqNo;
    }
    
    public void setAcctVolDiscReqNo(Integer acctVolDiscReqNo) {
        this.acctVolDiscReqNo = acctVolDiscReqNo;
    }

    public String getEvent() {
        return this.event;
    }
    
    public void setEvent(String event) {
        this.event = event;
    }

    public Timestamp getEffectiveDt() {
        return this.effectiveDt;
    }
    
    public void setEffectiveDt(Timestamp effectiveDt) {
        this.effectiveDt = effectiveDt;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public MstbVolDiscMaster getMstbVolDiscMaster() {
        return this.mstbVolDiscMaster;
    }
    
    public void setMstbVolDiscMaster(MstbVolDiscMaster mstbVolDiscMaster) {
        this.mstbVolDiscMaster = mstbVolDiscMaster;
    }

    public AmtbBillReq getAmtbBillReq() {
        return this.amtbBillReq;
    }
    
    public void setAmtbBillReq(AmtbBillReq amtbBillReq) {
        this.amtbBillReq = amtbBillReq;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("event").append("='").append(getEvent()).append("' ");			
      buffer.append("effectiveDt").append("='").append(getEffectiveDt()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmtbAcctVolDiscReq) ) return false;
		 AmtbAcctVolDiscReq castOther = ( AmtbAcctVolDiscReq ) other; 
         
		 return ( (this.getAcctVolDiscReqNo()==castOther.getAcctVolDiscReqNo()) || ( this.getAcctVolDiscReqNo()!=null && castOther.getAcctVolDiscReqNo()!=null && this.getAcctVolDiscReqNo().equals(castOther.getAcctVolDiscReqNo()) ) )
 && ( (this.getEvent()==castOther.getEvent()) || ( this.getEvent()!=null && castOther.getEvent()!=null && this.getEvent().equals(castOther.getEvent()) ) )
 && ( (this.getEffectiveDt()==castOther.getEffectiveDt()) || ( this.getEffectiveDt()!=null && castOther.getEffectiveDt()!=null && this.getEffectiveDt().equals(castOther.getEffectiveDt()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getMstbVolDiscMaster()==castOther.getMstbVolDiscMaster()) || ( this.getMstbVolDiscMaster()!=null && castOther.getMstbVolDiscMaster()!=null && this.getMstbVolDiscMaster().equals(castOther.getMstbVolDiscMaster()) ) )
 && ( (this.getAmtbBillReq()==castOther.getAmtbBillReq()) || ( this.getAmtbBillReq()!=null && castOther.getAmtbBillReq()!=null && this.getAmtbBillReq().equals(castOther.getAmtbBillReq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAcctVolDiscReqNo() == null ? 0 : this.getAcctVolDiscReqNo().hashCode() );
         result = 37 * result + ( getEvent() == null ? 0 : this.getEvent().hashCode() );
         result = 37 * result + ( getEffectiveDt() == null ? 0 : this.getEffectiveDt().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getMstbVolDiscMaster() == null ? 0 : this.getMstbVolDiscMaster().hashCode() );
         result = 37 * result + ( getAmtbBillReq() == null ? 0 : this.getAmtbBillReq().hashCode() );
         return result;
   }   





}
