package com.cdgtaxi.ibs.common.model;
// Generated Jul 20, 2009 4:09:44 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.master.model.MstbAdminFeeMaster;
import com.cdgtaxi.ibs.master.model.MstbEarlyPaymentMaster;
import com.cdgtaxi.ibs.master.model.MstbLatePaymentMaster;
import com.cdgtaxi.ibs.master.model.MstbMasterTable;
import com.cdgtaxi.ibs.master.model.MstbSalesperson;
import com.cdgtaxi.ibs.master.model.MstbVolDiscMaster;


/**
 * AmtbApplication generated by hbm2java
 */

public class AmtbApplication  implements java.io.Serializable {


    // Fields    

    private String applicationNo;
    private Timestamp applicationDt;
    private String applicantName;
    private String rcbNo;
    private Timestamp rcbDt;
    private BigDecimal capital;
    private String addressBlock;
    private String addressUnit;
    private String addressStreet;
    private String addressBuilding;
    private String addressArea;
    private String addressCity;
    private String addressState;
    private String addressPostal;
    private String authPerson;
    private String authTitle;
    private BigDecimal creditLimit;
    private BigDecimal deposit;
    private String nameOnCard;
    private String nric;
    private String tel;
    private String fax;
    private String mobile;
    private String office;
    private String email;
    private String billingSame;
    private String billingBlock;
    private String billingUnit;
    private String billingStreet;
    private String billingBuilding;
    private String billingArea;
    private String billingPostal;
    private String billingCity;
    private String billingState;
    private String shippingSame;
    private String shippingBlock;
    private String shippingUnit;
    private String shippingStreet;
    private String shippingBuilding;
    private String shippingArea;
    private String shippingPostal;
    private String shippingCity;
    private String shippingState;
    private String occupation;
    private String employerName;
    private String employerBlock;
    private String employerUnit;
    private String employerStreet;
    private String employerBuilding;
    private String employerArea;
    private String employerPostal;
    private String employerCity;
    private String employerState;
    private BigDecimal monthlyIncome;
    private Integer employYears;
    private String projectCode;
    private Timestamp createdDt;
    private Timestamp updatedDt;
    private String updatedBy;
    private String createdBy;
    private Integer version;
    private String einvoiceFlag;
    private String invoicePrinting;
    private String outsourcePrintingFlag;
    private String smsFlag;
    private String smsExpiryFlag;
	private String smsTopupFlag;
    private MstbEarlyPaymentMaster mstbEarlyPaymentMaster;
    private MstbMasterTable mstbMasterTableByBillingCountry;
    private MstbMasterTable mstbMasterTableByEmployerCountry;
    private MstbMasterTable mstbMasterTableByJobStatus;
    private MstbMasterTable mstbMasterTableByAuthSal;
    private MstbMasterTable mstbMasterTableByShippingCountry;
    private MstbMasterTable mstbMasterTableByIndustryNo;
    private MstbMasterTable mstbMasterTableByInformationSource;
    private MstbMasterTable mstbMasterTableByAddressCountry;
    private MstbSalesperson mstbSalesperson;
    private FmtbArContCodeMaster fmtbArContCodeMaster;
    private Set<AmtbApplicationProduct> amtbApplicationProducts = new HashSet<AmtbApplicationProduct>(0);
    private Set<AmtbApplicationFlow> amtbApplicationFlows = new HashSet<AmtbApplicationFlow>(0);
    private AmtbAcctType amtbAcctType;
    private AmtbAccount amtbAccount;
    private MstbVolDiscMaster mstbVolDiscMaster;
    private MstbAdminFeeMaster mstbAdminFeeMaster;
    private MstbLatePaymentMaster mstbLatePaymentMaster;

    private String invoiceFormat;
    private String invoiceSorting;
    private String govtEInvoiceFlag;
    private Integer businessUnitMasterNo;
    
    private String printTaxInvoiceOnly;
    private MstbMasterTable mstbMasterTableByMainContactRace;
    
    private String aceIndicator;
    private String coupaIndicator;

	public String getCoupaIndicator() {
		return coupaIndicator;
	}


	public void setCoupaIndicator(String coupaIndicator) {
		this.coupaIndicator = coupaIndicator;
	}

	private String pubbsFlag;
	private String fiFlag;
	private String recurringFlag;
	
    // Constructors

    /** default constructor */
    public AmtbApplication() {
    }

    
    /** full constructor */
    public AmtbApplication(Timestamp applicationDt, String applicantName, String rcbNo, Timestamp rcbDt, BigDecimal capital, String addressBlock, String addressUnit, String addressStreet, String addressBuilding, String addressArea, String addressCity, String addressState, String addressPostal, String authPerson, String authTitle, BigDecimal creditLimit, BigDecimal deposit, String nameOnCard, String nric, String tel, String fax, String mobile, String office, String email, String billingSame, String billingBlock, String billingUnit, String billingStreet, String billingBuilding, String billingArea, String billingPostal, String billingCity, String billingState, String shippingSame, String shippingBlock, String shippingUnit, String shippingStreet, String shippingBuilding, String shippingArea, String shippingPostal, String shippingCity, String shippingState, String occupation, String employerName, String employerBlock, String employerUnit, String employerStreet, String employerBuilding, String employerArea, String employerPostal, String employerCity, String employerState, BigDecimal monthlyIncome, Integer employYears, String projectCode, Timestamp createdDt, Timestamp updatedDt, String updatedBy, String createdBy, Integer version, String einvoiceFlag, String invoicePrinting, String smsFlag, String smsExpiryFlag, String smsTopupFlag, MstbEarlyPaymentMaster mstbEarlyPaymentMaster, MstbMasterTable mstbMasterTableByBillingCountry, MstbMasterTable mstbMasterTableByEmployerCountry, MstbMasterTable mstbMasterTableByJobStatus, MstbMasterTable mstbMasterTableByAuthSal, MstbMasterTable mstbMasterTableByShippingCountry, MstbMasterTable mstbMasterTableByIndustryNo, MstbMasterTable mstbMasterTableByInformationSource, MstbMasterTable mstbMasterTableByAddressCountry, MstbSalesperson mstbSalesperson, FmtbArContCodeMaster fmtbArContCodeMaster, Set<AmtbApplicationProduct> amtbApplicationProducts, Set<AmtbApplicationFlow> amtbApplicationFlows, AmtbAcctType amtbAcctType, AmtbAccount amtbAccount, MstbVolDiscMaster mstbVolDiscMaster, MstbAdminFeeMaster mstbAdminFeeMaster, MstbLatePaymentMaster mstbLatePaymentMaster, String invoiceFormat, String invoiceSorting, String govtEInvoiceFlag, int businessUnitMasterNo, String printTaxInvoiceOnly, MstbMasterTable mstbMasterTableByMainContactRace, String aceIndicator, String pubbsFlag, String fiFlag, String recurringFlag, Integer recurringChargeDay) {
        this.applicationDt = applicationDt;
        this.applicantName = applicantName;
        this.rcbNo = rcbNo;
        this.rcbDt = rcbDt;
        this.capital = capital;
        this.addressBlock = addressBlock;
        this.addressUnit = addressUnit;
        this.addressStreet = addressStreet;
        this.addressBuilding = addressBuilding;
        this.addressArea = addressArea;
        this.addressCity = addressCity;
        this.addressState = addressState;
        this.addressPostal = addressPostal;
        this.authPerson = authPerson;
        this.authTitle = authTitle;
        this.creditLimit = creditLimit;
        this.deposit = deposit;
        this.nameOnCard = nameOnCard;
        this.nric = nric;
        this.tel = tel;
        this.fax = fax;
        this.mobile = mobile;
        this.office = office;
        this.email = email;
        this.billingSame = billingSame;
        this.billingBlock = billingBlock;
        this.billingUnit = billingUnit;
        this.billingStreet = billingStreet;
        this.billingBuilding = billingBuilding;
        this.billingArea = billingArea;
        this.billingPostal = billingPostal;
        this.billingCity = billingCity;
        this.billingState = billingState;
        this.shippingSame = shippingSame;
        this.shippingBlock = shippingBlock;
        this.shippingUnit = shippingUnit;
        this.shippingStreet = shippingStreet;
        this.shippingBuilding = shippingBuilding;
        this.shippingArea = shippingArea;
        this.shippingPostal = shippingPostal;
        this.shippingCity = shippingCity;
        this.shippingState = shippingState;
        this.occupation = occupation;
        this.employerName = employerName;
        this.employerBlock = employerBlock;
        this.employerUnit = employerUnit;
        this.employerStreet = employerStreet;
        this.employerBuilding = employerBuilding;
        this.employerArea = employerArea;
        this.employerPostal = employerPostal;
        this.employerCity = employerCity;
        this.employerState = employerState;
        this.monthlyIncome = monthlyIncome;
        this.employYears = employYears;
        this.projectCode = projectCode;
        this.createdDt = createdDt;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.createdBy = createdBy;
        this.version = version;
        this.einvoiceFlag = einvoiceFlag;
        this.invoicePrinting = invoicePrinting;
        this.outsourcePrintingFlag = outsourcePrintingFlag;
        this.smsFlag = smsFlag;
        this.smsExpiryFlag = smsExpiryFlag;
		this.smsTopupFlag = smsTopupFlag;
        this.mstbEarlyPaymentMaster = mstbEarlyPaymentMaster;
        this.mstbMasterTableByBillingCountry = mstbMasterTableByBillingCountry;
        this.mstbMasterTableByEmployerCountry = mstbMasterTableByEmployerCountry;
        this.mstbMasterTableByJobStatus = mstbMasterTableByJobStatus;
        this.mstbMasterTableByAuthSal = mstbMasterTableByAuthSal;
        this.mstbMasterTableByShippingCountry = mstbMasterTableByShippingCountry;
        this.mstbMasterTableByIndustryNo = mstbMasterTableByIndustryNo;
        this.mstbMasterTableByInformationSource = mstbMasterTableByInformationSource;
        this.mstbMasterTableByAddressCountry = mstbMasterTableByAddressCountry;
        this.mstbSalesperson = mstbSalesperson;
        this.fmtbArContCodeMaster = fmtbArContCodeMaster;
        this.amtbApplicationProducts = amtbApplicationProducts;
        this.amtbApplicationFlows = amtbApplicationFlows;
        this.amtbAcctType = amtbAcctType;
        this.amtbAccount = amtbAccount;
        this.mstbVolDiscMaster = mstbVolDiscMaster;
        this.mstbAdminFeeMaster = mstbAdminFeeMaster;
        this.mstbLatePaymentMaster = mstbLatePaymentMaster;
        this.invoiceFormat = invoiceFormat;
        this.invoiceSorting = invoiceSorting;
        this.govtEInvoiceFlag = govtEInvoiceFlag;
        this.businessUnitMasterNo = businessUnitMasterNo;
        this.printTaxInvoiceOnly = printTaxInvoiceOnly;
        this.mstbMasterTableByMainContactRace = mstbMasterTableByMainContactRace;
        this.aceIndicator = aceIndicator;
        this.pubbsFlag = pubbsFlag;
        this.fiFlag = fiFlag;
        this.recurringFlag = recurringFlag;
    }
    

   
    // Property accessors

    public String getApplicationNo() {
        return this.applicationNo;
    }
    
    public void setApplicationNo(String applicationNo) {
        this.applicationNo = applicationNo;
    }

    public Timestamp getApplicationDt() {
        return this.applicationDt;
    }
    
    public void setApplicationDt(Timestamp applicationDt) {
        this.applicationDt = applicationDt;
    }

    public String getApplicantName() {
        return this.applicantName;
    }
    
    public void setApplicantName(String applicantName) {
        this.applicantName = applicantName;
    }

    public String getRcbNo() {
        return this.rcbNo;
    }
    
    public void setRcbNo(String rcbNo) {
        this.rcbNo = rcbNo;
    }

    public Timestamp getRcbDt() {
        return this.rcbDt;
    }
    
    public void setRcbDt(Timestamp rcbDt) {
        this.rcbDt = rcbDt;
    }

    public BigDecimal getCapital() {
        return this.capital;
    }
    
    public void setCapital(BigDecimal capital) {
        this.capital = capital;
    }

    public String getAddressBlock() {
        return this.addressBlock;
    }
    
    public void setAddressBlock(String addressBlock) {
        this.addressBlock = addressBlock;
    }

    public String getAddressUnit() {
        return this.addressUnit;
    }
    
    public void setAddressUnit(String addressUnit) {
        this.addressUnit = addressUnit;
    }

    public String getAddressStreet() {
        return this.addressStreet;
    }
    
    public void setAddressStreet(String addressStreet) {
        this.addressStreet = addressStreet;
    }

    public String getAddressBuilding() {
        return this.addressBuilding;
    }
    
    public void setAddressBuilding(String addressBuilding) {
        this.addressBuilding = addressBuilding;
    }

    public String getAddressArea() {
        return this.addressArea;
    }
    
    public void setAddressArea(String addressArea) {
        this.addressArea = addressArea;
    }

    public String getAddressCity() {
        return this.addressCity;
    }
    
    public void setAddressCity(String addressCity) {
        this.addressCity = addressCity;
    }

    public String getAddressState() {
        return this.addressState;
    }
    
    public void setAddressState(String addressState) {
        this.addressState = addressState;
    }

    public String getAddressPostal() {
        return this.addressPostal;
    }
    
    public void setAddressPostal(String addressPostal) {
        this.addressPostal = addressPostal;
    }

    public String getAuthPerson() {
        return this.authPerson;
    }
    
    public void setAuthPerson(String authPerson) {
        this.authPerson = authPerson;
    }

    public String getAuthTitle() {
        return this.authTitle;
    }
    
    public void setAuthTitle(String authTitle) {
        this.authTitle = authTitle;
    }

    public BigDecimal getCreditLimit() {
        return this.creditLimit;
    }
    
    public void setCreditLimit(BigDecimal creditLimit) {
        this.creditLimit = creditLimit;
    }

    public BigDecimal getDeposit() {
        return this.deposit;
    }
    
    public void setDeposit(BigDecimal deposit) {
        this.deposit = deposit;
    }

    public String getNameOnCard() {
        return this.nameOnCard;
    }
    
    public void setNameOnCard(String nameOnCard) {
        this.nameOnCard = nameOnCard;
    }

    public String getNric() {
        return this.nric;
    }
    
    public void setNric(String nric) {
        this.nric = nric;
    }

    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getOffice() {
        return this.office;
    }
    
    public void setOffice(String office) {
        this.office = office;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getBillingSame() {
        return this.billingSame;
    }
    
    public void setBillingSame(String billingSame) {
        this.billingSame = billingSame;
    }

    public String getBillingBlock() {
        return this.billingBlock;
    }
    
    public void setBillingBlock(String billingBlock) {
        this.billingBlock = billingBlock;
    }

    public String getBillingUnit() {
        return this.billingUnit;
    }
    
    public void setBillingUnit(String billingUnit) {
        this.billingUnit = billingUnit;
    }

    public String getBillingStreet() {
        return this.billingStreet;
    }
    
    public void setBillingStreet(String billingStreet) {
        this.billingStreet = billingStreet;
    }

    public String getBillingBuilding() {
        return this.billingBuilding;
    }
    
    public void setBillingBuilding(String billingBuilding) {
        this.billingBuilding = billingBuilding;
    }

    public String getBillingArea() {
        return this.billingArea;
    }
    
    public void setBillingArea(String billingArea) {
        this.billingArea = billingArea;
    }

    public String getBillingPostal() {
        return this.billingPostal;
    }
    
    public void setBillingPostal(String billingPostal) {
        this.billingPostal = billingPostal;
    }

    public String getBillingCity() {
        return this.billingCity;
    }
    
    public void setBillingCity(String billingCity) {
        this.billingCity = billingCity;
    }

    public String getBillingState() {
        return this.billingState;
    }
    
    public void setBillingState(String billingState) {
        this.billingState = billingState;
    }

    public String getShippingSame() {
        return this.shippingSame;
    }
    
    public void setShippingSame(String shippingSame) {
        this.shippingSame = shippingSame;
    }

    public String getShippingBlock() {
        return this.shippingBlock;
    }
    
    public void setShippingBlock(String shippingBlock) {
        this.shippingBlock = shippingBlock;
    }

    public String getShippingUnit() {
        return this.shippingUnit;
    }
    
    public void setShippingUnit(String shippingUnit) {
        this.shippingUnit = shippingUnit;
    }

    public String getShippingStreet() {
        return this.shippingStreet;
    }
    
    public void setShippingStreet(String shippingStreet) {
        this.shippingStreet = shippingStreet;
    }

    public String getShippingBuilding() {
        return this.shippingBuilding;
    }
    
    public void setShippingBuilding(String shippingBuilding) {
        this.shippingBuilding = shippingBuilding;
    }

    public String getShippingArea() {
        return this.shippingArea;
    }
    
    public void setShippingArea(String shippingArea) {
        this.shippingArea = shippingArea;
    }

    public String getShippingPostal() {
        return this.shippingPostal;
    }
    
    public void setShippingPostal(String shippingPostal) {
        this.shippingPostal = shippingPostal;
    }

    public String getShippingCity() {
        return this.shippingCity;
    }
    
    public void setShippingCity(String shippingCity) {
        this.shippingCity = shippingCity;
    }

    public String getShippingState() {
        return this.shippingState;
    }
    
    public void setShippingState(String shippingState) {
        this.shippingState = shippingState;
    }

    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    public String getEmployerName() {
        return this.employerName;
    }
    
    public void setEmployerName(String employerName) {
        this.employerName = employerName;
    }

    public String getEmployerBlock() {
        return this.employerBlock;
    }
    
    public void setEmployerBlock(String employerBlock) {
        this.employerBlock = employerBlock;
    }

    public String getEmployerUnit() {
        return this.employerUnit;
    }
    
    public void setEmployerUnit(String employerUnit) {
        this.employerUnit = employerUnit;
    }

    public String getEmployerStreet() {
        return this.employerStreet;
    }
    
    public void setEmployerStreet(String employerStreet) {
        this.employerStreet = employerStreet;
    }

    public String getEmployerBuilding() {
        return this.employerBuilding;
    }
    
    public void setEmployerBuilding(String employerBuilding) {
        this.employerBuilding = employerBuilding;
    }

    public String getEmployerArea() {
        return this.employerArea;
    }
    
    public void setEmployerArea(String employerArea) {
        this.employerArea = employerArea;
    }

    public String getEmployerPostal() {
        return this.employerPostal;
    }
    
    public void setEmployerPostal(String employerPostal) {
        this.employerPostal = employerPostal;
    }

    public String getEmployerCity() {
        return this.employerCity;
    }
    
    public void setEmployerCity(String employerCity) {
        this.employerCity = employerCity;
    }

    public String getEmployerState() {
        return this.employerState;
    }
    
    public void setEmployerState(String employerState) {
        this.employerState = employerState;
    }

    public BigDecimal getMonthlyIncome() {
        return this.monthlyIncome;
    }
    
    public void setMonthlyIncome(BigDecimal monthlyIncome) {
        this.monthlyIncome = monthlyIncome;
    }

    public Integer getEmployYears() {
        return this.employYears;
    }
    
    public void setEmployYears(Integer employYears) {
        this.employYears = employYears;
    }

    public String getProjectCode() {
        return this.projectCode;
    }
    
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }
    
    public String getEinvoiceFlag() {
        return this.einvoiceFlag;
    }
    
    public void setEinvoiceFlag(String einvoiceFlag) {
        this.einvoiceFlag = einvoiceFlag;
    }
    
	public String getInvoicePrinting() {
		return this.invoicePrinting;
	}

	public void setInvoicePrinting(String invoicePrinting) {
		this.invoicePrinting = invoicePrinting;
	}
    
    public String getSmsFlag() {
        return this.smsFlag;
    }
    
    public void setSmsFlag(String smsFlag) {
        this.smsFlag = smsFlag;
    }
    
    public String getSmsExpiryFlag() {
		return this.smsExpiryFlag;
	}

	public void setSmsExpiryFlag(String smsExpiryFlag) {
		this.smsExpiryFlag = smsExpiryFlag;
	}
	
	public String getSmsTopupFlag() {
		return this.smsTopupFlag;
	}

	public void setSmsTopupFlag(String smsTopupFlag) {
		this.smsTopupFlag = smsTopupFlag;
	}


    public MstbEarlyPaymentMaster getMstbEarlyPaymentMaster() {
        return this.mstbEarlyPaymentMaster;
    }
    
    public void setMstbEarlyPaymentMaster(MstbEarlyPaymentMaster mstbEarlyPaymentMaster) {
        this.mstbEarlyPaymentMaster = mstbEarlyPaymentMaster;
    }

    public MstbMasterTable getMstbMasterTableByBillingCountry() {
        return this.mstbMasterTableByBillingCountry;
    }
    
    public void setMstbMasterTableByBillingCountry(MstbMasterTable mstbMasterTableByBillingCountry) {
        this.mstbMasterTableByBillingCountry = mstbMasterTableByBillingCountry;
    }

    public MstbMasterTable getMstbMasterTableByEmployerCountry() {
        return this.mstbMasterTableByEmployerCountry;
    }
    
    public void setMstbMasterTableByEmployerCountry(MstbMasterTable mstbMasterTableByEmployerCountry) {
        this.mstbMasterTableByEmployerCountry = mstbMasterTableByEmployerCountry;
    }

    public MstbMasterTable getMstbMasterTableByJobStatus() {
        return this.mstbMasterTableByJobStatus;
    }
    
    public void setMstbMasterTableByJobStatus(MstbMasterTable mstbMasterTableByJobStatus) {
        this.mstbMasterTableByJobStatus = mstbMasterTableByJobStatus;
    }

    public MstbMasterTable getMstbMasterTableByAuthSal() {
        return this.mstbMasterTableByAuthSal;
    }
    
    public void setMstbMasterTableByAuthSal(MstbMasterTable mstbMasterTableByAuthSal) {
        this.mstbMasterTableByAuthSal = mstbMasterTableByAuthSal;
    }

    public MstbMasterTable getMstbMasterTableByShippingCountry() {
        return this.mstbMasterTableByShippingCountry;
    }
    
    public void setMstbMasterTableByShippingCountry(MstbMasterTable mstbMasterTableByShippingCountry) {
        this.mstbMasterTableByShippingCountry = mstbMasterTableByShippingCountry;
    }

    public MstbMasterTable getMstbMasterTableByIndustryNo() {
        return this.mstbMasterTableByIndustryNo;
    }
    
    public void setMstbMasterTableByIndustryNo(MstbMasterTable mstbMasterTableByIndustryNo) {
        this.mstbMasterTableByIndustryNo = mstbMasterTableByIndustryNo;
    }

    public MstbMasterTable getMstbMasterTableByInformationSource() {
        return this.mstbMasterTableByInformationSource;
    }
    
    public void setMstbMasterTableByInformationSource(MstbMasterTable mstbMasterTableByInformationSource) {
        this.mstbMasterTableByInformationSource = mstbMasterTableByInformationSource;
    }

    public MstbMasterTable getMstbMasterTableByAddressCountry() {
        return this.mstbMasterTableByAddressCountry;
    }
    
    public void setMstbMasterTableByAddressCountry(MstbMasterTable mstbMasterTableByAddressCountry) {
        this.mstbMasterTableByAddressCountry = mstbMasterTableByAddressCountry;
    }

    public MstbSalesperson getMstbSalesperson() {
        return this.mstbSalesperson;
    }
    
    public void setMstbSalesperson(MstbSalesperson mstbSalesperson) {
        this.mstbSalesperson = mstbSalesperson;
    }

    public FmtbArContCodeMaster getFmtbArContCodeMaster() {
        return this.fmtbArContCodeMaster;
    }
    
    public void setFmtbArContCodeMaster(FmtbArContCodeMaster fmtbArContCodeMaster) {
        this.fmtbArContCodeMaster = fmtbArContCodeMaster;
    }

    public Set<AmtbApplicationProduct> getAmtbApplicationProducts() {
        return this.amtbApplicationProducts;
    }
    
    public void setAmtbApplicationProducts(Set<AmtbApplicationProduct> amtbApplicationProducts) {
        this.amtbApplicationProducts = amtbApplicationProducts;
    }

    public Set<AmtbApplicationFlow> getAmtbApplicationFlows() {
        return this.amtbApplicationFlows;
    }
    
    public void setAmtbApplicationFlows(Set<AmtbApplicationFlow> amtbApplicationFlows) {
        this.amtbApplicationFlows = amtbApplicationFlows;
    }

    public AmtbAcctType getAmtbAcctType() {
        return this.amtbAcctType;
    }
    
    public void setAmtbAcctType(AmtbAcctType amtbAcctType) {
        this.amtbAcctType = amtbAcctType;
    }

    public AmtbAccount getAmtbAccount() {
        return this.amtbAccount;
    }
    
    public void setAmtbAccount(AmtbAccount amtbAccount) {
        this.amtbAccount = amtbAccount;
    }

    public MstbVolDiscMaster getMstbVolDiscMaster() {
        return this.mstbVolDiscMaster;
    }
    
    public void setMstbVolDiscMaster(MstbVolDiscMaster mstbVolDiscMaster) {
        this.mstbVolDiscMaster = mstbVolDiscMaster;
    }

    public MstbAdminFeeMaster getMstbAdminFeeMaster() {
        return this.mstbAdminFeeMaster;
    }
    
    public void setMstbAdminFeeMaster(MstbAdminFeeMaster mstbAdminFeeMaster) {
        this.mstbAdminFeeMaster = mstbAdminFeeMaster;
    }

    public MstbLatePaymentMaster getMstbLatePaymentMaster() {
        return this.mstbLatePaymentMaster;
    }
    
    public void setMstbLatePaymentMaster(MstbLatePaymentMaster mstbLatePaymentMaster) {
        this.mstbLatePaymentMaster = mstbLatePaymentMaster;
    }
   
    public String getInvoiceFormat() {
		return invoiceFormat;
	}


	public void setInvoiceFormat(String invoiceFormat) {
		this.invoiceFormat = invoiceFormat;
	}


	public String getInvoiceSorting() {
		return invoiceSorting;
	}


	public void setInvoiceSorting(String invoiceSorting) {
		this.invoiceSorting = invoiceSorting;
	}


	public String getGovtEInvoiceFlag() {
		return govtEInvoiceFlag;
	}


	public void setGovtEInvoiceFlag(String govtEInvoiceFlag) {
		this.govtEInvoiceFlag = govtEInvoiceFlag;
	}


	public Integer getBusinessUnitMasterNo() {
		return businessUnitMasterNo;
	}


	public void setBusinessUnitMasterNo(Integer businessUnitMasterNo) {
		this.businessUnitMasterNo = businessUnitMasterNo;
	}
	

	public String getOutsourcePrintingFlag() {
		return outsourcePrintingFlag;
	}


	public void setOutsourcePrintingFlag(String outsourcePrintingFlag) {
		this.outsourcePrintingFlag = outsourcePrintingFlag;
	}

	public String getPrintTaxInvoiceOnly() {
		return printTaxInvoiceOnly;
	}

	public void setPrintTaxInvoiceOnly(String printTaxInvoiceOnly) {
		this.printTaxInvoiceOnly = printTaxInvoiceOnly;
	}
	
    public MstbMasterTable getMstbMasterTableByMainContactRace() {
		return mstbMasterTableByMainContactRace;
	}

	public void setMstbMasterTableByMainContactRace(
			MstbMasterTable mstbMasterTableByMainContactRace) {
		this.mstbMasterTableByMainContactRace = mstbMasterTableByMainContactRace;
	}
	
	public String getAceIndicator() {
		return aceIndicator;
	}


	public void setAceIndicator(String aceIndicator) {
		this.aceIndicator = aceIndicator;
	}

	public String getPubbsFlag() {
		return pubbsFlag;
	}

	public void setPubbsFlag(String pubbsFlag) {
		this.pubbsFlag = pubbsFlag;
	}

	public String getFiFlag() {
		return fiFlag;
	}

	public void setFiFlag(String fiFlag) {
		this.fiFlag = fiFlag;
	}

	public String getRecurringFlag() {
		return recurringFlag;
	}

	public void setRecurringFlag(String recurringFlag) {
		this.recurringFlag = recurringFlag;
	}

	/**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("applicationDt").append("='").append(getApplicationDt()).append("' ");			
      buffer.append("applicantName").append("='").append(getApplicantName()).append("' ");			
      buffer.append("rcbNo").append("='").append(getRcbNo()).append("' ");			
      buffer.append("rcbDt").append("='").append(getRcbDt()).append("' ");			
      buffer.append("capital").append("='").append(getCapital()).append("' ");			
      buffer.append("addressBlock").append("='").append(getAddressBlock()).append("' ");			
      buffer.append("addressUnit").append("='").append(getAddressUnit()).append("' ");			
      buffer.append("addressStreet").append("='").append(getAddressStreet()).append("' ");			
      buffer.append("addressBuilding").append("='").append(getAddressBuilding()).append("' ");			
      buffer.append("addressArea").append("='").append(getAddressArea()).append("' ");			
      buffer.append("addressCity").append("='").append(getAddressCity()).append("' ");			
      buffer.append("addressState").append("='").append(getAddressState()).append("' ");			
      buffer.append("addressPostal").append("='").append(getAddressPostal()).append("' ");			
      buffer.append("authPerson").append("='").append(getAuthPerson()).append("' ");			
      buffer.append("authTitle").append("='").append(getAuthTitle()).append("' ");			
      buffer.append("creditLimit").append("='").append(getCreditLimit()).append("' ");			
      buffer.append("deposit").append("='").append(getDeposit()).append("' ");			
      buffer.append("nameOnCard").append("='").append(getNameOnCard()).append("' ");			
      buffer.append("nric").append("='").append(getNric()).append("' ");			
      buffer.append("tel").append("='").append(getTel()).append("' ");			
      buffer.append("fax").append("='").append(getFax()).append("' ");			
      buffer.append("mobile").append("='").append(getMobile()).append("' ");			
      buffer.append("office").append("='").append(getOffice()).append("' ");			
      buffer.append("email").append("='").append(getEmail()).append("' ");			
      buffer.append("billingSame").append("='").append(getBillingSame()).append("' ");			
      buffer.append("billingBlock").append("='").append(getBillingBlock()).append("' ");			
      buffer.append("billingUnit").append("='").append(getBillingUnit()).append("' ");			
      buffer.append("billingStreet").append("='").append(getBillingStreet()).append("' ");			
      buffer.append("billingBuilding").append("='").append(getBillingBuilding()).append("' ");			
      buffer.append("billingArea").append("='").append(getBillingArea()).append("' ");			
      buffer.append("billingPostal").append("='").append(getBillingPostal()).append("' ");			
      buffer.append("billingCity").append("='").append(getBillingCity()).append("' ");			
      buffer.append("billingState").append("='").append(getBillingState()).append("' ");			
      buffer.append("shippingSame").append("='").append(getShippingSame()).append("' ");			
      buffer.append("shippingBlock").append("='").append(getShippingBlock()).append("' ");			
      buffer.append("shippingUnit").append("='").append(getShippingUnit()).append("' ");			
      buffer.append("shippingStreet").append("='").append(getShippingStreet()).append("' ");			
      buffer.append("shippingBuilding").append("='").append(getShippingBuilding()).append("' ");			
      buffer.append("shippingArea").append("='").append(getShippingArea()).append("' ");			
      buffer.append("shippingPostal").append("='").append(getShippingPostal()).append("' ");			
      buffer.append("shippingCity").append("='").append(getShippingCity()).append("' ");			
      buffer.append("shippingState").append("='").append(getShippingState()).append("' ");			
      buffer.append("occupation").append("='").append(getOccupation()).append("' ");			
      buffer.append("employerName").append("='").append(getEmployerName()).append("' ");			
      buffer.append("employerBlock").append("='").append(getEmployerBlock()).append("' ");			
      buffer.append("employerUnit").append("='").append(getEmployerUnit()).append("' ");			
      buffer.append("employerStreet").append("='").append(getEmployerStreet()).append("' ");			
      buffer.append("employerBuilding").append("='").append(getEmployerBuilding()).append("' ");			
      buffer.append("employerArea").append("='").append(getEmployerArea()).append("' ");			
      buffer.append("employerPostal").append("='").append(getEmployerPostal()).append("' ");			
      buffer.append("employerCity").append("='").append(getEmployerCity()).append("' ");			
      buffer.append("employerState").append("='").append(getEmployerState()).append("' ");			
      buffer.append("monthlyIncome").append("='").append(getMonthlyIncome()).append("' ");			
      buffer.append("employYears").append("='").append(getEmployYears()).append("' ");			
      buffer.append("projectCode").append("='").append(getProjectCode()).append("' ");			
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("einvoiceFlag").append("='").append(getEinvoiceFlag()).append("' ");
      buffer.append("invoicePrinting").append("='").append(getInvoicePrinting()).append("' ");
      buffer.append("outsourcePrintingFlag").append("='").append(getOutsourcePrintingFlag()).append("' ");
      buffer.append("smsFlag").append("='").append(getSmsFlag()).append("' ");
      buffer.append("smsExpiryFlag").append("='").append(getSmsExpiryFlag()).append("' ");
	  buffer.append("smsTopupFlag").append("='").append(getSmsTopupFlag()).append("' ");
	  buffer.append("invoiceFormat").append("='").append(getInvoiceFormat()).append("' ");
	  buffer.append("invoiceSorting").append("='").append(getInvoiceSorting()).append("' ");
	  buffer.append("govtEInvoiceFlag").append("='").append(getGovtEInvoiceFlag()).append("' ");
	  buffer.append("businessUnitMasterNo").append("='").append(getBusinessUnitMasterNo()).append("' ");
	  buffer.append("printTaxInvoiceOnly").append("='").append(getPrintTaxInvoiceOnly()).append("' ");
	  buffer.append("aceIndicator").append("='").append(getAceIndicator()).append("' ");
	  buffer.append("pubbsFlag").append("='").append(getPubbsFlag()).append("' ");
	  buffer.append("fiFlag").append("='").append(getFiFlag()).append("' ");
	  buffer.append("recurringFlag").append("='").append(getRecurringFlag()).append("' ");
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmtbApplication) ) return false;
		 AmtbApplication castOther = ( AmtbApplication ) other; 
         
		 return ( (this.getApplicationNo()==castOther.getApplicationNo()) || ( this.getApplicationNo()!=null && castOther.getApplicationNo()!=null && this.getApplicationNo().equals(castOther.getApplicationNo()) ) )
 && ( (this.getApplicationDt()==castOther.getApplicationDt()) || ( this.getApplicationDt()!=null && castOther.getApplicationDt()!=null && this.getApplicationDt().equals(castOther.getApplicationDt()) ) )
 && ( (this.getApplicantName()==castOther.getApplicantName()) || ( this.getApplicantName()!=null && castOther.getApplicantName()!=null && this.getApplicantName().equals(castOther.getApplicantName()) ) )
 && ( (this.getRcbNo()==castOther.getRcbNo()) || ( this.getRcbNo()!=null && castOther.getRcbNo()!=null && this.getRcbNo().equals(castOther.getRcbNo()) ) )
 && ( (this.getRcbDt()==castOther.getRcbDt()) || ( this.getRcbDt()!=null && castOther.getRcbDt()!=null && this.getRcbDt().equals(castOther.getRcbDt()) ) )
 && ( (this.getCapital()==castOther.getCapital()) || ( this.getCapital()!=null && castOther.getCapital()!=null && this.getCapital().equals(castOther.getCapital()) ) )
 && ( (this.getAddressBlock()==castOther.getAddressBlock()) || ( this.getAddressBlock()!=null && castOther.getAddressBlock()!=null && this.getAddressBlock().equals(castOther.getAddressBlock()) ) )
 && ( (this.getAddressUnit()==castOther.getAddressUnit()) || ( this.getAddressUnit()!=null && castOther.getAddressUnit()!=null && this.getAddressUnit().equals(castOther.getAddressUnit()) ) )
 && ( (this.getAddressStreet()==castOther.getAddressStreet()) || ( this.getAddressStreet()!=null && castOther.getAddressStreet()!=null && this.getAddressStreet().equals(castOther.getAddressStreet()) ) )
 && ( (this.getAddressBuilding()==castOther.getAddressBuilding()) || ( this.getAddressBuilding()!=null && castOther.getAddressBuilding()!=null && this.getAddressBuilding().equals(castOther.getAddressBuilding()) ) )
 && ( (this.getAddressArea()==castOther.getAddressArea()) || ( this.getAddressArea()!=null && castOther.getAddressArea()!=null && this.getAddressArea().equals(castOther.getAddressArea()) ) )
 && ( (this.getAddressCity()==castOther.getAddressCity()) || ( this.getAddressCity()!=null && castOther.getAddressCity()!=null && this.getAddressCity().equals(castOther.getAddressCity()) ) )
 && ( (this.getAddressState()==castOther.getAddressState()) || ( this.getAddressState()!=null && castOther.getAddressState()!=null && this.getAddressState().equals(castOther.getAddressState()) ) )
 && ( (this.getAddressPostal()==castOther.getAddressPostal()) || ( this.getAddressPostal()!=null && castOther.getAddressPostal()!=null && this.getAddressPostal().equals(castOther.getAddressPostal()) ) )
 && ( (this.getAuthPerson()==castOther.getAuthPerson()) || ( this.getAuthPerson()!=null && castOther.getAuthPerson()!=null && this.getAuthPerson().equals(castOther.getAuthPerson()) ) )
 && ( (this.getAuthTitle()==castOther.getAuthTitle()) || ( this.getAuthTitle()!=null && castOther.getAuthTitle()!=null && this.getAuthTitle().equals(castOther.getAuthTitle()) ) )
 && ( (this.getCreditLimit()==castOther.getCreditLimit()) || ( this.getCreditLimit()!=null && castOther.getCreditLimit()!=null && this.getCreditLimit().equals(castOther.getCreditLimit()) ) )
 && ( (this.getDeposit()==castOther.getDeposit()) || ( this.getDeposit()!=null && castOther.getDeposit()!=null && this.getDeposit().equals(castOther.getDeposit()) ) )
 && ( (this.getNameOnCard()==castOther.getNameOnCard()) || ( this.getNameOnCard()!=null && castOther.getNameOnCard()!=null && this.getNameOnCard().equals(castOther.getNameOnCard()) ) )
 && ( (this.getNric()==castOther.getNric()) || ( this.getNric()!=null && castOther.getNric()!=null && this.getNric().equals(castOther.getNric()) ) )
 && ( (this.getTel()==castOther.getTel()) || ( this.getTel()!=null && castOther.getTel()!=null && this.getTel().equals(castOther.getTel()) ) )
 && ( (this.getFax()==castOther.getFax()) || ( this.getFax()!=null && castOther.getFax()!=null && this.getFax().equals(castOther.getFax()) ) )
 && ( (this.getMobile()==castOther.getMobile()) || ( this.getMobile()!=null && castOther.getMobile()!=null && this.getMobile().equals(castOther.getMobile()) ) )
 && ( (this.getOffice()==castOther.getOffice()) || ( this.getOffice()!=null && castOther.getOffice()!=null && this.getOffice().equals(castOther.getOffice()) ) )
 && ( (this.getEmail()==castOther.getEmail()) || ( this.getEmail()!=null && castOther.getEmail()!=null && this.getEmail().equals(castOther.getEmail()) ) )
 && ( (this.getBillingSame()==castOther.getBillingSame()) || ( this.getBillingSame()!=null && castOther.getBillingSame()!=null && this.getBillingSame().equals(castOther.getBillingSame()) ) )
 && ( (this.getBillingBlock()==castOther.getBillingBlock()) || ( this.getBillingBlock()!=null && castOther.getBillingBlock()!=null && this.getBillingBlock().equals(castOther.getBillingBlock()) ) )
 && ( (this.getBillingUnit()==castOther.getBillingUnit()) || ( this.getBillingUnit()!=null && castOther.getBillingUnit()!=null && this.getBillingUnit().equals(castOther.getBillingUnit()) ) )
 && ( (this.getBillingStreet()==castOther.getBillingStreet()) || ( this.getBillingStreet()!=null && castOther.getBillingStreet()!=null && this.getBillingStreet().equals(castOther.getBillingStreet()) ) )
 && ( (this.getBillingBuilding()==castOther.getBillingBuilding()) || ( this.getBillingBuilding()!=null && castOther.getBillingBuilding()!=null && this.getBillingBuilding().equals(castOther.getBillingBuilding()) ) )
 && ( (this.getBillingArea()==castOther.getBillingArea()) || ( this.getBillingArea()!=null && castOther.getBillingArea()!=null && this.getBillingArea().equals(castOther.getBillingArea()) ) )
 && ( (this.getBillingPostal()==castOther.getBillingPostal()) || ( this.getBillingPostal()!=null && castOther.getBillingPostal()!=null && this.getBillingPostal().equals(castOther.getBillingPostal()) ) )
 && ( (this.getBillingCity()==castOther.getBillingCity()) || ( this.getBillingCity()!=null && castOther.getBillingCity()!=null && this.getBillingCity().equals(castOther.getBillingCity()) ) )
 && ( (this.getBillingState()==castOther.getBillingState()) || ( this.getBillingState()!=null && castOther.getBillingState()!=null && this.getBillingState().equals(castOther.getBillingState()) ) )
 && ( (this.getShippingSame()==castOther.getShippingSame()) || ( this.getShippingSame()!=null && castOther.getShippingSame()!=null && this.getShippingSame().equals(castOther.getShippingSame()) ) )
 && ( (this.getShippingBlock()==castOther.getShippingBlock()) || ( this.getShippingBlock()!=null && castOther.getShippingBlock()!=null && this.getShippingBlock().equals(castOther.getShippingBlock()) ) )
 && ( (this.getShippingUnit()==castOther.getShippingUnit()) || ( this.getShippingUnit()!=null && castOther.getShippingUnit()!=null && this.getShippingUnit().equals(castOther.getShippingUnit()) ) )
 && ( (this.getShippingStreet()==castOther.getShippingStreet()) || ( this.getShippingStreet()!=null && castOther.getShippingStreet()!=null && this.getShippingStreet().equals(castOther.getShippingStreet()) ) )
 && ( (this.getShippingBuilding()==castOther.getShippingBuilding()) || ( this.getShippingBuilding()!=null && castOther.getShippingBuilding()!=null && this.getShippingBuilding().equals(castOther.getShippingBuilding()) ) )
 && ( (this.getShippingArea()==castOther.getShippingArea()) || ( this.getShippingArea()!=null && castOther.getShippingArea()!=null && this.getShippingArea().equals(castOther.getShippingArea()) ) )
 && ( (this.getShippingPostal()==castOther.getShippingPostal()) || ( this.getShippingPostal()!=null && castOther.getShippingPostal()!=null && this.getShippingPostal().equals(castOther.getShippingPostal()) ) )
 && ( (this.getShippingCity()==castOther.getShippingCity()) || ( this.getShippingCity()!=null && castOther.getShippingCity()!=null && this.getShippingCity().equals(castOther.getShippingCity()) ) )
 && ( (this.getShippingState()==castOther.getShippingState()) || ( this.getShippingState()!=null && castOther.getShippingState()!=null && this.getShippingState().equals(castOther.getShippingState()) ) )
 && ( (this.getOccupation()==castOther.getOccupation()) || ( this.getOccupation()!=null && castOther.getOccupation()!=null && this.getOccupation().equals(castOther.getOccupation()) ) )
 && ( (this.getEmployerName()==castOther.getEmployerName()) || ( this.getEmployerName()!=null && castOther.getEmployerName()!=null && this.getEmployerName().equals(castOther.getEmployerName()) ) )
 && ( (this.getEmployerBlock()==castOther.getEmployerBlock()) || ( this.getEmployerBlock()!=null && castOther.getEmployerBlock()!=null && this.getEmployerBlock().equals(castOther.getEmployerBlock()) ) )
 && ( (this.getEmployerUnit()==castOther.getEmployerUnit()) || ( this.getEmployerUnit()!=null && castOther.getEmployerUnit()!=null && this.getEmployerUnit().equals(castOther.getEmployerUnit()) ) )
 && ( (this.getEmployerStreet()==castOther.getEmployerStreet()) || ( this.getEmployerStreet()!=null && castOther.getEmployerStreet()!=null && this.getEmployerStreet().equals(castOther.getEmployerStreet()) ) )
 && ( (this.getEmployerBuilding()==castOther.getEmployerBuilding()) || ( this.getEmployerBuilding()!=null && castOther.getEmployerBuilding()!=null && this.getEmployerBuilding().equals(castOther.getEmployerBuilding()) ) )
 && ( (this.getEmployerArea()==castOther.getEmployerArea()) || ( this.getEmployerArea()!=null && castOther.getEmployerArea()!=null && this.getEmployerArea().equals(castOther.getEmployerArea()) ) )
 && ( (this.getEmployerPostal()==castOther.getEmployerPostal()) || ( this.getEmployerPostal()!=null && castOther.getEmployerPostal()!=null && this.getEmployerPostal().equals(castOther.getEmployerPostal()) ) )
 && ( (this.getEmployerCity()==castOther.getEmployerCity()) || ( this.getEmployerCity()!=null && castOther.getEmployerCity()!=null && this.getEmployerCity().equals(castOther.getEmployerCity()) ) )
 && ( (this.getEmployerState()==castOther.getEmployerState()) || ( this.getEmployerState()!=null && castOther.getEmployerState()!=null && this.getEmployerState().equals(castOther.getEmployerState()) ) )
 && ( (this.getMonthlyIncome()==castOther.getMonthlyIncome()) || ( this.getMonthlyIncome()!=null && castOther.getMonthlyIncome()!=null && this.getMonthlyIncome().equals(castOther.getMonthlyIncome()) ) )
 && ( (this.getEmployYears()==castOther.getEmployYears()) || ( this.getEmployYears()!=null && castOther.getEmployYears()!=null && this.getEmployYears().equals(castOther.getEmployYears()) ) )
 && ( (this.getProjectCode()==castOther.getProjectCode()) || ( this.getProjectCode()!=null && castOther.getProjectCode()!=null && this.getProjectCode().equals(castOther.getProjectCode()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getEinvoiceFlag()==castOther.getEinvoiceFlag()) || ( this.getEinvoiceFlag()!=null && castOther.getEinvoiceFlag()!=null && this.getEinvoiceFlag().equals(castOther.getEinvoiceFlag()) ) )
 && ( (this.getOutsourcePrintingFlag()==castOther.getOutsourcePrintingFlag()) || ( this.getOutsourcePrintingFlag()!=null && castOther.getOutsourcePrintingFlag()!=null && this.getOutsourcePrintingFlag().equals(castOther.getOutsourcePrintingFlag()) ) )
 && ( (this.getInvoicePrinting() == castOther.getInvoicePrinting()) || (this.getInvoicePrinting() != null && castOther.getInvoicePrinting() != null && this.getInvoicePrinting().equals(castOther.getInvoicePrinting())))
 && ( (this.getAceIndicator() == castOther.getAceIndicator()) || (this.getAceIndicator() != null && castOther.getAceIndicator() != null && this.getAceIndicator().equals(castOther.getAceIndicator())))
 && ( (this.getSmsFlag()==castOther.getSmsFlag()) || ( this.getSmsFlag()!=null && castOther.getSmsFlag()!=null && this.getSmsFlag().equals(castOther.getSmsFlag()) ) )
 && ((this.getSmsExpiryFlag() == castOther.getSmsExpiryFlag()) || (this.getSmsExpiryFlag() != null && castOther.getSmsExpiryFlag() != null && this.getSmsExpiryFlag().equals(castOther.getSmsExpiryFlag())))
 && ((this.getSmsTopupFlag() == castOther.getSmsTopupFlag()) || (this.getSmsTopupFlag() != null && castOther.getSmsTopupFlag() != null && this.getSmsTopupFlag().equals(castOther.getSmsTopupFlag())))	
 && ( (this.getMstbEarlyPaymentMaster()==castOther.getMstbEarlyPaymentMaster()) || ( this.getMstbEarlyPaymentMaster()!=null && castOther.getMstbEarlyPaymentMaster()!=null && this.getMstbEarlyPaymentMaster().equals(castOther.getMstbEarlyPaymentMaster()) ) )
 && ( (this.getMstbMasterTableByBillingCountry()==castOther.getMstbMasterTableByBillingCountry()) || ( this.getMstbMasterTableByBillingCountry()!=null && castOther.getMstbMasterTableByBillingCountry()!=null && this.getMstbMasterTableByBillingCountry().equals(castOther.getMstbMasterTableByBillingCountry()) ) )
 && ( (this.getMstbMasterTableByEmployerCountry()==castOther.getMstbMasterTableByEmployerCountry()) || ( this.getMstbMasterTableByEmployerCountry()!=null && castOther.getMstbMasterTableByEmployerCountry()!=null && this.getMstbMasterTableByEmployerCountry().equals(castOther.getMstbMasterTableByEmployerCountry()) ) )
 && ( (this.getMstbMasterTableByJobStatus()==castOther.getMstbMasterTableByJobStatus()) || ( this.getMstbMasterTableByJobStatus()!=null && castOther.getMstbMasterTableByJobStatus()!=null && this.getMstbMasterTableByJobStatus().equals(castOther.getMstbMasterTableByJobStatus()) ) )
 && ( (this.getMstbMasterTableByAuthSal()==castOther.getMstbMasterTableByAuthSal()) || ( this.getMstbMasterTableByAuthSal()!=null && castOther.getMstbMasterTableByAuthSal()!=null && this.getMstbMasterTableByAuthSal().equals(castOther.getMstbMasterTableByAuthSal()) ) )
 && ( (this.getMstbMasterTableByShippingCountry()==castOther.getMstbMasterTableByShippingCountry()) || ( this.getMstbMasterTableByShippingCountry()!=null && castOther.getMstbMasterTableByShippingCountry()!=null && this.getMstbMasterTableByShippingCountry().equals(castOther.getMstbMasterTableByShippingCountry()) ) )
 && ( (this.getMstbMasterTableByIndustryNo()==castOther.getMstbMasterTableByIndustryNo()) || ( this.getMstbMasterTableByIndustryNo()!=null && castOther.getMstbMasterTableByIndustryNo()!=null && this.getMstbMasterTableByIndustryNo().equals(castOther.getMstbMasterTableByIndustryNo()) ) )
 && ( (this.getMstbMasterTableByInformationSource()==castOther.getMstbMasterTableByInformationSource()) || ( this.getMstbMasterTableByInformationSource()!=null && castOther.getMstbMasterTableByInformationSource()!=null && this.getMstbMasterTableByInformationSource().equals(castOther.getMstbMasterTableByInformationSource()) ) )
 && ( (this.getMstbMasterTableByAddressCountry()==castOther.getMstbMasterTableByAddressCountry()) || ( this.getMstbMasterTableByAddressCountry()!=null && castOther.getMstbMasterTableByAddressCountry()!=null && this.getMstbMasterTableByAddressCountry().equals(castOther.getMstbMasterTableByAddressCountry()) ) )
 && ( (this.getMstbSalesperson()==castOther.getMstbSalesperson()) || ( this.getMstbSalesperson()!=null && castOther.getMstbSalesperson()!=null && this.getMstbSalesperson().equals(castOther.getMstbSalesperson()) ) )
 && ( (this.getFmtbArContCodeMaster()==castOther.getFmtbArContCodeMaster()) || ( this.getFmtbArContCodeMaster()!=null && castOther.getFmtbArContCodeMaster()!=null && this.getFmtbArContCodeMaster().equals(castOther.getFmtbArContCodeMaster()) ) )
 && ( (this.getAmtbAcctType()==castOther.getAmtbAcctType()) || ( this.getAmtbAcctType()!=null && castOther.getAmtbAcctType()!=null && this.getAmtbAcctType().equals(castOther.getAmtbAcctType()) ) )
 && ( (this.getAmtbAccount()==castOther.getAmtbAccount()) || ( this.getAmtbAccount()!=null && castOther.getAmtbAccount()!=null && this.getAmtbAccount().equals(castOther.getAmtbAccount()) ) )
 && ( (this.getMstbVolDiscMaster()==castOther.getMstbVolDiscMaster()) || ( this.getMstbVolDiscMaster()!=null && castOther.getMstbVolDiscMaster()!=null && this.getMstbVolDiscMaster().equals(castOther.getMstbVolDiscMaster()) ) )
 && ( (this.getMstbAdminFeeMaster()==castOther.getMstbAdminFeeMaster()) || ( this.getMstbAdminFeeMaster()!=null && castOther.getMstbAdminFeeMaster()!=null && this.getMstbAdminFeeMaster().equals(castOther.getMstbAdminFeeMaster()) ) )
 && ( (this.getMstbLatePaymentMaster()==castOther.getMstbLatePaymentMaster()) || ( this.getMstbLatePaymentMaster()!=null && castOther.getMstbLatePaymentMaster()!=null && this.getMstbLatePaymentMaster().equals(castOther.getMstbLatePaymentMaster()) ) )
 && ( (this.getInvoiceSorting() == castOther.getInvoiceSorting()) || (this.getInvoiceSorting() != null && castOther.getInvoiceSorting() != null && this.getInvoiceSorting().equals(castOther.getInvoiceSorting())))
 && ( (this.getInvoiceFormat() == castOther.getInvoiceFormat()) || (this.getInvoiceFormat() != null && castOther.getInvoiceFormat() != null && this.getInvoiceFormat().equals(castOther.getInvoiceFormat())))
 && ( (this.getGovtEInvoiceFlag() == castOther.getGovtEInvoiceFlag()) || (this.getGovtEInvoiceFlag() != null && castOther.getGovtEInvoiceFlag() != null && this.getGovtEInvoiceFlag().equals(castOther.getGovtEInvoiceFlag())))
 && ( (this.getPubbsFlag() == castOther.getPubbsFlag()) || (this.getPubbsFlag() != null && castOther.getPubbsFlag() != null && this.getPubbsFlag().equals(castOther.getPubbsFlag())))
 && ( (this.getFiFlag() == castOther.getFiFlag()) || (this.getFiFlag() != null && castOther.getFiFlag() != null && this.getFiFlag().equals(castOther.getFiFlag())))
 && ( (this.getRecurringFlag() == castOther.getRecurringFlag()) || (this.getRecurringFlag() != null && castOther.getRecurringFlag() != null && this.getRecurringFlag().equals(castOther.getRecurringFlag())))
 && ( (this.getMstbMasterTableByMainContactRace()==castOther.getMstbMasterTableByMainContactRace()) || ( this.getMstbMasterTableByMainContactRace()!=null && castOther.getMstbMasterTableByMainContactRace()!=null && this.getMstbMasterTableByMainContactRace().equals(castOther.getMstbMasterTableByMainContactRace()) ) )
 && ( (this.getBusinessUnitMasterNo() == castOther.getBusinessUnitMasterNo()) || (this.getBusinessUnitMasterNo() != null && castOther.getBusinessUnitMasterNo() != null && this.getBusinessUnitMasterNo().equals(castOther.getBusinessUnitMasterNo())));

   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getApplicationNo() == null ? 0 : this.getApplicationNo().hashCode() );
         result = 37 * result + ( getApplicationDt() == null ? 0 : this.getApplicationDt().hashCode() );
         result = 37 * result + ( getApplicantName() == null ? 0 : this.getApplicantName().hashCode() );
         result = 37 * result + ( getRcbNo() == null ? 0 : this.getRcbNo().hashCode() );
         result = 37 * result + ( getRcbDt() == null ? 0 : this.getRcbDt().hashCode() );
         result = 37 * result + ( getCapital() == null ? 0 : this.getCapital().hashCode() );
         result = 37 * result + ( getAddressBlock() == null ? 0 : this.getAddressBlock().hashCode() );
         result = 37 * result + ( getAddressUnit() == null ? 0 : this.getAddressUnit().hashCode() );
         result = 37 * result + ( getAddressStreet() == null ? 0 : this.getAddressStreet().hashCode() );
         result = 37 * result + ( getAddressBuilding() == null ? 0 : this.getAddressBuilding().hashCode() );
         result = 37 * result + ( getAddressArea() == null ? 0 : this.getAddressArea().hashCode() );
         result = 37 * result + ( getAddressCity() == null ? 0 : this.getAddressCity().hashCode() );
         result = 37 * result + ( getAddressState() == null ? 0 : this.getAddressState().hashCode() );
         result = 37 * result + ( getAddressPostal() == null ? 0 : this.getAddressPostal().hashCode() );
         result = 37 * result + ( getAuthPerson() == null ? 0 : this.getAuthPerson().hashCode() );
         result = 37 * result + ( getAuthTitle() == null ? 0 : this.getAuthTitle().hashCode() );
         result = 37 * result + ( getCreditLimit() == null ? 0 : this.getCreditLimit().hashCode() );
         result = 37 * result + ( getDeposit() == null ? 0 : this.getDeposit().hashCode() );
         result = 37 * result + ( getNameOnCard() == null ? 0 : this.getNameOnCard().hashCode() );
         result = 37 * result + ( getNric() == null ? 0 : this.getNric().hashCode() );
         result = 37 * result + ( getTel() == null ? 0 : this.getTel().hashCode() );
         result = 37 * result + ( getFax() == null ? 0 : this.getFax().hashCode() );
         result = 37 * result + ( getMobile() == null ? 0 : this.getMobile().hashCode() );
         result = 37 * result + ( getOffice() == null ? 0 : this.getOffice().hashCode() );
         result = 37 * result + ( getEmail() == null ? 0 : this.getEmail().hashCode() );
         result = 37 * result + ( getBillingSame() == null ? 0 : this.getBillingSame().hashCode() );
         result = 37 * result + ( getBillingBlock() == null ? 0 : this.getBillingBlock().hashCode() );
         result = 37 * result + ( getBillingUnit() == null ? 0 : this.getBillingUnit().hashCode() );
         result = 37 * result + ( getBillingStreet() == null ? 0 : this.getBillingStreet().hashCode() );
         result = 37 * result + ( getBillingBuilding() == null ? 0 : this.getBillingBuilding().hashCode() );
         result = 37 * result + ( getBillingArea() == null ? 0 : this.getBillingArea().hashCode() );
         result = 37 * result + ( getBillingPostal() == null ? 0 : this.getBillingPostal().hashCode() );
         result = 37 * result + ( getBillingCity() == null ? 0 : this.getBillingCity().hashCode() );
         result = 37 * result + ( getBillingState() == null ? 0 : this.getBillingState().hashCode() );
         result = 37 * result + ( getShippingSame() == null ? 0 : this.getShippingSame().hashCode() );
         result = 37 * result + ( getShippingBlock() == null ? 0 : this.getShippingBlock().hashCode() );
         result = 37 * result + ( getShippingUnit() == null ? 0 : this.getShippingUnit().hashCode() );
         result = 37 * result + ( getShippingStreet() == null ? 0 : this.getShippingStreet().hashCode() );
         result = 37 * result + ( getShippingBuilding() == null ? 0 : this.getShippingBuilding().hashCode() );
         result = 37 * result + ( getShippingArea() == null ? 0 : this.getShippingArea().hashCode() );
         result = 37 * result + ( getShippingPostal() == null ? 0 : this.getShippingPostal().hashCode() );
         result = 37 * result + ( getShippingCity() == null ? 0 : this.getShippingCity().hashCode() );
         result = 37 * result + ( getShippingState() == null ? 0 : this.getShippingState().hashCode() );
         result = 37 * result + ( getOccupation() == null ? 0 : this.getOccupation().hashCode() );
         result = 37 * result + ( getEmployerName() == null ? 0 : this.getEmployerName().hashCode() );
         result = 37 * result + ( getEmployerBlock() == null ? 0 : this.getEmployerBlock().hashCode() );
         result = 37 * result + ( getEmployerUnit() == null ? 0 : this.getEmployerUnit().hashCode() );
         result = 37 * result + ( getEmployerStreet() == null ? 0 : this.getEmployerStreet().hashCode() );
         result = 37 * result + ( getEmployerBuilding() == null ? 0 : this.getEmployerBuilding().hashCode() );
         result = 37 * result + ( getEmployerArea() == null ? 0 : this.getEmployerArea().hashCode() );
         result = 37 * result + ( getEmployerPostal() == null ? 0 : this.getEmployerPostal().hashCode() );
         result = 37 * result + ( getEmployerCity() == null ? 0 : this.getEmployerCity().hashCode() );
         result = 37 * result + ( getEmployerState() == null ? 0 : this.getEmployerState().hashCode() );
         result = 37 * result + ( getMonthlyIncome() == null ? 0 : this.getMonthlyIncome().hashCode() );
         result = 37 * result + ( getEmployYears() == null ? 0 : this.getEmployYears().hashCode() );
         result = 37 * result + ( getProjectCode() == null ? 0 : this.getProjectCode().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getEinvoiceFlag() == null ? 0 : this.getEinvoiceFlag().hashCode() );
         result = 37 * result + ( getInvoicePrinting() == null ? 0 : this.getInvoicePrinting().hashCode());
         result = 37 * result + ( getSmsFlag() == null ? 0 : this.getSmsFlag().hashCode() );
         result = 37 * result + ( getSmsExpiryFlag() == null ? 0 : this.getSmsExpiryFlag().hashCode());
 		 result = 37 * result + ( getSmsTopupFlag() == null ? 0 : this.getSmsTopupFlag().hashCode());
         result = 37 * result + ( getMstbEarlyPaymentMaster() == null ? 0 : this.getMstbEarlyPaymentMaster().hashCode() );
         result = 37 * result + ( getMstbMasterTableByBillingCountry() == null ? 0 : this.getMstbMasterTableByBillingCountry().hashCode() );
         result = 37 * result + ( getMstbMasterTableByEmployerCountry() == null ? 0 : this.getMstbMasterTableByEmployerCountry().hashCode() );
         result = 37 * result + ( getMstbMasterTableByJobStatus() == null ? 0 : this.getMstbMasterTableByJobStatus().hashCode() );
         result = 37 * result + ( getMstbMasterTableByAuthSal() == null ? 0 : this.getMstbMasterTableByAuthSal().hashCode() );
         result = 37 * result + ( getMstbMasterTableByShippingCountry() == null ? 0 : this.getMstbMasterTableByShippingCountry().hashCode() );
         result = 37 * result + ( getMstbMasterTableByIndustryNo() == null ? 0 : this.getMstbMasterTableByIndustryNo().hashCode() );
         result = 37 * result + ( getMstbMasterTableByInformationSource() == null ? 0 : this.getMstbMasterTableByInformationSource().hashCode() );
         result = 37 * result + ( getMstbMasterTableByAddressCountry() == null ? 0 : this.getMstbMasterTableByAddressCountry().hashCode() );
         result = 37 * result + ( getMstbSalesperson() == null ? 0 : this.getMstbSalesperson().hashCode() );
         result = 37 * result + ( getFmtbArContCodeMaster() == null ? 0 : this.getFmtbArContCodeMaster().hashCode() );
         
         
         result = 37 * result + ( getAmtbAcctType() == null ? 0 : this.getAmtbAcctType().hashCode() );
         result = 37 * result + ( getAmtbAccount() == null ? 0 : this.getAmtbAccount().hashCode() );
         result = 37 * result + ( getMstbVolDiscMaster() == null ? 0 : this.getMstbVolDiscMaster().hashCode() );
         result = 37 * result + ( getMstbAdminFeeMaster() == null ? 0 : this.getMstbAdminFeeMaster().hashCode() );
         result = 37 * result + ( getMstbLatePaymentMaster() == null ? 0 : this.getMstbLatePaymentMaster().hashCode() );
         
         result = 37 * result + ( getInvoiceFormat() == null ? 0 : this.getInvoiceFormat().hashCode() );
         result = 37 * result + ( getInvoiceSorting() == null ? 0 : this.getInvoiceSorting().hashCode() );
         result = 37 * result + ( getGovtEInvoiceFlag() == null ? 0 : this.getGovtEInvoiceFlag().hashCode() );
         result = 37 * result + ( getBusinessUnitMasterNo() ==  null ? 0 : this.getBusinessUnitMasterNo().hashCode() );
         result = 37 * result + ( getOutsourcePrintingFlag() ==  null ? 0 : this.getOutsourcePrintingFlag().hashCode() );
         result = 37 * result + ( getPrintTaxInvoiceOnly() == null ? 0 : this.getPrintTaxInvoiceOnly().hashCode() );
         result = 37 * result + ( getMstbMasterTableByMainContactRace() == null ? 0 : this.getMstbMasterTableByMainContactRace().hashCode() );
         result = 37 * result + ( getAceIndicator() == null ? 0 : this.getAceIndicator().hashCode() );
         result = 37 * result + ( getPubbsFlag() == null ? 0 : this.getPubbsFlag().hashCode() );
         result = 37 * result + ( getFiFlag() == null ? 0 : this.getFiFlag().hashCode() );
         result = 37 * result + ( getRecurringFlag() == null ? 0 : this.getRecurringFlag().hashCode() );
         
         return result;
   }   
}
