package com.cdgtaxi.ibs.common.model;
// Generated Jul 20, 2009 4:09:48 PM by Hibernate Tools 3.1.0.beta4



/**
 * AmtbAcctMainContactPK generated by hbm2java
 */

public class AmtbAcctMainContactPK  implements java.io.Serializable {


    // Fields    

    private String mainContactType;
    private AmtbAccount amtbAccount;


    // Constructors

    /** default constructor */
    public AmtbAcctMainContactPK() {
    }

    
    /** full constructor */
    public AmtbAcctMainContactPK(String mainContactType, AmtbAccount amtbAccount) {
        this.mainContactType = mainContactType;
        this.amtbAccount = amtbAccount;
    }
    

   
    // Property accessors

    public String getMainContactType() {
        return this.mainContactType;
    }
    
    public void setMainContactType(String mainContactType) {
        this.mainContactType = mainContactType;
    }

    public AmtbAccount getAmtbAccount() {
        return this.amtbAccount;
    }
    
    public void setAmtbAccount(AmtbAccount amtbAccount) {
        this.amtbAccount = amtbAccount;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmtbAcctMainContactPK) ) return false;
		 AmtbAcctMainContactPK castOther = ( AmtbAcctMainContactPK ) other; 
         
		 return ( (this.getMainContactType()==castOther.getMainContactType()) || ( this.getMainContactType()!=null && castOther.getMainContactType()!=null && this.getMainContactType().equals(castOther.getMainContactType()) ) )
 && ( (this.getAmtbAccount()==castOther.getAmtbAccount()) || ( this.getAmtbAccount()!=null && castOther.getAmtbAccount()!=null && this.getAmtbAccount().equals(castOther.getAmtbAccount()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMainContactType() == null ? 0 : this.getMainContactType().hashCode() );
         result = 37 * result + ( getAmtbAccount() == null ? 0 : this.getAmtbAccount().hashCode() );
         return result;
   }   





}
