package com.cdgtaxi.ibs.common.model;
// Generated Jul 21, 2009 1:20:25 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Date;


/**
 * AmtbAcctBillCycle generated by hbm2java
 */

public class AmtbAcctBillCycle  implements java.io.Serializable {


    // Fields    

    private Integer acctBillCycleNo;
    private String billingCycle;
    private Date effectiveDate;
    private Integer version;
    private AmtbAccount amtbAccount;


    // Constructors

    /** default constructor */
    public AmtbAcctBillCycle() {
    }

    
    /** full constructor */
    public AmtbAcctBillCycle(String billingCycle, Date effectiveDate, Integer version, AmtbAccount amtbAccount) {
        this.billingCycle = billingCycle;
        this.effectiveDate = effectiveDate;
        this.version = version;
        this.amtbAccount = amtbAccount;
    }
    

   
    // Property accessors

    public Integer getAcctBillCycleNo() {
        return this.acctBillCycleNo;
    }
    
    public void setAcctBillCycleNo(Integer acctBillCycleNo) {
        this.acctBillCycleNo = acctBillCycleNo;
    }

    public String getBillingCycle() {
        return this.billingCycle;
    }
    
    public void setBillingCycle(String billingCycle) {
        this.billingCycle = billingCycle;
    }

    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public AmtbAccount getAmtbAccount() {
        return this.amtbAccount;
    }
    
    public void setAmtbAccount(AmtbAccount amtbAccount) {
        this.amtbAccount = amtbAccount;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("billingCycle").append("='").append(getBillingCycle()).append("' ");			
      buffer.append("effectiveDate").append("='").append(getEffectiveDate()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmtbAcctBillCycle) ) return false;
		 AmtbAcctBillCycle castOther = ( AmtbAcctBillCycle ) other; 
         
		 return ( (this.getAcctBillCycleNo()==castOther.getAcctBillCycleNo()) || ( this.getAcctBillCycleNo()!=null && castOther.getAcctBillCycleNo()!=null && this.getAcctBillCycleNo().equals(castOther.getAcctBillCycleNo()) ) )
 && ( (this.getBillingCycle()==castOther.getBillingCycle()) || ( this.getBillingCycle()!=null && castOther.getBillingCycle()!=null && this.getBillingCycle().equals(castOther.getBillingCycle()) ) )
 && ( (this.getEffectiveDate()==castOther.getEffectiveDate()) || ( this.getEffectiveDate()!=null && castOther.getEffectiveDate()!=null && this.getEffectiveDate().equals(castOther.getEffectiveDate()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getAmtbAccount()==castOther.getAmtbAccount()) || ( this.getAmtbAccount()!=null && castOther.getAmtbAccount()!=null && this.getAmtbAccount().equals(castOther.getAmtbAccount()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAcctBillCycleNo() == null ? 0 : this.getAcctBillCycleNo().hashCode() );
         result = 37 * result + ( getBillingCycle() == null ? 0 : this.getBillingCycle().hashCode() );
         result = 37 * result + ( getEffectiveDate() == null ? 0 : this.getEffectiveDate().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getAmtbAccount() == null ? 0 : this.getAmtbAccount().hashCode() );
         return result;
   }   





}
