package com.cdgtaxi.ibs.common.model;
// Generated Jul 20, 2009 4:09:41 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;

import com.cdgtaxi.ibs.acl.model.SatbUser;

/**
 * AmtbApplicationFlow generated by hbm2java
 */

public class AmtbApplicationFlow  implements java.io.Serializable {


    // Fields    

    private Integer applicationFlowNo;
    private Timestamp flowDt;
    private String fromStatus;
    private String toStatus;
    private String remarks;
    private Integer version;
    private AmtbApplication amtbApplication;
    private SatbUser satbUser;


    // Constructors

    /** default constructor */
    public AmtbApplicationFlow() {
    }

	/** minimal constructor */
    public AmtbApplicationFlow(Timestamp flowDt, String fromStatus, String toStatus) {
        this.flowDt = flowDt;
        this.fromStatus = fromStatus;
        this.toStatus = toStatus;
    }
    
    /** full constructor */
    public AmtbApplicationFlow(Timestamp flowDt, String fromStatus, String toStatus, String remarks, Integer version, AmtbApplication amtbApplication, SatbUser satbUser) {
        this.flowDt = flowDt;
        this.fromStatus = fromStatus;
        this.toStatus = toStatus;
        this.remarks = remarks;
        this.version = version;
        this.amtbApplication = amtbApplication;
        this.satbUser = satbUser;
    }
    

   
    // Property accessors

    public Integer getApplicationFlowNo() {
        return this.applicationFlowNo;
    }
    
    public void setApplicationFlowNo(Integer applicationFlowNo) {
        this.applicationFlowNo = applicationFlowNo;
    }

    public Timestamp getFlowDt() {
        return this.flowDt;
    }
    
    public void setFlowDt(Timestamp flowDt) {
        this.flowDt = flowDt;
    }

    public String getFromStatus() {
        return this.fromStatus;
    }
    
    public void setFromStatus(String fromStatus) {
        this.fromStatus = fromStatus;
    }

    public String getToStatus() {
        return this.toStatus;
    }
    
    public void setToStatus(String toStatus) {
        this.toStatus = toStatus;
    }

    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public AmtbApplication getAmtbApplication() {
        return this.amtbApplication;
    }
    
    public void setAmtbApplication(AmtbApplication amtbApplication) {
        this.amtbApplication = amtbApplication;
    }

    public SatbUser getSatbUser() {
        return this.satbUser;
    }
    
    public void setSatbUser(SatbUser satbUser) {
        this.satbUser = satbUser;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("flowDt").append("='").append(getFlowDt()).append("' ");			
      buffer.append("fromStatus").append("='").append(getFromStatus()).append("' ");			
      buffer.append("toStatus").append("='").append(getToStatus()).append("' ");			
      buffer.append("remarks").append("='").append(getRemarks()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmtbApplicationFlow) ) return false;
		 AmtbApplicationFlow castOther = ( AmtbApplicationFlow ) other; 
         
		 return ( (this.getApplicationFlowNo()==castOther.getApplicationFlowNo()) || ( this.getApplicationFlowNo()!=null && castOther.getApplicationFlowNo()!=null && this.getApplicationFlowNo().equals(castOther.getApplicationFlowNo()) ) )
 && ( (this.getFlowDt()==castOther.getFlowDt()) || ( this.getFlowDt()!=null && castOther.getFlowDt()!=null && this.getFlowDt().equals(castOther.getFlowDt()) ) )
 && ( (this.getFromStatus()==castOther.getFromStatus()) || ( this.getFromStatus()!=null && castOther.getFromStatus()!=null && this.getFromStatus().equals(castOther.getFromStatus()) ) )
 && ( (this.getToStatus()==castOther.getToStatus()) || ( this.getToStatus()!=null && castOther.getToStatus()!=null && this.getToStatus().equals(castOther.getToStatus()) ) )
 && ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getAmtbApplication()==castOther.getAmtbApplication()) || ( this.getAmtbApplication()!=null && castOther.getAmtbApplication()!=null && this.getAmtbApplication().equals(castOther.getAmtbApplication()) ) )
 && ( (this.getSatbUser()==castOther.getSatbUser()) || ( this.getSatbUser()!=null && castOther.getSatbUser()!=null && this.getSatbUser().equals(castOther.getSatbUser()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getApplicationFlowNo() == null ? 0 : this.getApplicationFlowNo().hashCode() );
         result = 37 * result + ( getFlowDt() == null ? 0 : this.getFlowDt().hashCode() );
         result = 37 * result + ( getFromStatus() == null ? 0 : this.getFromStatus().hashCode() );
         result = 37 * result + ( getToStatus() == null ? 0 : this.getToStatus().hashCode() );
         result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getAmtbApplication() == null ? 0 : this.getAmtbApplication().hashCode() );
         result = 37 * result + ( getSatbUser() == null ? 0 : this.getSatbUser().hashCode() );
         return result;
   }   





}
