package com.cdgtaxi.ibs.common.model;
// Generated Jul 20, 2009 4:09:36 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;

import com.cdgtaxi.ibs.master.model.LrtbRewardMaster;
import com.cdgtaxi.ibs.master.model.MstbIssuanceFeeMaster;
import com.cdgtaxi.ibs.master.model.MstbProdDiscMaster;
import com.cdgtaxi.ibs.master.model.MstbSubscFeeMaster;


/**
 * AmtbSubscTo generated by hbm2java
 */

public class AmtbSubscTo  implements java.io.Serializable {


    // Fields    

    private AmtbSubscToPK comp_id;
    private Timestamp effectiveDt;
    private Integer version;
    private MstbProdDiscMaster mstbProdDiscMaster;
    private LrtbRewardMaster lrtbRewardMaster;
    private MstbSubscFeeMaster mstbSubscFeeMaster;
    private MstbIssuanceFeeMaster mstbIssuanceFeeMaster;


    // Constructors

    /** default constructor */
    public AmtbSubscTo() {
    }

	/** minimal constructor */
    public AmtbSubscTo(AmtbSubscToPK comp_id, Timestamp effectiveDt) {
        this.comp_id = comp_id;
        this.effectiveDt = effectiveDt;
    }
    
    /** full constructor */
    public AmtbSubscTo(AmtbSubscToPK comp_id, Timestamp effectiveDt, Integer version, MstbProdDiscMaster mstbProdDiscMaster, LrtbRewardMaster lrtbRewardMaster, MstbSubscFeeMaster mstbSubscFeeMaster, MstbIssuanceFeeMaster mstbIssuanceFeeMaster) {
        this.comp_id = comp_id;
        this.effectiveDt = effectiveDt;
        this.version = version;
        this.mstbProdDiscMaster = mstbProdDiscMaster;
        this.lrtbRewardMaster = lrtbRewardMaster;
        this.mstbSubscFeeMaster = mstbSubscFeeMaster;
        this.mstbIssuanceFeeMaster = mstbIssuanceFeeMaster;
    }
    

   
    // Property accessors

    public AmtbSubscToPK getComp_id() {
        return this.comp_id;
    }
    
    public void setComp_id(AmtbSubscToPK comp_id) {
        this.comp_id = comp_id;
    }

    public Timestamp getEffectiveDt() {
        return this.effectiveDt;
    }
    
    public void setEffectiveDt(Timestamp effectiveDt) {
        this.effectiveDt = effectiveDt;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public MstbProdDiscMaster getMstbProdDiscMaster() {
        return this.mstbProdDiscMaster;
    }
    
    public void setMstbProdDiscMaster(MstbProdDiscMaster mstbProdDiscMaster) {
        this.mstbProdDiscMaster = mstbProdDiscMaster;
    }

    public LrtbRewardMaster getLrtbRewardMaster() {
        return this.lrtbRewardMaster;
    }
    
    public void setLrtbRewardMaster(LrtbRewardMaster lrtbRewardMaster) {
        this.lrtbRewardMaster = lrtbRewardMaster;
    }

    public MstbSubscFeeMaster getMstbSubscFeeMaster() {
        return this.mstbSubscFeeMaster;
    }
    
    public void setMstbSubscFeeMaster(MstbSubscFeeMaster mstbSubscFeeMaster) {
        this.mstbSubscFeeMaster = mstbSubscFeeMaster;
    }
    
    public MstbIssuanceFeeMaster getMstbIssuanceFeeMaster() {
        return this.mstbIssuanceFeeMaster;
    }
    
    public void setMstbIssuanceFeeMaster(MstbIssuanceFeeMaster mstbIssuanceFeeMaster) {
        this.mstbIssuanceFeeMaster = mstbIssuanceFeeMaster;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("effectiveDt").append("='").append(getEffectiveDt()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmtbSubscTo) ) return false;
		 AmtbSubscTo castOther = ( AmtbSubscTo ) other; 
         
		 return ( (this.getComp_id()==castOther.getComp_id()) || ( this.getComp_id()!=null && castOther.getComp_id()!=null && this.getComp_id().equals(castOther.getComp_id()) ) )
 && ( (this.getEffectiveDt()==castOther.getEffectiveDt()) || ( this.getEffectiveDt()!=null && castOther.getEffectiveDt()!=null && this.getEffectiveDt().equals(castOther.getEffectiveDt()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getMstbProdDiscMaster()==castOther.getMstbProdDiscMaster()) || ( this.getMstbProdDiscMaster()!=null && castOther.getMstbProdDiscMaster()!=null && this.getMstbProdDiscMaster().equals(castOther.getMstbProdDiscMaster()) ) )
 && ( (this.getLrtbRewardMaster()==castOther.getLrtbRewardMaster()) || ( this.getLrtbRewardMaster()!=null && castOther.getLrtbRewardMaster()!=null && this.getLrtbRewardMaster().equals(castOther.getLrtbRewardMaster()) ) )
 && ( (this.getMstbSubscFeeMaster()==castOther.getMstbSubscFeeMaster()) || ( this.getMstbSubscFeeMaster()!=null && castOther.getMstbSubscFeeMaster()!=null && this.getMstbSubscFeeMaster().equals(castOther.getMstbSubscFeeMaster()) ) )
 && ( (this.getMstbIssuanceFeeMaster()==castOther.getMstbIssuanceFeeMaster()) || ( this.getMstbIssuanceFeeMaster()!=null && castOther.getMstbIssuanceFeeMaster()!=null && this.getMstbIssuanceFeeMaster().equals(castOther.getMstbIssuanceFeeMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getComp_id() == null ? 0 : this.getComp_id().hashCode() );
         result = 37 * result + ( getEffectiveDt() == null ? 0 : this.getEffectiveDt().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getMstbProdDiscMaster() == null ? 0 : this.getMstbProdDiscMaster().hashCode() );
         result = 37 * result + ( getLrtbRewardMaster() == null ? 0 : this.getLrtbRewardMaster().hashCode() );
         result = 37 * result + ( getMstbSubscFeeMaster() == null ? 0 : this.getMstbSubscFeeMaster().hashCode() );
         result = 37 * result + ( getMstbIssuanceFeeMaster() == null ? 0 : this.getMstbIssuanceFeeMaster().hashCode() );
         return result;
   }   





}
