package com.cdgtaxi.ibs.common.model;
// Generated Jul 20, 2009 4:09:34 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Date;

import com.cdgtaxi.ibs.master.model.MstbVolDiscMaster;


/**
 * AmtbAcctVolDisc generated by hbm2java
 */

public class AmtbAcctVolDisc  implements java.io.Serializable {


    // Fields    

    private Integer acctVolDiscNo;
    private Date effectiveDate;
    private Integer version;
    private AmtbAccount amtbAccount;
    private MstbVolDiscMaster mstbVolDiscMaster;


    // Constructors

    /** default constructor */
    public AmtbAcctVolDisc() {
    }

    
    /** full constructor */
    public AmtbAcctVolDisc(Date effectiveDate, Integer version, AmtbAccount amtbAccount, MstbVolDiscMaster mstbVolDiscMaster) {
        this.effectiveDate = effectiveDate;
        this.version = version;
        this.amtbAccount = amtbAccount;
        this.mstbVolDiscMaster = mstbVolDiscMaster;
    }
    

   
    // Property accessors

    public Integer getAcctVolDiscNo() {
        return this.acctVolDiscNo;
    }
    
    public void setAcctVolDiscNo(Integer acctVolDiscNo) {
        this.acctVolDiscNo = acctVolDiscNo;
    }

    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public AmtbAccount getAmtbAccount() {
        return this.amtbAccount;
    }
    
    public void setAmtbAccount(AmtbAccount amtbAccount) {
        this.amtbAccount = amtbAccount;
    }

    public MstbVolDiscMaster getMstbVolDiscMaster() {
        return this.mstbVolDiscMaster;
    }
    
    public void setMstbVolDiscMaster(MstbVolDiscMaster mstbVolDiscMaster) {
        this.mstbVolDiscMaster = mstbVolDiscMaster;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("effectiveDate").append("='").append(getEffectiveDate()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmtbAcctVolDisc) ) return false;
		 AmtbAcctVolDisc castOther = ( AmtbAcctVolDisc ) other; 
         
		 return ( (this.getAcctVolDiscNo()==castOther.getAcctVolDiscNo()) || ( this.getAcctVolDiscNo()!=null && castOther.getAcctVolDiscNo()!=null && this.getAcctVolDiscNo().equals(castOther.getAcctVolDiscNo()) ) )
 && ( (this.getEffectiveDate()==castOther.getEffectiveDate()) || ( this.getEffectiveDate()!=null && castOther.getEffectiveDate()!=null && this.getEffectiveDate().equals(castOther.getEffectiveDate()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getAmtbAccount()==castOther.getAmtbAccount()) || ( this.getAmtbAccount()!=null && castOther.getAmtbAccount()!=null && this.getAmtbAccount().equals(castOther.getAmtbAccount()) ) )
 && ( (this.getMstbVolDiscMaster()==castOther.getMstbVolDiscMaster()) || ( this.getMstbVolDiscMaster()!=null && castOther.getMstbVolDiscMaster()!=null && this.getMstbVolDiscMaster().equals(castOther.getMstbVolDiscMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAcctVolDiscNo() == null ? 0 : this.getAcctVolDiscNo().hashCode() );
         result = 37 * result + ( getEffectiveDate() == null ? 0 : this.getEffectiveDate().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getAmtbAccount() == null ? 0 : this.getAmtbAccount().hashCode() );
         result = 37 * result + ( getMstbVolDiscMaster() == null ? 0 : this.getMstbVolDiscMaster().hashCode() );
         return result;
   }   





}
