package com.cdgtaxi.ibs.common.model;
// Generated Jul 20, 2009 4:09:32 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Timestamp;

import com.cdgtaxi.ibs.master.model.MstbMasterTable;


/**
 * AmtbPersonalDetail generated by hbm2java
 */

public class AmtbPersonalDetail  implements java.io.Serializable {


    // Fields    

    private Integer personalDetailNo;
    private Timestamp birthDt;
    private String nric;
    private String tel;
    private String fax;
    private String addressBlock;
    private String addressUnit;
    private String addressStreet;
    private String addressBuilding;
    private String addressArea;
    private String addressPostal;
    private String addressCity;
    private String addressState;
    private String occupation;
    private String employerName;
    private BigDecimal monthlyIncome;
    private Integer employLengthYear;
    private String employerBlock;
    private String employerUnit;
    private String employerStreet;
    private String employerBuilding;
    private String employerArea;
    private String employerPostal;
    private String employerCity;
    private String employerState;
    private Integer version;
    private MstbMasterTable mstbMasterTableByIndustry;
    private MstbMasterTable mstbMasterTableByAddressCountry;
    private MstbMasterTable mstbMasterTableByEmployerCountry;
    private MstbMasterTable mstbMasterTableByJobStatus;
    private MstbMasterTable mstbMasterTableByRelationToParent;
    private AmtbAccount amtbAccount;
    private MstbMasterTable mstbMasterTableByMainContactRace;

    // Constructors

    /** default constructor */
    public AmtbPersonalDetail() {
    }

	/** minimal constructor */
    public AmtbPersonalDetail(String nric, String tel, String addressStreet, String addressPostal) {
        this.nric = nric;
        this.tel = tel;
        this.addressStreet = addressStreet;
        this.addressPostal = addressPostal;
    }
    
    /** full constructor */
    public AmtbPersonalDetail(Timestamp birthDt, String nric, String tel, String fax, String addressBlock, String addressUnit, String addressStreet, String addressBuilding, String addressArea, String addressPostal, String addressCity, String addressState, String occupation, String employerName, BigDecimal monthlyIncome, Integer employLengthYear, String employerBlock, String employerUnit, String employerStreet, String employerBuilding, String employerArea, String employerPostal, String employerCity, String employerState, Integer version, MstbMasterTable mstbMasterTableByIndustry, MstbMasterTable mstbMasterTableByAddressCountry, MstbMasterTable mstbMasterTableByEmployerCountry, MstbMasterTable mstbMasterTableByJobStatus, MstbMasterTable mstbMasterTableByRelationToParent, AmtbAccount amtbAccount, MstbMasterTable mstbMasterTableByMainContactRace) {
        this.birthDt = birthDt;
        this.nric = nric;
        this.tel = tel;
        this.fax = fax;
        this.addressBlock = addressBlock;
        this.addressUnit = addressUnit;
        this.addressStreet = addressStreet;
        this.addressBuilding = addressBuilding;
        this.addressArea = addressArea;
        this.addressPostal = addressPostal;
        this.addressCity = addressCity;
        this.addressState = addressState;
        this.occupation = occupation;
        this.employerName = employerName;
        this.monthlyIncome = monthlyIncome;
        this.employLengthYear = employLengthYear;
        this.employerBlock = employerBlock;
        this.employerUnit = employerUnit;
        this.employerStreet = employerStreet;
        this.employerBuilding = employerBuilding;
        this.employerArea = employerArea;
        this.employerPostal = employerPostal;
        this.employerCity = employerCity;
        this.employerState = employerState;
        this.version = version;
        this.mstbMasterTableByIndustry = mstbMasterTableByIndustry;
        this.mstbMasterTableByAddressCountry = mstbMasterTableByAddressCountry;
        this.mstbMasterTableByEmployerCountry = mstbMasterTableByEmployerCountry;
        this.mstbMasterTableByJobStatus = mstbMasterTableByJobStatus;
        this.mstbMasterTableByRelationToParent = mstbMasterTableByRelationToParent;
        this.amtbAccount = amtbAccount;
        this.mstbMasterTableByMainContactRace = mstbMasterTableByMainContactRace;
    }
    

   
    // Property accessors

    public Integer getPersonalDetailNo() {
        return this.personalDetailNo;
    }
    
    public void setPersonalDetailNo(Integer personalDetailNo) {
        this.personalDetailNo = personalDetailNo;
    }

    public Timestamp getBirthDt() {
        return this.birthDt;
    }
    
    public void setBirthDt(Timestamp birthDt) {
        this.birthDt = birthDt;
    }

    public String getNric() {
        return this.nric;
    }
    
    public void setNric(String nric) {
        this.nric = nric;
    }

    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getAddressBlock() {
        return this.addressBlock;
    }
    
    public void setAddressBlock(String addressBlock) {
        this.addressBlock = addressBlock;
    }

    public String getAddressUnit() {
        return this.addressUnit;
    }
    
    public void setAddressUnit(String addressUnit) {
        this.addressUnit = addressUnit;
    }

    public String getAddressStreet() {
        return this.addressStreet;
    }
    
    public void setAddressStreet(String addressStreet) {
        this.addressStreet = addressStreet;
    }

    public String getAddressBuilding() {
        return this.addressBuilding;
    }
    
    public void setAddressBuilding(String addressBuilding) {
        this.addressBuilding = addressBuilding;
    }

    public String getAddressArea() {
        return this.addressArea;
    }
    
    public void setAddressArea(String addressArea) {
        this.addressArea = addressArea;
    }

    public String getAddressPostal() {
        return this.addressPostal;
    }
    
    public void setAddressPostal(String addressPostal) {
        this.addressPostal = addressPostal;
    }

    public String getAddressCity() {
        return this.addressCity;
    }
    
    public void setAddressCity(String addressCity) {
        this.addressCity = addressCity;
    }

    public String getAddressState() {
        return this.addressState;
    }
    
    public void setAddressState(String addressState) {
        this.addressState = addressState;
    }

    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    public String getEmployerName() {
        return this.employerName;
    }
    
    public void setEmployerName(String employerName) {
        this.employerName = employerName;
    }

    public BigDecimal getMonthlyIncome() {
        return this.monthlyIncome;
    }
    
    public void setMonthlyIncome(BigDecimal monthlyIncome) {
        this.monthlyIncome = monthlyIncome;
    }

    public Integer getEmployLengthYear() {
        return this.employLengthYear;
    }
    
    public void setEmployLengthYear(Integer employLengthYear) {
        this.employLengthYear = employLengthYear;
    }

    public String getEmployerBlock() {
        return this.employerBlock;
    }
    
    public void setEmployerBlock(String employerBlock) {
        this.employerBlock = employerBlock;
    }

    public String getEmployerUnit() {
        return this.employerUnit;
    }
    
    public void setEmployerUnit(String employerUnit) {
        this.employerUnit = employerUnit;
    }

    public String getEmployerStreet() {
        return this.employerStreet;
    }
    
    public void setEmployerStreet(String employerStreet) {
        this.employerStreet = employerStreet;
    }

    public String getEmployerBuilding() {
        return this.employerBuilding;
    }
    
    public void setEmployerBuilding(String employerBuilding) {
        this.employerBuilding = employerBuilding;
    }

    public String getEmployerArea() {
        return this.employerArea;
    }
    
    public void setEmployerArea(String employerArea) {
        this.employerArea = employerArea;
    }

    public String getEmployerPostal() {
        return this.employerPostal;
    }
    
    public void setEmployerPostal(String employerPostal) {
        this.employerPostal = employerPostal;
    }

    public String getEmployerCity() {
        return this.employerCity;
    }
    
    public void setEmployerCity(String employerCity) {
        this.employerCity = employerCity;
    }

    public String getEmployerState() {
        return this.employerState;
    }
    
    public void setEmployerState(String employerState) {
        this.employerState = employerState;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public MstbMasterTable getMstbMasterTableByIndustry() {
        return this.mstbMasterTableByIndustry;
    }
    
    public void setMstbMasterTableByIndustry(MstbMasterTable mstbMasterTableByIndustry) {
        this.mstbMasterTableByIndustry = mstbMasterTableByIndustry;
    }

    public MstbMasterTable getMstbMasterTableByAddressCountry() {
        return this.mstbMasterTableByAddressCountry;
    }
    
    public void setMstbMasterTableByAddressCountry(MstbMasterTable mstbMasterTableByAddressCountry) {
        this.mstbMasterTableByAddressCountry = mstbMasterTableByAddressCountry;
    }

    public MstbMasterTable getMstbMasterTableByEmployerCountry() {
        return this.mstbMasterTableByEmployerCountry;
    }
    
    public void setMstbMasterTableByEmployerCountry(MstbMasterTable mstbMasterTableByEmployerCountry) {
        this.mstbMasterTableByEmployerCountry = mstbMasterTableByEmployerCountry;
    }

    public MstbMasterTable getMstbMasterTableByJobStatus() {
        return this.mstbMasterTableByJobStatus;
    }
    
    public void setMstbMasterTableByJobStatus(MstbMasterTable mstbMasterTableByJobStatus) {
        this.mstbMasterTableByJobStatus = mstbMasterTableByJobStatus;
    }

    public MstbMasterTable getMstbMasterTableByRelationToParent() {
        return this.mstbMasterTableByRelationToParent;
    }
    
    public void setMstbMasterTableByRelationToParent(MstbMasterTable mstbMasterTableByRelationToParent) {
        this.mstbMasterTableByRelationToParent = mstbMasterTableByRelationToParent;
    }

    public AmtbAccount getAmtbAccount() {
        return this.amtbAccount;
    }
    
    public void setAmtbAccount(AmtbAccount amtbAccount) {
        this.amtbAccount = amtbAccount;
    }
    
    public MstbMasterTable getMstbMasterTableByMainContactRace() {
 		return mstbMasterTableByMainContactRace;
 	}

 	public void setMstbMasterTableByMainContactRace(
 			MstbMasterTable mstbMasterTableByMainContactRace) {
 		this.mstbMasterTableByMainContactRace = mstbMasterTableByMainContactRace;
 	}

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("birthDt").append("='").append(getBirthDt()).append("' ");			
      buffer.append("nric").append("='").append(getNric()).append("' ");			
      buffer.append("tel").append("='").append(getTel()).append("' ");			
      buffer.append("fax").append("='").append(getFax()).append("' ");			
      buffer.append("addressBlock").append("='").append(getAddressBlock()).append("' ");			
      buffer.append("addressUnit").append("='").append(getAddressUnit()).append("' ");			
      buffer.append("addressStreet").append("='").append(getAddressStreet()).append("' ");			
      buffer.append("addressBuilding").append("='").append(getAddressBuilding()).append("' ");			
      buffer.append("addressArea").append("='").append(getAddressArea()).append("' ");			
      buffer.append("addressPostal").append("='").append(getAddressPostal()).append("' ");			
      buffer.append("addressCity").append("='").append(getAddressCity()).append("' ");			
      buffer.append("addressState").append("='").append(getAddressState()).append("' ");			
      buffer.append("occupation").append("='").append(getOccupation()).append("' ");			
      buffer.append("employerName").append("='").append(getEmployerName()).append("' ");			
      buffer.append("monthlyIncome").append("='").append(getMonthlyIncome()).append("' ");			
      buffer.append("employLengthYear").append("='").append(getEmployLengthYear()).append("' ");			
      buffer.append("employerBlock").append("='").append(getEmployerBlock()).append("' ");			
      buffer.append("employerUnit").append("='").append(getEmployerUnit()).append("' ");			
      buffer.append("employerStreet").append("='").append(getEmployerStreet()).append("' ");			
      buffer.append("employerBuilding").append("='").append(getEmployerBuilding()).append("' ");			
      buffer.append("employerArea").append("='").append(getEmployerArea()).append("' ");			
      buffer.append("employerPostal").append("='").append(getEmployerPostal()).append("' ");			
      buffer.append("employerCity").append("='").append(getEmployerCity()).append("' ");			
      buffer.append("employerState").append("='").append(getEmployerState()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmtbPersonalDetail) ) return false;
		 AmtbPersonalDetail castOther = ( AmtbPersonalDetail ) other; 
         
		 return ( (this.getPersonalDetailNo()==castOther.getPersonalDetailNo()) || ( this.getPersonalDetailNo()!=null && castOther.getPersonalDetailNo()!=null && this.getPersonalDetailNo().equals(castOther.getPersonalDetailNo()) ) )
 && ( (this.getBirthDt()==castOther.getBirthDt()) || ( this.getBirthDt()!=null && castOther.getBirthDt()!=null && this.getBirthDt().equals(castOther.getBirthDt()) ) )
 && ( (this.getNric()==castOther.getNric()) || ( this.getNric()!=null && castOther.getNric()!=null && this.getNric().equals(castOther.getNric()) ) )
 && ( (this.getTel()==castOther.getTel()) || ( this.getTel()!=null && castOther.getTel()!=null && this.getTel().equals(castOther.getTel()) ) )
 && ( (this.getFax()==castOther.getFax()) || ( this.getFax()!=null && castOther.getFax()!=null && this.getFax().equals(castOther.getFax()) ) )
 && ( (this.getAddressBlock()==castOther.getAddressBlock()) || ( this.getAddressBlock()!=null && castOther.getAddressBlock()!=null && this.getAddressBlock().equals(castOther.getAddressBlock()) ) )
 && ( (this.getAddressUnit()==castOther.getAddressUnit()) || ( this.getAddressUnit()!=null && castOther.getAddressUnit()!=null && this.getAddressUnit().equals(castOther.getAddressUnit()) ) )
 && ( (this.getAddressStreet()==castOther.getAddressStreet()) || ( this.getAddressStreet()!=null && castOther.getAddressStreet()!=null && this.getAddressStreet().equals(castOther.getAddressStreet()) ) )
 && ( (this.getAddressBuilding()==castOther.getAddressBuilding()) || ( this.getAddressBuilding()!=null && castOther.getAddressBuilding()!=null && this.getAddressBuilding().equals(castOther.getAddressBuilding()) ) )
 && ( (this.getAddressArea()==castOther.getAddressArea()) || ( this.getAddressArea()!=null && castOther.getAddressArea()!=null && this.getAddressArea().equals(castOther.getAddressArea()) ) )
 && ( (this.getAddressPostal()==castOther.getAddressPostal()) || ( this.getAddressPostal()!=null && castOther.getAddressPostal()!=null && this.getAddressPostal().equals(castOther.getAddressPostal()) ) )
 && ( (this.getAddressCity()==castOther.getAddressCity()) || ( this.getAddressCity()!=null && castOther.getAddressCity()!=null && this.getAddressCity().equals(castOther.getAddressCity()) ) )
 && ( (this.getAddressState()==castOther.getAddressState()) || ( this.getAddressState()!=null && castOther.getAddressState()!=null && this.getAddressState().equals(castOther.getAddressState()) ) )
 && ( (this.getOccupation()==castOther.getOccupation()) || ( this.getOccupation()!=null && castOther.getOccupation()!=null && this.getOccupation().equals(castOther.getOccupation()) ) )
 && ( (this.getEmployerName()==castOther.getEmployerName()) || ( this.getEmployerName()!=null && castOther.getEmployerName()!=null && this.getEmployerName().equals(castOther.getEmployerName()) ) )
 && ( (this.getMonthlyIncome()==castOther.getMonthlyIncome()) || ( this.getMonthlyIncome()!=null && castOther.getMonthlyIncome()!=null && this.getMonthlyIncome().equals(castOther.getMonthlyIncome()) ) )
 && ( (this.getEmployLengthYear()==castOther.getEmployLengthYear()) || ( this.getEmployLengthYear()!=null && castOther.getEmployLengthYear()!=null && this.getEmployLengthYear().equals(castOther.getEmployLengthYear()) ) )
 && ( (this.getEmployerBlock()==castOther.getEmployerBlock()) || ( this.getEmployerBlock()!=null && castOther.getEmployerBlock()!=null && this.getEmployerBlock().equals(castOther.getEmployerBlock()) ) )
 && ( (this.getEmployerUnit()==castOther.getEmployerUnit()) || ( this.getEmployerUnit()!=null && castOther.getEmployerUnit()!=null && this.getEmployerUnit().equals(castOther.getEmployerUnit()) ) )
 && ( (this.getEmployerStreet()==castOther.getEmployerStreet()) || ( this.getEmployerStreet()!=null && castOther.getEmployerStreet()!=null && this.getEmployerStreet().equals(castOther.getEmployerStreet()) ) )
 && ( (this.getEmployerBuilding()==castOther.getEmployerBuilding()) || ( this.getEmployerBuilding()!=null && castOther.getEmployerBuilding()!=null && this.getEmployerBuilding().equals(castOther.getEmployerBuilding()) ) )
 && ( (this.getEmployerArea()==castOther.getEmployerArea()) || ( this.getEmployerArea()!=null && castOther.getEmployerArea()!=null && this.getEmployerArea().equals(castOther.getEmployerArea()) ) )
 && ( (this.getEmployerPostal()==castOther.getEmployerPostal()) || ( this.getEmployerPostal()!=null && castOther.getEmployerPostal()!=null && this.getEmployerPostal().equals(castOther.getEmployerPostal()) ) )
 && ( (this.getEmployerCity()==castOther.getEmployerCity()) || ( this.getEmployerCity()!=null && castOther.getEmployerCity()!=null && this.getEmployerCity().equals(castOther.getEmployerCity()) ) )
 && ( (this.getEmployerState()==castOther.getEmployerState()) || ( this.getEmployerState()!=null && castOther.getEmployerState()!=null && this.getEmployerState().equals(castOther.getEmployerState()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getMstbMasterTableByIndustry()==castOther.getMstbMasterTableByIndustry()) || ( this.getMstbMasterTableByIndustry()!=null && castOther.getMstbMasterTableByIndustry()!=null && this.getMstbMasterTableByIndustry().equals(castOther.getMstbMasterTableByIndustry()) ) )
 && ( (this.getMstbMasterTableByAddressCountry()==castOther.getMstbMasterTableByAddressCountry()) || ( this.getMstbMasterTableByAddressCountry()!=null && castOther.getMstbMasterTableByAddressCountry()!=null && this.getMstbMasterTableByAddressCountry().equals(castOther.getMstbMasterTableByAddressCountry()) ) )
 && ( (this.getMstbMasterTableByEmployerCountry()==castOther.getMstbMasterTableByEmployerCountry()) || ( this.getMstbMasterTableByEmployerCountry()!=null && castOther.getMstbMasterTableByEmployerCountry()!=null && this.getMstbMasterTableByEmployerCountry().equals(castOther.getMstbMasterTableByEmployerCountry()) ) )
 && ( (this.getMstbMasterTableByJobStatus()==castOther.getMstbMasterTableByJobStatus()) || ( this.getMstbMasterTableByJobStatus()!=null && castOther.getMstbMasterTableByJobStatus()!=null && this.getMstbMasterTableByJobStatus().equals(castOther.getMstbMasterTableByJobStatus()) ) )
 && ( (this.getMstbMasterTableByRelationToParent()==castOther.getMstbMasterTableByRelationToParent()) || ( this.getMstbMasterTableByRelationToParent()!=null && castOther.getMstbMasterTableByRelationToParent()!=null && this.getMstbMasterTableByRelationToParent().equals(castOther.getMstbMasterTableByRelationToParent()) ) )
 && ( (this.getMstbMasterTableByMainContactRace()==castOther.getMstbMasterTableByMainContactRace()) || ( this.getMstbMasterTableByMainContactRace()!=null && castOther.getMstbMasterTableByMainContactRace()!=null && this.getMstbMasterTableByMainContactRace().equals(castOther.getMstbMasterTableByMainContactRace()) ) )
 && ( (this.getAmtbAccount()==castOther.getAmtbAccount()) || ( this.getAmtbAccount()!=null && castOther.getAmtbAccount()!=null && this.getAmtbAccount().equals(castOther.getAmtbAccount()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPersonalDetailNo() == null ? 0 : this.getPersonalDetailNo().hashCode() );
         result = 37 * result + ( getBirthDt() == null ? 0 : this.getBirthDt().hashCode() );
         result = 37 * result + ( getNric() == null ? 0 : this.getNric().hashCode() );
         result = 37 * result + ( getTel() == null ? 0 : this.getTel().hashCode() );
         result = 37 * result + ( getFax() == null ? 0 : this.getFax().hashCode() );
         result = 37 * result + ( getAddressBlock() == null ? 0 : this.getAddressBlock().hashCode() );
         result = 37 * result + ( getAddressUnit() == null ? 0 : this.getAddressUnit().hashCode() );
         result = 37 * result + ( getAddressStreet() == null ? 0 : this.getAddressStreet().hashCode() );
         result = 37 * result + ( getAddressBuilding() == null ? 0 : this.getAddressBuilding().hashCode() );
         result = 37 * result + ( getAddressArea() == null ? 0 : this.getAddressArea().hashCode() );
         result = 37 * result + ( getAddressPostal() == null ? 0 : this.getAddressPostal().hashCode() );
         result = 37 * result + ( getAddressCity() == null ? 0 : this.getAddressCity().hashCode() );
         result = 37 * result + ( getAddressState() == null ? 0 : this.getAddressState().hashCode() );
         result = 37 * result + ( getOccupation() == null ? 0 : this.getOccupation().hashCode() );
         result = 37 * result + ( getEmployerName() == null ? 0 : this.getEmployerName().hashCode() );
         result = 37 * result + ( getMonthlyIncome() == null ? 0 : this.getMonthlyIncome().hashCode() );
         result = 37 * result + ( getEmployLengthYear() == null ? 0 : this.getEmployLengthYear().hashCode() );
         result = 37 * result + ( getEmployerBlock() == null ? 0 : this.getEmployerBlock().hashCode() );
         result = 37 * result + ( getEmployerUnit() == null ? 0 : this.getEmployerUnit().hashCode() );
         result = 37 * result + ( getEmployerStreet() == null ? 0 : this.getEmployerStreet().hashCode() );
         result = 37 * result + ( getEmployerBuilding() == null ? 0 : this.getEmployerBuilding().hashCode() );
         result = 37 * result + ( getEmployerArea() == null ? 0 : this.getEmployerArea().hashCode() );
         result = 37 * result + ( getEmployerPostal() == null ? 0 : this.getEmployerPostal().hashCode() );
         result = 37 * result + ( getEmployerCity() == null ? 0 : this.getEmployerCity().hashCode() );
         result = 37 * result + ( getEmployerState() == null ? 0 : this.getEmployerState().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getMstbMasterTableByIndustry() == null ? 0 : this.getMstbMasterTableByIndustry().hashCode() );
         result = 37 * result + ( getMstbMasterTableByAddressCountry() == null ? 0 : this.getMstbMasterTableByAddressCountry().hashCode() );
         result = 37 * result + ( getMstbMasterTableByEmployerCountry() == null ? 0 : this.getMstbMasterTableByEmployerCountry().hashCode() );
         result = 37 * result + ( getMstbMasterTableByJobStatus() == null ? 0 : this.getMstbMasterTableByJobStatus().hashCode() );
         result = 37 * result + ( getMstbMasterTableByRelationToParent() == null ? 0 : this.getMstbMasterTableByRelationToParent().hashCode() );
         result = 37 * result + ( getAmtbAccount() == null ? 0 : this.getAmtbAccount().hashCode() );
         result = 37 * result + ( getMstbMasterTableByMainContactRace() == null ? 0 : this.getMstbMasterTableByMainContactRace().hashCode() );
         return result;
   }   





}
