package com.cdgtaxi.ibs.common.model;

// Generated Apr 7, 2010 1:57:38 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.master.model.MstbBankMaster;
import com.cdgtaxi.ibs.master.model.MstbBranchMaster;
import com.cdgtaxi.ibs.master.model.MstbMasterTable;

/**
 * AmtbAccount generated by hbm2java
 */

public class AmtbAccount implements java.io.Serializable, Auditable, Creatable, Updatable {

	// Fields

	private Integer accountNo;
	private String custNo;
	private String accountCategory;
	private BigDecimal creditLimit;
	private BigDecimal tempCreditLimit;
	private BigDecimal creditBalance;
	private BigDecimal deposit;
	private String bankAcctNo;
	private BigDecimal accountBalance;
	private String nameOnCard;
	private String accountName;
	private String code;
	private String invoiceFormat;
	private String invoiceSorting;
	private String invoicePrinting;
	private Timestamp createdDt;
	private Timestamp updatedDt;
	private String updatedBy;
	private String createdBy;
	private Integer version;
	private String einvoiceFlag;
    private String outsourcePrintingFlag;
	private String smsFlag;
	private String smsExpiryFlag;
	private String smsTopupFlag;
	private String govtEInvoiceFlag;
	private MstbMasterTable mstbMasterTableByDefaultPaymentMode;
	private MstbMasterTable mstbMasterTableByInformationSource;
	private MstbBankMaster mstbBankMaster;
	private FmtbArContCodeMaster fmtbArContCodeMaster;
	private AmtbAcctType amtbAcctType;
	private String recurringFlag;
	private Integer recurringChargeDay;
	private Set<AmtbCorporateDetail> amtbCorporateDetails = new HashSet<AmtbCorporateDetail>(0);
	private Set<AmtbPersonalDetail> amtbPersonalDetails = new HashSet<AmtbPersonalDetail>(0);
	private Set<BmtbBillGenError> bmtbBillGenErrorsByTopLevelAccountNo = new HashSet<BmtbBillGenError>(0);
	private Set<BmtbBillGenError> bmtbBillGenErrorsByBillableAccountNo = new HashSet<BmtbBillGenError>(0);
	private Set<BmtbInvoiceDetail> bmtbInvoiceDetails = new HashSet<BmtbInvoiceDetail>(0);
	private Set<TmtbTxnReviewReq> tmtbTxnReviewReqs = new HashSet<TmtbTxnReviewReq>(0);
	private Set<AmtbCredRevReq> amtbCredRevReqs = new HashSet<AmtbCredRevReq>(0);
	private Set<BmtbInvoiceHeader> bmtbInvoiceHeadersByAccountNo = new HashSet<BmtbInvoiceHeader>(0);
	private Set<BmtbInvoiceHeader> bmtbInvoiceHeadersByDebtTo = new HashSet<BmtbInvoiceHeader>(0);
	private Set<AmtbSubscTo> amtbSubscTos = new HashSet<AmtbSubscTo>(0);
	private Set<AmtbSubscProdReq> amtbProdSubscReqs = new HashSet<AmtbSubscProdReq>(0);
	private Set<AmtbAcctLatePymt> amtbAcctLatePymts = new HashSet<AmtbAcctLatePymt>(0);
	private Set<BmtbInvoiceSummary> bmtbInvoiceSummaries = new HashSet<BmtbInvoiceSummary>(0);
	private Set<PmtbProductRetag> pmtbProductRetagsByCurrentAccountNo = new HashSet<PmtbProductRetag>(0);
	private Set<PmtbProductRetag> pmtbProductRetagsByNewAccountNo = new HashSet<PmtbProductRetag>(0);
	private Set<AmtbAcctSalesperson> amtbAcctSalespersons = new HashSet<AmtbAcctSalesperson>(0);
	private Set<AmtbAcctBillCycle> amtbAcctBillCycles = new HashSet<AmtbAcctBillCycle>(0);
	private Set<BmtbInvoiceDepositTxn> bmtbInvoiceDepositTxns = new HashSet<BmtbInvoiceDepositTxn>(0);
	private Set<BmtbPaymentReceipt> bmtbPaymentReceipts = new HashSet<BmtbPaymentReceipt>(0);
	private Set<AmtbSubscToHist> amtbSubscToHists = new HashSet<AmtbSubscToHist>(0);
	private Set<AmtbAcctEarlyPymt> amtbAcctEarlyPymts = new HashSet<AmtbAcctEarlyPymt>(0);
	private Set<AmtbAcctCredTerm> amtbAcctCredTerms = new HashSet<AmtbAcctCredTerm>(0);
	private Set<AmtbApplication> amtbApplications = new HashSet<AmtbApplication>(0);
	private Set<AmtbAcctVolDisc> amtbAcctVolDiscs = new HashSet<AmtbAcctVolDisc>(0);
	private Set<LrtbRewardAccount> lrtbRewardAccounts = new HashSet<LrtbRewardAccount>(0);
	private Set<AmtbAcctStatus> amtbAcctStatuses = new HashSet<AmtbAcctStatus>(0);
	private Set<AmtbContactPerson> amtbContactPersons = new HashSet<AmtbContactPerson>(0);
	private Set<AmtbAcctMainContact> amtbAcctMainContacts = new HashSet<AmtbAcctMainContact>(0);
	private Set<BmtbNote> bmtbNotes = new HashSet<BmtbNote>(0);
	private Set<TmtbAcquireTxn> tmtbAcquireTxns = new HashSet<TmtbAcquireTxn>(0);
	private BmtbLastInvoiceLog bmtbLastInvoiceLog;
	private Set<AmtbAcctAdminFee> amtbAcctAdminFees = new HashSet<AmtbAcctAdminFee>(0);
	private Set<AmtbBillReq> amtbBillReqs = new HashSet<AmtbBillReq>(0);
	private Set<PmtbProduct> pmtbProducts = new HashSet<PmtbProduct>(0);
	private Set<AmtbAcctCredLimit> amtbAcctCredLimits = new HashSet<AmtbAcctCredLimit>(0);
	private Set<AmtbAccount> amtbAccounts = new HashSet<AmtbAccount>(0);
	private AmtbAccount amtbAccount;
	private MstbBranchMaster mstbBranchMaster;
	private Set<PmtbProductType> pmtbProductTypes = new HashSet<PmtbProductType>(0);
	private Set<BmtbBillGenReq> bmtbBillGenReqs = new HashSet<BmtbBillGenReq>(0);
	private Set<AmtbAcctPromotion> amtbAcctPromotions = new HashSet<AmtbAcctPromotion>(0);
	private MstbMasterTable mstbMasterTableByBusinessUnit;
	
	private transient String parentNo;
	private transient String parentParentNo;
	
	private String overdueReminder;
	private String reminderEmail;
	
	private String printTaxInvoiceOnly;
	private String aceIndicator;
	private String coupaIndicator;
	
    public String getCoupaIndicator() {
		return coupaIndicator;
	}

	public void setCoupaIndicator(String coupaIndicator) {
		this.coupaIndicator = coupaIndicator;
	}

	private Set<IttbCpMasterTagAcct> ittbCpMasterTagAcct = new HashSet<IttbCpMasterTagAcct>(0);
    
	private String pubbsFlag;
	private String fiFlag;
	
	private String eInvoiceEmailFlag;
	private String eInvoiceEmail;
	private String eInvoiceEmailSubject;
	private String eInvoiceEmailZipFlag;
	private String eInvoiceEmailAttachment;
	private String eInvoiceEmailPage;
	
	// Constructors

	/** default constructor */
	public AmtbAccount() {
	}

	/** minimal constructor */
	public AmtbAccount(String accountCategory, BigDecimal creditLimit, BigDecimal creditBalance,
			String nameOnCard) {
		this.accountCategory = accountCategory;
		this.creditLimit = creditLimit;
		this.creditBalance = creditBalance;
		this.nameOnCard = nameOnCard;
	}

	/** full constructor */
	public AmtbAccount(String custNo, String accountCategory, BigDecimal creditLimit,
			BigDecimal tempCreditLimit, BigDecimal creditBalance, BigDecimal deposit, String bankAcctNo,
			BigDecimal accountBalance, String nameOnCard, String accountName, String code,
			String invoiceFormat, String invoiceSorting, String invoicePrinting, Timestamp createdDt, Timestamp updatedDt,
			String updatedBy, String createdBy, Integer version, String einvoiceFlag, String smsFlag, String expirySmsFlag, String topupSmsFlag,
			MstbMasterTable mstbMasterTableByDefaultPaymentMode,
			MstbMasterTable mstbMasterTableByInformationSource, MstbBankMaster mstbBankMaster,
			FmtbArContCodeMaster fmtbArContCodeMaster, AmtbAcctType amtbAcctType,
			Set<AmtbCorporateDetail> amtbCorporateDetails, Set<AmtbPersonalDetail> amtbPersonalDetails,
			Set<BmtbBillGenError> bmtbBillGenErrorsByTopLevelAccountNo,
			Set<BmtbBillGenError> bmtbBillGenErrorsByBillableAccountNo,
			Set<BmtbInvoiceDetail> bmtbInvoiceDetails, Set<TmtbTxnReviewReq> tmtbTxnReviewReqs,
			Set<AmtbSubscProdReq> amtbProdSubscReqs,
			Set<AmtbCredRevReq> amtbCredRevReqs, Set<BmtbInvoiceHeader> bmtbInvoiceHeadersByAccountNo,
			Set<BmtbInvoiceHeader> bmtbInvoiceHeadersByDebtTo, Set<AmtbSubscTo> amtbSubscTos,
			Set<AmtbAcctLatePymt> amtbAcctLatePymts, Set<BmtbInvoiceSummary> bmtbInvoiceSummaries,
			Set<PmtbProductRetag> pmtbProductRetagsByCurrentAccountNo,
			Set<PmtbProductRetag> pmtbProductRetagsByNewAccountNo,
			Set<AmtbAcctSalesperson> amtbAcctSalespersons, Set<AmtbAcctBillCycle> amtbAcctBillCycles,
			Set<BmtbInvoiceDepositTxn> bmtbInvoiceDepositTxns, Set<BmtbPaymentReceipt> bmtbPaymentReceipts,
			Set<AmtbSubscToHist> amtbSubscToHists, Set<AmtbAcctEarlyPymt> amtbAcctEarlyPymts,
			Set<AmtbAcctCredTerm> amtbAcctCredTerms, Set<AmtbApplication> amtbApplications,
			Set<AmtbAcctVolDisc> amtbAcctVolDiscs, Set<AmtbAcctPromotion> amtbAcctPromotions,
			Set<LrtbRewardAccount> lrtbRewardAccounts, Set<AmtbAcctStatus> amtbAcctStatuses,
			Set<AmtbContactPerson> amtbContactPersons, Set<AmtbAcctMainContact> amtbAcctMainContacts,
			Set<BmtbNote> bmtbNotes, Set<TmtbAcquireTxn> tmtbAcquireTxns,
			BmtbLastInvoiceLog bmtbLastInvoiceLog, Set<AmtbAcctAdminFee> amtbAcctAdminFees,
			Set<AmtbBillReq> amtbBillReqs, Set<PmtbProduct> pmtbProducts,
			Set<AmtbAcctCredLimit> amtbAcctCredLimits, Set<AmtbAccount> amtbAccounts,
			AmtbAccount amtbAccount, MstbBranchMaster mstbBranchMaster,
			Set<PmtbProductType> pmtbProductTypes, Set<BmtbBillGenReq> bmtbBillGenReqs,
			String govtEInvoiceFlag, MstbMasterTable mstbMasterTableByBusinessUnit, String overdueReminder, String reminderEmail, 
			String printTaxInvoiceOnly, Set<IttbCpMasterTagAcct> ittbCpMasterTagAcct, String aceIndicator,String coupaIndicator, String pubbsFlag, String fiFlag, 
			String eInvoiceEmailFlag, String eInvoiceEmail, String eInvoiceEmailSubject, String eInvoiceEmailZipFlag, 
			String eInvoiceEmailAttachment, String eInvoiceEmailPage) {
		this.custNo = custNo;
		this.accountCategory = accountCategory;
		this.creditLimit = creditLimit;
		this.tempCreditLimit = tempCreditLimit;
		this.creditBalance = creditBalance;
		this.deposit = deposit;
		this.bankAcctNo = bankAcctNo;
		this.accountBalance = accountBalance;
		this.nameOnCard = nameOnCard;
		this.accountName = accountName;
		this.code = code;
		this.invoiceFormat = invoiceFormat;
		this.invoiceSorting = invoiceSorting;
		this.invoicePrinting = invoicePrinting;
		this.createdDt = createdDt;
		this.updatedDt = updatedDt;
		this.updatedBy = updatedBy;
		this.createdBy = createdBy;
		this.version = version;
		this.einvoiceFlag = einvoiceFlag;
		this.smsFlag = smsFlag;
		this.smsExpiryFlag = expirySmsFlag;
		this.smsTopupFlag = topupSmsFlag;
		this.mstbMasterTableByDefaultPaymentMode = mstbMasterTableByDefaultPaymentMode;
		this.mstbMasterTableByInformationSource = mstbMasterTableByInformationSource;
		this.mstbBankMaster = mstbBankMaster;
		this.fmtbArContCodeMaster = fmtbArContCodeMaster;
		this.amtbAcctType = amtbAcctType;
		this.amtbCorporateDetails = amtbCorporateDetails;
		this.amtbPersonalDetails = amtbPersonalDetails;
		this.bmtbBillGenErrorsByTopLevelAccountNo = bmtbBillGenErrorsByTopLevelAccountNo;
		this.bmtbBillGenErrorsByBillableAccountNo = bmtbBillGenErrorsByBillableAccountNo;
		this.bmtbInvoiceDetails = bmtbInvoiceDetails;
		this.tmtbTxnReviewReqs = tmtbTxnReviewReqs;
		this.amtbCredRevReqs = amtbCredRevReqs;
		this.bmtbInvoiceHeadersByAccountNo = bmtbInvoiceHeadersByAccountNo;
		this.bmtbInvoiceHeadersByDebtTo = bmtbInvoiceHeadersByDebtTo;
		this.amtbSubscTos = amtbSubscTos;
		this.amtbProdSubscReqs = amtbProdSubscReqs;
		this.amtbAcctLatePymts = amtbAcctLatePymts;
		this.bmtbInvoiceSummaries = bmtbInvoiceSummaries;
		this.pmtbProductRetagsByCurrentAccountNo = pmtbProductRetagsByCurrentAccountNo;
		this.pmtbProductRetagsByNewAccountNo = pmtbProductRetagsByNewAccountNo;
		this.amtbAcctSalespersons = amtbAcctSalespersons;
		this.amtbAcctBillCycles = amtbAcctBillCycles;
		this.bmtbInvoiceDepositTxns = bmtbInvoiceDepositTxns;
		this.bmtbPaymentReceipts = bmtbPaymentReceipts;
		this.amtbSubscToHists = amtbSubscToHists;
		this.amtbAcctEarlyPymts = amtbAcctEarlyPymts;
		this.amtbAcctCredTerms = amtbAcctCredTerms;
		this.amtbApplications = amtbApplications;
		this.amtbAcctVolDiscs = amtbAcctVolDiscs;
		this.lrtbRewardAccounts = lrtbRewardAccounts;
		this.amtbAcctStatuses = amtbAcctStatuses;
		this.amtbContactPersons = amtbContactPersons;
		this.amtbAcctMainContacts = amtbAcctMainContacts;
		this.amtbAcctPromotions = amtbAcctPromotions;
		this.bmtbNotes = bmtbNotes;
		this.tmtbAcquireTxns = tmtbAcquireTxns;
		this.bmtbLastInvoiceLog = bmtbLastInvoiceLog;
		this.amtbAcctAdminFees = amtbAcctAdminFees;
		this.amtbBillReqs = amtbBillReqs;
		this.pmtbProducts = pmtbProducts;
		this.amtbAcctCredLimits = amtbAcctCredLimits;
		this.amtbAccounts = amtbAccounts;
		this.amtbAccount = amtbAccount;
		this.mstbBranchMaster = mstbBranchMaster;
		this.pmtbProductTypes = pmtbProductTypes;
		this.bmtbBillGenReqs = bmtbBillGenReqs;
		this.govtEInvoiceFlag = govtEInvoiceFlag;
		this.mstbMasterTableByBusinessUnit = mstbMasterTableByBusinessUnit;
		this.overdueReminder = overdueReminder;
		this.reminderEmail = reminderEmail;
		this.printTaxInvoiceOnly = printTaxInvoiceOnly;
		this.ittbCpMasterTagAcct = ittbCpMasterTagAcct;
		this.aceIndicator = aceIndicator;
		this.coupaIndicator = coupaIndicator;
		this.pubbsFlag = pubbsFlag;
		this.fiFlag = fiFlag;
		this.eInvoiceEmailFlag = eInvoiceEmailFlag;
		this.eInvoiceEmail = eInvoiceEmail;
		this.eInvoiceEmailSubject = eInvoiceEmailSubject;
		this.eInvoiceEmailZipFlag = eInvoiceEmailZipFlag;
		this.eInvoiceEmailAttachment = eInvoiceEmailAttachment;
		this.eInvoiceEmailPage = eInvoiceEmailPage;
	}

	// Property accessors

	public String getOverdueReminder() {
		return overdueReminder;
	}

	public void setOverdueReminder(String overdueReminder) {
		this.overdueReminder = overdueReminder;
	}

	public String getReminderEmail() {
		return reminderEmail;
	}

	public void setReminderEmail(String reminderEmail) {
		this.reminderEmail = reminderEmail;
	}

	public String getParentNo() {
		return parentNo;
	}

	public void setParentNo(String parentNo) {
		this.parentNo = parentNo;
	}
	
	public String getParentParentNo() {
		return parentParentNo;
	}

	public void setParentParentNo(String parentParentNo) {
		this.parentParentNo = parentParentNo;
	}
	
	public Integer getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(Integer accountNo) {
		this.accountNo = accountNo;
	}

	public String getCustNo() {
		return this.custNo;
	}

	public void setCustNo(String custNo) {
		this.custNo = custNo;
	}

	public String getAccountCategory() {
		return this.accountCategory;
	}

	public void setAccountCategory(String accountCategory) {
		this.accountCategory = accountCategory;
	}

	public BigDecimal getCreditLimit() {
		return this.creditLimit;
	}

	public void setCreditLimit(BigDecimal creditLimit) {
		this.creditLimit = creditLimit;
	}

	public BigDecimal getTempCreditLimit() {
		return this.tempCreditLimit;
	}

	public void setTempCreditLimit(BigDecimal tempCreditLimit) {
		this.tempCreditLimit = tempCreditLimit;
	}

	public BigDecimal getCreditBalance() {
		return this.creditBalance;
	}

	public void setCreditBalance(BigDecimal creditBalance) {
		this.creditBalance = creditBalance;
	}

	public BigDecimal getDeposit() {
		return this.deposit;
	}

	public void setDeposit(BigDecimal deposit) {
		this.deposit = deposit;
	}

	public String getBankAcctNo() {
		return this.bankAcctNo;
	}

	public void setBankAcctNo(String bankAcctNo) {
		this.bankAcctNo = bankAcctNo;
	}

	public BigDecimal getAccountBalance() {
		return this.accountBalance;
	}

	public void setAccountBalance(BigDecimal accountBalance) {
		this.accountBalance = accountBalance;
	}

	public String getNameOnCard() {
		return this.nameOnCard;
	}

	public void setNameOnCard(String nameOnCard) {
		this.nameOnCard = nameOnCard;
	}

	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getInvoiceFormat() {
		return this.invoiceFormat;
	}

	public void setInvoiceFormat(String invoiceFormat) {
		this.invoiceFormat = invoiceFormat;
	}

	public String getInvoiceSorting() {
		return this.invoiceSorting;
	}

	public void setInvoiceSorting(String invoiceSorting) {
		this.invoiceSorting = invoiceSorting;
	}
	
	public String getInvoicePrinting() {
		return this.invoicePrinting;
	}

	public void setInvoicePrinting(String invoicePrinting) {
		this.invoicePrinting = invoicePrinting;
	}

	public Timestamp getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Timestamp createdDt) {
		this.createdDt = createdDt;
	}

	public Timestamp getUpdatedDt() {
		return this.updatedDt;
	}

	public void setUpdatedDt(Timestamp updatedDt) {
		this.updatedDt = updatedDt;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getEinvoiceFlag() {
		return this.einvoiceFlag;
	}

	public void setEinvoiceFlag(String einvoiceFlag) {
		this.einvoiceFlag = einvoiceFlag;
	}
	
	public String getRecurringFlag() {
		return recurringFlag;
	}

	public void setRecurringFlag(String recurringFlag) {
		this.recurringFlag = recurringFlag;
	}
	
	public Integer getRecurringChargeDay() {
		return recurringChargeDay;
	}

	public void setRecurringChargeDay(Integer recurringChargeDay) {
		this.recurringChargeDay = recurringChargeDay;
	}

	public String getSmsFlag() {
		return this.smsFlag;
	}

	public void setSmsFlag(String smsFlag) {
		this.smsFlag = smsFlag;
	}
	
	public String getSmsExpiryFlag() {
		return this.smsExpiryFlag;
	}

	public void setSmsExpiryFlag(String smsExpiryFlag) {
		this.smsExpiryFlag = smsExpiryFlag;
	}
	
	public String getSmsTopupFlag() {
		return this.smsTopupFlag;
	}

	public void setSmsTopupFlag(String smsTopupFlag) {
		this.smsTopupFlag = smsTopupFlag;
	}

	public MstbMasterTable getMstbMasterTableByDefaultPaymentMode() {
		return this.mstbMasterTableByDefaultPaymentMode;
	}

	public void setMstbMasterTableByDefaultPaymentMode(MstbMasterTable mstbMasterTableByDefaultPaymentMode) {
		this.mstbMasterTableByDefaultPaymentMode = mstbMasterTableByDefaultPaymentMode;
	}

	public MstbMasterTable getMstbMasterTableByInformationSource() {
		return this.mstbMasterTableByInformationSource;
	}

	public void setMstbMasterTableByInformationSource(MstbMasterTable mstbMasterTableByInformationSource) {
		this.mstbMasterTableByInformationSource = mstbMasterTableByInformationSource;
	}

	public MstbBankMaster getMstbBankMaster() {
		return this.mstbBankMaster;
	}

	public void setMstbBankMaster(MstbBankMaster mstbBankMaster) {
		this.mstbBankMaster = mstbBankMaster;
	}

	public FmtbArContCodeMaster getFmtbArContCodeMaster() {
		return this.fmtbArContCodeMaster;
	}

	public void setFmtbArContCodeMaster(FmtbArContCodeMaster fmtbArContCodeMaster) {
		this.fmtbArContCodeMaster = fmtbArContCodeMaster;
	}

	public AmtbAcctType getAmtbAcctType() {
		return this.amtbAcctType;
	}

	public void setAmtbAcctType(AmtbAcctType amtbAcctType) {
		this.amtbAcctType = amtbAcctType;
	}

	public Set<AmtbCorporateDetail> getAmtbCorporateDetails() {
		return this.amtbCorporateDetails;
	}

	public void setAmtbCorporateDetails(Set<AmtbCorporateDetail> amtbCorporateDetails) {
		this.amtbCorporateDetails = amtbCorporateDetails;
	}

	public Set<AmtbPersonalDetail> getAmtbPersonalDetails() {
		return this.amtbPersonalDetails;
	}

	public void setAmtbPersonalDetails(Set<AmtbPersonalDetail> amtbPersonalDetails) {
		this.amtbPersonalDetails = amtbPersonalDetails;
	}

	public Set<BmtbBillGenError> getBmtbBillGenErrorsByTopLevelAccountNo() {
		return this.bmtbBillGenErrorsByTopLevelAccountNo;
	}

	public void setBmtbBillGenErrorsByTopLevelAccountNo(
			Set<BmtbBillGenError> bmtbBillGenErrorsByTopLevelAccountNo) {
		this.bmtbBillGenErrorsByTopLevelAccountNo = bmtbBillGenErrorsByTopLevelAccountNo;
	}

	public Set<BmtbBillGenError> getBmtbBillGenErrorsByBillableAccountNo() {
		return this.bmtbBillGenErrorsByBillableAccountNo;
	}

	public void setBmtbBillGenErrorsByBillableAccountNo(
			Set<BmtbBillGenError> bmtbBillGenErrorsByBillableAccountNo) {
		this.bmtbBillGenErrorsByBillableAccountNo = bmtbBillGenErrorsByBillableAccountNo;
	}

	public Set<BmtbInvoiceDetail> getBmtbInvoiceDetails() {
		return this.bmtbInvoiceDetails;
	}

	public void setBmtbInvoiceDetails(Set<BmtbInvoiceDetail> bmtbInvoiceDetails) {
		this.bmtbInvoiceDetails = bmtbInvoiceDetails;
	}

	public Set<TmtbTxnReviewReq> getTmtbTxnReviewReqs() {
		return this.tmtbTxnReviewReqs;
	}

	public void setTmtbTxnReviewReqs(Set<TmtbTxnReviewReq> tmtbTxnReviewReqs) {
		this.tmtbTxnReviewReqs = tmtbTxnReviewReqs;
	}

	public Set<AmtbCredRevReq> getAmtbCredRevReqs() {
		return this.amtbCredRevReqs;
	}

	public void setAmtbCredRevReqs(Set<AmtbCredRevReq> amtbCredRevReqs) {
		this.amtbCredRevReqs = amtbCredRevReqs;
	}

	public Set<BmtbInvoiceHeader> getBmtbInvoiceHeadersByAccountNo() {
		return this.bmtbInvoiceHeadersByAccountNo;
	}

	public void setBmtbInvoiceHeadersByAccountNo(Set<BmtbInvoiceHeader> bmtbInvoiceHeadersByAccountNo) {
		this.bmtbInvoiceHeadersByAccountNo = bmtbInvoiceHeadersByAccountNo;
	}

	public Set<BmtbInvoiceHeader> getBmtbInvoiceHeadersByDebtTo() {
		return this.bmtbInvoiceHeadersByDebtTo;
	}

	public void setBmtbInvoiceHeadersByDebtTo(Set<BmtbInvoiceHeader> bmtbInvoiceHeadersByDebtTo) {
		this.bmtbInvoiceHeadersByDebtTo = bmtbInvoiceHeadersByDebtTo;
	}

	public Set<AmtbSubscTo> getAmtbSubscTos() {
		return this.amtbSubscTos;
	}

	public void setAmtbSubscTos(Set<AmtbSubscTo> amtbSubscTos) {
		this.amtbSubscTos = amtbSubscTos;
	}

	public Set<AmtbSubscProdReq> getAmtbProdSubscReqs() {
		return this.amtbProdSubscReqs;
	}

	public void setAmtbProdSubscReqs(Set<AmtbSubscProdReq> amtbProdSubscReqs) {
		this.amtbProdSubscReqs = amtbProdSubscReqs;
	}

	public Set<AmtbAcctLatePymt> getAmtbAcctLatePymts() {
		return this.amtbAcctLatePymts;
	}

	public void setAmtbAcctLatePymts(Set<AmtbAcctLatePymt> amtbAcctLatePymts) {
		this.amtbAcctLatePymts = amtbAcctLatePymts;
	}

	public Set<BmtbInvoiceSummary> getBmtbInvoiceSummaries() {
		return this.bmtbInvoiceSummaries;
	}

	public void setBmtbInvoiceSummaries(Set<BmtbInvoiceSummary> bmtbInvoiceSummaries) {
		this.bmtbInvoiceSummaries = bmtbInvoiceSummaries;
	}

	public Set<PmtbProductRetag> getPmtbProductRetagsByCurrentAccountNo() {
		return this.pmtbProductRetagsByCurrentAccountNo;
	}

	public void setPmtbProductRetagsByCurrentAccountNo(
			Set<PmtbProductRetag> pmtbProductRetagsByCurrentAccountNo) {
		this.pmtbProductRetagsByCurrentAccountNo = pmtbProductRetagsByCurrentAccountNo;
	}

	public Set<PmtbProductRetag> getPmtbProductRetagsByNewAccountNo() {
		return this.pmtbProductRetagsByNewAccountNo;
	}

	public void setPmtbProductRetagsByNewAccountNo(Set<PmtbProductRetag> pmtbProductRetagsByNewAccountNo) {
		this.pmtbProductRetagsByNewAccountNo = pmtbProductRetagsByNewAccountNo;
	}

	public Set<AmtbAcctSalesperson> getAmtbAcctSalespersons() {
		return this.amtbAcctSalespersons;
	}

	public void setAmtbAcctSalespersons(Set<AmtbAcctSalesperson> amtbAcctSalespersons) {
		this.amtbAcctSalespersons = amtbAcctSalespersons;
	}

	public Set<AmtbAcctBillCycle> getAmtbAcctBillCycles() {
		return this.amtbAcctBillCycles;
	}

	public void setAmtbAcctBillCycles(Set<AmtbAcctBillCycle> amtbAcctBillCycles) {
		this.amtbAcctBillCycles = amtbAcctBillCycles;
	}

	public Set<BmtbInvoiceDepositTxn> getBmtbInvoiceDepositTxns() {
		return this.bmtbInvoiceDepositTxns;
	}

	public void setBmtbInvoiceDepositTxns(Set<BmtbInvoiceDepositTxn> bmtbInvoiceDepositTxns) {
		this.bmtbInvoiceDepositTxns = bmtbInvoiceDepositTxns;
	}

	public Set<BmtbPaymentReceipt> getBmtbPaymentReceipts() {
		return this.bmtbPaymentReceipts;
	}

	public void setBmtbPaymentReceipts(Set<BmtbPaymentReceipt> bmtbPaymentReceipts) {
		this.bmtbPaymentReceipts = bmtbPaymentReceipts;
	}

	public Set<AmtbSubscToHist> getAmtbSubscToHists() {
		return this.amtbSubscToHists;
	}

	public void setAmtbSubscToHists(Set<AmtbSubscToHist> amtbSubscToHists) {
		this.amtbSubscToHists = amtbSubscToHists;
	}

	public Set<AmtbAcctEarlyPymt> getAmtbAcctEarlyPymts() {
		return this.amtbAcctEarlyPymts;
	}

	public void setAmtbAcctEarlyPymts(Set<AmtbAcctEarlyPymt> amtbAcctEarlyPymts) {
		this.amtbAcctEarlyPymts = amtbAcctEarlyPymts;
	}

	public Set<AmtbAcctCredTerm> getAmtbAcctCredTerms() {
		return this.amtbAcctCredTerms;
	}

	public void setAmtbAcctCredTerms(Set<AmtbAcctCredTerm> amtbAcctCredTerms) {
		this.amtbAcctCredTerms = amtbAcctCredTerms;
	}

	public Set<AmtbApplication> getAmtbApplications() {
		return this.amtbApplications;
	}

	public void setAmtbApplications(Set<AmtbApplication> amtbApplications) {
		this.amtbApplications = amtbApplications;
	}

	public Set<AmtbAcctVolDisc> getAmtbAcctVolDiscs() {
		return this.amtbAcctVolDiscs;
	}

	public void setAmtbAcctVolDiscs(Set<AmtbAcctVolDisc> amtbAcctVolDiscs) {
		this.amtbAcctVolDiscs = amtbAcctVolDiscs;
	}

	public Set<LrtbRewardAccount> getLrtbRewardAccounts() {
		return this.lrtbRewardAccounts;
	}

	public void setLrtbRewardAccounts(Set<LrtbRewardAccount> lrtbRewardAccounts) {
		this.lrtbRewardAccounts = lrtbRewardAccounts;
	}

	public Set<AmtbAcctStatus> getAmtbAcctStatuses() {
		return this.amtbAcctStatuses;
	}

	public void setAmtbAcctStatuses(Set<AmtbAcctStatus> amtbAcctStatuses) {
		this.amtbAcctStatuses = amtbAcctStatuses;
	}

	public Set<AmtbContactPerson> getAmtbContactPersons() {
		return this.amtbContactPersons;
	}

	public void setAmtbContactPersons(Set<AmtbContactPerson> amtbContactPersons) {
		this.amtbContactPersons = amtbContactPersons;
	}

	public Set<AmtbAcctMainContact> getAmtbAcctMainContacts() {
		return this.amtbAcctMainContacts;
	}

	public void setAmtbAcctMainContacts(Set<AmtbAcctMainContact> amtbAcctMainContacts) {
		this.amtbAcctMainContacts = amtbAcctMainContacts;
	}

	public Set<BmtbNote> getBmtbNotes() {
		return this.bmtbNotes;
	}

	public void setBmtbNotes(Set<BmtbNote> bmtbNotes) {
		this.bmtbNotes = bmtbNotes;
	}

	public Set<TmtbAcquireTxn> getTmtbAcquireTxns() {
		return this.tmtbAcquireTxns;
	}

	public void setTmtbAcquireTxns(Set<TmtbAcquireTxn> tmtbAcquireTxns) {
		this.tmtbAcquireTxns = tmtbAcquireTxns;
	}
	
	public BmtbLastInvoiceLog getBmtbLastInvoiceLog() {
		return this.bmtbLastInvoiceLog;
	}

	public void setBmtbLastInvoiceLog(BmtbLastInvoiceLog bmtbLastInvoiceLog) {
		this.bmtbLastInvoiceLog = bmtbLastInvoiceLog;
	}

	public Set<AmtbAcctAdminFee> getAmtbAcctAdminFees() {
		return this.amtbAcctAdminFees;
	}

	public void setAmtbAcctAdminFees(Set<AmtbAcctAdminFee> amtbAcctAdminFees) {
		this.amtbAcctAdminFees = amtbAcctAdminFees;
	}

	public Set<AmtbBillReq> getAmtbBillReqs() {
		return this.amtbBillReqs;
	}

	public void setAmtbBillReqs(Set<AmtbBillReq> amtbBillReqs) {
		this.amtbBillReqs = amtbBillReqs;
	}

	public Set<PmtbProduct> getPmtbProducts() {
		return this.pmtbProducts;
	}

	public void setPmtbProducts(Set<PmtbProduct> pmtbProducts) {
		this.pmtbProducts = pmtbProducts;
	}

	public Set<AmtbAcctCredLimit> getAmtbAcctCredLimits() {
		return this.amtbAcctCredLimits;
	}

	public void setAmtbAcctCredLimits(Set<AmtbAcctCredLimit> amtbAcctCredLimits) {
		this.amtbAcctCredLimits = amtbAcctCredLimits;
	}

	public Set<AmtbAccount> getAmtbAccounts() {
		return this.amtbAccounts;
	}

	public void setAmtbAccounts(Set<AmtbAccount> amtbAccounts) {
		this.amtbAccounts = amtbAccounts;
	}

	public AmtbAccount getAmtbAccount() {
		return this.amtbAccount;
	}

	public void setAmtbAccount(AmtbAccount amtbAccount) {
		this.amtbAccount = amtbAccount;
	}

	public MstbBranchMaster getMstbBranchMaster() {
		return this.mstbBranchMaster;
	}

	public void setMstbBranchMaster(MstbBranchMaster mstbBranchMaster) {
		this.mstbBranchMaster = mstbBranchMaster;
	}

	public Set<PmtbProductType> getPmtbProductTypes() {
		return this.pmtbProductTypes;
	}

	public void setPmtbProductTypes(Set<PmtbProductType> pmtbProductTypes) {
		this.pmtbProductTypes = pmtbProductTypes;
	}

	public Set<BmtbBillGenReq> getBmtbBillGenReqs() {
		return this.bmtbBillGenReqs;
	}

	public void setBmtbBillGenReqs(Set<BmtbBillGenReq> bmtbBillGenReqs) {
		this.bmtbBillGenReqs = bmtbBillGenReqs;
	}

	public Set<AmtbAcctPromotion> getAmtbAcctPromotions() {
		return this.amtbAcctPromotions;
	}

	public void setAmtbAcctPromotions(Set<AmtbAcctPromotion> amtbAcctPromotions) {
		this.amtbAcctPromotions = amtbAcctPromotions;
	}

	public String getGovtEInvoiceFlag() {
		return govtEInvoiceFlag;
	}

	public void setGovtEInvoiceFlag(String govtEInvoiceFlag) {
		this.govtEInvoiceFlag = govtEInvoiceFlag;
	}

	public MstbMasterTable getMstbMasterTableByBusinessUnit() {
		return mstbMasterTableByBusinessUnit;
	}

	public void setMstbMasterTableByBusinessUnit(MstbMasterTable mstbMasterTableByBusinessUnit) {
		this.mstbMasterTableByBusinessUnit = mstbMasterTableByBusinessUnit;
	}
	
	public String getOutsourcePrintingFlag() {
		return outsourcePrintingFlag;
	}

	public void setOutsourcePrintingFlag(String outsourcePrintingFlag) {
		this.outsourcePrintingFlag = outsourcePrintingFlag;
	}

	public String getPrintTaxInvoiceOnly() {
		return printTaxInvoiceOnly;
	}

	public void setPrintTaxInvoiceOnly(String printTaxInvoiceOnly) {
		this.printTaxInvoiceOnly = printTaxInvoiceOnly;
	}
	
	public Set<IttbCpMasterTagAcct> getIttbCpMasterTagAcct() {
		return ittbCpMasterTagAcct;
	}

	public void setIttbCpMasterTagAcct(Set<IttbCpMasterTagAcct> ittbCpMasterTagAcct) {
		this.ittbCpMasterTagAcct = ittbCpMasterTagAcct;
	}

	public String getAceIndicator() {
		return aceIndicator;
	}

	public void setAceIndicator(String aceIndicator) {
		this.aceIndicator = aceIndicator;
	}
	
	public String getPubbsFlag() {
		return pubbsFlag;
	}

	public void setPubbsFlag(String pubbsFlag) {
		this.pubbsFlag = pubbsFlag;
	}
	
	public String getFiFlag() {
		return fiFlag;
	}

	public void setFiFlag(String fiFlag) {
		this.fiFlag = fiFlag;
	}
	
	public String geteInvoiceEmailFlag() {
		return eInvoiceEmailFlag;
	}

	public void seteInvoiceEmailFlag(String eInvoiceEmailFlag) {
		this.eInvoiceEmailFlag = eInvoiceEmailFlag;
	}

	public String geteInvoiceEmail() {
		return eInvoiceEmail;
	}

	public void seteInvoiceEmail(String eInvoiceEmail) {
		this.eInvoiceEmail = eInvoiceEmail;
	}

	public String geteInvoiceEmailSubject() {
		return eInvoiceEmailSubject;
	}

	public void seteInvoiceEmailSubject(String eInvoiceEmailSubject) {
		this.eInvoiceEmailSubject = eInvoiceEmailSubject;
	}

	public String geteInvoiceEmailZipFlag() {
		return eInvoiceEmailZipFlag;
	}

	public void seteInvoiceEmailZipFlag(String eInvoiceEmailZipFlag) {
		this.eInvoiceEmailZipFlag = eInvoiceEmailZipFlag;
	}

	public String geteInvoiceEmailAttachment() {
		return eInvoiceEmailAttachment;
	}

	public void seteInvoiceEmailAttachment(String eInvoiceEmailAttachment) {
		this.eInvoiceEmailAttachment = eInvoiceEmailAttachment;
	}

	public String geteInvoiceEmailPage() {
		return eInvoiceEmailPage;
	}

	public void seteInvoiceEmailPage(String eInvoiceEmailPage) {
		this.eInvoiceEmailPage = eInvoiceEmailPage;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("custNo").append("='").append(getCustNo()).append("' ");
		buffer.append("accountCategory").append("='").append(getAccountCategory()).append("' ");
		buffer.append("creditLimit").append("='").append(getCreditLimit()).append("' ");
		buffer.append("tempCreditLimit").append("='").append(getTempCreditLimit()).append("' ");
		buffer.append("creditBalance").append("='").append(getCreditBalance()).append("' ");
		buffer.append("deposit").append("='").append(getDeposit()).append("' ");
		buffer.append("bankAcctNo").append("='").append(getBankAcctNo()).append("' ");
		buffer.append("accountBalance").append("='").append(getAccountBalance()).append("' ");
		buffer.append("nameOnCard").append("='").append(getNameOnCard()).append("' ");
		buffer.append("accountName").append("='").append(getAccountName()).append("' ");
		buffer.append("code").append("='").append(getCode()).append("' ");
		buffer.append("invoiceFormat").append("='").append(getInvoiceFormat()).append("' ");
		buffer.append("invoiceSorting").append("='").append(getInvoiceSorting()).append("' ");
		buffer.append("invoicePrinting").append("='").append(getInvoicePrinting()).append("' ");
		buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");
		buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");
		buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");
		buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
		buffer.append("version").append("='").append(getVersion()).append("' ");
		buffer.append("einvoiceFlag").append("='").append(getEinvoiceFlag()).append("' ");
		buffer.append("recurringFlag").append("='").append(getRecurringFlag()).append("' ");
		buffer.append("recurringChargeDay").append("='").append(getRecurringChargeDay()).append("' ");
		buffer.append("smsFlag").append("='").append(getSmsFlag()).append("' ");
		buffer.append("smsExpiryFlag").append("='").append(getSmsExpiryFlag()).append("' ");
		buffer.append("smsTopupFlag").append("='").append(getSmsTopupFlag()).append("' ");
		buffer.append("govtEInvoiceFlag").append("='").append(getGovtEInvoiceFlag()).append("' ");
		buffer.append("overdueReminder").append("='").append(getOverdueReminder()).append("' ");
		buffer.append("reminderEmail").append("='").append(getReminderEmail()).append("' ");
		buffer.append("printTaxInvoiceOnly").append("='").append(getPrintTaxInvoiceOnly()).append("' ");
		buffer.append("aceIndicator").append("='").append(getAceIndicator()).append("' ");
		buffer.append("coupaIndicator").append("='").append(getCoupaIndicator()).append("' ");
		buffer.append("pubbsFlag").append("='").append(getPubbsFlag()).append("' ");
		buffer.append("fiFlag").append("='").append(getFiFlag()).append("' ");
		buffer.append("eInvoiceEmailFlag").append("='").append(geteInvoiceEmailFlag()).append("' ");
		buffer.append("eInvoiceEmail").append("='").append(geteInvoiceEmail()).append("' ");
		buffer.append("eInvoiceEmailSubject").append("='").append(geteInvoiceEmailSubject()).append("' ");
		buffer.append("eInvoiceEmailZipFlag").append("='").append(geteInvoiceEmailZipFlag()).append("' ");
		buffer.append("eInvoiceEmailAttachment").append("='").append(geteInvoiceEmailAttachment()).append("' ");
		buffer.append("eInvoiceEmailPage").append("='").append(geteInvoiceEmailPage()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AmtbAccount))
			return false;
		AmtbAccount castOther = (AmtbAccount) other;

		return ((this.getAccountNo() == castOther.getAccountNo()) || (this.getAccountNo() != null
				&& castOther.getAccountNo() != null && this.getAccountNo().equals(castOther.getAccountNo())))
				&& ((this.getCustNo() == castOther.getCustNo()) || (this.getCustNo() != null
						&& castOther.getCustNo() != null && this.getCustNo().equals(castOther.getCustNo())))
				&& ((this.getAccountCategory() == castOther.getAccountCategory()) || (this
						.getAccountCategory() != null && castOther.getAccountCategory() != null && this
						.getAccountCategory().equals(castOther.getAccountCategory())))
				&& ((this.getCreditLimit() == castOther.getCreditLimit()) || (this.getCreditLimit() != null
						&& castOther.getCreditLimit() != null && this.getCreditLimit().equals(
						castOther.getCreditLimit())))
				&& ((this.getTempCreditLimit() == castOther.getTempCreditLimit()) || (this
						.getTempCreditLimit() != null && castOther.getTempCreditLimit() != null && this
						.getTempCreditLimit().equals(castOther.getTempCreditLimit())))
				&& ((this.getCreditBalance() == castOther.getCreditBalance()) || (this.getCreditBalance() != null
						&& castOther.getCreditBalance() != null && this.getCreditBalance().equals(
						castOther.getCreditBalance())))
				&& ((this.getDeposit() == castOther.getDeposit()) || (this.getDeposit() != null
						&& castOther.getDeposit() != null && this.getDeposit().equals(castOther.getDeposit())))
				&& ((this.getBankAcctNo() == castOther.getBankAcctNo()) || (this.getBankAcctNo() != null
						&& castOther.getBankAcctNo() != null && this.getBankAcctNo().equals(
						castOther.getBankAcctNo())))
				&& ((this.getAccountBalance() == castOther.getAccountBalance()) || (this.getAccountBalance() != null
						&& castOther.getAccountBalance() != null && this.getAccountBalance().equals(
						castOther.getAccountBalance())))
				&& ((this.getNameOnCard() == castOther.getNameOnCard()) || (this.getNameOnCard() != null
						&& castOther.getNameOnCard() != null && this.getNameOnCard().equals(
						castOther.getNameOnCard())))
				&& ((this.getAccountName() == castOther.getAccountName()) || (this.getAccountName() != null
						&& castOther.getAccountName() != null && this.getAccountName().equals(
						castOther.getAccountName())))
				&& ((this.getCode() == castOther.getCode()) || (this.getCode() != null
						&& castOther.getCode() != null && this.getCode().equals(castOther.getCode())))
				&& ((this.getInvoiceFormat() == castOther.getInvoiceFormat()) || (this.getInvoiceFormat() != null
						&& castOther.getInvoiceFormat() != null && this.getInvoiceFormat().equals(
						castOther.getInvoiceFormat())))
				&& ((this.getInvoiceSorting() == castOther.getInvoiceSorting()) || (this.getInvoiceSorting() != null
						&& castOther.getInvoiceSorting() != null && this.getInvoiceSorting().equals(
						castOther.getInvoiceSorting())))
				&& ((this.getInvoicePrinting() == castOther.getInvoicePrinting()) || (this.getInvoicePrinting() != null
						&& castOther.getInvoicePrinting() != null && this.getInvoicePrinting().equals(
						castOther.getInvoicePrinting())))
				&& ((this.getCreatedDt() == castOther.getCreatedDt()) || (this.getCreatedDt() != null
						&& castOther.getCreatedDt() != null && this.getCreatedDt().equals(
						castOther.getCreatedDt())))
				&& ((this.getUpdatedDt() == castOther.getUpdatedDt()) || (this.getUpdatedDt() != null
						&& castOther.getUpdatedDt() != null && this.getUpdatedDt().equals(
						castOther.getUpdatedDt())))
				&& ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this.getUpdatedBy() != null
						&& castOther.getUpdatedBy() != null && this.getUpdatedBy().equals(
						castOther.getUpdatedBy())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this.getCreatedBy().equals(
						castOther.getCreatedBy())))
				&& ((this.getVersion() == castOther.getVersion()) || (this.getVersion() != null
						&& castOther.getVersion() != null && this.getVersion().equals(castOther.getVersion())))
				&& ((this.getEinvoiceFlag() == castOther.getEinvoiceFlag()) || (this.getEinvoiceFlag() != null
						&& castOther.getEinvoiceFlag() != null && this.getEinvoiceFlag().equals(
						castOther.getEinvoiceFlag())))
				&& ((this.getRecurringFlag() == castOther.getRecurringFlag()) || (this.getRecurringFlag() != null
					&& castOther.getRecurringFlag() != null && this.getRecurringFlag().equals(castOther.getRecurringFlag())))
				&& ((this.getRecurringChargeDay() == castOther.getRecurringChargeDay()) || (this.getRecurringChargeDay() != null
					&& castOther.getRecurringChargeDay() != null && this.getRecurringChargeDay().equals(castOther.getRecurringChargeDay())))
				&& ((this.getSmsFlag() == castOther.getSmsFlag()) || (this.getSmsFlag() != null
						&& castOther.getSmsFlag() != null && this.getSmsFlag().equals(castOther.getSmsFlag())))
				&& ((this.getSmsExpiryFlag() == castOther.getSmsExpiryFlag()) || (this.getSmsExpiryFlag() != null
						&& castOther.getSmsExpiryFlag() != null && this.getSmsExpiryFlag().equals(castOther.getSmsExpiryFlag())))
				&& ((this.getSmsTopupFlag() == castOther.getSmsTopupFlag()) || (this.getSmsTopupFlag() != null
						&& castOther.getSmsTopupFlag() != null && this.getSmsTopupFlag().equals(castOther.getSmsTopupFlag())));
				/*&& ((this.getMstbMasterTableByDefaultPaymentMode() == castOther
						.getMstbMasterTableByDefaultPaymentMode()) || (this
						.getMstbMasterTableByDefaultPaymentMode() != null
						&& castOther.getMstbMasterTableByDefaultPaymentMode() != null && this
						.getMstbMasterTableByDefaultPaymentMode().equals(
								castOther.getMstbMasterTableByDefaultPaymentMode())))
				&& ((this.getMstbMasterTableByInformationSource() == castOther
						.getMstbMasterTableByInformationSource()) || (this
						.getMstbMasterTableByInformationSource() != null
						&& castOther.getMstbMasterTableByInformationSource() != null && this
						.getMstbMasterTableByInformationSource().equals(
								castOther.getMstbMasterTableByInformationSource())))
				&& ((this.getMstbBankMaster() == castOther.getMstbBankMaster()) || (this.getMstbBankMaster() != null
						&& castOther.getMstbBankMaster() != null && this.getMstbBankMaster().equals(
						castOther.getMstbBankMaster())))
				&& ((this.getFmtbArContCodeMaster() == castOther.getFmtbArContCodeMaster()) || (this
						.getFmtbArContCodeMaster() != null && castOther.getFmtbArContCodeMaster() != null && this
						.getFmtbArContCodeMaster().equals(castOther.getFmtbArContCodeMaster())))
				&& ((this.getAmtbAcctType() == castOther.getAmtbAcctType()) || (this.getAmtbAcctType() != null
						&& castOther.getAmtbAcctType() != null && this.getAmtbAcctType().equals(
						castOther.getAmtbAcctType())))
				&& ((this.getAmtbAccount() == castOther.getAmtbAccount()) || (this.getAmtbAccount() != null
						&& castOther.getAmtbAccount() != null && this.getAmtbAccount().equals(
						castOther.getAmtbAccount())))
				&& ((this.getMstbBranchMaster() == castOther.getMstbBranchMaster()) || (this
						.getMstbBranchMaster() != null && castOther.getMstbBranchMaster() != null && this
						.getMstbBranchMaster().equals(castOther.getMstbBranchMaster())))
				&& ((this.getGovtEInvoiceFlag() == castOther.getGovtEInvoiceFlag()) || (this
						.getGovtEInvoiceFlag() != null && castOther.getGovtEInvoiceFlag() != null && this
						.getGovtEInvoiceFlag().equals(castOther.getGovtEInvoiceFlag())))
				&& ((this.getMstbMasterTableByBusinessUnit() == castOther.getMstbMasterTableByBusinessUnit()) || (this
						.getMstbMasterTableByBusinessUnit() != null
						&& castOther.getMstbMasterTableByBusinessUnit() != null && this
						.getMstbMasterTableByBusinessUnit().equals(
								castOther.getMstbMasterTableByBusinessUnit())));*/
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAccountNo() == null ? 0 : this.getAccountNo().hashCode());
		result = 37 * result + (getCustNo() == null ? 0 : this.getCustNo().hashCode());
		result = 37 * result + (getAccountCategory() == null ? 0 : this.getAccountCategory().hashCode());
		result = 37 * result + (getCreditLimit() == null ? 0 : this.getCreditLimit().hashCode());
		result = 37 * result + (getTempCreditLimit() == null ? 0 : this.getTempCreditLimit().hashCode());
		result = 37 * result + (getCreditBalance() == null ? 0 : this.getCreditBalance().hashCode());
		result = 37 * result + (getDeposit() == null ? 0 : this.getDeposit().hashCode());
		result = 37 * result + (getBankAcctNo() == null ? 0 : this.getBankAcctNo().hashCode());
		result = 37 * result + (getAccountBalance() == null ? 0 : this.getAccountBalance().hashCode());
		result = 37 * result + (getNameOnCard() == null ? 0 : this.getNameOnCard().hashCode());
		result = 37 * result + (getAccountName() == null ? 0 : this.getAccountName().hashCode());
		result = 37 * result + (getCode() == null ? 0 : this.getCode().hashCode());
		result = 37 * result + (getInvoiceFormat() == null ? 0 : this.getInvoiceFormat().hashCode());
		result = 37 * result + (getInvoiceSorting() == null ? 0 : this.getInvoiceSorting().hashCode());
		result = 37 * result + (getInvoicePrinting() == null ? 0 : this.getInvoicePrinting().hashCode());
		result = 37 * result + (getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode());
		result = 37 * result + (getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode());
		result = 37 * result + (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result + (getEinvoiceFlag() == null ? 0 : this.getEinvoiceFlag().hashCode());
		result = 37 * result + (getRecurringFlag() == null ? 0 : this.getRecurringFlag().hashCode());
		result = 37 * result + (getRecurringChargeDay() == null ? 0 : this.getRecurringChargeDay().hashCode());
		result = 37 * result + (getSmsFlag() == null ? 0 : this.getSmsFlag().hashCode());
		result = 37 * result + (getSmsExpiryFlag() == null ? 0 : this.getSmsExpiryFlag().hashCode());
		result = 37 * result + (getSmsTopupFlag() == null ? 0 : this.getSmsTopupFlag().hashCode());
		result = 37 * result + (getGovtEInvoiceFlag() == null ? 0 : this.getGovtEInvoiceFlag().hashCode());
		result = 37 * result + (getOverdueReminder() == null ? 0 : this.getOverdueReminder().hashCode());
		result = 37 * result + (getReminderEmail() == null ? 0 : this.getReminderEmail().hashCode());
		result = 37 * result + (getPrintTaxInvoiceOnly() == null ? 0 : this.getPrintTaxInvoiceOnly().hashCode());
		result = 37 * result + (getAceIndicator() == null ? 0 : this.getAceIndicator().hashCode());
		result = 37 * result + (getPubbsFlag() == null ? 0 : this.getPubbsFlag().hashCode());
		result = 37 * result + (getFiFlag() == null ? 0 : this.getFiFlag().hashCode());
		result = 37 * result + (geteInvoiceEmailFlag() == null ? 0 : this.geteInvoiceEmailFlag().hashCode());
		result = 37 * result + (geteInvoiceEmail() == null ? 0 : this.geteInvoiceEmail().hashCode());
		result = 37 * result + (geteInvoiceEmailSubject() == null ? 0 : this.geteInvoiceEmailSubject().hashCode());
		result = 37 * result + (geteInvoiceEmailZipFlag() == null ? 0 : this.geteInvoiceEmailZipFlag().hashCode());
		result = 37 * result + (geteInvoiceEmailAttachment() == null ? 0 : this.geteInvoiceEmailAttachment().hashCode());
		result = 37 * result + (geteInvoiceEmailPage() == null ? 0 : this.geteInvoiceEmailPage().hashCode());

		// comment by Rodney due to lazy init
		// result = 37 * result + ( getMstbMasterTableByDefaultPaymentMode() == null ? 0 :
		// this.getMstbMasterTableByDefaultPaymentMode().hashCode() );
		// result = 37 * result + ( getMstbMasterTableByInformationSource() == null ? 0 :
		// this.getMstbMasterTableByInformationSource().hashCode() );
		// result = 37 * result + ( getMstbBankMaster() == null ? 0 : this.getMstbBankMaster().hashCode() );
		// result = 37 * result + ( getFmtbArContCodeMaster() == null ? 0 :
		// this.getFmtbArContCodeMaster().hashCode() );
		// result = 37 * result + ( getAmtbAcctType() == null ? 0 : this.getAmtbAcctType().hashCode() );
		// result = 37 * result + ( getAmtbAccount() == null ? 0 : this.getAmtbAccount().hashCode() );
		// result = 37 * result + ( getMstbBranchMaster() == null ? 0 : this.getMstbBranchMaster().hashCode()
		// );
		return result;
	}
}