package com.cdgtaxi.ibs.common.model;
// Generated Jul 20, 2009 4:09:43 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.master.model.MstbSalesperson;


/**
 * AmtbAcctSalesperson generated by hbm2java
 */

public class AmtbAcctSalesperson  implements java.io.Serializable, Auditable {


    // Fields    

    private Integer acctSalespersonNo;
    private Timestamp effectiveDtFrom;
    private Timestamp effectiveDtTo;
    private Integer version;
    private MstbSalesperson mstbSalesperson;
    private AmtbAccount amtbAccount;
    private AmtbAcctSalespersonReq amtbAcctSalespersonReq;


    // Constructors

    /** default constructor */
    public AmtbAcctSalesperson() {
    }

	/** minimal constructor */
    public AmtbAcctSalesperson(Timestamp effectiveDtFrom) {
        this.effectiveDtFrom = effectiveDtFrom;
    }
    
    /** full constructor */
    public AmtbAcctSalesperson(Timestamp effectiveDtFrom, Timestamp effectiveDtTo, Integer version, MstbSalesperson mstbSalesperson, AmtbAccount amtbAccount, AmtbAcctSalespersonReq amtbAcctSalespersonReq) {
        this.effectiveDtFrom = effectiveDtFrom;
        this.effectiveDtTo = effectiveDtTo;
        this.version = version;
        this.mstbSalesperson = mstbSalesperson;
        this.amtbAccount = amtbAccount;
        this.amtbAcctSalespersonReq = amtbAcctSalespersonReq;
    }
    

   
    // Property accessors

    public Integer getAcctSalespersonNo() {
        return this.acctSalespersonNo;
    }
    
    public void setAcctSalespersonNo(Integer acctSalespersonNo) {
        this.acctSalespersonNo = acctSalespersonNo;
    }

    public Timestamp getEffectiveDtFrom() {
        return this.effectiveDtFrom;
    }
    
    public void setEffectiveDtFrom(Timestamp effectiveDtFrom) {
        this.effectiveDtFrom = effectiveDtFrom;
    }

    public Timestamp getEffectiveDtTo() {
        return this.effectiveDtTo;
    }
    
    public void setEffectiveDtTo(Timestamp effectiveDtTo) {
        this.effectiveDtTo = effectiveDtTo;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public MstbSalesperson getMstbSalesperson() {
        return this.mstbSalesperson;
    }
    
    public void setMstbSalesperson(MstbSalesperson mstbSalesperson) {
        this.mstbSalesperson = mstbSalesperson;
    }

    public AmtbAccount getAmtbAccount() {
        return this.amtbAccount;
    }
    
    public void setAmtbAccount(AmtbAccount amtbAccount) {
        this.amtbAccount = amtbAccount;
    }

    public AmtbAcctSalespersonReq getAmtbAcctSalespersonReq() {
        return this.amtbAcctSalespersonReq;
    }
    
    public void setAmtbAcctSalespersonReq(AmtbAcctSalespersonReq amtbAcctSalespersonReq) {
        this.amtbAcctSalespersonReq = amtbAcctSalespersonReq;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("effectiveDtFrom").append("='").append(getEffectiveDtFrom()).append("' ");			
      buffer.append("effectiveDtTo").append("='").append(getEffectiveDtTo()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmtbAcctSalesperson) ) return false;
		 AmtbAcctSalesperson castOther = ( AmtbAcctSalesperson ) other; 
         
		 return ( (this.getAcctSalespersonNo()==castOther.getAcctSalespersonNo()) || ( this.getAcctSalespersonNo()!=null && castOther.getAcctSalespersonNo()!=null && this.getAcctSalespersonNo().equals(castOther.getAcctSalespersonNo()) ) )
 && ( (this.getEffectiveDtFrom()==castOther.getEffectiveDtFrom()) || ( this.getEffectiveDtFrom()!=null && castOther.getEffectiveDtFrom()!=null && this.getEffectiveDtFrom().equals(castOther.getEffectiveDtFrom()) ) )
 && ( (this.getEffectiveDtTo()==castOther.getEffectiveDtTo()) || ( this.getEffectiveDtTo()!=null && castOther.getEffectiveDtTo()!=null && this.getEffectiveDtTo().equals(castOther.getEffectiveDtTo()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getMstbSalesperson()==castOther.getMstbSalesperson()) || ( this.getMstbSalesperson()!=null && castOther.getMstbSalesperson()!=null && this.getMstbSalesperson().equals(castOther.getMstbSalesperson()) ) )
 && ( (this.getAmtbAccount()==castOther.getAmtbAccount()) || ( this.getAmtbAccount()!=null && castOther.getAmtbAccount()!=null && this.getAmtbAccount().equals(castOther.getAmtbAccount()) ) )
 && ( (this.getAmtbAcctSalespersonReq()==castOther.getAmtbAcctSalespersonReq()) || ( this.getAmtbAcctSalespersonReq()!=null && castOther.getAmtbAcctSalespersonReq()!=null && this.getAmtbAcctSalespersonReq().equals(castOther.getAmtbAcctSalespersonReq()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAcctSalespersonNo() == null ? 0 : this.getAcctSalespersonNo().hashCode() );
         result = 37 * result + ( getEffectiveDtFrom() == null ? 0 : this.getEffectiveDtFrom().hashCode() );
         result = 37 * result + ( getEffectiveDtTo() == null ? 0 : this.getEffectiveDtTo().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getMstbSalesperson() == null ? 0 : this.getMstbSalesperson().hashCode() );
         result = 37 * result + ( getAmtbAccount() == null ? 0 : this.getAmtbAccount().hashCode() );
         result = 37 * result + ( getAmtbAcctSalespersonReq() == null ? 0 : this.getAmtbAcctSalespersonReq().hashCode() );
         return result;
   }   





}
