package com.cdgtaxi.ibs.common.model;
// Generated Dec 16, 2009 12:01:50 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;


/**
 * BmtbInvoicePrintReq generated by hbm2java
 */

public class BmtbInvoicePrintReq  implements java.io.Serializable, Creatable {


    // Fields    

    private Long reqId;
    private Integer billGenReqNo;
    private Integer custNoFrom;
    private Integer custNoTo;
    private Long invoiceNoFrom;
    private Long invoiceNoTo;
    private String createdBy;
    private Timestamp createdDt;


    // Constructors

    /** default constructor */
    public BmtbInvoicePrintReq() {
    }

    
    /** full constructor */
    public BmtbInvoicePrintReq(Integer billGenReqNo, Integer custNoFrom, Integer custNoTo, Long invoiceNoFrom, Long invoiceNoTo, String createdBy, Timestamp createdDt) {
        this.billGenReqNo = billGenReqNo;
        this.custNoFrom = custNoFrom;
        this.custNoTo = custNoTo;
        this.invoiceNoFrom = invoiceNoFrom;
        this.invoiceNoTo = invoiceNoTo;
        this.createdBy = createdBy;
        this.createdDt = createdDt;
    }
    

   
    // Property accessors

    public Long getReqId() {
        return this.reqId;
    }
    
    public void setReqId(Long reqId) {
        this.reqId = reqId;
    }

    public Integer getBillGenReqNo() {
        return this.billGenReqNo;
    }
    
    public void setBillGenReqNo(Integer billGenReqNo) {
        this.billGenReqNo = billGenReqNo;
    }

    public Integer getCustNoFrom() {
        return this.custNoFrom;
    }
    
    public void setCustNoFrom(Integer custNoFrom) {
        this.custNoFrom = custNoFrom;
    }

    public Integer getCustNoTo() {
        return this.custNoTo;
    }
    
    public void setCustNoTo(Integer custNoTo) {
        this.custNoTo = custNoTo;
    }

    public Long getInvoiceNoFrom() {
        return this.invoiceNoFrom;
    }
    
    public void setInvoiceNoFrom(Long invoiceNoFrom) {
        this.invoiceNoFrom = invoiceNoFrom;
    }

    public Long getInvoiceNoTo() {
        return this.invoiceNoTo;
    }
    
    public void setInvoiceNoTo(Long invoiceNoTo) {
        this.invoiceNoTo = invoiceNoTo;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("billGenReqNo").append("='").append(getBillGenReqNo()).append("' ");			
      buffer.append("custNoFrom").append("='").append(getCustNoFrom()).append("' ");			
      buffer.append("custNoTo").append("='").append(getCustNoTo()).append("' ");			
      buffer.append("invoiceNoFrom").append("='").append(getInvoiceNoFrom()).append("' ");			
      buffer.append("invoiceNoTo").append("='").append(getInvoiceNoTo()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BmtbInvoicePrintReq) ) return false;
		 BmtbInvoicePrintReq castOther = ( BmtbInvoicePrintReq ) other; 
         
		 return ( (this.getReqId()==castOther.getReqId()) || ( this.getReqId()!=null && castOther.getReqId()!=null && this.getReqId().equals(castOther.getReqId()) ) )
 && ( (this.getBillGenReqNo()==castOther.getBillGenReqNo()) || ( this.getBillGenReqNo()!=null && castOther.getBillGenReqNo()!=null && this.getBillGenReqNo().equals(castOther.getBillGenReqNo()) ) )
 && ( (this.getCustNoFrom()==castOther.getCustNoFrom()) || ( this.getCustNoFrom()!=null && castOther.getCustNoFrom()!=null && this.getCustNoFrom().equals(castOther.getCustNoFrom()) ) )
 && ( (this.getCustNoTo()==castOther.getCustNoTo()) || ( this.getCustNoTo()!=null && castOther.getCustNoTo()!=null && this.getCustNoTo().equals(castOther.getCustNoTo()) ) )
 && ( (this.getInvoiceNoFrom()==castOther.getInvoiceNoFrom()) || ( this.getInvoiceNoFrom()!=null && castOther.getInvoiceNoFrom()!=null && this.getInvoiceNoFrom().equals(castOther.getInvoiceNoFrom()) ) )
 && ( (this.getInvoiceNoTo()==castOther.getInvoiceNoTo()) || ( this.getInvoiceNoTo()!=null && castOther.getInvoiceNoTo()!=null && this.getInvoiceNoTo().equals(castOther.getInvoiceNoTo()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getReqId() == null ? 0 : this.getReqId().hashCode() );
         result = 37 * result + ( getBillGenReqNo() == null ? 0 : this.getBillGenReqNo().hashCode() );
         result = 37 * result + ( getCustNoFrom() == null ? 0 : this.getCustNoFrom().hashCode() );
         result = 37 * result + ( getCustNoTo() == null ? 0 : this.getCustNoTo().hashCode() );
         result = 37 * result + ( getInvoiceNoFrom() == null ? 0 : this.getInvoiceNoFrom().hashCode() );
         result = 37 * result + ( getInvoiceNoTo() == null ? 0 : this.getInvoiceNoTo().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         return result;
   }   





}
