package com.cdgtaxi.ibs.common.model;
// Generated Jul 20, 2009 4:09:20 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Timestamp;

import com.cdgtaxi.ibs.acl.security.Auditable;


/**
 * BmtbPaymentReceiptDetail generated by hbm2java
 */

public class BmtbPaymentReceiptDetail  implements java.io.Serializable, Auditable, Creatable, Updatable {


    // Fields    

    private Long paymentReceiptDetailNo;
    private BigDecimal appliedAmount;
    private BigDecimal deductedCreditBalance;
    private String billedFlag;
    private String cancelBilledFlag;
    private String createdBy;
    private Timestamp createdDt;
    private String updatedBy;
    private Timestamp updatedDt;
    private Integer version;
    private BmtbInvoiceHeader bmtbInvoiceHeader;
    private BmtbInvoiceDetail bmtbInvoiceDetail;
    private BmtbPaymentReceipt bmtbPaymentReceipt;
    private BmtbInvoicePaymentHeader bmtbInvoicePaymentHeader;
    private PmtbPrepaidCardTxn pmtbPrepaidCardTxn;

    // Constructors

    /** default constructor */
    public BmtbPaymentReceiptDetail() {
    	deductedCreditBalance = new BigDecimal(0);
    }

	/** minimal constructor */
    public BmtbPaymentReceiptDetail(BigDecimal deductedCreditBalance, String billedFlag, String cancelBilledFlag) {
        this.deductedCreditBalance = deductedCreditBalance;
        this.billedFlag = billedFlag;
        this.cancelBilledFlag = cancelBilledFlag;
    }
    
    /** full constructor */
    public BmtbPaymentReceiptDetail(BigDecimal appliedAmount, BigDecimal deductedCreditBalance, String billedFlag, String cancelBilledFlag, String createdBy, Timestamp createdDt, String updatedBy, Timestamp updatedDt, Integer version, BmtbInvoiceHeader bmtbInvoiceHeader, BmtbInvoiceDetail bmtbInvoiceDetail, BmtbPaymentReceipt bmtbPaymentReceipt, BmtbInvoicePaymentHeader bmtbInvoicePaymentHeader) {
        this.appliedAmount = appliedAmount;
        this.deductedCreditBalance = deductedCreditBalance;
        this.billedFlag = billedFlag;
        this.cancelBilledFlag = cancelBilledFlag;
        this.createdBy = createdBy;
        this.createdDt = createdDt;
        this.updatedBy = updatedBy;
        this.updatedDt = updatedDt;
        this.version = version;
        this.bmtbInvoiceHeader = bmtbInvoiceHeader;
        this.bmtbInvoiceDetail = bmtbInvoiceDetail;
        this.bmtbPaymentReceipt = bmtbPaymentReceipt;
        this.bmtbInvoicePaymentHeader = bmtbInvoicePaymentHeader;
    }
    

   
    // Property accessors

    public Long getPaymentReceiptDetailNo() {
        return this.paymentReceiptDetailNo;
    }
    
    public void setPaymentReceiptDetailNo(Long paymentReceiptDetailNo) {
        this.paymentReceiptDetailNo = paymentReceiptDetailNo;
    }

    public BigDecimal getAppliedAmount() {
        return this.appliedAmount;
    }
    
    public void setAppliedAmount(BigDecimal appliedAmount) {
        this.appliedAmount = appliedAmount;
    }

    public BigDecimal getDeductedCreditBalance() {
        return this.deductedCreditBalance;
    }
    
    public void setDeductedCreditBalance(BigDecimal deductedCreditBalance) {
        this.deductedCreditBalance = deductedCreditBalance;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public BmtbInvoiceHeader getBmtbInvoiceHeader() {
        return this.bmtbInvoiceHeader;
    }
    
    public void setBmtbInvoiceHeader(BmtbInvoiceHeader bmtbInvoiceHeader) {
        this.bmtbInvoiceHeader = bmtbInvoiceHeader;
    }

    public BmtbInvoiceDetail getBmtbInvoiceDetail() {
        return this.bmtbInvoiceDetail;
    }
    
    public void setBmtbInvoiceDetail(BmtbInvoiceDetail bmtbInvoiceDetail) {
        this.bmtbInvoiceDetail = bmtbInvoiceDetail;
    }

    public BmtbPaymentReceipt getBmtbPaymentReceipt() {
        return this.bmtbPaymentReceipt;
    }
    
    public void setBmtbPaymentReceipt(BmtbPaymentReceipt bmtbPaymentReceipt) {
        this.bmtbPaymentReceipt = bmtbPaymentReceipt;
    }
   
    public String getBilledFlag() {
    	return billedFlag;
    }

    public void setBilledFlag(String billedFlag) {
    	this.billedFlag = billedFlag;
    }   
    
    public BmtbInvoicePaymentHeader getBmtbInvoicePaymentHeader() {
        return this.bmtbInvoicePaymentHeader;
    }
    
    public void setBmtbInvoicePaymentHeader(BmtbInvoicePaymentHeader bmtbInvoicePaymentHeader) {
        this.bmtbInvoicePaymentHeader = bmtbInvoicePaymentHeader;
    }
    
    public String getCancelBilledFlag() {
        return this.cancelBilledFlag;
    }
    
    public void setCancelBilledFlag(String cancelBilledFlag) {
        this.cancelBilledFlag = cancelBilledFlag;
    }



	public PmtbPrepaidCardTxn getPmtbPrepaidCardTxn() {
		return pmtbPrepaidCardTxn;
	}

	public void setPmtbPrepaidCardTxn(PmtbPrepaidCardTxn pmtbPrepaidCardTxn) {
		this.pmtbPrepaidCardTxn = pmtbPrepaidCardTxn;
	}

	/**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("appliedAmount").append("='").append(getAppliedAmount()).append("' ");			
      buffer.append("deductedCreditBalance").append("='").append(getDeductedCreditBalance()).append("' ");
      buffer.append("billedFlag").append("='").append(getBilledFlag()).append("' ");
      buffer.append("cancelBilledFlag").append("='").append(getCancelBilledFlag()).append("' ");
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BmtbPaymentReceiptDetail) ) return false;
		 BmtbPaymentReceiptDetail castOther = ( BmtbPaymentReceiptDetail ) other; 
         
		 return ( (this.getPaymentReceiptDetailNo()==castOther.getPaymentReceiptDetailNo()) || ( this.getPaymentReceiptDetailNo()!=null && castOther.getPaymentReceiptDetailNo()!=null && this.getPaymentReceiptDetailNo().equals(castOther.getPaymentReceiptDetailNo()) ) )
 && ( (this.getAppliedAmount()==castOther.getAppliedAmount()) || ( this.getAppliedAmount()!=null && castOther.getAppliedAmount()!=null && this.getAppliedAmount().equals(castOther.getAppliedAmount()) ) )
 && ( (this.getDeductedCreditBalance()==castOther.getDeductedCreditBalance()) || ( this.getDeductedCreditBalance()!=null && castOther.getDeductedCreditBalance()!=null && this.getDeductedCreditBalance().equals(castOther.getDeductedCreditBalance()) ) )
 && ( (this.getBilledFlag()==castOther.getBilledFlag()) || ( this.getBilledFlag()!=null && castOther.getBilledFlag()!=null && this.getBilledFlag().equals(castOther.getBilledFlag()) ) )
 && ( (this.getCancelBilledFlag()==castOther.getCancelBilledFlag()) || ( this.getCancelBilledFlag()!=null && castOther.getCancelBilledFlag()!=null && this.getCancelBilledFlag().equals(castOther.getCancelBilledFlag()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getBmtbInvoiceHeader()==castOther.getBmtbInvoiceHeader()) || ( this.getBmtbInvoiceHeader()!=null && castOther.getBmtbInvoiceHeader()!=null && this.getBmtbInvoiceHeader().equals(castOther.getBmtbInvoiceHeader()) ) )
 && ( (this.getBmtbInvoiceDetail()==castOther.getBmtbInvoiceDetail()) || ( this.getBmtbInvoiceDetail()!=null && castOther.getBmtbInvoiceDetail()!=null && this.getBmtbInvoiceDetail().equals(castOther.getBmtbInvoiceDetail()) ) )
 && ( (this.getBmtbPaymentReceipt()==castOther.getBmtbPaymentReceipt()) || ( this.getBmtbPaymentReceipt()!=null && castOther.getBmtbPaymentReceipt()!=null && this.getBmtbPaymentReceipt().equals(castOther.getBmtbPaymentReceipt()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPaymentReceiptDetailNo() == null ? 0 : this.getPaymentReceiptDetailNo().hashCode() );
         result = 37 * result + ( getAppliedAmount() == null ? 0 : this.getAppliedAmount().hashCode() );
         result = 37 * result + ( getDeductedCreditBalance() == null ? 0 : this.getDeductedCreditBalance().hashCode() );
         result = 37 * result + ( getBilledFlag() == null ? 0 : this.getBilledFlag().hashCode() );
         result = 37 * result + ( getCancelBilledFlag() == null ? 0 : this.getCancelBilledFlag().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getBmtbInvoiceHeader() == null ? 0 : this.getBmtbInvoiceHeader().hashCode() );
         result = 37 * result + ( getBmtbInvoiceDetail() == null ? 0 : this.getBmtbInvoiceDetail().hashCode() );
         result = 37 * result + ( getBmtbPaymentReceipt() == null ? 0 : this.getBmtbPaymentReceipt().hashCode() );
         return result;
   }

}
