package com.cdgtaxi.ibs.common.model;
// Generated Jul 20, 2009 4:09:25 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.master.model.MstbMasterTable;


/**
 * BmtbNote generated by hbm2java
 */

public class BmtbNote  implements java.io.Serializable, Auditable, Creatable, Updatable{


	// Fields

	private Long noteNo;
	private String noteType;
	private String noteTxnType;
	private BigDecimal noteAmount;
	private BigDecimal discount;
	private BigDecimal adminFee;
	private BigDecimal prodDis;
	private BigDecimal promoDis;
	private BigDecimal gst;
	private String remarks;
	private String status;
	private Timestamp cancelDt;
	private String createdBy;
	private Timestamp createdDt;
	private String updatedBy;
	private Timestamp updatedDt;
	private Integer version;
	private BmtbInvoiceHeader bmtbInvoiceHeader;
	private MstbMasterTable mstbMasterTableByCancellationReason;
	private MstbMasterTable mstbMasterTableByReason;
	private FmtbTransactionCode fmtbTransactionCode;
	private AmtbAccount amtbAccount;
	private Set<FmtbGlLogDetail> fmtbGlLogDetails = new HashSet<FmtbGlLogDetail>(0);
	private Set<BmtbInvoiceDepositTxn> bmtbInvoiceDepositTxns = new HashSet<BmtbInvoiceDepositTxn>(0);
	private BmtbInvoiceTxn bmtbInvoiceTxnByBilledInvoiceTxnNo;
	private BmtbInvoiceTxn bmtbInvoiceTxnByIssuedInvoiceTxnNo;
	private Set<TmtbAcquireTxn> tmtbAcquireTxns = new HashSet<TmtbAcquireTxn>(0);


	// Constructors

	/** default constructor */
	public BmtbNote() {
	}

	/** minimal constructor */
	public BmtbNote(String noteType, String noteTxnType, BigDecimal noteAmount, BigDecimal discount, BigDecimal adminFee, BigDecimal prodDis, BigDecimal promoDis, BigDecimal gst) {
		this.noteType = noteType;
		this.noteTxnType = noteTxnType;
		this.noteAmount = noteAmount;
		this.discount = discount;
		this.adminFee = adminFee;
		this.prodDis = prodDis;
		this.promoDis = promoDis;
		this.gst = gst;
	}

	/** full constructor */
	public BmtbNote(String noteType, String noteTxnType, BigDecimal noteAmount, BigDecimal discount, BigDecimal adminFee, BigDecimal prodDis, BigDecimal promoDis, BigDecimal gst, String remarks, String status, Timestamp cancelDt, String createdBy, Timestamp createdDt, String updatedBy, Timestamp updatedDt, Integer version, BmtbInvoiceHeader bmtbInvoiceHeader, MstbMasterTable mstbMasterTableByCancellationReason, MstbMasterTable mstbMasterTableByReason, FmtbTransactionCode fmtbTransactionCode, AmtbAccount amtbAccount, Set<FmtbGlLogDetail> fmtbGlLogDetails, Set<BmtbInvoiceDepositTxn> bmtbInvoiceDepositTxns, BmtbInvoiceTxn bmtbInvoiceTxnByBilledInvoiceTxnNo, BmtbInvoiceTxn bmtbInvoiceTxnByIssuedInvoiceTxnNo, Set<TmtbAcquireTxn> tmtbAcquireTxns) {
		this.noteType = noteType;
		this.noteTxnType = noteTxnType;
		this.noteAmount = noteAmount;
		this.discount = discount;
		this.adminFee = adminFee;
		this.prodDis = prodDis;
		this.promoDis = promoDis;
		this.gst = gst;
		this.remarks = remarks;
		this.status = status;
		this.cancelDt = cancelDt;
		this.createdBy = createdBy;
		this.createdDt = createdDt;
		this.updatedBy = updatedBy;
		this.updatedDt = updatedDt;
		this.version = version;
		this.bmtbInvoiceHeader = bmtbInvoiceHeader;
		this.mstbMasterTableByCancellationReason = mstbMasterTableByCancellationReason;
		this.mstbMasterTableByReason = mstbMasterTableByReason;
		this.fmtbTransactionCode = fmtbTransactionCode;
		this.amtbAccount = amtbAccount;
		this.fmtbGlLogDetails = fmtbGlLogDetails;
		this.bmtbInvoiceDepositTxns = bmtbInvoiceDepositTxns;
		this.bmtbInvoiceTxnByBilledInvoiceTxnNo = bmtbInvoiceTxnByBilledInvoiceTxnNo;
		this.bmtbInvoiceTxnByIssuedInvoiceTxnNo = bmtbInvoiceTxnByIssuedInvoiceTxnNo;
		this.tmtbAcquireTxns = tmtbAcquireTxns;
	}



	// Property accessors

	public Long getNoteNo() {
		return this.noteNo;
	}

	public void setNoteNo(Long noteNo) {
		this.noteNo = noteNo;
	}

	public String getNoteType() {
		return this.noteType;
	}

	public void setNoteType(String noteType) {
		this.noteType = noteType;
	}

	public String getNoteTxnType() {
		return this.noteTxnType;
	}

	public void setNoteTxnType(String noteTxnType) {
		this.noteTxnType = noteTxnType;
	}

	public BigDecimal getNoteAmount() {
		return this.noteAmount;
	}

	public void setNoteAmount(BigDecimal noteAmount) {
		this.noteAmount = noteAmount;
	}

	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	public BigDecimal getAdminFee() {
		return this.adminFee;
	}

	public void setAdminFee(BigDecimal adminFee) {
		this.adminFee = adminFee;
	}

	public BigDecimal getProdDis() {
		return this.prodDis;
	}

	public void setProdDis(BigDecimal prodDis) {
		this.prodDis = prodDis;
	}

	public BigDecimal getPromoDis() {
		return promoDis;
	}

	public void setPromoDis(BigDecimal promoDis) {
		this.promoDis = promoDis;
	}
	
	public BigDecimal getGst() {
		return this.gst;
	}

	public void setGst(BigDecimal gst) {
		this.gst = gst;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Timestamp getCancelDt() {
		return this.cancelDt;
	}

	public void setCancelDt(Timestamp cancelDt) {
		this.cancelDt = cancelDt;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Timestamp getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Timestamp createdDt) {
		this.createdDt = createdDt;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Timestamp getUpdatedDt() {
		return this.updatedDt;
	}

	public void setUpdatedDt(Timestamp updatedDt) {
		this.updatedDt = updatedDt;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public BmtbInvoiceHeader getBmtbInvoiceHeader() {
		return this.bmtbInvoiceHeader;
	}

	public void setBmtbInvoiceHeader(BmtbInvoiceHeader bmtbInvoiceHeader) {
		this.bmtbInvoiceHeader = bmtbInvoiceHeader;
	}

	public MstbMasterTable getMstbMasterTableByCancellationReason() {
		return this.mstbMasterTableByCancellationReason;
	}

	public void setMstbMasterTableByCancellationReason(MstbMasterTable mstbMasterTableByCancellationReason) {
		this.mstbMasterTableByCancellationReason = mstbMasterTableByCancellationReason;
	}

	public MstbMasterTable getMstbMasterTableByReason() {
		return this.mstbMasterTableByReason;
	}

	public void setMstbMasterTableByReason(MstbMasterTable mstbMasterTableByReason) {
		this.mstbMasterTableByReason = mstbMasterTableByReason;
	}

	public FmtbTransactionCode getFmtbTransactionCode() {
		return this.fmtbTransactionCode;
	}

	public void setFmtbTransactionCode(FmtbTransactionCode fmtbTransactionCode) {
		this.fmtbTransactionCode = fmtbTransactionCode;
	}

	public AmtbAccount getAmtbAccount() {
		return this.amtbAccount;
	}

	public void setAmtbAccount(AmtbAccount amtbAccount) {
		this.amtbAccount = amtbAccount;
	}

	public Set<FmtbGlLogDetail> getFmtbGlLogDetails() {
		return this.fmtbGlLogDetails;
	}

	public void setFmtbGlLogDetails(Set<FmtbGlLogDetail> fmtbGlLogDetails) {
		this.fmtbGlLogDetails = fmtbGlLogDetails;
	}

	public Set<BmtbInvoiceDepositTxn> getBmtbInvoiceDepositTxns() {
		return this.bmtbInvoiceDepositTxns;
	}

	public void setBmtbInvoiceDepositTxns(Set<BmtbInvoiceDepositTxn> bmtbInvoiceDepositTxns) {
		this.bmtbInvoiceDepositTxns = bmtbInvoiceDepositTxns;
	}

	public BmtbInvoiceTxn getBmtbInvoiceTxnByBilledInvoiceTxnNo() {
		return this.bmtbInvoiceTxnByBilledInvoiceTxnNo;
	}

	public void setBmtbInvoiceTxnByBilledInvoiceTxnNo(BmtbInvoiceTxn bmtbInvoiceTxnByBilledInvoiceTxnNo) {
		this.bmtbInvoiceTxnByBilledInvoiceTxnNo = bmtbInvoiceTxnByBilledInvoiceTxnNo;
	}

	public BmtbInvoiceTxn getBmtbInvoiceTxnByIssuedInvoiceTxnNo() {
		return this.bmtbInvoiceTxnByIssuedInvoiceTxnNo;
	}

	public void setBmtbInvoiceTxnByIssuedInvoiceTxnNo(BmtbInvoiceTxn bmtbInvoiceTxnByIssuedInvoiceTxnNo) {
		this.bmtbInvoiceTxnByIssuedInvoiceTxnNo = bmtbInvoiceTxnByIssuedInvoiceTxnNo;
	}

	public Set<TmtbAcquireTxn> getTmtbAcquireTxns() {
		return tmtbAcquireTxns;
	}

	public void setTmtbAcquireTxns(Set<TmtbAcquireTxn> tmtbAcquireTxns) {
		this.tmtbAcquireTxns = tmtbAcquireTxns;
	}
	
	/**
	 * toString
	 * @return String
	 */
	 @Override
	 public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("noteType").append("='").append(getNoteType()).append("' ");
		buffer.append("noteTxnType").append("='").append(getNoteTxnType()).append("' ");
		buffer.append("noteAmount").append("='").append(getNoteAmount()).append("' ");
		buffer.append("discount").append("='").append(getDiscount()).append("' ");
		buffer.append("adminFee").append("='").append(getAdminFee()).append("' ");
		buffer.append("prodDis").append("='").append(getProdDis()).append("' ");
		buffer.append("promoDis").append("='").append(getPromoDis()).append("' ");
		buffer.append("gst").append("='").append(getGst()).append("' ");
		buffer.append("remarks").append("='").append(getRemarks()).append("' ");
		buffer.append("status").append("='").append(getStatus()).append("' ");
		buffer.append("cancelDt").append("='").append(getCancelDt()).append("' ");
		buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
		buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");
		buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");
		buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");
		buffer.append("version").append("='").append(getVersion()).append("' ");
		buffer.append("]");

		return buffer.toString();
	 }


	 @Override
	 public boolean equals(Object other) {
		 if ( (this == other ) ) {
			 return true;
		 }
		 if ( (other == null ) ) {
			 return false;
		 }
		 if ( !(other instanceof BmtbNote) ) {
			 return false;
		 }
		 BmtbNote castOther = ( BmtbNote ) other;

		 return ( (this.getNoteNo()==castOther.getNoteNo()) || ( this.getNoteNo()!=null && castOther.getNoteNo()!=null && this.getNoteNo().equals(castOther.getNoteNo()) ) )
		 && ( (this.getNoteType()==castOther.getNoteType()) || ( this.getNoteType()!=null && castOther.getNoteType()!=null && this.getNoteType().equals(castOther.getNoteType()) ) )
		 && ( (this.getNoteTxnType()==castOther.getNoteTxnType()) || ( this.getNoteTxnType()!=null && castOther.getNoteTxnType()!=null && this.getNoteTxnType().equals(castOther.getNoteTxnType()) ) )
		 && ( (this.getNoteAmount()==castOther.getNoteAmount()) || ( this.getNoteAmount()!=null && castOther.getNoteAmount()!=null && this.getNoteAmount().equals(castOther.getNoteAmount()) ) )
		 && ( (this.getDiscount()==castOther.getDiscount()) || ( this.getDiscount()!=null && castOther.getDiscount()!=null && this.getDiscount().equals(castOther.getDiscount()) ) )
		 && ( (this.getAdminFee()==castOther.getAdminFee()) || ( this.getAdminFee()!=null && castOther.getAdminFee()!=null && this.getAdminFee().equals(castOther.getAdminFee()) ) )
		 && ( (this.getProdDis()==castOther.getProdDis()) || ( this.getProdDis()!=null && castOther.getProdDis()!=null && this.getProdDis().equals(castOther.getProdDis()) ) )
		 && ( (this.getPromoDis()==castOther.getPromoDis()) || ( this.getPromoDis()!=null && castOther.getPromoDis()!=null && this.getPromoDis().equals(castOther.getPromoDis()) ) )
		 && ( (this.getGst()==castOther.getGst()) || ( this.getGst()!=null && castOther.getGst()!=null && this.getGst().equals(castOther.getGst()) ) )
		 && ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) )
		 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
		 && ( (this.getCancelDt()==castOther.getCancelDt()) || ( this.getCancelDt()!=null && castOther.getCancelDt()!=null && this.getCancelDt().equals(castOther.getCancelDt()) ) )
		 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
		 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
		 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
		 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
		 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
		 && ( (this.getBmtbInvoiceHeader()==castOther.getBmtbInvoiceHeader()) || ( this.getBmtbInvoiceHeader()!=null && castOther.getBmtbInvoiceHeader()!=null && this.getBmtbInvoiceHeader().equals(castOther.getBmtbInvoiceHeader()) ) )
		 && ( (this.getMstbMasterTableByCancellationReason()==castOther.getMstbMasterTableByCancellationReason()) || ( this.getMstbMasterTableByCancellationReason()!=null && castOther.getMstbMasterTableByCancellationReason()!=null && this.getMstbMasterTableByCancellationReason().equals(castOther.getMstbMasterTableByCancellationReason()) ) )
		 && ( (this.getMstbMasterTableByReason()==castOther.getMstbMasterTableByReason()) || ( this.getMstbMasterTableByReason()!=null && castOther.getMstbMasterTableByReason()!=null && this.getMstbMasterTableByReason().equals(castOther.getMstbMasterTableByReason()) ) )
		 && ( (this.getFmtbTransactionCode()==castOther.getFmtbTransactionCode()) || ( this.getFmtbTransactionCode()!=null && castOther.getFmtbTransactionCode()!=null && this.getFmtbTransactionCode().equals(castOther.getFmtbTransactionCode()) ) )
		 && ( (this.getAmtbAccount()==castOther.getAmtbAccount()) || ( this.getAmtbAccount()!=null && castOther.getAmtbAccount()!=null && this.getAmtbAccount().equals(castOther.getAmtbAccount()) ) )
		 && ( (this.getBmtbInvoiceTxnByBilledInvoiceTxnNo()==castOther.getBmtbInvoiceTxnByBilledInvoiceTxnNo()) || ( this.getBmtbInvoiceTxnByBilledInvoiceTxnNo()!=null && castOther.getBmtbInvoiceTxnByBilledInvoiceTxnNo()!=null && this.getBmtbInvoiceTxnByBilledInvoiceTxnNo().equals(castOther.getBmtbInvoiceTxnByBilledInvoiceTxnNo()) ) )
		 && ( (this.getBmtbInvoiceTxnByIssuedInvoiceTxnNo()==castOther.getBmtbInvoiceTxnByIssuedInvoiceTxnNo()) || ( this.getBmtbInvoiceTxnByIssuedInvoiceTxnNo()!=null && castOther.getBmtbInvoiceTxnByIssuedInvoiceTxnNo()!=null && this.getBmtbInvoiceTxnByIssuedInvoiceTxnNo().equals(castOther.getBmtbInvoiceTxnByIssuedInvoiceTxnNo()) ) );
	 }

	 @Override
	 public int hashCode() {
		 int result = 17;

		 result = 37 * result + ( getNoteNo() == null ? 0 : this.getNoteNo().hashCode() );
		 result = 37 * result + ( getNoteType() == null ? 0 : this.getNoteType().hashCode() );
		 result = 37 * result + ( getNoteTxnType() == null ? 0 : this.getNoteTxnType().hashCode() );
		 result = 37 * result + ( getNoteAmount() == null ? 0 : this.getNoteAmount().hashCode() );
		 result = 37 * result + ( getDiscount() == null ? 0 : this.getDiscount().hashCode() );
		 result = 37 * result + ( getAdminFee() == null ? 0 : this.getAdminFee().hashCode() );
		 result = 37 * result + ( getProdDis() == null ? 0 : this.getProdDis().hashCode() );
		 result = 37 * result + ( getPromoDis() == null ? 0 : this.getPromoDis().hashCode() );
		 result = 37 * result + ( getGst() == null ? 0 : this.getGst().hashCode() );
		 result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
		 result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
		 result = 37 * result + ( getCancelDt() == null ? 0 : this.getCancelDt().hashCode() );
		 result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
		 result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
		 result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
		 result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
		 result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
		 result = 37 * result + ( getBmtbInvoiceHeader() == null ? 0 : this.getBmtbInvoiceHeader().hashCode() );
		 result = 37 * result + ( getMstbMasterTableByCancellationReason() == null ? 0 : this.getMstbMasterTableByCancellationReason().hashCode() );
		 result = 37 * result + ( getMstbMasterTableByReason() == null ? 0 : this.getMstbMasterTableByReason().hashCode() );
//		 result = 37 * result + ( getFmtbTransactionCode() == null ? 0 : this.getFmtbTransactionCode().hashCode() );
		 result = 37 * result + ( getAmtbAccount() == null ? 0 : this.getAmtbAccount().hashCode() );


		 result = 37 * result + ( getBmtbInvoiceTxnByBilledInvoiceTxnNo() == null ? 0 : this.getBmtbInvoiceTxnByBilledInvoiceTxnNo().hashCode() );
		 result = 37 * result + ( getBmtbInvoiceTxnByIssuedInvoiceTxnNo() == null ? 0 : this.getBmtbInvoiceTxnByIssuedInvoiceTxnNo().hashCode() );
		 return result;
	 }

}
