package com.cdgtaxi.ibs.common.model;
// Generated Apr 30, 2010 3:43:17 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.master.model.MstbAcquirer;


/**
 * FmtbBankPaymentMaster generated by hbm2java
 */

public class FmtbBankPaymentMaster  implements java.io.Serializable, Auditable, Creatable, Updatable {


    // Fields    

    private Integer masterNo;
    private String pymtType;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private Integer version;
    private Set<FmtbBankPaymentDetail> fmtbBankPaymentDetails = new HashSet<FmtbBankPaymentDetail>(0);
    private MstbAcquirer mstbAcquirer;


    // Constructors

    /** default constructor */
    public FmtbBankPaymentMaster() {
    }

    
    /** full constructor */
    public FmtbBankPaymentMaster(String pymtType, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, Integer version, Set<FmtbBankPaymentDetail> fmtbBankPaymentDetails, MstbAcquirer mstbAcquirer) {
        this.pymtType = pymtType;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.version = version;
        this.fmtbBankPaymentDetails = fmtbBankPaymentDetails;
        this.mstbAcquirer = mstbAcquirer;
    }
    
    // Property accessors

    public Integer getMasterNo() {
        return this.masterNo;
    }
    
    public void setMasterNo(Integer masterNo) {
        this.masterNo = masterNo;
    }

    public String getPymtType() {
        return this.pymtType;
    }
    
    public void setPymtType(String pymtType) {
        this.pymtType = pymtType;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public Set<FmtbBankPaymentDetail> getFmtbBankPaymentDetails() {
        return this.fmtbBankPaymentDetails;
    }
    
    public void setFmtbBankPaymentDetails(Set<FmtbBankPaymentDetail> fmtbBankPaymentDetails) {
        this.fmtbBankPaymentDetails = fmtbBankPaymentDetails;
    }
   
    public MstbAcquirer getMstbAcquirer() {
    	return mstbAcquirer;
    }

    public void setMstbAcquirer(MstbAcquirer mstbAcquirer) {
    	this.mstbAcquirer = mstbAcquirer;
    }   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("pymtType").append("='").append(getPymtType()).append("' ");			
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FmtbBankPaymentMaster) ) return false;
		 FmtbBankPaymentMaster castOther = ( FmtbBankPaymentMaster ) other; 
         
		 return ( (this.getMasterNo()==castOther.getMasterNo()) || ( this.getMasterNo()!=null && castOther.getMasterNo()!=null && this.getMasterNo().equals(castOther.getMasterNo()) ) )
 && ( (this.getPymtType()==castOther.getPymtType()) || ( this.getPymtType()!=null && castOther.getPymtType()!=null && this.getPymtType().equals(castOther.getPymtType()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMasterNo() == null ? 0 : this.getMasterNo().hashCode() );
         result = 37 * result + ( getPymtType() == null ? 0 : this.getPymtType().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         
         return result;
   }

}
