package com.cdgtaxi.ibs.common.model;
// Generated Jul 20, 2009 4:09:31 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * FmtbGlLogHeader generated by hbm2java
 */

public class FmtbGlLogHeader  implements java.io.Serializable {


    // Fields    

    private Integer glLogNo;
    private Date glDate;
    private Date createdDate;
    private Date fileDate;
    private Integer version;
    private FmtbEntityMaster fmtbEntityMaster;
    private Set<FmtbGlLogDetail> fmtbGlLogDetails = new HashSet<FmtbGlLogDetail>(0);


    // Constructors

    /** default constructor */
    public FmtbGlLogHeader() {
    }

    
    /** full constructor */
    public FmtbGlLogHeader(Date glDate, Date createdDate, Date fileDate, Integer version, FmtbEntityMaster fmtbEntityMaster, Set<FmtbGlLogDetail> fmtbGlLogDetails) {
        this.glDate = glDate;
        this.createdDate = createdDate;
        this.fileDate = fileDate;
        this.version = version;
        this.fmtbEntityMaster = fmtbEntityMaster;
        this.fmtbGlLogDetails = fmtbGlLogDetails;
    }
    

   
    // Property accessors

    public Integer getGlLogNo() {
        return this.glLogNo;
    }
    
    public void setGlLogNo(Integer glLogNo) {
        this.glLogNo = glLogNo;
    }

    public Date getGlDate() {
        return this.glDate;
    }
    
    public void setGlDate(Date glDate) {
        this.glDate = glDate;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public FmtbEntityMaster getFmtbEntityMaster() {
        return this.fmtbEntityMaster;
    }
    
    public void setFmtbEntityMaster(FmtbEntityMaster fmtbEntityMaster) {
        this.fmtbEntityMaster = fmtbEntityMaster;
    }

    public Set<FmtbGlLogDetail> getFmtbGlLogDetails() {
        return this.fmtbGlLogDetails;
    }
    
    public void setFmtbGlLogDetails(Set<FmtbGlLogDetail> fmtbGlLogDetails) {
        this.fmtbGlLogDetails = fmtbGlLogDetails;
    }
   
    public Date getFileDate() {
    	return fileDate;
    }

    public void setFileDate(Date fileDate) {
    	this.fileDate = fileDate;
    }   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("glDate").append("='").append(getGlDate()).append("' ");			
      buffer.append("createdDate").append("='").append(getCreatedDate()).append("' ");
      buffer.append("fileDate").append("='").append(getFileDate()).append("' ");
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FmtbGlLogHeader) ) return false;
		 FmtbGlLogHeader castOther = ( FmtbGlLogHeader ) other; 
         
		 return ( (this.getGlLogNo()==castOther.getGlLogNo()) || ( this.getGlLogNo()!=null && castOther.getGlLogNo()!=null && this.getGlLogNo().equals(castOther.getGlLogNo()) ) )
 && ( (this.getGlDate()==castOther.getGlDate()) || ( this.getGlDate()!=null && castOther.getGlDate()!=null && this.getGlDate().equals(castOther.getGlDate()) ) )
 && ( (this.getCreatedDate()==castOther.getCreatedDate()) || ( this.getCreatedDate()!=null && castOther.getCreatedDate()!=null && this.getCreatedDate().equals(castOther.getCreatedDate()) ) )
 && ( (this.getFileDate()==castOther.getFileDate()) || ( this.getFileDate()!=null && castOther.getFileDate()!=null && this.getFileDate().equals(castOther.getFileDate()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getFmtbEntityMaster()==castOther.getFmtbEntityMaster()) || ( this.getFmtbEntityMaster()!=null && castOther.getFmtbEntityMaster()!=null && this.getFmtbEntityMaster().equals(castOther.getFmtbEntityMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGlLogNo() == null ? 0 : this.getGlLogNo().hashCode() );
         result = 37 * result + ( getGlDate() == null ? 0 : this.getGlDate().hashCode() );
         result = 37 * result + ( getCreatedDate() == null ? 0 : this.getCreatedDate().hashCode() );
         result = 37 * result + ( getFileDate() == null ? 0 : this.getFileDate().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getFmtbEntityMaster() == null ? 0 : this.getFmtbEntityMaster().hashCode() );
         
         return result;
   }

}
