package com.cdgtaxi.ibs.common.model;
// Generated Aug 29, 2009 7:17:38 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;


/**
 * ImtbIssueReq generated by hbm2java
 */

public class ImtbIssueReq  implements java.io.Serializable {


	// Fields

	private Integer issueReqNo;
	private Long quantity;
	private Timestamp requestDt;
	private Integer version;
	private String createBy;
	private ImtbItemType imtbItemType;
	private ImtbIssueReqFlow imtbIssueReqFlow;
	private AmtbAccount amtbAccount;
	private ImtbIssue imtbIssue;
	private Set<ImtbIssueReqFlow> imtbIssueReqFlows = new HashSet<ImtbIssueReqFlow>(0);
	private AmtbContactPerson amtbContactPerson;
	private Date expiryDate;
	private BigDecimal handlingFee;
	private BigDecimal discount;
	private BigDecimal deliveryCharges;
	private BigDecimal serialNoStart;
	private BigDecimal serialNoEnd;
	private String requestorRemarks;

	// Constructors

	/** default constructor */
	public ImtbIssueReq() {
	}

	/** minimal constructor */
	public ImtbIssueReq(Long quantity, Timestamp requestDt, AmtbContactPerson amtbContactPerson, Date expiryDate,
			BigDecimal handlingFee, BigDecimal discount, BigDecimal deliveryCharges, BigDecimal serialNoStart, BigDecimal serialNoEnd) {
		this.quantity = quantity;
		this.requestDt = requestDt;
		this.amtbContactPerson = amtbContactPerson;
		this.expiryDate = expiryDate;
		this.handlingFee = handlingFee;
		this.discount = discount;
		this.deliveryCharges = deliveryCharges;
		this.serialNoStart = serialNoStart;
		this.serialNoEnd = serialNoEnd;
	}

	/** full constructor */
	public ImtbIssueReq(Long quantity, Timestamp requestDt, Integer version, String createBy, ImtbItemType imtbItemType, 
			ImtbIssueReqFlow imtbIssueReqFlow, AmtbAccount amtbAccount, ImtbIssue imtbIssue, Set<ImtbIssueReqFlow> imtbIssueReqFlows, 
			AmtbContactPerson amtbContactPerson, Date expiryDate, BigDecimal handlingFee, BigDecimal discount, 
			BigDecimal deliveryCharges, BigDecimal serialNoStart, BigDecimal serialNoEnd, String requestoRemarks) {
		this.quantity = quantity;
		this.requestDt = requestDt;
		this.version = version;
		this.createBy = createBy;
		this.imtbItemType = imtbItemType;
		this.imtbIssueReqFlow = imtbIssueReqFlow;
		this.amtbAccount = amtbAccount;
		this.imtbIssue = imtbIssue;
		this.imtbIssueReqFlows = imtbIssueReqFlows;
		this.amtbContactPerson = amtbContactPerson;
		this.expiryDate = expiryDate;
		this.handlingFee = handlingFee;
		this.discount = discount;
		this.deliveryCharges = deliveryCharges;
		this.serialNoStart = serialNoStart;
		this.serialNoEnd = serialNoEnd;
		this.requestorRemarks = requestorRemarks;
	}



	// Property accessors

	public Date getExpiryDate() {
		return expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	public BigDecimal getHandlingFee() {
		return handlingFee;
	}

	public void setHandlingFee(BigDecimal handlingFee) {
		this.handlingFee = handlingFee;
	}

	public BigDecimal getDiscount() {
		return discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	public BigDecimal getDeliveryCharges() {
		return deliveryCharges;
	}

	public void setDeliveryCharges(BigDecimal deliveryCharges) {
		this.deliveryCharges = deliveryCharges;
	}

	public BigDecimal getSerialNoStart() {
		return serialNoStart;
	}

	public void setSerialNoStart(BigDecimal serialNoStart) {
		this.serialNoStart = serialNoStart;
	}

	public BigDecimal getSerialNoEnd() {
		return serialNoEnd;
	}

	public void setSerialNoEnd(BigDecimal serialNoEnd) {
		this.serialNoEnd = serialNoEnd;
	}
	
	public AmtbContactPerson getAmtbContactPerson() {
		return amtbContactPerson;
	}

	public void setAmtbContactPerson(AmtbContactPerson amtbContactPerson) {
		this.amtbContactPerson = amtbContactPerson;
	}

	public Integer getIssueReqNo() {
		return this.issueReqNo;
	}

	public void setIssueReqNo(Integer issueReqNo) {
		this.issueReqNo = issueReqNo;
	}

	public Long getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Long quantity) {
		this.quantity = quantity;
	}

	public Timestamp getRequestDt() {
		return this.requestDt;
	}

	public void setRequestDt(Timestamp requestDt) {
		this.requestDt = requestDt;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public ImtbItemType getImtbItemType() {
		return this.imtbItemType;
	}

	public void setImtbItemType(ImtbItemType imtbItemType) {
		this.imtbItemType = imtbItemType;
	}

	public ImtbIssueReqFlow getImtbIssueReqFlow() {
		return this.imtbIssueReqFlow;
	}

	public void setImtbIssueReqFlow(ImtbIssueReqFlow imtbIssueReqFlow) {
		this.imtbIssueReqFlow = imtbIssueReqFlow;
	}

	public AmtbAccount getAmtbAccount() {
		return this.amtbAccount;
	}

	public void setAmtbAccount(AmtbAccount amtbAccount) {
		this.amtbAccount = amtbAccount;
	}

	public ImtbIssue getImtbIssue() {
		return this.imtbIssue;
	}

	public void setImtbIssue(ImtbIssue imtbIssue) {
		this.imtbIssue = imtbIssue;
	}

	public Set<ImtbIssueReqFlow> getImtbIssueReqFlows() {
		return this.imtbIssueReqFlows;
	}

	public void setImtbIssueReqFlows(Set<ImtbIssueReqFlow> imtbIssueReqFlows) {
		this.imtbIssueReqFlows = imtbIssueReqFlows;
	}


	public String getRequestorRemarks() {
		return requestorRemarks;
	}

	public void setRequestorRemarks(String requestorRemarks) {
		this.requestorRemarks = requestorRemarks;
	}

	/**
	 * toString
	 * @return String
	 */
	 @Override
	 public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("quantity").append("='").append(getQuantity()).append("' ");
		buffer.append("requestDt").append("='").append(getRequestDt()).append("' ");
		buffer.append("version").append("='").append(getVersion()).append("' ");
		buffer.append("createBy").append("='").append(getCreateBy()).append("' ");
		buffer.append("expiryDate").append("='").append(getExpiryDate()).append("' ");
		buffer.append("processingFee").append("='").append(getHandlingFee()).append("' ");
		buffer.append("discount").append("='").append(getDiscount()).append("' ");
		buffer.append("deliveryCharges").append("='").append(getDeliveryCharges()).append("' ");
		buffer.append("serialNoStart").append("='").append(getSerialNoStart()).append("' ");
		buffer.append("serialNoEnd").append("='").append(getSerialNoEnd()).append("' ");
		buffer.append("requestorRemarks").append("='").append(getRequestorRemarks()).append("' ");
		buffer.append("]");

		return buffer.toString();
	 }


	 @Override
	 public boolean equals(Object other) {
		 if ( (this == other ) ) {
			 return true;
		 }
		 if ( (other == null ) ) {
			 return false;
		 }
		 if ( !(other instanceof ImtbIssueReq) ) {
			 return false;
		 }
		 ImtbIssueReq castOther = ( ImtbIssueReq ) other;

		 return ( (this.getIssueReqNo()==castOther.getIssueReqNo()) || ( this.getIssueReqNo()!=null && castOther.getIssueReqNo()!=null && this.getIssueReqNo().equals(castOther.getIssueReqNo()) ) )
		 && (this.getQuantity()==castOther.getQuantity())
		 && ( (this.getRequestDt()==castOther.getRequestDt()) || ( this.getRequestDt()!=null && castOther.getRequestDt()!=null && this.getRequestDt().equals(castOther.getRequestDt()) ) )
		 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
		 && ( (this.getCreateBy()==castOther.getCreateBy()) || ( this.getCreateBy()!=null && castOther.getCreateBy()!=null && this.getCreateBy().equals(castOther.getCreateBy()) ) )
		 && ( (this.getImtbItemType()==castOther.getImtbItemType()) || ( this.getImtbItemType()!=null && castOther.getImtbItemType()!=null && this.getImtbItemType().equals(castOther.getImtbItemType()) ) )
		 && ( (this.getImtbIssueReqFlow()==castOther.getImtbIssueReqFlow()) || ( this.getImtbIssueReqFlow()!=null && castOther.getImtbIssueReqFlow()!=null && this.getImtbIssueReqFlow().equals(castOther.getImtbIssueReqFlow()) ) )
		 && ( (this.getAmtbAccount()==castOther.getAmtbAccount()) || ( this.getAmtbAccount()!=null && castOther.getAmtbAccount()!=null && this.getAmtbAccount().equals(castOther.getAmtbAccount()) ) )
		 && ( (this.getAmtbContactPerson()==castOther.getAmtbContactPerson()) || ( this.getAmtbContactPerson()!=null && castOther.getAmtbContactPerson()!=null && this.getAmtbContactPerson().equals(castOther.getAmtbContactPerson()) ) )
		 && ( (this.getExpiryDate()==castOther.getExpiryDate()) || ( this.getExpiryDate()!=null && castOther.getExpiryDate()!=null && this.getExpiryDate().equals(castOther.getExpiryDate()) ) )
		 && ( (this.getHandlingFee()==castOther.getHandlingFee()) || ( this.getHandlingFee()!=null && castOther.getHandlingFee()!=null && this.getHandlingFee().equals(castOther.getHandlingFee()) ) )
		 && ( (this.getDiscount()==castOther.getDiscount()) || ( this.getDiscount()!=null && castOther.getDiscount()!=null && this.getDiscount().equals(castOther.getDiscount()) ) )
		 && ( (this.getDeliveryCharges()==castOther.getDeliveryCharges()) || ( this.getDeliveryCharges()!=null && castOther.getDeliveryCharges()!=null && this.getDeliveryCharges().equals(castOther.getDeliveryCharges()) ) )
		 && ( (this.getSerialNoStart()==castOther.getSerialNoStart()) || ( this.getSerialNoStart()!=null && castOther.getSerialNoStart()!=null && this.getSerialNoStart().equals(castOther.getSerialNoStart()) ) )
		 && ( (this.getSerialNoEnd()==castOther.getSerialNoEnd()) || ( this.getSerialNoEnd()!=null && castOther.getSerialNoEnd()!=null && this.getSerialNoEnd().equals(castOther.getSerialNoEnd()) ) )
		 && ( (this.getRequestorRemarks()==castOther.getRequestorRemarks()) || ( this.getRequestorRemarks()!=null && castOther.getRequestorRemarks()!=null && this.getRequestorRemarks().equals(castOther.getRequestorRemarks()) ) );
	 }

	 @Override
	 public int hashCode() {
		 int result = 17;

		 result = 37 * result + ( getIssueReqNo() == null ? 0 : this.getIssueReqNo().hashCode() );
		 result = 37 * result + ( getQuantity() == null ? 0 : this.getQuantity().hashCode() );
		 result = 37 * result + ( getRequestDt() == null ? 0 : this.getRequestDt().hashCode() );
		 result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
		 result = 37 * result + ( getCreateBy() == null ? 0 : this.getCreateBy().hashCode() );
		 result = 37 * result + ( getExpiryDate() == null ? 0 : this.getExpiryDate().hashCode() );
		 result = 37 * result + ( getHandlingFee() == null ? 0 : this.getHandlingFee().hashCode() );
		 result = 37 * result + ( getDiscount() == null ? 0 : this.getDiscount().hashCode() );
		 result = 37 * result + ( getDeliveryCharges() == null ? 0 : this.getDeliveryCharges().hashCode() );
		 result = 37 * result + ( getSerialNoStart() == null ? 0 : this.getSerialNoStart().hashCode() );
		 result = 37 * result + ( getSerialNoEnd() == null ? 0 : this.getSerialNoEnd().hashCode() );
		 
		 result = 37 * result + ( getImtbItemType() == null ? 0 : this.getImtbItemType().hashCode() );
		 //result = 37 * result + ( getImtbIssueReqFlow() == null ? 0 : this.getImtbIssueReqFlow().hashCode() );
		 result = 37 * result + ( getAmtbAccount() == null ? 0 : this.getAmtbAccount().hashCode() );
		 result = 37 * result + ( getRequestorRemarks() == null ? 0 : this.getRequestorRemarks().hashCode() );
		 
		 return result;
	 }





}
