package com.cdgtaxi.ibs.common.model;
// Generated Aug 27, 2009 1:20:18 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;


/**
 * ImtbItemType generated by hbm2java
 */

public class ImtbItemType  implements java.io.Serializable {


    // Fields    

    private Integer itemTypeNo;
    private String typeName;
    private BigDecimal price;
    private Integer version;
    private Set<ImtbIssueReq> imtbIssueReqs = new HashSet<ImtbIssueReq>(0);
    private Set<ImtbStock> imtbStocks = new HashSet<ImtbStock>(0);
    private Set<ImtbItem> imtbItems = new HashSet<ImtbItem>(0);


    // Constructors

    /** default constructor */
    public ImtbItemType() {
    }

	/** minimal constructor */
    public ImtbItemType(String typeName, BigDecimal price) {
        this.typeName = typeName;
        this.price = price;
    }
    
    /** full constructor */
    public ImtbItemType(String typeName, BigDecimal price, Integer version, Set<ImtbIssueReq> imtbIssueReqs, Set<ImtbStock> imtbStocks, Set<ImtbItem> imtbItems) {
        this.typeName = typeName;
        this.price = price;
        this.version = version;
        this.imtbIssueReqs = imtbIssueReqs;
        this.imtbStocks = imtbStocks;
        this.imtbItems = imtbItems;
    }
    

   
    // Property accessors

    public Integer getItemTypeNo() {
        return this.itemTypeNo;
    }
    
    public void setItemTypeNo(Integer itemTypeNo) {
        this.itemTypeNo = itemTypeNo;
    }

    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public Set<ImtbIssueReq> getImtbIssueReqs() {
        return this.imtbIssueReqs;
    }
    
    public void setImtbIssueReqs(Set<ImtbIssueReq> imtbIssueReqs) {
        this.imtbIssueReqs = imtbIssueReqs;
    }

    public Set<ImtbStock> getImtbStocks() {
        return this.imtbStocks;
    }
    
    public void setImtbStocks(Set<ImtbStock> imtbStocks) {
        this.imtbStocks = imtbStocks;
    }

    public Set<ImtbItem> getImtbItems() {
        return this.imtbItems;
    }
    
    public void setImtbItems(Set<ImtbItem> imtbItems) {
        this.imtbItems = imtbItems;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("typeName").append("='").append(getTypeName()).append("' ");			
      buffer.append("price").append("='").append(getPrice()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ImtbItemType) ) return false;
		 ImtbItemType castOther = ( ImtbItemType ) other; 
         
		 return ( (this.getItemTypeNo()==castOther.getItemTypeNo()) || ( this.getItemTypeNo()!=null && castOther.getItemTypeNo()!=null && this.getItemTypeNo().equals(castOther.getItemTypeNo()) ) )
 && ( (this.getTypeName()==castOther.getTypeName()) || ( this.getTypeName()!=null && castOther.getTypeName()!=null && this.getTypeName().equals(castOther.getTypeName()) ) )
 && ( (this.getPrice()==castOther.getPrice()) || ( this.getPrice()!=null && castOther.getPrice()!=null && this.getPrice().equals(castOther.getPrice()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getItemTypeNo() == null ? 0 : this.getItemTypeNo().hashCode() );
         result = 37 * result + ( getTypeName() == null ? 0 : this.getTypeName().hashCode() );
         result = 37 * result + ( getPrice() == null ? 0 : this.getPrice().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         
         
         
         return result;
   }   





}
