package com.cdgtaxi.ibs.common.model;
// Generated Aug 29, 2009 5:40:05 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.acl.model.SatbUser;


/**
 * ImtbIssueReqFlow generated by hbm2java
 */

public class ImtbIssueReqFlow  implements java.io.Serializable {


	// Fields

	private Integer issueReqFlowNo;
	private String fromStatus;
	private String toStatus;
	private String remarks;
	private Timestamp flowDt;
	private Integer version;
	private Set<ImtbIssueReq> imtbIssueReqs = new HashSet<ImtbIssueReq>(0);
	private Set<ImtbIssueReqFlow> imtbIssueReqFlows = new HashSet<ImtbIssueReqFlow>(0);
	private ImtbIssueReqFlow imtbIssueReqFlow;
	private SatbUser satbUser;
	private ImtbIssueReq imtbIssueReq;


	// Constructors

	/** default constructor */
	public ImtbIssueReqFlow() {
	}

	/** minimal constructor */
	public ImtbIssueReqFlow(String fromStatus, String toStatus, Timestamp flowDt) {
		this.fromStatus = fromStatus;
		this.toStatus = toStatus;
		this.flowDt = flowDt;
	}

	/** full constructor */
	public ImtbIssueReqFlow(String fromStatus, String toStatus, String remarks, Timestamp flowDt, Integer version, Set<ImtbIssueReq> imtbIssueReqs, Set<ImtbIssueReqFlow> imtbIssueReqFlows, ImtbIssueReqFlow imtbIssueReqFlow, SatbUser satbUser, ImtbIssueReq imtbIssueReq) {
		this.fromStatus = fromStatus;
		this.toStatus = toStatus;
		this.remarks = remarks;
		this.flowDt = flowDt;
		this.version = version;
		this.imtbIssueReqs = imtbIssueReqs;
		this.imtbIssueReqFlows = imtbIssueReqFlows;
		this.imtbIssueReqFlow = imtbIssueReqFlow;
		this.satbUser = satbUser;
		this.imtbIssueReq = imtbIssueReq;
	}



	// Property accessors

	public Integer getIssueReqFlowNo() {
		return this.issueReqFlowNo;
	}

	public void setIssueReqFlowNo(Integer issueReqFlowNo) {
		this.issueReqFlowNo = issueReqFlowNo;
	}

	public String getFromStatus() {
		return this.fromStatus;
	}

	public void setFromStatus(String fromStatus) {
		this.fromStatus = fromStatus;
	}

	public String getToStatus() {
		return this.toStatus;
	}

	public void setToStatus(String toStatus) {
		this.toStatus = toStatus;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Timestamp getFlowDt() {
		return this.flowDt;
	}

	public void setFlowDt(Timestamp flowDt) {
		this.flowDt = flowDt;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Set<ImtbIssueReq> getImtbIssueReqs() {
		return this.imtbIssueReqs;
	}

	public void setImtbIssueReqs(Set<ImtbIssueReq> imtbIssueReqs) {
		this.imtbIssueReqs = imtbIssueReqs;
	}

	public Set<ImtbIssueReqFlow> getImtbIssueReqFlows() {
		return this.imtbIssueReqFlows;
	}

	public void setImtbIssueReqFlows(Set<ImtbIssueReqFlow> imtbIssueReqFlows) {
		this.imtbIssueReqFlows = imtbIssueReqFlows;
	}

	public ImtbIssueReqFlow getImtbIssueReqFlow() {
		return this.imtbIssueReqFlow;
	}

	public void setImtbIssueReqFlow(ImtbIssueReqFlow imtbIssueReqFlow) {
		this.imtbIssueReqFlow = imtbIssueReqFlow;
	}

	public SatbUser getSatbUser() {
		return this.satbUser;
	}

	public void setSatbUser(SatbUser satbUser) {
		this.satbUser = satbUser;
	}

	public ImtbIssueReq getImtbIssueReq() {
		return this.imtbIssueReq;
	}

	public void setImtbIssueReq(ImtbIssueReq imtbIssueReq) {
		this.imtbIssueReq = imtbIssueReq;
	}


	/**
	 * toString
	 * @return String
	 */
	 @Override
	 public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("fromStatus").append("='").append(getFromStatus()).append("' ");
		buffer.append("toStatus").append("='").append(getToStatus()).append("' ");
		buffer.append("remarks").append("='").append(getRemarks()).append("' ");
		buffer.append("flowDt").append("='").append(getFlowDt()).append("' ");
		buffer.append("version").append("='").append(getVersion()).append("' ");
		buffer.append("]");

		return buffer.toString();
	 }


	 @Override
	 public boolean equals(Object other) {
		 if ( (this == other ) ) {
			 return true;
		 }
		 if ( (other == null ) ) {
			 return false;
		 }
		 if ( !(other instanceof ImtbIssueReqFlow) ) {
			 return false;
		 }
		 ImtbIssueReqFlow castOther = ( ImtbIssueReqFlow ) other;

		 return ( (this.getIssueReqFlowNo()==castOther.getIssueReqFlowNo()) || ( this.getIssueReqFlowNo()!=null && castOther.getIssueReqFlowNo()!=null && this.getIssueReqFlowNo().equals(castOther.getIssueReqFlowNo()) ) )
		 && ( (this.getFromStatus()==castOther.getFromStatus()) || ( this.getFromStatus()!=null && castOther.getFromStatus()!=null && this.getFromStatus().equals(castOther.getFromStatus()) ) )
		 && ( (this.getToStatus()==castOther.getToStatus()) || ( this.getToStatus()!=null && castOther.getToStatus()!=null && this.getToStatus().equals(castOther.getToStatus()) ) )
		 && ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) )
		 && ( (this.getFlowDt()==castOther.getFlowDt()) || ( this.getFlowDt()!=null && castOther.getFlowDt()!=null && this.getFlowDt().equals(castOther.getFlowDt()) ) )
		 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
		 && ( (this.getImtbIssueReqFlow()==castOther.getImtbIssueReqFlow()) || ( this.getImtbIssueReqFlow()!=null && castOther.getImtbIssueReqFlow()!=null && this.getImtbIssueReqFlow().equals(castOther.getImtbIssueReqFlow()) ) )
		 && ( (this.getSatbUser()==castOther.getSatbUser()) || ( this.getSatbUser()!=null && castOther.getSatbUser()!=null && this.getSatbUser().equals(castOther.getSatbUser()) ) )
		 && ( (this.getImtbIssueReq()==castOther.getImtbIssueReq()) || ( this.getImtbIssueReq()!=null && castOther.getImtbIssueReq()!=null && this.getImtbIssueReq().equals(castOther.getImtbIssueReq()) ) );
	 }

	 @Override
	 public int hashCode() {
		 int result = 17;

		 result = 37 * result + ( getIssueReqFlowNo() == null ? 0 : this.getIssueReqFlowNo().hashCode() );
		 result = 37 * result + ( getFromStatus() == null ? 0 : this.getFromStatus().hashCode() );
		 result = 37 * result + ( getToStatus() == null ? 0 : this.getToStatus().hashCode() );
		 result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
		 result = 37 * result + ( getFlowDt() == null ? 0 : this.getFlowDt().hashCode() );
		 result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );


		 result = 37 * result + ( getImtbIssueReqFlow() == null ? 0 : this.getImtbIssueReqFlow().hashCode() );
		 result = 37 * result + ( getSatbUser() == null ? 0 : this.getSatbUser().hashCode() );
		 result = 37 * result + ( getImtbIssueReq() == null ? 0 : this.getImtbIssueReq().hashCode() );
		 return result;
	 }





}
