package com.cdgtaxi.ibs.common.model;

// Generated Jul 20, 2009 5:50:40 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.master.model.MstbMasterTable;

/**
 * AmtbBillReq generated by hbm2java
 */

public class ImtbItemReq implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	// Fields
	private Integer reqNo;
	private Timestamp requestDt;
	private String requestor;
	private MstbMasterTable mstbMasterTableByReason; // reason
	private String remarks;
	private Integer version;
	private Timestamp redeemTime;
    private String redeemPoint;
    private String batchNo;
    private Date batchDate;
    private String cashierId;
    private BigDecimal serialNo;
    private String currentStatus;
    private String action;
    private Date newExpiryDate;
    
	// Relationships
	private ImtbItem imtbItem;
	private Set<ImtbItemReqFlow> imtbItemReqFlows = new HashSet<ImtbItemReqFlow>(0);

	// Constructors
	/** default constructor */
	public ImtbItemReq() {
	}

	/** minimal constructor */
	public ImtbItemReq(Timestamp requestDt, String requestor,
			MstbMasterTable mstbMasterTableByReason, ImtbItem imtbItem,
			String currentStatus, String action) {
		this.requestDt = requestDt;
		this.requestor = requestor;
		this.mstbMasterTableByReason = mstbMasterTableByReason;
		this.imtbItem = imtbItem;
		this.currentStatus = currentStatus;
		this.action = action;
	}

	/** full constructor */
	public ImtbItemReq(Integer reqNo, Timestamp requestDt, String requestor,
			MstbMasterTable mstbMasterTableByReason, String remarks, Integer version,
			ImtbItem imtbItem, Set<ImtbItemReqFlow> imtbItemReqFlows, Timestamp redeemTime,
			String redeemPoint, String batchNo, Date batchDate, String cashierId, BigDecimal serialNo, String currentStatus,
			String action, Date newExpiryDate) {
		super();
		this.reqNo = reqNo;
		this.requestDt = requestDt;
		this.requestor = requestor;
		this.mstbMasterTableByReason = mstbMasterTableByReason;
		this.remarks = remarks;
		this.version = version;
		this.imtbItem = imtbItem;
		this.imtbItemReqFlows = imtbItemReqFlows;
		this.redeemTime = redeemTime;
		this.redeemPoint = redeemPoint;
		this.batchNo = batchNo;
		this.batchDate = batchDate;
		this.cashierId = cashierId;
		this.serialNo = serialNo;
		this.currentStatus = currentStatus;
		this.action = action;
		this.newExpiryDate = newExpiryDate;
	}

	// Property accessors
	public String getAction() {
		return action;
	}

	public void setAction(String action) {
		this.action = action;
	}
	
	public Integer getReqNo() {
		return reqNo;
	}

	public void setReqNo(Integer reqNo) {
		this.reqNo = reqNo;
	}

	public Timestamp getRequestDt() {
		return requestDt;
	}

	public void setRequestDt(Timestamp requestDt) {
		this.requestDt = requestDt;
	}

	public String getRequestor() {
		return requestor;
	}

	public void setRequestor(String requestor) {
		this.requestor = requestor;
	}

	public MstbMasterTable getMstbMasterTableByReason() {
		return mstbMasterTableByReason;
	}

	public void setMstbMasterTableByReason(MstbMasterTable mstbMasterTableByReason) {
		this.mstbMasterTableByReason = mstbMasterTableByReason;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Integer getVersion() {
		return version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public ImtbItem getImtbItem() {
		return imtbItem;
	}

	public void setImtbItem(ImtbItem imtbItem) {
		this.imtbItem = imtbItem;
	}

	public Set<ImtbItemReqFlow> getImtbItemReqFlows() {
		return imtbItemReqFlows;
	}

	public void setImtbItemReqFlows(Set<ImtbItemReqFlow> imtbItemReqFlows) {
		this.imtbItemReqFlows = imtbItemReqFlows;
	}

	public Timestamp getRedeemTime() {
		return redeemTime;
	}

	public void setRedeemTime(Timestamp redeemTime) {
		this.redeemTime = redeemTime;
	}

	public String getRedeemPoint() {
		return redeemPoint;
	}

	public void setRedeemPoint(String redeemPoint) {
		this.redeemPoint = redeemPoint;
	}
	
	public String getBatchNo() {
		return batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}
	
	public Date getBatchDate() {
		return batchDate;
	}

	public void setBatchDate(Date batchDate) {
		this.batchDate = batchDate;
	}

	public String getCashierId() {
		return cashierId;
	}

	public void setCashierId(String cashierId) {
		this.cashierId = cashierId;
	}

	public BigDecimal getSerialNo() {
		return serialNo;
	}

	public void setSerialNo(BigDecimal serialNo) {
		this.serialNo = serialNo;
	}

	public String getCurrentStatus() {
		return currentStatus;
	}

	public void setCurrentStatus(String currentStatus) {
		this.currentStatus = currentStatus;
	}
	
	public Date getNewExpiryDate() {
		return newExpiryDate;
	}

	public void setNewExpiryDate(Date newExpiryDate) {
		this.newExpiryDate = newExpiryDate;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	public String toString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode()))
				.append(" [");
		buffer.append("reqNo").append("='").append(getReqNo()).append("' ");
		buffer.append("requestDt").append("='").append(getRequestDt()).append("' ");
		buffer.append("requestor").append("='").append(getRequestor()).append("' ");
		buffer.append("remarks").append("='").append(getRemarks()).append("' ");
		buffer.append("version").append("='").append(getVersion()).append("' ");
		buffer.append("redeemTime").append("='").append(getRedeemTime()).append("' ");
		buffer.append("redeemPoint").append("='").append(getRedeemPoint()).append("' ");
		buffer.append("batchNo").append("='").append(getBatchNo()).append("' ");
		buffer.append("batchDate").append("='").append(getBatchDate()).append("' ");
		buffer.append("cashierId").append("='").append(getCashierId()).append("' ");
		buffer.append("serialNo").append("='").append(getSerialNo()).append("' ");
		buffer.append("currentStatus").append("='").append(getCurrentStatus()).append("' ");
		buffer.append("action").append("='").append(getAction()).append("' ");
		buffer.append("newExpiryDate").append("='").append(getNewExpiryDate()).append("' ");
		buffer.append("]");
		return buffer.toString();
	}

	public boolean equals(Object other) {
		if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof ImtbItemReq) ) return false;
		ImtbItemReq castOther = ( ImtbItemReq ) other; 
        
		 return ( (this.getReqNo()==castOther.getReqNo()) || ( this.getReqNo()!=null && castOther.getReqNo()!=null && this.getReqNo().equals(castOther.getReqNo()) ) )
&& ( (this.getRequestDt()==castOther.getRequestDt()) || ( this.getRequestDt()!=null && castOther.getRequestDt()!=null && this.getRequestDt().equals(castOther.getRequestDt()) ) )
&& ( (this.getRequestor()==castOther.getRequestor()) || ( this.getRequestor()!=null && castOther.getRequestor()!=null && this.getRequestor().equals(castOther.getRequestor()) ) )
&& ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) )
&& ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
&& ( (this.getRedeemTime()==castOther.getRedeemTime()) || ( this.getRedeemTime()!=null && castOther.getRedeemTime()!=null && this.getRedeemTime().equals(castOther.getRedeemTime()) ) )
&& ( (this.getRedeemPoint()==castOther.getRedeemPoint()) || ( this.getRedeemPoint()!=null && castOther.getRedeemPoint()!=null && this.getRedeemPoint().equals(castOther.getRedeemPoint()) ) )
&& ( (this.getBatchNo()==castOther.getBatchNo()) || ( this.getBatchNo()!=null && castOther.getBatchNo()!=null && this.getBatchNo().equals(castOther.getBatchNo()) ) )
&& ( (this.getBatchDate()==castOther.getBatchDate()) || ( this.getBatchDate()!=null && castOther.getBatchDate()!=null && this.getBatchDate().equals(castOther.getBatchDate()) ) )
&& ( (this.getCashierId()==castOther.getCashierId()) || ( this.getCashierId()!=null && castOther.getCashierId()!=null && this.getCashierId().equals(castOther.getCashierId()) ) )
&& ( (this.getSerialNo()==castOther.getSerialNo()) || ( this.getSerialNo()!=null && castOther.getSerialNo()!=null && this.getSerialNo().equals(castOther.getSerialNo()) ) )
&& ( (this.getCurrentStatus()==castOther.getCurrentStatus()) || ( this.getCurrentStatus()!=null && castOther.getCurrentStatus()!=null && this.getCurrentStatus().equals(castOther.getCurrentStatus()) ) )
&& ( (this.getAction()==castOther.getAction()) || ( this.getAction()!=null && castOther.getAction()!=null && this.getAction().equals(castOther.getAction()) ) )
&& ( (this.getNewExpiryDate()==castOther.getNewExpiryDate()) || ( this.getNewExpiryDate()!=null && castOther.getNewExpiryDate()!=null && this.getNewExpiryDate().equals(castOther.getNewExpiryDate()) ) );
  }

	public int hashCode() {
        int result = 17;
        
        result = 37 * result + ( getReqNo() == null ? 0 : this.getReqNo().hashCode() );
        result = 37 * result + ( getRequestDt() == null ? 0 : this.getRequestDt().hashCode() );
        result = 37 * result + ( getRequestor() == null ? 0 : this.getRequestor().hashCode() );
        result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
        result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
        result = 37 * result + ( getRedeemTime() == null ? 0 : this.getRedeemTime().hashCode() );
        result = 37 * result + ( getRedeemPoint() == null ? 0 : this.getRedeemPoint().hashCode() );
        result = 37 * result + ( getBatchNo() == null ? 0 : this.getBatchNo().hashCode() );
        result = 37 * result + ( getBatchDate() == null ? 0 : this.getBatchDate().hashCode() );
        result = 37 * result + ( getCashierId() == null ? 0 : this.getCashierId().hashCode() );
        result = 37 * result + ( getSerialNo() == null ? 0 : this.getSerialNo().hashCode() );
        result = 37 * result + ( getCurrentStatus() == null ? 0 : this.getCurrentStatus().hashCode() );
        result = 37 * result + ( getAction() == null ? 0 : this.getAction().hashCode() );
        result = 37 * result + ( getNewExpiryDate() == null ? 0 : this.getNewExpiryDate().hashCode() );
        return result;
  }   
}
