package com.cdgtaxi.ibs.common.model;
// Generated Aug 30, 2009 4:14:58 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

/**
 * ImtbItem generated by hbm2java
 */

@SuppressWarnings("serial")
public class ImtbItem implements java.io.Serializable, Creatable, Updatable {

	// Fields

	private Long itemNo;
	private BigDecimal serialNo;
	private String status;
	private Integer version;
	private Timestamp updateDt;
	private ImtbItemType imtbItemType;
	private ImtbIssue imtbIssue;
	private Timestamp redeemTime;
	private String redeemPoint;
	private String batchNo;
	private String cashierId;
	private Date batchDate;
	private Timestamp createdDt;
	private String createdBy;
	private String updatedBy;
	private Date expiryDate;
	// Constructors

	/** default constructor */
	public ImtbItem() {
	}

	/** minimal constructor */
	public ImtbItem(BigDecimal serialNo, String status, Timestamp updateDt) {
		this.serialNo = serialNo;
		this.status = status;
		this.updateDt = updateDt;
	}

	/** full constructor */
	public ImtbItem(BigDecimal serialNo, String status, Integer version, Timestamp updateDt,
			ImtbItemType imtbItemType, ImtbIssue imtbIssue, Timestamp redeemTime,
			String redeemPoint, String batchNo, String cashierId, Date batchDate,
			Timestamp createdDt, String createdBy, String updatedBy, Date expiryDate) {
		this.serialNo = serialNo;
		this.status = status;
		this.version = version;
		this.updateDt = updateDt;
		this.imtbItemType = imtbItemType;
		this.imtbIssue = imtbIssue;
		this.redeemTime = redeemTime;
		this.redeemPoint = redeemPoint;
		this.batchNo = batchNo;
		this.cashierId = cashierId;
		this.batchDate = batchDate;
		this.createdDt = createdDt;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.expiryDate = expiryDate;
	}

	// Property accessors

	public Timestamp getCreatedDt() {
		return createdDt;
	}

	public void setCreatedDt(Timestamp createdDt) {
		this.createdDt = createdDt;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Timestamp getRedeemTime() {
		return redeemTime;
	}

	public void setRedeemTime(Timestamp redeemTime) {
		this.redeemTime = redeemTime;
	}

	public String getRedeemPoint() {
		return redeemPoint;
	}

	public void setRedeemPoint(String redeemPoint) {
		this.redeemPoint = redeemPoint;
	}

	public String getBatchNo() {
		return batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	public String getCashierId() {
		return cashierId;
	}

	public void setCashierId(String cashierId) {
		this.cashierId = cashierId;
	}

	public Long getItemNo() {
		return this.itemNo;
	}

	public void setItemNo(Long itemNo) {
		this.itemNo = itemNo;
	}

	public BigDecimal getSerialNo() {
		return this.serialNo;
	}

	public void setSerialNo(BigDecimal serialNo) {
		this.serialNo = serialNo;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public Timestamp getUpdateDt() {
		return this.updateDt;
	}

	public void setUpdateDt(Timestamp updateDt) {
		this.updateDt = updateDt;
	}

	public Date getExpiryDate() {
		return expiryDate;
	}

	public void setExpiryDate(Date expiryDate) {
		this.expiryDate = expiryDate;
	}

	public ImtbItemType getImtbItemType() {
		return this.imtbItemType;
	}

	public void setImtbItemType(ImtbItemType imtbItemType) {
		this.imtbItemType = imtbItemType;
	}

	public ImtbIssue getImtbIssue() {
		return this.imtbIssue;
	}

	public void setImtbIssue(ImtbIssue imtbIssue) {
		this.imtbIssue = imtbIssue;
	}

	public void setUpdatedDt(Timestamp timestamp) {
		this.updateDt = timestamp;
	}

	public Date getBatchDate() {
		return batchDate;
	}

	public void setBatchDate(Date batchDate) {
		this.batchDate = batchDate;
	}

	/**
	 * toString
	 * 
	 * @return String
	 */
	@Override
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode()))
				.append(" [");
		buffer.append("serialNo").append("='").append(getSerialNo()).append("' ");
		buffer.append("status").append("='").append(getStatus()).append("' ");
		buffer.append("version").append("='").append(getVersion()).append("' ");
		buffer.append("updateDt").append("='").append(getUpdateDt()).append("' ");
		buffer.append("redeemTime").append("='").append(getRedeemTime()).append("' ");
		buffer.append("redeemPoint").append("='").append(getRedeemPoint()).append("' ");
		buffer.append("batchNo").append("='").append(getBatchNo()).append("' ");
		buffer.append("cashierId").append("='").append(getCashierId()).append("' ");
		buffer.append("batchDate").append("='").append(getBatchDate()).append("' ");
		buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");
		buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
		buffer.append("updateDt").append("='").append(getUpdateDt()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	@Override
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ImtbItem))
			return false;
		ImtbItem castOther = (ImtbItem) other;

		return ((this.getItemNo() == castOther.getItemNo()) || (this.getItemNo() != null
				&& castOther.getItemNo() != null && this.getItemNo().equals(castOther.getItemNo())))
				&& ((this.getSerialNo() == castOther.getSerialNo()) || (this.getSerialNo() != null
						&& castOther.getSerialNo() != null && this.getSerialNo().equals(
						castOther.getSerialNo())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(
						castOther.getStatus())))
				&& ((this.getVersion() == castOther.getVersion()) || (this.getVersion() != null
						&& castOther.getVersion() != null && this.getVersion().equals(
						castOther.getVersion())))
				&& ((this.getUpdateDt() == castOther.getUpdateDt()) || (this.getUpdateDt() != null
						&& castOther.getUpdateDt() != null && this.getUpdateDt().equals(
						castOther.getUpdateDt())))
				&& ((this.getImtbItemType() == castOther.getImtbItemType()) || (this
						.getImtbItemType() != null && castOther.getImtbItemType() != null && this
						.getImtbItemType().equals(castOther.getImtbItemType())))
				&& ((this.getImtbIssue() == castOther.getImtbIssue()) || (this.getImtbIssue() != null
						&& castOther.getImtbIssue() != null && this.getImtbIssue().equals(
						castOther.getImtbIssue())))
				&& ((this.getRedeemTime() == castOther.getRedeemTime()) || (this.getRedeemTime() != null
						&& castOther.getRedeemTime() != null && this.getRedeemTime().equals(
						castOther.getRedeemTime())))
				&& ((this.getRedeemPoint() == castOther.getRedeemPoint()) || (this.getRedeemPoint() != null
						&& castOther.getRedeemPoint() != null && this.getRedeemPoint().equals(
						castOther.getRedeemPoint())))
				&& ((this.getBatchNo() == castOther.getBatchNo()) || (this.getBatchNo() != null
						&& castOther.getBatchNo() != null && this.getBatchNo().equals(
						castOther.getBatchNo())))
				&& ((this.getCashierId() == castOther.getCashierId()) || (this.getCashierId() != null
						&& castOther.getCashierId() != null && this.getCashierId().equals(
						castOther.getCashierId())))
				&& ((this.getBatchDate() == castOther.getBatchDate()) || (this.getBatchDate() != null
						&& castOther.getBatchDate() != null && this.getBatchDate().equals(
						castOther.getBatchDate())))
				&& ((this.getCreatedDt() == castOther.getCreatedDt()) || (this.getCreatedDt() != null
						&& castOther.getCreatedDt() != null && this.getCreatedDt().equals(
						castOther.getCreatedDt())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this.getCreatedBy().equals(
						castOther.getCreatedBy())))
				&& ((this.getUpdateDt() == castOther.getUpdateDt()) || (this.getUpdateDt() != null
						&& castOther.getUpdateDt() != null && this.getUpdateDt().equals(
						castOther.getUpdateDt())));
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + (getItemNo() == null ? 0 : this.getItemNo().hashCode());
		result = 37 * result + (getSerialNo() == null ? 0 : this.getSerialNo().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result + (getUpdateDt() == null ? 0 : this.getUpdateDt().hashCode());
		result = 37 * result + (getImtbItemType() == null ? 0 : this.getImtbItemType().hashCode());
		result = 37 * result + (getImtbIssue() == null ? 0 : this.getImtbIssue().hashCode());
		result = 37 * result + (getRedeemTime() == null ? 0 : this.getRedeemTime().hashCode());
		result = 37 * result + (getRedeemPoint() == null ? 0 : this.getRedeemPoint().hashCode());
		result = 37 * result + (getBatchNo() == null ? 0 : this.getBatchNo().hashCode());
		result = 37 * result + (getCashierId() == null ? 0 : this.getCashierId().hashCode());
		result = 37 * result + (getBatchDate() == null ? 0 : this.getBatchDate().hashCode());
		result = 37 * result + (getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode());
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getUpdateDt() == null ? 0 : this.getUpdateDt().hashCode());
		return result;
	}

}
