package com.cdgtaxi.ibs.common.model;
// Generated Jul 28, 2009 5:37:59 PM by Hibernate Tools 3.1.0.beta4

import com.cdgtaxi.ibs.acl.security.Auditable;


/**
 * FmtbArContCodeDetail generated by hbm2java
 */

public class IttbRecurringChargeTagAcct  implements java.io.Serializable, Auditable {


    // Fields    
	private Integer id;

	private AmtbAccount amtbAccount;
    private IttbRecurringCharge recurringChargeId;
    
    public Integer getId() {
		return id;
	}


	public void setId(Integer id) {
		this.id = id;
	}



    // Constructors

   

	/** default constructor */
    public IttbRecurringChargeTagAcct() {
    }


	 public AmtbAccount getAmtbAccount() {
			return amtbAccount;
		}


		public void setAmtbAccount(AmtbAccount amtbAccount) {
			this.amtbAccount = amtbAccount;
		}


		public IttbRecurringCharge getRecurringChargeId() {
			return recurringChargeId;
		}


		public void setRecurringChargeId(IttbRecurringCharge recurringChargeId) {
			this.recurringChargeId = recurringChargeId;
		}
}