package com.cdgtaxi.ibs.common.model;
// Generated Feb 15, 2011 3:17:30 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.acl.security.DoNotAudit;


/**
 * IttbGiroReq generated by hbm2java
 */

@SuppressWarnings("serial")
public class IttbGiroReq  implements java.io.Serializable, Auditable, Creatable, Updatable {


    // Fields    

    private Long reqNo;
    private Date requestDate;
    private int requestTime;
    private Date valueDate;
    private Date cutoffDate;
    private String status;
    private Integer version;
    private String createdBy;
    private Timestamp createdDt;
    private String updatedBy;
    private Timestamp updatedDt;
    private Set<IttbGiroUobHeader> ittbGiroUobHeaders = new HashSet<IttbGiroUobHeader>(0);
    private IttbGiroSetup ittbGiroSetup;

    // Custom Fields
    @DoNotAudit
    private String entityCode;
    @DoNotAudit
    private String fileName;
    @DoNotAudit
    private Long totalRecordCount;
    @DoNotAudit
    private BigDecimal totalGiroAmount;

    // Constructors

    /** default constructor */
    public IttbGiroReq() {
    }

	/** minimal constructor */
    public IttbGiroReq(Date requestDate, int reqTime, String status, Date valueDate, Date cutoffDate) {
        this.requestDate = requestDate;
        this.requestTime = reqTime;
        this.valueDate = valueDate;
        this.cutoffDate = cutoffDate;
        this.status = status;
    }
    
    /** full constructor */
    public IttbGiroReq(Date requestDate, int requestTime, Date valueDate, Date cutoffDate, String status, Integer version, String createdBy, Timestamp createdDt, String updatedBy, Timestamp updatedDt, Set<IttbGiroUobHeader> ittbGiroUobHeaders, IttbGiroSetup ittbGiroSetup) {
        this.requestDate = requestDate;
        this.requestTime = requestTime;
        this.valueDate = valueDate;
        this.cutoffDate = cutoffDate;
        this.status = status;
        this.version = version;
        this.createdBy = createdBy;
        this.createdDt = createdDt;
        this.updatedBy = updatedBy;
        this.updatedDt = updatedDt;
        this.ittbGiroUobHeaders = ittbGiroUobHeaders;
        this.ittbGiroSetup = ittbGiroSetup;
    }
   
    // Property accessors

    public Long getReqNo() {
        return this.reqNo;
    }
    
    public void setReqNo(Long reqNo) {
        this.reqNo = reqNo;
    }

    public Date getRequestDate() {
        return this.requestDate;
    }
    
    public void setRequestDate(Date requestDate) {
        this.requestDate = requestDate;
    }

    public int getRequestTime() {
        return this.requestTime;
    }
    
    public void setRequestTime(int requestTime) {
        this.requestTime = requestTime;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public Set<IttbGiroUobHeader> getIttbGiroUobHeaders() {
        return this.ittbGiroUobHeaders;
    }
    
    public void setIttbGiroUobHeaders(Set<IttbGiroUobHeader> ittbGiroUobHeaders) {
        this.ittbGiroUobHeaders = ittbGiroUobHeaders;
    }

    public IttbGiroSetup getIttbGiroSetup() {
        return this.ittbGiroSetup;
    }
    
    public void setIttbGiroSetup(IttbGiroSetup ittbGiroSetup) {
        this.ittbGiroSetup = ittbGiroSetup;
    }
   
    public String getEntityCode() {
		return entityCode;
	}

	public void setEntityCode(String entityCode) {
		this.entityCode = entityCode;
	}

	public Date getValueDate() {
		return valueDate;
	}

	public void setValueDate(Date valueDate) {
		this.valueDate = valueDate;
	}

	public Date getCutoffDate() {
		return cutoffDate;
	}

	public void setCutoffDate(Date cutoffDate) {
		this.cutoffDate = cutoffDate;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public Long getTotalRecordCount() {
		return totalRecordCount;
	}

	public void setTotalRecordCount(Long totalRecordCount) {
		this.totalRecordCount = totalRecordCount;
	}

	public BigDecimal getTotalGiroAmount() {
		return totalGiroAmount;
	}

	public void setTotalGiroAmount(BigDecimal totalGiroAmount) {
		this.totalGiroAmount = totalGiroAmount;
	}
    
    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("requestDate").append("='").append(getRequestDate()).append("' ");			
      buffer.append("requestTime").append("='").append(getRequestTime()).append("' ");
      buffer.append("valueDate").append("='").append(getValueDate()).append("' ");
      buffer.append("cutoffDate").append("='").append(getCutoffDate()).append("' ");
      buffer.append("status").append("='").append(getStatus()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IttbGiroReq) ) return false;
		 IttbGiroReq castOther = ( IttbGiroReq ) other; 
         
		 return ( (this.getReqNo()==castOther.getReqNo()) || ( this.getReqNo()!=null && castOther.getReqNo()!=null && this.getReqNo().equals(castOther.getReqNo()) ) )
 && ( (this.getRequestDate()==castOther.getRequestDate()) || ( this.getRequestDate()!=null && castOther.getRequestDate()!=null && this.getRequestDate().equals(castOther.getRequestDate()) ) )
 && (this.getRequestTime()==castOther.getRequestTime())
 && ( (this.getValueDate()==castOther.getValueDate()) || ( this.getValueDate()!=null && castOther.getValueDate()!=null && this.getValueDate().equals(castOther.getValueDate()) ) )
 && ( (this.getCutoffDate()==castOther.getCutoffDate()) || ( this.getCutoffDate()!=null && castOther.getCutoffDate()!=null && this.getCutoffDate().equals(castOther.getCutoffDate()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getIttbGiroSetup()==castOther.getIttbGiroSetup()) || ( this.getIttbGiroSetup()!=null && castOther.getIttbGiroSetup()!=null && this.getIttbGiroSetup().equals(castOther.getIttbGiroSetup()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getReqNo() == null ? 0 : this.getReqNo().hashCode() );
         result = 37 * result + ( getRequestDate() == null ? 0 : this.getRequestDate().hashCode() );
         result = 37 * result + this.getRequestTime();
         result = 37 * result + ( getValueDate() == null ? 0 : this.getValueDate().hashCode() );
         result = 37 * result + ( getCutoffDate() == null ? 0 : this.getCutoffDate().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         
         result = 37 * result + ( getIttbGiroSetup() == null ? 0 : this.getIttbGiroSetup().hashCode() );
         return result;
   }   





}
