package com.cdgtaxi.ibs.common.model;
// Generated Jan 21, 2010 10:43:47 AM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Timestamp;

import com.cdgtaxi.ibs.common.model.IttbCpGuest;
import com.cdgtaxi.ibs.common.model.PmtbProduct;


/**
 * IttbCpGuestProduct generated by hbm2java
 */

public class IttbCpGuestProduct  implements java.io.Serializable {


    // Fields    

    private Long guestProductNo;
    
    //
    private BigDecimal pmtbProductNo;
    private Long guestNo;
        
    private Timestamp activationDt;
    private Timestamp deactivationDt;
    private String createdBy;
    private Timestamp createdDt;
    private String updatedBy;
    private Timestamp updatedDt;
    private PmtbProduct pmtbProduct;
    private IttbCpGuest ittbCpGuest;
    private String billedFlag;

    // Constructors

    /** default constructor */
    public IttbCpGuestProduct() {
    	billedFlag = "N";
    }

	/** minimal constructor */
    public IttbCpGuestProduct(Long guestNo, Timestamp activationDt, String billedFlag) {
        this.guestNo = guestNo;
        this.activationDt = activationDt;
        this.billedFlag = billedFlag;
    }
    
    /** full constructor */
    public IttbCpGuestProduct(Long guestNo, Timestamp activationDt, Timestamp deactivationDt, String createdBy, Timestamp createdDt, String updatedBy, Timestamp updatedDt,PmtbProduct pmtbProduct,BigDecimal pmtbProductNo,IttbCpGuest ittbCpGuest, String billedFlag) {
        this.guestNo = guestNo;
        this.activationDt = activationDt;
        this.deactivationDt = deactivationDt;
        this.createdBy = createdBy;
        this.createdDt = createdDt;
        this.updatedBy = updatedBy;
        this.updatedDt = updatedDt;
        this.pmtbProduct = pmtbProduct;
        this.pmtbProductNo = pmtbProductNo;
        this.ittbCpGuest = ittbCpGuest;
        this.billedFlag = billedFlag;
    }
    

   
    // Property accessors

    public Long getGuestProductNo() {
        return this.guestProductNo;
    }
    
    public void setGuestProductNo(Long guestProductNo) {
        this.guestProductNo = guestProductNo;
    }
    public BigDecimal getPmtbProductNo() {
		return pmtbProductNo;
	}
	public void setPmtbProductNo(BigDecimal pmtbProductNo) {
		this.pmtbProductNo = pmtbProductNo;
	}    
    public Long getGuestNo() {
        return this.guestNo;
    }
    
    public void setGuestNo(Long guestNo) {
        this.guestNo = guestNo;
    }
    public Timestamp getActivationDt() {
        return this.activationDt;
    }
    public void setActivationDt(Timestamp activationDt) {
        this.activationDt = activationDt;
    }

    public Timestamp getDeactivationDt() {
        return this.deactivationDt;
    }
    
    public void setDeactivationDt(Timestamp deactivationDt) {
        this.deactivationDt = deactivationDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }
	public IttbCpGuest getIttbCpGuest() {
		return ittbCpGuest;
	}
	public void setIttbCpGuest(IttbCpGuest ittbCpGuest) {
		this.ittbCpGuest = ittbCpGuest;
	}
	public PmtbProduct getPmtbProduct() {
			return pmtbProduct;
	}
	public void setPmtbProduct(PmtbProduct pmtbProduct) {
			this.pmtbProduct = pmtbProduct;
	}


    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("guestNo").append("='").append(getGuestNo()).append("' ");			
      buffer.append("activationDt").append("='").append(getActivationDt()).append("' ");			
      buffer.append("deactivationDt").append("='").append(getDeactivationDt()).append("' ");
      buffer.append("billedFlag").append("='").append(getBilledFlag()).append("' ");
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IttbCpGuestProduct) ) return false;
		 IttbCpGuestProduct castOther = ( IttbCpGuestProduct ) other; 
         
		 return ( (this.getGuestProductNo()==castOther.getGuestProductNo()) || ( this.getGuestProductNo()!=null && castOther.getGuestProductNo()!=null && this.getGuestProductNo().equals(castOther.getGuestProductNo()) ) )
 && ( (this.getGuestNo()==castOther.getGuestNo()) || ( this.getGuestNo()!=null && castOther.getGuestNo()!=null && this.getGuestNo().equals(castOther.getGuestNo()) ) )
 && ( (this.getActivationDt()==castOther.getActivationDt()) || ( this.getActivationDt()!=null && castOther.getActivationDt()!=null && this.getActivationDt().equals(castOther.getActivationDt()) ) )
 && ( (this.getDeactivationDt()==castOther.getDeactivationDt()) || ( this.getDeactivationDt()!=null && castOther.getDeactivationDt()!=null && this.getDeactivationDt().equals(castOther.getDeactivationDt()) ) )
 && ( (this.getBilledFlag()==castOther.getBilledFlag()) || ( this.getBilledFlag()!=null && castOther.getBilledFlag()!=null && this.getBilledFlag().equals(castOther.getBilledFlag()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getGuestProductNo() == null ? 0 : this.getGuestProductNo().hashCode() );
         result = 37 * result + ( getGuestNo() == null ? 0 : this.getGuestNo().hashCode() );
         result = 37 * result + ( getActivationDt() == null ? 0 : this.getActivationDt().hashCode() );
         result = 37 * result + ( getDeactivationDt() == null ? 0 : this.getDeactivationDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getBilledFlag() == null ? 0 : this.getBilledFlag().hashCode() );
         return result;
   }

	public String getBilledFlag() {
		return billedFlag;
	}
	
	public void setBilledFlag(String billedFlag) {
		this.billedFlag = billedFlag;
}   





}
