package com.cdgtaxi.ibs.common.model;
// Generated Feb 15, 2011 3:17:25 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.acl.security.Auditable;


/**
 * IttbGiroUobRejected generated by hbm2java
 */

public class IttbGiroUobRejected  implements java.io.Serializable, Creatable, Updatable {


    // Fields    

    private Long uobRejectedNo;
    private String bankCode;
    private String branchCode;
    private String bankAcctNo;
    private int transactionCode;
    private BigDecimal giroAmount;
    private String particulars;
    private String reference;
    private int clearFate;
    private int rejectionCode;
    private String rejectionReason;
    private String rejectedBy;
    private Integer version;
    private String createdBy;
    private Timestamp createdDt;
    private String updatedBy;
    private Timestamp updatedDt;
    private Set<IttbGiroUobDetail> ittbGiroUobDetails = new HashSet<IttbGiroUobDetail>(0);
    private AmtbAccount amtbAccount;


    // Constructors

    /** default constructor */
    public IttbGiroUobRejected() {
    }

	/** minimal constructor */
    public IttbGiroUobRejected(String bankCode, String branchCode, String bankAcctNo, int transactionCode, BigDecimal giroAmount, String particulars, String reference, int clearFate, int rejectionCode, String rejectedBy) {
        this.bankCode = bankCode;
        this.branchCode = branchCode;
        this.bankAcctNo = bankAcctNo;
        this.transactionCode = transactionCode;
        this.giroAmount = giroAmount;
        this.particulars = particulars;
        this.reference = reference;
        this.clearFate = clearFate;
        this.rejectionCode = rejectionCode;
        this.rejectedBy = rejectedBy;
    }
    
    /** full constructor */
    public IttbGiroUobRejected(String bankCode, String branchCode, String bankAcctNo, int transactionCode, BigDecimal giroAmount, String particulars, String reference, int clearFate, int rejectionCode, String rejectionReason, String rejectedBy, Integer version, String createdBy, Timestamp createdDt, String updatedBy, Timestamp updatedDt, Set<IttbGiroUobDetail> ittbGiroUobDetails, AmtbAccount amtbAccount) {
        this.bankCode = bankCode;
        this.branchCode = branchCode;
        this.bankAcctNo = bankAcctNo;
        this.transactionCode = transactionCode;
        this.giroAmount = giroAmount;
        this.particulars = particulars;
        this.reference = reference;
        this.clearFate = clearFate;
        this.rejectionCode = rejectionCode;
        this.rejectionReason = rejectionReason;
        this.rejectedBy = rejectedBy;
        this.version = version;
        this.createdBy = createdBy;
        this.createdDt = createdDt;
        this.updatedBy = updatedBy;
        this.updatedDt = updatedDt;
        this.ittbGiroUobDetails = ittbGiroUobDetails;
        this.amtbAccount = amtbAccount;
    }
    

   
    // Property accessors

    public Long getUobRejectedNo() {
        return this.uobRejectedNo;
    }
    
    public void setUobRejectedNo(Long uobRejectedNo) {
        this.uobRejectedNo = uobRejectedNo;
    }

    public String getBankCode() {
        return this.bankCode;
    }
    
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    public String getBranchCode() {
        return this.branchCode;
    }
    
    public void setBranchCode(String branchCode) {
        this.branchCode = branchCode;
    }

    public String getBankAcctNo() {
        return this.bankAcctNo;
    }
    
    public void setBankAcctNo(String bankAcctNo) {
        this.bankAcctNo = bankAcctNo;
    }

    public int getTransactionCode() {
        return this.transactionCode;
    }
    
    public void setTransactionCode(int transactionCode) {
        this.transactionCode = transactionCode;
    }

    public BigDecimal getGiroAmount() {
        return this.giroAmount;
    }
    
    public void setGiroAmount(BigDecimal giroAmount) {
        this.giroAmount = giroAmount;
    }

    public String getParticulars() {
        return this.particulars;
    }
    
    public void setParticulars(String particulars) {
        this.particulars = particulars;
    }

    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }

    public int getClearFate() {
        return this.clearFate;
    }
    
    public void setClearFate(int clearFate) {
        this.clearFate = clearFate;
    }

    public int getRejectionCode() {
        return this.rejectionCode;
    }
    
    public void setRejectionCode(int rejectionCode) {
        this.rejectionCode = rejectionCode;
    }

    public String getRejectionReason() {
        return this.rejectionReason;
    }
    
    public void setRejectionReason(String rejectionReason) {
        this.rejectionReason = rejectionReason;
    }

    public String getRejectedBy() {
        return this.rejectedBy;
    }
    
    public void setRejectedBy(String rejectedBy) {
        this.rejectedBy = rejectedBy;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public Set<IttbGiroUobDetail> getIttbGiroUobDetails() {
        return this.ittbGiroUobDetails;
    }
    
    public void setIttbGiroUobDetails(Set<IttbGiroUobDetail> ittbGiroUobDetails) {
        this.ittbGiroUobDetails = ittbGiroUobDetails;
    }

    public AmtbAccount getAmtbAccount() {
        return this.amtbAccount;
    }
    
    public void setAmtbAccount(AmtbAccount amtbAccount) {
        this.amtbAccount = amtbAccount;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("bankCode").append("='").append(getBankCode()).append("' ");			
      buffer.append("branchCode").append("='").append(getBranchCode()).append("' ");			
      buffer.append("bankAcctNo").append("='").append(getBankAcctNo()).append("' ");			
      buffer.append("transactionCode").append("='").append(getTransactionCode()).append("' ");			
      buffer.append("giroAmount").append("='").append(getGiroAmount()).append("' ");			
      buffer.append("particulars").append("='").append(getParticulars()).append("' ");			
      buffer.append("reference").append("='").append(getReference()).append("' ");			
      buffer.append("clearFate").append("='").append(getClearFate()).append("' ");			
      buffer.append("rejectionCode").append("='").append(getRejectionCode()).append("' ");			
      buffer.append("rejectionReason").append("='").append(getRejectionReason()).append("' ");			
      buffer.append("rejectedBy").append("='").append(getRejectedBy()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IttbGiroUobRejected) ) return false;
		 IttbGiroUobRejected castOther = ( IttbGiroUobRejected ) other; 
         
		 return ( (this.getUobRejectedNo()==castOther.getUobRejectedNo()) || ( this.getUobRejectedNo()!=null && castOther.getUobRejectedNo()!=null && this.getUobRejectedNo().equals(castOther.getUobRejectedNo()) ) )
 && ( (this.getBankCode()==castOther.getBankCode()) || ( this.getBankCode()!=null && castOther.getBankCode()!=null && this.getBankCode().equals(castOther.getBankCode()) ) )
 && ( (this.getBranchCode()==castOther.getBranchCode()) || ( this.getBranchCode()!=null && castOther.getBranchCode()!=null && this.getBranchCode().equals(castOther.getBranchCode()) ) )
 && ( (this.getBankAcctNo()==castOther.getBankAcctNo()) || ( this.getBankAcctNo()!=null && castOther.getBankAcctNo()!=null && this.getBankAcctNo().equals(castOther.getBankAcctNo()) ) )
 && (this.getTransactionCode()==castOther.getTransactionCode())
 && ( (this.getGiroAmount()==castOther.getGiroAmount()) || ( this.getGiroAmount()!=null && castOther.getGiroAmount()!=null && this.getGiroAmount().equals(castOther.getGiroAmount()) ) )
 && ( (this.getParticulars()==castOther.getParticulars()) || ( this.getParticulars()!=null && castOther.getParticulars()!=null && this.getParticulars().equals(castOther.getParticulars()) ) )
 && ( (this.getReference()==castOther.getReference()) || ( this.getReference()!=null && castOther.getReference()!=null && this.getReference().equals(castOther.getReference()) ) )
 && (this.getClearFate()==castOther.getClearFate())
 && (this.getRejectionCode()==castOther.getRejectionCode())
 && ( (this.getRejectionReason()==castOther.getRejectionReason()) || ( this.getRejectionReason()!=null && castOther.getRejectionReason()!=null && this.getRejectionReason().equals(castOther.getRejectionReason()) ) )
 && ( (this.getRejectedBy()==castOther.getRejectedBy()) || ( this.getRejectedBy()!=null && castOther.getRejectedBy()!=null && this.getRejectedBy().equals(castOther.getRejectedBy()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getAmtbAccount()==castOther.getAmtbAccount()) || ( this.getAmtbAccount()!=null && castOther.getAmtbAccount()!=null && this.getAmtbAccount().equals(castOther.getAmtbAccount()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUobRejectedNo() == null ? 0 : this.getUobRejectedNo().hashCode() );
         result = 37 * result + ( getBankCode() == null ? 0 : this.getBankCode().hashCode() );
         result = 37 * result + ( getBranchCode() == null ? 0 : this.getBranchCode().hashCode() );
         result = 37 * result + ( getBankAcctNo() == null ? 0 : this.getBankAcctNo().hashCode() );
         result = 37 * result + this.getTransactionCode();
         result = 37 * result + ( getGiroAmount() == null ? 0 : this.getGiroAmount().hashCode() );
         result = 37 * result + ( getParticulars() == null ? 0 : this.getParticulars().hashCode() );
         result = 37 * result + ( getReference() == null ? 0 : this.getReference().hashCode() );
         result = 37 * result + this.getClearFate();
         result = 37 * result + this.getRejectionCode();
         result = 37 * result + ( getRejectionReason() == null ? 0 : this.getRejectionReason().hashCode() );
         result = 37 * result + ( getRejectedBy() == null ? 0 : this.getRejectedBy().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         
         result = 37 * result + ( getAmtbAccount() == null ? 0 : this.getAmtbAccount().hashCode() );
         return result;
   }   





}
