package com.cdgtaxi.ibs.common.model;
// Generated Jul 20, 2009 4:09:26 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.master.model.MstbMasterTable;


/**
 * PmtbProductType generated by hbm2java
 */

public class PmtbProductType  implements java.io.Serializable,Auditable {


    // Fields    

    private String productTypeId;
    private String name;
    private String batchIssue;
    private String nameOnProduct;
    private String luhnCheck;
    private String oneTimeUsage;
    private String fixedValue;
    private String creditLimit;
    private String validityPeriod;
    private String defaultCardStatus;
    private int numberOfDigit;
    private Integer minTopupLimit;
    private Integer maxTopupLimit;
    private String binRange;
    private String subBinRange;
    private String externalCard;
    private String issuable;
    private String issueType;
    private int defaultValidPeriod;
    private String interfaceMappingValue;
    private Integer version;
    private BigDecimal replacementFees;
    private String loginRegistration;
    private String hotel;
    private String prepaid;
    private String contactless;
    private String cardless;
    private String virtualProduct;
    private String viewPastTxn;
    private Integer defaultBalanceExpMonths;
    private BigDecimal topUpFee;
    private BigDecimal transferFee;
    private Set<AmtbApplicationProduct> amtbApplicationProducts = new HashSet<AmtbApplicationProduct>(0);
    private Set<BmtbInvoiceDetail> bmtbInvoiceDetails = new HashSet<BmtbInvoiceDetail>(0);
    private Set<TmtbTxnReviewReq> tmtbTxnReviewReqs = new HashSet<TmtbTxnReviewReq>(0);
    private Set<TmtbAcquireTxn> tmtbAcquireTxns = new HashSet<TmtbAcquireTxn>(0);
    private Set<FmtbTransactionCode> fmtbTransactionCodes = new HashSet<FmtbTransactionCode>(0);
    private Set<PmtbProduct> pmtbProducts = new HashSet<PmtbProduct>(0);
    private Set<AmtbSubscTo> amtbSubscTos = new HashSet<AmtbSubscTo>(0);
    private Set<BmtbInvoiceSummary> bmtbInvoiceSummaries = new HashSet<BmtbInvoiceSummary>(0);
    private Set<AmtbAcctType> amtbAcctTypes = new HashSet<AmtbAcctType>(0);
    private Set<AmtbAccount> amtbAccounts = new HashSet<AmtbAccount>(0);
    private MstbMasterTable mstbMasterTableBySMSFormat;
    private MstbMasterTable mstbMasterTableBySMSExpiryFormat;
    private MstbMasterTable mstbMasterTableBySMSTopupFormat;

    // Constructors

    /** default constructor */
    public PmtbProductType() {
    }

	/** minimal constructor */
    public PmtbProductType(String name, String batchIssue, String nameOnProduct, String luhnCheck, String oneTimeUsage, String fixedValue, String creditLimit, String validityPeriod, String defaultCardStatus, int numberOfDigit, String binRange, String subBinRange, String externalCard, String issuable, String issueType, int defaultValidPeriod, BigDecimal replacementFees, String loginRegistration, String hotel, String prepaid, String contactless, String cardless, String virtualProduct, String viewPastTxn, MstbMasterTable mstbMasterTableBySMSFormat, MstbMasterTable mstbMasterTableBySMSExpiryFormat, MstbMasterTable mstbMasterTableBySMSTopupFormat) {
        this.name = name;
        this.batchIssue = batchIssue;
        this.nameOnProduct = nameOnProduct;
        this.luhnCheck = luhnCheck;
        this.oneTimeUsage = oneTimeUsage;
        this.fixedValue = fixedValue;
        this.creditLimit = creditLimit;
        this.validityPeriod = validityPeriod;
        this.defaultCardStatus = defaultCardStatus;
        this.numberOfDigit = numberOfDigit;
        this.binRange = binRange;
        this.subBinRange = subBinRange;
        this.externalCard = externalCard;
        this.issuable = issuable;
        this.issueType = issueType;
        this.defaultValidPeriod = defaultValidPeriod;
        this.replacementFees = replacementFees;
        this.loginRegistration = loginRegistration;
        this.hotel = hotel;
        this.prepaid = prepaid;
        this.contactless = contactless;
        this.cardless = cardless;
        this.virtualProduct = virtualProduct;
        this.viewPastTxn = viewPastTxn;
        this.mstbMasterTableBySMSFormat = mstbMasterTableBySMSFormat;
        this.mstbMasterTableBySMSExpiryFormat = mstbMasterTableBySMSExpiryFormat;
        this.mstbMasterTableBySMSTopupFormat = mstbMasterTableBySMSTopupFormat;
        
    }
    
    /** full constructor */
    public PmtbProductType(String name, String batchIssue, String nameOnProduct, String luhnCheck, String oneTimeUsage, String fixedValue, String creditLimit, String validityPeriod, String defaultCardStatus, int numberOfDigit, String binRange, String subBinRange, String externalCard, String issuable, String issueType, int defaultValidPeriod, String interfaceMappingValue, Integer version, BigDecimal replacementFees, String loginRegistration, String hotel, String prepaid, String contactless, String cardless, String virtualProduct, String viewPastTxn, Set<AmtbApplicationProduct> amtbApplicationProducts, Set<BmtbInvoiceDetail> bmtbInvoiceDetails, Set<TmtbTxnReviewReq> tmtbTxnReviewReqs, Set<TmtbAcquireTxn> tmtbAcquireTxns, Set<FmtbTransactionCode> fmtbTransactionCodes, Set<PmtbProduct> pmtbProducts, Set<AmtbSubscTo> amtbSubscTos, Set<BmtbInvoiceSummary> bmtbInvoiceSummaries, Set<AmtbAcctType> amtbAcctTypes, Set<AmtbAccount> amtbAccounts,  MstbMasterTable mstbMasterTableBySMSFormat, MstbMasterTable mstbMasterTableBySMSExpiryFormat, MstbMasterTable mstbMasterTableBySMSTopupFormat) {
        this.name = name;
        this.batchIssue = batchIssue;
        this.nameOnProduct = nameOnProduct;
        this.luhnCheck = luhnCheck;
        this.oneTimeUsage = oneTimeUsage;
        this.fixedValue = fixedValue;
        this.creditLimit = creditLimit;
        this.validityPeriod = validityPeriod;
        this.defaultCardStatus = defaultCardStatus;
        this.numberOfDigit = numberOfDigit;
        this.binRange = binRange;
        this.subBinRange = subBinRange;
        this.externalCard = externalCard;
        this.issuable = issuable;
        this.issueType = issueType;
        this.defaultValidPeriod = defaultValidPeriod;
        this.interfaceMappingValue = interfaceMappingValue;
        this.version = version;
        this.replacementFees = replacementFees;
        this.loginRegistration = loginRegistration;
        this.hotel = hotel;
        this.prepaid = prepaid;
        this.contactless = contactless;
        this.cardless = cardless;
        this.virtualProduct = virtualProduct;
        this.viewPastTxn = viewPastTxn;
        this.amtbApplicationProducts = amtbApplicationProducts;
        this.bmtbInvoiceDetails = bmtbInvoiceDetails;
        this.tmtbTxnReviewReqs = tmtbTxnReviewReqs;
        this.tmtbAcquireTxns = tmtbAcquireTxns;
        this.fmtbTransactionCodes = fmtbTransactionCodes;
        this.pmtbProducts = pmtbProducts;
        this.amtbSubscTos = amtbSubscTos;
        this.bmtbInvoiceSummaries = bmtbInvoiceSummaries;
        this.amtbAcctTypes = amtbAcctTypes;
        this.amtbAccounts = amtbAccounts;
        this.mstbMasterTableBySMSFormat = mstbMasterTableBySMSFormat;
        this.mstbMasterTableBySMSExpiryFormat = mstbMasterTableBySMSExpiryFormat;
        this.mstbMasterTableBySMSTopupFormat = mstbMasterTableBySMSTopupFormat;
    }
    

   
    // Property accessors

    public String getProductTypeId() {
        return this.productTypeId;
    }
    
    public void setProductTypeId(String productTypeId) {
        this.productTypeId = productTypeId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getBatchIssue() {
        return this.batchIssue;
    }
    
    public void setBatchIssue(String batchIssue) {
        this.batchIssue = batchIssue;
    }

    public String getNameOnProduct() {
        return this.nameOnProduct;
    }
    
    public void setNameOnProduct(String nameOnProduct) {
        this.nameOnProduct = nameOnProduct;
    }

    public String getLuhnCheck() {
        return this.luhnCheck;
    }
    
    public void setLuhnCheck(String luhnCheck) {
        this.luhnCheck = luhnCheck;
    }

    public String getOneTimeUsage() {
        return this.oneTimeUsage;
    }
    
    public void setOneTimeUsage(String oneTimeUsage) {
        this.oneTimeUsage = oneTimeUsage;
    }

    public String getFixedValue() {
        return this.fixedValue;
    }
    
    public void setFixedValue(String fixedValue) {
        this.fixedValue = fixedValue;
    }

    public String getCreditLimit() {
        return this.creditLimit;
    }
    
    public void setCreditLimit(String creditLimit) {
        this.creditLimit = creditLimit;
    }

    public String getValidityPeriod() {
        return this.validityPeriod;
    }
    
    public void setValidityPeriod(String validityPeriod) {
        this.validityPeriod = validityPeriod;
    }

    public String getDefaultCardStatus() {
        return this.defaultCardStatus;
    }
    
    public void setDefaultCardStatus(String defaultCardStatus) {
        this.defaultCardStatus = defaultCardStatus;
    }

    public int getNumberOfDigit() {
        return this.numberOfDigit;
    }
    
    public void setNumberOfDigit(int numberOfDigit) {
        this.numberOfDigit = numberOfDigit;
    }

    public String getBinRange() {
        return this.binRange;
    }
    
    public void setBinRange(String binRange) {
        this.binRange = binRange;
    }

    public String getSubBinRange() {
        return this.subBinRange;
    }
    
    public void setSubBinRange(String subBinRange) {
        this.subBinRange = subBinRange;
    }

    public String getExternalCard() {
        return this.externalCard;
    }
    
    public void setExternalCard(String externalCard) {
        this.externalCard = externalCard;
    }

    public String getIssuable() {
        return this.issuable;
    }
    
    public void setIssuable(String issuable) {
        this.issuable = issuable;
    }

    public String getIssueType() {
        return this.issueType;
    }
    
    public void setIssueType(String issueType) {
        this.issueType = issueType;
    }

    public int getDefaultValidPeriod() {
        return this.defaultValidPeriod;
    }
    
    public void setDefaultValidPeriod(int defaultValidPeriod) {
    	this.defaultValidPeriod = defaultValidPeriod;
    }

    public String getInterfaceMappingValue() {
        return this.interfaceMappingValue;
    }
    
    public void setInterfaceMappingValue(String interfaceMappingValue) {
        this.interfaceMappingValue = interfaceMappingValue;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public BigDecimal getReplacementFees() {
        return this.replacementFees;
    }
    
    public void setReplacementFees(BigDecimal replacementFees) {
        this.replacementFees = replacementFees;
    }

    public String getLoginRegistration() {
        return this.loginRegistration;
    }
    
    public void setLoginRegistration(String loginRegistration) {
        this.loginRegistration = loginRegistration;
    }

    public String getHotel() {
        return this.hotel;
    }
    
    public void setHotel(String hotel) {
        this.hotel = hotel;
    }
    
    public String getPrepaid() {
		return prepaid;
	}

	public void setPrepaid(String prepaid) {
		this.prepaid = prepaid;
	}
	
	public String getContactless() {
		return contactless;
	}

	public void setContactless(String contactless) {
		this.contactless = contactless;
	}
	public String getCardless() {
		return cardless;
	}

	public void setCardless(String cardless) {
		this.cardless = cardless;
	}
	
	public String getVirtualProduct() {
		return virtualProduct;
	}

	public void setVirtualProduct(String virtualProduct) {
		this.virtualProduct = virtualProduct;
	}
	
	public String getViewPastTxn() {
		return viewPastTxn;
	}

	public void setViewPastTxn(String viewPastTxn) {
		this.viewPastTxn = viewPastTxn;
	}
	
	public Integer getDefaultBalanceExpMonths() {
		return defaultBalanceExpMonths;
	}

	public BigDecimal getTopUpFee() {
		return topUpFee;
	}

	public BigDecimal getTransferFee() {
		return transferFee;
	}

	public void setDefaultBalanceExpMonths(Integer defaultBalanceExpMonths) {
		this.defaultBalanceExpMonths = defaultBalanceExpMonths;
	}

	public void setTopUpFee(BigDecimal topUpFee) {
		this.topUpFee = topUpFee;
	}

	public void setTransferFee(BigDecimal transferFee) {
		this.transferFee = transferFee;
	}

	public MstbMasterTable getMstbMasterTableBySMSFormat() {
		return mstbMasterTableBySMSFormat;
	}

	public void setMstbMasterTableBySMSFormat(MstbMasterTable mstbMasterTableBySMSFormat) {
		this.mstbMasterTableBySMSFormat = mstbMasterTableBySMSFormat;
	}
	
	public MstbMasterTable getMstbMasterTableBySMSExpiryFormat() {
		return mstbMasterTableBySMSExpiryFormat;
	}

	public void setMstbMasterTableBySMSExpiryFormat(MstbMasterTable mstbMasterTableBySMSExpiryFormat) {
		this.mstbMasterTableBySMSExpiryFormat = mstbMasterTableBySMSExpiryFormat;
	}

	public MstbMasterTable getMstbMasterTableBySMSTopupFormat() {
		return mstbMasterTableBySMSTopupFormat;
	}

	public void setMstbMasterTableBySMSTopupFormat(MstbMasterTable mstbMasterTableBySMSTopupFormat) {
		this.mstbMasterTableBySMSTopupFormat = mstbMasterTableBySMSTopupFormat;
	}

	public Set<AmtbApplicationProduct> getAmtbApplicationProducts() {
        return this.amtbApplicationProducts;
    }
    
    public void setAmtbApplicationProducts(Set<AmtbApplicationProduct> amtbApplicationProducts) {
        this.amtbApplicationProducts = amtbApplicationProducts;
    }

    public Set<BmtbInvoiceDetail> getBmtbInvoiceDetails() {
        return this.bmtbInvoiceDetails;
    }
    
    public void setBmtbInvoiceDetails(Set<BmtbInvoiceDetail> bmtbInvoiceDetails) {
        this.bmtbInvoiceDetails = bmtbInvoiceDetails;
    }

    public Set<TmtbTxnReviewReq> getTmtbTxnReviewReqs() {
        return this.tmtbTxnReviewReqs;
    }
    
    public void setTmtbTxnReviewReqs(Set<TmtbTxnReviewReq> tmtbTxnReviewReqs) {
        this.tmtbTxnReviewReqs = tmtbTxnReviewReqs;
    }

    public Set<TmtbAcquireTxn> getTmtbAcquireTxns() {
        return this.tmtbAcquireTxns;
    }
    
    public void setTmtbAcquireTxns(Set<TmtbAcquireTxn> tmtbAcquireTxns) {
        this.tmtbAcquireTxns = tmtbAcquireTxns;
    }

    public Set<FmtbTransactionCode> getFmtbTransactionCodes() {
        return this.fmtbTransactionCodes;
    }
    
    public void setFmtbTransactionCodes(Set<FmtbTransactionCode> fmtbTransactionCodes) {
        this.fmtbTransactionCodes = fmtbTransactionCodes;
    }

    public Set<PmtbProduct> getPmtbProducts() {
        return this.pmtbProducts;
    }
    
    public void setPmtbProducts(Set<PmtbProduct> pmtbProducts) {
        this.pmtbProducts = pmtbProducts;
    }

    public Set<AmtbSubscTo> getAmtbSubscTos() {
        return this.amtbSubscTos;
    }
    
    public void setAmtbSubscTos(Set<AmtbSubscTo> amtbSubscTos) {
        this.amtbSubscTos = amtbSubscTos;
    }

    public Set<BmtbInvoiceSummary> getBmtbInvoiceSummaries() {
        return this.bmtbInvoiceSummaries;
    }
    
    public void setBmtbInvoiceSummaries(Set<BmtbInvoiceSummary> bmtbInvoiceSummaries) {
        this.bmtbInvoiceSummaries = bmtbInvoiceSummaries;
    }

    public Set<AmtbAcctType> getAmtbAcctTypes() {
        return this.amtbAcctTypes;
    }
    
    public void setAmtbAcctTypes(Set<AmtbAcctType> amtbAcctTypes) {
        this.amtbAcctTypes = amtbAcctTypes;
    }

    public Set<AmtbAccount> getAmtbAccounts() {
        return this.amtbAccounts;
    }
    
    public void setAmtbAccounts(Set<AmtbAccount> amtbAccounts) {
        this.amtbAccounts = amtbAccounts;
    }
   
    public Integer getMinTopupLimit() {
    	return minTopupLimit;
    }

    public Integer getMaxTopupLimit() {
    	return maxTopupLimit;
    }

    public void setMinTopupLimit(Integer minTopupLimit) {
    	this.minTopupLimit = minTopupLimit;
    }

    public void setMaxTopupLimit(Integer maxTopupLimit) {
    	this.maxTopupLimit = maxTopupLimit;
    }   
    
    

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("name").append("='").append(getName()).append("' ");			
      buffer.append("batchIssue").append("='").append(getBatchIssue()).append("' ");			
      buffer.append("nameOnProduct").append("='").append(getNameOnProduct()).append("' ");			
      buffer.append("luhnCheck").append("='").append(getLuhnCheck()).append("' ");			
      buffer.append("oneTimeUsage").append("='").append(getOneTimeUsage()).append("' ");			
      buffer.append("fixedValue").append("='").append(getFixedValue()).append("' ");			
      buffer.append("creditLimit").append("='").append(getCreditLimit()).append("' ");			
      buffer.append("validityPeriod").append("='").append(getValidityPeriod()).append("' ");			
      buffer.append("defaultCardStatus").append("='").append(getDefaultCardStatus()).append("' ");			
      buffer.append("numberOfDigit").append("='").append(getNumberOfDigit()).append("' ");		
      buffer.append("minTopupLimit").append("='").append(getMinTopupLimit()).append("' ");		
      buffer.append("maxTopupLimit").append("='").append(getMaxTopupLimit()).append("' ");		
      buffer.append("binRange").append("='").append(getBinRange()).append("' ");			
      buffer.append("subBinRange").append("='").append(getSubBinRange()).append("' ");			
      buffer.append("externalCard").append("='").append(getExternalCard()).append("' ");			
      buffer.append("issuable").append("='").append(getIssuable()).append("' ");			
      buffer.append("issueType").append("='").append(getIssueType()).append("' ");			
      buffer.append("defaultValidPeriod").append("='").append(getDefaultValidPeriod()).append("' ");			
      buffer.append("interfaceMappingValue").append("='").append(getInterfaceMappingValue()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("replacementFees").append("='").append(getReplacementFees()).append("' ");
      buffer.append("loginRegistration").append("='").append(getLoginRegistration()).append("' ");			
      buffer.append("hotel").append("='").append(getHotel()).append("' ");
      buffer.append("prepaid").append("='").append(getPrepaid()).append("' ");
      buffer.append("contactless").append("='").append(getContactless()).append("' ");
      buffer.append("cardless").append("='").append(getCardless()).append("' ");
      buffer.append("virtualProduct").append("='").append(getVirtualProduct()).append("' ");
      buffer.append("viewPastTxn").append("='").append(getViewPastTxn()).append("' ");
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PmtbProductType) ) return false;
		 PmtbProductType castOther = ( PmtbProductType ) other; 
         
		 return ( (this.getProductTypeId()==castOther.getProductTypeId()) || ( this.getProductTypeId()!=null && castOther.getProductTypeId()!=null && this.getProductTypeId().equals(castOther.getProductTypeId()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getBatchIssue()==castOther.getBatchIssue()) || ( this.getBatchIssue()!=null && castOther.getBatchIssue()!=null && this.getBatchIssue().equals(castOther.getBatchIssue()) ) )
 && ( (this.getNameOnProduct()==castOther.getNameOnProduct()) || ( this.getNameOnProduct()!=null && castOther.getNameOnProduct()!=null && this.getNameOnProduct().equals(castOther.getNameOnProduct()) ) )
 && ( (this.getLuhnCheck()==castOther.getLuhnCheck()) || ( this.getLuhnCheck()!=null && castOther.getLuhnCheck()!=null && this.getLuhnCheck().equals(castOther.getLuhnCheck()) ) )
 && ( (this.getOneTimeUsage()==castOther.getOneTimeUsage()) || ( this.getOneTimeUsage()!=null && castOther.getOneTimeUsage()!=null && this.getOneTimeUsage().equals(castOther.getOneTimeUsage()) ) )
 && ( (this.getFixedValue()==castOther.getFixedValue()) || ( this.getFixedValue()!=null && castOther.getFixedValue()!=null && this.getFixedValue().equals(castOther.getFixedValue()) ) )
 && ( (this.getCreditLimit()==castOther.getCreditLimit()) || ( this.getCreditLimit()!=null && castOther.getCreditLimit()!=null && this.getCreditLimit().equals(castOther.getCreditLimit()) ) )
 && ( (this.getValidityPeriod()==castOther.getValidityPeriod()) || ( this.getValidityPeriod()!=null && castOther.getValidityPeriod()!=null && this.getValidityPeriod().equals(castOther.getValidityPeriod()) ) )
 && ( (this.getDefaultCardStatus()==castOther.getDefaultCardStatus()) || ( this.getDefaultCardStatus()!=null && castOther.getDefaultCardStatus()!=null && this.getDefaultCardStatus().equals(castOther.getDefaultCardStatus()) ) )
 && (this.getNumberOfDigit()==castOther.getNumberOfDigit())
 && ( (this.getMinTopupLimit()==castOther.getMinTopupLimit()) || ( this.getMinTopupLimit()!=null && castOther.getMinTopupLimit()!=null && this.getMinTopupLimit().equals(castOther.getMinTopupLimit()) ) )
 && ( (this.getMaxTopupLimit()==castOther.getMaxTopupLimit()) || ( this.getMaxTopupLimit()!=null && castOther.getMaxTopupLimit()!=null && this.getMaxTopupLimit().equals(castOther.getMaxTopupLimit()) ) )
 && ( (this.getBinRange()==castOther.getBinRange()) || ( this.getBinRange()!=null && castOther.getBinRange()!=null && this.getBinRange().equals(castOther.getBinRange()) ) )
 && ( (this.getSubBinRange()==castOther.getSubBinRange()) || ( this.getSubBinRange()!=null && castOther.getSubBinRange()!=null && this.getSubBinRange().equals(castOther.getSubBinRange()) ) )
 && ( (this.getExternalCard()==castOther.getExternalCard()) || ( this.getExternalCard()!=null && castOther.getExternalCard()!=null && this.getExternalCard().equals(castOther.getExternalCard()) ) )
 && ( (this.getIssuable()==castOther.getIssuable()) || ( this.getIssuable()!=null && castOther.getIssuable()!=null && this.getIssuable().equals(castOther.getIssuable()) ) )
 && ( (this.getIssueType()==castOther.getIssueType()) || ( this.getIssueType()!=null && castOther.getIssueType()!=null && this.getIssueType().equals(castOther.getIssueType()) ) )
 && (this.getDefaultValidPeriod()==castOther.getDefaultValidPeriod())
 && ( (this.getInterfaceMappingValue()==castOther.getInterfaceMappingValue()) || ( this.getInterfaceMappingValue()!=null && castOther.getInterfaceMappingValue()!=null && this.getInterfaceMappingValue().equals(castOther.getInterfaceMappingValue()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getReplacementFees()==castOther.getReplacementFees()) || ( this.getReplacementFees()!=null && castOther.getReplacementFees()!=null && this.getReplacementFees().equals(castOther.getReplacementFees()) ) )
 && ( (this.getLoginRegistration()==castOther.getLoginRegistration()) || ( this.getLoginRegistration()!=null && castOther.getLoginRegistration()!=null && this.getLoginRegistration().equals(castOther.getLoginRegistration()) ) )
 && ( (this.getHotel()==castOther.getHotel()) || ( this.getHotel()!=null && castOther.getHotel()!=null && this.getHotel().equals(castOther.getHotel()) ) )
 && ( (this.getPrepaid()==castOther.getPrepaid()) || ( this.getPrepaid()!=null && castOther.getPrepaid()!=null && this.getPrepaid().equals(castOther.getPrepaid()) ) )
 && ( (this.getContactless()==castOther.getContactless()) || ( this.getContactless()!=null && castOther.getContactless()!=null && this.getContactless().equals(castOther.getContactless()) ) )
 && ( (this.getCardless()==castOther.getCardless()) || ( this.getCardless()!=null && castOther.getCardless()!=null && this.getCardless().equals(castOther.getCardless()) ) )
 && ( (this.getVirtualProduct()==castOther.getVirtualProduct()) || ( this.getVirtualProduct()!=null && castOther.getVirtualProduct()!=null && this.getVirtualProduct().equals(castOther.getVirtualProduct()) ) )
 && ( (this.getViewPastTxn()==castOther.getViewPastTxn()) || ( this.getViewPastTxn()!=null && castOther.getViewPastTxn()!=null && this.getViewPastTxn().equals(castOther.getViewPastTxn()) ) );
 //&& ( (this.getMstbMasterTableBySMSFormat()==castOther.getMstbMasterTableBySMSFormat()) || ( this.getMstbMasterTableBySMSFormat()!=null && castOther.getMstbMasterTableBySMSFormat()!=null && this.getMstbMasterTableBySMSFormat().equals(castOther.getMstbMasterTableBySMSFormat()) ) )
 //&& ( (this.getMstbMasterTableBySMSExpiryFormat()==castOther.getMstbMasterTableBySMSExpiryFormat()) || ( this.getMstbMasterTableBySMSExpiryFormat()!=null && castOther.getMstbMasterTableBySMSExpiryFormat()!=null && this.getMstbMasterTableBySMSExpiryFormat().equals(castOther.getMstbMasterTableBySMSExpiryFormat()) ) )
 //&& ( (this.getMstbMasterTableBySMSTopupFormat()==castOther.getMstbMasterTableBySMSTopupFormat()) || ( this.getMstbMasterTableBySMSTopupFormat()!=null && castOther.getMstbMasterTableBySMSTopupFormat()!=null && this.getMstbMasterTableBySMSTopupFormat().equals(castOther.getMstbMasterTableBySMSTopupFormat()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProductTypeId() == null ? 0 : this.getProductTypeId().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getBatchIssue() == null ? 0 : this.getBatchIssue().hashCode() );
         result = 37 * result + ( getNameOnProduct() == null ? 0 : this.getNameOnProduct().hashCode() );
         result = 37 * result + ( getLuhnCheck() == null ? 0 : this.getLuhnCheck().hashCode() );
         result = 37 * result + ( getOneTimeUsage() == null ? 0 : this.getOneTimeUsage().hashCode() );
         result = 37 * result + ( getFixedValue() == null ? 0 : this.getFixedValue().hashCode() );
         result = 37 * result + ( getCreditLimit() == null ? 0 : this.getCreditLimit().hashCode() );
         result = 37 * result + ( getValidityPeriod() == null ? 0 : this.getValidityPeriod().hashCode() );
         result = 37 * result + ( getDefaultCardStatus() == null ? 0 : this.getDefaultCardStatus().hashCode() );
         result = 37 * result + this.getNumberOfDigit();
         result = 37 * result + ( getMinTopupLimit() == null ? 0 : this.getMinTopupLimit().hashCode() );
         result = 37 * result + ( getMaxTopupLimit() == null ? 0 : this.getMaxTopupLimit().hashCode() );
         result = 37 * result + ( getBinRange() == null ? 0 : this.getBinRange().hashCode() );
         result = 37 * result + ( getSubBinRange() == null ? 0 : this.getSubBinRange().hashCode() );
         result = 37 * result + ( getExternalCard() == null ? 0 : this.getExternalCard().hashCode() );
         result = 37 * result + ( getIssuable() == null ? 0 : this.getIssuable().hashCode() );
         result = 37 * result + ( getIssueType() == null ? 0 : this.getIssueType().hashCode() );
         result = 37 * result + this.getDefaultValidPeriod();
         result = 37 * result + ( getInterfaceMappingValue() == null ? 0 : this.getInterfaceMappingValue().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getReplacementFees() == null ? 0 : this.getReplacementFees().hashCode() );
         result = 37 * result + ( getLoginRegistration() == null ? 0 : this.getLoginRegistration().hashCode() );
         result = 37 * result + ( getHotel() == null ? 0 : this.getHotel().hashCode() );
         result = 37 * result + ( getPrepaid() == null ? 0 : this.getPrepaid().hashCode() );
         result = 37 * result + ( getContactless() == null ? 0 : this.getContactless().hashCode() );
         result = 37 * result + ( getCardless() == null ? 0 : this.getCardless().hashCode() );
         result = 37 * result + ( getVirtualProduct() == null ? 0 : this.getVirtualProduct().hashCode() );
         result = 37 * result + ( getViewPastTxn() == null ? 0 : this.getViewPastTxn().hashCode() );
         // comment due to lazy init
         //result = 37 * result + ( getMstbMasterTableBySMSFormat() == null ? 0 : this.getMstbMasterTableBySMSFormat().hashCode() );
         return result;
   }


}