package com.cdgtaxi.ibs.common.model;
// Generated Oct 9, 2009 11:56:37 AM by Hibernate Tools 3.1.0.beta4



/**
 * TempAcctMapping generated by hbm2java
 */

public class TempAcctMapping  implements java.io.Serializable {


    // Fields    

    private String oldCustNo;
    private String newCustNo;


    // Constructors

    /** default constructor */
    public TempAcctMapping() {
    }

    
    /** full constructor */
    public TempAcctMapping(String newCustNo) {
        this.newCustNo = newCustNo;
    }
    

   
    // Property accessors

    public String getOldCustNo() {
        return this.oldCustNo;
    }
    
    public void setOldCustNo(String oldCustNo) {
        this.oldCustNo = oldCustNo;
    }

    public String getNewCustNo() {
        return this.newCustNo;
    }
    
    public void setNewCustNo(String newCustNo) {
        this.newCustNo = newCustNo;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("newCustNo").append("='").append(getNewCustNo()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TempAcctMapping) ) return false;
		 TempAcctMapping castOther = ( TempAcctMapping ) other; 
         
		 return ( (this.getOldCustNo()==castOther.getOldCustNo()) || ( this.getOldCustNo()!=null && castOther.getOldCustNo()!=null && this.getOldCustNo().equals(castOther.getOldCustNo()) ) )
 && ( (this.getNewCustNo()==castOther.getNewCustNo()) || ( this.getNewCustNo()!=null && castOther.getNewCustNo()!=null && this.getNewCustNo().equals(castOther.getNewCustNo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getOldCustNo() == null ? 0 : this.getOldCustNo().hashCode() );
         result = 37 * result + ( getNewCustNo() == null ? 0 : this.getNewCustNo().hashCode() );
         return result;
   }   





}
