package com.cdgtaxi.ibs.common.model;
// Generated May 4, 2010 3:35:26 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.master.model.MstbAcquirerPymtType;
import com.cdgtaxi.ibs.master.model.MstbMasterTable;


/**
 * TmtbNonBillableTxn generated by hbm2java
 */

@SuppressWarnings("serial")
public class TmtbNonBillableTxn implements java.io.Serializable, Auditable, Updatable, Creatable {

    // Fields    

    private Long txnId;
    private BigDecimal txnNo;
    private String status;
    private String jobNo;
    private String taxiNo;
    private String nric;
    private Timestamp tripStartDt;
    private Timestamp tripEndDt;
    private String cardNo;
    private BigDecimal fareAmt;
    private BigDecimal adminFee;
    private BigDecimal gst;
    private BigDecimal total;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private Integer version;
    private String remarks;
    private Date chargebackRefundDate;
    private String pickupAddress;
    private String destination;
    private BigDecimal levy;
    private String updateFms;
    private BigDecimal fmsAmt;
    private BigDecimal incentiveAmt;
    private BigDecimal promoAmt;
    private String fmsFlag;
    private BigDecimal chargebackRefundFareAmt;
    private BigDecimal chargebackRefundAdminFee;
    private BigDecimal chargebackRefundGst;
    private String offlineFlag;
    private MstbAcquirerPymtType mstbAcquirerPymtType;
    private TmtbNonBillableBatch tmtbNonBillableBatch;
    private MstbMasterTable mstbMasterTableByChargebackRefundReason;
    private MstbMasterTable mstbMasterTableByServiceProvider;
    private MstbMasterTable mstbMasterTableByChargebackType;
    private MstbMasterTable mstbMasterTableByJobType;

    private BigDecimal commissionAmt;
    private String commissionType;
    private BigDecimal commissionValue;

    private BigDecimal cabRewardsAmt;
    private String productId;

    private String pspRefNo1;//does not follow hibernate mapping due to business constraint
    private String pspRefNo2;
    private Set<TmtbNonBillableTxnCrca> tmtbNonBillableTxnCrca1 = new HashSet<TmtbNonBillableTxnCrca>(0);
    private Set<TmtbNonBillableTxnCrca> tmtbNonBillableTxnCrca2 = new HashSet<TmtbNonBillableTxnCrca>(0);
    private BigDecimal txnAmount1;
    private BigDecimal txnAmount2;
    private String matchingStatus;
    private String source;

    private String policyNumber;
    private Date startOfInsurance;
    private Date endOfInsurance;
    private BigDecimal premiumAmount;
    private BigDecimal premiumGst;
    private String policyStatus;
    
    // Constructors

    /**
     * default constructor
     */
    public TmtbNonBillableTxn() {
    }

    /**
     * minimal constructor
     */
    public TmtbNonBillableTxn(String status, String jobNo, String taxiNo, Timestamp tripStartDt, BigDecimal fareAmt, BigDecimal adminFee, BigDecimal gst, BigDecimal total) {
        this.status = status;
        this.jobNo = jobNo;
        this.taxiNo = taxiNo;
        this.tripStartDt = tripStartDt;
        this.fareAmt = fareAmt;
        this.adminFee = adminFee;
        this.gst = gst;
        this.total = total;
    }

    /**
     * full constructor
     */
    public TmtbNonBillableTxn(Long txnId, String status, String jobNo, String taxiNo, String nric, Timestamp tripStartDt, Timestamp tripEndDt, String cardNo, BigDecimal fareAmt, BigDecimal adminFee, BigDecimal gst, BigDecimal total, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, Integer version, String remarks, Date chargebackRefundDate, String pickupAddress, String destination, BigDecimal levy, String updateFms, BigDecimal fmsAmt, BigDecimal incentiveAmt, BigDecimal promoAmt, String fmsFlag, BigDecimal chargebackRefundFareAmt, BigDecimal chargebackRefundAdminFee, BigDecimal chargebackRefundGst, String offlineFlag, MstbAcquirerPymtType mstbAcquirerPymtType, TmtbNonBillableBatch tmtbNonBillableBatch, MstbMasterTable mstbMasterTableByChargebackRefundReason, MstbMasterTable mstbMasterTableByServiceProvider, MstbMasterTable mstbMasterTableByChargebackType, MstbMasterTable mstbMasterTableByJobType, BigDecimal commissionAmt, String commissionType, BigDecimal commissionValue, BigDecimal cabRewardsAmt, String productId, String pspRefNo1, String pspRefNo2, Set<TmtbNonBillableTxnCrca> tmtbNonBillableTxnCrca1, Set<TmtbNonBillableTxnCrca> tmtbNonBillableTxnCrca2, BigDecimal txnAmount1, BigDecimal txnAmount2, String matchingStatus, String source,
    		 String policyNumber, Date startOfInsurance, Date endOfInsurance, BigDecimal premiumAmount, BigDecimal premiumGst, String policyStatus) {
        this.txnId = txnId;
        this.status = status;
        this.jobNo = jobNo;
        this.taxiNo = taxiNo;
        this.nric = nric;
        this.tripStartDt = tripStartDt;
        this.tripEndDt = tripEndDt;
        this.cardNo = cardNo;
        this.fareAmt = fareAmt;
        this.adminFee = adminFee;
        this.gst = gst;
        this.total = total;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.version = version;
        this.remarks = remarks;
        this.chargebackRefundDate = chargebackRefundDate;
        this.pickupAddress = pickupAddress;
        this.destination = destination;
        this.levy = levy;
        this.updateFms = updateFms;
        this.fmsAmt = fmsAmt;
        this.incentiveAmt = incentiveAmt;
        this.promoAmt = promoAmt;
        this.fmsFlag = fmsFlag;
        this.chargebackRefundFareAmt = chargebackRefundFareAmt;
        this.chargebackRefundAdminFee = chargebackRefundAdminFee;
        this.chargebackRefundGst = chargebackRefundGst;
        this.offlineFlag = offlineFlag;
        this.mstbAcquirerPymtType = mstbAcquirerPymtType;
        this.tmtbNonBillableBatch = tmtbNonBillableBatch;
        this.mstbMasterTableByChargebackRefundReason = mstbMasterTableByChargebackRefundReason;
        this.mstbMasterTableByServiceProvider = mstbMasterTableByServiceProvider;
        this.mstbMasterTableByChargebackType = mstbMasterTableByChargebackType;
        this.mstbMasterTableByJobType = mstbMasterTableByJobType;
        this.commissionAmt = commissionAmt;
        this.commissionType = commissionType;
        this.commissionValue = commissionValue;
        this.cabRewardsAmt = cabRewardsAmt;
        this.productId = productId;
        this.pspRefNo1 = pspRefNo1;
        this.pspRefNo2 = pspRefNo2;
        this.tmtbNonBillableTxnCrca1 = tmtbNonBillableTxnCrca1;
        this.tmtbNonBillableTxnCrca2 = tmtbNonBillableTxnCrca2;
        this.txnAmount1 = txnAmount1;
        this.txnAmount2 = txnAmount2;
        this.matchingStatus = matchingStatus;
        this.source = source;
        this.policyNumber = policyNumber;
        this.startOfInsurance = startOfInsurance;
        this.endOfInsurance = endOfInsurance;
        this.premiumAmount = premiumAmount;
        this.premiumGst = premiumGst;
        this.policyStatus = policyStatus;
    }

    // Property accessors

    public String getOfflineFlag() {
        return offlineFlag;
    }

    public void setOfflineFlag(String offlineFlag) {
        this.offlineFlag = offlineFlag;
    }

    public Long getTxnId() {
        return this.txnId;
    }

    public void setTxnId(Long txnId) {
        this.txnId = txnId;
    }

    public BigDecimal getTxnNo() {
        return txnNo;
    }

    public void setTxnNo(BigDecimal txnNo) {
        this.txnNo = txnNo;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getJobNo() {
        return this.jobNo;
    }

    public void setJobNo(String jobNo) {
        this.jobNo = jobNo;
    }

    public String getTaxiNo() {
        return this.taxiNo;
    }

    public void setTaxiNo(String taxiNo) {
        this.taxiNo = taxiNo;
    }

    public String getNric() {
        return this.nric;
    }

    public void setNric(String nric) {
        this.nric = nric;
    }

    public Timestamp getTripStartDt() {
        return this.tripStartDt;
    }

    public void setTripStartDt(Timestamp tripStartDt) {
        this.tripStartDt = tripStartDt;
    }

    public Timestamp getTripEndDt() {
        return this.tripEndDt;
    }

    public void setTripEndDt(Timestamp tripEndDt) {
        this.tripEndDt = tripEndDt;
    }

    public String getCardNo() {
        return this.cardNo;
    }

    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    public BigDecimal getFareAmt() {
        return this.fareAmt;
    }

    public void setFareAmt(BigDecimal fareAmt) {
        this.fareAmt = fareAmt;
    }

    public BigDecimal getAdminFee() {
        return this.adminFee;
    }

    public void setAdminFee(BigDecimal adminFee) {
        this.adminFee = adminFee;
    }

    public BigDecimal getGst() {
        return this.gst;
    }

    public void setGst(BigDecimal gst) {
        this.gst = gst;
    }

    public BigDecimal getTotal() {
        return this.total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }

    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }

    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public Date getChargebackRefundDate() {
        return this.chargebackRefundDate;
    }

    public void setChargebackRefundDate(Date chargebackRefundDate) {
        this.chargebackRefundDate = chargebackRefundDate;
    }

    public String getPickupAddress() {
        return this.pickupAddress;
    }

    public void setPickupAddress(String pickupAddress) {
        this.pickupAddress = pickupAddress;
    }

    public String getDestination() {
        return this.destination;
    }

    public void setDestination(String destination) {
        this.destination = destination;
    }

    public BigDecimal getLevy() {
        return this.levy;
    }

    public void setLevy(BigDecimal levy) {
        this.levy = levy;
    }

    public String getUpdateFms() {
        return this.updateFms;
    }

    public void setUpdateFms(String updateFms) {
        this.updateFms = updateFms;
    }

    public BigDecimal getFmsAmt() {
        return this.fmsAmt;
    }

    public void setFmsAmt(BigDecimal fmsAmt) {
        this.fmsAmt = fmsAmt;
    }

    public BigDecimal getIncentiveAmt() {
        return this.incentiveAmt;
    }

    public void setIncentiveAmt(BigDecimal incentiveAmt) {
        this.incentiveAmt = incentiveAmt;
    }

    public BigDecimal getPromoAmt() {
        return this.promoAmt;
    }

    public void setPromoAmt(BigDecimal promoAmt) {
        this.promoAmt = promoAmt;
    }

    public BigDecimal getCabRewardsAmt() {
        return this.cabRewardsAmt;
    }

    public void setCabRewardsAmt(BigDecimal cabRewardsAmt) {
        this.cabRewardsAmt = cabRewardsAmt;
    }

    public String getFmsFlag() {
        return this.fmsFlag;
    }

    public void setFmsFlag(String fmsFlag) {
        this.fmsFlag = fmsFlag;
    }

    public BigDecimal getChargebackRefundFareAmt() {
        return this.chargebackRefundFareAmt;
    }

    public void setChargebackRefundFareAmt(BigDecimal chargebackRefundFareAmt) {
        this.chargebackRefundFareAmt = chargebackRefundFareAmt;
    }

    public BigDecimal getChargebackRefundAdminFee() {
        return this.chargebackRefundAdminFee;
    }

    public void setChargebackRefundAdminFee(BigDecimal chargebackRefundAdminFee) {
        this.chargebackRefundAdminFee = chargebackRefundAdminFee;
    }

    public BigDecimal getChargebackRefundGst() {
        return this.chargebackRefundGst;
    }

    public void setChargebackRefundGst(BigDecimal chargebackRefundGst) {
        this.chargebackRefundGst = chargebackRefundGst;
    }

    public MstbAcquirerPymtType getMstbAcquirerPymtType() {
        return this.mstbAcquirerPymtType;
    }

    public void setMstbAcquirerPymtType(MstbAcquirerPymtType mstbAcquirerPymtType) {
        this.mstbAcquirerPymtType = mstbAcquirerPymtType;
    }

    public TmtbNonBillableBatch getTmtbNonBillableBatch() {
        return this.tmtbNonBillableBatch;
    }

    public void setTmtbNonBillableBatch(TmtbNonBillableBatch tmtbNonBillableBatch) {
        this.tmtbNonBillableBatch = tmtbNonBillableBatch;
    }

    public MstbMasterTable getMstbMasterTableByChargebackRefundReason() {
        return this.mstbMasterTableByChargebackRefundReason;
    }

    public void setMstbMasterTableByChargebackRefundReason(MstbMasterTable mstbMasterTableByChargebackRefundReason) {
        this.mstbMasterTableByChargebackRefundReason = mstbMasterTableByChargebackRefundReason;
    }

    public MstbMasterTable getMstbMasterTableByServiceProvider() {
        return this.mstbMasterTableByServiceProvider;
    }

    public void setMstbMasterTableByServiceProvider(MstbMasterTable mstbMasterTableByServiceProvider) {
        this.mstbMasterTableByServiceProvider = mstbMasterTableByServiceProvider;
    }

    public MstbMasterTable getMstbMasterTableByChargebackType() {
        return this.mstbMasterTableByChargebackType;
    }

    public void setMstbMasterTableByChargebackType(MstbMasterTable mstbMasterTableByChargebackType) {
        this.mstbMasterTableByChargebackType = mstbMasterTableByChargebackType;
    }

    public MstbMasterTable getMstbMasterTableByJobType() {
        return this.mstbMasterTableByJobType;
    }

    public void setMstbMasterTableByJobType(MstbMasterTable mstbMasterTableByJobType) {
        this.mstbMasterTableByJobType = mstbMasterTableByJobType;
    }

    public BigDecimal getCommissionAmt() {
        return commissionAmt;
    }

    public void setCommissionAmt(BigDecimal commissionAmt) {
        this.commissionAmt = commissionAmt;
    }

    public String getCommissionType() {
        return commissionType;
    }

    public void setCommissionType(String commissionType) {
        this.commissionType = commissionType;
    }

    public BigDecimal getCommissionValue() {
        return commissionValue;
    }

    public void setCommissionValue(BigDecimal commissionValue) {
        this.commissionValue = commissionValue;
    }

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public Set<TmtbNonBillableTxnCrca> getTmtbNonBillableTxnCrca1() {
        return tmtbNonBillableTxnCrca1;
    }

    public void setTmtbNonBillableTxnCrca1(Set<TmtbNonBillableTxnCrca> tmtbNonBillableTxnCrca1) {
        this.tmtbNonBillableTxnCrca1 = tmtbNonBillableTxnCrca1;
    }

    public Set<TmtbNonBillableTxnCrca> getTmtbNonBillableTxnCrca2() {
        return tmtbNonBillableTxnCrca2;
    }

    public void setTmtbNonBillableTxnCrca2(Set<TmtbNonBillableTxnCrca> tmtbNonBillableTxnCrca2) {
        this.tmtbNonBillableTxnCrca2 = tmtbNonBillableTxnCrca2;
    }

    public String getPspRefNo1() {
        return pspRefNo1;
    }

    public void setPspRefNo1(String pspRefNo1) {
        this.pspRefNo1 = pspRefNo1;
    }

    public String getPspRefNo2() {
        return pspRefNo2;
    }

    public void setPspRefNo2(String pspRefNo2) {
        this.pspRefNo2 = pspRefNo2;
    }

    public BigDecimal getTxnAmount1() {
        return txnAmount1;
    }

    public void setTxnAmount1(BigDecimal txnAmount1) {
        this.txnAmount1 = txnAmount1;
    }

    public BigDecimal getTxnAmount2() {
        return txnAmount2;
    }

    public void setTxnAmount2(BigDecimal txnAmount2) {
        this.txnAmount2 = txnAmount2;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getMatchingStatus() {
        return matchingStatus;
    }

    public void setMatchingStatus(String matchingStatus) {
        this.matchingStatus = matchingStatus;
    }
    public String getPolicyNumber() {
		return policyNumber;
	}

	public void setPolicyNumber(String policyNumber) {
		this.policyNumber = policyNumber;
	}

	public Date getStartOfInsurance() {
		return startOfInsurance;
	}

	public void setStartOfInsurance(Date startOfInsurance) {
		this.startOfInsurance = startOfInsurance;
	}

	public Date getEndOfInsurance() {
		return endOfInsurance;
	}

	public void setEndOfInsurance(Date endOfInsurance) {
		this.endOfInsurance = endOfInsurance;
	}

	public BigDecimal getPremiumAmount() {
		return premiumAmount;
	}

	public void setPremiumAmount(BigDecimal premiumAmount) {
		this.premiumAmount = premiumAmount;
	}

	public BigDecimal getPremiumGst() {
		return premiumGst;
	}

	public void setPremiumGst(BigDecimal premiumGst) {
		this.premiumGst = premiumGst;
	}

	public String getPolicyStatus() {
		return policyStatus;
	}

	public void setPolicyStatus(String policyStatus) {
		this.policyStatus = policyStatus;
	}
    /**
     * toString
     *
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("txnNo").append("='").append(getTxnNo()).append("' ");
        buffer.append("status").append("='").append(getStatus()).append("' ");
        buffer.append("jobNo").append("='").append(getJobNo()).append("' ");
        buffer.append("taxiNo").append("='").append(getTaxiNo()).append("' ");
        buffer.append("nric").append("='").append(getNric()).append("' ");
        buffer.append("tripStartDt").append("='").append(getTripStartDt()).append("' ");
        buffer.append("tripEndDt").append("='").append(getTripEndDt()).append("' ");
        buffer.append("cardNo").append("='").append(getCardNo()).append("' ");
        buffer.append("fareAmt").append("='").append(getFareAmt()).append("' ");
        buffer.append("adminFee").append("='").append(getAdminFee()).append("' ");
        buffer.append("gst").append("='").append(getGst()).append("' ");
        buffer.append("total").append("='").append(getTotal()).append("' ");
        buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");
        buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");
        buffer.append("version").append("='").append(getVersion()).append("' ");
        buffer.append("remarks").append("='").append(getRemarks()).append("' ");
        buffer.append("chargebackRefundDate").append("='").append(getChargebackRefundDate()).append("' ");
        buffer.append("pickupAddress").append("='").append(getPickupAddress()).append("' ");
        buffer.append("destination").append("='").append(getDestination()).append("' ");
        buffer.append("levy").append("='").append(getLevy()).append("' ");
        buffer.append("updateFms").append("='").append(getUpdateFms()).append("' ");
        buffer.append("fmsAmt").append("='").append(getFmsAmt()).append("' ");
        buffer.append("incentiveAmt").append("='").append(getIncentiveAmt()).append("' ");
        buffer.append("promoAmt").append("='").append(getPromoAmt()).append("' ");
        buffer.append("cabRewardsAmt").append("='").append(getCabRewardsAmt()).append("' ");
        buffer.append("fmsFlag").append("='").append(getFmsFlag()).append("' ");
        buffer.append("chargebackRefundFareAmt").append("='").append(getChargebackRefundFareAmt()).append("' ");
        buffer.append("chargebackRefundAdminFee").append("='").append(getChargebackRefundAdminFee()).append("' ");
        buffer.append("chargebackRefundGst").append("='").append(getChargebackRefundGst()).append("' ");
        buffer.append("offlineFlag").append("='").append(getOfflineFlag()).append("' ");
        buffer.append("commissionAmt").append("='").append(getCommissionAmt()).append("' ");
        buffer.append("commissionType").append("='").append(getCommissionType()).append("' ");
        buffer.append("commissionValue").append("='").append(getCommissionValue()).append("' ");
        buffer.append("productId").append("='").append(getProductId()).append("' ");
        buffer.append("txnAmount1").append("='").append(getTxnAmount1()).append("' ");
        buffer.append("txnAmount2").append("='").append(getTxnAmount2()).append("' ");
        buffer.append("source").append("='").append(getSource()).append("' ");
        buffer.append("matchingStatus").append("='").append(getMatchingStatus()).append("' ");
        buffer.append("policyNumber").append("='").append(getPolicyNumber()).append("' ");
        buffer.append("startOfInsurance").append("='").append(getStartOfInsurance()).append("' ");
        buffer.append("endOfInsurance").append("='").append(getEndOfInsurance()).append("' ");
        buffer.append("premiumAmount").append("='").append(getPremiumAmount()).append("' ");
        buffer.append("premiumGst").append("='").append(getPremiumGst()).append("' ");
        buffer.append("policyStatus").append("='").append(getPolicyStatus()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }


    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof TmtbNonBillableTxn)) return false;
        TmtbNonBillableTxn castOther = (TmtbNonBillableTxn) other;

        return ((this.getTxnId() == castOther.getTxnId()) || (this.getTxnId() != null && castOther.getTxnId() != null && this.getTxnId().equals(castOther.getTxnId())))
                && ((this.getTxnNo() == castOther.getTxnNo()) || (this.getTxnNo() != null && castOther.getTxnNo() != null && this.getTxnNo().equals(castOther.getTxnNo())))
                && ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null && castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
                && ((this.getJobNo() == castOther.getJobNo()) || (this.getJobNo() != null && castOther.getJobNo() != null && this.getJobNo().equals(castOther.getJobNo())))
                && ((this.getTaxiNo() == castOther.getTaxiNo()) || (this.getTaxiNo() != null && castOther.getTaxiNo() != null && this.getTaxiNo().equals(castOther.getTaxiNo())))
                && ((this.getNric() == castOther.getNric()) || (this.getNric() != null && castOther.getNric() != null && this.getNric().equals(castOther.getNric())))
                && ((this.getTripStartDt() == castOther.getTripStartDt()) || (this.getTripStartDt() != null && castOther.getTripStartDt() != null && this.getTripStartDt().equals(castOther.getTripStartDt())))
                && ((this.getTripEndDt() == castOther.getTripEndDt()) || (this.getTripEndDt() != null && castOther.getTripEndDt() != null && this.getTripEndDt().equals(castOther.getTripEndDt())))
                && ((this.getCardNo() == castOther.getCardNo()) || (this.getCardNo() != null && castOther.getCardNo() != null && this.getCardNo().equals(castOther.getCardNo())))
                && ((this.getFareAmt() == castOther.getFareAmt()) || (this.getFareAmt() != null && castOther.getFareAmt() != null && this.getFareAmt().equals(castOther.getFareAmt())))
                && ((this.getAdminFee() == castOther.getAdminFee()) || (this.getAdminFee() != null && castOther.getAdminFee() != null && this.getAdminFee().equals(castOther.getAdminFee())))
                && ((this.getGst() == castOther.getGst()) || (this.getGst() != null && castOther.getGst() != null && this.getGst().equals(castOther.getGst())))
                && ((this.getTotal() == castOther.getTotal()) || (this.getTotal() != null && castOther.getTotal() != null && this.getTotal().equals(castOther.getTotal())))
                && ((this.getCreatedDt() == castOther.getCreatedDt()) || (this.getCreatedDt() != null && castOther.getCreatedDt() != null && this.getCreatedDt().equals(castOther.getCreatedDt())))
                && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
                && ((this.getUpdatedDt() == castOther.getUpdatedDt()) || (this.getUpdatedDt() != null && castOther.getUpdatedDt() != null && this.getUpdatedDt().equals(castOther.getUpdatedDt())))
                && ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this.getUpdatedBy() != null && castOther.getUpdatedBy() != null && this.getUpdatedBy().equals(castOther.getUpdatedBy())))
                && ((this.getVersion() == castOther.getVersion()) || (this.getVersion() != null && castOther.getVersion() != null && this.getVersion().equals(castOther.getVersion())))
                && ((this.getRemarks() == castOther.getRemarks()) || (this.getRemarks() != null && castOther.getRemarks() != null && this.getRemarks().equals(castOther.getRemarks())))
                && ((this.getChargebackRefundDate() == castOther.getChargebackRefundDate()) || (this.getChargebackRefundDate() != null && castOther.getChargebackRefundDate() != null && this.getChargebackRefundDate().equals(castOther.getChargebackRefundDate())))
                && ((this.getPickupAddress() == castOther.getPickupAddress()) || (this.getPickupAddress() != null && castOther.getPickupAddress() != null && this.getPickupAddress().equals(castOther.getPickupAddress())))
                && ((this.getDestination() == castOther.getDestination()) || (this.getDestination() != null && castOther.getDestination() != null && this.getDestination().equals(castOther.getDestination())))
                && ((this.getLevy() == castOther.getLevy()) || (this.getLevy() != null && castOther.getLevy() != null && this.getLevy().equals(castOther.getLevy())))
                && ((this.getUpdateFms() == castOther.getUpdateFms()) || (this.getUpdateFms() != null && castOther.getUpdateFms() != null && this.getUpdateFms().equals(castOther.getUpdateFms())))
                && ((this.getFmsAmt() == castOther.getFmsAmt()) || (this.getFmsAmt() != null && castOther.getFmsAmt() != null && this.getFmsAmt().equals(castOther.getFmsAmt())))
                && ((this.getIncentiveAmt() == castOther.getIncentiveAmt()) || (this.getIncentiveAmt() != null && castOther.getIncentiveAmt() != null && this.getIncentiveAmt().equals(castOther.getIncentiveAmt())))
                && ((this.getPromoAmt() == castOther.getPromoAmt()) || (this.getPromoAmt() != null && castOther.getPromoAmt() != null && this.getPromoAmt().equals(castOther.getPromoAmt())))
                && ((this.getCabRewardsAmt() == castOther.getCabRewardsAmt()) || (this.getCabRewardsAmt() != null && castOther.getCabRewardsAmt() != null && this.getCabRewardsAmt().equals(castOther.getCabRewardsAmt())))
                && ((this.getFmsFlag() == castOther.getFmsFlag()) || (this.getFmsFlag() != null && castOther.getFmsFlag() != null && this.getFmsFlag().equals(castOther.getFmsFlag())))
                && ((this.getChargebackRefundFareAmt() == castOther.getChargebackRefundFareAmt()) || (this.getChargebackRefundFareAmt() != null && castOther.getChargebackRefundFareAmt() != null && this.getChargebackRefundFareAmt().equals(castOther.getChargebackRefundFareAmt())))
                && ((this.getChargebackRefundAdminFee() == castOther.getChargebackRefundAdminFee()) || (this.getChargebackRefundAdminFee() != null && castOther.getChargebackRefundAdminFee() != null && this.getChargebackRefundAdminFee().equals(castOther.getChargebackRefundAdminFee())))
                && ((this.getChargebackRefundGst() == castOther.getChargebackRefundGst()) || (this.getChargebackRefundGst() != null && castOther.getChargebackRefundGst() != null && this.getChargebackRefundGst().equals(castOther.getChargebackRefundGst())))
                && ((this.getOfflineFlag() == castOther.getOfflineFlag()) || (this.getOfflineFlag() != null && castOther.getOfflineFlag() != null && this.getOfflineFlag().equals(castOther.getOfflineFlag())))
                && ((this.getMstbAcquirerPymtType() == castOther.getMstbAcquirerPymtType()) || (this.getMstbAcquirerPymtType() != null && castOther.getMstbAcquirerPymtType() != null && this.getMstbAcquirerPymtType().equals(castOther.getMstbAcquirerPymtType())))
                && ((this.getTmtbNonBillableBatch() == castOther.getTmtbNonBillableBatch()) || (this.getTmtbNonBillableBatch() != null && castOther.getTmtbNonBillableBatch() != null && this.getTmtbNonBillableBatch().equals(castOther.getTmtbNonBillableBatch())))
                && ((this.getMstbMasterTableByChargebackRefundReason() == castOther.getMstbMasterTableByChargebackRefundReason()) || (this.getMstbMasterTableByChargebackRefundReason() != null && castOther.getMstbMasterTableByChargebackRefundReason() != null && this.getMstbMasterTableByChargebackRefundReason().equals(castOther.getMstbMasterTableByChargebackRefundReason())))
                && ((this.getMstbMasterTableByServiceProvider() == castOther.getMstbMasterTableByServiceProvider()) || (this.getMstbMasterTableByServiceProvider() != null && castOther.getMstbMasterTableByServiceProvider() != null && this.getMstbMasterTableByServiceProvider().equals(castOther.getMstbMasterTableByServiceProvider())))
                && ((this.getMstbMasterTableByChargebackType() == castOther.getMstbMasterTableByChargebackType()) || (this.getMstbMasterTableByChargebackType() != null && castOther.getMstbMasterTableByChargebackType() != null && this.getMstbMasterTableByChargebackType().equals(castOther.getMstbMasterTableByChargebackType())))
                && ((this.getMstbMasterTableByJobType() == castOther.getMstbMasterTableByJobType()) || (this.getMstbMasterTableByJobType() != null && castOther.getMstbMasterTableByJobType() != null && this.getMstbMasterTableByJobType().equals(castOther.getMstbMasterTableByJobType())))
                && ((this.getCommissionAmt() == castOther.getCommissionAmt()) || (this.getCommissionAmt() != null && castOther.getCommissionAmt() != null && this.getCommissionAmt().equals(castOther.getCommissionAmt())))
                && ((this.getProductId() == castOther.getProductId()) || (this.getProductId() != null && castOther.getProductId() != null && this.getProductId().equals(castOther.getProductId())))
                && ((this.getCommissionType() == castOther.getCommissionType()) || (this.getCommissionType() != null && castOther.getCommissionType() != null && this.getCommissionType().equals(castOther.getCommissionType())))
                && ((this.getCommissionValue() == castOther.getCommissionValue()) || (this.getCommissionValue() != null && castOther.getCommissionValue() != null && this.getCommissionValue().equals(castOther.getCommissionValue())))
//                && ( (this.getTmtbNonBillableTxnCrca1()==castOther.getTmtbNonBillableTxnCrca1()) || ( this.getTmtbNonBillableTxnCrca1() != null && castOther.getTmtbNonBillableTxnCrca1()!=null && this.getTmtbNonBillableTxnCrca1().equals(castOther.getTmtbNonBillableTxnCrca1())))
//                && ( (this.getTmtbNonBillableTxnCrca2()==castOther.getTmtbNonBillableTxnCrca2()) || ( this.getTmtbNonBillableTxnCrca2() != null && castOther.getTmtbNonBillableTxnCrca2()!=null && this.getTmtbNonBillableTxnCrca2().equals(castOther.getTmtbNonBillableTxnCrca2())))
                && ( (this.getTxnAmount1()==castOther.getTxnAmount1()) || ( this.getTxnAmount1() != null && castOther.getTxnAmount1()!=null && this.getTxnAmount1().equals(castOther.getTxnAmount1())))
                && ( (this.getTxnAmount2()==castOther.getTxnAmount2()) || ( this.getTxnAmount2() != null && castOther.getTxnAmount2()!=null && this.getTxnAmount2().equals(castOther.getTxnAmount2())))
                && ( (this.getSource()==castOther.getSource()) || ( this.getSource() != null && castOther.getSource()!=null && this.getSource().equals(castOther.getSource())))
                && ( (this.getMatchingStatus()==castOther.getMatchingStatus()) || ( this.getMatchingStatus() != null && castOther.getMatchingStatus()!=null && this.getMatchingStatus().equals(castOther.getMatchingStatus())))
                && ( (this.getPolicyNumber()==castOther.getPolicyNumber()) || ( this.getPolicyNumber() != null && castOther.getPolicyNumber()!=null && this.getPolicyNumber().equals(castOther.getPolicyNumber()) ) )
                && ( (this.getStartOfInsurance()==castOther.getStartOfInsurance()) || ( this.getStartOfInsurance() != null && castOther.getStartOfInsurance()!=null && this.getStartOfInsurance().equals(castOther.getStartOfInsurance()) ) )
                && ( (this.getEndOfInsurance()==castOther.getEndOfInsurance()) || ( this.getEndOfInsurance() != null && castOther.getEndOfInsurance()!=null && this.getEndOfInsurance().equals(castOther.getEndOfInsurance()) ) )
                && ( (this.getPremiumAmount()==castOther.getPremiumAmount()) || ( this.getPremiumAmount() != null && castOther.getPremiumAmount()!=null && this.getPremiumAmount().equals(castOther.getPremiumAmount()) ) )
                && ( (this.getPremiumGst()==castOther.getPremiumGst()) || ( this.getPremiumGst() != null && castOther.getPremiumGst()!=null && this.getPremiumGst().equals(castOther.getPremiumGst()) ) )
                && ( (this.getPolicyStatus()==castOther.getPolicyStatus()) || ( this.getPolicyStatus() != null && castOther.getPolicyStatus()!=null && this.getPolicyStatus().equals(castOther.getPolicyStatus()) ) )
                ;


    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getTxnId() == null ? 0 : this.getTxnId().hashCode());
        result = 37 * result + (getTxnNo() == null ? 0 : this.getTxnNo().hashCode());
        result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
        result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
        result = 37 * result + (getJobNo() == null ? 0 : this.getJobNo().hashCode());
        result = 37 * result + (getTaxiNo() == null ? 0 : this.getTaxiNo().hashCode());
        result = 37 * result + (getNric() == null ? 0 : this.getNric().hashCode());
        result = 37 * result + (getTripStartDt() == null ? 0 : this.getTripStartDt().hashCode());
        result = 37 * result + (getTripEndDt() == null ? 0 : this.getTripEndDt().hashCode());
        result = 37 * result + (getCardNo() == null ? 0 : this.getCardNo().hashCode());
        result = 37 * result + (getFareAmt() == null ? 0 : this.getFareAmt().hashCode());
        result = 37 * result + (getAdminFee() == null ? 0 : this.getAdminFee().hashCode());
        result = 37 * result + (getGst() == null ? 0 : this.getGst().hashCode());
        result = 37 * result + (getTotal() == null ? 0 : this.getTotal().hashCode());
        result = 37 * result + (getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode());
        result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37 * result + (getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode());
        result = 37 * result + (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
        result = 37 * result + (getVersion() == null ? 0 : this.getVersion().hashCode());
        result = 37 * result + (getRemarks() == null ? 0 : this.getRemarks().hashCode());
        result = 37 * result + (getChargebackRefundDate() == null ? 0 : this.getChargebackRefundDate().hashCode());
        result = 37 * result + (getPickupAddress() == null ? 0 : this.getPickupAddress().hashCode());
        result = 37 * result + (getDestination() == null ? 0 : this.getDestination().hashCode());
        result = 37 * result + (getLevy() == null ? 0 : this.getLevy().hashCode());
        result = 37 * result + (getUpdateFms() == null ? 0 : this.getUpdateFms().hashCode());
        result = 37 * result + (getFmsAmt() == null ? 0 : this.getFmsAmt().hashCode());
        result = 37 * result + (getIncentiveAmt() == null ? 0 : this.getIncentiveAmt().hashCode());
        result = 37 * result + (getPromoAmt() == null ? 0 : this.getPromoAmt().hashCode());
        result = 37 * result + (getCabRewardsAmt() == null ? 0 : this.getCabRewardsAmt().hashCode());
        result = 37 * result + (getFmsFlag() == null ? 0 : this.getFmsFlag().hashCode());
        result = 37 * result + (getChargebackRefundFareAmt() == null ? 0 : this.getChargebackRefundFareAmt().hashCode());
        result = 37 * result + (getChargebackRefundAdminFee() == null ? 0 : this.getChargebackRefundAdminFee().hashCode());
        result = 37 * result + (getChargebackRefundGst() == null ? 0 : this.getChargebackRefundGst().hashCode());
        result = 37 * result + (getOfflineFlag() == null ? 0 : this.getOfflineFlag().hashCode());
//        result = 37 * result + (getMstbAcquirerPymtType() == null ? 0 : this.getMstbAcquirerPymtType().hashCode());
//        result = 37 * result + (getTmtbNonBillableBatch() == null ? 0 : this.getTmtbNonBillableBatch().hashCode());
//        result = 37 * result + (getMstbMasterTableByChargebackReason() == null ? 0 : this.getMstbMasterTableByChargebackReason().hashCode());
//        result = 37 * result + (getMstbMasterTableByServiceProvider() == null ? 0 : this.getMstbMasterTableByServiceProvider().hashCode());
//        result = 37 * result + (getMstbMasterTableByChargebackType() == null ? 0 : this.getMstbMasterTableByChargebackType().hashCode());
//        result = 37 * result + (getMstbMasterTableByJobType() == null ? 0 : this.getMstbMasterTableByJobType().hashCode());
        result = 37 * result + (getCommissionAmt() == null ? 0 : this.getCommissionAmt().hashCode());
        result = 37 * result + (getCommissionType() == null ? 0 : this.getCommissionType().hashCode());
        result = 37 * result + (getCommissionValue() == null ? 0 : this.getCommissionValue().hashCode());
        result = 37 * result + (getProductId() == null ? 0 : this.getProductId().hashCode());
//        result = 37 * result + ( getTmtbNonBillableTxnCrca1()== null ? 0 : this.getTmtbNonBillableTxnCrca1().hashCode());
//        result = 37 * result + ( getTmtbNonBillableTxnCrca2()== null ? 0 : this.getTmtbNonBillableTxnCrca2().hashCode());
        result = 37 * result + ( getTxnAmount1()== null ? 0 : this.getTxnAmount1().hashCode());
        result = 37 * result + ( getTxnAmount2()== null ? 0 : this.getTxnAmount2().hashCode());
        result = 37 * result + ( getSource()== null ? 0 : this.getSource().hashCode());
        result = 37 * result + ( getMatchingStatus()== null ? 0 : this.getMatchingStatus().hashCode());
        result = 37 * result + ( getPolicyNumber()== null ? 0 : this.getPolicyNumber().hashCode() );
        result = 37 * result + ( getStartOfInsurance()== null ? 0 : this.getStartOfInsurance().hashCode() );
        result = 37 * result + ( getEndOfInsurance()== null ? 0 : this.getEndOfInsurance().hashCode() );
        result = 37 * result + ( getPremiumAmount()== null ? 0 : this.getPremiumAmount().hashCode() );
        result = 37 * result + ( getPremiumGst()== null ? 0 : this.getPremiumGst().hashCode() );
        result = 37 * result + ( getPolicyStatus()== null ? 0 : this.getPolicyStatus().hashCode() );
        return result;
    }

}
