package com.cdgtaxi.ibs.common.model;
// Generated Sep 24, 2009 2:19:43 PM by Hibernate Tools 3.1.0.beta4 

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.master.model.MstbMasterTable;


/**
 * TmtbTxnReviewReq generated by hbm2java
 */

public class TmtbTxnReviewReq  implements java.io.Serializable {


    // Fields    

    private Integer txnReviewReqNo;
    private String actionTxn;
    private Timestamp tripStartDt;
    private Timestamp tripEndDt;
    private Integer entityNo;
    private BigDecimal fareAmt;
    private String pickupAddress;
    private String destination;
    private String remarks;
    private BigDecimal levy;
    private String passengerName;
    private String bookingRef;
    private String bookedBy;
    private String surcharge;
    private String salesDraftNo;
    private String updateFms;
    private BigDecimal fmsAmt;
    private BigDecimal incentiveAmt;
    private BigDecimal promoAmt;
    private BigDecimal cabRewardsAmt;
    private String fmsFlag;
    private String otuFlag;
    private String flightInfo;
    private Timestamp bookDateTime;
    private Integer version;
    private String projectDesc;
    private String complimentary;
    private String externalCardNo;
    private Set<TmtbTxnReviewReqFlow> tmtbTxnReviewReqFlows = new HashSet<TmtbTxnReviewReqFlow>(0);
    private PmtbProduct pmtbProduct;
    private PmtbProductType pmtbProductType;
    private MstbMasterTable mstbMasterTableByServiceProvider;
    private MstbMasterTable mstbMasterTableByTripType;
    private MstbMasterTable mstbMasterTableByVehicleType;
    private TmtbAcquireTxn tmtbAcquireTxn;
    private AmtbAccount amtbAccount;
    private MstbMasterTable mstbMasterTableByJobType;
    private MstbMasterTable mstbMasterTableByVehicleModel;

	private BigDecimal adminFeeValue;
	private BigDecimal gstValue;
	
	private String tripCodeReason;

    // Constructors

    /** default constructor */
    public TmtbTxnReviewReq() {
    }

    
    /** full constructor */
    public TmtbTxnReviewReq(String actionTxn, Timestamp tripStartDt, Timestamp tripEndDt, Integer entityNo, BigDecimal fareAmt, String pickupAddress, String destination, String remarks, BigDecimal levy, String passengerName, String bookingRef, String bookedBy, String surcharge, String salesDraftNo, String updateFms, BigDecimal fmsAmt, BigDecimal incentiveAmt, BigDecimal promoAmt, BigDecimal cabRewardsAmt, String fmsFlag, String otuFlag, String flightInfo, Timestamp bookDateTime, Integer version, String projectDesc, String complimentary, String externalCardNo, Set<TmtbTxnReviewReqFlow> tmtbTxnReviewReqFlows, PmtbProduct pmtbProduct, PmtbProductType pmtbProductType, MstbMasterTable mstbMasterTableByServiceProvider, MstbMasterTable mstbMasterTableByTripType, MstbMasterTable mstbMasterTableByVehicleType, TmtbAcquireTxn tmtbAcquireTxn, AmtbAccount amtbAccount, MstbMasterTable mstbMasterTableByJobType, MstbMasterTable mstbMasterTableByVehicleModel, String tripCodeReason) {
        this.actionTxn = actionTxn;
        this.tripStartDt = tripStartDt;
        this.tripEndDt = tripEndDt;
        this.entityNo = entityNo;
        this.fareAmt = fareAmt;
        this.pickupAddress = pickupAddress;
        this.destination = destination;
        this.remarks = remarks;
        this.levy = levy;
        this.passengerName = passengerName;
        this.bookingRef = bookingRef;
        this.bookedBy = bookedBy;
        this.surcharge = surcharge;
        this.salesDraftNo = salesDraftNo;
        this.updateFms = updateFms;
        this.fmsAmt = fmsAmt;
        this.incentiveAmt = incentiveAmt;
        this.promoAmt = promoAmt;
        this.cabRewardsAmt = cabRewardsAmt;
        this.fmsFlag = fmsFlag;
        this.otuFlag = otuFlag;
        this.flightInfo = flightInfo;
        this.bookDateTime = bookDateTime;
        this.version = version;
        this.projectDesc = projectDesc;
        this.complimentary = complimentary;
        this.externalCardNo = externalCardNo;
        this.tmtbTxnReviewReqFlows = tmtbTxnReviewReqFlows;
        this.pmtbProduct = pmtbProduct;
        this.pmtbProductType = pmtbProductType;
        this.mstbMasterTableByServiceProvider = mstbMasterTableByServiceProvider;
        this.mstbMasterTableByTripType = mstbMasterTableByTripType;
        this.mstbMasterTableByVehicleType = mstbMasterTableByVehicleType;
        this.tmtbAcquireTxn = tmtbAcquireTxn;
        this.amtbAccount = amtbAccount;
        this.mstbMasterTableByJobType = mstbMasterTableByJobType;
        this.mstbMasterTableByVehicleModel = mstbMasterTableByVehicleModel;
        
        this.tripCodeReason = tripCodeReason;
    }
    

   
    // Property accessors

    public String getExternalCardNo() {
		return externalCardNo;
	}

	public void setExternalCardNo(String externalCardNo) {
		this.externalCardNo = externalCardNo;
	}
    
    public Integer getTxnReviewReqNo() {
        return this.txnReviewReqNo;
    }
    
	public void setTxnReviewReqNo(Integer txnReviewReqNo) {
        this.txnReviewReqNo = txnReviewReqNo;
    }

    public String getActionTxn() {
        return this.actionTxn;
    }
    
    public void setActionTxn(String actionTxn) {
        this.actionTxn = actionTxn;
    }

    public Timestamp getTripStartDt() {
        return this.tripStartDt;
    }
    
    public void setTripStartDt(Timestamp tripStartDt) {
        this.tripStartDt = tripStartDt;
    }

    public Timestamp getTripEndDt() {
        return this.tripEndDt;
    }
    
    public void setTripEndDt(Timestamp tripEndDt) {
        this.tripEndDt = tripEndDt;
    }

    public Integer getEntityNo() {
        return this.entityNo;
    }
    
    public void setEntityNo(Integer entityNo) {
        this.entityNo = entityNo;
    }

    public BigDecimal getFareAmt() {
        return this.fareAmt;
    }
    
    public void setFareAmt(BigDecimal fareAmt) {
        this.fareAmt = fareAmt;
    }

    public String getPickupAddress() {
        return this.pickupAddress;
    }
    
    public void setPickupAddress(String pickupAddress) {
        this.pickupAddress = pickupAddress;
    }

    public String getDestination() {
        return this.destination;
    }
    
    public void setDestination(String destination) {
        this.destination = destination;
    }

    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public BigDecimal getLevy() {
        return this.levy;
    }
    
    public void setLevy(BigDecimal levy) {
        this.levy = levy;
    }

    public String getPassengerName() {
        return this.passengerName;
    }
    
    public void setPassengerName(String passengerName) {
        this.passengerName = passengerName;
    }

    public String getBookingRef() {
        return this.bookingRef;
    }
    
    public void setBookingRef(String bookingRef) {
        this.bookingRef = bookingRef;
    }

    public String getBookedBy() {
        return this.bookedBy;
    }
    
    public void setBookedBy(String bookedBy) {
        this.bookedBy = bookedBy;
    }

    public String getSurcharge() {
        return this.surcharge;
    }
    
    public void setSurcharge(String surcharge) {
        this.surcharge = surcharge;
    }

    public String getSalesDraftNo() {
        return this.salesDraftNo;
    }
    
    public void setSalesDraftNo(String salesDraftNo) {
        this.salesDraftNo = salesDraftNo;
    }

    public String getUpdateFms() {
        return this.updateFms;
    }
    
    public void setUpdateFms(String updateFms) {
        this.updateFms = updateFms;
    }

    public BigDecimal getFmsAmt() {
        return this.fmsAmt;
    }
    
    public void setFmsAmt(BigDecimal fmsAmt) {
        this.fmsAmt = fmsAmt;
    }
    
    public BigDecimal getIncentiveAmt() {
        return this.incentiveAmt;
    }
    
    public void setIncentiveAmt(BigDecimal incentiveAmt) {
        this.incentiveAmt = incentiveAmt;
    }
    
    public BigDecimal getPromoAmt() {
    	return this.promoAmt;
    }
    
    public void setPromoAmt(BigDecimal promoAmt) {
    	this.promoAmt = promoAmt;
    }

    public BigDecimal getCabRewardsAmt() {
    	return this.cabRewardsAmt;
    }
    
    public void setCabRewardsAmt(BigDecimal cabRewardsAmt) {
    	this.cabRewardsAmt = cabRewardsAmt;
    }
    
    public String getFmsFlag() {
        return this.fmsFlag;
    }
    
    public void setFmsFlag(String fmsFlag) {
        this.fmsFlag = fmsFlag;
    }

    public String getOtuFlag() {
        return this.otuFlag;
    }
    
    public void setOtuFlag(String otuFlag) {
        this.otuFlag = otuFlag;
    }

    public String getFlightInfo() {
        return this.flightInfo;
    }
    
    public void setFlightInfo(String flightInfo) {
        this.flightInfo = flightInfo;
    }

    public Timestamp getBookDateTime() {
        return this.bookDateTime;
    }
    
    public void setBookDateTime(Timestamp bookDateTime) {
        this.bookDateTime = bookDateTime;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getProjectDesc() {
        return this.projectDesc;
    }
    
    public void setProjectDesc(String projectDesc) {
        this.projectDesc = projectDesc;
    }

    public String getComplimentary() {
        return this.complimentary;
    }
    
    public void setComplimentary(String complimentary) {
        this.complimentary = complimentary;
    }

    public Set<TmtbTxnReviewReqFlow> getTmtbTxnReviewReqFlows() {
        return this.tmtbTxnReviewReqFlows;
    }
    
    public void setTmtbTxnReviewReqFlows(Set<TmtbTxnReviewReqFlow> tmtbTxnReviewReqFlows) {
        this.tmtbTxnReviewReqFlows = tmtbTxnReviewReqFlows;
    }

    public PmtbProduct getPmtbProduct() {
        return this.pmtbProduct;
    }
    
    public void setPmtbProduct(PmtbProduct pmtbProduct) {
        this.pmtbProduct = pmtbProduct;
    }

    public PmtbProductType getPmtbProductType() {
        return this.pmtbProductType;
    }
    
    public void setPmtbProductType(PmtbProductType pmtbProductType) {
        this.pmtbProductType = pmtbProductType;
    }

    public MstbMasterTable getMstbMasterTableByServiceProvider() {
        return this.mstbMasterTableByServiceProvider;
    }
    
    public void setMstbMasterTableByServiceProvider(MstbMasterTable mstbMasterTableByServiceProvider) {
        this.mstbMasterTableByServiceProvider = mstbMasterTableByServiceProvider;
    }

    public MstbMasterTable getMstbMasterTableByTripType() {
        return this.mstbMasterTableByTripType;
    }
    
    public void setMstbMasterTableByTripType(MstbMasterTable mstbMasterTableByTripType) {
        this.mstbMasterTableByTripType = mstbMasterTableByTripType;
    }

    public MstbMasterTable getMstbMasterTableByVehicleType() {
        return this.mstbMasterTableByVehicleType;
    }
    
    public void setMstbMasterTableByVehicleType(MstbMasterTable mstbMasterTableByVehicleType) {
        this.mstbMasterTableByVehicleType = mstbMasterTableByVehicleType;
    }

    public TmtbAcquireTxn getTmtbAcquireTxn() {
        return this.tmtbAcquireTxn;
    }
    
    public void setTmtbAcquireTxn(TmtbAcquireTxn tmtbAcquireTxn) {
        this.tmtbAcquireTxn = tmtbAcquireTxn;
    }

    public AmtbAccount getAmtbAccount() {
        return this.amtbAccount;
    }
    
    public void setAmtbAccount(AmtbAccount amtbAccount) {
        this.amtbAccount = amtbAccount;
    }
   
    public MstbMasterTable getMstbMasterTableByJobType() {
    	return mstbMasterTableByJobType;
    }

    public void setMstbMasterTableByJobType(MstbMasterTable mstbMasterTableByJobType) {
    	this.mstbMasterTableByJobType = mstbMasterTableByJobType;
    }

    public MstbMasterTable getMstbMasterTableByVehicleModel() {
    	return mstbMasterTableByVehicleModel;
    }

    public void setMstbMasterTableByVehicleModel(
    		MstbMasterTable mstbMasterTableByVehicleModel) {
    	this.mstbMasterTableByVehicleModel = mstbMasterTableByVehicleModel;
    }

    public BigDecimal getAdminFeeValue() {
		return adminFeeValue;
	}


	public void setAdminFeeValue(BigDecimal adminFeeValue) {
		this.adminFeeValue = adminFeeValue;
	}


	public BigDecimal getGstValue() {
		return gstValue;
	}


	public void setGstValue(BigDecimal gstValue) {
		this.gstValue = gstValue;
	}

	public String getTripCodeReason() {
		return tripCodeReason;
	}


	public void setTripCodeReason(String tripCodeReason) {
		this.tripCodeReason = tripCodeReason;
	}


	/**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("actionTxn").append("='").append(getActionTxn()).append("' ");			
      buffer.append("tripStartDt").append("='").append(getTripStartDt()).append("' ");			
      buffer.append("tripEndDt").append("='").append(getTripEndDt()).append("' ");			
      buffer.append("entityNo").append("='").append(getEntityNo()).append("' ");			
      buffer.append("fareAmt").append("='").append(getFareAmt()).append("' ");			
      buffer.append("pickupAddress").append("='").append(getPickupAddress()).append("' ");			
      buffer.append("destination").append("='").append(getDestination()).append("' ");			
      buffer.append("remarks").append("='").append(getRemarks()).append("' ");			
      buffer.append("levy").append("='").append(getLevy()).append("' ");			
      buffer.append("passengerName").append("='").append(getPassengerName()).append("' ");			
      buffer.append("bookingRef").append("='").append(getBookingRef()).append("' ");			
      buffer.append("bookedBy").append("='").append(getBookedBy()).append("' ");			
      buffer.append("surcharge").append("='").append(getSurcharge()).append("' ");			
      buffer.append("salesDraftNo").append("='").append(getSalesDraftNo()).append("' ");			
      buffer.append("updateFms").append("='").append(getUpdateFms()).append("' ");			
      buffer.append("fmsAmt").append("='").append(getFmsAmt()).append("' ");
      buffer.append("incentiveAmt").append("='").append(getIncentiveAmt()).append("' ");
      buffer.append("promoAmt").append("='").append(getPromoAmt()).append("' ");
      buffer.append("cabRewardsAmt").append("='").append(getCabRewardsAmt()).append("' ");
      buffer.append("fmsFlag").append("='").append(getFmsFlag()).append("' ");			
      buffer.append("otuFlag").append("='").append(getOtuFlag()).append("' ");			
      buffer.append("flightInfo").append("='").append(getFlightInfo()).append("' ");			
      buffer.append("bookDateTime").append("='").append(getBookDateTime()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("projectDesc").append("='").append(getProjectDesc()).append("' ");			
      buffer.append("complimentary").append("='").append(getComplimentary()).append("' ");
      buffer.append("externalCardNo").append("='").append(getExternalCardNo()).append("' ");
      buffer.append("gstValue").append("='").append(getGstValue()).append("' ");
	  buffer.append("adminFeeValue").append("='").append(getAdminFeeValue()).append("' ");
	  buffer.append("tripCodeReason").append("='").append(getTripCodeReason()).append("' ");
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TmtbTxnReviewReq) ) return false;
		 TmtbTxnReviewReq castOther = ( TmtbTxnReviewReq ) other; 
         
		 return ( (this.getTxnReviewReqNo()==castOther.getTxnReviewReqNo()) || ( this.getTxnReviewReqNo()!=null && castOther.getTxnReviewReqNo()!=null && this.getTxnReviewReqNo().equals(castOther.getTxnReviewReqNo()) ) )
 && ( (this.getActionTxn()==castOther.getActionTxn()) || ( this.getActionTxn()!=null && castOther.getActionTxn()!=null && this.getActionTxn().equals(castOther.getActionTxn()) ) )
 && ( (this.getTripStartDt()==castOther.getTripStartDt()) || ( this.getTripStartDt()!=null && castOther.getTripStartDt()!=null && this.getTripStartDt().equals(castOther.getTripStartDt()) ) )
 && ( (this.getTripEndDt()==castOther.getTripEndDt()) || ( this.getTripEndDt()!=null && castOther.getTripEndDt()!=null && this.getTripEndDt().equals(castOther.getTripEndDt()) ) )
 && ( (this.getEntityNo()==castOther.getEntityNo()) || ( this.getEntityNo()!=null && castOther.getEntityNo()!=null && this.getEntityNo().equals(castOther.getEntityNo()) ) )
 && ( (this.getFareAmt()==castOther.getFareAmt()) || ( this.getFareAmt()!=null && castOther.getFareAmt()!=null && this.getFareAmt().equals(castOther.getFareAmt()) ) )
 && ( (this.getPickupAddress()==castOther.getPickupAddress()) || ( this.getPickupAddress()!=null && castOther.getPickupAddress()!=null && this.getPickupAddress().equals(castOther.getPickupAddress()) ) )
 && ( (this.getDestination()==castOther.getDestination()) || ( this.getDestination()!=null && castOther.getDestination()!=null && this.getDestination().equals(castOther.getDestination()) ) )
 && ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) )
 && ( (this.getLevy()==castOther.getLevy()) || ( this.getLevy()!=null && castOther.getLevy()!=null && this.getLevy().equals(castOther.getLevy()) ) )
 && ( (this.getPassengerName()==castOther.getPassengerName()) || ( this.getPassengerName()!=null && castOther.getPassengerName()!=null && this.getPassengerName().equals(castOther.getPassengerName()) ) )
 && ( (this.getBookingRef()==castOther.getBookingRef()) || ( this.getBookingRef()!=null && castOther.getBookingRef()!=null && this.getBookingRef().equals(castOther.getBookingRef()) ) )
 && ( (this.getBookedBy()==castOther.getBookedBy()) || ( this.getBookedBy()!=null && castOther.getBookedBy()!=null && this.getBookedBy().equals(castOther.getBookedBy()) ) )
 && ( (this.getSurcharge()==castOther.getSurcharge()) || ( this.getSurcharge()!=null && castOther.getSurcharge()!=null && this.getSurcharge().equals(castOther.getSurcharge()) ) )
 && ( (this.getSalesDraftNo()==castOther.getSalesDraftNo()) || ( this.getSalesDraftNo()!=null && castOther.getSalesDraftNo()!=null && this.getSalesDraftNo().equals(castOther.getSalesDraftNo()) ) )
 && ( (this.getUpdateFms()==castOther.getUpdateFms()) || ( this.getUpdateFms()!=null && castOther.getUpdateFms()!=null && this.getUpdateFms().equals(castOther.getUpdateFms()) ) )
 && ( (this.getFmsAmt()==castOther.getFmsAmt()) || ( this.getFmsAmt()!=null && castOther.getFmsAmt()!=null && this.getFmsAmt().equals(castOther.getFmsAmt()) ) )
 && ( (this.getIncentiveAmt()==castOther.getIncentiveAmt()) || ( this.getIncentiveAmt()!=null && castOther.getIncentiveAmt()!=null && this.getIncentiveAmt().equals(castOther.getIncentiveAmt()) ) )
 && ( (this.getPromoAmt()==castOther.getPromoAmt()) || ( this.getPromoAmt()!=null && castOther.getPromoAmt()!=null && this.getPromoAmt().equals(castOther.getPromoAmt()) ) )
 && ( (this.getCabRewardsAmt()==castOther.getCabRewardsAmt()) || ( this.getCabRewardsAmt()!=null && castOther.getCabRewardsAmt()!=null && this.getCabRewardsAmt().equals(castOther.getCabRewardsAmt()) ) )
 && ( (this.getFmsFlag()==castOther.getFmsFlag()) || ( this.getFmsFlag()!=null && castOther.getFmsFlag()!=null && this.getFmsFlag().equals(castOther.getFmsFlag()) ) )
 && ( (this.getOtuFlag()==castOther.getOtuFlag()) || ( this.getOtuFlag()!=null && castOther.getOtuFlag()!=null && this.getOtuFlag().equals(castOther.getOtuFlag()) ) )
 && ( (this.getFlightInfo()==castOther.getFlightInfo()) || ( this.getFlightInfo()!=null && castOther.getFlightInfo()!=null && this.getFlightInfo().equals(castOther.getFlightInfo()) ) )
 && ( (this.getBookDateTime()==castOther.getBookDateTime()) || ( this.getBookDateTime()!=null && castOther.getBookDateTime()!=null && this.getBookDateTime().equals(castOther.getBookDateTime()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getProjectDesc()==castOther.getProjectDesc()) || ( this.getProjectDesc()!=null && castOther.getProjectDesc()!=null && this.getProjectDesc().equals(castOther.getProjectDesc()) ) )
 && ( (this.getComplimentary()==castOther.getComplimentary()) || ( this.getComplimentary()!=null && castOther.getComplimentary()!=null && this.getComplimentary().equals(castOther.getComplimentary()) ) )
 && ( (this.getExternalCardNo()==castOther.getExternalCardNo()) || ( this.getExternalCardNo()!=null && castOther.getExternalCardNo()!=null && this.getExternalCardNo().equals(castOther.getExternalCardNo()) ) )
 && ( (this.getPmtbProduct()==castOther.getPmtbProduct()) || ( this.getPmtbProduct()!=null && castOther.getPmtbProduct()!=null && this.getPmtbProduct().equals(castOther.getPmtbProduct()) ) )
 && ( (this.getPmtbProductType()==castOther.getPmtbProductType()) || ( this.getPmtbProductType()!=null && castOther.getPmtbProductType()!=null && this.getPmtbProductType().equals(castOther.getPmtbProductType()) ) )
 && ( (this.getMstbMasterTableByServiceProvider()==castOther.getMstbMasterTableByServiceProvider()) || ( this.getMstbMasterTableByServiceProvider()!=null && castOther.getMstbMasterTableByServiceProvider()!=null && this.getMstbMasterTableByServiceProvider().equals(castOther.getMstbMasterTableByServiceProvider()) ) )
 && ( (this.getMstbMasterTableByTripType()==castOther.getMstbMasterTableByTripType()) || ( this.getMstbMasterTableByTripType()!=null && castOther.getMstbMasterTableByTripType()!=null && this.getMstbMasterTableByTripType().equals(castOther.getMstbMasterTableByTripType()) ) )
 && ( (this.getMstbMasterTableByVehicleType()==castOther.getMstbMasterTableByVehicleType()) || ( this.getMstbMasterTableByVehicleType()!=null && castOther.getMstbMasterTableByVehicleType()!=null && this.getMstbMasterTableByVehicleType().equals(castOther.getMstbMasterTableByVehicleType()) ) )
 && ( (this.getTmtbAcquireTxn()==castOther.getTmtbAcquireTxn()) || ( this.getTmtbAcquireTxn()!=null && castOther.getTmtbAcquireTxn()!=null && this.getTmtbAcquireTxn().equals(castOther.getTmtbAcquireTxn()) ) )
 && ( (this.getAmtbAccount()==castOther.getAmtbAccount()) || ( this.getAmtbAccount()!=null && castOther.getAmtbAccount()!=null && this.getAmtbAccount().equals(castOther.getAmtbAccount()) )) 
 && ( (this.getGstValue()==castOther.getGstValue()) || ( this.getGstValue()!=null && castOther.getGstValue()!=null && this.getGstValue().equals(castOther.getGstValue()) )) 
 && ( (this.getTripCodeReason()==castOther.getTripCodeReason()) || ( this.getTripCodeReason()!=null && castOther.getTripCodeReason()!=null && this.getTripCodeReason().equals(castOther.getTripCodeReason()) )) 
 && ( (this.getAdminFeeValue()==castOther.getAdminFeeValue()) || ( this.getAdminFeeValue()!=null && castOther.getAdminFeeValue()!=null && this.getAdminFeeValue().equals(castOther.getAdminFeeValue()))); 


   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTxnReviewReqNo() == null ? 0 : this.getTxnReviewReqNo().hashCode() );
         result = 37 * result + ( getActionTxn() == null ? 0 : this.getActionTxn().hashCode() );
         result = 37 * result + ( getTripStartDt() == null ? 0 : this.getTripStartDt().hashCode() );
         result = 37 * result + ( getTripEndDt() == null ? 0 : this.getTripEndDt().hashCode() );
         result = 37 * result + ( getEntityNo() == null ? 0 : this.getEntityNo().hashCode() );
         result = 37 * result + ( getFareAmt() == null ? 0 : this.getFareAmt().hashCode() );
         result = 37 * result + ( getPickupAddress() == null ? 0 : this.getPickupAddress().hashCode() );
         result = 37 * result + ( getDestination() == null ? 0 : this.getDestination().hashCode() );
         result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
         result = 37 * result + ( getLevy() == null ? 0 : this.getLevy().hashCode() );
         result = 37 * result + ( getPassengerName() == null ? 0 : this.getPassengerName().hashCode() );
         result = 37 * result + ( getBookingRef() == null ? 0 : this.getBookingRef().hashCode() );
         result = 37 * result + ( getBookedBy() == null ? 0 : this.getBookedBy().hashCode() );
         result = 37 * result + ( getSurcharge() == null ? 0 : this.getSurcharge().hashCode() );
         result = 37 * result + ( getSalesDraftNo() == null ? 0 : this.getSalesDraftNo().hashCode() );
         result = 37 * result + ( getUpdateFms() == null ? 0 : this.getUpdateFms().hashCode() );
         result = 37 * result + ( getFmsAmt() == null ? 0 : this.getFmsAmt().hashCode() );
         result = 37 * result + ( getIncentiveAmt() == null ? 0 : this.getIncentiveAmt().hashCode() );
         result = 37 * result + ( getPromoAmt() == null ? 0 : this.getPromoAmt().hashCode() );
         result = 37 * result + ( getCabRewardsAmt() == null ? 0 : this.getCabRewardsAmt().hashCode() );
         result = 37 * result + ( getFmsFlag() == null ? 0 : this.getFmsFlag().hashCode() );
         result = 37 * result + ( getOtuFlag() == null ? 0 : this.getOtuFlag().hashCode() );
         result = 37 * result + ( getFlightInfo() == null ? 0 : this.getFlightInfo().hashCode() );
         result = 37 * result + ( getBookDateTime() == null ? 0 : this.getBookDateTime().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getProjectDesc() == null ? 0 : this.getProjectDesc().hashCode() );
         result = 37 * result + ( getComplimentary() == null ? 0 : this.getComplimentary().hashCode() );
         result = 37 * result + ( getExternalCardNo() == null ? 0 : this.getExternalCardNo().hashCode() );
         
         result = 37 * result + ( getPmtbProduct() == null ? 0 : this.getPmtbProduct().hashCode() );
         result = 37 * result + ( getPmtbProductType() == null ? 0 : this.getPmtbProductType().hashCode() );
         result = 37 * result + ( getMstbMasterTableByServiceProvider() == null ? 0 : this.getMstbMasterTableByServiceProvider().hashCode() );
         result = 37 * result + ( getMstbMasterTableByTripType() == null ? 0 : this.getMstbMasterTableByTripType().hashCode() );
         result = 37 * result + ( getMstbMasterTableByVehicleType() == null ? 0 : this.getMstbMasterTableByVehicleType().hashCode() );
         result = 37 * result + ( getTmtbAcquireTxn() == null ? 0 : this.getTmtbAcquireTxn().hashCode() );
         result = 37 * result + ( getAmtbAccount() == null ? 0 : this.getAmtbAccount().hashCode() );
         
         result = 37 * result + ( getGstValue() == null ? 0 : this.getGstValue().hashCode() );
         result = 37 * result + ( getAdminFeeValue() == null ? 0 : this.getAdminFeeValue().hashCode() );
         result = 37 * result + ( getTripCodeReason() == null ? 0 : this.getTripCodeReason().hashCode() );
         
         return result;
   }   





}
