
package com.cdgtaxi.ibs.interfaces.as.webservice.client;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ComfortDelGroImpl", targetNamespace = "http://www.comfortdelgro.com.sg")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ComfortDelGroImpl {


    /**
     * 
     * @param arg5
     * @param arg3
     * @param arg1
     * @param arg7
     * @param arg9
     * @param arg6
     * @param arg0
     * @param arg2
     * @param arg4
     * @param arg8
     */
    @WebMethod
    @RequestWrapper(localName = "createProduct", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.CreateProduct")
    @ResponseWrapper(localName = "createProductResponse", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.CreateProductResponse")
    public void createProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9);

    /**
     * 
     * @param arg5
     * @param arg3
     * @param arg1
     * @param arg0
     * @param arg2
     * @param arg4
     */
    @WebMethod
    @RequestWrapper(localName = "createAccount", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.CreateAccount")
    @ResponseWrapper(localName = "createAccountResponse", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.CreateAccountResponse")
    public void createAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg5
     * @param arg3
     * @param arg1
     * @param arg7
     * @param arg6
     * @param arg0
     * @param arg2
     * @param arg4
     * @param arg8
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateProduct", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.UpdateProduct")
    @ResponseWrapper(localName = "updateProductResponse", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.UpdateProductResponse")
    public String updateProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8);

    /**
     * 
     * @param arg5
     * @param arg3
     * @param arg1
     * @param arg0
     * @param arg2
     * @param arg4
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateAccount", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.UpdateAccount")
    @ResponseWrapper(localName = "updateAccountResponse", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.UpdateAccountResponse")
    public String updateAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg5
     * @param arg3
     * @param arg1
     * @param arg0
     * @param arg2
     * @param arg4
     */
    @WebMethod
    @RequestWrapper(localName = "updateProductBillingInformation", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.UpdateProductBillingInformation")
    @ResponseWrapper(localName = "updateProductBillingInformationResponse", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.UpdateProductBillingInformationResponse")
    public void updateProductBillingInformation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg5
     * @param arg3
     * @param arg1
     * @param arg0
     * @param arg2
     * @param arg4
     */
    @WebMethod
    @RequestWrapper(localName = "updateAccountBillingInformation", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.UpdateAccountBillingInformation")
    @ResponseWrapper(localName = "updateAccountBillingInformationResponse", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.UpdateAccountBillingInformationResponse")
    public void updateAccountBillingInformation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg3
     * @param arg1
     * @param arg0
     * @param arg2
     * @param arg4
     */
    @WebMethod
    @RequestWrapper(localName = "updateAccountPayment", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.UpdateAccountPayment")
    @ResponseWrapper(localName = "updateAccountPaymentResponse", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.UpdateAccountPaymentResponse")
    public void updateAccountPayment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg3
     * @param arg1
     * @param arg0
     * @param arg2
     * @param arg4
     */
    @WebMethod
    @RequestWrapper(localName = "updateProductPayment", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.UpdateProductPayment")
    @ResponseWrapper(localName = "updateProductPaymentResponse", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.UpdateProductPaymentResponse")
    public void updateProductPayment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg3
     * @param arg1
     * @param arg0
     * @param arg2
     * @param arg4
     */
    @WebMethod
    @RequestWrapper(localName = "reversalTransaction", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.ReversalTransaction")
    @ResponseWrapper(localName = "reversalTransactionResponse", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.ReversalTransactionResponse")
    public void reversalTransaction(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg3
     * @param arg1
     * @param arg0
     * @param arg2
     * @param arg4
     */
    @WebMethod
    @RequestWrapper(localName = "reversalTransactionForAccount", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.ReversalTransactionForAccount")
    @ResponseWrapper(localName = "reversalTransactionForAccountResponse", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.ReversalTransactionForAccountResponse")
    public void reversalTransactionForAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg3
     * @param arg1
     * @param arg0
     * @param arg2
     * @param arg4
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateProductUsage", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.UpdateProductUsage")
    @ResponseWrapper(localName = "updateProductUsageResponse", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.UpdateProductUsageResponse")
    public String updateProductUsage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "handShake", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.HandShake")
    @ResponseWrapper(localName = "handShakeResponse", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.HandShakeResponse")
    public String handShake();

    /**
     * 
     * @param arg5
     * @param arg3
     * @param arg1
     * @param arg6
     * @param arg0
     * @param arg2
     * @param arg4
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enquireTransaction", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.EnquireTransaction")
    @ResponseWrapper(localName = "enquireTransactionResponse", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.EnquireTransactionResponse")
    public List<Object> enquireTransaction(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "enquireProduct", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.EnquireProduct")
    @ResponseWrapper(localName = "enquireProductResponse", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.EnquireProductResponse")
    public List<Object> enquireProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg9
     * @param arg6
     * @param arg2
     * @param arg10
     * @param arg5
     * @param arg1
     * @param arg7
     * @param arg11
     * @param arg0
     * @param arg12
     * @param arg4
     * @param arg8
     * @param arg13
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createProductType", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.CreateProductType")
    @ResponseWrapper(localName = "createProductTypeResponse", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.CreateProductTypeResponse")
    public String createProductType(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        String arg13);

    /**
     * 
     * @param arg3
     * @param arg1
     * @param arg0
     * @param arg2
     */
    @WebMethod
    @RequestWrapper(localName = "createNegativeProduct", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.CreateNegativeProduct")
    @ResponseWrapper(localName = "createNegativeProductResponse", targetNamespace = "http://www.comfortdelgro.com.sg", className = "com.cdgtaxi.ibs.interfaces.as.webservice.client.CreateNegativeProductResponse")
    public void createNegativeProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

}
