CREATE INDEX IMTB_ISSUE_REQ_FLOW_N1 ON IMTB_ISSUE_REQ_FLOW (PARENT_REQ_FLOW_NO);
CREATE INDEX IMTB_ISSUE_REQ_FLOW_N2 ON IMTB_ISSUE_REQ_FLOW (ISSUE_REQ_NO);

CREATE INDEX IMTB_ISSUE_REQ_N1 ON IMTB_ISSUE_REQ (ACCOUNT_NO);
CREATE INDEX IMTB_ISSUE_REQ_N2 ON IMTB_ISSUE_REQ (ITEM_TYPE_NO);
CREATE INDEX IMTB_ISSUE_REQ_N3 ON IMTB_ISSUE_REQ (ISSUE_REQ_FLOW_NO);
CREATE INDEX IMTB_ISSUE_REQ_N4 ON IMTB_ISSUE_REQ (CONTACT_PERSON_NO);

CREATE INDEX IMTB_ITEM_N1 ON IMTB_ITEM (ITEM_TYPE_NO);
CREATE INDEX IMTB_STOCK_N1 ON IMTB_STOCK (ITEM_TYPE_NO);