/*
alter table IMTB_ISSUE_REQ DISABLE constraint IMTB_ISSUE_REQ_FK3;
alter table IMTB_ISSUE_REQ_FLOW DISABLE constraint IMTB_ISSUE_REQ_FLOW_FK1;
alter table IMTB_ISSUE DISABLE constraint IMTB_ISSUE_FK1;
alter table IMTB_ITEM DISABLE constraint IMTB_ITEM_FK2;
delete from IMTB_ISSUE_REQ_FLOW;
delete from IMTB_ISSUE_REQ;
delete from IMTB_ISSUE;
delete from IMTB_STOCK;
delete from IMTB_ITEM;
alter table IMTB_ISSUE_REQ ENABLE constraint IMTB_ISSUE_REQ_FK3;
alter table IMTB_ISSUE_REQ_FLOW ENABLE constraint IMTB_ISSUE_REQ_FLOW_FK1;
alter table IMTB_ISSUE ENABLE constraint IMTB_ISSUE_FK1;
alter table IMTB_ITEM ENABLE constraint IMTB_ITEM_FK2;
*/

CREATE UNIQUE INDEX IMTB_ITEM_U1 ON IMTB_ITEM (SERIAL_NO);

--missed out this reason
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'IVMR','R1',null,'REASON 1','A',0);

--for the grace period
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'IVGP','GP',null,'3','A',0);