/* ********************
 * CDGE Interface
 * ********************/
alter table IMTB_ITEM add(
  REDEEM_TIME timestamp,
  REDEEM_POINT VARCHAR2(80),
  BATCH_NO varchar2(10),
  CASHIER_ID VARCHAR2(80),
  UPDATED_BY VARCHAR2(80),
  CREATED_DT timestamp,
  CREATED_BY VARCHAR2(80)
);

--IBS to CDGE interface seq
CREATE SEQUENCE  "IBS_CDGE_SQ1"  MINVALUE 1 MAXVALUE 9999999 INCREMENT BY 1 START WITH 2 CACHE 10 NOORDER  NOCYCLE ;

--21 refers to this resource Product Mgmt
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) 
VALUES (146,21,'Manage Taxi Vouchers','U','/inventory/search_item.zul',19,'Manage Taxi Vouchers','Y',0);
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) 
VALUES (147,21,'View Taxi Voucher','U','/inventory/view_item.zul',20,'View Taxi Voucher','N',0);
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) 
VALUES (148,21,'Suspend Taxi Voucher','U','Suspend Taxi Voucher',21,'Suspend Taxi Voucher','N',0);
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) 
VALUES (149,21,'Reactivate Taxi Voucher','U','Reactivate Taxi Voucher',22,'Reactivate Taxi Voucher','N',0);
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) 
VALUES (150,21,'Void Taxi Voucher','U','Void Taxi Voucher',23,'Void Taxi Voucher','N',0);
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) 
VALUES (151,21,'Change of Taxi Voucher Redemption','U','Change of Taxi Voucher Redemption',24,'Change of Taxi Voucher Redemption','N',0);
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) 
VALUES (152,21,'Approval of Taxi Vouchers','U','/inventory/search_item_request.zul',25,'Approval of Taxi Vouchers','Y',0);
INSERT INTO SATB_RESOURCE (RSRC_ID,PAR_RSRC_ID,RSRC_NAME,RSRC_TYPE,URI,SEQUENCE,DISPLAY_NAME,DISPLAY,VERSION) 
VALUES (153,21,'Remove Taxi Voucher Redemption','U','Remove Taxi Voucher Redemption',26,'Remove Taxi Voucher Redemption','N',0);

--INVENTORY_SUSPENSION_REASONS = "IVSR";
--INVENTORY_REACTIVATION_REASONS = "IVRR";
--INVENTORY_VOID_REASONS = "IVVR";
--INVENTORY_CHANGE_OF_REDEMPTION_REASONS = "IVCR";
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'IVSR','R1',null,'REASON 1','A',0);
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'IVRR','R1',null,'REASON 1','A',0);
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'IVVR','R1',null,'REASON 1','A',0);
INSERT INTO MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) 
VALUES (MSTB_MASTER_TABLE_SQ1.NEXTVAL,'IVCR','R1',null,'REASON 1','A',0);


CREATE TABLE IMTB_ITEM_REQ (
  REQ_NO NUMBER(8) NOT NULL,
  CURRENT_STATUS varchar2(1) NOT NULL,
  ITEM_NO NUMBER(18) NOT NULL,
  REQUEST_DT TIMESTAMP NOT NULL,
  REQUESTOR VARCHAR2(80) NOT NULL,
  REDEEM_TIME timestamp,
  REDEEM_POINT VARCHAR2(80),
  CASHIER_ID VARCHAR2(80),
  SERIAL_NO NUMBER(25),
  REMARKS VARCHAR2(500),
  MASTER_NO NUMBER(8) NOT NULL,
  VERSION NUMBER(9,0) DEFAULT 0,
  CONSTRAINT IMTB_ITEM_REQ_PK PRIMARY KEY(REQ_NO),
  CONSTRAINT IMTB_ITEM_REQ_FK1 FOREIGN KEY(MASTER_NO) REFERENCES MSTB_MASTER_TABLE(MASTER_NO),
  CONSTRAINT IMTB_ITEM_REQ_FK2 FOREIGN KEY(ITEM_NO) REFERENCES IMTB_ITEM(ITEM_NO)
);
-- creating indexes --
CREATE INDEX IMTB_ITEM_REQ_N1 ON IMTB_ITEM_REQ (MASTER_NO);
CREATE INDEX IMTB_ITEM_REQ_N2 ON IMTB_ITEM_REQ (ITEM_NO);
CREATE SEQUENCE  "IMTB_ITEM_REQ_SQ1"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 2 CACHE 10 NOORDER  NOCYCLE ;


CREATE TABLE IMTB_ITEM_REQ_FLOW (
  REQ_FLOW_NO NUMBER(8) NOT NULL,
  REQ_NO NUMBER(8) NOT NULL,
  FROM_STATUS VARCHAR2(1) NOT NULL,
  TO_STATUS VARCHAR2(1) NOT NULL,
  USER_ID NUMBER(8) NOT NULL,
  REMARKS VARCHAR2(500),
  FLOW_DT TIMESTAMP NOT NULL,
  VERSION NUMBER(9,0) DEFAULT 0,
  CONSTRAINT IMTB_ITEM_REQ_FLOW_PK PRIMARY KEY(REQ_FLOW_NO),
  CONSTRAINT IMTB_ITEM_REQ_FLOW_FK1 FOREIGN KEY(REQ_NO) REFERENCES IMTB_ITEM_REQ(REQ_NO),
  CONSTRAINT IMTB_ITEM_REQ_FLOW_FK2 FOREIGN KEY(USER_ID) REFERENCES SATB_USER(USER_ID)
);
-- creating indexes --
CREATE INDEX IMTB_ITEM_REQ_FLOW_N1 ON IMTB_ITEM_REQ_FLOW (REQ_NO);
CREATE INDEX IMTB_ITEM_REQ_FLOW_N2 ON IMTB_ITEM_REQ_FLOW (USER_ID);
CREATE SEQUENCE  "IMTB_ITEM_REQ_FLOW_SQ1"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 2 CACHE 10 NOORDER  NOCYCLE ;