package com.cdgtaxi.ibs.master.model;
// Generated Mar 27, 2009 6:21:32 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.common.model.Creatable;
import com.cdgtaxi.ibs.common.model.Updatable;


/**
 * MstbCreditTermDetail generated by hbm2java
 */

public class MstbCreditTermDetail  implements java.io.Serializable, Creatable, Updatable, Auditable {


    // Fields    

    private Integer mstbCreditTermDetailNo;
    private Timestamp effectiveDt;
    private int creditTerm;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private Integer version;
    private MstbCreditTermMaster mstbCreditTermMaster;


    // Constructors

    /** default constructor */
    public MstbCreditTermDetail() {
    }

	/** minimal constructor */
    public MstbCreditTermDetail(Timestamp effectiveDt, int creditTerm) {
        this.effectiveDt = effectiveDt;
        this.creditTerm = creditTerm;
    }
    
    /** full constructor */
    public MstbCreditTermDetail(Timestamp effectiveDt, int creditTerm, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, Integer version, MstbCreditTermMaster mstbCreditTermMaster) {
        this.effectiveDt = effectiveDt;
        this.creditTerm = creditTerm;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.version = version;
        this.mstbCreditTermMaster = mstbCreditTermMaster;
    }
    

   
    // Property accessors

    public Integer getMstbCreditTermDetailNo() {
        return this.mstbCreditTermDetailNo;
    }
    
    public void setMstbCreditTermDetailNo(Integer mstbCreditTermDetailNo) {
        this.mstbCreditTermDetailNo = mstbCreditTermDetailNo;
    }

    public Timestamp getEffectiveDt() {
        return this.effectiveDt;
    }
    
    public void setEffectiveDt(Timestamp effectiveDt) {
        this.effectiveDt = effectiveDt;
    }

    public int getCreditTerm() {
        return this.creditTerm;
    }
    
    public void setCreditTerm(int creditTerm) {
        this.creditTerm = creditTerm;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public MstbCreditTermMaster getMstbCreditTermMaster() {
        return this.mstbCreditTermMaster;
    }
    
    public void setMstbCreditTermMaster(MstbCreditTermMaster mstbCreditTermMaster) {
        this.mstbCreditTermMaster = mstbCreditTermMaster;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("effectiveDt").append("='").append(getEffectiveDt()).append("' ");			
      buffer.append("creditTerm").append("='").append(getCreditTerm()).append("' ");
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstbCreditTermDetail) ) return false;
		 MstbCreditTermDetail castOther = ( MstbCreditTermDetail ) other; 
         
		 return ( (this.getMstbCreditTermDetailNo()==castOther.getMstbCreditTermDetailNo()) || ( this.getMstbCreditTermDetailNo()!=null && castOther.getMstbCreditTermDetailNo()!=null && this.getMstbCreditTermDetailNo().equals(castOther.getMstbCreditTermDetailNo()) ) )
 && ( (this.getEffectiveDt()==castOther.getEffectiveDt()) || ( this.getEffectiveDt()!=null && castOther.getEffectiveDt()!=null && this.getEffectiveDt().equals(castOther.getEffectiveDt()) ) )
 && (this.getCreditTerm()==castOther.getCreditTerm())
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getMstbCreditTermMaster()==castOther.getMstbCreditTermMaster()) || ( this.getMstbCreditTermMaster()!=null && castOther.getMstbCreditTermMaster()!=null && this.getMstbCreditTermMaster().equals(castOther.getMstbCreditTermMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getMstbCreditTermDetailNo() == null ? 0 : this.getMstbCreditTermDetailNo().hashCode() );
         result = 37 * result + ( getEffectiveDt() == null ? 0 : this.getEffectiveDt().hashCode() );
         result = 37 * result + this.getCreditTerm();
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getMstbCreditTermMaster() == null ? 0 : this.getMstbCreditTermMaster().hashCode() );
         return result;
   }   





}
