package com.cdgtaxi.ibs.master.model;
// Generated Mar 31, 2010 6:19:35 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Blob;
import java.sql.Timestamp;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.common.model.Creatable;
import com.cdgtaxi.ibs.common.model.Updatable;


/**
 * MstbInvoicePromo generated by hbm2java
 */

public class MstbInvoicePromo  implements java.io.Serializable, Creatable, Updatable, Auditable{


    // Fields    

    private Integer invoicePromoId;
    private String name;
    private Timestamp insertDt;
    private String checkOverdue;
    private String checkInvoiceCorp;
    private BigDecimal checkInvoiceCorpValue;
    private String checkInvoicePers;
    private BigDecimal checkInvoicePersValue;
    private String checkPt;
    private BigDecimal checkPtValue;
    private String checkMainBillContact;
    private String checkRace;
    private String checkRaceValue;
    private String checkAltContact;
    private BigDecimal checkQuantityValue;
    
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;

    private String promo1;
    private String promo2;
    private String promo3;
    
    private Blob fileData;
    private String fileName;
    
    // Constructors

    /** default constructor */
    public MstbInvoicePromo() {
    }
    
    /** full constructor */
    public MstbInvoicePromo(Timestamp insertDt, String name, String checkOverdue, String checkInvoiceCorp, BigDecimal checkInvoiceCorpValue, String checkInvoicePers, BigDecimal checkInvoicePersValue, String checkPt, BigDecimal checkPtValue, String checkMainBillContact, String checkRace, String checkRaceValue, String checkAltContact, BigDecimal checkQuantityValue, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, String promo1, String promo2, String promo3, Blob fileData, String fileName) {
        this.insertDt = insertDt;
        this.name = name;
        this.checkOverdue = checkOverdue;
        this.checkInvoiceCorp = checkInvoiceCorp;
        this.checkInvoiceCorpValue = checkInvoiceCorpValue;
        this.checkInvoicePers = checkInvoicePers;
        this.checkInvoicePersValue = checkInvoicePersValue;
        this.checkPt = checkPt;
        this.checkPtValue = checkPtValue;
        this.checkMainBillContact = checkMainBillContact;
        this.checkRace = checkRace;
        this.checkRaceValue = checkRaceValue;
        this.checkAltContact = checkAltContact;
        this.checkQuantityValue = checkQuantityValue;
        
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        
        this.promo1 = promo1;
        this.promo2 = promo2;
        this.promo3 = promo3;
        
        this.fileData = fileData;
        this.fileName = fileName;
    }
    

   
    // Property accessors

   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("insertDt").append("='").append(getInsertDt()).append("' ");			
      buffer.append("name").append("='").append(getName()).append("' ");			
      buffer.append("checkOverdue").append("='").append(getCheckOverdue()).append("' ");	
      buffer.append("checkInvoiceCorp").append("='").append(getCheckInvoiceCorp()).append("' ");
      buffer.append("checkInvoiceCorpValue").append("='").append(getCheckInvoiceCorpValue()).append("' ");
      buffer.append("checkInvoicePers").append("='").append(getCheckInvoicePers()).append("' ");	
      buffer.append("checkInvoicePersValue").append("='").append(getCheckInvoicePersValue()).append("' ");
      buffer.append("checkPt").append("='").append(getCheckPt()).append("' ");
      buffer.append("checkPtValue").append("='").append(getCheckPtValue()).append("' ");
      buffer.append("checkMainBillContact").append("='").append(getCheckMainBillContact()).append("' ");
      buffer.append("checkRace").append("='").append(getCheckRace()).append("' ");
      buffer.append("checkRaceValue").append("='").append(getCheckRaceValue()).append("' ");
      buffer.append("checkAltContact").append("='").append(getCheckAltContact()).append("' ");
      buffer.append("checkQuantityValue").append("='").append(getCheckQuantityValue()).append("' ");
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");
      buffer.append("promo1").append("='").append(getPromo1()).append("' ");
      buffer.append("promo2").append("='").append(getPromo2()).append("' ");
      buffer.append("promo3").append("='").append(getPromo3()).append("' ");
      buffer.append("fileData").append("='").append(getFileData()).append("' ");
      buffer.append("fileName").append("='").append(getFileName()).append("' ");
      buffer.append("]");
      
      return buffer.toString();
     }


   public Integer getInvoicePromoId() {
		return invoicePromoId;
	}

	public void setInvoicePromoId(Integer invoicePromoId) {
		this.invoicePromoId = invoicePromoId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Timestamp getInsertDt() {
		return insertDt;
	}

	public void setInsertDt(Timestamp insertDt) {
		this.insertDt = insertDt;
	}

	public String getCheckOverdue() {
		return checkOverdue;
	}

	public void setCheckOverdue(String checkOverdue) {
		this.checkOverdue = checkOverdue;
	}

	public String getCheckInvoiceCorp() {
		return checkInvoiceCorp;
	}

	public void setCheckInvoiceCorp(String checkInvoiceCorp) {
		this.checkInvoiceCorp = checkInvoiceCorp;
	}

	public BigDecimal getCheckInvoiceCorpValue() {
		return checkInvoiceCorpValue;
	}

	public void setCheckInvoiceCorpValue(BigDecimal checkInvoiceCorpValue) {
		this.checkInvoiceCorpValue = checkInvoiceCorpValue;
	}

	public String getCheckInvoicePers() {
		return checkInvoicePers;
	}

	public void setCheckInvoicePers(String checkInvoicePers) {
		this.checkInvoicePers = checkInvoicePers;
	}

	public BigDecimal getCheckInvoicePersValue() {
		return checkInvoicePersValue;
	}

	public void setCheckInvoicePersValue(BigDecimal checkInvoicePersValue) {
		this.checkInvoicePersValue = checkInvoicePersValue;
	}

	public String getCheckPt() {
		return checkPt;
	}

	public void setCheckPt(String checkPt) {
		this.checkPt = checkPt;
	}

	public BigDecimal getCheckPtValue() {
		return checkPtValue;
	}

	public void setCheckPtValue(BigDecimal checkPtValue) {
		this.checkPtValue = checkPtValue;
	}

	public String getCheckMainBillContact() {
		return checkMainBillContact;
	}

	public void setCheckMainBillContact(String checkMainBillContact) {
		this.checkMainBillContact = checkMainBillContact;
	}

	public String getCheckRace() {
		return checkRace;
	}

	public void setCheckRace(String checkRace) {
		this.checkRace = checkRace;
	}

	public String getCheckAltContact() {
		return checkAltContact;
	}

	public void setCheckAltContact(String checkAltContact) {
		this.checkAltContact = checkAltContact;
	}

	public BigDecimal getCheckQuantityValue() {
		return checkQuantityValue;
	}

	public void setCheckQuantityValue(BigDecimal checkQuantityValue) {
		this.checkQuantityValue = checkQuantityValue;
	}

	public Timestamp getCreatedDt() {
		return createdDt;
	}

	public void setCreatedDt(Timestamp createdDt) {
		this.createdDt = createdDt;
	}

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Timestamp getUpdatedDt() {
		return updatedDt;
	}

	public void setUpdatedDt(Timestamp updatedDt) {
		this.updatedDt = updatedDt;
	}

	public String getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}
	
	public String getPromo1() {
		return promo1;
	}

	public void setPromo1(String promo1) {
		this.promo1 = promo1;
	}

	public String getPromo2() {
		return promo2;
	}

	public void setPromo2(String promo2) {
		this.promo2 = promo2;
	}

	public String getPromo3() {
		return promo3;
	}

	public void setPromo3(String promo3) {
		this.promo3 = promo3;
	}
	
	public Blob getFileData() {
		return fileData;
	}

	public void setFileData(Blob fileData) {
		this.fileData = fileData;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getCheckRaceValue() {
		return checkRaceValue;
	}

	public void setCheckRaceValue(String checkRaceValue) {
		this.checkRaceValue = checkRaceValue;
	}

public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstbInvoicePromo) ) return false;
		 MstbInvoicePromo castOther = ( MstbInvoicePromo ) other; 
         
		 return ( (this.getInvoicePromoId()==castOther.getInvoicePromoId()) || ( this.getInvoicePromoId()!=null && castOther.getInvoicePromoId()!=null && this.getInvoicePromoId().equals(castOther.getInvoicePromoId()) ) )
 && ( (this.getInsertDt()==castOther.getInsertDt()) || ( this.getInsertDt()!=null && castOther.getInsertDt()!=null && this.getInsertDt().equals(castOther.getInsertDt()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getCheckOverdue()==castOther.getCheckOverdue()) || ( this.getCheckOverdue()!=null && castOther.getCheckOverdue()!=null && this.getCheckOverdue().equals(castOther.getCheckOverdue()) ) )
 && ( (this.getCheckInvoiceCorp()==castOther.getCheckInvoiceCorp()) || ( this.getCheckInvoiceCorp()!=null && castOther.getCheckInvoiceCorp()!=null && this.getCheckInvoiceCorp().equals(castOther.getCheckInvoiceCorp()) ) )
 && ( (this.getCheckInvoiceCorpValue()==castOther.getCheckInvoiceCorpValue()) || ( this.getCheckInvoiceCorpValue()!=null && castOther.getCheckInvoiceCorpValue()!=null && this.getCheckInvoiceCorpValue().equals(castOther.getCheckInvoiceCorpValue()) ) )
 && ( (this.getCheckInvoicePers()==castOther.getCheckInvoicePers()) || ( this.getCheckInvoicePers()!=null && castOther.getCheckInvoicePers()!=null && this.getCheckInvoicePers().equals(castOther.getCheckInvoicePers()) ) )
 && ( (this.getCheckInvoicePersValue()==castOther.getCheckInvoicePersValue()) || ( this.getCheckInvoicePersValue()!=null && castOther.getCheckInvoicePersValue()!=null && this.getCheckInvoicePersValue().equals(castOther.getCheckInvoicePersValue()) ) )
 && ( (this.getCheckPt()==castOther.getCheckPt()) || ( this.getCheckPt()!=null && castOther.getCheckPt()!=null && this.getCheckPt().equals(castOther.getCheckPt()) ) )
 && ( (this.getCheckPtValue()==castOther.getCheckPtValue()) || ( this.getCheckPtValue()!=null && castOther.getCheckPtValue()!=null && this.getCheckPtValue().equals(castOther.getCheckPtValue()) ) )
 && ( (this.getCheckMainBillContact()==castOther.getCheckMainBillContact()) || ( this.getCheckMainBillContact()!=null && castOther.getCheckMainBillContact()!=null && this.getCheckMainBillContact().equals(castOther.getCheckMainBillContact()) ) )
 && ( (this.getCheckRace()==castOther.getCheckRace()) || ( this.getCheckRace()!=null && castOther.getCheckRace()!=null && this.getCheckRace().equals(castOther.getCheckRace()) ) )
 && ( (this.getCheckAltContact()==castOther.getCheckAltContact()) || ( this.getCheckAltContact()!=null && castOther.getCheckAltContact()!=null && this.getCheckAltContact().equals(castOther.getCheckAltContact()) ) )
 && ( (this.getCheckQuantityValue()==castOther.getCheckQuantityValue()) || ( this.getCheckQuantityValue()!=null && castOther.getCheckQuantityValue()!=null && this.getCheckQuantityValue().equals(castOther.getCheckQuantityValue()) ) )

 && ( (this.getPromo1()==castOther.getPromo1()) || ( this.getPromo1()!=null && castOther.getPromo1()!=null && this.getPromo1().equals(castOther.getPromo1()) ) )
 && ( (this.getPromo2()==castOther.getPromo2()) || ( this.getPromo2()!=null && castOther.getPromo2()!=null && this.getPromo2().equals(castOther.getPromo2()) ) )
 && ( (this.getPromo3()==castOther.getPromo3()) || ( this.getPromo3()!=null && castOther.getPromo3()!=null && this.getPromo3().equals(castOther.getPromo3()) ) )
 && ( (this.getCheckRaceValue()==castOther.getCheckRaceValue()) || ( this.getCheckRaceValue()!=null && castOther.getCheckRaceValue()!=null && this.getCheckRaceValue().equals(castOther.getCheckRaceValue()) ) )
 && ( (this.getFileData()==castOther.getFileData()) || ( this.getFileData()!=null && castOther.getFileData()!=null && this.getFileData().equals(castOther.getFileData()) ) )
 && ( (this.getFileName()==castOther.getFileName()) || ( this.getFileName()!=null && castOther.getFileName()!=null && this.getFileName().equals(castOther.getFileName()) ) )

 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getInvoicePromoId() == null ? 0 : this.getInvoicePromoId().hashCode() );
         result = 37 * result + ( getInsertDt() == null ? 0 : this.getInsertDt().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getCheckOverdue() == null ? 0 : this.getCheckOverdue().hashCode() );
         result = 37 * result + ( getCheckInvoiceCorp() == null ? 0 : this.getCheckInvoiceCorp().hashCode() );
         result = 37 * result + ( getCheckInvoiceCorpValue() == null ? 0 : this.getCheckInvoiceCorpValue().hashCode() );
         result = 37 * result + ( getCheckInvoicePers() == null ? 0 : this.getCheckInvoicePers().hashCode() );
         result = 37 * result + ( getCheckInvoicePersValue() == null ? 0 : this.getCheckInvoicePersValue().hashCode() );
         result = 37 * result + ( getCheckPt() == null ? 0 : this.getCheckPt().hashCode() );
         result = 37 * result + ( getCheckPtValue() == null ? 0 : this.getCheckPtValue().hashCode() );
         result = 37 * result + ( getCheckMainBillContact() == null ? 0 : this.getCheckMainBillContact().hashCode() );
         result = 37 * result + ( getCheckRace() == null ? 0 : this.getCheckRace().hashCode() );
         result = 37 * result + ( getCheckRaceValue() == null ? 0 : this.getCheckRaceValue().hashCode() );
         result = 37 * result + ( getCheckAltContact() == null ? 0 : this.getCheckAltContact().hashCode() );
         result = 37 * result + ( getCheckQuantityValue() == null ? 0 : this.getCheckQuantityValue().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         
         result = 37 * result + ( getPromo1() == null ? 0 : this.getPromo1().hashCode() );
         result = 37 * result + ( getPromo2() == null ? 0 : this.getPromo2().hashCode() );
         result = 37 * result + ( getPromo3() == null ? 0 : this.getPromo3().hashCode() );
         
         result = 37 * result + ( getFileData() == null ? 0 : this.getFileData().hashCode() );
         result = 37 * result + ( getFileName() == null ? 0 : this.getFileName().hashCode() );
         
         return result;
   }   

}
