package com.cdgtaxi.ibs.master.model;
// Generated Mar 27, 2009 6:21:34 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.common.model.Creatable;
import com.cdgtaxi.ibs.common.model.Updatable;

import weblogic.xml.security.wsu.Created;


/**
 * MstbVolDiscDetail generated by hbm2java
 */

public class MstbVolDiscDetail  implements java.io.Serializable, Creatable, Updatable {


    // Fields    

    private Integer volumeDiscountPlanDetailNo;
    private String volumeDiscountType;
    private Timestamp effectiveDt;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private Integer version;
    private Set<MstbVolDiscTier> mstbVolDiscTiers = new HashSet<MstbVolDiscTier>(0);
    private MstbVolDiscMaster mstbVolDiscMaster;


    // Constructors

    /** default constructor */
    public MstbVolDiscDetail() {
    }

	/** minimal constructor */
    public MstbVolDiscDetail(String volumeDiscountType, Timestamp effectiveDt) {
        this.volumeDiscountType = volumeDiscountType;
        this.effectiveDt = effectiveDt;
    }
    
    /** full constructor */
    public MstbVolDiscDetail(String volumeDiscountType, Timestamp effectiveDt, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, Integer version, Set<MstbVolDiscTier> mstbVolDiscTiers, MstbVolDiscMaster mstbVolDiscMaster) {
        this.volumeDiscountType = volumeDiscountType;
        this.effectiveDt = effectiveDt;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.version = version;
        this.mstbVolDiscTiers = mstbVolDiscTiers;
        this.mstbVolDiscMaster = mstbVolDiscMaster;
    }
    

   
    // Property accessors

    public Integer getVolumeDiscountPlanDetailNo() {
        return this.volumeDiscountPlanDetailNo;
    }
    
    public void setVolumeDiscountPlanDetailNo(Integer volumeDiscountPlanDetailNo) {
        this.volumeDiscountPlanDetailNo = volumeDiscountPlanDetailNo;
    }

    public String getVolumeDiscountType() {
        return this.volumeDiscountType;
    }
    
    public void setVolumeDiscountType(String volumeDiscountType) {
        this.volumeDiscountType = volumeDiscountType;
    }

    public Timestamp getEffectiveDt() {
        return this.effectiveDt;
    }
    
    public void setEffectiveDt(Timestamp effectiveDt) {
        this.effectiveDt = effectiveDt;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }
    
    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public Set<MstbVolDiscTier> getMstbVolDiscTiers() {
        return this.mstbVolDiscTiers;
    }
    
    public void setMstbVolDiscTiers(Set<MstbVolDiscTier> mstbVolDiscTiers) {
        this.mstbVolDiscTiers = mstbVolDiscTiers;
    }

    public MstbVolDiscMaster getMstbVolDiscMaster() {
        return this.mstbVolDiscMaster;
    }
    
    public void setMstbVolDiscMaster(MstbVolDiscMaster mstbVolDiscMaster) {
        this.mstbVolDiscMaster = mstbVolDiscMaster;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("volumeDiscountType").append("='").append(getVolumeDiscountType()).append("' ");			
      buffer.append("effectiveDt").append("='").append(getEffectiveDt()).append("' ");			
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");	
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstbVolDiscDetail) ) return false;
		 MstbVolDiscDetail castOther = ( MstbVolDiscDetail ) other; 
         
		 return ( (this.getVolumeDiscountPlanDetailNo()==castOther.getVolumeDiscountPlanDetailNo()) || ( this.getVolumeDiscountPlanDetailNo()!=null && castOther.getVolumeDiscountPlanDetailNo()!=null && this.getVolumeDiscountPlanDetailNo().equals(castOther.getVolumeDiscountPlanDetailNo()) ) )
 && ( (this.getVolumeDiscountType()==castOther.getVolumeDiscountType()) || ( this.getVolumeDiscountType()!=null && castOther.getVolumeDiscountType()!=null && this.getVolumeDiscountType().equals(castOther.getVolumeDiscountType()) ) )
 && ( (this.getEffectiveDt()==castOther.getEffectiveDt()) || ( this.getEffectiveDt()!=null && castOther.getEffectiveDt()!=null && this.getEffectiveDt().equals(castOther.getEffectiveDt()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getMstbVolDiscMaster()==castOther.getMstbVolDiscMaster()) || ( this.getMstbVolDiscMaster()!=null && castOther.getMstbVolDiscMaster()!=null && this.getMstbVolDiscMaster().equals(castOther.getMstbVolDiscMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getVolumeDiscountPlanDetailNo() == null ? 0 : this.getVolumeDiscountPlanDetailNo().hashCode() );
         result = 37 * result + ( getVolumeDiscountType() == null ? 0 : this.getVolumeDiscountType().hashCode() );
         result = 37 * result + ( getEffectiveDt() == null ? 0 : this.getEffectiveDt().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         
         result = 37 * result + ( getMstbVolDiscMaster() == null ? 0 : this.getMstbVolDiscMaster().hashCode() );
         return result;
   }   





}
