package com.cdgtaxi.ibs.master.model;
// Generated Jul 20, 2009 6:36:56 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.common.model.AmtbApplicationProduct;
import com.cdgtaxi.ibs.common.model.AmtbSubscTo;
import com.cdgtaxi.ibs.common.model.Creatable;
import com.cdgtaxi.ibs.common.model.Updatable;


/**
 * MstbIssuanceFeeMaster generated by hbm2java
 */

public class MstbIssuanceFeeMaster  implements java.io.Serializable, Creatable, Updatable {


    // Fields    

    private Integer issuanceFeeNo;
    private String issuanceFeeName;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private Integer version;
    private Set<AmtbApplicationProduct> amtbApplicationProducts = new HashSet<AmtbApplicationProduct>(0);
    private Set<MstbIssuanceFeeDetail> mstbIssuanceFeeDetails = new HashSet<MstbIssuanceFeeDetail>(0);
    private Set<AmtbSubscTo> amtbSubscTos = new HashSet<AmtbSubscTo>(0);


    // Constructors

    /** default constructor */
    public MstbIssuanceFeeMaster() {
    }

	/** minimal constructor */
    public MstbIssuanceFeeMaster(String issuanceFeeName) {
        this.issuanceFeeName = issuanceFeeName;
    }
    
    /** full constructor */
    public MstbIssuanceFeeMaster(String issuanceFeeName, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, Integer version, Set<AmtbApplicationProduct> amtbApplicationProducts, Set<MstbIssuanceFeeDetail> mstbIssuanceFeeDetails, Set<AmtbSubscTo> amtbSubscTos) {
        this.issuanceFeeName = issuanceFeeName;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.version = version;
        this.amtbApplicationProducts = amtbApplicationProducts;
        this.mstbIssuanceFeeDetails = mstbIssuanceFeeDetails;
        this.amtbSubscTos = amtbSubscTos;
    }
    

   
    // Property accessors

    public Integer getIssuanceFeeNo() {
        return this.issuanceFeeNo;
    }
    
    public void setIssuanceFeeNo(Integer issuanceFeeNo) {
        this.issuanceFeeNo = issuanceFeeNo;
    }

    public String getIssuanceFeeName() {
        return this.issuanceFeeName;
    }
    
    public void setIssuanceFeeName(String issuanceFeeName) {
        this.issuanceFeeName = issuanceFeeName;
    }
    
    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public Set<AmtbApplicationProduct> getAmtbApplicationProducts() {
        return this.amtbApplicationProducts;
    }
    
    public void setAmtbApplicationProducts(Set<AmtbApplicationProduct> amtbApplicationProducts) {
        this.amtbApplicationProducts = amtbApplicationProducts;
    }

    public Set<MstbIssuanceFeeDetail> getMstbIssuanceFeeDetails() {
        return this.mstbIssuanceFeeDetails;
    }
    
    public void setMstbIssuanceFeeDetails(Set<MstbIssuanceFeeDetail> mstbIssuanceFeeDetails) {
        this.mstbIssuanceFeeDetails = mstbIssuanceFeeDetails;
    }

    public Set<AmtbSubscTo> getAmtbSubscTos() {
        return this.amtbSubscTos;
    }
    
    public void setAmtbSubscTos(Set<AmtbSubscTo> amtbSubscTos) {
        this.amtbSubscTos = amtbSubscTos;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("issuanceFeeName").append("='").append(getIssuanceFeeName()).append("' ");		
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MstbIssuanceFeeMaster) ) return false;
		 MstbIssuanceFeeMaster castOther = ( MstbIssuanceFeeMaster ) other; 
         
		 return ( (this.getIssuanceFeeNo()==castOther.getIssuanceFeeNo()) || ( this.getIssuanceFeeNo()!=null && castOther.getIssuanceFeeNo()!=null && this.getIssuanceFeeNo().equals(castOther.getIssuanceFeeNo()) ) )
 && ( (this.getIssuanceFeeName()==castOther.getIssuanceFeeName()) || ( this.getIssuanceFeeName()!=null && castOther.getIssuanceFeeName()!=null && this.getIssuanceFeeName().equals(castOther.getIssuanceFeeName()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIssuanceFeeNo() == null ? 0 : this.getIssuanceFeeNo().hashCode() );
         result = 37 * result + ( getIssuanceFeeName() == null ? 0 : this.getIssuanceFeeName().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         return result;
   }   

}
