package com.cdgtaxi.ibs.common.model;
// Generated Jun 15, 2010 3:44:42 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Date;

import com.cdgtaxi.ibs.master.model.MstbPromotion;


/**
 * AmtbAcctPromotion generated by hbm2java
 */

public class AmtbAcctPromotion  implements java.io.Serializable {


    // Fields    

    private Integer acctPromotionNo;
    private Date effectiveDateFrom;
    private Date effectiveDateTo;
    private Integer version;
    private MstbPromotion mstbPromotion;
    private AmtbAccount amtbAccount;


    // Constructors

    /** default constructor */
    public AmtbAcctPromotion() {
    }

	/** minimal constructor */
    public AmtbAcctPromotion(Date effectiveDateFrom) {
        this.effectiveDateFrom = effectiveDateFrom;
    }
    
    /** full constructor */
    public AmtbAcctPromotion(Date effectiveDateFrom, Date effectiveDateTo, Integer version, MstbPromotion mstbPromotion, AmtbAccount amtbAccount) {
        this.effectiveDateFrom = effectiveDateFrom;
        this.effectiveDateTo = effectiveDateTo;
        this.version = version;
        this.mstbPromotion = mstbPromotion;
        this.amtbAccount = amtbAccount;
    }
    

   
    // Property accessors

    public Integer getAcctPromotionNo() {
        return this.acctPromotionNo;
    }
    
    public void setAcctPromotionNo(Integer acctPromotionNo) {
        this.acctPromotionNo = acctPromotionNo;
    }

    public Date getEffectiveDateFrom() {
        return this.effectiveDateFrom;
    }
    
    public void setEffectiveDateFrom(Date effectiveDateFrom) {
        this.effectiveDateFrom = effectiveDateFrom;
    }

    public Date getEffectiveDateTo() {
        return this.effectiveDateTo;
    }
    
    public void setEffectiveDateTo(Date effectiveDateTo) {
        this.effectiveDateTo = effectiveDateTo;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public MstbPromotion getMstbPromotion() {
        return this.mstbPromotion;
    }
    
    public void setMstbPromotion(MstbPromotion mstbPromotion) {
        this.mstbPromotion = mstbPromotion;
    }

    public AmtbAccount getAmtbAccount() {
        return this.amtbAccount;
    }
    
    public void setAmtbAccount(AmtbAccount amtbAccount) {
        this.amtbAccount = amtbAccount;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("effectiveDateFrom").append("='").append(getEffectiveDateFrom()).append("' ");			
      buffer.append("effectiveDateTo").append("='").append(getEffectiveDateTo()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmtbAcctPromotion) ) return false;
		 AmtbAcctPromotion castOther = ( AmtbAcctPromotion ) other; 
         
		 return ( (this.getAcctPromotionNo()==castOther.getAcctPromotionNo()) || ( this.getAcctPromotionNo()!=null && castOther.getAcctPromotionNo()!=null && this.getAcctPromotionNo().equals(castOther.getAcctPromotionNo()) ) )
 && ( (this.getEffectiveDateFrom()==castOther.getEffectiveDateFrom()) || ( this.getEffectiveDateFrom()!=null && castOther.getEffectiveDateFrom()!=null && this.getEffectiveDateFrom().equals(castOther.getEffectiveDateFrom()) ) )
 && ( (this.getEffectiveDateTo()==castOther.getEffectiveDateTo()) || ( this.getEffectiveDateTo()!=null && castOther.getEffectiveDateTo()!=null && this.getEffectiveDateTo().equals(castOther.getEffectiveDateTo()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getMstbPromotion()==castOther.getMstbPromotion()) || ( this.getMstbPromotion()!=null && castOther.getMstbPromotion()!=null && this.getMstbPromotion().equals(castOther.getMstbPromotion()) ) )
 && ( (this.getAmtbAccount()==castOther.getAmtbAccount()) || ( this.getAmtbAccount()!=null && castOther.getAmtbAccount()!=null && this.getAmtbAccount().equals(castOther.getAmtbAccount()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAcctPromotionNo() == null ? 0 : this.getAcctPromotionNo().hashCode() );
         result = 37 * result + ( getEffectiveDateFrom() == null ? 0 : this.getEffectiveDateFrom().hashCode() );
         result = 37 * result + ( getEffectiveDateTo() == null ? 0 : this.getEffectiveDateTo().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getMstbPromotion() == null ? 0 : this.getMstbPromotion().hashCode() );
         result = 37 * result + ( getAmtbAccount() == null ? 0 : this.getAmtbAccount().hashCode() );
         return result;
   }   





}
