package com.cdgtaxi.ibs.common.model;

import com.cdgtaxi.ibs.master.model.LrtbRewardMaster;
import com.cdgtaxi.ibs.master.model.MstbIssuanceFeeMaster;
import com.cdgtaxi.ibs.master.model.MstbProdDiscMaster;
import com.cdgtaxi.ibs.master.model.MstbSubscFeeMaster;



/**
 * AmtbApplicationProduct generated by hbm2java
 */

public class AmtbApplicationProduct  implements java.io.Serializable {


    // Fields    

    private Integer applicationProductNo;
    private Integer version;
    private PmtbProductType pmtbProductType;
    private MstbProdDiscMaster mstbProdDiscMaster;
    private AmtbApplication amtbApplication;
    private LrtbRewardMaster lrtbRewardMaster;
    private MstbSubscFeeMaster mstbSubscFeeMaster;
    private MstbIssuanceFeeMaster mstbIssuanceFeeMaster;

    // Constructors

    /** default constructor */
    public AmtbApplicationProduct() {
    }

    
    /** full constructor */
    public AmtbApplicationProduct(Integer version, PmtbProductType pmtbProductType, MstbProdDiscMaster mstbProdDiscMaster, AmtbApplication amtbApplication, LrtbRewardMaster lrtbRewardMaster, MstbSubscFeeMaster mstbSubscFeeMaster, MstbIssuanceFeeMaster mstbIssuanceFeeMaster) {
        this.version = version;
        this.pmtbProductType = pmtbProductType;
        this.mstbProdDiscMaster = mstbProdDiscMaster;
        this.amtbApplication = amtbApplication;
        this.lrtbRewardMaster = lrtbRewardMaster;
        this.mstbSubscFeeMaster = mstbSubscFeeMaster;
        this.mstbIssuanceFeeMaster = mstbIssuanceFeeMaster;
    }
    

   
    // Property accessors

    public Integer getApplicationProductNo() {
        return this.applicationProductNo;
    }
    
    public void setApplicationProductNo(Integer applicationProductNo) {
        this.applicationProductNo = applicationProductNo;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public PmtbProductType getPmtbProductType() {
        return this.pmtbProductType;
    }
    
    public void setPmtbProductType(PmtbProductType pmtbProductType) {
        this.pmtbProductType = pmtbProductType;
    }

    public MstbProdDiscMaster getMstbProdDiscMaster() {
        return this.mstbProdDiscMaster;
    }
    
    public void setMstbProdDiscMaster(MstbProdDiscMaster mstbProdDiscMaster) {
        this.mstbProdDiscMaster = mstbProdDiscMaster;
    }

    public AmtbApplication getAmtbApplication() {
        return this.amtbApplication;
    }
    
    public void setAmtbApplication(AmtbApplication amtbApplication) {
        this.amtbApplication = amtbApplication;
    }

    public LrtbRewardMaster getLrtbRewardMaster() {
        return this.lrtbRewardMaster;
    }
    
    public void setLrtbRewardMaster(LrtbRewardMaster lrtbRewardMaster) {
        this.lrtbRewardMaster = lrtbRewardMaster;
    }

    public MstbSubscFeeMaster getMstbSubscFeeMaster() {
        return this.mstbSubscFeeMaster;
    }
    
    public void setMstbSubscFeeMaster(MstbSubscFeeMaster mstbSubscFeeMaster) {
        this.mstbSubscFeeMaster = mstbSubscFeeMaster;
    }
    
    public MstbIssuanceFeeMaster getMstbIssuanceFeeMaster() {
        return this.mstbIssuanceFeeMaster;
    }
    
    public void setMstbIssuanceFeeMaster(MstbIssuanceFeeMaster mstbIssuanceFeeMaster) {
        this.mstbIssuanceFeeMaster = mstbIssuanceFeeMaster;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmtbApplicationProduct) ) return false;
		 AmtbApplicationProduct castOther = ( AmtbApplicationProduct ) other; 
         
		 return ( (this.getApplicationProductNo()==castOther.getApplicationProductNo()) || ( this.getApplicationProductNo()!=null && castOther.getApplicationProductNo()!=null && this.getApplicationProductNo().equals(castOther.getApplicationProductNo()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getPmtbProductType()==castOther.getPmtbProductType()) || ( this.getPmtbProductType()!=null && castOther.getPmtbProductType()!=null && this.getPmtbProductType().equals(castOther.getPmtbProductType()) ) )
 && ( (this.getMstbProdDiscMaster()==castOther.getMstbProdDiscMaster()) || ( this.getMstbProdDiscMaster()!=null && castOther.getMstbProdDiscMaster()!=null && this.getMstbProdDiscMaster().equals(castOther.getMstbProdDiscMaster()) ) )
 && ( (this.getAmtbApplication()==castOther.getAmtbApplication()) || ( this.getAmtbApplication()!=null && castOther.getAmtbApplication()!=null && this.getAmtbApplication().equals(castOther.getAmtbApplication()) ) )
 && ( (this.getLrtbRewardMaster()==castOther.getLrtbRewardMaster()) || ( this.getLrtbRewardMaster()!=null && castOther.getLrtbRewardMaster()!=null && this.getLrtbRewardMaster().equals(castOther.getLrtbRewardMaster()) ) )
 && ( (this.getMstbSubscFeeMaster()==castOther.getMstbSubscFeeMaster()) || ( this.getMstbSubscFeeMaster()!=null && castOther.getMstbSubscFeeMaster()!=null && this.getMstbSubscFeeMaster().equals(castOther.getMstbSubscFeeMaster()) ) )
 && ( (this.getMstbIssuanceFeeMaster()==castOther.getMstbIssuanceFeeMaster()) || ( this.getMstbIssuanceFeeMaster()!=null && castOther.getMstbIssuanceFeeMaster()!=null && this.getMstbIssuanceFeeMaster().equals(castOther.getMstbIssuanceFeeMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getApplicationProductNo() == null ? 0 : this.getApplicationProductNo().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getPmtbProductType() == null ? 0 : this.getPmtbProductType().hashCode() );
         result = 37 * result + ( getMstbProdDiscMaster() == null ? 0 : this.getMstbProdDiscMaster().hashCode() );
         result = 37 * result + ( getAmtbApplication() == null ? 0 : this.getAmtbApplication().hashCode() );
         result = 37 * result + ( getLrtbRewardMaster() == null ? 0 : this.getLrtbRewardMaster().hashCode() );
         result = 37 * result + ( getMstbSubscFeeMaster() == null ? 0 : this.getMstbSubscFeeMaster().hashCode() );
         result = 37 * result + ( getMstbIssuanceFeeMaster() == null ? 0 : this.getMstbIssuanceFeeMaster().hashCode() );
         return result;
   }   





}
