package com.cdgtaxi.ibs.common.model;
// Generated Jul 27, 2009 5:03:52 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;

import com.cdgtaxi.ibs.master.model.LrtbRewardMaster;
import com.cdgtaxi.ibs.master.model.MstbProdDiscMaster;
import com.cdgtaxi.ibs.master.model.MstbSubscFeeMaster;


/**
 * AmtbSubscToHist generated by hbm2java
 */

public class AmtbSubscToHist  implements java.io.Serializable {


    // Fields    

    private Integer subscToHistNo;
    private Timestamp effDtFrom;
    private Timestamp effDtTo;
    private Integer version;
    private PmtbProductType pmtbProductType;
    private MstbProdDiscMaster mstbProdDiscMaster;
    private AmtbAccount amtbAccount;
    private LrtbRewardMaster lrtbRewardMaster;
    private MstbSubscFeeMaster mstbSubscFeeMaster;


    // Constructors

    /** default constructor */
    public AmtbSubscToHist() {
    }

	/** minimal constructor */
    public AmtbSubscToHist(Timestamp effDtFrom) {
        this.effDtFrom = effDtFrom;
    }
    
    /** full constructor */
    public AmtbSubscToHist(Timestamp effDtFrom, Timestamp effDtTo, Integer version, PmtbProductType pmtbProductType, MstbProdDiscMaster mstbProdDiscMaster, AmtbAccount amtbAccount, LrtbRewardMaster lrtbRewardMaster, MstbSubscFeeMaster mstbSubscFeeMaster) {
        this.effDtFrom = effDtFrom;
        this.effDtTo = effDtTo;
        this.version = version;
        this.pmtbProductType = pmtbProductType;
        this.mstbProdDiscMaster = mstbProdDiscMaster;
        this.amtbAccount = amtbAccount;
        this.lrtbRewardMaster = lrtbRewardMaster;
        this.mstbSubscFeeMaster = mstbSubscFeeMaster;
    }
    

   
    // Property accessors

    public Integer getSubscToHistNo() {
        return this.subscToHistNo;
    }
    
    public void setSubscToHistNo(Integer subscToHistNo) {
        this.subscToHistNo = subscToHistNo;
    }

    public Timestamp getEffDtFrom() {
        return this.effDtFrom;
    }
    
    public void setEffDtFrom(Timestamp effDtFrom) {
        this.effDtFrom = effDtFrom;
    }

    public Timestamp getEffDtTo() {
        return this.effDtTo;
    }
    
    public void setEffDtTo(Timestamp effDtTo) {
        this.effDtTo = effDtTo;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public PmtbProductType getPmtbProductType() {
        return this.pmtbProductType;
    }
    
    public void setPmtbProductType(PmtbProductType pmtbProductType) {
        this.pmtbProductType = pmtbProductType;
    }

    public MstbProdDiscMaster getMstbProdDiscMaster() {
        return this.mstbProdDiscMaster;
    }
    
    public void setMstbProdDiscMaster(MstbProdDiscMaster mstbProdDiscMaster) {
        this.mstbProdDiscMaster = mstbProdDiscMaster;
    }

    public AmtbAccount getAmtbAccount() {
        return this.amtbAccount;
    }
    
    public void setAmtbAccount(AmtbAccount amtbAccount) {
        this.amtbAccount = amtbAccount;
    }

    public LrtbRewardMaster getLrtbRewardMaster() {
        return this.lrtbRewardMaster;
    }
    
    public void setLrtbRewardMaster(LrtbRewardMaster lrtbRewardMaster) {
        this.lrtbRewardMaster = lrtbRewardMaster;
    }

    public MstbSubscFeeMaster getMstbSubscFeeMaster() {
        return this.mstbSubscFeeMaster;
    }
    
    public void setMstbSubscFeeMaster(MstbSubscFeeMaster mstbSubscFeeMaster) {
        this.mstbSubscFeeMaster = mstbSubscFeeMaster;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("effDtFrom").append("='").append(getEffDtFrom()).append("' ");			
      buffer.append("effDtTo").append("='").append(getEffDtTo()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmtbSubscToHist) ) return false;
		 AmtbSubscToHist castOther = ( AmtbSubscToHist ) other; 
         
		 return ( (this.getSubscToHistNo()==castOther.getSubscToHistNo()) || ( this.getSubscToHistNo()!=null && castOther.getSubscToHistNo()!=null && this.getSubscToHistNo().equals(castOther.getSubscToHistNo()) ) )
 && ( (this.getEffDtFrom()==castOther.getEffDtFrom()) || ( this.getEffDtFrom()!=null && castOther.getEffDtFrom()!=null && this.getEffDtFrom().equals(castOther.getEffDtFrom()) ) )
 && ( (this.getEffDtTo()==castOther.getEffDtTo()) || ( this.getEffDtTo()!=null && castOther.getEffDtTo()!=null && this.getEffDtTo().equals(castOther.getEffDtTo()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getPmtbProductType()==castOther.getPmtbProductType()) || ( this.getPmtbProductType()!=null && castOther.getPmtbProductType()!=null && this.getPmtbProductType().equals(castOther.getPmtbProductType()) ) )
 && ( (this.getMstbProdDiscMaster()==castOther.getMstbProdDiscMaster()) || ( this.getMstbProdDiscMaster()!=null && castOther.getMstbProdDiscMaster()!=null && this.getMstbProdDiscMaster().equals(castOther.getMstbProdDiscMaster()) ) )
 && ( (this.getAmtbAccount()==castOther.getAmtbAccount()) || ( this.getAmtbAccount()!=null && castOther.getAmtbAccount()!=null && this.getAmtbAccount().equals(castOther.getAmtbAccount()) ) )
 && ( (this.getLrtbRewardMaster()==castOther.getLrtbRewardMaster()) || ( this.getLrtbRewardMaster()!=null && castOther.getLrtbRewardMaster()!=null && this.getLrtbRewardMaster().equals(castOther.getLrtbRewardMaster()) ) )
 && ( (this.getMstbSubscFeeMaster()==castOther.getMstbSubscFeeMaster()) || ( this.getMstbSubscFeeMaster()!=null && castOther.getMstbSubscFeeMaster()!=null && this.getMstbSubscFeeMaster().equals(castOther.getMstbSubscFeeMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSubscToHistNo() == null ? 0 : this.getSubscToHistNo().hashCode() );
         result = 37 * result + ( getEffDtFrom() == null ? 0 : this.getEffDtFrom().hashCode() );
         result = 37 * result + ( getEffDtTo() == null ? 0 : this.getEffDtTo().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getPmtbProductType() == null ? 0 : this.getPmtbProductType().hashCode() );
         result = 37 * result + ( getMstbProdDiscMaster() == null ? 0 : this.getMstbProdDiscMaster().hashCode() );
         result = 37 * result + ( getAmtbAccount() == null ? 0 : this.getAmtbAccount().hashCode() );
         result = 37 * result + ( getLrtbRewardMaster() == null ? 0 : this.getLrtbRewardMaster().hashCode() );
         result = 37 * result + ( getMstbSubscFeeMaster() == null ? 0 : this.getMstbSubscFeeMaster().hashCode() );
         return result;
   }   





}
