package com.cdgtaxi.ibs.common.model;
// Generated Jul 20, 2009 4:09:36 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.acl.model.SatbUser;
import com.cdgtaxi.ibs.master.model.MstbSalesperson;


/**
 * AmtbAcctSalespersonReq generated by hbm2java
 */

public class AmtbAcctSalespersonReq  implements java.io.Serializable {


    // Fields    

    private Integer acctSalespersonReqNo;
    private Timestamp requestDt;
    private Timestamp effectiveDt;
    private Integer version;
    private MstbSalesperson mstbSalespersonByToSalespersonNo;
    private MstbSalesperson mstbSalespersonByFromSalespersonNo;
    private Set<AmtbAcctSalesperson> amtbAcctSalespersons = new HashSet<AmtbAcctSalesperson>(0);
    private SatbUser satbUser;


    // Constructors

    /** default constructor */
    public AmtbAcctSalespersonReq() {
    }

	/** minimal constructor */
    public AmtbAcctSalespersonReq(Timestamp requestDt, Timestamp effectiveDt) {
        this.requestDt = requestDt;
        this.effectiveDt = effectiveDt;
    }
    
    /** full constructor */
    public AmtbAcctSalespersonReq(Timestamp requestDt, Timestamp effectiveDt, Integer version, MstbSalesperson mstbSalespersonByToSalespersonNo, MstbSalesperson mstbSalespersonByFromSalespersonNo, Set<AmtbAcctSalesperson> amtbAcctSalespersons, SatbUser satbUser) {
        this.requestDt = requestDt;
        this.effectiveDt = effectiveDt;
        this.version = version;
        this.mstbSalespersonByToSalespersonNo = mstbSalespersonByToSalespersonNo;
        this.mstbSalespersonByFromSalespersonNo = mstbSalespersonByFromSalespersonNo;
        this.amtbAcctSalespersons = amtbAcctSalespersons;
        this.satbUser = satbUser;
    }
    

   
    // Property accessors

    public Integer getAcctSalespersonReqNo() {
        return this.acctSalespersonReqNo;
    }
    
    public void setAcctSalespersonReqNo(Integer acctSalespersonReqNo) {
        this.acctSalespersonReqNo = acctSalespersonReqNo;
    }

    public Timestamp getRequestDt() {
        return this.requestDt;
    }
    
    public void setRequestDt(Timestamp requestDt) {
        this.requestDt = requestDt;
    }

    public Timestamp getEffectiveDt() {
        return this.effectiveDt;
    }
    
    public void setEffectiveDt(Timestamp effectiveDt) {
        this.effectiveDt = effectiveDt;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public MstbSalesperson getMstbSalespersonByToSalespersonNo() {
        return this.mstbSalespersonByToSalespersonNo;
    }
    
    public void setMstbSalespersonByToSalespersonNo(MstbSalesperson mstbSalespersonByToSalespersonNo) {
        this.mstbSalespersonByToSalespersonNo = mstbSalespersonByToSalespersonNo;
    }

    public MstbSalesperson getMstbSalespersonByFromSalespersonNo() {
        return this.mstbSalespersonByFromSalespersonNo;
    }
    
    public void setMstbSalespersonByFromSalespersonNo(MstbSalesperson mstbSalespersonByFromSalespersonNo) {
        this.mstbSalespersonByFromSalespersonNo = mstbSalespersonByFromSalespersonNo;
    }

    public Set<AmtbAcctSalesperson> getAmtbAcctSalespersons() {
        return this.amtbAcctSalespersons;
    }
    
    public void setAmtbAcctSalespersons(Set<AmtbAcctSalesperson> amtbAcctSalespersons) {
        this.amtbAcctSalespersons = amtbAcctSalespersons;
    }

    public SatbUser getSatbUser() {
        return this.satbUser;
    }
    
    public void setSatbUser(SatbUser satbUser) {
        this.satbUser = satbUser;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("requestDt").append("='").append(getRequestDt()).append("' ");			
      buffer.append("effectiveDt").append("='").append(getEffectiveDt()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AmtbAcctSalespersonReq) ) return false;
		 AmtbAcctSalespersonReq castOther = ( AmtbAcctSalespersonReq ) other; 
         
		 return ( (this.getAcctSalespersonReqNo()==castOther.getAcctSalespersonReqNo()) || ( this.getAcctSalespersonReqNo()!=null && castOther.getAcctSalespersonReqNo()!=null && this.getAcctSalespersonReqNo().equals(castOther.getAcctSalespersonReqNo()) ) )
 && ( (this.getRequestDt()==castOther.getRequestDt()) || ( this.getRequestDt()!=null && castOther.getRequestDt()!=null && this.getRequestDt().equals(castOther.getRequestDt()) ) )
 && ( (this.getEffectiveDt()==castOther.getEffectiveDt()) || ( this.getEffectiveDt()!=null && castOther.getEffectiveDt()!=null && this.getEffectiveDt().equals(castOther.getEffectiveDt()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getMstbSalespersonByToSalespersonNo()==castOther.getMstbSalespersonByToSalespersonNo()) || ( this.getMstbSalespersonByToSalespersonNo()!=null && castOther.getMstbSalespersonByToSalespersonNo()!=null && this.getMstbSalespersonByToSalespersonNo().equals(castOther.getMstbSalespersonByToSalespersonNo()) ) )
 && ( (this.getMstbSalespersonByFromSalespersonNo()==castOther.getMstbSalespersonByFromSalespersonNo()) || ( this.getMstbSalespersonByFromSalespersonNo()!=null && castOther.getMstbSalespersonByFromSalespersonNo()!=null && this.getMstbSalespersonByFromSalespersonNo().equals(castOther.getMstbSalespersonByFromSalespersonNo()) ) )
 && ( (this.getSatbUser()==castOther.getSatbUser()) || ( this.getSatbUser()!=null && castOther.getSatbUser()!=null && this.getSatbUser().equals(castOther.getSatbUser()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAcctSalespersonReqNo() == null ? 0 : this.getAcctSalespersonReqNo().hashCode() );
         result = 37 * result + ( getRequestDt() == null ? 0 : this.getRequestDt().hashCode() );
         result = 37 * result + ( getEffectiveDt() == null ? 0 : this.getEffectiveDt().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getMstbSalespersonByToSalespersonNo() == null ? 0 : this.getMstbSalespersonByToSalespersonNo().hashCode() );
         result = 37 * result + ( getMstbSalespersonByFromSalespersonNo() == null ? 0 : this.getMstbSalespersonByFromSalespersonNo().hashCode() );
         
         result = 37 * result + ( getSatbUser() == null ? 0 : this.getSatbUser().hashCode() );
         return result;
   }   





}
