
package com.cdgtaxi.ibs.common.model;
// Generated Jul 20, 2009 4:09:24 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.acl.security.Auditable;


/**
 * BmtbBillGenSetup generated by hbm2java
 */

public class BmtbBillGenSetup  implements java.io.Serializable, Auditable, Updatable, Creatable {


    // Fields    

    private Integer setupNo;
    private String name;
    private Integer cutOffDay;
    private Integer billGenDay;
    private String billGenTime;
    private Integer invoiceDay;
    private String createdBy;
    private Timestamp createdDt;
    private String updatedBy;
    private Timestamp updatedDt;
    private Integer version;
    private String govtEInvoiceFlag;
    private String pubbsFlag;
    private Set<BmtbBillGenReq> bmtbBillGenReqs = new HashSet<BmtbBillGenReq>(0);


    // Constructors

    /** default constructor */
    public BmtbBillGenSetup() {
    }

	/** minimal constructor */
    public BmtbBillGenSetup(String name) {
        this.name = name;
    }
    
	/** full constructor */
	public BmtbBillGenSetup(String name, Integer cutOffDay, Integer billGenDay, String billGenTime,
			Integer invoiceDay, String createdBy, Timestamp createdDt, String updatedBy,
			Timestamp updatedDt, Integer version, Set<BmtbBillGenReq> bmtbBillGenReqs,
			String govtEInvoiceFlag, String pubbsFlag) {
		this.name = name;
        this.cutOffDay = cutOffDay;
        this.billGenDay = billGenDay;
        this.billGenTime = billGenTime;
        this.invoiceDay = invoiceDay;
        this.createdBy = createdBy;
        this.createdDt = createdDt;
        this.updatedBy = updatedBy;
        this.updatedDt = updatedDt;
        this.version = version;
        this.bmtbBillGenReqs = bmtbBillGenReqs;
        this.govtEInvoiceFlag = govtEInvoiceFlag;
        this.pubbsFlag = pubbsFlag;
    }
    

   
    // Property accessors

	public Integer getSetupNo() {
        return this.setupNo;
    }
    
    public void setSetupNo(Integer setupNo) {
        this.setupNo = setupNo;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public Integer getCutOffDay() {
        return this.cutOffDay;
    }
    
    public void setCutOffDay(Integer cutOffDay) {
        this.cutOffDay = cutOffDay;
    }

    public Integer getBillGenDay() {
        return this.billGenDay;
    }
    
    public void setBillGenDay(Integer billGenDay) {
        this.billGenDay = billGenDay;
    }

    public String getBillGenTime() {
        return this.billGenTime;
    }
    
    public void setBillGenTime(String billGenTime) {
        this.billGenTime = billGenTime;
    }

    public Integer getInvoiceDay() {
        return this.invoiceDay;
    }
    
    public void setInvoiceDay(Integer invoiceDay) {
        this.invoiceDay = invoiceDay;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public Set<BmtbBillGenReq> getBmtbBillGenReqs() {
        return this.bmtbBillGenReqs;
    }
    
    public void setBmtbBillGenReqs(Set<BmtbBillGenReq> bmtbBillGenReqs) {
        this.bmtbBillGenReqs = bmtbBillGenReqs;
    }
   
    public String getGovtEInvoiceFlag() {
		return govtEInvoiceFlag;
	}

	public void setGovtEInvoiceFlag(String govtEInvoiceFlag) {
		this.govtEInvoiceFlag = govtEInvoiceFlag;
	}

    public String getPubbsFlag() {
		return pubbsFlag;
	}

	public void setPubbsFlag(String pubbsFlag) {
		this.pubbsFlag = pubbsFlag;
	}

	/**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("name").append("='").append(getName()).append("' ");			
      buffer.append("cutOffDay").append("='").append(getCutOffDay()).append("' ");			
      buffer.append("billGenDay").append("='").append(getBillGenDay()).append("' ");			
      buffer.append("billGenTime").append("='").append(getBillGenTime()).append("' ");			
      buffer.append("invoiceDay").append("='").append(getInvoiceDay()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");
      buffer.append("govtEInvoiceFlag").append("='").append(getGovtEInvoiceFlag()).append("' ");		
      buffer.append("pubbsFlag").append("='").append(getPubbsFlag()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BmtbBillGenSetup) ) return false;
		 BmtbBillGenSetup castOther = ( BmtbBillGenSetup ) other; 
         
		 return ( (this.getSetupNo()==castOther.getSetupNo()) || ( this.getSetupNo()!=null && castOther.getSetupNo()!=null && this.getSetupNo().equals(castOther.getSetupNo()) ) )
 && ( (this.getName()==castOther.getName()) || ( this.getName()!=null && castOther.getName()!=null && this.getName().equals(castOther.getName()) ) )
 && ( (this.getCutOffDay()==castOther.getCutOffDay()) || ( this.getCutOffDay()!=null && castOther.getCutOffDay()!=null && this.getCutOffDay().equals(castOther.getCutOffDay()) ) )
 && ( (this.getBillGenDay()==castOther.getBillGenDay()) || ( this.getBillGenDay()!=null && castOther.getBillGenDay()!=null && this.getBillGenDay().equals(castOther.getBillGenDay()) ) )
 && ( (this.getBillGenTime()==castOther.getBillGenTime()) || ( this.getBillGenTime()!=null && castOther.getBillGenTime()!=null && this.getBillGenTime().equals(castOther.getBillGenTime()) ) )
 && ( (this.getInvoiceDay()==castOther.getInvoiceDay()) || ( this.getInvoiceDay()!=null && castOther.getInvoiceDay()!=null && this.getInvoiceDay().equals(castOther.getInvoiceDay()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getPubbsFlag()==castOther.getPubbsFlag()) || ( this.getPubbsFlag()!=null && castOther.getPubbsFlag()!=null && this.getPubbsFlag().equals(castOther.getPubbsFlag()) ) )
 && ( (this.getGovtEInvoiceFlag()==castOther.getGovtEInvoiceFlag()) || ( this.getGovtEInvoiceFlag()!=null && castOther.getGovtEInvoiceFlag()!=null && this.getGovtEInvoiceFlag().equals(castOther.getGovtEInvoiceFlag()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSetupNo() == null ? 0 : this.getSetupNo().hashCode() );
         result = 37 * result + ( getName() == null ? 0 : this.getName().hashCode() );
         result = 37 * result + ( getCutOffDay() == null ? 0 : this.getCutOffDay().hashCode() );
         result = 37 * result + ( getBillGenDay() == null ? 0 : this.getBillGenDay().hashCode() );
         result = 37 * result + ( getBillGenTime() == null ? 0 : this.getBillGenTime().hashCode() );
         result = 37 * result + ( getInvoiceDay() == null ? 0 : this.getInvoiceDay().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getGovtEInvoiceFlag() == null ? 0 : this.getGovtEInvoiceFlag().hashCode() );
         result = 37 * result + ( getPubbsFlag() == null ? 0 : this.getPubbsFlag().hashCode() );
         
         return result;
   }   
}
