package com.cdgtaxi.ibs.common.model;
// Generated Jul 28, 2009 5:37:59 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.master.model.MstbMasterTable;


/**
 * FmtbArContCodeDetail generated by hbm2java
 */

public class FmtbArContCodeDetail  implements java.io.Serializable, Creatable, Updatable, Auditable {


    // Fields    

    private Integer arContCodeDetailNo;
    private int glAccount;
    private String costCentre;
    private String description;
    private Timestamp effectiveDt;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private Integer version;
    private MstbMasterTable mstbMasterTable;
    private FmtbArContCodeMaster fmtbArContCodeMaster;


    // Constructors

    /** default constructor */
    public FmtbArContCodeDetail() {
    }

	/** minimal constructor */
    public FmtbArContCodeDetail(int glAccount, String costCentre, String description) {
        this.glAccount = glAccount;
        this.costCentre = costCentre;
        this.description = description;
    }
    
    /** full constructor */
    public FmtbArContCodeDetail(int glAccount, String costCentre, String description, Timestamp effectiveDt, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, Integer version, MstbMasterTable mstbMasterTable, FmtbArContCodeMaster fmtbArContCodeMaster) {
        this.glAccount = glAccount;
        this.costCentre = costCentre;
        this.description = description;
        this.effectiveDt = effectiveDt;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.version = version;
        this.mstbMasterTable = mstbMasterTable;
        this.fmtbArContCodeMaster = fmtbArContCodeMaster;
    }
    

   
    // Property accessors

    public Integer getArContCodeDetailNo() {
        return this.arContCodeDetailNo;
    }
    
    public void setArContCodeDetailNo(Integer arContCodeDetailNo) {
        this.arContCodeDetailNo = arContCodeDetailNo;
    }

    public int getGlAccount() {
        return this.glAccount;
    }
    
    public void setGlAccount(int glAccount) {
        this.glAccount = glAccount;
    }

    public String getCostCentre() {
        return this.costCentre;
    }
    
    public void setCostCentre(String costCentre) {
        this.costCentre = costCentre;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Timestamp getEffectiveDt() {
        return this.effectiveDt;
    }
    
    public void setEffectiveDt(Timestamp effectiveDt) {
        this.effectiveDt = effectiveDt;
    }
    
    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public MstbMasterTable getMstbMasterTable() {
        return this.mstbMasterTable;
    }
    
    public void setMstbMasterTable(MstbMasterTable mstbMasterTable) {
        this.mstbMasterTable = mstbMasterTable;
    }

    public FmtbArContCodeMaster getFmtbArContCodeMaster() {
        return this.fmtbArContCodeMaster;
    }
    
    public void setFmtbArContCodeMaster(FmtbArContCodeMaster fmtbArContCodeMaster) {
        this.fmtbArContCodeMaster = fmtbArContCodeMaster;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      //buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("glAccount").append("='").append(getGlAccount()).append("' ");			
      buffer.append("costCentre").append("='").append(getCostCentre()).append("' ");			
      buffer.append("description").append("='").append(getDescription()).append("' ");			
      buffer.append("effectiveDt").append("='").append(getEffectiveDt()).append("' ");		
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FmtbArContCodeDetail) ) return false;
		 FmtbArContCodeDetail castOther = ( FmtbArContCodeDetail ) other; 
         
		 return ( (this.getArContCodeDetailNo()==castOther.getArContCodeDetailNo()) || ( this.getArContCodeDetailNo()!=null && castOther.getArContCodeDetailNo()!=null && this.getArContCodeDetailNo().equals(castOther.getArContCodeDetailNo()) ) )
 && (this.getGlAccount()==castOther.getGlAccount())
 && ( (this.getCostCentre()==castOther.getCostCentre()) || ( this.getCostCentre()!=null && castOther.getCostCentre()!=null && this.getCostCentre().equals(castOther.getCostCentre()) ) )
 && ( (this.getDescription()==castOther.getDescription()) || ( this.getDescription()!=null && castOther.getDescription()!=null && this.getDescription().equals(castOther.getDescription()) ) )
 && ( (this.getEffectiveDt()==castOther.getEffectiveDt()) || ( this.getEffectiveDt()!=null && castOther.getEffectiveDt()!=null && this.getEffectiveDt().equals(castOther.getEffectiveDt()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getMstbMasterTable()==castOther.getMstbMasterTable()) || ( this.getMstbMasterTable()!=null && castOther.getMstbMasterTable()!=null && this.getMstbMasterTable().equals(castOther.getMstbMasterTable()) ) )
 && ( (this.getFmtbArContCodeMaster()==castOther.getFmtbArContCodeMaster()) || ( this.getFmtbArContCodeMaster()!=null && castOther.getFmtbArContCodeMaster()!=null && this.getFmtbArContCodeMaster().equals(castOther.getFmtbArContCodeMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getArContCodeDetailNo() == null ? 0 : this.getArContCodeDetailNo().hashCode() );
         result = 37 * result + this.getGlAccount();
         result = 37 * result + ( getCostCentre() == null ? 0 : this.getCostCentre().hashCode() );
         result = 37 * result + ( getDescription() == null ? 0 : this.getDescription().hashCode() );
         result = 37 * result + ( getEffectiveDt() == null ? 0 : this.getEffectiveDt().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getMstbMasterTable() == null ? 0 : this.getMstbMasterTable().hashCode() );
         //result = 37 * result + ( getFmtbArContCodeMaster() == null ? 0 : this.getFmtbArContCodeMaster().hashCode() );
         return result;
   }   





}
