package com.cdgtaxi.ibs.common.model;
// Generated Apr 30, 2010 3:43:14 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Date;
import java.sql.Timestamp;

import com.cdgtaxi.ibs.acl.security.Auditable;


/**
 * FmtbNonBillableDetail generated by hbm2java
 */

public class FmtbNonBillableDetail  implements java.io.Serializable, Auditable, Creatable, Updatable {


    // Fields    

    private Integer detailNo;
    private String fareAmountTxnCode;
    private String adminFeeTxnCode;
    private String premiumAmountTxnCode;
    private Date effectiveDate;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private Integer version;
    private FmtbNonBillableMaster fmtbNonBillableMaster;
    private FmtbArContCodeMaster fmtbArContCodeMaster;


    // Constructors

    /** default constructor */
    public FmtbNonBillableDetail() {
    }

	/** minimal constructor */
    public FmtbNonBillableDetail(String fareAmountTxnCode, String adminFeeTxnCode, String premiumAmountTxnCode, Date effectiveDate) {
        this.fareAmountTxnCode = fareAmountTxnCode;
        this.adminFeeTxnCode = adminFeeTxnCode;
        this.premiumAmountTxnCode = premiumAmountTxnCode;
        this.effectiveDate = effectiveDate;
    }
    
    /** full constructor */
    public FmtbNonBillableDetail(String fareAmountTxnCode, String adminFeeTxnCode, String premiumAmounTxnCode, Date effectiveDate, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, Integer version, FmtbNonBillableMaster fmtbNonBillableMaster, FmtbArContCodeMaster fmtbArContCodeMaster) {
        this.fareAmountTxnCode = fareAmountTxnCode;
        this.adminFeeTxnCode = adminFeeTxnCode;
        this.premiumAmountTxnCode = premiumAmountTxnCode;
        this.effectiveDate = effectiveDate;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.version = version;
        this.fmtbNonBillableMaster = fmtbNonBillableMaster;
        this.fmtbArContCodeMaster = fmtbArContCodeMaster;
    }
    

   
    // Property accessors

    public Integer getDetailNo() {
        return this.detailNo;
    }
    
    public void setDetailNo(Integer detailNo) {
        this.detailNo = detailNo;
    }

    public String getFareAmountTxnCode() {
        return this.fareAmountTxnCode;
    }
    
    public void setFareAmountTxnCode(String fareAmountTxnCode) {
        this.fareAmountTxnCode = fareAmountTxnCode;
    }

    public String getAdminFeeTxnCode() {
        return this.adminFeeTxnCode;
    }
    
    public String getPremiumAmountTxnCode() {
		return premiumAmountTxnCode;
	}

	public void setPremiumAmountTxnCode(String premiumAmountTxnCode) {
		this.premiumAmountTxnCode = premiumAmountTxnCode;
	}

	public void setAdminFeeTxnCode(String adminFeeTxnCode) {
        this.adminFeeTxnCode = adminFeeTxnCode;
    }

    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public FmtbNonBillableMaster getFmtbNonBillableMaster() {
        return this.fmtbNonBillableMaster;
    }
    
    public void setFmtbNonBillableMaster(FmtbNonBillableMaster fmtbNonBillableMaster) {
        this.fmtbNonBillableMaster = fmtbNonBillableMaster;
    }

    public FmtbArContCodeMaster getFmtbArContCodeMaster() {
        return this.fmtbArContCodeMaster;
    }
    
    public void setFmtbArContCodeMaster(FmtbArContCodeMaster fmtbArContCodeMaster) {
        this.fmtbArContCodeMaster = fmtbArContCodeMaster;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("fareAmountTxnCode").append("='").append(getFareAmountTxnCode()).append("' ");			
      buffer.append("adminFeeTxnCode").append("='").append(getAdminFeeTxnCode()).append("' ");	
      buffer.append("premiumAmountTxnCode").append("='").append(getPremiumAmountTxnCode()).append("' ");		
      buffer.append("effectiveDate").append("='").append(getEffectiveDate()).append("' ");			
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FmtbNonBillableDetail) ) return false;
		 FmtbNonBillableDetail castOther = ( FmtbNonBillableDetail ) other; 
         
		 return ( (this.getDetailNo()==castOther.getDetailNo()) || ( this.getDetailNo()!=null && castOther.getDetailNo()!=null && this.getDetailNo().equals(castOther.getDetailNo()) ) )
 && ( (this.getFareAmountTxnCode()==castOther.getFareAmountTxnCode()) || ( this.getFareAmountTxnCode()!=null && castOther.getFareAmountTxnCode()!=null && this.getFareAmountTxnCode().equals(castOther.getFareAmountTxnCode()) ) )
 && ( (this.getAdminFeeTxnCode()==castOther.getAdminFeeTxnCode()) || ( this.getAdminFeeTxnCode()!=null && castOther.getAdminFeeTxnCode()!=null && this.getAdminFeeTxnCode().equals(castOther.getAdminFeeTxnCode()) ) )
 && ( (this.getPremiumAmountTxnCode()==castOther.getPremiumAmountTxnCode()) || ( this.getPremiumAmountTxnCode()!=null && castOther.getPremiumAmountTxnCode()!=null && this.getPremiumAmountTxnCode().equals(castOther.getPremiumAmountTxnCode()) ) )
 && ( (this.getEffectiveDate()==castOther.getEffectiveDate()) || ( this.getEffectiveDate()!=null && castOther.getEffectiveDate()!=null && this.getEffectiveDate().equals(castOther.getEffectiveDate()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getFmtbNonBillableMaster()==castOther.getFmtbNonBillableMaster()) || ( this.getFmtbNonBillableMaster()!=null && castOther.getFmtbNonBillableMaster()!=null && this.getFmtbNonBillableMaster().equals(castOther.getFmtbNonBillableMaster()) ) )
 && ( (this.getFmtbArContCodeMaster()==castOther.getFmtbArContCodeMaster()) || ( this.getFmtbArContCodeMaster()!=null && castOther.getFmtbArContCodeMaster()!=null && this.getFmtbArContCodeMaster().equals(castOther.getFmtbArContCodeMaster()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDetailNo() == null ? 0 : this.getDetailNo().hashCode() );
         result = 37 * result + ( getFareAmountTxnCode() == null ? 0 : this.getFareAmountTxnCode().hashCode() );
         result = 37 * result + ( getAdminFeeTxnCode() == null ? 0 : this.getAdminFeeTxnCode().hashCode() );
         result = 37 * result + ( getPremiumAmountTxnCode() == null ? 0 : this.getPremiumAmountTxnCode().hashCode() );
         result = 37 * result + ( getEffectiveDate() == null ? 0 : this.getEffectiveDate().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getFmtbNonBillableMaster() == null ? 0 : this.getFmtbNonBillableMaster().hashCode() );
         result = 37 * result + ( getFmtbArContCodeMaster() == null ? 0 : this.getFmtbArContCodeMaster().hashCode() );
         return result;
   }   
}