package com.cdgtaxi.ibs.common.model;
// Generated Mar 15, 2011 3:19:42 PM by Hibernate Tools 3.1.0.beta4

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.acl.security.Auditable;


/**
 * IttbGiroReturnReq generated by hbm2java
 */

@SuppressWarnings("serial")
public class IttbPubbsReturnReq  implements java.io.Serializable, Auditable, Creatable, Updatable {


    // Fields    

    private Long reqNo;
    private String fileName;
    private String header;
    private String status;
    private String remarks;
    private Integer version;
    private String createdBy;
    private Timestamp createdDt;
    private String updatedBy;
    private Timestamp updatedDt;
    private Set<IttbPubbsReturnDetail> ittbPubbsReturnDetails = new HashSet<IttbPubbsReturnDetail>(0);

    // Constructors

    /** default constructor */
    public IttbPubbsReturnReq() {
    }
    
    /** full constructor */
    public IttbPubbsReturnReq(String fileName, String header, String status, String remarks, Integer version, String createdBy, Timestamp createdDt, String updatedBy, Timestamp updatedDt, Set<IttbPubbsReturnDetail> ittbPubbsReturnDetails) {
        this.fileName = fileName;
        this.header = header;
        this.status = status;
        this.remarks = remarks;
        this.version = version;
        this.createdBy = createdBy;
        this.createdDt = createdDt;
        this.updatedBy = updatedBy;
        this.updatedDt = updatedDt;
        this.ittbPubbsReturnDetails = ittbPubbsReturnDetails;
    }
    

   
    // Property accessors

    public Long getReqNo() {
        return this.reqNo;
    }
    
    public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public void setReqNo(Long reqNo) {
        this.reqNo = reqNo;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public String getHeader() {
		return header;
	}

	public void setHeader(String header) {
		this.header = header;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public Set<IttbPubbsReturnDetail> getIttbPubbsReturnDetails() {
		return ittbPubbsReturnDetails;
	}

	public void setIttbPubbsReturnDetails(Set<IttbPubbsReturnDetail> ittbPubbsReturnDetails) {
		this.ittbPubbsReturnDetails = ittbPubbsReturnDetails;
	}

	/**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("fileName").append("='").append(getFileName()).append("' ");
      buffer.append("header").append("='").append(getHeader()).append("' ");
      buffer.append("status").append("='").append(getStatus()).append("' ");		
      buffer.append("remarks").append("='").append(getRemarks()).append("' ");		
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof IttbPubbsReturnReq) ) return false;
		 IttbPubbsReturnReq castOther = ( IttbPubbsReturnReq ) other; 
         
		 return ( (this.getReqNo()==castOther.getReqNo()) || ( this.getReqNo()!=null && castOther.getReqNo()!=null && this.getReqNo().equals(castOther.getReqNo()) ) )
 && ( (this.getFileName()==castOther.getFileName()) || ( this.getFileName()!=null && castOther.getFileName()!=null && this.getFileName().equals(castOther.getFileName()) ) )
 && ( (this.getHeader()==castOther.getHeader()) || ( this.getHeader()!=null && castOther.getHeader()!=null && this.getHeader().equals(castOther.getHeader()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) );
}
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getReqNo() == null ? 0 : this.getReqNo().hashCode() );
         result = 37 * result + ( getFileName() == null ? 0 : this.getFileName().hashCode() );
         result = 37 * result + ( getHeader() == null ? 0 : this.getHeader().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         return result;
   }   
}