package com.cdgtaxi.ibs.common.model;
// Generated Jul 20, 2009 4:09:23 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Timestamp;

import com.cdgtaxi.ibs.acl.security.Auditable;

/**
 * PmtbProductCreditLimit generated by hbm2java
 */
//,Auditable 
public class PmtbProductCreditLimit  implements java.io.Serializable,Creatable,Updatable{


    // Fields    

    private BigDecimal productCreditLimitNo;
    private String creditLimitType;
    private BigDecimal newCreditLimit;
    private Timestamp effectiveDtFrom;
    private Timestamp effectiveDtTo;
    private String remarks;
    private Integer version;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private PmtbProduct pmtbProduct;


    // Constructors

    /** default constructor */
    public PmtbProductCreditLimit() {
    }

	/** minimal constructor */
    public PmtbProductCreditLimit(String creditLimitType, BigDecimal newCreditLimit, Timestamp effectiveDtFrom, String remarks) {
        this.creditLimitType = creditLimitType;
        this.newCreditLimit = newCreditLimit;
        this.effectiveDtFrom = effectiveDtFrom;
        this.remarks = remarks;
    }
    
    /** full constructor */
    public PmtbProductCreditLimit(String creditLimitType, BigDecimal newCreditLimit, Timestamp effectiveDtFrom, Timestamp effectiveDtTo, String remarks, Integer version, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, PmtbProduct pmtbProduct) {
        this.creditLimitType = creditLimitType;
        this.newCreditLimit = newCreditLimit;
        this.effectiveDtFrom = effectiveDtFrom;
        this.effectiveDtTo = effectiveDtTo;
        this.remarks = remarks;
        this.version = version;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.pmtbProduct = pmtbProduct;
    }
    

   
    // Property accessors

    public BigDecimal getProductCreditLimitNo() {
        return this.productCreditLimitNo;
    }
    
    public void setProductCreditLimitNo(BigDecimal productCreditLimitNo) {
        this.productCreditLimitNo = productCreditLimitNo;
    }

    public String getCreditLimitType() {
        return this.creditLimitType;
    }
    
    public void setCreditLimitType(String creditLimitType) {
        this.creditLimitType = creditLimitType;
    }

    public BigDecimal getNewCreditLimit() {
        return this.newCreditLimit;
    }
    
    public void setNewCreditLimit(BigDecimal newCreditLimit) {
        this.newCreditLimit = newCreditLimit;
    }

    public Timestamp getEffectiveDtFrom() {
        return this.effectiveDtFrom;
    }
    
    public void setEffectiveDtFrom(Timestamp effectiveDtFrom) {
        this.effectiveDtFrom = effectiveDtFrom;
    }

    public Timestamp getEffectiveDtTo() {
        return this.effectiveDtTo;
    }
    
    public void setEffectiveDtTo(Timestamp effectiveDtTo) {
        this.effectiveDtTo = effectiveDtTo;
    }

    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public PmtbProduct getPmtbProduct() {
        return this.pmtbProduct;
    }
    
    public void setPmtbProduct(PmtbProduct pmtbProduct) {
        this.pmtbProduct = pmtbProduct;
    }
   

    /**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("creditLimitType").append("='").append(getCreditLimitType()).append("' ");			
      buffer.append("newCreditLimit").append("='").append(getNewCreditLimit()).append("' ");			
      buffer.append("effectiveDtFrom").append("='").append(getEffectiveDtFrom()).append("' ");			
      buffer.append("effectiveDtTo").append("='").append(getEffectiveDtTo()).append("' ");			
      buffer.append("remarks").append("='").append(getRemarks()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");			
      buffer.append("]");
      
      return buffer.toString();
     }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PmtbProductCreditLimit) ) return false;
		 PmtbProductCreditLimit castOther = ( PmtbProductCreditLimit ) other; 
         
		 return ( (this.getProductCreditLimitNo()==castOther.getProductCreditLimitNo()) || ( this.getProductCreditLimitNo()!=null && castOther.getProductCreditLimitNo()!=null && this.getProductCreditLimitNo().equals(castOther.getProductCreditLimitNo()) ) )
 && ( (this.getCreditLimitType()==castOther.getCreditLimitType()) || ( this.getCreditLimitType()!=null && castOther.getCreditLimitType()!=null && this.getCreditLimitType().equals(castOther.getCreditLimitType()) ) )
 && ( (this.getNewCreditLimit()==castOther.getNewCreditLimit()) || ( this.getNewCreditLimit()!=null && castOther.getNewCreditLimit()!=null && this.getNewCreditLimit().equals(castOther.getNewCreditLimit()) ) )
 && ( (this.getEffectiveDtFrom()==castOther.getEffectiveDtFrom()) || ( this.getEffectiveDtFrom()!=null && castOther.getEffectiveDtFrom()!=null && this.getEffectiveDtFrom().equals(castOther.getEffectiveDtFrom()) ) )
 && ( (this.getEffectiveDtTo()==castOther.getEffectiveDtTo()) || ( this.getEffectiveDtTo()!=null && castOther.getEffectiveDtTo()!=null && this.getEffectiveDtTo().equals(castOther.getEffectiveDtTo()) ) )
 && ( (this.getRemarks()==castOther.getRemarks()) || ( this.getRemarks()!=null && castOther.getRemarks()!=null && this.getRemarks().equals(castOther.getRemarks()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getPmtbProduct()==castOther.getPmtbProduct()) || ( this.getPmtbProduct()!=null && castOther.getPmtbProduct()!=null && this.getPmtbProduct().equals(castOther.getPmtbProduct()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         result = 37 * result + ( getProductCreditLimitNo() == null ? 0 : this.getProductCreditLimitNo().hashCode() );
         result = 37 * result + ( getCreditLimitType() == null ? 0 : this.getCreditLimitType().hashCode() );
         result = 37 * result + ( getNewCreditLimit() == null ? 0 : this.getNewCreditLimit().hashCode() );
         result = 37 * result + ( getEffectiveDtFrom() == null ? 0 : this.getEffectiveDtFrom().hashCode() );
         result = 37 * result + ( getEffectiveDtTo() == null ? 0 : this.getEffectiveDtTo().hashCode() );
         result = 37 * result + ( getRemarks() == null ? 0 : this.getRemarks().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getPmtbProduct() == null ? 0 : this.getPmtbProduct().hashCode() );
         return result;
   }   
}