package com.cdgtaxi.ibs.common.model;
// Generated Jul 20, 2009 4:09:29 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.common.model.forms.IssueProductForm;

/**
 * PmtbProduct generated by hbm2java
 */
//,Auditable

public class PmtbProduct  implements java.io.Serializable, Creatable, Updatable{


    // Fields    

    private BigDecimal productNo;
    private String cardNo;
    private String nameOnProduct;
    private BigDecimal creditLimit;
    private BigDecimal tempCreditLimit;
    private BigDecimal creditBalance;
    private Date issueDate;
    private Date expiryDate;
    private BigDecimal fixedValue;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private String cardHolderName;
    private String cardHolderTitle;
    private String cardHolderTel;
    private String cardHolderSalutation;
    private String cardHolderMobile;
    private String cardHolderEmail;
    private Integer version;
    private String waiveSubscFeeFlag;
    private Date lastSubscFeeChargeDate;
    private String currentStatus;
    private String isIndividualCard;
    private String embossFlag;
    private String smsExpirySent;
    private String smsExpiryFlag;
	private String smsTopupFlag;
    private Timestamp expiryTime;
    private Integer offlineCount;
    private BigDecimal offlineAmount;
    private BigDecimal offlineTxnAmount;
    private String embossNameOnCard;
    private String waiveIssuanceFeeFlag;
    private Date lastIssuanceFeeChargeDate;
    private PmtbProductType pmtbProductType;
    private AmtbAccount amtbAccount;
    private java.util.Date balanceExpiryDate;
    private BigDecimal cashplus;
    private BigDecimal cardValue;
    private String expiredFlag;
    private String balanceForfeitedFlag;
	private transient String transientEmbossNameOnCard;
    private transient String transientNameOnProduct;
    private String employeeId;
    
    private Set<PmtbProductCreditLimit> pmtbProductCreditLimits = new HashSet<PmtbProductCreditLimit>(0);
    private Set<PmtbProductRenew> pmtbProductRenews = new HashSet<PmtbProductRenew>(0);
    private Set<BmtbInvoiceDetail> bmtbInvoiceDetails = new HashSet<BmtbInvoiceDetail>(0);
    private Set<TmtbTxnReviewReq> tmtbTxnReviewReqs = new HashSet<TmtbTxnReviewReq>(0);
    private Set<TmtbAcquireTxn> tmtbAcquireTxns = new HashSet<TmtbAcquireTxn>(0);
    private Set<PmtbVirtualEmail> pmtbVirtualEmails = new HashSet<PmtbVirtualEmail>(0);
    private Set<PmtbProductReplacement> pmtbProductReplacements = new HashSet<PmtbProductReplacement>(0);
    private Set<PmtbProductStatus> pmtbProductStatuses = new HashSet<PmtbProductStatus>(0);
    private Set<PmtbProductRetag> pmtbProductRetags = new HashSet<PmtbProductRetag>(0);
    private Set<IttbCpLogin> ittbCpLogins = new HashSet<IttbCpLogin>(0);
    private Set<IttbCpLoginNew> ittbCpLoginsNew = new HashSet<IttbCpLoginNew>(0);
    private Set<IttbCpGuestProduct> ittbCpGuestProducts = new HashSet<IttbCpGuestProduct>(0);

    private Set<PmtbPrepaidCardTxn> pmtbPrepaidCardTxns;
    private Set<PmtbBalanceForfeiture> pmtbBalanceForfeitures;
    private Set<IttbCpCustCardIssuance> ittbCpCustCardIssuances;
    
    // Constructors

    /** default constructor */
    public PmtbProduct() {
    }

	/** minimal constructor */
    public PmtbProduct(String cardNo, Date issueDate, String waiveSubscFeeFlag) {
        this.cardNo = cardNo;
        this.issueDate = issueDate;
        this.waiveSubscFeeFlag = waiveSubscFeeFlag;
    }
    
    /** full constructor */
    public PmtbProduct(String cardNo, String nameOnProduct, BigDecimal creditLimit, BigDecimal tempCreditLimit, BigDecimal creditBalance, Date issueDate, Date expiryDate, BigDecimal fixedValue, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, String cardHolderName, String cardHolderTitle, String cardHolderTel, String cardHolderSalutation, String cardHolderMobile, String cardHolderEmail, Integer version, String waiveSubscFeeFlag, Date lastSubscFeeChargeDate, String currentStatus, String isIndividualCard, String embossFlag, String smsExpirySent, String smsExpiryFlag, String smsTopupFlag, Integer offlineCount, BigDecimal offlineAmount, BigDecimal offlineTxnAmount, String embossNameOnCard, String waiveIssuanceFeeFlag, Date lastIssuanceFeeChargeDate, PmtbProductType pmtbProductType, AmtbAccount amtbAccount, Set<PmtbProductCreditLimit> pmtbProductCreditLimits, Set<PmtbProductRenew> pmtbProductRenews, Set<BmtbInvoiceDetail> bmtbInvoiceDetails, Set<TmtbTxnReviewReq> tmtbTxnReviewReqs, Set<TmtbAcquireTxn> tmtbAcquireTxns, Set<PmtbVirtualEmail> pmtbVirtualEmails, Set<PmtbProductReplacement> pmtbProductReplacements, Set<PmtbProductStatus> pmtbProductStatuses, Set<PmtbProductRetag> pmtbProductRetags, Set<IttbCpLogin> ittbCpLogins, Set<IttbCpLoginNew> ittbCpLoginsNew, Set<IttbCpGuestProduct> ittbCpGuestProducts, Timestamp expiryTime, String employeeId) {
        this.cardNo = cardNo;
        this.nameOnProduct = nameOnProduct;
        this.creditLimit = creditLimit;
        this.tempCreditLimit = tempCreditLimit;
        this.creditBalance = creditBalance;
        this.issueDate = issueDate;
        this.expiryDate = expiryDate;
        this.fixedValue = fixedValue;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.cardHolderName = cardHolderName;
        this.cardHolderTitle = cardHolderTitle;
        this.cardHolderTel = cardHolderTel;
        this.cardHolderSalutation = cardHolderSalutation;
        this.cardHolderMobile = cardHolderMobile;
        this.cardHolderEmail = cardHolderEmail;
        this.version = version;
        this.waiveSubscFeeFlag = waiveSubscFeeFlag;
        this.lastSubscFeeChargeDate = lastSubscFeeChargeDate;
        this.currentStatus = currentStatus;
        this.isIndividualCard = isIndividualCard;
        this.embossFlag = embossFlag;
        this.smsExpirySent = smsExpirySent;
        this.smsExpiryFlag = smsExpiryFlag;
		this.smsTopupFlag = smsTopupFlag;
		
        this.offlineCount = offlineCount;
        this.offlineAmount = offlineAmount;
        this.offlineTxnAmount = offlineTxnAmount;
        this.embossNameOnCard = embossNameOnCard;
        this.waiveIssuanceFeeFlag = waiveIssuanceFeeFlag;
        this.lastIssuanceFeeChargeDate = lastIssuanceFeeChargeDate;

        this.pmtbProductType = pmtbProductType;
        this.amtbAccount = amtbAccount;
        this.pmtbProductCreditLimits = pmtbProductCreditLimits;
        this.pmtbProductRenews = pmtbProductRenews;
        this.bmtbInvoiceDetails = bmtbInvoiceDetails;
        this.tmtbTxnReviewReqs = tmtbTxnReviewReqs;
        this.tmtbAcquireTxns = tmtbAcquireTxns;
        this.pmtbVirtualEmails = pmtbVirtualEmails;
        this.pmtbProductReplacements = pmtbProductReplacements;
        this.pmtbProductStatuses = pmtbProductStatuses;
        this.pmtbProductRetags = pmtbProductRetags;
        this.ittbCpLogins = ittbCpLogins;
        this.ittbCpLoginsNew = ittbCpLoginsNew;
        this.ittbCpGuestProducts = ittbCpGuestProducts;
        this.expiryTime = expiryTime;
        this.employeeId = employeeId;
    }
    
    // Property accessors

	public BigDecimal getProductNo() {
        return this.productNo;
    }
    
	public void setProductNo(BigDecimal productNo) {
        this.productNo = productNo;
    }

    public String getCardNo() {
        return this.cardNo;
    }
    
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    public String getNameOnProduct() {
        return this.nameOnProduct;
    }
    
    public void setNameOnProduct(String nameOnProduct) {
        this.nameOnProduct = nameOnProduct;
    }

    public BigDecimal getCreditLimit() {
        return this.creditLimit;
    }
    
    public void setCreditLimit(BigDecimal creditLimit) {
        this.creditLimit = creditLimit;
    }

    public BigDecimal getTempCreditLimit() {
        return this.tempCreditLimit;
    }
    
    public void setTempCreditLimit(BigDecimal tempCreditLimit) {
        this.tempCreditLimit = tempCreditLimit;
    }

    public BigDecimal getCreditBalance() {
        return this.creditBalance;
    }
    
    public void setCreditBalance(BigDecimal creditBalance) {
        this.creditBalance = creditBalance;
    }

    public Date getIssueDate() {
        return this.issueDate;
    }
    
    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }

    public Date getExpiryDate() {
        return this.expiryDate;
    }
    
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    public BigDecimal getFixedValue() {
        return this.fixedValue;
    }
    
    public void setFixedValue(BigDecimal fixedValue) {
        this.fixedValue = fixedValue;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }
    
    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }
    
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public String getCardHolderName() {
        return this.cardHolderName;
    }
    
    public void setCardHolderName(String cardHolderName) {
        this.cardHolderName = cardHolderName;
    }

    public String getCardHolderTitle() {
        return this.cardHolderTitle;
    }
    
    public void setCardHolderTitle(String cardHolderTitle) {
        this.cardHolderTitle = cardHolderTitle;
    }

    public String getCardHolderTel() {
        return this.cardHolderTel;
    }
    
    public void setCardHolderTel(String cardHolderTel) {
        this.cardHolderTel = cardHolderTel;
    }

    public String getCardHolderSalutation() {
        return this.cardHolderSalutation;
    }
    
    public void setCardHolderSalutation(String cardHolderSalutation) {
        this.cardHolderSalutation = cardHolderSalutation;
    }

    public String getCardHolderMobile() {
        return this.cardHolderMobile;
    }
    
    public void setCardHolderMobile(String cardHolderMobile) {
        this.cardHolderMobile = cardHolderMobile;
    }

    public String getCardHolderEmail() {
        return this.cardHolderEmail;
    }
    
    public void setCardHolderEmail(String cardHolderEmail) {
        this.cardHolderEmail = cardHolderEmail;
    }

    public Integer getVersion() {
        return this.version;
    }
    
    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getWaiveSubscFeeFlag() {
        return this.waiveSubscFeeFlag;
    }
    
    public void setWaiveSubscFeeFlag(String waiveSubscFeeFlag) {
        this.waiveSubscFeeFlag = waiveSubscFeeFlag;
    }

    public Date getLastSubscFeeChargeDate() {
        return this.lastSubscFeeChargeDate;
    }
    
    public void setLastSubscFeeChargeDate(Date lastSubscFeeChargeDate) {
        this.lastSubscFeeChargeDate = lastSubscFeeChargeDate;
    }

    public String getCurrentStatus() {
        return this.currentStatus;
    }
    
    public void setCurrentStatus(String currentStatus) {
        this.currentStatus = currentStatus;
    }

    public String getIsIndividualCard() {
        return this.isIndividualCard;
    }
    
    public void setIsIndividualCard(String isIndividualCard) {
        this.isIndividualCard = isIndividualCard;
    }

    public String getEmbossFlag() {
        return this.embossFlag;
    }
    
    public void setEmbossFlag(String embossFlag) {
        this.embossFlag = embossFlag;
    }
    
    public String getSmsExpirySent() {
		return this.smsExpirySent;
	}

	public void setSmsExpirySent(String smsExpirySent) {
		this.smsExpirySent = smsExpirySent;
	}

    public String getSmsExpiryFlag() {
		return this.smsExpiryFlag;
	}

	public void setSmsExpiryFlag(String smsExpiryFlag) {
		this.smsExpiryFlag = smsExpiryFlag;
	}
	
	public String getSmsTopupFlag() {
		return this.smsTopupFlag;
	}

	public void setSmsTopupFlag(String smsTopUpFlag) {
		this.smsTopupFlag = smsTopUpFlag;
	}

	
    public PmtbProductType getPmtbProductType() {
        return this.pmtbProductType;
    }
    
    public void setPmtbProductType(PmtbProductType pmtbProductType) {
        this.pmtbProductType = pmtbProductType;
    }

    public AmtbAccount getAmtbAccount() {
        return this.amtbAccount;
    }
    
    public void setAmtbAccount(AmtbAccount amtbAccount) {
        this.amtbAccount = amtbAccount;
    }

    public Set<PmtbProductCreditLimit> getPmtbProductCreditLimits() {
        return this.pmtbProductCreditLimits;
    }
    
    public void setPmtbProductCreditLimits(Set<PmtbProductCreditLimit> pmtbProductCreditLimits) {
        this.pmtbProductCreditLimits = pmtbProductCreditLimits;
    }

    public Set<PmtbProductRenew> getPmtbProductRenews() {
        return this.pmtbProductRenews;
    }
    
    public void setPmtbProductRenews(Set<PmtbProductRenew> pmtbProductRenews) {
        this.pmtbProductRenews = pmtbProductRenews;
    }

    public Set<BmtbInvoiceDetail> getBmtbInvoiceDetails() {
        return this.bmtbInvoiceDetails;
    }
    
    public void setBmtbInvoiceDetails(Set<BmtbInvoiceDetail> bmtbInvoiceDetails) {
        this.bmtbInvoiceDetails = bmtbInvoiceDetails;
    }

    public Set<TmtbTxnReviewReq> getTmtbTxnReviewReqs() {
        return this.tmtbTxnReviewReqs;
    }
    
    public void setTmtbTxnReviewReqs(Set<TmtbTxnReviewReq> tmtbTxnReviewReqs) {
        this.tmtbTxnReviewReqs = tmtbTxnReviewReqs;
    }

    public Set<TmtbAcquireTxn> getTmtbAcquireTxns() {
        return this.tmtbAcquireTxns;
    }
    
    public void setTmtbAcquireTxns(Set<TmtbAcquireTxn> tmtbAcquireTxns) {
        this.tmtbAcquireTxns = tmtbAcquireTxns;
    }
    
    public Set<PmtbVirtualEmail> getPmtbVirtualEmails() {
        return this.pmtbVirtualEmails;
    }
    
    public void setPmtbVirtualEmails(Set<PmtbVirtualEmail> pmtbVirtualEmails) {
        this.pmtbVirtualEmails = pmtbVirtualEmails;
    }

    public Set<PmtbProductReplacement> getPmtbProductReplacements() {
        return this.pmtbProductReplacements;
    }
    
    public void setPmtbProductReplacements(Set<PmtbProductReplacement> pmtbProductReplacements) {
        this.pmtbProductReplacements = pmtbProductReplacements;
    }

    public Set<PmtbProductStatus> getPmtbProductStatuses() {
        return this.pmtbProductStatuses;
    }
    
    public void setPmtbProductStatuses(Set<PmtbProductStatus> pmtbProductStatuses) {
        this.pmtbProductStatuses = pmtbProductStatuses;
    }

    public Set<PmtbProductRetag> getPmtbProductRetags() {
        return this.pmtbProductRetags;
    }
    
    public void setPmtbProductRetags(Set<PmtbProductRetag> pmtbProductRetags) {
        this.pmtbProductRetags = pmtbProductRetags;
    }
   
    public Set<IttbCpLogin> getIttbCpLogins() {
        return this.ittbCpLogins;
    }
    
    public void setIttbCpLogins(Set<IttbCpLogin> ittbCpLogins) {
        this.ittbCpLogins = ittbCpLogins;
    }
    
    public Set<IttbCpLoginNew> getIttbCpLoginsNew() {
        return this.ittbCpLoginsNew;
    }
    
    public void setIttbCpLoginsNew(Set<IttbCpLoginNew> ittbCpLoginsNew) {
        this.ittbCpLoginsNew = ittbCpLoginsNew;
    }
    
    public Set<IttbCpGuestProduct> getIttbCpGuestProducts() {
        return this.ittbCpGuestProducts;
    }
    
    public void setIttbCpGuestProducts(Set<IttbCpGuestProduct> ittbCpGuestProducts) {
        this.ittbCpGuestProducts = ittbCpGuestProducts;
    }
    
    public Timestamp getExpiryTime() {
		return expiryTime;
	}

	public void setExpiryTime(Timestamp expiryTime) {
		this.expiryTime = expiryTime;
	}
	
    public Integer getOfflineCount() {
		return offlineCount;
	}

	public void setOfflineCount(Integer offlineCount) {
		this.offlineCount = offlineCount;
	}

	public BigDecimal getOfflineAmount() {
		return offlineAmount;
	}

	public void setOfflineAmount(BigDecimal offlineAmount) {
		this.offlineAmount = offlineAmount;
	}

	public BigDecimal getOfflineTxnAmount() {
		return offlineTxnAmount;
	}

	public void setOfflineTxnAmount(BigDecimal offlineTxnAmount) {
		this.offlineTxnAmount = offlineTxnAmount;
	}

	public String getEmbossNameOnCard() {
		return embossNameOnCard;
	}

	public void setEmbossNameOnCard(String embossNameOnCard) {
		this.embossNameOnCard = embossNameOnCard;
	}
	
	public String getWaiveIssuanceFeeFlag() {
		return waiveIssuanceFeeFlag;
	}

	public void setWaiveIssuanceFeeFlag(String waiveIssuanceFeeFlag) {
		this.waiveIssuanceFeeFlag = waiveIssuanceFeeFlag;
	}
	
	public Date getLastIssuanceFeeChargeDate() {
	    return this.lastIssuanceFeeChargeDate;
	}
	    
	public void setLastIssuanceFeeChargeDate(Date lastIssuanceFeeChargeDate) {
		this.lastIssuanceFeeChargeDate = lastIssuanceFeeChargeDate;
	}

   public java.util.Date getBalanceExpiryDate() {
		return balanceExpiryDate;
	
   }

	public void setBalanceExpiryDate(java.util.Date balanceExpiryDate) {
		this.balanceExpiryDate = balanceExpiryDate;
	}
	
	public BigDecimal getCashplus() {
		return cashplus;
	}

	public void setCashplus(BigDecimal cashplus) {
		this.cashplus = cashplus;
	}

	public BigDecimal getCardValue() {
		return cardValue;
	}

	public void setCardValue(BigDecimal cardValue) {
		this.cardValue = cardValue;
	}
	
    public String getExpiredFlag() {
		return expiredFlag;
	}

	public void setExpiredFlag(String expiredFlag) {
		this.expiredFlag = expiredFlag;
	}

	public String getBalanceForfeitedFlag() {
		return balanceForfeitedFlag;
	}

	public void setBalanceForfeitedFlag(String balanceForfeitedFlag) {
		this.balanceForfeitedFlag = balanceForfeitedFlag;
	}

	public String getTransientEmbossNameOnCard() {
		return transientEmbossNameOnCard;
	}

	public String getTransientNameOnProduct() {
		return transientNameOnProduct;
	}

	public void setTransientEmbossNameOnCard(String transientEmbossNameOnCard) {
		this.transientEmbossNameOnCard = transientEmbossNameOnCard;
	}

	public void setTransientNameOnProduct(String transientNameOnProduct) {
		this.transientNameOnProduct = transientNameOnProduct;
	}

	public Set<PmtbPrepaidCardTxn> getPmtbPrepaidCardTxns() {
		return pmtbPrepaidCardTxns;
	}

	public void setPmtbPrepaidCardTxns(Set<PmtbPrepaidCardTxn> pmtbPrepaidCardTxns) {
		this.pmtbPrepaidCardTxns = pmtbPrepaidCardTxns;
	}

	public Set<PmtbBalanceForfeiture> getPmtbBalanceForfeitures() {
		return pmtbBalanceForfeitures;
	}

	public void setPmtbBalanceForfeitures(Set<PmtbBalanceForfeiture> pmtbBalanceForfeitures) {
		this.pmtbBalanceForfeitures = pmtbBalanceForfeitures;
	}

	public String getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	/**
     * toString
     * @return String
     */
     public String toString() {
	  StringBuffer buffer = new StringBuffer();

      buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
      buffer.append("cardNo").append("='").append(getCardNo()).append("' ");			
      buffer.append("nameOnProduct").append("='").append(getNameOnProduct()).append("' ");			
      buffer.append("creditLimit").append("='").append(getCreditLimit()).append("' ");			
      buffer.append("tempCreditLimit").append("='").append(getTempCreditLimit()).append("' ");			
      buffer.append("creditBalance").append("='").append(getCreditBalance()).append("' ");			
      buffer.append("issueDate").append("='").append(getIssueDate()).append("' ");			
      buffer.append("expiryDate").append("='").append(getExpiryDate()).append("' ");			
      buffer.append("fixedValue").append("='").append(getFixedValue()).append("' ");			
      buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");			
      buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");			
      buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");			
      buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");			
      buffer.append("cardHolderName").append("='").append(getCardHolderName()).append("' ");			
      buffer.append("cardHolderTitle").append("='").append(getCardHolderTitle()).append("' ");			
      buffer.append("cardHolderTel").append("='").append(getCardHolderTel()).append("' ");			
      buffer.append("cardHolderSalutation").append("='").append(getCardHolderSalutation()).append("' ");			
      buffer.append("cardHolderMobile").append("='").append(getCardHolderMobile()).append("' ");			
      buffer.append("cardHolderEmail").append("='").append(getCardHolderEmail()).append("' ");			
      buffer.append("version").append("='").append(getVersion()).append("' ");			
      buffer.append("waiveSubscFeeFlag").append("='").append(getWaiveSubscFeeFlag()).append("' ");			
      buffer.append("lastSubscFeeChargeDate").append("='").append(getLastSubscFeeChargeDate()).append("' ");			
      buffer.append("currentStatus").append("='").append(getCurrentStatus()).append("' ");			
      buffer.append("isIndividualCard").append("='").append(getIsIndividualCard()).append("' ");			
      buffer.append("embossFlag").append("='").append(getEmbossFlag()).append("' ");
      buffer.append("smsExpirySent").append("='").append(getSmsExpirySent()).append("' ");
      buffer.append("smsExpiryFlag").append("='").append(getSmsExpiryFlag()).append("' ");
	  buffer.append("smsTopupFlag").append("='").append(getSmsTopupFlag()).append("' ");
      buffer.append("expiryTime").append("='").append(getExpiryTime()).append("' ");

      buffer.append("offlineCount").append("='").append(getOfflineCount()).append("' ");
      buffer.append("offlineAmount").append("='").append(getOfflineAmount()).append("' ");
      buffer.append("offlineTxnAmount").append("='").append(getOfflineTxnAmount()).append("' ");
      buffer.append("embossNameOnCard").append("='").append(getEmbossNameOnCard()).append("' ");
      buffer.append("waiveIssuanceFeeFlag").append("='").append(getWaiveIssuanceFeeFlag()).append("' ");
      buffer.append("lastIssuanceFeeChargeDate").append("='").append(getLastIssuanceFeeChargeDate()).append("' ");
      buffer.append("balanceExpiryDate").append("='").append(getBalanceExpiryDate()).append("' ");
      buffer.append("expiredFlag").append("='").append(getExpiredFlag()).append("' ");
      buffer.append("employeeId").append("='").append(getEmployeeId()).append("' ");
      
      buffer.append("]");
      
      return buffer.toString();
     }




public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PmtbProduct) ) return false;
		 PmtbProduct castOther = ( PmtbProduct ) other; 
         
		 return ( (this.getProductNo()==castOther.getProductNo()) || ( this.getProductNo()!=null && castOther.getProductNo()!=null && this.getProductNo().equals(castOther.getProductNo()) ) )
 && ( (this.getCardNo()==castOther.getCardNo()) || ( this.getCardNo()!=null && castOther.getCardNo()!=null && this.getCardNo().equals(castOther.getCardNo()) ) )
 && ( (this.getNameOnProduct()==castOther.getNameOnProduct()) || ( this.getNameOnProduct()!=null && castOther.getNameOnProduct()!=null && this.getNameOnProduct().equals(castOther.getNameOnProduct()) ) )
 && ( (this.getCreditLimit()==castOther.getCreditLimit()) || ( this.getCreditLimit()!=null && castOther.getCreditLimit()!=null && this.getCreditLimit().equals(castOther.getCreditLimit()) ) )
 && ( (this.getTempCreditLimit()==castOther.getTempCreditLimit()) || ( this.getTempCreditLimit()!=null && castOther.getTempCreditLimit()!=null && this.getTempCreditLimit().equals(castOther.getTempCreditLimit()) ) )
 && ( (this.getCreditBalance()==castOther.getCreditBalance()) || ( this.getCreditBalance()!=null && castOther.getCreditBalance()!=null && this.getCreditBalance().equals(castOther.getCreditBalance()) ) )
 && ( (this.getIssueDate()==castOther.getIssueDate()) || ( this.getIssueDate()!=null && castOther.getIssueDate()!=null && this.getIssueDate().equals(castOther.getIssueDate()) ) )
 && ( (this.getExpiryDate()==castOther.getExpiryDate()) || ( this.getExpiryDate()!=null && castOther.getExpiryDate()!=null && this.getExpiryDate().equals(castOther.getExpiryDate()) ) )
 && ( (this.getFixedValue()==castOther.getFixedValue()) || ( this.getFixedValue()!=null && castOther.getFixedValue()!=null && this.getFixedValue().equals(castOther.getFixedValue()) ) )
 && ( (this.getCreatedDt()==castOther.getCreatedDt()) || ( this.getCreatedDt()!=null && castOther.getCreatedDt()!=null && this.getCreatedDt().equals(castOther.getCreatedDt()) ) )
 && ( (this.getCreatedBy()==castOther.getCreatedBy()) || ( this.getCreatedBy()!=null && castOther.getCreatedBy()!=null && this.getCreatedBy().equals(castOther.getCreatedBy()) ) )
 && ( (this.getUpdatedDt()==castOther.getUpdatedDt()) || ( this.getUpdatedDt()!=null && castOther.getUpdatedDt()!=null && this.getUpdatedDt().equals(castOther.getUpdatedDt()) ) )
 && ( (this.getUpdatedBy()==castOther.getUpdatedBy()) || ( this.getUpdatedBy()!=null && castOther.getUpdatedBy()!=null && this.getUpdatedBy().equals(castOther.getUpdatedBy()) ) )
 && ( (this.getCardHolderName()==castOther.getCardHolderName()) || ( this.getCardHolderName()!=null && castOther.getCardHolderName()!=null && this.getCardHolderName().equals(castOther.getCardHolderName()) ) )
 && ( (this.getCardHolderTitle()==castOther.getCardHolderTitle()) || ( this.getCardHolderTitle()!=null && castOther.getCardHolderTitle()!=null && this.getCardHolderTitle().equals(castOther.getCardHolderTitle()) ) )
 && ( (this.getCardHolderTel()==castOther.getCardHolderTel()) || ( this.getCardHolderTel()!=null && castOther.getCardHolderTel()!=null && this.getCardHolderTel().equals(castOther.getCardHolderTel()) ) )
 && ( (this.getCardHolderSalutation()==castOther.getCardHolderSalutation()) || ( this.getCardHolderSalutation()!=null && castOther.getCardHolderSalutation()!=null && this.getCardHolderSalutation().equals(castOther.getCardHolderSalutation()) ) )
 && ( (this.getCardHolderMobile()==castOther.getCardHolderMobile()) || ( this.getCardHolderMobile()!=null && castOther.getCardHolderMobile()!=null && this.getCardHolderMobile().equals(castOther.getCardHolderMobile()) ) )
 && ( (this.getCardHolderEmail()==castOther.getCardHolderEmail()) || ( this.getCardHolderEmail()!=null && castOther.getCardHolderEmail()!=null && this.getCardHolderEmail().equals(castOther.getCardHolderEmail()) ) )
 && ( (this.getVersion()==castOther.getVersion()) || ( this.getVersion()!=null && castOther.getVersion()!=null && this.getVersion().equals(castOther.getVersion()) ) )
 && ( (this.getWaiveSubscFeeFlag()==castOther.getWaiveSubscFeeFlag()) || ( this.getWaiveSubscFeeFlag()!=null && castOther.getWaiveSubscFeeFlag()!=null && this.getWaiveSubscFeeFlag().equals(castOther.getWaiveSubscFeeFlag()) ) )
 && ( (this.getLastSubscFeeChargeDate()==castOther.getLastSubscFeeChargeDate()) || ( this.getLastSubscFeeChargeDate()!=null && castOther.getLastSubscFeeChargeDate()!=null && this.getLastSubscFeeChargeDate().equals(castOther.getLastSubscFeeChargeDate()) ) )
 && ( (this.getCurrentStatus()==castOther.getCurrentStatus()) || ( this.getCurrentStatus()!=null && castOther.getCurrentStatus()!=null && this.getCurrentStatus().equals(castOther.getCurrentStatus()) ) )
 && ( (this.getIsIndividualCard()==castOther.getIsIndividualCard()) || ( this.getIsIndividualCard()!=null && castOther.getIsIndividualCard()!=null && this.getIsIndividualCard().equals(castOther.getIsIndividualCard()) ) )
 && ( (this.getEmbossFlag()==castOther.getEmbossFlag()) || ( this.getEmbossFlag()!=null && castOther.getEmbossFlag()!=null && this.getEmbossFlag().equals(castOther.getEmbossFlag()) ) )
 && ( (this.getSmsExpirySent() == castOther.getSmsExpirySent()) || (this.getSmsExpirySent() != null && castOther.getSmsExpirySent() != null && this.getSmsExpirySent().equals(castOther.getSmsExpirySent())))
 && ( (this.getSmsExpiryFlag() == castOther.getSmsExpiryFlag()) || (this.getSmsExpiryFlag() != null && castOther.getSmsExpiryFlag() != null && this.getSmsExpiryFlag().equals(castOther.getSmsExpiryFlag())))
 && ( (this.getSmsTopupFlag() == castOther.getSmsTopupFlag()) || (this.getSmsTopupFlag() != null && castOther.getSmsTopupFlag() != null && this.getSmsTopupFlag().equals(castOther.getSmsTopupFlag())))	
 && ( (this.getPmtbProductType()==castOther.getPmtbProductType()) || ( this.getPmtbProductType()!=null && castOther.getPmtbProductType()!=null && this.getPmtbProductType().equals(castOther.getPmtbProductType()) ) )
 && ( (this.getAmtbAccount()==castOther.getAmtbAccount()) || ( this.getAmtbAccount()!=null && castOther.getAmtbAccount()!=null && this.getAmtbAccount().equals(castOther.getAmtbAccount()) ) )
 && ( (this.getExpiryTime()==castOther.getExpiryTime()) || ( this.getExpiryTime()!=null && castOther.getExpiryTime()!=null && this.getExpiryTime().equals(castOther.getExpiryTime()) ) )
 && ( (this.getOfflineCount()==castOther.getOfflineCount()) || ( this.getOfflineCount()!=null && castOther.getOfflineCount()!=null && this.getOfflineCount().equals(castOther.getOfflineCount()) ) )
 && ( (this.getOfflineAmount()==castOther.getOfflineAmount()) || ( this.getOfflineAmount()!=null && castOther.getOfflineAmount()!=null && this.getOfflineAmount().equals(castOther.getOfflineAmount()) ) )
 && ( (this.getOfflineTxnAmount()==castOther.getOfflineTxnAmount()) || ( this.getOfflineTxnAmount()!=null && castOther.getOfflineTxnAmount()!=null && this.getOfflineTxnAmount().equals(castOther.getOfflineTxnAmount()) ) )
 && ( (this.getEmbossNameOnCard()==castOther.getEmbossNameOnCard()) || ( this.getEmbossNameOnCard()!=null && castOther.getEmbossNameOnCard()!=null && this.getEmbossNameOnCard().equals(castOther.getEmbossNameOnCard()) ) )
 && ( (this.getWaiveIssuanceFeeFlag()==castOther.getWaiveIssuanceFeeFlag()) || ( this.getWaiveIssuanceFeeFlag()!=null && castOther.getWaiveIssuanceFeeFlag()!=null && this.getWaiveIssuanceFeeFlag().equals(castOther.getWaiveIssuanceFeeFlag()) ) )
 && ( (this.getLastIssuanceFeeChargeDate()==castOther.getLastIssuanceFeeChargeDate()) || ( this.getLastIssuanceFeeChargeDate()!=null && castOther.getLastIssuanceFeeChargeDate()!=null && this.getLastIssuanceFeeChargeDate().equals(castOther.getLastIssuanceFeeChargeDate()) ) )
 && ( (this.getEmployeeId()==castOther.getEmployeeId()) || ( this.getEmployeeId()!=null && castOther.getEmployeeId()!=null && this.getEmployeeId().equals(castOther.getEmployeeId()) ) )
 && ( (this.getBalanceExpiryDate()==castOther.getBalanceExpiryDate()) || ( this.getBalanceExpiryDate()!=null && castOther.getBalanceExpiryDate()!=null && this.getBalanceExpiryDate().equals(castOther.getBalanceExpiryDate()) )
 && ( (this.getExpiredFlag()==castOther.getExpiredFlag()) || ( this.getExpiredFlag()!=null && castOther.getExpiredFlag()!=null && this.getExpiredFlag().equals(castOther.getExpiredFlag())))
	);
		   

}
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProductNo() == null ? 0 : this.getProductNo().hashCode() );
         result = 37 * result + ( getCardNo() == null ? 0 : this.getCardNo().hashCode() );
         result = 37 * result + ( getNameOnProduct() == null ? 0 : this.getNameOnProduct().hashCode() );
         result = 37 * result + ( getCreditLimit() == null ? 0 : this.getCreditLimit().hashCode() );
         result = 37 * result + ( getTempCreditLimit() == null ? 0 : this.getTempCreditLimit().hashCode() );
         result = 37 * result + ( getCreditBalance() == null ? 0 : this.getCreditBalance().hashCode() );
         result = 37 * result + ( getIssueDate() == null ? 0 : this.getIssueDate().hashCode() );
         result = 37 * result + ( getExpiryDate() == null ? 0 : this.getExpiryDate().hashCode() );
         result = 37 * result + ( getFixedValue() == null ? 0 : this.getFixedValue().hashCode() );
         result = 37 * result + ( getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode() );
         result = 37 * result + ( getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode() );
         result = 37 * result + ( getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode() );
         result = 37 * result + ( getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode() );
         result = 37 * result + ( getCardHolderName() == null ? 0 : this.getCardHolderName().hashCode() );
         result = 37 * result + ( getCardHolderTitle() == null ? 0 : this.getCardHolderTitle().hashCode() );
         result = 37 * result + ( getCardHolderTel() == null ? 0 : this.getCardHolderTel().hashCode() );
         result = 37 * result + ( getCardHolderSalutation() == null ? 0 : this.getCardHolderSalutation().hashCode() );
         result = 37 * result + ( getCardHolderMobile() == null ? 0 : this.getCardHolderMobile().hashCode() );
         result = 37 * result + ( getCardHolderEmail() == null ? 0 : this.getCardHolderEmail().hashCode() );
         result = 37 * result + ( getVersion() == null ? 0 : this.getVersion().hashCode() );
         result = 37 * result + ( getWaiveSubscFeeFlag() == null ? 0 : this.getWaiveSubscFeeFlag().hashCode() );
         result = 37 * result + ( getLastSubscFeeChargeDate() == null ? 0 : this.getLastSubscFeeChargeDate().hashCode() );
         result = 37 * result + ( getCurrentStatus() == null ? 0 : this.getCurrentStatus().hashCode() );
         result = 37 * result + ( getIsIndividualCard() == null ? 0 : this.getIsIndividualCard().hashCode() );
         result = 37 * result + ( getEmbossFlag() == null ? 0 : this.getEmbossFlag().hashCode() );
         result = 37 * result + ( getSmsExpirySent() == null ? 0 : this.getSmsExpirySent().hashCode());
         result = 37 * result + ( getSmsExpiryFlag() == null ? 0 : this.getSmsExpiryFlag().hashCode());
 		 result = 37 * result + ( getSmsTopupFlag() == null ? 0 : this.getSmsTopupFlag().hashCode());
         result = 37 * result + ( getPmtbProductType() == null ? 0 : this.getPmtbProductType().hashCode() );
         result = 37 * result + ( getExpiryTime() == null ? 0 : this.getExpiryTime().hashCode() );
        
         result = 37 * result + ( getOfflineCount() == null ? 0 : this.getOfflineCount().hashCode() );
         result = 37 * result + ( getOfflineAmount() == null ? 0 : this.getOfflineAmount().hashCode() );
         result = 37 * result + ( getOfflineTxnAmount() == null ? 0 : this.getOfflineTxnAmount().hashCode() );
         result = 37 * result + ( getEmbossNameOnCard() == null ? 0 : this.getEmbossNameOnCard().hashCode() );
         result = 37 * result + ( getWaiveIssuanceFeeFlag() == null ? 0 : this.getWaiveIssuanceFeeFlag().hashCode() );
         result = 37 * result + ( getLastIssuanceFeeChargeDate() == null ? 0 : this.getLastIssuanceFeeChargeDate().hashCode() );
         result = 37 * result + ( getBalanceExpiryDate() == null ? 0 : this.getBalanceExpiryDate().hashCode() );
         result = 37 * result + ( getExpiredFlag() == null ? 0 : this.getExpiredFlag().hashCode() );
         result = 37 * result + ( getEmployeeId() == null ? 0 : this.getEmployeeId().hashCode());
         
         // Removed by Rodney
         //result = 37 * result + ( getAmtbAccount() == null ? 0 : this.getAmtbAccount().hashCode() );
         return result;
   }
   
   
   
   public static PmtbProduct buildProduct(IssueProductForm form){
	   
	   PmtbProduct product = new PmtbProduct();
	   product.setAmtbAccount(form.getAmtbAccount());
	   product.setPmtbProductType(form.getPmtbProductType());
	   product.setExpiryDate(form.getExpiryDate());
	   product.setCreditLimit(form.getCreditLimit());
	   product.setFixedValue(form.getFixedValue());
	   product.setExpiryDate(form.getExpiryDate());
	   product.setExpiryTime(form.getExpiryTime());
	   product.setNameOnProduct(form.getNameOnProduct());
	   product.setCardHolderMobile(form.getCardHolderMobile());
	   product.setCardHolderEmail(form.getCardHolderEmail());
	   product.setCardHolderTel(form.getCardHolderTel());
	   product.setCardHolderName(form.getCardHolderName());
	   product.setCardHolderTitle(form.getCardHolderTitle());
	   product.setCardHolderSalutation(form.getCardHolderSalutation());
	   product.setSmsExpiryFlag(form.getSmsExpiryFlag());
	   product.setSmsTopupFlag(form.getSmsTopupFlag());
	 
	   product.setOfflineCount(form.getOfflineCount());
	   product.setOfflineAmount(form.getOfflineAmount());
	   product.setOfflineTxnAmount(form.getOfflineTxnAmount());
	   product.setEmbossNameOnCard(form.getEmbossNameOnCard());
	   product.setWaiveIssuanceFeeFlag(form.getWaiveIssuanceFeeFlag());

	   product.setWaiveSubscFeeFlag(form.getWaiveSubscFeeFlag());
	   product.setIsIndividualCard(form.getIsIndividualCard());
	   product.setCardValue(form.getCardValue());
	   product.setCashplus(form.getCashplus());
	  
	   product.setEmployeeId(form.getEmployeeId());
	   
	   return product;

   }
   
   
   public static PmtbProduct buildProduct(PmtbIssuanceReqCard card){
	   
	   PmtbProduct product = new PmtbProduct();
	   product.setAmtbAccount(card.getAmtbAccount());
	   product.setPmtbProductType(card.getPmtbProductType());
	   product.setExpiryDate(card.getExpiryDate());
	   product.setCreditLimit(card.getCreditLimit());
	   product.setFixedValue(card.getFixedValue());
	   product.setExpiryDate(card.getExpiryDate());
	   product.setExpiryTime(card.getExpiryTime());
	   product.setNameOnProduct(card.getNameOnProduct());
	   product.setCardHolderMobile(card.getCardHolderMobile());
	   product.setCardHolderEmail(card.getCardHolderEmail());
	   product.setCardHolderTel(card.getCardHolderTel());
	   product.setCardHolderName(card.getCardHolderName());
	   product.setCardHolderTitle(card.getCardHolderTitle());
	   product.setCardHolderSalutation(card.getCardHolderSalutation());
	   product.setSmsExpiryFlag(card.getSmsExpiryFlag());
	   product.setSmsTopupFlag(card.getSmsTopupFlag());
	 
	   product.setOfflineCount(card.getOfflineCount());
	   product.setOfflineAmount(card.getOfflineAmount());
	   product.setOfflineTxnAmount(card.getOfflineTxnAmount());
	   product.setEmbossNameOnCard(card.getEmbossNameOnCard());
	   product.setWaiveIssuanceFeeFlag(card.getWaiveIssuanceFeeFlag());

	   product.setWaiveSubscFeeFlag(card.getWaiveSubscFeeFlag());
	   product.setIsIndividualCard(card.getIsIndividualCard());
	   product.setCardValue(card.getCardValue());
	   product.setCashplus(card.getCashplus());
	   product.setBalanceExpiryDate(card.getBalanceExpiryDate());
	 
	   return product;
	
   }

	public Set<IttbCpCustCardIssuance> getIttbCpCustCardIssuances() {
		return ittbCpCustCardIssuances;
	}
	
	public void setIttbCpCustCardIssuances(Set<IttbCpCustCardIssuance> ittbCpCustCardIssuances) {
		this.ittbCpCustCardIssuances = ittbCpCustCardIssuances;
	}
   
   
   
   
}