package com.cdgtaxi.ibs.common.model;
// Generated Mar 31, 2010 6:18:23 PM by Hibernate Tools 3.1.0.beta4

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

import com.cdgtaxi.ibs.acl.security.Auditable;
import com.cdgtaxi.ibs.master.model.MstbAcquirer;
import com.cdgtaxi.ibs.report.dto.NonBillableBatchDto;


/**
 * TmtbNonBillableBatch generated by hbm2java
 */

public class TmtbNonBillableBatch implements java.io.Serializable, Auditable, Creatable, Updatable {


    // Fields    

    private Long batchId;
    private String batchNo;
    private Date settlementDate;
    private String status;
    private String mid;
    private String tid;
    private long txnCount;
    private BigDecimal txnAmt;
    private BigDecimal refundAmt;
    private BigDecimal refundReverseAmt;
    private BigDecimal chargebackAmt;
    private BigDecimal chargebackReverseAmt;
    private BigDecimal markup;
    private BigDecimal commission;
    private BigDecimal schemeFee;
    private BigDecimal interchange;
    private BigDecimal otherCreditAmt;
    private BigDecimal otherDebitAmt;
    private Long creditCount;
    private BigDecimal creditAmt;
    private Timestamp createdDt;
    private String createdBy;
    private Timestamp updatedDt;
    private String updatedBy;
    private Integer version;
    private String completeStatus;
    private MstbAcquirer mstbAcquirer;
    private Set<TmtbNonBillableTxn> tmtbNonBillableTxns = new HashSet<TmtbNonBillableTxn>(0);
    private Set<BmtbBankPaymentDetail> bmtbBankPaymentDetails = new HashSet<BmtbBankPaymentDetail>(0);
    private String fileName;
    private String uploadDtString;
    
    private BigDecimal premiumAmount;
    private BigDecimal premiumGst;

    // Constructors

    /**
     * default constructor
     */
    public TmtbNonBillableBatch() {
    }

    /**
     * minimal constructor
     */
    public TmtbNonBillableBatch(String batchNo, Date settlementDate, String status, long txnCount, BigDecimal txnAmt) {
        this.batchNo = batchNo;
        this.settlementDate = settlementDate;
        this.status = status;
        this.txnCount = txnCount;
        this.txnAmt = txnAmt;
    }

    public TmtbNonBillableBatch(Long batchId, String batchNo, Date settlementDate, String status, String mid, String tid, long txnCount, BigDecimal txnAmt, BigDecimal refundAmt, BigDecimal refundReverseAmt, BigDecimal chargebackAmt, BigDecimal chargebackReverseAmt, BigDecimal markup, BigDecimal commission, BigDecimal schemeFee, BigDecimal interchange, BigDecimal otherCreditAmt, BigDecimal otherDebitAmt, Long creditCount, BigDecimal creditAmt, Timestamp createdDt, String createdBy, Timestamp updatedDt, String updatedBy, Integer version, String completeStatus, MstbAcquirer mstbAcquirer, Set<TmtbNonBillableTxn> tmtbNonBillableTxns, Set<BmtbBankPaymentDetail> bmtbBankPaymentDetails, String fileName, String uploadDtString, BigDecimal premiumAmount, BigDecimal premiumGst) {
        this.batchId = batchId;
        this.batchNo = batchNo;
        this.settlementDate = settlementDate;
        this.status = status;
        this.mid = mid;
        this.tid = tid;
        this.txnCount = txnCount;
        this.txnAmt = txnAmt;
        this.refundAmt = refundAmt;
        this.refundReverseAmt = refundReverseAmt;
        this.chargebackAmt = chargebackAmt;
        this.chargebackReverseAmt = chargebackReverseAmt;
        this.markup = markup;
        this.commission = commission;
        this.schemeFee = schemeFee;
        this.interchange = interchange;
        this.otherCreditAmt = otherCreditAmt;
        this.otherDebitAmt = otherDebitAmt;
        this.creditCount = creditCount;
        this.creditAmt = creditAmt;
        this.createdDt = createdDt;
        this.createdBy = createdBy;
        this.updatedDt = updatedDt;
        this.updatedBy = updatedBy;
        this.version = version;
        this.completeStatus = completeStatus;
        this.mstbAcquirer = mstbAcquirer;
        this.tmtbNonBillableTxns = tmtbNonBillableTxns;
        this.bmtbBankPaymentDetails = bmtbBankPaymentDetails;
        this.fileName = fileName;
        this.uploadDtString = uploadDtString;
        
        this.premiumAmount = premiumAmount;
        this.premiumGst = premiumGst;
    }

    /**
     * full constructor
     */


    public TmtbNonBillableBatch(NonBillableBatchDto dto) {
        this.batchId = dto.getBatchId();
        this.batchNo = dto.getBatchNo();
        this.settlementDate = dto.getSettlementDate();
        this.tid = dto.getTid();
        this.txnCount = dto.getTxnCount();
        this.txnAmt = dto.getTxnAmt();
        this.creditCount = dto.getCreditCount();
        this.creditAmt = dto.getCreditAmt();
    }

    // Property accessors

    public Long getBatchId() {
        return batchId;
    }

    public void setBatchId(Long batchId) {
        this.batchId = batchId;
    }

    public String getBatchNo() {
        return this.batchNo;
    }

    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo;
    }

    public Date getSettlementDate() {
        return this.settlementDate;
    }

    public void setSettlementDate(Date settlementDate) {
        this.settlementDate = settlementDate;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getMid() {
        return this.mid;
    }

    public void setMid(String mid) {
        this.mid = mid;
    }

    public String getTid() {
        return this.tid;
    }

    public void setTid(String tid) {
        this.tid = tid;
    }

    public long getTxnCount() {
        return this.txnCount;
    }

    public void setTxnCount(long txnCount) {
        this.txnCount = txnCount;
    }

    public BigDecimal getTxnAmt() {
        return this.txnAmt;
    }

    public void setTxnAmt(BigDecimal txnAmt) {
        this.txnAmt = txnAmt;
    }

    public BigDecimal getRefundAmt() {
        return refundAmt;
    }

    public void setRefundAmt(BigDecimal refundAmt) {
        this.refundAmt = refundAmt;
    }

    public BigDecimal getRefundReverseAmt() {
        return refundReverseAmt;
    }

    public void setRefundReverseAmt(BigDecimal refundReverseAmt) {
        this.refundReverseAmt = refundReverseAmt;
    }

    public BigDecimal getChargebackAmt() {
        return chargebackAmt;
    }

    public void setChargebackAmt(BigDecimal chargebackAmt) {
        this.chargebackAmt = chargebackAmt;
    }

    public BigDecimal getChargebackReverseAmt() {
        return chargebackReverseAmt;
    }

    public void setChargebackReverseAmt(BigDecimal chargebackReverseAmt) {
        this.chargebackReverseAmt = chargebackReverseAmt;
    }

    public BigDecimal getMarkup() {
        return markup;
    }

    public void setMarkup(BigDecimal markup) {
        this.markup = markup;
    }

    public BigDecimal getCommission() {
        return commission;
    }

    public void setCommission(BigDecimal commission) {
        this.commission = commission;
    }

    public BigDecimal getSchemeFee() {
        return schemeFee;
    }

    public void setSchemeFee(BigDecimal schemeFee) {
        this.schemeFee = schemeFee;
    }

    public BigDecimal getInterchange() {
        return interchange;
    }

    public void setInterchange(BigDecimal interchange) {
        this.interchange = interchange;
    }

    public BigDecimal getOtherCreditAmt() {
        return otherCreditAmt;
    }

    public void setOtherCreditAmt(BigDecimal otherCreditAmt) {
        this.otherCreditAmt = otherCreditAmt;
    }

    public BigDecimal getOtherDebitAmt() {
        return otherDebitAmt;
    }

    public void setOtherDebitAmt(BigDecimal otherDebitAmt) {
        this.otherDebitAmt = otherDebitAmt;
    }

    public Long getCreditCount() {
        return this.creditCount;
    }

    public void setCreditCount(Long creditCount) {
        this.creditCount = creditCount;
    }

    public BigDecimal getCreditAmt() {
        return this.creditAmt;
    }

    public void setCreditAmt(BigDecimal creditAmt) {
        this.creditAmt = creditAmt;
    }

    public Timestamp getCreatedDt() {
        return this.createdDt;
    }

    public void setCreatedDt(Timestamp createdDt) {
        this.createdDt = createdDt;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Timestamp getUpdatedDt() {
        return this.updatedDt;
    }

    public void setUpdatedDt(Timestamp updatedDt) {
        this.updatedDt = updatedDt;
    }

    public String getUpdatedBy() {
        return this.updatedBy;
    }

    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public String getCompleteStatus() {
        return completeStatus;
    }

    public void setCompleteStatus(String completeStatus) {
        this.completeStatus = completeStatus;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getUploadDtString() {
        return uploadDtString;
    }

    public void setUploadDtString(String uploadDtString) {
        this.uploadDtString = uploadDtString;
    }

    public MstbAcquirer getMstbAcquirer() {
        return this.mstbAcquirer;
    }

    public void setMstbAcquirer(MstbAcquirer mstbAcquirer) {
        this.mstbAcquirer = mstbAcquirer;
    }

    public Set<TmtbNonBillableTxn> getTmtbNonBillableTxns() {
        return this.tmtbNonBillableTxns;
    }

    public void setTmtbNonBillableTxns(Set<TmtbNonBillableTxn> tmtbNonBillableTxns) {
        this.tmtbNonBillableTxns = tmtbNonBillableTxns;
    }

    public Set<BmtbBankPaymentDetail> getBmtbBankPaymentDetails() {
        return this.bmtbBankPaymentDetails;
    }

    public void setBmtbBankPaymentDetails(Set<BmtbBankPaymentDetail> bmtbBankPaymentDetails) {
        this.bmtbBankPaymentDetails = bmtbBankPaymentDetails;
    }
    
    public BigDecimal getPremiumAmount() {
		return premiumAmount;
	}

	public void setPremiumAmount(BigDecimal premiumAmount) {
		this.premiumAmount = premiumAmount;
	}

	public BigDecimal getPremiumGst() {
		return premiumGst;
	}

	public void setPremiumGst(BigDecimal premiumGst) {
		this.premiumGst = premiumGst;
	}

	/**
     * toString
     *
     * @return String
     */
    public String toString() {
        StringBuffer buffer = new StringBuffer();

        buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
        buffer.append("batchNo").append("='").append(getBatchNo()).append("' ");
        buffer.append("settlementDate").append("='").append(getSettlementDate()).append("' ");
        buffer.append("status").append("='").append(getStatus()).append("' ");
        buffer.append("mid").append("='").append(getMid()).append("' ");
        buffer.append("tid").append("='").append(getTid()).append("' ");
        buffer.append("txnCount").append("='").append(getTxnCount()).append("' ");
        buffer.append("txnAmt").append("='").append(getTxnAmt()).append("' ");
        buffer.append("refundAmt").append("='").append(getRefundAmt()).append("' ");
        buffer.append("refundReverseAmt").append("='").append(getRefundReverseAmt()).append("' ");
        buffer.append("chargebackAmt").append("='").append(getChargebackAmt()).append("' ");
        buffer.append("chargebackReverseAmt").append("='").append(getChargebackReverseAmt()).append("' ");
        buffer.append("markup").append("='").append(getMarkup()).append("' ");
        buffer.append("commission").append("='").append(getCommission()).append("' ");
        buffer.append("schemeFee").append("='").append(getSchemeFee()).append("' ");
        buffer.append("interchange").append("='").append(getInterchange()).append("' ");
        buffer.append("otherCreditAmt").append("='").append(getOtherCreditAmt()).append("' ");
        buffer.append("otherDebitAmt").append("='").append(getOtherDebitAmt()).append("' ");
        buffer.append("creditCount").append("='").append(getCreditCount()).append("' ");
        buffer.append("creditAmt").append("='").append(getCreditAmt()).append("' ");
        buffer.append("createdDt").append("='").append(getCreatedDt()).append("' ");
        buffer.append("createdBy").append("='").append(getCreatedBy()).append("' ");
        buffer.append("updatedDt").append("='").append(getUpdatedDt()).append("' ");
        buffer.append("updatedBy").append("='").append(getUpdatedBy()).append("' ");
        buffer.append("version").append("='").append(getVersion()).append("' ");
        buffer.append("completeStatus").append("='").append(getCompleteStatus()).append("' ");
        buffer.append("fileName").append("='").append(getFileName()).append("' ");
        buffer.append("uploadDt").append("='").append(getUploadDtString()).append("' ");
        buffer.append("premiumAmount").append("='").append(getPremiumAmount()).append("' ");
        buffer.append("premiumGst").append("='").append(getPremiumGst()).append("' ");
        buffer.append("]");

        return buffer.toString();
    }


    public boolean equals(Object other) {
        if ((this == other)) return true;
        if ((other == null)) return false;
        if (!(other instanceof TmtbNonBillableBatch)) return false;
        TmtbNonBillableBatch castOther = (TmtbNonBillableBatch) other;

        return ((this.getBatchId() == castOther.getBatchId()) || (this.getBatchId() != null && castOther.getBatchId() != null && this.getBatchId().equals(castOther.getBatchId())))
                && ((this.getBatchNo() == castOther.getBatchNo()) || (this.getBatchNo() != null && castOther.getBatchNo() != null && this.getBatchNo().equals(castOther.getBatchNo())))
                && ((this.getSettlementDate() == castOther.getSettlementDate()) || (this.getSettlementDate() != null && castOther.getSettlementDate() != null && this.getSettlementDate().equals(castOther.getSettlementDate())))
                && ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null && castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
                && ((this.getMid() == castOther.getMid()) || (this.getMid() != null && castOther.getMid() != null && this.getMid().equals(castOther.getMid())))
                && ((this.getTid() == castOther.getTid()) || (this.getTid() != null && castOther.getTid() != null && this.getTid().equals(castOther.getTid())))
                && (this.getTxnCount() == castOther.getTxnCount())
                && ((this.getTxnAmt() == castOther.getTxnAmt()) || (this.getTxnAmt() != null && castOther.getTxnAmt() != null && this.getTxnAmt().equals(castOther.getTxnAmt())))
                && ((this.getRefundAmt() == castOther.getRefundAmt()) || (this.getRefundAmt() != null && castOther.getRefundAmt() != null && this.getRefundAmt().equals(castOther.getRefundAmt())))
                && ((this.getRefundReverseAmt() == castOther.getRefundReverseAmt()) || (this.getRefundReverseAmt() != null && castOther.getRefundReverseAmt() != null && this.getRefundReverseAmt().equals(castOther.getRefundReverseAmt())))
                && ((this.getChargebackAmt() == castOther.getChargebackAmt()) || (this.getChargebackAmt() != null && castOther.getChargebackAmt() != null && this.getChargebackAmt().equals(castOther.getChargebackAmt())))
                && ((this.getChargebackReverseAmt() == castOther.getChargebackReverseAmt()) || (this.getChargebackReverseAmt() != null && castOther.getChargebackReverseAmt() != null && this.getChargebackReverseAmt().equals(castOther.getChargebackReverseAmt())))
                && ((this.getMarkup() == castOther.getMarkup()) || (this.getMarkup() != null && castOther.getMarkup() != null && this.getMarkup().equals(castOther.getMarkup())))
                && ((this.getCommission() == castOther.getCommission()) || (this.getCommission() != null && castOther.getCommission() != null && this.getCommission().equals(castOther.getCommission())))
                && ((this.getSchemeFee() == castOther.getSchemeFee()) || (this.getSchemeFee() != null && castOther.getSchemeFee() != null && this.getSchemeFee().equals(castOther.getSchemeFee())))
                && ((this.getInterchange() == castOther.getInterchange()) || (this.getInterchange() != null && castOther.getInterchange() != null && this.getInterchange().equals(castOther.getInterchange())))
                && ((this.getOtherCreditAmt() == castOther.getOtherCreditAmt()) || (this.getOtherCreditAmt() != null && castOther.getOtherCreditAmt() != null && this.getOtherCreditAmt().equals(castOther.getOtherCreditAmt())))
                && ((this.getOtherDebitAmt() == castOther.getOtherDebitAmt()) || (this.getOtherDebitAmt() != null && castOther.getOtherDebitAmt() != null && this.getOtherDebitAmt().equals(castOther.getOtherDebitAmt()))) && ((this.getCreditCount() == castOther.getCreditCount()) || (this.getCreditCount() != null && castOther.getCreditCount() != null && this.getCreditCount().equals(castOther.getCreditCount())))
                && ((this.getCreditAmt() == castOther.getCreditAmt()) || (this.getCreditAmt() != null && castOther.getCreditAmt() != null && this.getCreditAmt().equals(castOther.getCreditAmt())))
                && ((this.getCreatedDt() == castOther.getCreatedDt()) || (this.getCreatedDt() != null && castOther.getCreatedDt() != null && this.getCreatedDt().equals(castOther.getCreatedDt())))
                && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
                && ((this.getUpdatedDt() == castOther.getUpdatedDt()) || (this.getUpdatedDt() != null && castOther.getUpdatedDt() != null && this.getUpdatedDt().equals(castOther.getUpdatedDt())))
                && ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this.getUpdatedBy() != null && castOther.getUpdatedBy() != null && this.getUpdatedBy().equals(castOther.getUpdatedBy())))
                && ((this.getVersion() == castOther.getVersion()) || (this.getVersion() != null && castOther.getVersion() != null && this.getVersion().equals(castOther.getVersion())))
                && ((this.getCompleteStatus() == castOther.getCompleteStatus()) || (this.getCompleteStatus() != null && castOther.getCompleteStatus() != null && this.getCompleteStatus().equals(castOther.getCompleteStatus())))
                && ((this.getFileName() == castOther.getFileName()) || (this.getFileName() != null && castOther.getFileName() != null && this.getFileName().equals(castOther.getFileName())))
                && ((this.getPremiumAmount() == castOther.getPremiumAmount()) || (this.getPremiumAmount() != null && castOther.getPremiumAmount() != null && this.getPremiumAmount().equals(castOther.getPremiumAmount())))
                && ((this.getPremiumGst() == castOther.getPremiumGst()) || (this.getPremiumGst() != null && castOther.getPremiumGst() != null && this.getPremiumGst().equals(castOther.getPremiumGst())))
                && ((this.getUploadDtString() == castOther.getUploadDtString()) || (this.getUploadDtString() != null && castOther.getUploadDtString() != null && this.getUploadDtString().equals(castOther.getUploadDtString())));
//                && ((this.getMstbAcquirer() == castOther.getMstbAcquirer()) || (this.getMstbAcquirer() != null && castOther.getMstbAcquirer() != null && this.getMstbAcquirer().equals(castOther.getMstbAcquirer())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getBatchId() == null ? 0 : this.getBatchId().hashCode());
        result = 37 * result + (getBatchNo() == null ? 0 : this.getBatchNo().hashCode());
        result = 37 * result + (getSettlementDate() == null ? 0 : this.getSettlementDate().hashCode());
        result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
        result = 37 * result + (getMid() == null ? 0 : this.getMid().hashCode());
        result = 37 * result + (getTid() == null ? 0 : this.getTid().hashCode());
        result = 37 * result + (int) this.getTxnCount();
        result = 37 * result + (getTxnAmt() == null ? 0 : this.getTxnAmt().hashCode());
        result = 37 * result + (getRefundAmt() == null ? 0 : getRefundAmt().hashCode());
        result = 37 * result + (getRefundReverseAmt() == null ? 0 : getRefundReverseAmt().hashCode());
        result = 37 * result + (getChargebackAmt() == null ? 0 : getChargebackAmt().hashCode());
        result = 37 * result + (getChargebackReverseAmt() == null ? 0 : getChargebackReverseAmt().hashCode());
        result = 37 * result + (getMarkup() == null ? 0 : getMarkup().hashCode());
        result = 37 * result + (getCommission() == null ? 0 : getCommission().hashCode());
        result = 37 * result + (getSchemeFee() == null ? 0 : getSchemeFee().hashCode());
        result = 37 * result + (getInterchange() == null ? 0 : getInterchange().hashCode());
        result = 37 * result + (getOtherCreditAmt() == null ? 0 : getOtherCreditAmt().hashCode());
        result = 37 * result + (getOtherDebitAmt() == null ? 0 : getOtherDebitAmt().hashCode());
        result = 37 * result + (getCreditCount() == null ? 0 : this.getCreditCount().hashCode());
        result = 37 * result + (getCreditAmt() == null ? 0 : this.getCreditAmt().hashCode());
        result = 37 * result + (getCreatedDt() == null ? 0 : this.getCreatedDt().hashCode());
        result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
        result = 37 * result + (getUpdatedDt() == null ? 0 : this.getUpdatedDt().hashCode());
        result = 37 * result + (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
        result = 37 * result + (getVersion() == null ? 0 : this.getVersion().hashCode());
        result = 37 * result + (getCompleteStatus() == null ? 0 : this.getCompleteStatus().hashCode());
        result = 37 * result + (getFileName() == null ? 0 : this.getFileName().hashCode());
        result = 37 * result + (getUploadDtString() == null ? 0 : this.getUploadDtString().hashCode());
        result = 37 * result + (getPremiumAmount() == null ? 0 : this.getPremiumAmount().hashCode());
        result = 37 * result + (getPremiumGst() == null ? 0 : this.getPremiumGst().hashCode());
//         result = 37 * result + ( getMstbAcquirer() == null ? 0 : this.getMstbAcquirer().hashCode() );

        return result;
    }

}
