SET PAGES 5000
SET LINE  10000
SET TRIMSPOOL ON
set echo on

column dt new_value new_dt 
column ext new_value new_ext
select  sys_context('userenv','instance_name') || '_julIssueLogs_dml_' || to_char(sysdate,'YYYYMMDDHH24MISS') dt,'.txt' ext from dual;
SPOOL  &new_dt&new_ext
set define off
alter session set current_schema=ibssys;



/*-- 12/07/2021  CR HLA START */


--Alter existing table to add new HLA fields
ALTER TABLE RCVW_INTF_SETL_FOR_IBS
ADD(POLICY_NUMBER VARCHAR2(80),
START_OF_INSURANCE DATE,
END_OF_INSURANCE DATE,
PREMIUM_AMOUNT NUMBER,
PREMIUM_GST NUMBER,
POLICY_STATUS VARCHAR2(1));


COMMENT ON COLUMN RCVW_INTF_SETL_FOR_IBS.POLICY_NUMBER IS 'Policy Number of Insurance';
COMMENT ON COLUMN RCVW_INTF_SETL_FOR_IBS.START_OF_INSURANCE IS 'Start Date of Insurace';
COMMENT ON COLUMN RCVW_INTF_SETL_FOR_IBS.END_OF_INSURANCE IS 'End Date of Insurance';
COMMENT ON COLUMN RCVW_INTF_SETL_FOR_IBS.PREMIUM_AMOUNT IS 'Insurance Premium Amount';
COMMENT ON COLUMN RCVW_INTF_SETL_FOR_IBS.PREMIUM_GST IS 'Insurance GST Amount';
COMMENT ON COLUMN RCVW_INTF_SETL_FOR_IBS.POLICY_STATUS IS 'Insurance Policy Status A=Active, C=Cancelled, M=Manual Cancel';


ALTER TABLE ITTB_SETL_TXN
ADD(POLICY_NUMBER VARCHAR2(80),
START_OF_INSURANCE DATE,
END_OF_INSURANCE DATE,
PREMIUM_AMOUNT NUMBER,
PREMIUM_GST NUMBER,
POLICY_STATUS VARCHAR2(1));



COMMENT ON COLUMN ITTB_SETL_TXN.POLICY_NUMBER IS 'Policy Number of Insurance';
COMMENT ON COLUMN ITTB_SETL_TXN.START_OF_INSURANCE IS 'Start Date of Insurace';
COMMENT ON COLUMN ITTB_SETL_TXN.END_OF_INSURANCE IS 'End Date of Insurance';
COMMENT ON COLUMN ITTB_SETL_TXN.PREMIUM_AMOUNT IS 'Insurance Premium Amount';
COMMENT ON COLUMN ITTB_SETL_TXN.PREMIUM_GST IS 'Insurance GST Amount';
COMMENT ON COLUMN ITTB_SETL_TXN.POLICY_STATUS IS 'Insurance Policy Status A=Active, C=Cancelled, M=Manual Cancel';



ALTER TABLE TMTB_NON_BILLABLE_TXN
ADD(POLICY_NUMBER VARCHAR2(80),
START_OF_INSURANCE DATE,
END_OF_INSURANCE DATE,
PREMIUM_AMOUNT NUMBER,
PREMIUM_GST NUMBER,
POLICY_STATUS VARCHAR2(1));



COMMENT ON COLUMN TMTB_NON_BILLABLE_TXN.POLICY_NUMBER IS 'Policy Number of Insurance';
COMMENT ON COLUMN TMTB_NON_BILLABLE_TXN.START_OF_INSURANCE IS 'Start Date of Insurace';
COMMENT ON COLUMN TMTB_NON_BILLABLE_TXN.END_OF_INSURANCE IS 'End Date of Insurance';
COMMENT ON COLUMN TMTB_NON_BILLABLE_TXN.PREMIUM_AMOUNT IS 'Insurance Premium Amount';
COMMENT ON COLUMN TMTB_NON_BILLABLE_TXN.PREMIUM_GST IS 'Insurance GST Amount';
COMMENT ON COLUMN TMTB_NON_BILLABLE_TXN.POLICY_STATUS IS 'Insurance Policy Status A=Active, C=Cancelled, M=Manual Cancel';




ALTER TABLE TMTB_NON_BILLABLE_BATCH
ADD(PREMIUM_AMOUNT NUMBER,
PREMIUM_GST NUMBER);

COMMENT ON COLUMN TMTB_NON_BILLABLE_BATCH.PREMIUM_AMOUNT IS 'Insurance Premium Amount';
COMMENT ON COLUMN TMTB_NON_BILLABLE_BATCH.PREMIUM_GST IS 'Insurance GST Amount';



/*-- 12/07/2021  CR HLA  END */




spool off