--WILSON: VIEW INVOICE
-- Add Note Reason
-- Add Cancellation Reason
ALTER TABLE "BMTB_NOTE"
ADD (
    REASON NUMBER(8,0),
	CANCELLATION_REASON NUMBER(8,0),
	CONSTRAINT "BMTB_NOTE_FK5" FOREIGN KEY ("REASON")
	  REFERENCES "MSTB_MASTER_TABLE" ("MASTER_NO") ENABLE, 
	CONSTRAINT "BMTB_NOTE_FK6" FOREIGN KEY ("CANCELLATION_REASON")
	  REFERENCES "MSTB_MASTER_TABLE" ("MASTER_NO") ENABLE
);
--END
-- added old account no for account
alter table amtb_account add OLD_ACCOUNT_NO varchar2(25);

-- WILSON:  NOTE STATUS
ALTER TABLE "BMTB_NOTE"
ADD (
    STATUS VARCHAR2(1)
);
COMMENT ON COLUMN BMTB_NOTE.STATUS IS 'P = PENDING, B = BILLED, C = CANCELLED';
-- increasing audit log value length
alter table SATB_AUDIT_LOG modify NEW_VALUE varchar(2048);
alter table SATB_AUDIT_LOG modify OLD_VALUE varchar(2048);

--SENGTAT: TRIP BASED NOTE
ALTER TABLE "BMTB_NOTE"
ADD (
	ISSUED_INVOICE_TXN_NO NUMBER(18,0),
	CONSTRAINT "BMTB_NOTE_FK7" FOREIGN KEY ("ISSUED_INVOICE_TXN_NO")
	  REFERENCES "BMTB_INVOICE_TXN" ("INVOICE_TXN_NO") ENABLE
);
CREATE INDEX "BMTB_NOTE_N5" ON BMTB_NOTE(ISSUED_INVOICE_TXN_NO);
--END


-- WILSON: ISSUE CREDIT/DEBIT NOTE
UPDATE "SATB_RESOURCE" SET URI = '/billing/note/search_invoice_for_issue_note.zul' WHERE RSRC_ID = 26;
UPDATE "SATB_RESOURCE" SET DISPLAY_NAME = 'View Credit/Debit Note' WHERE RSRC_NAME = 'Search Note';
UPDATE "SATB_RESOURCE" SET DISPLAY = 'N' WHERE RSRC_NAME = 'Manage Credit/Debit Note';

INSERT INTO "SATB_RESOURCE" (RSRC_ID, PAR_RSRC_ID, RSRC_NAME, RSRC_TYPE, URI, SEQUENCE, DISPLAY_NAME, DISPLAY, VERSION)
VALUES ((SELECT MAX(RSRC_ID)+1 FROM "SATB_RESOURCE"), '29', 'Issue Note', 'U', '/billing/note/issue_note.zul', '6', 'Issue Credit/Debit Note', 'N', '0');
INSERT INTO "SATB_ROLE_RESOURCE" (ROLE_ID, RSRC_ID)
VALUES(2, (SELECT MAX(RSRC_ID) FROM "SATB_RESOURCE"));

INSERT INTO "SATB_RESOURCE" (RSRC_ID, PAR_RSRC_ID, RSRC_NAME, RSRC_TYPE, URI, SEQUENCE, DISPLAY_NAME, DISPLAY, VERSION)
VALUES ((SELECT MAX(RSRC_ID)+1 FROM "SATB_RESOURCE"), '29', 'Search Note', 'U', '/billing/note/search_note.zul', '7', 'Cancel Credit/Debit Note', 'Y', '0');
INSERT INTO "SATB_ROLE_RESOURCE" (ROLE_ID, RSRC_ID)
VALUES(2, (SELECT MAX(RSRC_ID) FROM "SATB_RESOURCE"));

INSERT INTO "SATB_RESOURCE" (RSRC_ID, PAR_RSRC_ID, RSRC_NAME, RSRC_TYPE, URI, SEQUENCE, DISPLAY_NAME, DISPLAY, VERSION)
VALUES ((SELECT MAX(RSRC_ID)+1 FROM "SATB_RESOURCE"), '29', 'View Note', 'U', '/billing/note/view_note.zul', '8', 'View Credit/Debit Note', 'N', '0');
INSERT INTO "SATB_ROLE_RESOURCE" (ROLE_ID, RSRC_ID)
VALUES(2, (SELECT MAX(RSRC_ID) FROM "SATB_RESOURCE"));
UPDATE "SATB_RESOURCE" SET DISPLAY_NAME = 'View Credit/Debit Note' WHERE RSRC_NAME = 'Search Note';
UPDATE "SATB_RESOURCE" SET DISPLAY = 'N' WHERE RSRC_NAME = 'Manage Credit/Debit Note';

INSERT INTO "SATB_RESOURCE" (RSRC_ID, PAR_RSRC_ID, RSRC_NAME, RSRC_TYPE, URI, SEQUENCE, DISPLAY_NAME, DISPLAY, VERSION)
VALUES ((SELECT MAX(RSRC_ID)+1 FROM "SATB_RESOURCE"), '29', 'Cancel Note', 'U', '/billing/note/cancel_note.zul', '9', 'Cancel Credit/Debit Note', 'N', '0');
INSERT INTO "SATB_ROLE_RESOURCE" (ROLE_ID, RSRC_ID)
VALUES(2, (SELECT MAX(RSRC_ID) FROM "SATB_RESOURCE"));

alter table "FMTB_TRANSACTION_CODE" modify ( "TXN_CODE" VARCHAR2(10) );
alter table "FMTB_TRANSACTION_CODE" modify ( "DESCRIPTION" VARCHAR2(60) );
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(1,'1','CC','TFCOC','CORPORATE CARD - TAXI FARE','FA','308301','BCCACCA0','N','','',DATE '2009-01-01',46,0,'N');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(2,'1','CC','AFCOC','CORPORATE CARD - ADMIN FEE','AF','308300','BCCACCA0','Y','365912','BCCACCA0',DATE '2009-01-01',45,0,'N');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(3,'1','PC','TFPEC','PERSONAL CARD - TAXI FARE','FA','308313','BCCACCA0','N','','',DATE '2009-01-01',46,0,'N');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(4,'1','PC','AFPEC','PERSONAL CARD - ADMIN FEE','AF','308314','BCCACCA0','Y','365914','BCCACCA0',DATE '2009-01-01',45,0,'N');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(5,'1','HC','TFHOC','HOTEL CARD - TAXI FARE','FA','308317','BCCACCA0','N','','',DATE '2009-01-01',46,0,'N');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(6,'1','HC','AFHOC','HOTEL CARD - ADMIN FEE','AF','308318','BCCACCA0','Y','365918','BCCACCA0',DATE '2009-01-01',45,0,'N');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(7,'1','OV','TFOVEV','OPEN-VALUE E-VOUCHER - TAXI FARE','FA','308321','BCCACCA0','N','','',DATE '2009-01-01',46,0,'N');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(8,'1','OV','AFOVEV','OPEN-VALUE E-VOUCHER - ADMIN FEE','AF','308322','BCCACCA0','Y','365922','BCCACCA0',DATE '2009-01-01',45,0,'N');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(9,'1','FV','TFFVEV','FIXED-VALUE E-VOUCHER - TAXI FARE','FA','308325','BCCACCA0','N','','',DATE '2009-01-01',46,0,'N');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(10,'1','FV','AFFVEV','FIXED-VALUE E-VOUCHER - ADMIN FEE','AF','308326','BCCACCA0','Y','365926','BCCACCA0',DATE '2009-01-01',45,0,'N');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(11,'1','MS','TFFVCV','FIXED-VALUE CASH VOUCHER ($5, $10)  - TAXI FARE','FA','308329','BCCACCA0','N','','',DATE '2009-01-01',46,0,'Y');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(12,'1','MS','AFFVCV','FIXED-VALUE CASH VOUCHER ($5, $10) - ADMIN FEE','AF','308330','BCCACCA0','Y','365930','BCCACCA0',DATE '2009-01-01',45,0,'Y');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(13,'1','PS','TFPRMS','PREMIER SERVICE - TAXI FARE','FA','308430','BCCACCA0','N','','',DATE '2009-01-01',46,0,'N');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(14,'1','PS','AFPRMS','PREMIER SERVICE - ADMIN FEE','AF','308334','BCCACCA0','Y','365934','BCCACCA0',DATE '2009-01-01',45,0,'N');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(15,'1','','DEPAYT','EARLY PAYMENT DISCOUNTS','EP','442400','BCCACCA0','N','','',DATE '2009-01-01',45,0,'Y');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(16,'1','','ILATEP','INTEREST FOR LATE PAYMENT','LP','311315','BCCACCA0','N','','',DATE '2009-01-01',46,0,'Y');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(17,'1','','VOLDIS','VOLUME DISCOUNT','VD','0','XXXXXXXX','N','','',DATE '2009-01-01',45,0,'Y');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(18,'1','','PRODIS','PROMOTION DISCOUNT','PD','0','XXXXXXXX','N','','',DATE '2009-01-01',46,0,'Y');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(19,'1','','CRPLFEE','CARD REPLACEMENT FEE','RF','369100','BCCACCA0','N','','',DATE '2009-01-01',45,0,'Y');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(20,'1','','SUBFEE','SUBSCRIPTION FEE','SF','0','XXXXXXXX','N','','',DATE '2009-01-01',45,0,'Y');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(21,'1','','DEPOSIT','DEPOSIT','DP','0','XXXXXXXX','N','','',DATE '2009-01-01',46,0,'N');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(22,'1','','MISCEG','MISCELLANEOUS - GST','MS','0','XXXXXXXX','N','','',DATE '2009-01-01',45,0,'Y');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(23,'1','','MISCE','MISCELLANEOUS – NON GST','MS','0','XXXXXXXX','N','','',DATE '2009-01-01',46,0,'Y');
INSERT INTO FMTB_TRANSACTION_CODE (TRANSACTION_CODE_NO, ENTITY_NO, PRODUCT_TYPE_ID, TXN_CODE, DESCRIPTION, TXN_TYPE, GL_CODE, COST_CENTRE, DISCOUNTABLE, DISCOUNT_GL_CODE, DISCOUNT_COST_CENTRE, EFFECTIVE_DATE, TAX_TYPE, VERSION, IS_MANUAL) VALUES(24,'1','','CONTRA','CONTRA \& CLEARING','MS','0','XXXXXXXX','N','','',DATE '2009-01-01',46,0,'N');
DROP SEQUENCE  "FMTB_TRANSACTION_CODE_SQ1";
CREATE SEQUENCE  "FMTB_TRANSACTION_CODE_SQ1"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 25 CACHE 10 NOORDER  NOCYCLE ;
 
alter table "FMTB_TAX_CODE" modify ( "COST_CENTRE" VARCHAR2(10) );
INSERT INTO FMTB_TAX_CODE (TAX_CODE_NO, ENTITY_NO, GL_TAX_CODE, GL_CODE, COST_CENTRE, TAX_TYPE, TAX_RATE, EFFECTIVE_DATE, VERSION) VALUES(1,1,'S0','249100','BCCACCA0',46,0,DATE '1994-01-01',0);
INSERT INTO FMTB_TAX_CODE (TAX_CODE_NO, ENTITY_NO, GL_TAX_CODE, GL_CODE, COST_CENTRE, TAX_TYPE, TAX_RATE, EFFECTIVE_DATE, VERSION) VALUES(2,1,'S3','249100','BCCACCA0',45,3,DATE '1994-01-01',0);
INSERT INTO FMTB_TAX_CODE (TAX_CODE_NO, ENTITY_NO, GL_TAX_CODE, GL_CODE, COST_CENTRE, TAX_TYPE, TAX_RATE, EFFECTIVE_DATE, VERSION) VALUES(3,1,'S4','249100','BCCACCA0',45,4,DATE '2003-01-01',0);
INSERT INTO FMTB_TAX_CODE (TAX_CODE_NO, ENTITY_NO, GL_TAX_CODE, GL_CODE, COST_CENTRE, TAX_TYPE, TAX_RATE, EFFECTIVE_DATE, VERSION) VALUES(4,1,'S5','249100','BCCACCA0',45,5,DATE '2004-01-01',0);
INSERT INTO FMTB_TAX_CODE (TAX_CODE_NO, ENTITY_NO, GL_TAX_CODE, GL_CODE, COST_CENTRE, TAX_TYPE, TAX_RATE, EFFECTIVE_DATE, VERSION) VALUES(5,1,'S7','249100','BCCACCA0',45,7,DATE '2007-07-01',0);
INSERT INTO FMTB_TAX_CODE (TAX_CODE_NO, ENTITY_NO, GL_TAX_CODE, GL_CODE, COST_CENTRE, TAX_TYPE, TAX_RATE, EFFECTIVE_DATE, VERSION) VALUES(6,1,'SS','249100','BCCACCA0',48,0,DATE '1994-01-01',0);
INSERT INTO FMTB_TAX_CODE (TAX_CODE_NO, ENTITY_NO, GL_TAX_CODE, GL_CODE, COST_CENTRE, TAX_TYPE, TAX_RATE, EFFECTIVE_DATE, VERSION) VALUES(7,1,'SE','249100','BCCACCA0',47,0,DATE '1994-01-01',0);
DROP SEQUENCE  "FMTB_TAX_CODE_SQ1";
CREATE SEQUENCE  "FMTB_TAX_CODE_SQ1"  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 8 CACHE 10 NOORDER  NOCYCLE ;

Insert into MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) values (83,'NR','GST',null,'WRONG GST AMOUNT','A',0);
Insert into MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) values (84,'NR','RS1',null,'REASON 1','A',0);
Insert into MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) values (85,'NR','RS2',null,'REASON 2','A',0);
Insert into MSTB_MASTER_TABLE (MASTER_NO,MASTER_TYPE,MASTER_CODE,INTERFACE_MAPPING_VALUE,MASTER_VALUE,MASTER_STATUS,VERSION) values (86,'NR','RS3',null,'REASON 3','A',0);

-- END

-- WILSON: ISSUE MISC INVOICE
INSERT INTO "SATB_RESOURCE" (RSRC_ID, PAR_RSRC_ID, RSRC_NAME, RSRC_TYPE, URI, SEQUENCE, DISPLAY_NAME, DISPLAY, VERSION)
VALUES ((SELECT MAX(RSRC_ID)+1 FROM "SATB_RESOURCE"), '29', 'Search Account', 'U', '/billing/invoice/search_account_for_issue_misc_invoice.zul', '10', 'Issue Misc. Account', 'Y', '0');
INSERT INTO "SATB_ROLE_RESOURCE" (ROLE_ID, RSRC_ID)
VALUES(2, (SELECT MAX(RSRC_ID) FROM "SATB_RESOURCE"));

INSERT INTO "SATB_RESOURCE" (RSRC_ID, PAR_RSRC_ID, RSRC_NAME, RSRC_TYPE, URI, SEQUENCE, DISPLAY_NAME, DISPLAY, VERSION)
VALUES ((SELECT MAX(RSRC_ID)+1 FROM "SATB_RESOURCE"), '29', 'Issue Misc. Invoice', 'U', '/billing/invoice/issue_misc_invoice.zul', '11', 'Issue Misc. Invoice', 'N', '0');
INSERT INTO "SATB_ROLE_RESOURCE" (ROLE_ID, RSRC_ID)
VALUES(2, (SELECT MAX(RSRC_ID) FROM "SATB_RESOURCE"));
-- END
-- for account transfer request
alter table AMTB_ACCT_SALESPERSON_REQ add USER_ID NUMBER(10);
update AMTB_ACCT_SALESPERSON_REQ set USER_ID = 2;
alter table AMTB_ACCT_SALESPERSON_REQ modify USER_ID not null;
alter table AMTB_ACCT_SALESPERSON_REQ add CONSTRAINT AMTB_ACCT_SALESPERSON_REQ_FK3 FOREIGN KEY(USER_ID) REFERENCES SATB_USER(USER_ID) enable;
-- for contact main email
alter table AMTB_CONTACT_PERSON modify MAIN_CONTACT_EMAIL null;
alter table AMTB_CONTACT_PERSON modify MAIN_CONTACT_TITLE null;
-- to remove incorporate date
alter table AMTB_APPLICATION drop COLUMN INCORPORATION_DT;
alter table AMTB_CORPORATE_DETAIL drop COLUMN CORPORATION_DT;