drop table FMTB_PAYMENT_MODE;
drop table FMTB_ENTITY_CODE;
alter table FMTB_AR_CONT_CODE_MASTER drop column BANK_ACCOUNT_NO;
alter table FMTB_AR_CONT_CODE_MASTER drop column BANK_ACCOUNT_NAME;
alter table FMTB_AR_CONT_CODE_MASTER drop column BRANCH;
alter table FMTB_AR_CONT_CODE_MASTER drop column USED_FOR;
alter table FMTB_AR_CONT_CODE_MASTER drop column GL_ACCOUNT;
alter table FMTB_AR_CONT_CODE_MASTER drop column COST_CENTRE;
alter table FMTB_AR_CONT_CODE_MASTER drop column END_DT;
alter table FMTB_BANK_CODE modify TAX_TYPE null;
update fmtb_bank_code set TAX_TYPE = null
alter table FMTB_BANK_CODE modify TAX_TYPE number(8);
alter table FMTB_BANK_CODE add CONSTRAINT FMTB_BANK_CODE_FK2 FOREIGN KEY(TAX_TYPE) REFERENCES MSTB_MASTER_TABLE(MASTER_NO) enable;
CREATE INDEX FMTB_BANK_CODE_N2 ON FMTB_BANK_CODE (TAX_TYPE);
-- creating seq for AR CONTROL CODE --
CREATE SEQUENCE  "FMTB_AR_CONT_CODE_DETAIL_SQ1"  MINVALUE 1 MAXVALUE 99999999 INCREMENT BY 1 START WITH 3 CACHE 10 NOORDER  NOCYCLE ;
-- AR CONTROL CODE TABLE --
CREATE TABLE FMTB_AR_CONT_CODE_DETAIL (
	AR_CONT_CODE_DETAIL_NO NUMBER(8) NOT NULL,
	AR_CONTROL_CODE_NO NUMBER(8) NOT NULL,
	GL_ACCOUNT NUMBER(8) NOT NULL,
	COST_CENTRE VARCHAR2(80) NOT NULL,
	TAX_TYPE NUMBER(8),
	DESCRIPTION VARCHAR2(60) NOT NULL,
	EFFECTIVE_DT TIMESTAMP,
	VERSION NUMBER(9,0) DEFAULT 0,
	CONSTRAINT FMTB_AR_CONT_CODE_DETAIL_FK1 FOREIGN KEY(AR_CONTROL_CODE_NO) REFERENCES FMTB_AR_CONT_CODE_MASTER(AR_CONTROL_CODE_NO),
	CONSTRAINT FMTB_AR_CONT_CODE_DETAIL_FK2 FOREIGN KEY(TAX_TYPE) REFERENCES MSTB_MASTER_TABLE(MASTER_NO),
	CONSTRAINT FMTB_AR_CONT_CODE_DETAIL_PK PRIMARY KEY(AR_CONT_CODE_DETAIL_NO)
);
-- creating indexes --
CREATE INDEX FMTB_AR_CONT_CODE_DETAIL_N1 ON FMTB_AR_CONT_CODE_DETAIL (AR_CONTROL_CODE_NO);
CREATE INDEX FMTB_AR_CONT_CODE_DETAIL_N2 ON FMTB_AR_CONT_CODE_DETAIL (TAX_TYPE);
-- dumping some data into it
INSERT INTO FMTB_AR_CONT_CODE_DETAIL
	(AR_CONT_CODE_DETAIL_NO, AR_CONTROL_CODE_NO, GL_ACCOUNT, COST_CENTRE, TAX_TYPE, DESCRIPTION, EFFECTIVE_DT)
VALUES
	(1,1,1,1,NULL, 'VICOM', TO_TIMESTAMP('01/01/2009','dd/mm/yyyy'));