alter table RCVW_INTF_TRIPS_FOR_IBS add FLIGHT_DETAILS varchar2(20);
alter table RCVW_INTF_TRIPS_FOR_IBS add AGENT_NAME varchar2(80);
CREATE OR REPLACE VIEW VW_INTF_TRIPS_FOR_IBS AS
	SELECT "TRIP_INTF_PK","JOB_NO","VEHICLE_NO","DRIVER_IC","ENTITY","BOOKED_CHANNEL","BOOKED_DATE_TIME",
		"BOOKED_VEHICLE_GROUP","PAX_NAME","BOOKING_REFERENCE","TRIP_START","TRIP_END","PICKUP","DESTINATION",
		"JOB_TYPE","JOB_STATUS","PAX_PRIVILEGE","PRODUCT_ID","PRODUCT","PAYMENT_MODE","ACCOUNT_LV1",
		"ACCOUNT_LV2","CARD_NO","APPROVAL_CODE","GST_INCLUSIVE","TXN_AMOUNT","BOOKING_FEE","ADMIN_AMOUNT",
		"GST_AMOUNT","TOTAL_AMOUNT","DRIVER_LEVY","MERIT_POINT_FEE","SURCHARGE_DESCRIPTION","CHARGED_TO",
		"COMPLIMENTARY","STATUS","FMS_STATUS","FMS_DATE","CREATE_BY","CREATE_DATE","LAST_UPDATE_BY",
		"LAST_UPDATE_DATE","SERVICE_TYPE","ACCOUNT_LV3","ACCOUNT_LV1_NAME","ACCOUNT_LV2_NAME","ACCOUNT_LV3_NAME",
		"BOOKED_BY","ERROR_CODE","FLOWTHRU_ACTION","FLOWTHRU_BY","FLOWTHRU_DT","FLOWTHRU_COMMENTS","TID",
		"CANCEL_REASON_CODE","CANCEL_REASON_DESC","SURCHARGE_BREAKDOWN","TRIP_INTF_REF","REFUND","CARD_TYPE",
		"SETL_DATE","BANK_TID","BANK_BATCH_CLOSE_NO","COMPLETED_DT","SALES_DRAFT_NO","RECON_DATE","SCENARIO",
		"IBS_STATUS","IBS_ERROR_CODE","IBS_DATE","FLIGHT_DETAILS","AGENT_NAME"
	FROM RCVW_INTF_TRIPS_FOR_IBS;