insert into MSTB_REPORT_FORMAT_MAP
select NVL(MAX(MAP_NO),0)+1 MAP_NO, MAX(RSRC_ID) RSRC_ID, UPPER('PDF')
from
(
    select max(MAP_NO) as MAP_NO, null as RSRC_ID
    from MSTB_REPORT_FORMAT_MAP MAP
    union
    select null as MAP_NO, RSRC.RSRC_ID
    from SATB_RESOURCE RSRC
    where upper(RSRC_NAME) = upper('Customer Aging Summary')
) temp;

insert into MSTB_REPORT_FORMAT_MAP
select NVL(MAX(MAP_NO),0)+1 MAP_NO, MAX(RSRC_ID) RSRC_ID, UPPER('PDF')
from
(
    select max(MAP_NO) as MAP_NO, null as RSRC_ID
    from MSTB_REPORT_FORMAT_MAP MAP
    union
    select null as MAP_NO, RSRC.RSRC_ID
    from SATB_RESOURCE RSRC
    where upper(RSRC_NAME) = upper('Customer Aging Detail')
) temp;

ALTER TABLE BMTB_INVOICE_HEADER
ADD (
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP
);

ALTER TABLE BMTB_INVOICE_FILE
ADD (
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP
);

ALTER TABLE BMTB_INVOICE_SUMMARY
ADD (
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP
);

ALTER TABLE BMTB_INVOICE_DETAIL
ADD (
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP
);

ALTER TABLE BMTB_INVOICE_TXN
ADD (
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP
);

ALTER TABLE BMTB_INVOICE_PAYMENT_HEADER
ADD (
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP
);

ALTER TABLE BMTB_INVOICE_PAYMENT_DETAIL
ADD (
  CREATED_BY VARCHAR2(80),
  CREATED_DT TIMESTAMP,
  UPDATED_BY VARCHAR2(80),
  UPDATED_DT TIMESTAMP
);

